### ISSUE TITLE
With SQLite database whereBetween on date field skipping start date

### ISSUE THREAD

**Issue by ajaxray** [laravel/framework#10006]
If I use `whereBetween` with a SQLite Database, it's not including the start date even if matching row exists. Using the following code (`$weekStart` and `$weekEnd` is php `\DateTime` object)
```->whereBetween('date', [$weekStart, $weekEnd])```
the rows where date (e,g, `2015-08-15`) is same to 'Y-m-d' of `$weekStart` are being skipped. But it's working with same data and same code when using MySql

**Comment by jairovsky** [comment]
Let's consider this snippet:
```php
$rangeStart = new DateTime('2014-02-13');
$rangeEnd = new DateTime('2015-05-15');

Post::whereBetween('published_at', [$rangeStart, $rangeEnd])->get();
```

The code above generates the following SQL query:
```sql
select * from "posts" where "published_at" between '2014-02-13 00:00:00' and '2015-05-15 00:00:00'
```
The problem here is that `date` type parameters are being formatted using `datetime` format <br>`Y-m-d H:i:s`, and SQLite will make you mad when you use `datetime` ranges on `date` column queries.

Now, why is Laravel using `Y-m-d H:i:s` format **even if our column has type `date`**?

Let's look at [`Illuminate\Database\Query\Grammars\Grammar`](https://github.com/illuminate/database/blob/5292833ddb13f86b22370ca2abaa97bffc7da64a/Grammar.php#L161) class:
```php
public function getDateFormat()
{
    return 'Y-m-d H:i:s';
}
```

This is the default date format, since `Grammar` is the parent class for all SQL grammars.

Now, if we look at **[`SQLiteGrammar`](https://github.com/illuminate/database/blob/dc7ca8c3de49a14ffdf4a92aaab9466ec514738d/Query/Grammars/SQLiteGrammar.php)**'s source code...

It doesn't override the `getDateFormat()` method! So SQLiteGrammar will inherit the the `Y-m-d H:i:s` formatting style.

The quickest solution for you is to format the parameters by yourself:

```php
$rangeStartString = $rangeStart->format('Y-m-d');
$rangeEndString = $rangeEnd->format('Y-m-d');

Post::whereBetween('published_at', [$rangeStartString, $rangeEndString])->get();
```

**Comment by ajaxray** [comment]
@jairovsky ,
Thanks a lot for your detail explanation :)

Actually I was using sqlite for unit testing and it was failing because of this situation. And that really made me mad for couple of hours. Later discovered this matter and instead of fixing it for sqlite, started using MySql for testing as application itself is using MySql too.

However, thank you again :+1:
