### ISSUE TITLE
[5.1] Blade "or" Syntax Issue

### ISSUE THREAD

**Issue by khninethree** [laravel/framework#10135]
It seems as if the blade or syntax is causing an issue using a variable and a function:

eg:
`{!! $form->text('search', null, ['placeholder' => 'this or that']) !!}`

Is being compiled into:
`<?php echo isset($form->text('search', null, ['placeholder' => 'this) ? $form->text('search', null, ['placeholder' => 'this : that']); ?>`

It seems this only happens if a variable is used, when using:
`{!! Form::text('search', null, ['placeholder' => 'this or that']) !!}`

The syntax is formatted cleanly.

**Comment by GrahamCampbell** [comment]
Sorry, yeh, we're aware of this issue. We marked it as a nofix. The or syntax is limited. We're open to good PR fixes though. :)

**Comment by khninethree** [comment]
Probably smart not to implement something that completely breaks functionality, I disabled it given that it doesn't work.

**Comment by cryode** [comment]
I played around with this for a while this morning, because it sounded like a fun challenge. This is a *very* difficult thing to implement with full compliancy to all the edge cases I could come up with. In the end, there are three possible solutions I could come up with, each with varying complexity:

1. Use a unique symbol to indicate the "or", rather than just the word itself. Example:

        {{ $username L_OR 'Guest' }}

  Not exactly the best looking, but makes finding the exact split point very easy. Biggest con with this solution is the possibility of someone wanting to use `L_OR` in their string. Not common, but then again edge cases are why we're developers. This solution would be the most performant.

2. Replace content temporarily in order to determine where the real "or" lives. This means any strings can be ignored and replaced with placeholders while we search for the real "or". This is from a limitation in regular expressions (or at least a limitation in my knowledge of them) -- while I found a way to replace a single "or" that lived inside a string with a placeholder, I couldn't find a way to replace multiples inside of the *same* string using regex.

3. Parse the text inside the curly braces into tokens, and find "or" which would be considered a constant by the tokenizer. I'd consider this the most stable solution of the three, but requires a much larger dependency and is likely the slowest solution.

At the end of the day, this feature is something I'd drop entirely from the framework at some point, which is probably the conclusion Taylor & co. have already come to.

As a temporary solution to @khninethree's problem, you could modify the current regex to look for a more specific format when replacing "or" -- specifically, the " or " must be followed by the start of a variable (`$`) or the start of a quoted string.

    ^(\$.+?)(?:\s+or\s+)([\$'"].+?)$

This would be a breaking change for any apps that use a constant/class/function as the default, so not something I'd suggest overall.

**Comment by cryode** [comment]
Or, actually, a fourth solution would be to use the [isset() ternary coalesce operator](https://wiki.php.net/rfc/isset_ternary) that is in PHP 7. Blade could support the syntax through `preg_replace()` for older versions of PHP by doing the same thing as `or` currently, but with fewer side effects.

Perhaps the next version of Laravel could provide this functionality, and deprecate the `or` syntax. Eventually Laravel wouldn't even need to support it internally, whenever its minimum requirements are >= PHP 7.

**Comment by rkgrep** [comment]
PHP 7 has a null coalescing operator (`??`). Maybe it makes sense to change `or` to `??` and use native PHP 7 feature where possible? So this bug will only be present in PHP 5.

**Comment by GrahamCampbell** [comment]
> So this bug will only be present in PHP 5.

No, because blade still will try to match ` or ` on all systems...

**Comment by rkgrep** [comment]
@GrahamCampbell I meant to replace `or` with `??` in blade syntax. However found a closed PR on that, so never mind.

**Comment by GrahamCampbell** [comment]
> I meant to replace or with ?? in blade syntax. However found a closed PR on that, so never mind.

The bug is that laravel matches that syntax incorrectly when people didn't even want to use it.

**Comment by rkgrep** [comment]
Yes, and if the syntax will be changed to `??` - it shouldn't be matched in PHP 7 at all.

**Comment by GrahamCampbell** [comment]
I'd saying we remove it, not that we change it.

**Comment by GrahamCampbell** [comment]
PHP can parse that correctly. We failed at it.
