### ISSUE TITLE
Ambiguous index name creation if chaning method after addColumn

### ISSUE THREAD

**Issue by hienning** [laravel/framework#10195]
According to the section "Dropping Indexes" of the documentation,  Laravel will, by default, "**simply concatenate the table name, the name of the indexed column, and the index type**". So, when I create index with

```php

Schema::table('trades_log', function(Blueprint $table)
{
    $table->integer('order_id', false, true)
          ->index('order_id');
    ...
}

```

I was expect that Laravel will create the index named "trades_log_order_id_index", but it was named to "order_id". I have to break that chained code into 2 lines to have my intended result, as below:

```php

Schema::table('trades_log', function(Blueprint $table)
{
    $table->integer('order_id', false, true);
    $table->index('order_id');
    ...
}

```

By doing some research, I found that, addColumn constructed a new Fluent and then invoked the subsequent index() via its method, rather than the indexCommand method of Blueprint, that equivalent to call indexCommand with an index name, which results an unexpected behavior.

**Comment by jobrios** [comment]
This is the expected behavior. In the first snippet with the chained `index` method call, the column name is implied, so the argument to the method is the name of the index. This overrides the default index name.

In the second snippet with the 2 separate method calls, the column name is no longer implied, so the first argument to the `index` method is the name of the column(s) to be indexed. You therefore get the default index name (you can pass a custom name as the second argument).

Review the usage in the [Migrations > Creating Indexes section of the docs](http://laravel.com/docs/5.1/migrations#creating-indexes).

**Comment by hienning** [comment]
Thanks for your explanation.

I'm not going to against you, but the Laravel's documentation didn't mention this, which is why I said it's "unexpected". Actually, the only section that mention default index name is in the [Migration -> Dropping Indexes](http://laravel.com/docs/5.1/migrations#dropping-indexes) section, rather than in the **Creating Indexes** section.

If this is the expected behavior, I think we shall explain this behavior in the **Creating Indexes** section too.
