### ISSUE TITLE
UNION throws ErrorException when binding added clauses

### ISSUE THREAD

**Issue by JBMcClure** [laravel/framework#10267]
Laravel Framework version 5.1.16 (LTS)

Unions that contain an added clause are generating an ErrorException.

This works:
```
			$foo = Foo::select('created_at');	
			$bar = Bar::select('created_at');	
			$foo->union($bar);
			$foo->get();
```

This fails:
```
			$foo = Foo::select('created_at');	
			$bar = Bar::select('created_at')->where('updated_at','<', \Carbon::now());	
			$foo->union($bar);
			$foo->get();
```

```
ErrorException in Builder.php line 1244: 
Undefined property: Illuminate\Database\Eloquent\Builder::$bindings
```

Changing this statement:
```
framework/src/Illuminate/Database/Query/Builder.php Line 1244: 
$this->addBinding($query->bindings, 'union');
```

To:
```
$this->addBinding($query->getBindings(), 'union');
```
Is what remedied the problem for myself. Noted that all binding was being placed correctly, however, I'm a newbie when it comes to contributing to open source. Don't wanna futz anything up. Especially if I'm wrong. :)

Thanks!

**Comment by aguilarcarlos** [comment]
Good! bro, this helped to me when I was using advanced **joins** and **unions**, by the way, if this was intentional in **Laravel 5.1.17 (LTS)**, then is possible the property **$query->bindings** is being used in some moment, but if this is an error in the code, the best would be use until this was fixed:

    $this->addBinding(isset($query->bindings) ?: $query->getBindings(), 'union');

@taylorotwell Was this intentional? Is it possible that this is added to the project?

See [Illuminate/Database/Query/Builder.php#L1249](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L1249)

This:

    $this->addBinding(isset($query->bindings) ?: $query->getBindings(), 'union');
Instead of this:

    $this->addBinding($query->bindings, 'union');
Thanks!

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by percymamedy** [comment]
I also have the same problem....

Changing $this->addBinding($query->bindings, 'union'); to $this->addBinding(isset($query->bindings) ?: $query->getBindings(), 'union'); 

seems to fix the issue

**Comment by gdolphy** [comment]
$foo = Foo::select('created_at');   
            $bar = Bar::select('created_at')->where('updated_at','<', \Carbon::now());  
            $foo->union($bar);
            $foo->get();
Undefined property: Illuminate\Database\Eloquent\Builder::$bindings

Your loosing your bindings because as I presume the union()  is executing  $bar first then passing it to $foo hence your need to modify the framework to hold onto those bindings.

I have not built queries much  in static format $foo::select
but if it is the same thing 

$foo = new model_X()->select('created_at');
$bar = new model_y()->select('created_at')->where('updated_at','<', \Carbon::now());
return $foo->union($bar->getQuery())->get()  // adds the $bar query to $foo instead of executing.

If you want to add joins to the query you will need to be specific to avoid an ambiguity Use 
$foo->selectRaw('the_foo_table_name.field_name, some_table.field_name')->join("the_joining_table as some_table", "the_foo_table_name.field_name", "=","some_table.field_name"  );

then do 
$foo->union($bar->getQuery())->get(); 

you can chain many unions
