### ISSUE TITLE
Bootstrap/cache directory location static?

### ISSUE THREAD

**Issue by shahariaazam** [laravel/framework#10332]
why this is fixed? 

```php
public function getCachedConfigPath()
{
    return $this->basePath().'/bootstrap/cache/config.php';
}
```

Somehow can we change that? or make it more dynamic so users can set their bootstrap directory by themselves.

Reference:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Application.php#L807

**Comment by GrahamCampbell** [comment]
If you want to customize that, you need to extend the application class.

**Comment by Phyrom** [comment]
I come to a situation that my environment doesn't allow write to /bootstrap/cache or anything under root (./) of laravel.
I have change config in .env to use redis so that laravel write logs, sessions, other cache. However, laravel still writes to /bootstrap/cache. Is there any way that we can FORCE laravel to follow the config to use REDIS or MEMCACHE?

**Comment by Athuli7** [comment]
I'm trying to deploy to Google App Engine, Standard Env, PHP 7.2 Beta.
And this is the issue.
