### ISSUE TITLE
[feature request] automagically mass assign models and their relationships

### ISSUE THREAD

**Issue by Evertt** [laravel/framework#10391]
Lets say I make a form like this:

```html
<form>
    <input type="text" name="User[person][name]">
    <input type="text" name="User[person][infix]">
    <input type="text" name="User[person][surname]">

    <input type="text" name="User[email]">
    <input type="text" name="User[password]">
    <input type="text" name="User[password_confirmation]">

    <input type="checkbox" name="User[person][tags][]" value="1"> hot
    <input type="checkbox" name="User[person][tags][]" value="2"> cool
</form>
```

As you can see, all the relationships between the models are apparent from the way I've set up the form. The resulting array might look something like:

![screen shot 2015-09-26 at 16 43 22](https://cloud.githubusercontent.com/assets/1267282/10118057/c48be58e-646d-11e5-919d-3bfc39774e0e.png)

Now in my UserController's store method I'd still need to separately assign everything to the corresponding models, because mass-assignment doesn't work for relationships. But that's so unnecessary work and over the course of a big project it adds up.

I think it would be cool if the model would automagically be built up in the Request object, so you could do this:

```php
// In UsersController

public function store(CreateUserRequest $request)
{
    // We know it's validated, because otherwise we'd never hit this code
    $user = $request['User'];
    $user->save();
}
```

Or if you'd like a slightly different syntax then I'm all ears. I'm not invested in the syntax per se, I just want the "write less code" side of it.

Of course I'd prefer if this process isn't tightly coupled with Eloquent, but via some contracts so I can build the same contracts in [Analogue](https://github.com/analogueorm/analogue).

**Comment by syaiful6** [comment]
it's not good idea i think. Just take that dirty work, abstract it via your trait or so. There are many relationship to take care, and how it assigned. Never hide what your code do, explicit is better than implicit.

**Comment by adamwathan** [comment]
You could do this pretty easily in the custom request object yourself. I don't know that it's a good addition to the framework, because I don't know how often people need to do _exactly_ this without any tiny tweaks for their own applications.

I think you are usually better off creating a form object for this sort of thing and handling it yourself. I worry this is an attempt to over-DRY things to the point that you end up with a difficult to manage abstraction that's trying to be too general.

On top of that, there are a bunch of annoying limitations with how PHP parses arrays and associative arrays from form input (`tags[][name]` won't actually get parsed properly for example) and I think it's more common to submit complex forms like this as JSON over AJAX these days as well.

I think you should try building it out as a package first and see what sort of usage and adoption it gets. Definitely the best way to figure out if it's a good idea or not :+1:

**Comment by Evertt** [comment]
Thank you, sounds like a good idea. :-)

**Comment by tysonsteele** [comment]
Am I missing something or does $model->fill() not work anymore? Write your interface and in your Eloquent implementation wouldn't $model->fill($request['Model']); and $model->push() not work?

I might be completely missing the intent.

**Comment by bencorlett** [comment]
What @adamwathan said is perfect :) Great (and tidy approach).
