### ISSUE TITLE
[5.1] Eloquent collection `pluck()` function should return base collection

### ISSUE THREAD

**Issue by tinpont** [laravel/framework#10596]
```php
$groups = User::all()->pluck('group_id')->unique();
```

This will throw an Exception
###### exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getKey() on integer' in app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php:223

**Comment by GrahamCampbell** [comment]
What exact version of 5.1 please?

**Comment by GrahamCampbell** [comment]
Also, is this still the same on 5.2?

**Comment by TommyC81** [comment]
The issue of EloquentCollections not returning BaseCollections where appropriate and hence causing these types of errors has been brought up before, including pull requests to fix it.

I'm using toBase to fix this, but the appropriate thing is, in my opinion, that the conversion is done automatically for all Collection functions that will break unless converted to BaseCollections. The problem stems from classes inheriting BaseCollections returning a collection of its own type rather than forcing the return of a BaseCollection where appropriate. Is there an easy fix for this?

**Comment by tinpont** [comment]
@GrahamCampbell  In all 5.1 versions. Yes, 5.2 still has this issue. Because `pluck()` still `return new static`.

**Comment by tinpont** [comment]
@TommyC81 This can simply add a `toBase()` function in `BaseCollection` to return itself.

**Comment by rkgrep** [comment]
This had been already discussed in #9191

**Comment by tinpont** [comment]
@rkgrep Thanks for you work.
