### ISSUE TITLE
BCC recipients became visible with Mailgun driver

### ISSUE THREAD

**Issue by nilay** [laravel/framework#10650]
I am using the Mailgun driver in Laravel 5.1. We're sending out group emails and would like the recipients to be hidden via BCC.

After switching from Mandrill to Mailgun, BCC recipients became visible in some clients, including Gmail. The code we use in Laravel to send the email has not changed.

```
Mail::send('emails.group-email', $data, function($message) use ($data) {
            $message->to('support@example.com');
            $message->bcc($this->recipients); // Contains an array of emails
            $message->subject('FVRS Group Email - ' . $this->subject);
        });
```

**Comment by rkgrep** [comment]
Confirm the problem is present.
Laravel uses `to` parameter to pass all recipients to Mailgun, while CC and BCC separating is made in message headers. This makes BCC visible in message source code - so Gmail displays it.
There is additional info in [examples](https://documentation.mailgun.com/api-sending.html#examples) which shows that `bcc` parameter can be passed.
I've tested it manually and there is a way to make it work with Laravel.

**Comment by GrahamCampbell** [comment]
Fixed.

**Comment by enVolt** [comment]
This issue still persist (using Laravel 5.1)
