### ISSUE TITLE
Database name is incorrect

### ISSUE THREAD

**Issue by michaelachrisco** [laravel/framework#10713]
I am running MS Server 2008 R2 and running into some issues saving.
I created a migration:
```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTwelveMonthEligReportIndexTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('TwelveMonthEligReportIndex', function (Blueprint $table) {
            $table->increments('id')->index();
            $table->date('EffectiveDate');
            $table->date('DisplayDate');
            $table->date('TerminationDate');
            $table->string('CreatedBy');
            $table->string('ModifiedBy');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('TwelveMonthEligReportIndex');
    }
}
``` 

and model:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TwelveMonthEligReportIndex extends Model
{
  protected $fillable = ['EffectiveDate', 'DisplayDate', 'TerminationDate', 'CreatedBy', 'ModifiedBy'];
}
```
When I try:
```php
      $effectiveDate = date('2014-10-01 23:29:53.000');
      $termDate = date('2014-12-30 23:29:53.000');
      $displayDate = date('2014-12-30 23:29:53.000');
    $twelveMonthEligReportIndex = TwelveMonthEligReportIndex::create(
    [
      'EffectiveDate' => $effectiveDate,
     'DisplayDate' => $showDate,
     'TerminationDate' => $termDate,
     'CreatedBy' => 'dbo',
     'ModifiedBy'=>'dbo'
    ]);
```
I get the following error:
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 208 General SQL Server error: Check messages from the SQL Server [208] (severity 16) [(null)] (SQL: insert into [twelve_month_elig_report_indices] ([EffectiveDate], [DisplayDate], [TerminationDate], [CreatedBy], [ModifiedBy], [updated_at], [created_at]) values (2014-10-01 23:29:53.000, 2014-12-30 23:29:53.000, 2014-12-30 23:29:53.000, dbo, dbo, 2015-10-24 00:07:38.000, 2015-10-24 00:07:38.000))
```

I am a novice to the framework so there may be something I am missing.

**Comment by rkgrep** [comment]
First: to save dates properly add `$dates = [ ... ]` property to your model with date fields' names - so Laravel can determine which fields should be converted to database date format.
Second: `date` function usage is `date($format, $timestamp = null)`, so your lines are incorrect. If you want to convert string date to timestamp, use `strtotime` function or `Carbon::createFromFormat` to get a `Carbon`/`Datetime` object.
Third: if you are saving dates with time, you should use `datetime` or `timestamp` field type in schema

The actual problem is in date format, which is `YYYYMMDD` for SQL Server while you passing strings which are not converted to proper format because of incorrect model definition.

**Comment by michaelachrisco** [comment]
Thanks Ill give it a shot.

**Comment by michaelachrisco** [comment]
Turned out, the Database Table name was automatically going to name_foo rather than NameFoo (snake case vs camel case). Setting public `$table = 'TwelveMonthEligReportIndex';` fixed the issue. Looks like Eloquent and the DB can understand the date commend well enough. I did add your suggestions after the fact (thanks! @rkgrep).
