### ISSUE TITLE
SerializesModels with recently deleted models

### ISSUE THREAD

**Issue by pulkitjalan** [laravel/framework#10733]
I'm having an issue where my event `UserWasRemoved` which is using the `SerializesModels` trait and I have a few listeners setup for that event. I have added a new queued listener, however when the job is being processed I am getting a `No query results for model` error.

The above event is fired after the user has been removed and the error is thrown from `SerializesModels@getRestoredPropertyValue` due to the `findOrFail`.

What are your thought on something like:

```
/**
 * Get the property value prepared for serialization.
 *
 * @param  mixed  $value
 * @return mixed
 */
protected function getSerializedPropertyValue($value)
{
    return $value instanceof QueueableEntity
                    ? ($value->exists ? new ModelIdentifier(get_class($value), $value->getQueueableId()) : serialize($value))
                    : $value;
}

/**
 * Get the restored property value after deserialization.
 *
 * @param  mixed  $value
 * @return mixed
 */
protected function getRestoredPropertyValue($value)
{
    return $value instanceof ModelIdentifier
                    ? (new $value->class)->findOrFail($value->id)
                    : (@unserialize($value) ?: $value);
}
```

Thanks.

**Comment by GrahamCampbell** [comment]
This is intended. We definitely don't want to silently fail and use null here.

**Comment by pulkitjalan** [comment]
The above suggestion would not silently fail, it checks if the model exists using the `exists` property, which is set to false on delete, and would serialize the deleted model instead of using `ModelIdentifier`. Then on restore it would `unserialize`.

**Comment by pulkitjalan** [comment]
Ping @GrahamCampbell

**Comment by taylorotwell** [comment]
What are you wanting to do in your queued listener that requires you to have the full user?

**Comment by pulkitjalan** [comment]
There are a number of items that are stored for a user on s3. The new listener removes these items. Since it can take time to remove they are queued. The references are stored in the user model and in 1 other relationship. The listener also deletes the related item from the db once s3 has finished.

**Comment by pulkitjalan** [comment]
I also need to add another queued listener that contacts a third party service to also remove the user info. Again queued because I am dealing with a third party api.

All the non queued listeners are fine, it's just not consistent with queued ones.

**Comment by taylorotwell** [comment]
Right, it's not consistent because the user is already deleted by that
point. What I suggest is using a separate event for these and passing the
information you actually need into the event instead of the entire user
model. I don't think we're going to have a very natural, clean way to give
you a deleted User instance that actually doesn't even exist in the
database anymore.

**Comment by ryanhungate** [comment]
Ping @taylorotwell - I am getting a never ending loop while using beanstalkd when a SerializesModels queue job can not find a DB record.  The "findOrFail()" is fine if you're catching that, but in this case, the __wakeup() method is called too soon for the queue job to catch the error and deal with it. 

What are you doing to prevent that yourself?  I'm adding an override in all the classes that use this trait which kind of sucks.

    /**
     * Get the restored property value after deserialization.
     *
     * @param  mixed  $value
     * @return mixed
     */
    protected function getRestoredPropertyValue($value)
    {
        try {
            return $value instanceof ModelIdentifier
                ? (new $value->class)->findOrFail($value->id) : $value;
        } catch (ModelNotFoundException $e) {
            return null;
        }
    }

**Comment by taylorotwell** [comment]
Are you setting a max retry count are your queue listener using --tries=3
for example?

**Comment by ryanhungate** [comment]
I typically do 3 yeah.  I can check if this particular queue pipe is any
different - but pretty sure it's not even getting to that function to deal
with the failure because it's in the __wakeup() call - so I'll give you an
example; fire up beanstalk - push a job in with a model that exists but
don't run the queue until you delete the record that was supposed to be
used - and then you'll see what I mean.

Think of a scenario where you're queueing up a job 1 hour later but that
record gets deleted for whatever reason... This is what's happening and
it's a real nasty error that won't stop until you override this and deal
with it.  Basically the job should be deleted but should have a fallback
function to deal with a failure if you need to report it,  make sense?

**Comment by taylorotwell** [comment]
I just tested it and having the retries seemed to work fine. It went into
the failed_jobs queue.

**Comment by ryanhungate** [comment]
Using supervisor?  Or artisan one at a time?

**Comment by ryanhungate** [comment]
I think you may have just found it… it’s the “try count” that may be messing that up.  Good call man thanks.  That’s the problem when you fire up tons of queue workers and different pipes.  We run like 40-50 processes so it’s easy to miss that!  Sorry to bother.

Ryan
