### ISSUE TITLE
[5.1] Route::controller() deprecated?

### ISSUE THREAD

**Issue by eidng8** [laravel/framework#10971]
Just updated today, and suddenly see a bunch of deprecation warning.

Can't really find a clue on it, except #10781.

If it's deprecated, what should I use?

Route::xxx()?
or route()->xxx()?
or something else?

**Comment by squigg** [comment]
Set up each route manually using the standard post/get/put/patch/delete syntax. It's only the controller method that's deprecated.
http://laravel.com/docs/5.1/routing#basic-routing

You can use $router->xxx or Route::xxx or route()->xxx, depending on which flavour you prefer.

**Comment by eidng8** [comment]
Sorry to bump in a closed issue.

Shouldn't this be reflected in the document? http://laravel.com/docs/5.1/controllers#implicit-controllers

**Comment by GrahamCampbell** [comment]
It's not deprecated in 5.1 anymore as of the next 5.1.x release.

**Comment by eidng8** [comment]
oh~ great! Luckily I haven't start changing the codes. :sweat_smile:

**Comment by shehi** [comment]
@GrahamCampbell : Sorry for reviving closed topic, but I wonder - what triggered this deprecation? What was the idea behind this move?

**Comment by glandre** [comment]
Hello everyone, @GrahamCampbell, @eidng8 and @shehi,

I've been searching on the internet, but I couldn't find any example of problem that my occur while using implicit controllers. All posts I see people saying that it's not a good practice, and, because it's important to see explicitly all routes in your routes file. However, nobody actually provides a real example of possible problems of it.

In my opinion, if I know a route related to a specific controller, I will simply take a look at it's methods in order to find out the routes... Or maybe run a 'php artisan routes:list'.

For example, the method 'Route::auth' ends up in the same situation... I need to know which routes are related to it, but it's nice to have this helper...

Since I want to keep my project updated, and, because of that I want to use the latest version of Laravel, I'm planning to remove all Implicit Controllers. However I would like to get more clearer reasons why removing it, and, what possible problems this was causing.

Thanks.

**Comment by shehi** [comment]
To my experience the problem with route-controllers mostly is related to 
hardcoded verbs in them (as in "get" in "getItem()" etc). That practice 
itself creates bottlenecks for large projects, and as you know you *had 
to* provide verbs in route-controllers. By deprecating that practice, 
the team just removed the mandatory "verbage" of routes.

**Comment by crynobone** [comment]
>  However I would like to get more clearer reasons why removing it, and, what possible problems this was causing.
> Finally, why don't warn the user of the related problems and, allow it by providing extra documentation about the ways of using it in the right way?

This has been discussed directly in previous GitHub issues for numbers of time, deprecation has been made during 5.2.0 releases. 

![screen shot 2016-09-23 at 7 45 27 pm](https://cloud.githubusercontent.com/assets/172966/18784706/57bef816-81c6-11e6-90b1-81476a807dac.png)

> However, nobody actually provides a real example of possible problems of it.

If you search on the previous issues/PR under `laravel/framework`, the issues are basically these two, and those who are involved with the discussion mostly agrees on removing it:

1. Without `artisan route:cache` all implicit controller need to be resolved (running `new FooController`) which is not ideal for performance, this would also led to anything that resolved in the construct to be executed twice. 

2. You can't use implicit/explicit method binding with implicit controllers, add this become an issue when developers expected it to be the same.

> removing it will penalize projects under production when updating the version of the framework...

There's tool such as https://github.com/themsaid/laravel-routes-publisher to upgrade your code.

**Comment by glandre** [comment]
OK guys. Thanks for your insights. I'll try this command that will probably help a lot.
