### ISSUE TITLE
\Illuminate\Foundation\Auth\ResetPasswords

### ISSUE THREAD

**Issue by esperantic** [laravel/framework#11012]
if use ResetsPasswords trait in PasswordController,

function resetPassword update $user->password = bcrypt($password); (line 113) with double encrypt...
I was long time search why user can't login after restore password but problem was in this function.
because, if update password field in user object, Eloquent automatically encrypt password.
problem solved if change $user->password = bcrypt($password); to  $user->password = $password;

**Comment by joaumg** [comment]
Store passwords as plain text is a really, really bad idea.

Are you sure you have OpenSSL PHP Extension installed ?

**Comment by rkgrep** [comment]
You're probably encoding password somewhere before it is passed to the trait.

**Comment by arcanedev-maroc** [comment]
Hi @driesvints, is there any workaround to override only this [line](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L105) instead of overriding the whole method?

The issue i've got is when i use the default reset password controller + a mutator `setPasswordAttribute` in the user model = hashes the password twice.

I can make a PR to extract a method like `$this->setUserPassword($user, $password)` in `Illuminate/Foundation/Auth/ResetsPasswords`.
