### ISSUE TITLE
Installer creates incomplete Laravel project

### ISSUE THREAD

**Issue by jhoff** [laravel/framework#11033]
http://cabinet.laravel.com/latest.zip seems to currently be missing a handful of core files, like `composer.json`, `config/app.php`, etc.

https://github.com/laravel/installer/blob/master/src/NewCommand.php#L97

This is causing the laravel installer to create non-working projects.

**Comment by shssoichiro** [comment]
Confirmed, was able to replicate

    $ laravel new tester
    Crafting application...
    Composer could not find a composer.json file in /Users/holmerj/tester
    To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
    Application ready! Build something amazing.

**Comment by ariadeploy** [comment]
I having been using v3 for quite some time. We're building a new app and decided it's time to use Laravel v5. All I can say is I miss v3. I'm stuck at the moment due to this very issue. No idea how to proceed.

**Comment by thomastkim** [comment]
@ariadeploy You can always use composer's `create-project` command.

`composer create-project laravel/laravel someDirectory --prefer-dist`

**Comment by pixelgremlins** [comment]
Confirmed here, the "laravel new *" command is failing as well, however the composer create-project is a work-around for the time being. @ariadeploy I would never recommend l3 over l4 or l5 - a lot has changed since l3, l4 was beautiful by itself, but l5 is just awesome in all the new features that it brings to the table, like baked-in authentication and authorization.

**Comment by velvetfont** [comment]
Happening here too. :-/ Sigh... I thought it was me.  I am new to this stuff so it was kind of frustrating to understand why it was breaking.

**Comment by bretterer** [comment]
I do not see the issue here.   the latest .zip is working for me... and so is `laravel new app`

<img width="358" alt="screen shot 2015-11-20 at 12 23 01 am" src="https://cloud.githubusercontent.com/assets/1906920/11292506/f77ffbe0-8f1c-11e5-961f-b2043fa16453.png">

<img width="1047" alt="screen shot 2015-11-20 at 12 24 21 am" src="https://cloud.githubusercontent.com/assets/1906920/11292518/18201772-8f1d-11e5-908e-c1ef23502cd5.png">

**Comment by arjasco** [comment]
I can also confirm that yesterday the files were missing from the zip but today all seems to be fine.

**Comment by GrahamCampbell** [comment]
I assume the script that generates the zip crashed yesterday, but it's fine today. :P
