### ISSUE TITLE
Error changing column type to json

### ISSUE THREAD

**Issue by PhiloNL** [laravel/framework#11095]
Not sure if it's a bug, but when changing a column type from varchar to json results in the following error:

```php
Schema::table('fields', function (Blueprint $table) {
    $table->json('label')->change();
});
```

```
  [Doctrine\DBAL\DBALException]
  Unknown column type "json" requested. Any Doctrine type that you use has to be registered
  with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with
  \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspecti
  on then you might have forgot to register all database types for a Doctrine Type. Use Abst
  ractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMap
  pedDatabaseTypes(). If the type name is empty you might have a problem with the cache or f
  orgot some mapping information.
```

Use `$table->text('label')->change();` instead?

**Comment by edcs** [comment]
The problem lies with Doctrine DBAL, it doesn't support the JSON column type for MySQL yet:

https://github.com/doctrine/dbal/blob/2.0.x/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L598

I can't see any PRs for it at the moment, but you can add custom map types (as suggested in the error message):

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html

**Comment by pappavic** [comment]
I'm getting this error even though I'm using a PostgreSQL database using Laravel 5.3

**Comment by fernandobandeira** [comment]
@pappavic The same applies to PostgreSQL

https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L1098

**Comment by nausmani** [comment]
$query = "ALTER TABLE fields MODIFY `label` JSON DEFAULT NULL";
        \Illuminate\Support\Facades\DB::statement($query);


Try this in laravel migration.. working for me
