### ISSUE TITLE
Official docker container

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#11102]
Seems like other frameworks and servers are making a special effort to publish containers in the docker hub that are tagged as "official".

Would love too see one for Laravel, even if it means co-opting an existing Dockerfile from the community.  At the very least, having one with the official seal will be good for the community.

Reason: I was doing a demo of the neat new tutum tool and was able to just tell it to grab the new ASP.NET's official docker image.  Would love to be able to do this with Laravel as well!

**Comment by ArjanSchouten** [comment]
I've written some Dockerfiles for my own environment and it's easy enough to write you're own. Finally I decided to not use docker for Laravel (was more like a test and for my own interest). I think it is making things only more complex for most Laravel cases!

Sometimes you can really benefit from it but I think it's not worth the pain for Laravel to create and **maintain** such official containers.

**Comment by GrahamCampbell** [comment]
Agreed. If you want to discuss this with Taylor in private, feel free though. We don't process proposal issues on GitHub.

**Comment by atrauzzi** [comment]
@ArjanSchouten - I'm aware of being able to create one, although the thought expressed here is that the community would benefit from pooling knowledge under an official one.

In terms of "making things more complex", I'd be interested in hearing your reasoning there.  In my case, I've only found the requirements of docker to help make applications more robust.  This is thinking along the lines of the 12factor principles.

**Comment by ArjanSchouten** [comment]
From my experience it's only adding complexity when you're using docker containers for small projects. When projects grow you can decide that it's has some benefits to be more portable with containers (for snapshots, running multiple instances). My main point is that it's probably not suitable for most Laravel projects(and suitable for a few results in overhead for the other users because a lot of people will follow). But this is only my opinion about the fact if you should make it a part of Laravel. I rather like to see a good docker solution for Laravel projects!

**Comment by atrauzzi** [comment]
Really the consideration of using containers isn't  a question of complexity, it's aaquestion of how you plan to deploy.

So whether you like them or not... Some people will use then
