### ISSUE TITLE
Method 'save' not described in Illuminate\Contracts\Auth\Authenticatable

### ISSUE THREAD

**Issue by andkom** [laravel/framework#11200]
Method updateRememberToken() calls save() method on an object that implements Illuminate\Contracts\Auth\Authenticatable interface but this method is not described there and object may not contain such method.

Illuminate/Auth/EloquentUserProvider.php:
```php
    public function updateRememberToken(UserContract $user, $token)
    {
        $user->setRememberToken($token);

        $user->save();
    }
```
it also assigns new remember token twice, setRememberToken() is also called before updateRememberToken():

Illuminate/Auth/Guard.php:
```php
    protected function refreshRememberToken(UserContract $user)
    {
        $user->setRememberToken($token = Str::random(60));

        $this->provider->updateRememberToken($user, $token);
    }
```

**Comment by taylorotwell** [comment]
Ah, we're just assuming if you're using the Eloquent provider ->save() is available.

**Comment by andkom** [comment]
but if you use custom auth driver and that driver implements only UserContract and don't have method save() there will be error

**Comment by andkom** [comment]
UserContract should have save() method defined or better implementation...

**Comment by SamMousa** [comment]
@taylorotwell These assumptions make it hard for other developers to replace your code, which is the primary reason for using the contract.

Adding the `save()` method would mean a major breaking change, but at least that is a break that can easily be detected, whereas this error will only be detected if / when someone finally calls `updateRememberToken()`.

**Comment by crynobone** [comment]
`save()` is only being used in `EloquentUserProvider` class, if let say you're using `DatabaseUserProvider` it never requires that (https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/DatabaseUserProvider.php#L86). 

Let's say one day someone wants to create `DoctrineUserProvider`, it doesn't depends that `Authenticatable` have `save()` method available.

**Comment by SamMousa** [comment]
@crynobone Then why not create another contract, or at least check if the given object has the save method... And then throw a proper exception describing that this user provider requires the `save()` function to be present.

**Comment by crynobone** [comment]
If we pass in a different typehint (child of `Authenticatable` contract), would that break the `UserProvider::updateRememberToken()` contract <https://github.com/laravel/framework/blob/5.2/src/Illuminate/Contracts/Auth/UserProvider.php#L31>?

**Comment by SamMousa** [comment]
Even better, since `EloquentUserProvider` has the name of the model, it could do the save without breaking the contract; the contract specified `getAuthIdentifierName()` and `getAuthIdentifier()` giving me unique identifiers that I can use to find the Eloquent model, call `setRememberToken()` on it and then `save()` it.

That way I can pass in another implementation while still using it with `EloquentUserProvider` and in case I pass an actual `Eloquent` model instance than the query can be skipped and we save it directly.

Thereby you code against the interface you publish, you guarantee it works with any implementation of the interface, but you still get the optimization in case you pass in a specific type.

**Comment by SamMousa** [comment]
@crynobone  Yes it would, so I understand not doing that directly for this one case. Also if the `save()` is hardly ever required then adding it would be a burden to all implementors.

I'm just disagreeing with the implicit requirement that will never show up in testing, especially since there is a way to make it always work at a very minor cost of 1 query for cases where it does not work at all now, and the cost of 1 instanceof check for the situation where it currently works.

**Comment by crynobone** [comment]
If there is a requirement, it should actually just check `($user instanceof Illuminate\Database\Model\Eloquent)` and throws an exception if it's not. Since `EloquentUserProvider` is really just meant to be used with Eloquent.

**Comment by SamMousa** [comment]
I agree, but my point is there is an easy implementation that just works and obeys the contract... why not use that instead?
Like so:

````
public function updateRememberToken(UserContract $user, $token)
    {
        $user->setRememberToken($token);
        if ($user instanceof Illuminate\Database\Model\Eloquent) {
            $user->save();
        } else {
            // Taken from createModel()
            $model = $this->createModel()->newQuery()->find($user->getAuthIdentifier());
            $model->setRememberToken($token);
            $model->save();
    }
````

Some improvements still remaining, for example checking against the type `$this->model` instead of the base eloquent model. Also I don't know if this behavior is better than throwing an exception as you suggested. Either of those is better than just calling a function blindly though!

By the way, scrutinizer also detects these kinds of errors:
https://scrutinizer-ci.com/g/laravel/framework/code-structure/master/class/Illuminate%5CAuth%5CEloquentUserProvider#inspectioncomment-700653667

**Comment by crynobone** [comment]
> but my point is there is an easy implementation that just works and obeys the contract... why not use that instead?

Wouldn't that seem like allowing hacks to be implemented (hack here refer to sending  `Authenticatable` other than Eloquent instance).

if anything it should be.

```php
    public function updateRememberToken(UserContract $user, $token)
    {
        $user->setRememberToken($token);
        if (! $user instanceof \Illuminate\Database\Model\Eloquent) {
            throw new \InvalidArgumentException('Expecting $user to be an instance of Eloquent');
        }

        $user->save();
        
        // ...
    }
````

**Comment by SamMousa** [comment]
That's fair enough; that is a decision that is outside of the purely technical scope and I'm not familiar enough with Laravel to go into that. However by doing this check you at least make the requirement on `$user` a bit more explicit.
Considering other scenarios where `$user` might be passed around internal functions several times and one of them could call `save()` this will make the life of a developer much simpler!

**Comment by crynobone** [comment]
> Considering other scenarios where $user might be passed around internal functions several times and one of them could call save() this will make the life of a developer much simpler!

This is what I mean by opening the possibility for hacks. `Guard` contract would retrieve the user using `UserProvider` contract, if you are set to use the `EloquentUserProvider` this would always return an eloquent instance. 

The only times where this could change is for some reason you're using e.g `LdapUserProvider` and probably get a `GenericUser`, then during the request lifecycle you change the configuration to "eloquent" (not sure if this even possible) and then the code request "logout" which would update the remember token. 

Now, the `EloquentUserProvider` accept the `GenericUser`, which my properly, this would throw an exception because it not possible to update the user using "eloquent" for LDAP users, which your suggestion it detect it's not an Eloquent and then still attempt to write the "eloquent". 

Would you want to allow such hacks?

**Comment by SamMousa** [comment]
No, I don't see any use cases for those kinds of hacks, so exception seems like a great improvement to what is done currently.
