### ISSUE TITLE
[Homestead] GuestAdditions version mismatch

### ISSUE THREAD

**Issue by sandrodz** [laravel/framework#11439]
I'm using plugin that automatically installs correct guest addition on guest machine

```vagrant plugin install vagrant-vbguest```

error:
```GuestAdditions versions on your host (5.0.10) and guest (5.0.4) do not match.
An error occurred during installation of VirtualBox Guest Additions 5.0.10. Some functionality may not work as intended.```

~~fix!
run inside homestead vm:
```sudo apt-get update && sudo apt-get install linux-generic```~~

~~maybe we can add installing linux headers during provisioning?~~

After installing correct version of guest additions on guest VM, now it thinks there is a mismatch again, but versions are reversed it thinks host has 5.0.4 and guest 5.0.10

I use various vagrant boxes, and I've never seen this issue before.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by sandrodz** [comment]
Actually my fix only worked for first start, I'm still having issues.

**Comment by GrahamCampbell** [comment]
@sandrodz Thanks for reporting. Are you still having this issue?

**Comment by dennschu** [comment]
@GrahamCampbell got the same message during clean install of homestead 3.0.1 on a mac. 

**Workaround until there is a solution or the real culprit is found** *(i think its vbguest)*

1. add the following to your projects `Vagrantfile` in order to disable `vbguest` auto_update:

````ruby
if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
end
````
2. run guest additions manually per project through vagrant `vbguest` plugin once in a time

````sh
vagrant vbguest --do install
````

For my case that does the job - guest additions got installed and version mismatch disappeared. @sandrodz does this workaround also work on your side?

**Comment by sandrodz** [comment]
@dennschu yes it works, but its a workaround, would be great to have a definitive fix...
