### ISSUE TITLE
[5.2] Auth bug new install

### ISSUE THREAD

**Issue by cyprusglobe** [laravel/framework#11435]
isnt getting the ```web middleware```
```
Route::get('/', function () {
    return view('welcome');
});
```

if i do this
```
Route::get('/', ['middleware' => 'web', function () {
    return view('welcome');
}]);

or

Route::group(['middleware' => ['web']], function () {
    Route::get('/', function () {
        return view('welcome');
    });
});
```
i thought this was suppose to cover it though
```
Route::group(['middleware' => ['web']], function () {
    //
});
```

**Comment by GrahamCampbell** [comment]
I don't see the bug?

**Comment by cyprusglobe** [comment]
@GrahamCampbell i posted what im see here https://www.youtube.com/watch?v=D480A63XTbI

**Comment by GrahamCampbell** [comment]
I still don't see what you think is wrong there. Feel free to create a new issue with clear reasoning.

**Comment by crynobone** [comment]
> I still don't see what you think is wrong there. Feel free to create a new issue with clear reasoning.

## Expected behaviour

By running `php artisan make:auth` all the routes and views should work as expected.

## Current behaviour

After running `php artisan make:auth`, every routes works fine. However once you logged in, and then go to `GET /` (which does not have the `web` middleware). No session was loaded, hence you'll see in the video that both `Login` and `Register` link are available, instead of seeing your username/name.

```
$user = User::find(1);
$this->be($user);
$this->visit('/')->notSee('Login');
```

**Comment by GrahamCampbell** [comment]
> GET / (which does not have the web middleware). No session was loaded, hence you'll see in the video that both Login and Register link are available, instead of seeing your username/name.

Right. That's why I was saying there was no bug in the actual framework.

**Comment by GrahamCampbell** [comment]
If the auth stubs are broken, we'd accept a PR to fix them. ;)

**Comment by danharper** [comment]
I can see this being very confusing.

The auth stubs change the `welcome.blade.php` file to use the `layouts/app.blade.php` template. That template does an `Auth::check` to switch between showing Login/Register or the logged in user's name.

However since on the default Laravel install, the `/` route loads no middleware, you're never "logged in". So if you are logged in and go to the home page, you see "Login/Register", and if you click them you're taken back to the `/` route due to the guest middleware.

It took me a while to figure it out, and without understanding how middleware groups work (i.e. someone new to Laravel) you'd think it was a more serious authentication bug.

Perhaps either the `welcome.blade.php` template in the auth stubs should be changed/removed, or the `/` route in the default Laravel install should be moved into the `web` middleware group?
