### ISSUE TITLE
[5.2] Illuminate\Auth\SessionGuard is not injectable, inconsistent with API docs

### ISSUE THREAD

**Issue by GameReplays** [laravel/framework#11465]
In Laravel 5.1, I was injecting the Guard instance (instead of doing Auth::login() or Auth::user() facade access), but that no longer exists. So I tried injecting the SessionGuard as that is what I was using in my custom auth wrapper (which integrates a legacy auth system), but that cannot be injected due to the `$name` scalar. 

However, the API docs don't seem to be consistent. 

Laracasts post:

https://laracasts.com/discuss/channels/laravel/52-upgrade-problem-class-illuminateauthguard-does-not-exist

If there is an alternative way of injecting what used to be the `Guard` instance, it would be good to mention that in both the upgrade guide, as well as the documentation Facade class reference.

**Comment by crynobone** [comment]
can't you inject `Illuminate\Contracts\Auth\Guard`?

**Comment by serhatdurum** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Both should be bound so they can be injected imo, actually.

**Comment by GameReplays** [comment]
Or at the very least, the docs should be updated to indicate what is the recommended way to obtain the Guard instance.

**Comment by GrahamCampbell** [comment]
No, this is a bug. You should be able to typehint a concretion and have it correctly resolved, even if we recommend typehinting a contract. Sometimes you really might want the concretion, if you need methods not available on the contract, for example.

**Comment by GrahamCampbell** [comment]
Thanks for reporting btw. ;)

**Comment by GrahamCampbell** [comment]
Hmmm, on further investigation, I can actually confirm that this is not a bug, due to the way the new auth system works. It may be possible for the default auth system to not be using sessions, so binding it would be incorrect.

**Comment by GrahamCampbell** [comment]
I'd suggest injecting the auth manager class if you want more control.

**Comment by GameReplays** [comment]
Docs should be updated:

`52. Docs -> Facades -> Class Facade Reference -> Auth (instance)` will throw an error if you try and inject that. Should be updated to the contract reference, or removed.

**Comment by GrahamCampbell** [comment]
auth.driver is also missing from there

**Comment by GrahamCampbell** [comment]
we're open to PRs to fix :)

**Comment by EliasZ** [comment]
@GrahamCampbell So what is the recommended way to get an instance of the previous `Guard`? Inject `Illuminate\Auth\AuthManager` and access it via `->guard()`?

**Comment by GrahamCampbell** [comment]
I'd recommend just injecting the contract.

**Comment by GrahamCampbell** [comment]
Only use the manager if you need a non-default connection.

**Comment by serhatdurum** [comment]
I have same problem, before 5.2 with Guard injection everything works fine , but now when i use Authmanager for auth in construct and then `$this->auth->guard("web")->attempt($userdata, true)` that returns true but when i redirect to user profile page with 
`Route::group(['middleware' => 'auth'],function () {
    Route::get('/u/{username}', 'ProfilController@index');
});` it redirects "login". @GrahamCampbell @EliasZ

**Comment by EliasZ** [comment]
@GrahamCampbell Right now you cannot inject "the Guard" (`auth.driver`). For example, type hinting the `Guard` contract will result in missing out on `login` (among others) due to this being part of `StatefulGuard` (yes, you can still call them due to non-strictness).

The `Auth` facade calls methods on the underlying `Guard` and the facade methods discussed in the documentation might in some situations not be available which is confusing. The facade reference could include some explanation on which guard contract you need to inject when.

**Comment by Deall0c** [comment]
so if I understand it correctly, there's currently no way to use the authentication with interfaces?
Yes you can inject the guard, but it doesn't have the methods you use on them (which doesn't seem correct to me).

**Comment by mallinus** [comment]
Resolving the concrete implementation for \Illuminate\Contracts\Auth\Guard is working here, however there's no attempt method available in that contract. You need to resolve the concrete implementation for \Illuminate\Contracts\Auth\StatefulGuard in order to get access to this method, and this is throwing the following error here:

![2016-02-06 12_00_03-localhost_8000_login](https://cloud.githubusercontent.com/assets/13000832/12866275/645280c8-ccc9-11e5-9fd3-e1d73c163717.png)

So yes, basically there's no way currently (as I know of) to type hint an authentication contract for password grant authentication.
