### ISSUE TITLE
Migrate command boots the whole app. Fails when there are DB calls in an Service Provider

### ISSUE THREAD

**Issue by PhillippOhlandt** [laravel/framework#11491]
Hey,

sometimes you have to get some data out of the database in a Service Provider. 
For Example: Jeffreys ACL episode

But then you can't deploy your application because the migrate command will fail because the application tries to get data out of an missing database table. 

Sure you can try-catch that or ask if app is called through the console but that's not great. In my mind the migrate command shouldn't boot the whole app.

Phillipp

**Comment by GrahamCampbell** [comment]
I'd not recommend making database calls in a service provider.

**Comment by GrahamCampbell** [comment]
Or, actually, just make the service provider deferred.

**Comment by heisian** [comment]
seems more like you'd want to grab data using middleware, not a service provider

**Comment by GrahamCampbell** [comment]
Yeh, that's totally the correct place for it.

**Comment by PhillippOhlandt** [comment]
I have to setup my roles and permissions and global settings. They shouldn't belong in a middleware. They should be in a non-deferred Service Provider because I need them as early as possible. 

Booting the whole app just to run 5 scripts from a folder shouldn't be the right way.

**Comment by heisian** [comment]
Personally I use service providers for initializing things like Singletons containing arrayed data and app event listeners.  What you are describing, i.e. setting up user roles/permissions is what I do in middleware, because a lot of it is route-dependent (am I going to an admin-only page or a general user page?) b/c it is easy to specify what middleware to use either in `routes.php` or the controller itself.
