### ISSUE TITLE
No Guard Instance for Password Reset? Laravel 5.2.0

### ISSUE THREAD

**Issue by kazi-mainuddin-ahmed** [laravel/framework#11695]
I have successfully tried 2 different Database table Login for 2 different area. Then I thought it is a great scalability option for Laravel. But then when I tried Resetting Password for Login Credentials other than default users table. It stopped. It only runs query on the users table no matter where you are.

In L-5.2.0 specifying other guard instance is introduced for Auth Facade. eg.
`Auth::guard("GuardInstanceName")`
But I think it is required for Password Facade too. Something like:
`Password::guard("GuardInstanceName")->reset(Credentials, Callback);`

**Comment by hiendv** [comment]
It's `PasswordBroker`, not `Guard`. Since `Password` Facade (`auth.password.broker`) is registered with the default broker, I suggest that you should resolve another broker for the other `PasswordController` and replace `Password` with it. If you don't mind waiting, I'm working on an *easy (hope so!)* solution. It will take about 30 minutes ;)

**Comment by kazi-mainuddin-ahmed** [comment]
I guess it should not be closed... Because it is indeed an Issue. If separate Auth Provider is recognized through `$this->getGuard()` but there is nothing to handle the Provider for Password Reset. How is this issue fixed anyway!
