### ISSUE TITLE
Improve exception handling when no logger's been registered yet

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#11756]

**Comment by stevenmyhre** [comment]
Any progress on this?  It comes up any time I go to a new machine and run composer update or any artisan command.  Artisan tries to boot up but it can't resolve dependencies due to a missing .env config variable.  Which then forces me to debug into the laravel source code in order to figure out what  config key is missing.

It's one of those **I remember this vague error message 'Class log does not exist', but I can't for the life of me remember what the real problem was!**

Proposed solution, as others have suggested, is to re-throw the exception if it's not "reportable", i.e.
```php
    public function handle($input, $output = null)
    {
        try {
            $this->bootstrap();

            return $this->getArtisan()->run($input, $output);
        } catch (Exception $e) {
            try {
                $this->reportException($e);

                $this->renderException($output, $e);
            } catch(Exception $ex) {
                throw $e;
            }
            return 1;
        } catch (Throwable $e) {
            $e = new FatalThrowableError($e);

            $this->reportException($e);

            $this->renderException($output, $e);

            return 1;
        }
    }
```
https://github.com/laravel/framework/blob/b88014713b2581d6bb443f4a0e8837662267772c/src/Illuminate/Foundation/Console/Kernel.php#L102-123

**Comment by GrahamCampbell** [comment]
This has been fixed on:
* Laravel 5.3+
* The latest Lumen 5.1, 5.2, and 5.3+.

**Comment by GrahamCampbell** [comment]
Run down for why not latest Laravel 5.1 and 5.2 was due to BC issues.
