### ISSUE TITLE
Array validation - subarray same field name

### ISSUE THREAD

**Issue by pmall** [laravel/framework#11772]
It seems like there is something wrong doing this : 

```
$rules = [
    'plates.*.name' => 'required|max:32|regex:/^[A-Z]+$/i',
    'plates.*.regions.*.name' => 'required|max:16',
]
```

The regex rule get applied on both the plates names and the regions names.

By sending post data like this :

```
[
    'plates' => [
        0 => [
            'name' => 'foo',
            'regions' => [
                0 => [
                    'name' => 'foo bar',
                ],
            ],
        ],
    ],
]
```

I got validation error : The plates.0.regions.0.name format is invalid. It is because of the space in the region name, it doesnt pass the regex rules which should be applied only on the plates names. By removing the regex rule for the plates names, everything works fine.

**Comment by peterquentin** [comment]
@pmall this is because the function `Str::is`, that is used in `Illuminate\Validation\Validator::each` is to greedy for that to work.

I made it work by writing a regression test.
Not sure what to name this new method or if it should be a new method at all.

```
//obviously this is an awful name and should be made a helper

function strIsWithNumericWildcard($pattern, $value)
{
        if ($pattern == $value) {
            return true;
        }

        $pattern = preg_quote($pattern, '#');

        // Asterisks are translated into zero-or-more regular expression numeric wildcards
        $pattern = str_replace('\.\*\.', '\.[0-9]*\.', $pattern);

        return (bool) preg_match('#^' . $pattern . '\z#', $value);
}
```
I've added extra dots around the asteriks; so when your fieldname itself contains a * it will not be replaced. ex: random*field (I would recommend against naming your fields like that though).

in `Illuminate\Validation\Validator::each`

```
public function each($attribute, $rules)
{
        $data = Arr::dot($this->data);

        foreach ($data as $key => $value) {
            if (Str::startsWith($key, $attribute) || strIsWithNumericWildcard($attribute, $key)) {
                foreach ((array) $rules as $ruleKey => $ruleValue) {
                    if (! is_string($ruleKey) || Str::endsWith($key, $ruleKey)) {
                        $this->mergeRules($key, $ruleValue);
                    }
                }
            }
        }
}
```
Hopefully this will get resolved soon.
