### ISSUE TITLE
Update method change created_at column value

### ISSUE THREAD

**Issue by sajjadrad** [laravel/framework#11806]
I used update method for updating multi rows with one query. but after that all created_at column values changes!

$notifications->update(['read' => 1]);

**Comment by sajjadrad** [comment]
I found out created_at column attribute defined as ON UPDATE CURRENT_TIMESTAMP.
How can I define timestamp without this attribute in migration file?

**Comment by sajjadrad** [comment]
I used $table->nullableTimestamps(); in migration.

**Comment by x-yuri** [comment]
It happens because `$this->timestamps()` was equal to `$this->timestamp('created_at'); $this->timestamp('updated_at');` which led to the following query being executed:

```
CREATE TABLE ... (... created_at timestamp not null, updated_at timestamp not null)
```

which is equivalent to

```
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
```

in mysql. Do note the `ON UPDATE CURRENT_TIMESTAMP` part. Already [fixed][1] in the repo.

[1]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Schema/Blueprint.php#L794

**Comment by sajjadrad** [comment]
Yup, as commit message "Use the current timestamp as a default." the current timestamp is default value. anyway I set created_at nullable so the default value is null.

Thanks
