### ISSUE TITLE
Form requests throwing 404 when headers missing

### ISSUE THREAD

**Issue by joshhornby** [laravel/framework#11828]
When using form requests, if you don't pass the `Accept: application/json` header the route will 404. This seems strange as the route is valid so there is no reason why it should return a 404.

To me this looks like a bug but it could be by design.

**Comment by trevorgehman** [comment]
This has to be a bug. I'm experiencing nearly the same thing. In my `routes.php` file I have:

```
Route::get('account', 'Api\AccountController@index');
```

And in `AccountController.php`:
```
public function index(Request $request)
    {
        $this->validate($request, [
            'timezone' => ['in:'.implode(',',timezone_identifiers_list())]
        ]);
     ...
    }
```

If the request validates, everything is fine. However, if it doesn't validate, Laravel throws a `NotFoundHttpException` having to do with the route not being found:

```
Illuminate\Routing\RouteCollection.php:161
throw new NotFoundHttpException;
```

I think it should be throwing a `ValidationError`, but it doesn't. However, adding the `Accept: application/json` header fixes it.

**Comment by trevorgehman** [comment]
Okay, I think I've figured out some more information. Without the `Accept: application/json` header, I believe Laravel is calling `redirect()->back()` and sending the user to an invalid route, hence the 404. At least, this is what was happening in my case.

This is documented:

> When using the validate method during an AJAX request, Laravel will not generate a redirect response. Instead, Laravel generates a JSON response containing all of the validation errors. This JSON response will be sent with a 422 HTTP status code.
> https://laravel.com/docs/master/validation#quick-ajax-requests-and-validation

The same is true for Form Requests:

> If the request was an AJAX request, a HTTP response with a 422 status code will be returned to the user including a JSON representation of the validation errors.
> https://laravel.com/docs/master/validation#form-request-validation

And you're right, adding the `Accept: application/json` header fixed it, because instead of redirecting, it returned a JSON representation of the validation errors.

In my case, for an API, I always want JSON to be returned, regardless of whether the `Accept: application/json` header is properly set. It seems then that the only way to use Laravel's validation is by manually creating a Validator:

```
$validator = Validator::make($request->all(), [
            'title' => 'required|unique:posts|max:255',
            'body' => 'required',
        ]);

        if ($validator->fails()) {
            return Response::json([
                    'http_code'      =>  422,
                    'message'   =>  'Request failed validation.'
                ], 422);
        }
```

**Comment by trevorgehman** [comment]
As an alternative, this looks like a good way to basically force Form Requests to return JSON:

```
<?php

namespace App\Http\Requests;


class ApiRequest extends Request
{
    public function wantsJson()
    {
        return true;
    }
}
```

http://stackoverflow.com/a/34062691

**Comment by joshhornby** [comment]
Any update on this? @taylorotwell

**Comment by freddinator** [comment]
Taylor posted about this on twitter: https://twitter.com/taylorotwell/status/700798586636750848
> not really a bug Laravel just needs to know its an Ajax request which it doesn't without certain headers

**Comment by jounesya** [comment]
Hello, seems that this issue is troubling many developpers, I had faced it in one of my web applications, it takes me more than 5 days to find where the problem was. I think that you can fixe it just by changing the encoding to ANSI format of your file where you want to put the instruction of returning a specific HTTP Status instead of 200. Check the best answer of this topic :

[http://e-howtogeek.com/710944/problem-page-found-returns-http-status-code-instead-laravel](url)

**Comment by andzandz** [comment]
Wasted most of a day trying to figure out why my production code was 404ing. When the `Accepts:application/json` header is missing, it could still return a 422.

**Comment by andzandz** [comment]
Wasted most of a day trying to figure out why my production code was 404ing. When the `Accept:application/json` header is missing, it could still return a 422.

**Comment by admench** [comment]
When using postman, simply add this header in:

![screen shot 2018-09-13 at 11 54 07](https://user-images.githubusercontent.com/672916/45484361-c3310500-b74b-11e8-9f04-5b0d7a5d10f1.png)

`Accept: application/json`

**Comment by andzandz** [comment]
> When using postman, simply add this header in:
> 
> ![screen shot 2018-09-13 at 11 54 07](https://user-images.githubusercontent.com/672916/45484361-c3310500-b74b-11e8-9f04-5b0d7a5d10f1.png)
> 
> `Accept: application/json`

Sure, but your application could be mysteriously 404ing for a number of reasons. You can't google something you don't know is missing to find this page.
