### ISSUE TITLE
Recent Blueprint change breaks timestamps() for anything less than MySQL 5.6.5

### ISSUE THREAD

**Issue by tomschlick** [laravel/framework#11843]
https://github.com/laravel/framework/commit/0c2b7da2635f7bbbaf63d1b93fa817232bdd9d65

This commit, release with v5.2.8 breaks $table->timestamps() in migrations when the server is using < mysql 5.6.5

it produces this error

```sh
[PDOException]                                                               
SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

Not sure if this was intended. Just found it via my CI tests on CircleCI which defaults to mysql 5.5.

**Comment by yajra** [comment]
I think it's intended and [documented](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)?

# Database

## MySQL Dates

Starting with MySQL 5.7, 0000-00-00 00:00:00 is no longer considered a valid date, since strict mode is enabled by default. All timestamp columns should receive a valid default value when you insert records into your database. You may use the useCurrent method in your migrations to default the timestamp columns to the current timestamps, or you may make the timestamps nullable to allow null values:
```php
$table->timestamp('foo')->nullable();

$table->timestamp('foo')->useCurrent();

$table->nullableTimestamps();
```

**Comment by tomschlick** [comment]
Thanks. Don't know how I missed that section while upgrading... I'll give that a shot.

**Comment by tomschlick** [comment]
Good call @yajra that was it. Thanks!
