### ISSUE TITLE
[5.2] can't get global scopes to apply to update / delete methods

### ISSUE THREAD

**Issue by richardwyke** [laravel/framework#11989]
Since the changes to global scopes in 5.2, i can't get the update or delete methods in eloquent to apply a global scope.

I have this trait:
```php
namespace App\Traits;

trait AccountTrait
{
    public static function bootAccountTrait()
    {
        static::addGlobalScope(new AccountScope);
    }
}
```
And then the scope itself
```php
namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Scope;

class AccountScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $accountId = active_account_id();
        $builder->where('account_id', $accountId);
    }
}
```

and apply this to the Model like so:
```php
class Variable extends Model
{
    use AccountTrait;
}
```

This works as it used to in 5.1 when doing a query:
```php
App\Variable::first();
```
which generates the following query:
```sql
select * from `variables` where `account_id` = '3335' limit 1;
```

however, other methods do not apply the scope,
Delete:
```php
App\Variable::first()->delete();
```
```sql
delete from `variables` where `id` = '2330016';
```
Update:
```php
Variable::first()->update(['name'=>'foo']);
```
```sql
update `variables` set `updated_at` = '2016-01-23 01:23:24', `name` = 'foo' where `id` = '2330012';
```

**Comment by acasar** [comment]
@richardwyke This works exactly the same as in 5.1. If you call update or delete directly on the model, scopes are not applied. However if you call it on a query, they are.

So instead of:
```php
App\Variable::first()->delete();
Variable::first()->update(['name'=>'foo']);
```

You should do:
```php
App\Variable::where('id', $id)->delete();
App\Variable::where('id', $id)->update(['name'=>'foo']);
```

**Comment by richardwyke** [comment]
for me, changing it to
```php
App\Variable::where('id', 23597)->update(['name'=>'foo']);
```
results in the same sql
```sql
update `variables` set `name` = 'foo', `updated_at` = '2016-01-23 02:23:09' where `id` = '23597'
```

**Comment by acasar** [comment]
Hmm... Can you tell me exactly how you did it in 5.1? So I can check for possible BC break.

**Comment by acasar** [comment]
In 5.1 scopes were not applied when deleting/updating/saving model:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L1193
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L1494

But they were applied when deleting/updating with the builder.

Can you confirm that this PR fixes your problem? https://github.com/laravel/framework/pull/11990

**Comment by brunorsantos** [comment]
@acasar I'm trying to use global scope in Laravel 5.4 for updates through eloquent save() method. But It doesn't work.

This PR were supposed to make it work to? 
Do you have any suggestion for some alternative for this?

It would be nice if i could you save() method instead of mass update. For legibility on code.
Thanks!

**Comment by acasar** [comment]
@brunorsantos Could you post your code so I can try to replicate the problem?

**Comment by brunorsantos** [comment]
@acasar Thanks for the answer! I found out a way to work.
As you said, we cant use save() method from model class, because it use newQueryWithoutScopes.

To solve my problem, I wrote another save() method directy in my class, that does not use newQueryWithoutScopes.

```
    public function save(array $options = [])
    {
        if ($this->exists) {
            $saved = $this->isDirty() ?
                        $this->performUpdate($this->newQuery()) : true;
            return $saved;             
        }
        parent::save($options);
    }  
```

Instead of newQueryWithoutScopes() performUpdate use newQuery()
And every time, an update is needed, the query with the scope will be used. 
Do you think it will have a bad behavior in some other functionality on the project? Thanks!

**Comment by justinatack** [comment]
There might be a simple way around this using validation on your update and delete routes. See the following code.

```
request->validate([
    'id' => 'required|integer|exists:users,id'
]);
```

This should trigger a SELECT query in order to validate the ID passed in the request, even if it's for an UPDATE or DELETE route. In turn this is scoped to your global query, this at least will prevent a person from updating or deleting a record that doesn't belong to them, or scope it with your requirements.

It works for me, hopefully works for you.

**Comment by ahmeti** [comment]
Ohh! Eloquent & Composite Keys 👎 
Maybe some people need it.
For Details: [https://blog.maqe.com/solved-eloquent-doesnt-support-composite-primary-keys-62b740120f](https://blog.maqe.com/solved-eloquent-doesnt-support-composite-primary-keys-62b740120f)
```php
    /**
     * Set the keys for a save update query.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function setKeysForSaveQuery(Builder $query)
    {
        // SET YOUR CUSTOM WHERE
        $query
            ->where('account_id', session('account_id'))
            ->where($this->getKeyName(), '=', $this->getKeyForSaveQuery());

        return $query;
    }
```
