### ISSUE TITLE
Validator doesnt work with deleted at

### ISSUE THREAD

**Issue by nuhh** [laravel/framework#12041]
Hello everyone,

My English might be not good. Sorry before start.

In my project, I am using validator to check if column is unique in database. Also I am using SoftDeletes which keeps values in database and insert date of deleted. So if I delete a row, and try to add again it gives me error. So validator doesnt valid with SoftDelete.

I hope, i explain everything clear.

Thanks

**Comment by themsaid** [comment]
You can do the following:
`'email' => 'unique:users,email_address,NULL,id,deleted_at,NOT_NULL'`

This will make the validator count only rows with `deleted_at <> NULL` will be included in the check, that means way only available models will be considered, but take care when you restore a deleted model you have to check other models first in order to avoid a duplication of a value that should be unique.

**Comment by nuhh** [comment]
Again, Laravel is just awesome.

Thanks :)

**Comment by nuhh** [comment]
Just in case, the last not_null supposed to be null.
