### ISSUE TITLE
Add translation.missing event

### ISSUE THREAD

**Issue by marvinschroeder** [laravel/framework#12104]
I would like to propose a "translation.missing" event fireing, when there is missing a line in the lang file. In that case we could send a notification to ourselves, that there is still something to translate. This would be really helpful if you are creating dynamic translation lines, like
`trans('sections.section-'.$section->id)`
or just forgot a line..

**Comment by GrahamCampbell** [comment]
5.1 is closed for adding events, and 5.2 doesn't use events formatted like that.

We are open to PRs to add such an event object though. Infact, in future please just jump straight to the PR stage rather than opening an issue, and discuss on slack first if needed, as per our contribution guide lines.
