### ISSUE TITLE
Cache store [wincache] is not defined

### ISSUE THREAD

**Issue by carbontwelve** [laravel/framework#12207]
The wincache driver appears to exist in Illuminate\Cache in the form of `WinCacheStore` created by the `CacheManager` method `createWincacheDriver` but due to the configuration `cache.stores.wincache` not existing, attempting to use the driver leads to a `Cache store [wincache] is not defined` exception.

**Comment by wdmtech** [comment]
Same issue here

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by arrilot** [comment]
Wincache and Xcache drivers are no longer supported.
https://github.com/laravel/framework/commit/104e138f4dd65e9cd0d4cc6fc6c3f6d5327880af

**Comment by GrahamCampbell** [comment]
You can stay on L5.1 LTS if you'd like them.

**Comment by arrilot** [comment]
@GrahamCampbell I guess those drivers were not meant to work in 5.1 either.

**Comment by carbontwelve** [comment]
@arrilot what do you mean by not meant to work?

**Comment by GrahamCampbell** [comment]
> what do you mean by not meant to work?

They were removed from the core.

**Comment by carbontwelve** [comment]
Ah, I see. I am still a little confused as to why working functionality was disabled and then removed from core but I guess it will be easy enough to write a third party driver - actually this will give me an excuse to do so :+1:

**Comment by wmather** [comment]
I was going to upgrade to 5.2 but this might be the final straw. I am happy to help out with a package, but would need some pointers on how to go about it. This is business critical for my team.

This is another example of how Taylor doesn't give a shit about anyone that uses something he doesn't. Too many of the releases in the last 18 months have been about removing previously existing features due to a different flavour of the month. 

Some visibility on the decision process would be nice. Framework additions get lavish discussions regarding the chosen solution, coding style and achieveing theoretical perfection, yet framework removals are just fair game; one day it's just.......... _gone_.

Please don't make 5.1 into the WinXP of Laravel.

**Comment by carbontwelve** [comment]
@wmather I am investigating how I would go about writing the plugin this week as I have a number of Laravel based applications being migrated to Azure.

**Comment by carbontwelve** [comment]
@arrilot that's not an unreasonable question, Azzure web apps have wincache installed by default; its a locked down IIS environment and while I could install Redis or memcache on a separate VM, link it via a VPN and then amend the php ini to install a compiled version of the required extension, it is far easier to go with what is provided given that it is good enough and already available (also I would have to do the previous steps over 50 times, once per web app, which unfortunately adds up in time.)

**Comment by wmather** [comment]
I finally got round to writing a package to add back Wincache if anyone is interested: https://packagist.org/packages/wmather/wincache

**Comment by carbontwelve** [comment]
@wmather thank you for letting us know :+1:
