### ISSUE TITLE
Eloquent firstOrCreate() doesn't work with cast attributes

### ISSUE THREAD

**Issue by cviebrock** [laravel/framework#12238]
This might be related to #5578, but if I have a model that uses `$casts`, then the `firstOrCreate()` always creates a new instance.  For example:

``` php
class MyModel extends \Illuminate\Database\Eloquent\Model {

  $casts = [
    'field' => 'array'
  ];
}

$data = [
  'field' => [1,2,3]
];

// creates a new model
$model = MyModel::firstOrCreate($data); 

//...

// also creates a new model instead of retrieving the first one
$model2 = MyModel::firstOrCreate($data);
```

**Comment by cviebrock** [comment]
Further infomation: The "find" part of `firstOrCreate` doesn't use cast attributes, but the "create" part does. So, unfortunately I can't even manually cast them before passing it to `firstOrCreate` (otherwise my array is manually cast to a string, and then cast to another string by Laravel).

**Comment by crazycodr** [comment]
It would be my first real contribution but i'll try to fix this one and see the impacts, i can't set myself as assignee though since i do not have write access to this!

**Comment by crazycodr** [comment]
I've studied the code mostly the query builder and model/builder part. If you were to always do:

```php
MyModel::where(['data' => [1,2,3])
//or
MyModel::where('data', '=', [1,2,3])
```
Then it would be feasible, but problem is that if you where to start a query from another point in the chain, then it wouldn't be possible because you would be in the context of the query and at that point we do not have the reference to the model (i think, can't be sure) but just the table name. This means we cannot cast asJson the values passed to the where at that point...

Mutators and casts are operational at the model level not the query builder level. There is maybe a way to query using a model such as creating a getRawAttributeValue function that returns the already casted / mutated value but then again, because of mutators which may alter many attributes at once, you never know if something else was modified also:

```php
$myModel = new MyModel();
$myModel->data = [1,2,3];
$raw = $myModel->getRawAttributeValue('data');
var_dump(MyModel::where('data', $raw)); //Would work
```
I'll wait for another contributor before implementing this as there is probably something better that i'm not aware of.

**Comment by Assada** [comment]
Also Eloquent firstOrCreate() doesn't work with fillable attributes too

**Comment by kyranb** [comment]
I've just run into the same issue as @Assada using firstOrCreate with a date property.

**Comment by kmccarth** [comment]
I too have noticed a similar issue with a $cast attribute that maps to a JSON column (MySQL 5.7)

**Comment by reedmaniac** [comment]
Also just ran into this issue where attribute mutators are not taken into account with firstOrNew(). So, watching this thread.

**Comment by Dylan-DPC** [comment]
I think you can close this issue and reopen it if you find it in 5.5

**Comment by reedmaniac** [comment]
The [code has not changed](https://github.com/illuminate/database/blob/master/Eloquent/Builder.php#L359) in 5.5.  I am still curious if this is considered a bug since there was a [revert of a fix](https://github.com/illuminate/database/commit/d6395aa9f7be48f716e50e4b11f9c155ae3ad9b4) back in Aug 2016

**Comment by themsaid** [comment]
Moved the discussion to https://github.com/laravel/internals/issues/856, it's very hard to say if this behaviour is wanted or not, so let's first discuss it before we say it's a bug to be fixed or is the current behaviour the one intended.
