### ISSUE TITLE
[5.2] No errors and old input after failed validation when using database session driver

### ISSUE THREAD

**Issue by htulibacki** [laravel/framework#12257]
I started new project with Laravel 5.2.14 and came across the problem described in the title. At first I thought that the problem is related to #12168, but when i changed column type, the problem still existed. I also checked solution described in #12022, but with no luck.

The problem disappears only when I change session driver (to cookie or file for example). I use  PHP 5.6.18 and MariaDB 10.1.11.

**Comment by htulibacki** [comment]
And after 4 hours I'm pretty sure that this is MariaDB issue. I also tried MariaDB 10.0.23 with the same error in result. After that I migrated to MySQL 5.5.47 and the problem disappeared.

I hope someone manages to reproduce that.

**Comment by ooiginla** [comment]
I am still also experiencing the same issue. The $errors variable is empty when $this->validate($request,$rules) fails...

**Comment by ooiginla** [comment]
this problem is related to this link: #12022 . here and @cwansart  comment seems to solve the problem

![web](https://cloud.githubusercontent.com/assets/8362020/14670645/e5c99a28-06e5-11e6-96ef-5fed1488a9f9.png)

[https://github.com/laravel/framework/issues/12022](url)

The web middleware is duplicated.
I removed the Route::group(['middleware' => 'web'], function () { }); and it works

**Comment by cwansart** [comment]
@ooiginla it seems that @JeffreyWay fixed this bug a while ago. :smile: See https://github.com/laravel/framework/commit/88d42be19a6fdc7c87d3b17bdf815080c94481c5
So I guess in new projects this should now work.
