### ISSUE TITLE
Regex validation

### ISSUE THREAD

**Issue by traubisoda** [laravel/framework#12393]
Hi!
I noticed a strange thing in 5.2: 
I've tried to validate unicode names with the following regex: /((?!\d)[\p{L} ]+)/u
I would expect any strings with digits inside to fail the validation, but since the default regex validator method only returns a preg_match, it passes (it finds the alpha part).
Is this behavior intended?

Examples:
"Unicóde string" - pass, expected
"Unicóde string99" - pass, not expected
"99" - fail, expected

**Comment by cryode** [comment]
This is more due to your regular expression than Laravel.

Your regex is only looking to see if the string _contains_ a match, rather than comparing the string as a whole to the pattern. If you add in the appropriate `^` and `$` characters to the regex, it should give the expected results:

```php
$rules = [
    'unicode' => 'regex:/^((?!\d)[\p{L} ]+)$/u',
];
```

[Here is a Regex101 example of your regex](https://regex101.com/r/pG5cM0/1), showing that the "invalid" example matches part of the string, which is good enough.

It's not really Laravel's job to enforce matching regex against the entire string. It provides the regular expression to match, it's the user's job to decide how to use it.
