### ISSUE TITLE
Middleware not being called when using implicit model binding and target is not found

### ISSUE THREAD

**Issue by adaojunior** [laravel/framework#12440]
I found that when I'm injecting a model into a controller but this model ends up not being found throwing a `ModelNotFoundException` none of my middlewares are called.
I think this happens because middlewares run after automatic model binding.

If the user is not found, it throws a `ModelNotFoundException` and no middlewares are called.
```
   public function getById(User $user)
   {
        //
   }
```

If the user is not found, it throws a `ModelNotFoundException` BUT, this time the middlewares have already being called.
```
  public function getById($id)
  {
      User::findOrFail($id);
  }
```

Of course I could always add my middlewares to the global HTTP middleware stack, but it would not serve the purpose of what I'm trying to do.

**Comment by danieliancu** [comment]
@adaojunior I too came across the exact same issue as you have.
I would like to add that adding middleware to the global stack did not solve the issue and I ended up not using implicit model binding at all and going the old way with `findOrFail()` for now.
The problem that I had was that I required access to the session in order to redirect properly after the exception was thrown and since the middleware that handles the session was not activated I was not able to use the session.

**Comment by adaojunior** [comment]
@danieliancu yes, I'll go back to the old `findOrFail()` as well.
I just saw your issue and I was going to close this one, do you think I should keep it? maybe they will reconsider ?

**Comment by danieliancu** [comment]
@adaojunior I don't remember opening an issue on this and I haven't found one.
I have only discussed it on Slack.

You should leave this issue open.
This issue tracker is limited to bug reports only and I find this issue to be a bug.

Here's why: if the global middleware stack is not activated on all requests, the middleware responsible of handling maintenance will not be activated on routes with implicit model binding, thus the application will still query the database to find a valid model with the given field even though the application is in maintenance mode.

I will take a look at the exact code to verify this right now and if it's true, then this issue must be addressed and the way to do it is to active the global middleware stack on all requests.

**Comment by adaojunior** [comment]
There's this one as well
https://github.com/laravel/framework/issues/11496

**Comment by adaojunior** [comment]
@danieliancu the global middleware stack actually runs every single request. it is only the route middlewares that don't run.

**Comment by danieliancu** [comment]
@adaojunior Yes you are right.
Thanks for referencing the issue.

**Comment by danieliancu** [comment]
@adaojunior Can you provide more details on your use case please?

Mine was to catch the exception in the application exceptions handler and redirect the user appropriately, but I needed session access and even adding session related middleware to the global stack was not working because by the time it was reaching the exceptions handler render method the session was already terminated.

**Comment by danieliancu** [comment]
I got it a little wrong on this one. If I add session related middleware to the global stack it works and I have access to the session in the application exceptions handler. But I can’t do it this way, because the session related middleware should only belong to the web group so it will not interfere with the api.

**Comment by adaojunior** [comment]
```
    public function handle($request, Closure $next, $guard = null)
    {
        $request->headers->add([
            'Accept' => 'application/json'
        ]);

        return $next($request);
    }
```
I ensure all requests to api want a json.
I also handle some exception bases on that.
