### ISSUE TITLE
BelongsToMany: detach and attach behavior

### ISSUE THREAD

**Issue by redcenter** [laravel/framework#12468]
Using both the detach and attach methods in the BelongsToMany class, I would expect the return behavior to be the same.

But the attach returns nothing and the detach returns the output from the query.

I would expect the attach to return at least something.

**Comment by Jimbolino** [comment]
I noticed the exact same thing when using version 4.2.
Was hoping it would have been fixed in a newer version, but its the same in latest version:

attach returns void
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L891

detach returns int (result of query)
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L1024
