### ISSUE TITLE
[5.2] Custom Password Resetting

### ISSUE THREAD

**Issue by browner12** [laravel/framework#12512]
While I think the scaffolding that Laravel provides for resetting passwords is great, and excellent work has been done to make it as customizable as possible, I think some tweaks could be made to give users full control over it.

There are two reason why I am bringing this up.  First off, even though a lot of customization is built in, I think it's difficult or impossible to provide all of the customization an end user could want.  The second reason is because most of us have a certain way of building our sites, and building our controllers, services, etc. With the built in password controller, now we have one spot in our app that behaves differently than every where else, which makes it a little harder on the developer (or future developers) to immediately know what's going on.

To reset a password, the programmers essentially cares about two things. Creating a unique token, and then checking that token. Emailing, updating the password, rendering views, redirecting, and the like are all more superfluous things that Laravel already makes it easy for us to do. So what I would propose is the `PasswordBroker` has 2 public methods for these things.

```php
$broker->generateToken(CanResetPasswordContract $user); //returns a string
``` 

which would create the token and store it to the database, and

```php
$broker->validateToken($credentials); //returns a boolean
```

which would validate the passed in token against the database and then delete it if valid.

While this way of handling password resets wouldn't be for everyone, it would give users who want full control these easy to use methods, and then they are required to handle everything else (emails, views, redirecting).

I just currently did basically this with a project of mine (I needed more control of the emailing), and although it was doable, it was not easy like I've grown accustomed to with Laravel. I'm assuming others may have done this as well, so looking for some feedback.

Just to be clear, I am not arguing to get rid of the current scaffolding, but rather just give tools to the users who wish to implement it themselves.

Thanks!

**Comment by danieliancu** [comment]
:+1:

I too faced these issues and I can't say I'm satisfied with how I handled them, just like you said "it was not easy like I've grown accustomed to with Laravel".

Please note that this issue tracker is limited to bug reports only. You should discuss them on Slack or forums.

**Comment by browner12** [comment]
closing this issue and moving it over to `laravel/internals`

**Comment by judgej** [comment]
I'll just add a "me too" to this (no idea where this issue has been moved to yet).

The issue I am having is generating the token. Each time a user requests a password reset, the previous token (if any) is deleted and a new one created, even if the old token is still current, i.e. has not expired. This causes *many* support calls from customers who have ISPs that are slow in delivering emails - they request a password reset multiple times when they don't get an email, and then the emails start arriving and the tokens are all now wrong, because they have been deleted by subsequent password reset requests.

L4.1 did not do this, and just resent the current token if it was still active. From L4.2, and still here in L5.2, requesting a new password reset token blindly starts by deleting any existing tokens, and that is right in the core of Laravel where it is difficulty to customise.

**Comment by judgej** [comment]
Ah, moved here: https://github.com/laravel/internals/issues/12
