### ISSUE TITLE
Add $request->inputOrNull() in addition to $request->input()

### ISSUE THREAD

**Issue by let-aurn** [laravel/framework#12568]
It would be useful to have a method that returns null if a field is not filled in on the client side.

By now, `$request->input('tag')` returns `''` instead of `null` if the field named `tag` is not filled in on the client side.

An implementation would be like

    public function inputOrNull($key = null, $default = null)
    {
        $input = $this->input($key, $default);

        return $input == '' ? null : $input;
    }

**Comment by rbadillap** [comment]
Hi, if the field named `tag` is not filled, the field is not NULL, it exists but it doesn't have any value. So it's fine that Laravel returns empty, imo.

If you need NULL by default if field are not filled, you can use something like:

```php
$request->input('tag') ?: null;
```

So if field tag are empty, it returns NULL. Otherwise it returns its value.

**Comment by lagbox** [comment]
`'' == null`

**Comment by let-aurn** [comment]
@rbadillap Yep, but don't really feel like writing this for every field I have.

**Comment by vlakoff** [comment]
Pretty sure this wouldn't be accepted. Still, you can easily add it to your application:
```php
use Illuminate\Http\Request;

Request::macro('inputNotEmpty', function ($key, $default = null)
{
    $input = $this->input($key, $default);

    return $input === '' ? $default : $input;
});
```
