### ISSUE TITLE
Geo-points support

### ISSUE THREAD

**Issue by devmsh** [laravel/framework#12635]
Is there any plan or opened issue or PR that aims to support geo-points at the database layer?

As you know, many mobile application nowadays depend on the location of the user, and there is many modules in Mysql, PostgerSQL and other DBMS that try to make is easier to manage these type of data.

If there is any interests or initial approval about the concepts, Me and my team can work on this and send a PR?

**Comment by Mevrael** [comment]
+1 point columns become popular those days and replaced old lat/long float columns, however I am still not sure about the implementation.

In my codebase I added mutators and `$model->point` returns an array with 'lat' and 'lng' keys and same format is used for assigning a new value `$model->point = ['lat' => 1.2345, 'lng' => 2.3456]` and exception thrown if invalid format is used, i.e. $model->point = 42;

Main problem is with extending select queries, where instead of `SELECT * FROM model` should be `SELECT a, b, ST_X(point) as lat, ST_Y(point) as lng, ...z FROM model` or keep it as is and use a 3rd party library to parse geo point column's blob.

**Comment by mikey0000** [comment]
Any reason this isn't going to be supported?
