### ISSUE TITLE
Feature request - change syntax for Route groups to allow caching.

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#12660]
As far as I know, currently routes can only be grouped using this closure syntax:
```
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function ()    {
        // Uses Auth Middleware
    });
```

As routes with closures cannot be cached, it follows that we can't cache grouped routes.

Why? I tried looking through other issues and the reason for disallowing closures was that all performance gain is lost when deserializing the closure. OK, but do we actually need that?

I use route groups because I have a lot of routes. And that is also the reason why I need caching. 
Do I actually need closures there? No! I need a way to make that the same middleware would be applied to many routes. Or the same prefix would be added to some or even all routes.

These things could as well be specified for every route separately. So this seems perfect for caching - I specify a bunch of routes that should have the same prefix and "caching" adds the prefix to every route. This should never actually get unserialized in the original form for execution.

Maybe this could be done by introducing some route compiling step before the actual serializing - every route in group would get the prefix/middleware tied to it individually and groups themselves would get unwrapped - then the result could be serialized without worries about closures.

**Comment by david-ridgeonnet** [comment]
I think you might have misunderstood how the Route::group works, it executes the closure straight away so the routes are generated, thus there's no closure to be cached as the routes and their associated attributes are all defined just like they would be if you had done each one separately. 

Route closures don't work like this as that closure isn't executed into the route is actually called (otherwise each page load would require every page to be "generated") so are stored as closures until needed.

Hopefully that makes sense and is accurate, you can check the code for the ::group function to see more :)
