### ISSUE TITLE
5.2.23 JSON where clauses case sensitivity and unquote

### ISSUE THREAD

**Issue by Dannybevers** [laravel/framework#12728]
Hello,

In the newest version of Laravel 5.2.23 added JSON where clauses.
I'm using it in the previous version with a lot of research like this;

`$results->where( \DB::raw( "lcase(json_unquote(json_extract(data, '$._" . $field . "')))" ), '=', strtolower( $value ) );`

With the newest version of Laravel it doesn't works properly. The sensitive case and unquote does not work in the latests framework. Is it designed as how it works on this moment or is it a bug that will be fixed in a later release?

**Comment by themsaid** [comment]
What do you mean by doesn't work?

You mean when you do:
`$results->where( \DB::raw( "lcase(json_unquote(json_extract(data, '$._" . $field . "')))" ), '=', strtolower( $value ) );`
you get different results in `5.2.23` other than `5.2.22`?

Or you mean using the new syntax `column->field->field` doesn't use `lcase` and `json_unquote`?

**Comment by Dannybevers** [comment]
Themsaid, 

My researched method too get data from my database which contains JSON data works in 5.2.22 equals as 5.2.23. But on 5.2.23 laravel support JSON where clauses i like the way too clean up my code with more readable code on the laravel method. 

The new syntax like column->field->field can't search in my database JSON column which has sensitive casing and integer/string/boolean. 

Hope this will be integrated in a later version in laravel too retrieve my data on the laravel JSON where clauses which is a cleaner way to programming opposites the \DB::raw(lcase(json_unquote(json_extract(..)))  on my way on this moment!

**Comment by themsaid** [comment]
Well the syntax is just a wrapper for the native JSON path syntax for MySQL, I believe you'll need to keep using the raw query format if you need to apply more advanced rules.

**Comment by Dannybevers** [comment]
But this wrapper function did not work for people which has case sensitive data or string/int/bool in his database. But thanks for your reaction :-)

**Comment by Rafache** [comment]
Let us imagine the table "user" :

```
-------------------------------------------
| id (INT) | datas (JSON TYPE)
-------------------------------------------
| 1        | {"name": "john", "id": 12345}
-------------------------------------------
```

`User::where('datas->id', 12345)->get();` does not return result because Laravel add quotes.
Laravel generate : 
```sql
select * from `users` where datas->"$.id" = '12345'
```

For requesting int value, you need to use : `User::whereRaw('datas->"$.id" = 12345')->get();`
Laravel will generate : 
 ```sql 
select * from `users` where datas->"$.id" = 12345
```

But the code is less readable ...

**Comment by themsaid** [comment]
Laravel generates the following from:

```
DB::table('categories')->where('name->specs', 1)->get();
```

<img width="512" alt="screen shot 2016-03-23 at 2 46 04 pm" src="https://cloud.githubusercontent.com/assets/4332182/13985307/b0621c4e-f104-11e5-8853-24767e0adad2.png">

I believe the issue is not with laravel but with how PDO binds values in general, check this out: https://bugs.php.net/bug.php?id=40740

Looks like PDO adds quotes around bindings unless you force it not to:

```
bindValue(":id", $value, PDO::PARAM_INT);
```

**Comment by mark86092** [comment]
The json query is type sensitive.
i.e. `select * from `users` where datas->"$.id" = 12345` not the same as `select * from `users` where datas->"$.id" = '12345'`
