### ISSUE TITLE
5.2.23 Arr::get backwards compat - array_key_exists() expects parameter 2 to be array

### ISSUE THREAD

**Issue by claar** [laravel/framework#12725]
The changes in v5.2.23 changed the behavior of `Arr::get()`, thus breaking the fairly popular Laravel Former package I maintain.

In Laravel 5.2.23, `Arr::get()` no longer supports `null` in its `$array` argument:

```bash
$ composer require laravel/framework 5.2.22 # [ output snipped ]
$ echo 'array_get(null, 4);' | php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.15 — cli) by Justin Hileman
=> null
$ composer require laravel/framework 5.2.23 # [ output snipped ]
$ echo 'array_get(null, 4);' | php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.15 — cli) by Justin Hileman
PHP warning:  array_key_exists() expects parameter 2 to be array, null given in
  [path snipped]/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 145
```

While we can debate the merits of passing in null arrays to `Arr::get()`, this backwards compatibility breakage may affect a decent number of folks.

**Comment by claar** [comment]
Reported to Former at https://github.com/formers/former/issues/514

**Comment by taylorotwell** [comment]
@vlakoff would this be related to your various Arr changes?

**Comment by vlakoff** [comment]
I think this is because of https://github.com/laravel/framework/commit/41aec8abcc86e1bee4d72c3bb86173368458df11.

Before:
* Test `isset`. False, so go on.
* Enter the `foreach` loop which does `static::accessible` && `static::exists`. False, so return default.

After:
* Test `static::exists`. Doesn't work because expects `array` or `ArrayAccess`.

But: Why the hell is `null` passed to `Arr::get()`?!? This is not expected! Note that previously it would have broken the same if `Arr::has()` had been used.

I should have a look at code of Former. But I repeat, you shouldn't have passed `null` to `Arr::get()`!

**Comment by crynobone** [comment]
Thank you for unexpected breaking change on a patch release.

**Comment by lagbox** [comment]
@vlakoff well obviously, but the previous behaviour did allow for it (and people will do it). All of this should just be changed in 5.3.

**Comment by vlakoff** [comment]
PR #12726.

**Comment by mark86092** [comment]
The PR is merged. Waiting for the new release.
