### ISSUE TITLE
Which laravel/homestead commit points to box 0.3.3?

### ISSUE THREAD

**Issue by morfin** [laravel/framework#12865]
Laravel/homestead 2.2.1 release points to 0.3.0
```
config.vm.box_version = settings["version"] ||= "<= 0.3.0"
```

I need the release that points to 0.3.3, any idea?

**Comment by c0defre4k** [comment]
Checkout 9b22c56920b268a068f5e645f88de5630737407e. It worked fine for me when using box version 0.3.3.

**Comment by sisve** [comment]
You want the 2.0 _branch_, not the 2.2.1 _tag_.
If you really want the 0.3.3 machine, and not any future 0.3.4 upgrade, specify "version = 0.3.3" in your Homestead.yaml file (which still requires the 2.0 _branch_ since the scripts are made for that machine)
https://github.com/laravel/homestead/blob/2.0/scripts/homestead.rb#L14
