### ISSUE TITLE
Universal mail not working for bcc and cc mails.

### ISSUE THREAD

**Issue by ankitjain0269** [laravel/framework#12965]
Universal to is not working in case of bcc and cc mail, all  (to) mail goto universal mail only but it is not working in case of bcc and cc.

**Comment by GrahamCampbell** [comment]
I don't understand your question. We only have code for global to and from, and nothing else.

**Comment by sebestenyb** [comment]
Hi Graham,

I understand what he mentions:

See documentation: https://laravel.com/docs/master/mail#mail-and-local-development

> When developing an application that sends e-mail, you probably don't want to actually send e-mails to live e-mail addresses. Laravel provides several ways to "disable" the actual sending of e-mail messages.
> 
> Universal To
> 
> Another solution provided by Laravel is to set a universal recipient of all e-mails sent by the framework. This way, all the emails generated by your application will be sent to a specific address, instead of the address actually specified when sending the message.

I think it clearly says that **all** email will be sent to this **Universal To** set in the config, instead of the real address set. 

But if you have a _CC_ or _BCC_ field set, then only the _To_ field will be changed to the _Universal To_, the real _CC_ or _BCC_ recipient will still receive the email.

Probably this limitation should be mentioned in the documentation.

Cheers, Sebi

**Comment by ankitjain0269** [comment]
@sebestenyb, yes this is what I was trying to say.

**Comment by makuser** [comment]
@GrahamCampbell why did you close this? IMO this is a valid bugreport.

**Comment by devcircus** [comment]
Check PR #16705. This fixed the issue.

**Comment by makuser** [comment]
Wonderful. Thanks @devcircus!
