### ISSUE TITLE
Out-of-the-box Auth applies middleware twice

### ISSUE THREAD

**Issue by JThompson1123** [laravel/framework#12979]
I upgraded from 5.2.27 to 5.2.28 less than an hour ago. I noticed that all of my authentication routes have double middleware:

Login: middleware = web, guest, guest etc

My own routes are fine.

Any help?

**Comment by mdecooman** [comment]
I tried with a new install a laravel: do a `php artisan make:auth`, then do a `php artisan route:list` and voila.  double auth and guest middlewares:
<img width="982" alt="screen shot 2016-04-02 at 11 20 53 am" src="https://cloud.githubusercontent.com/assets/16573697/14225272/817f3c22-f8c5-11e5-821b-d1470bca7925.png">

**Comment by hiendv** [comment]
Upload your `routes.php`.

**Comment by vis-bp** [comment]
This happens if you explicitly include the web middleware in your routes.php. The web middelware is autmatically included for these routes (https://laravel.com/docs/5.2/middleware#middleware-groups). 
The issue has been discussed in https://github.com/laravel/framework/issues/12022 as well. As stated in that issue some seconds ago, the quickstart examples need to be updated since they contain the double loading as well.

**Comment by hiendv** [comment]
I got it.
https://github.com/laravel/laravel/commit/5c30c98db96459b4cc878d085490e4677b0b67ed
