### ISSUE TITLE
Dirty eloquent models sometimes don't reload from DB as expected

### ISSUE THREAD

**Issue by peterkinnaird** [laravel/framework#13055]
I have a model `User` that `hasOne('CustomerAccount')`. `CustomerAccount` has some properties, such as `credit_card_id` and `charge_amount`.

The following code produces: `ErrorException: Creating default object from empty value` on the `$account->charge_amount` line.

```
$user = User::find($id);
$customerAccount = new CustomerAccount;
$customerAccount->user_id = $id;
$customerAccount->credit_card_id = $card_id;
$customerAccount->save();
$account = $user->customerAccount;
$account->charge_amount = 10;
$account->save;
```

This is not my actual code which uses several functions, but should be sufficient to explain the problem.

It's fixable by adding `$user = User::find($id);` immediately after `$customerAccount->save();`

I think `$user` should be marked as dirty when it's related object, `CustomerAccount` saves.

**Comment by GrahamCampbell** [comment]
Thanks for the issue, but I personally disagree that we should change the current behaviour. Let's see what other people think, inc @taylorotwell.

**Comment by peterkinnaird** [comment]
I'd suggest that it's fair for a developer to always assume that properties and relations on their model are accurate to what's in the database as soon as a `save` call has been made. I understand why that's not the case here (the foreign key is on the dirty model), but think it's surprising.

**Comment by trevorgehman** [comment]
I assume this doesn't happen if you did:

    $customerAccount->user()->associate($user);

instead of 

    $customerAccount->user_id = $id;

Am I wrong about that?

**Comment by peterkinnaird** [comment]
@trevorgehman great question. I tend to avoid that construction because it's always felt a little clumsy to me.

**Comment by HolgerW1** [comment]
Imho what @trevorgehman describes is the 'proper' way to do it in Eloquent since that's how you handle relationships. Setting the foreign keys manually bypasses the whole relationship handling and is more like a low level connection.

Imho the code you describe should not automatically touch your user instance, that's what the `touches` property is for.
A general rule about relationships in Eloquent is that the parent doesn't really know much about its relationship models or what operations were executed on them.

Here are a few examples:
* `$post = $user->post()->create(['name' => 'First Post']);` 
If you immediately try to access `$user->post` after invoking this command the relationship won't be set on `$user` and will be loaded from the DB even though you just created it yourself. I.e. `$user->post` won't be the same instance as `$post` and an extra DB call will be made.

* `$user->post()->delete();`
If the _post_ relationship was loaded before the statement `$user->post` it will not return `null` as you might expect. I.e. you will get a zombie instance which doesn't have a persistent representation in the DB.

* Deleting a parent model won't delete its relationships, i.e. `$user->delete()` will not delete the `post` of the user and Eloquent doesn't provide any automatic mechanism to handle relationship deletions when the parent gets deleted. That's especially problematic if you can't use foreign key constraints.
