### ISSUE TITLE
Rawquery using where in clause 

### ISSUE THREAD

**Issue by ezekel** [laravel/framework#13141]
I have this raw query but I am having problem if I will use the where in clause there is no output . I tried my query manually in mysql editor and it shows output.

`
 DB::select(" SELECT ud.id,ud.project_id,ud.user_name,pr.created_at
        from user_project as ud
        INNER JOIN
          (  
             SELECT project_id , MAX(created_at) AS latest FROM project GROUP  BY project_id 
          ) AS dx 
        ON dx.project_id = ud.project_id
        INNER JOIN project AS pr
        ON pr.project_id = dx.project_id  AND pr.created_at = dx.latest 
         where  ud.user_id = ? AND ud.project_id in ( ? )  ", $id, $pojectarr);
`

Thank you in advance.

**Comment by ezekel** [comment]
someone help me on this please

**Comment by WindSaber** [comment]
@ezekel Issues section is not a forum, there are other sites as stackoverflow. Please read [https://laravel.com/docs/5.2/contributions](url)

Anyway it seems you have added your variables as parameters instead of an array

I recommend you to read documentation first before reporting an issue [https://laravel.com/docs/5.1/database#running-queries](url)

**Comment by ezekel** [comment]
@WindSaber ,

Yes I know that I passed $projearr
`
$projearr = '000004455,0000088888';
`
and I change the parameter in last part.

, [$id,$projearr] ); // still no output, I have problem in  the IN clause in using DB::SELECT
