### ISSUE TITLE
[Lumen 5.2.6] Can't run migrations after the latest update 

### ISSUE THREAD

**Issue by adrian7** [laravel/framework#13340]
I'm using lumen framework with pgsql. I am running migrations with the using 

    php artisan migrate --path=vendor/package/migrations

They were running fine until I updated today my packages, and even I do a rollback I get the following error:  
![untitled](https://cloud.githubusercontent.com/assets/225180/14857838/95707c80-0c95-11e6-8064-009421f35af3.png)

    lumen.ERROR: exception 'PDOException' with message 'SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "db_migrations" already exists' in /var/www/vendor/illuminate/database/Connection.php:408

`migrate` runs without any issues after deleting the `db_migrations` table. However still have to delete the db_migrations in order to run it :(

**Comment by themsaid** [comment]
When you run `artisan migrate` laravel checks for the presence of the migrations table, if not present then it attempts to create it, just today an update to `Illuminate\Database` was released, it fixes an issue with how laravel checks for table existence in postgres.

Before the update the check for table existence was done using the following query:

```
select * from information_schema.tables where table_name = ?
```

So it checks if the table exists, and would return true even if the table existed in a schema other than the one you are currently using. After the fix the query becomes:

```
select * from information_schema.tables where table_schema = ? and table_name = ?
```

It's using the schema name as in `conifg/database.php` for `pgsql`, by default the schema is set to `public`.

I assume that the table was created before on a different schema, and it was found only because it exists anyway, but now after the fix it'll look only into the schema you're connected to.

**Comment by adrian7** [comment]
Hmm, I can't find the table in any other schema. 

    select * from information_schema.tables where table_name = 'db_migrations'

Returns one row only.

**Comment by themsaid** [comment]
Make sure the returned table exists in the schema configured in your config file.

**Comment by adrian7** [comment]
I don't have any schema configured... was supposed to use the default one right?

**Comment by themsaid** [comment]
yes it should be `default`

**Comment by themsaid** [comment]
I just noticed you're talking about Lumen not laravel, I'm not sure how it's configured in Lumen.

**Comment by adrian7** [comment]
Right, setting `'schema'    => 'public'` in _config/database.php_ solved the issue. I assume the schema is set to NULL in Lumen for some reason.

**Comment by themsaid** [comment]
I think Lumen by default points to the `public` schema, https://github.com/laravel/lumen-framework/blob/5.2/config/database.php#L83

**Comment by themsaid** [comment]
@adrian7 still can't figure it out?

**Comment by GrahamCampbell** [comment]
Thanks, but this doesn't look like a bug in the laravel core. Feel free to keep discussing though.

**Comment by adrian7** [comment]
Thanks, @GrahamCampbell. I'll try to reproduce the issue on a fresh install.
