### ISSUE TITLE
TokenGuard can't work out of the box, as it misses attempt() & login() functions

### ISSUE THREAD

**Issue by ShadyAbuKalam** [laravel/framework#13421]
In `RegistersUsers` and `AuthenticatesUsers` traits, `attempt()` & `login()` functions are used on the returned guard. 
In case of `TokenGuard`, It just throws an error complaining that `TokenGuard` don't have these methods.
I have checked `SessionGuard` , it has these methods.
I think `TokenGuard` must be altered to implement `StatefulGuard`.. But I feel it's like an odd ball solution

**Comment by golonix** [comment]
`RegisterUsers` and `AuthenticatesUsers` traits are just helpers/shortcuts for controllers to handle user registration and basic authentication. There are methods like `showRegistrationForm` or `postRegister` which are self-explanatory. It is quite obvious that there should be stateful-like guard used, thus I don't understand your need to use `TokenGuard` here. Token-based authentication is done in completely different way. It is stateless by definition. You should read a bit more about it. It is very interesting topic.

**Comment by malhal** [comment]
To use the TokenGuard you have to make an APILoginController subclass of LoginController that instead returns the api_token, requires re-implementing a few of the trait methods. Then on further requests to your API routes just include the api_token query param, then in your controller you can do Auth::guard('api')->user(); to get the user. And if you want routes blocked if there is no user then you can enable the 'auth:api' middleware on api-routes.  To allow the api/login route to work you have to disable the  'auth:api' in RouteServiceProvider otherwise you are guarded from evening logging in which appears to be a bug in the current Laravel 5.3.

**Comment by themsaid** [comment]
Closing since it's not really a bug report. Thanks!
