### ISSUE TITLE
Add explicit set(attribute, value = true) method to Fluent

### ISSUE THREAD

**Issue by danilcha** [laravel/framework#13481]
To add an attribute to ``Illuminate\Support\Fluent`` we have to use magic methods. Contemporary IDEs don't like that. I would rather write ``.add('nullable').add('index')`` than ``.nullable().index()``, because it is more explicit (I am more careful with strings than with method calls because in the latter case I have IDE/runtime that can tell me I made a typo).

It will also make the API more consistent and predictable, because ``Fluent`` already has an explicit ``get`` method. The same with ``Request``—I can either use magic methods or ``$request->input('name')``, which I prefer.

**Comment by JeroenVanOort** [comment]
This probably won't happen unless you make a PR for it. Since the feature you request isn't in Laravel now, many have apparently done fine without it, like myself. It isn't a minor thing either; I guess it will take someone the best part of an afternoon to get this right and I don't think the person is going to invest that time in something that might be nice to have but isn't a major improvement to most users.
