### ISSUE TITLE
InvalidArgumentException in SQLiteConnector.php / Database (xxx/xxx.sqlite) does not exist.

### ISSUE THREAD

**Issue by jrean** [laravel/framework#13491]
This is how I encounter the issue:

Laravel Framework version 5.2.31

`xxx.sqlite` into `database` directory

`config/database.php`

```
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('SQLITE_DB_NAME', database_path('database.sqlite')),
            'prefix' => '',
        ],
```

.env

```
SQLITE_DB_NAME=xxx.sqlite
```

> `php artisan migrate:status`

```
[InvalidArgumentException]
  Database (xxx.sqlite) does not exist.
```

.env

```
SQLITE_DB_NAME=database/xxx.sqlite
```

> `php artisan migrate:status`

```
+------+--------------------------------------------------+
| Ran? | Migration                                        |
+------+--------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table             |
| Y    | 2014_10_12_100000_create_password_resets_table   |
+------+--------------------------------------------------+
```

Into a Controller

```
    public function store(XxxRequest $request)
    {
        $this->xxx->create($request->all());

        return redirect()->route('xxx');
    }
```

```
InvalidArgumentException in SQLiteConnector.php line 34:
Database (database/xxx.sqlite) does not exist.
```

Trace:

```
in SQLiteConnector.php line 34
at SQLiteConnector->connect(array('driver' => 'sqlite', 'database' => 'database/xxx.sqlite', 'prefix' => '', 'name' => 'sqlite')) in ConnectionFactory.php line 61
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure)) in Connection.php line 868
at Connection->getPdo() in Connection.php line 736
```

If php artisan command is able to read the DB we should have this error?!
I'm still trying to trace the error with a debuger.

J.

**Comment by fhb12345** [comment]
is there a xxx.sqlite file inside your database folder? usually you should cd there and create one (empty file), at least thats what it seems to be Database (database/xxx.sqlite) does not exist.

**Comment by GrahamCampbell** [comment]
Please create the file.

**Comment by jrean** [comment]
The file is created!!
The PHP artisan command read the file... Please give it more attention

Jean

**Comment by GrahamCampbell** [comment]
You're using `/database/database`. Remove the extra `database` from the path.

**Comment by jrean** [comment]
@GrahamCampbell if in the `.env` file I put `SQLITE_DB_NAME=xxx.sqlite` the php artisan command `php artisan migrate:status` returns:

```
[InvalidArgumentException]
  Database (pranacanal-dev.sqlite) does not exist.
```

and the controller call doesn't work and returns the `InvalidArgumentException in SQLiteConnector.php / Database (xxx/xxx.sqlite) does not exist.`

If in the `.env` file I put `SQLITE_DB_NAME=database/xxx.sqlite` the php artisan command `php artisan migrate:status` returns:

```
+------+--------------------------------------------------+
| Ran? | Migration                                        |
+------+--------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table             |
| Y    | 2014_10_12_100000_create_password_resets_table   |
```

but the controller call returns: `InvalidArgumentException in SQLiteConnector.php / Database (xxx/xxx.sqlite) does not exist.`

Please try to reproduce, there is something wrong somewhere.

**Comment by fhb12345** [comment]
You should actually pass an absolute path instead of just xxx.sqlite, according to the docs:

DB_CONNECTION=sqlite
DB_DATABASE=/absolute/path/to/database.sqlite

the default value is database_path('database.sqlite') probably if you change
'database' => env('SQLITE_DB_NAME', database_path('database.sqlite')),
to 
'database' => database_path(env('SQLITE_DB_NAME', 'database.sqlite')),

it would work...

**Comment by jrean** [comment]
@fhb12345 thanks for the input. Making it working is not a problem, I'm just trying to highlight something weird. By default we shouldn't change how the config file is written... It should work out of the box.

I ask you just to try and to reproduce. If the artisan command is reading the database file the entire application should read it.

**Comment by fhb12345** [comment]
@jrean I don't think that we should change the config file, it's actually intended to be this way, otherwise if the sqlite file is not inside the database folder then the config file would need to be changed, for a quick working sqlite database there's also the option of using the default database.sqlite, this way you just remove the DB_DATABASE from the .env file and create an empty file database.sqlite inside the database folder and you're ready to go.

I use sqlite only for small developments, so i don't really know why you would need a sqlite file outside the database folder (maybe if its for sharing purposes), but there's definitely a reason for it...

**Comment by jrean** [comment]
I don't want an sqlite file outside of the database directory, I just highlight there is something not working out of the box. Please try, follow the steps described and see.

**Comment by fhb12345** [comment]
@jrean It works out of the box, you just need to provide the absolute path, if your laravel installation is inside /var/www/laravel for example you should then pass:

DB_CONNECTION=/var/www/laravel/database/xxx.sqlite

It also works without needing to change the config file, however since i don't know where is your laravel installation modifying the config file was a better solution since it would work no matter where the laravel is.

**Comment by jrean** [comment]
trying to say that according to the document we should use: `DB_DATABASE=/absolute/path/to/database.sqlite`

But if you don't, if you use `DB_DATABASE=database/database.sqlite` then the php artisan command `php artisan migrate:status` will read the DB but the application won't.

**Comment by fhb12345** [comment]
@jrean If you have laravel in /var/www/laravel, database/database.sqlite results in many different paths,

**artisan is inside /var/www/laravel **so he will try to use the /var/www/laravel/database/database.sqlite file, which exists and works...

**the connector is not inside /var/www/laravel** so he will try to access /var/www/laravel/connectorSubfolders/database/database.sqlite and this file will not exist, thats why you need an absolute path, this is a common behavior.

As of now artisan is a helper, not a tool to use to find out if the installation is working as intended, so there's no problem if he runs meanwhile the system doesn't. Maybe in the future there will be a command to verify if the installation is working and theres a db connectionas of now you can't rely on artisan for this...

**Comment by jrean** [comment]
@fhb12345 thanks a lot for the comment. I'm not trying to use artisan commands to test a database connection. I just configured a new app, added a test database and used the artisan command to check something. As expected the connection worked and artisan read the database. Later I tryied to perform a crud action and noticed the database couldn't be read with the given error...

I just tried to dig and was surprised because almost anything into Lavarel is aligned and I found this behaviour weird...

Btw, great idea to have a command to check a database connection.
