### ISSUE TITLE
Elixir helper method returns absolute path to server web root

### ISSUE THREAD

**Issue by bjhansen-ualr** [laravel/framework#13490]
I noticed that when I used the Elixir helper function it returns an absolute path to the root of the server. I have a project that's located in a directory (http://server.test/project) and couldn't get my versioned css and js files to be loaded correctly.

In Illuminate\Foundation\helpers.php line 349 I changed
`return '/'.$buildDirectory.'/'.$manifest[$file];`
to
`return url($buildDirectory.'/'.$manifest[$file]);`
so that it would return a path relative to where my project is located.

This was the only way I found to get my project to correctly reference my versioned build files and it seems to me that the `url()` helper method should've been used here to begin with.

**Comment by GrahamCampbell** [comment]
This has been suggested loads of times. Not sure why it's not changed in L5.3 yet. Ping @taylorotwell.

**Comment by it-can** [comment]
But how would you handle a custom domain for a file? I have some css on a CDN, so what I do is:

```
function cdnUrl()
{
    return (config('settings.cdn')) ?: url('/');
}

function elixirCDN($file)
{
    return cdnUrl() . elixir($file);
}
```

When the elixer() function automatically include url() this will not work anymore...

**Comment by fhb12345** [comment]
Maybe elixir could accept an url?

Like this:
```php
return elixir($file, $assetsUrl, $buildDirectory);
```

This way elixir would use the relative path as the default one or the url path provided as the parameter.

**Comment by fhb12345** [comment]
@it-can Maybe the elixir function could support a new parameter;

```php
function elixir($file, $customUrl,$buildDirectory = 'build')
```

This way the return would check if the parameter exists or use the url() by default

```php
return url($buildDirectory.'/'.$manifest[$file]);
```

This way you could just call this in your function:
```php
return elixir($file, cdnUrl()); //breakable change
//or
return elixir($file, 'build', cdnUrl()); //not so pretty
```

**Comment by it-can** [comment]
@fhb12345 I think changing the function with ```url()``` function and even adding a url parameter to the ```elixir()``` function is breaking...

**Comment by fhb12345** [comment]
@it-can The parameter could be added as the third parameter and instead of using url() by default it could be used a config file with this you could:

1 - Edit the config file and add a cdn url, all of the elixir functions would get the files from your cdn with no need of any parameter.
2 - Have a custom parameter in case you need to use cdn just for a few files or have multiple cdn's (one for your site and another for your dashboard). 

Then the change would not break, for new installations the config parameter could be set to url('/'), for older ones it would not exist thus it would be a '' and the elixir would work as it's working today...

**Comment by GrahamCampbell** [comment]
This has come up before. It's probably easier for people to just make their own function which exactly fits their individual requirements.
