### ISSUE TITLE
Redis tagged cache using a lot more storage since upgrading from 5.2.12 to 5.2.28

### ISSUE THREAD

**Issue by HughNoble** [laravel/framework#13675]
We use tagged redis cache to power a custom page cache implementation and since upgrading from Laravel 5.2.12 to 5.2.28 our Redis instance has been filling up within a matter of hours (it was previously running for > 6 months without filling up). We have cleared our instance since the upgrade and each time we do this it fills up within a few hours.

Here's an example of what it was doing vs what it's doing now. Same application code for both, different Laravel version.

**5.2.12**
- tag > {page_cache_tag} = 57446252aca8d812554263
- 71f15aa7ad3a126cfabdebe2e99ebec0b86e171f > {expected_end_result}

**5.2.28**
- tag > {page_cache_tag} = 5744602c7e054020397443
- 5744602c7e054020397443 > 5744602c7e054020397443:standard = list. List item 1 = {final_page_cache_key}
- {final_page_cache_key} = {expected_end_result}

For the 5.2.28 version the middle key seems to store a reference to each tag which uses the key stored within it. So if there are 2 tags which relate to 2 keys it will store 4 items in that reference stage.

It's the keys in that middle step which are filling up our instance.

If more information is needed let me know and I'll try to get it.

**Comment by GrahamCampbell** [comment]
Can you pull in the person who made the Cache tags changes here please.

**Comment by HughNoble** [comment]
I think I may have tracked down the commit.

https://github.com/laravel/framework/commit/36abed903fabaeb5f48620b7f83f40b459508ec5#diff-9f5d8af92b58ba2f54dd31cc674f3f1c

Related to this bug.

https://github.com/laravel/framework/issues/9967

**Comment by GrahamCampbell** [comment]
Ping @mstephens, @taylorotwell.

**Comment by GrahamCampbell** [comment]
Note:

#### THIS ALSO AFFECTS L5.1 LTS TOO

**Comment by GrahamCampbell** [comment]
Related PR: https://github.com/laravel/framework/pull/12178.

**Comment by mstephens** [comment]
@taylorotwell @grahamcampell 

This was the fix I made to Laravel caching a short while back, that was then reverted as one person moaned loudly about having to clear the cache when upgrading.

Laravel has a bug with how currently the cache tags uses array storage, using lrange and not list. I can't dig my commits out right now as away from pc. As said it duplicates the referenced cache file when storing tags in the cache. 

My first commit was to introduce cache tags (using old method of Laravel which is live) as Laravel did with forever tags. (standard tags didn't used to work from day one). 

The second commit improved both forever (which was already in Laravel from day one) and standard tags however was reverted as it wasn't deemed a bug fix. This I believe was put back to 5.3. 

The reason it hasn't been noted before now it Laravel never used to store cache tags for standard tags (although it should). I patched the second fix as I too had noticed Laravel consuming too much space. 

Maybe do not be too quick blame next time :)

**Comment by taylorotwell** [comment]
Nobody is blaming anyone.

**Comment by GrahamCampbell** [comment]
Yeh, I pinged you to get your expertise, not to complain you broke something. ;)

**Comment by mstephens** [comment]
Ok. I just felt a little deflated when my last pull request was rejected and not deemed a genuine bug :). You guys do such a good job by the way ! It must be hard to manage such a project :) 

As for the issue. Either the workaround I patched previously would need to be re-introduced with a note to flush the cache, as the upgrade is performed or the issue continues. The extra cache data is stored in a single Redis cache item. 

@HughNoble do you use tagging extensively? Did you notice prior to 4 months ago (5.2.23 I think) that tagging didn't work? Would be interested to hear if you flush via cache tags as this wil have improved tagging performance with the first commit.

**Comment by HughNoble** [comment]
@mstephens we do use tagging extensively. We use it for a custom page caching module for which the html for pages can be cached with multiple tags so that by clearing one of those tags the content gets invalidated. Due to the complexity of our application each page could have upwards of 30 tags. So there are a lot of tags flying around in our instance. 

We hadn't noticed that it wasn't working, although if I understand your commit the issue was that the end cache key wasn't cleared when the tags were cleared. Our instance had not become full so this hadn't become an issue for us yet.

**Comment by johnboy-leeds** [comment]
Just to elaborate on what @HughNoble said (I am a colleague of his) about the way we have been working with the Redis cache. We run a platform provided over 20,000 sports club websites. For scaling we developed a middleware that caches HTML responses into Redis and returns the response direct from cache for the next identical request (we looked into using Varnish etc for this but due to the nature of our application it wasn't a good fit).

### Storing an item into the cache
We would save the HTML of the homepage on website A tagged with `news` and `fixtures` (in reality the number of tags may be quite a few more)
```
Cache::store(config('our_redis_store'))
    ->tags(['website_a', 'website_a_news', 'website_a_fixtures'])
    ->put('website_a_homepage', '<html>...</html>', 43200);
```

and the latest news page tagged with just `news`
```
Cache::store(config('our_redis_store'))
    ->tags(['website_a',  'website_a_news'])
    ->put('website_a_latest_news', '<html>...</html>', 43200);
```


Website A would then publish a new news item which would trigger a job to flush the cache all the pages that show latest news (in this example both the latest news page and the homepage) with the following
```
Cache::store(config('our_redis_store'))->tags(['website_a_news'])->flush();
```


### What has changed our end

We had been running this with no incident for around 6 to 9 months with some rather hefty traffic. However we recently updated Laravel from 5.2.12 to 5.2.28 and within 24 hours or Redis instance was falling over as the number of items being stored seems to have increase exponentially.

**Comment by mstephens** [comment]
Hi guys 

Yep that's correct until the fix referenced above, Laravel didn't clear cache tags for standard (not forever) tags. This meant the items just stayed there but also lead to inaccurate cache. 

I guess perhaps you didn't notice as you mentioned traffic wasn't so high then. Also with a new cache write with the same id they'd be overridden. The first fix just mirrored how Laravel already handled tagging for forever tags. 

Later as you found, I also discovered the same problem and fixed it. It was released but then reverted. I believe @grahamcampbell said this would be ported to 5.3. Here's the commit, https://github.com/mstephens/framework/commit/58f4041323245037a599b5814a3c889da1b64f5b it's a very simple fix and stores unique values. 

I'm not sure of 5.3 release date (think it's June) but perhaps you could temporarily fork the fix (hacky I know). :/

**Comment by GrahamCampbell** [comment]
> I'm not sure of 5.3 release date (think it's June) but perhaps you could temporarily fork the fix (hacky I know). :/

Yeh, it'll likely be June. Taylor's not make a public announcement yet I don't think.

**Comment by taylorotwell** [comment]
Do we have discussion anywhere of why @mstephens PR was reverted? I don't remember why users had to flush the cache? Can someone refresh my memory?

**Comment by HughNoble** [comment]
@taylorotwell Looks like the discussion's on the original pull request for the fix which was reverted. https://github.com/laravel/framework/pull/12733

**Comment by taylorotwell** [comment]
So is that PR all that needs to be done to fix this issue?

**Comment by ryanabrams** [comment]
I've been dealing with this exact issue for a while now, with cache tags filling up and bringing down our instance. I narrowed it down to the use of lists - if I use two tags (A & B) on a key (X), then flush tag B, it's removing X, then when re-caching X, it's re-inserting the key X into tag A every time. Thus A is continually growing with duplicate X keys, and either fills up the cache instance, or causes the application to fail on flushing tag A as the list of keys is larger than the php memory limit.

That PR ( #12733 ) fixes the issue by implementing the exact same solution I was about to: using native redis sets to eliminate any chance of duplicate entries in a tag, and thus eliminating the redundant and detrimental list growth. It fixes a major issue with tags and redis, and is needed as soon as possible.

That said, this change is also breaking, in that it will require a cache flush upon upgrading. Otherwise the application will attempt to read from a redis list using a redis sets command, and fail.

One option would be to salt redis cache keys differently as a part of the PR, so that they all change and use sets and the lists are just left to get cleaned up by redis. That's ugly for lots of reasons, but it would make this a non-breaking change.

**Comment by HughNoble** [comment]
The other option would be to also revert https://github.com/laravel/framework/pull/12178, this would fix the tag storage issue albeit at the expense of reintroducing the original bug with cache keys not being removed. And then reintroduce both in 5.3 as a breaking change.

Although would changing the `REFERENCE_KEY_STANDARD` constant to a different value stop this being a breaking change?

**Comment by taylorotwell** [comment]
While the change is breaking, is it technically a bug fix? Obviously we want to be careful about breaking anything mid release cycle but if it's to fix a genuine bug it may be something worth considering?

**Comment by mstephens** [comment]
Hey guys as @ryanabrams says, the fix changed the way Redis stores the cache in unique lists. 

When I made the change as said there was no easy way to eliminate a migration without some kind of work around. Although as you see in the comments on the referenced pull request, I believed it a bug, hence back porting to 5.1. 

As said the constant above could be changed which then wouldn't error about invalid storage types. However the forever one will also need to be changed too. Perhaps some kind of further prefix for now. I did refactor the code so they both use the same internal logic besides their key name. 

Happy to assist although away from a pc for a few days!

**Comment by ryanabrams** [comment]
Yeah. If you change `REFERENCE_KEY_STANDARD` and `REFERENCE_KEY_FOREVER`, you can merge this without it throwing exceptions for people otherwise unaware of the problem. The downside is that everyone's tags would start from scratch, so it would essentially be faking a cache flush. Which will create the same downside for users relying on tagged redis cache keys.

That said, there is no question that this is a bug fix, for a rather critical bug. I think it technically qualifies as backwards compatible, since it's not changing any API code or calls, so it is viable. But there is ultimately no getting around the fact that this change requires resetting redis cache tags, one way or the other, and that may affect some users.

**Comment by mstephens** [comment]
Yeah agree 100%. Recommend merging in my pull requests so that you get the new tests too then applying the constant fix.

**Comment by taylorotwell** [comment]
So the only thing we need to merge is #12733 right?

**Comment by HughNoble** [comment]
Yes, although we could also merge in https://github.com/laravel/framework/pull/13730 to stop people's applications breaking when they update.
