### ISSUE TITLE
Query\Builder::whereRaw() doesn't accept parameters

### ISSUE THREAD

**Issue by guoyunhe** [laravel/framework#13679]
I have the following code and expect to pass `$search` into the raw query:
```php
$tags = Tag::whereHas('translations', function ($query) use ($search) {
    $query->whereRaw("MATCH(`name`) AGAINST(? IN BOOLEAN MODE)", [$search]);
    echo $query->toSql();
})->get();
```
SQL dump:
```sql
select * from `tag_translation` where `tag_translation`.`tag_id` = `tag`.`id` and MATCH(`name`) AGAINST(? IN BOOLEAN MODE)
```
The `?` is not replaced by `$search`.

Cannot find useful document about the `whereRaw()` function. Is here any good way to excute a raw SQL for fulltext index?

**Comment by guoyunhe** [comment]
Found my problem. The query won't fill `?` with bindings until it is executed.

**Comment by sprov03** [comment]
There is a way to still get the whereRaw to work.
I still uses pod binding under the hood, so instead of ? replace it with :search

$tags = Tag::whereHas('translations', function ($query) use ($search) {
    $query->whereRaw("MATCH(`name`) AGAINST(\:search IN BOOLEAN MODE)", [$search]);
    echo $query->toSql();
})->get();


This is not documented i just figured that it would work and gave it a try when i ran into the same problem.

**Comment by sprov03** [comment]
Use Select Raw instead its a pain because you have to do the entire query by hand but at least you still get pdo binding.
