### ISSUE TITLE
Eloquent isDirty not checking properly numbers

### ISSUE THREAD

**Issue by iget-master** [laravel/framework#13742]
Hi,

I found this issue with Eloquent's `isDirty` method: 

Checking a numeric field MySQL `DECIMAL(12,2)` where the original value is dumped as:

`STRING(5) "14.00"`

and the dirty value is

`INT(14)`

The field is marked as Dirty, but it is not dirty, since `14.00` is same numerically that `14`.

I didn't verified yet, but found the problem may be on `originalIsNumericallyEquivalent` method, that does a cast to string and compare the both values using `strcmp`.

**Using Laravel 5.1.35 (LTS)**

**Comment by iget-master** [comment]
This does not look the same issue as #8972, isn't a eloquent casting problem. It's a problem when checking originalIsNumericallyEquivalent.

I've made a workarroud by overriding the method on my Model by this one:

```
    protected function originalIsNumericallyEquivalent($key)
    {
        $current = $this->attributes[$key];
        $original = $this->original[$key];
        return is_numeric($current) && is_numeric($original) && (float) $current == (float) $original;
    }
```

**Comment by themsaid** [comment]
This is a bit opinionated, if the original value was `14` and I want to change it to `14.00` in some cases I expect this attribute to be considered as dirty, same with `14.0` => `14.00`, `14.1` => `14.10`

**Comment by GrahamCampbell** [comment]
Thanks for the report, but our current behaviour is correct I think. It's better to be slightly oversensitive here, than the reverse.

**Comment by slakbal** [comment]
Hi @themsaid, I also came across this today where I only want to create a new (replicate) row + change, if anything changed on the existing row. Hence when I have a number value in there it compares a number with a string, which is problematic. A use case for this would be e.g. a rates table, which should only add a new row if the rate really changed:

```
           //fill new data into the model
            $current_rate->fill($data);

            //test if anything changed
            if ($current_rate->isDirty()) {
                  //if anything changed create a new rate row
            }
```
here the output. The DB column is a decimal(10,3) hence the .000 decimal places.

```
 #attributes: array:17 [
    "id" => 8
    "valid_from" => "2018-07-31 17:37:18"
    "valid_until" => null
    "commission_percent" => 4
    "created_at" => "2018-07-31 17:37:18"
    "updated_at" => "2018-07-31 17:37:18"
    "deleted_at" => null
  ]
  #original: array:17 [
    "id" => 8
    "valid_from" => "2018-07-31 17:37:18"
    "valid_until" => null
    "commission_percent" => "4.000"
    "created_at" => "2018-07-31 17:37:18"
    "updated_at" => "2018-07-31 17:37:18"
    "deleted_at" => null
  ]

```
Maybe we can just have a look at this again, because even if it is an opinionated thing, it does however created an exclusion of values e.g numbers.

Thanks!
