### ISSUE TITLE
JSON serialization should by default convert Carbon / DateTime columns into UNIX

### ISSUE THREAD

**Issue by jaw-sh** [laravel/framework#13876]
```
"reply_last": "2016-06-04 03:58:28",
"bumped_last": "2016-06-04 03:58:28",
"created_at": "2016-06-04 03:58:28",
"updated_at": "2016-06-04 03:58:28",
```

This information is worthless. I don't know the server's timezone. `toJson` should convert Carbon into UNIX.

**Comment by jaw-sh** [comment]
The strict `timestamp` typecasting doesn't help either.

```
            case 'timestamp':
                return $this->asTimeStamp($value);
```

I don't want UNIX for internal operations, only in JSON serialization. I don't see when full date strings would ever be useful in JSON.

**Comment by sisve** [comment]
You could override Model::serializeDate to return the format you want to use.

I could argue that the serialized date should be formatted according to ISO 8901 and include timezone information; I disagree that we should switch to unix timestamps due to ambiguity. The specification indicates the number of seconds since an epoch, "represented in seconds since the Epoch, each and every day shall be accounted for by exactly 86400 seconds", but doesn't take leap seconds into account where days are longer than 86400 seconds...

More information: http://www.madore.org/~david/computers/unix-leap-seconds.html

**Comment by jaw-sh** [comment]
I found out about serializeDate and was very relieved, so you're right,
that does work.

I'd agree either way about the timestamp. Make it UNIX, make it ISO, or
just include the timezone. I don't care, but the current default is
useless as an API.
