### ISSUE TITLE
Eloquent: Value method returns Eloquent\Builder

### ISSUE THREAD

**Issue by rejanu** [laravel/framework#13982]
It seems like value method within model's scope returns Eloquent\Builder instead of a column value when a value of the column is 0.

This way I get correct values - 0 or 1:
`MyModel::where('ID', $id)->value('isEnabled');`

This way I get an **Illuminate\Database\Eloquent\Builder Object** when a value of isEnabled = 0. When value of isEnabled > 0, I get an appropriate value.

```
public function scopeGetEnabled($query, $id) {
        return $query->where('ID', '=', $id)->value('isEnabled');
}
MyModel::getEnabled($id);
```

**Comment by guiassemany** [comment]
Same thing here... Have you found a way to solve it?

**Comment by lagbox** [comment]
The builder is calling the scope on the model (`Illuminate\Database\Eloquent\Builder@callScope`). If that call returns a true value (truthy) it is returned, if its not, the builder itself is returned. That is why you are seeing what you are seeing. `0 == false` so the builder is returned.

Would seem scopes are for adding constraints to queries rather than a mechanism for executing queries.

Laravel Docs:
>"Local scopes allow you to define common sets of constraints that you may easily re-use throughout your application"
>"Scopes should always return a query builder instance"
[Laravel Docs - Eloquent - Query Scopes - Local Scopes](https://laravel.com/docs/5.2/eloquent#local-scopes)
