### ISSUE TITLE
hasMany() + where() returns where conditions in opposite order

### ISSUE THREAD

**Issue by unskaa** [laravel/framework#13994]
Using the following:

    return $this->hasMany(Text::class, 'item_id')->where('item_type', 'product');

Will make a query like this:

    select * from texts where item_type = 'product' and texts.item_id in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')

When it should be like this:

    select * from texts where texts.item_id in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10') and item_type = 'product'

The functions are called in the following order: hasMany() + where() but the where conditions are in the following order: where() + hasMany().

**Comment by GrahamCampbell** [comment]
Thanks for the report. Please can you provide the exact Laravel version you are using?

**Comment by unskaa** [comment]
@GrahamCampbell 

Laravel Framework version 5.2.37

**Comment by unskaa** [comment]
The hasMany() will always be the last where condition regardless how many where()s is following it.

**Comment by themsaid** [comment]
@unskaa does the order matter?

**Comment by unskaa** [comment]
I'm not sure. It might with partial composite indexes.

Even if it didnt matter its illogical.

**Comment by themsaid** [comment]
I don't think the order of where clauses matters.

**Comment by bbashy** [comment]
I think if it's indexed, it does matter? https://dev.mysql.com/doc/refman/5.7/en/multiple-column-indexes.html

**Comment by acasar** [comment]
@unskaa @bbashy This is not a actually a bug but just the way Eloquent works. User defined conditions will always be applied first, eager load constraints second and relation conditions third.That's because relation conditions are not even known until the parent query has already executed.

Anyway, there is no way to change this since it's a design decision, so I suggest closing this issue.
