### ISSUE TITLE
Laravel without composer

### ISSUE THREAD

**Issue by assunluis80** [laravel/framework#14006]
Please add an option to download Laravel without composer. Composer may work fine with devs with good internet connections, but if don't have internet connection you simple CAN'T use Laravel. I am telling this with facts: even if you managed to download the project from github, you still have to use composer to install it (vendor)!!! Realy? This stupid and not helpful. Why don't you give an option to download it with the vendor already included.

The second point is: even if have a good internet connection, but if you're working in places where you have to use proxy connections, composer is a big pain in the ass.

Why you don't you simple provide a way to download the entire project, like others frameworks lfor instance like CakePHP, Zend Framework, etc...

**Comment by deframe** [comment]
Opening a brand new issue and repeating yourself isn't going to do much to aid your cause. Cake and ZF both require Composer to download their latest versions, as do a myriad of other frameworks and libraries.

**Comment by jaschweder** [comment]
@assunluis80 why not only download all in a machine with network access, zip it and use it. There are a lot of dependencies packages in laravel/framework and manually control the version of each of them is really ridiculous because there is a great chance to break something. Second, if you can't use packagist or internet access, create your own server, here is the repo https://github.com/composer/packagist

**Comment by lagbox** [comment]
#14000

**Comment by GrahamCampbell** [comment]
You already opened an issue.
