### ISSUE TITLE
[documention] Undocumented Code Styling

### ISSUE THREAD

**Issue by oink111** [laravel/framework#14051]
A Laravel member is enforcing a coding standard that does not appear within the guildlines for contributing, this should be documented at https://laravel.com/docs/5.2/contributions#coding-style

PSR-1, PSR-2 and PSR-4 does not seem to define any order for use statements therefore its impossible to know what Laravel wants; 

**Laravel Version**: ~

**Example:**
https://github.com/laravel/framework/pull/14043

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

Our code style docs are missing quite a few things because we want StyleCI to just automatically fix things, so contributors don't have to worry about CS.

We cannot currently fix imports to order them by length, and we're currently missing the ability to perform some phpdoc fixes too.

Feel free to get back to us if you have any other questions. ;)

**Comment by GrahamCampbell** [comment]
I might add a note to the docs about this particular case though, because it does seem to be tripping people up. Thanks for pointing it out. :heart:

**Comment by GrahamCampbell** [comment]
Does https://github.com/laravel/docs/pull/2373 look good to you?
