### ISSUE TITLE
Issue with isset on belongsToMany relationship

### ISSUE THREAD

**Issue by liam056** [laravel/framework#14074]
duplicationCheck is a belongsToMany relationship. 

When using isset() on duplicationCheck it returns false unless it has been accessed before.

```php
$duplicationCheck = $campaignModel->duplicationCheck;
var_dump(isset($campaignModel->duplicationCheck));
```

the var dump returns true

```php
var_dump(isset($campaignModel->duplicationCheck));
```

there it returns false

**Comment by kamranahmedse** [comment]
Not an issue.

It happens because when you access the `duplicationCheck` property using `$campaignModel->duplicationCheck` in the first example, it loads the results through the relationship and the property gets set because of the hydration and when you do `var_dump`, the property is set and so true is returned.

In the second case, since you are checking the existence of the property directly and not accessing it (which doesn't trigger `__get()` on the model), the relation isn't loaded and thus property doesn't get set.
