### ISSUE TITLE
How to get a scheme from urlGenerator?

### ISSUE THREAD

**Issue by AidasK** [laravel/framework#14358]
I have HTTP Middleware for cloudflare:
```php
        if (strpos($request->server->get('HTTP_CF_VISITOR'), '"scheme":"https"') !== false) {
            $this->urlGenerator->forceSchema('https');
        }
```

In the model I am generating url to s3 bucket:
```php
        $bucket = config('filesystems.disks.s3.bucket');
        return 'http://' . $bucket . '/image.jpg';
```

How can I get forced schema from urlGenerator? I can not see any public methods to do so.

**Comment by patrickcarlohickman** [comment]
If you have called `forceSchema()`, you will get that schema back when you call `getScheme()` without a parameter.

This will only work if your middleware and your model have access to the same `UrlGenerator` instance, though.

**Comment by sisve** [comment]
I'm guessing that you're trying to force generating https urls for a site behind a Cloudflare proxy. You are seeing http urls generated since the traffic between Cloudflare and your server is http. Cloudflare does use the standard headers X-Forwarded-For (visitors ip address) and X-Forwarded-Proto (protocol/scheme that the visitor used to Cloudflare). Laravel can use these, instead of data read from the connection between Cloudflare and your servers, by using trusted proxies. If Laravel sees a connection from a trusted proxy, some http headers (like those mentioned) is allowed to override the existing values.

A quick google shows some examples; https://hernandev.com/en/middleware-examples-https-and-cloudflare is one of them.

**Comment by AidasK** [comment]
I have tried to find a simpler solution without setting a list of trusted proxies. Because a list of proxies can change over time and needs to be updated. 
I am building a simple website where security is not important, but I need to support ssl. 
It would be great to have a method in a `Request` class called `setSecure(true)` or  `forceSecure(true)`.

**Comment by themsaid** [comment]
`URL::to('/')` will return the URL with a forced schema if used.

Closing since it's not really a bug report, please feel free to open a PR if you have a suggested change.
