### ISSUE TITLE
Illuminate\Support requires ext/ctype, missing from composer.json

### ISSUE THREAD

**Issue by JoshyPHP** [laravel/framework#14461]
The [current version of Illuminate\Support\Str](https://github.com/laravel/framework/blob/02a9bd05a750ee9d215ccefe105665885402a570/src/Illuminate/Support/Str.php#L381) uses `ctype_lower()` but `ext/ctype` is missing from its [composer.json](https://github.com/laravel/framework/blob/02a9bd05a750ee9d215ccefe105665885402a570/src/Illuminate/Support/composer.json).

Note that this is currently the only [occurence of `ext/ctype` used in the codebase](https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=ctype) so you can either add the requirement to `composer.json` or replace that lone use with a regexp.

**Comment by alexbowers** [comment]
It appears that the reason `ctype_lower` has been used is to allow support for different locales.

Since its usecase is in the `snake` method, it may be possible to simply use something like this to compare:

```php
$string === strtolower($string)
```

instead, however this does have some downsides, where it returns differently to `ctype_lower`. An example of this is string being `stringβ`.

Demonstration: https://3v4l.org/K4AvC

I think the best thing here would be to change the composer.json file to require it as an `ext/ctype` as you suggested.

**Comment by alexbowers** [comment]
It is worth noting however, that these have been available by default since php 4.2

> Beginning with PHP 4.2.0 these functions are enabled by default.
http://php.net/manual/en/ctype.installation.php

Have you actually ran into an issue where you didn't have this enabled?

If so, was this a custom compilation where you specifically disabled support with `--disable-ctype`?

The actual chances of this occurring for the vast majority of people is pretty slim.

**Comment by JoshyPHP** [comment]
> Have you actually ran into an issue where you didn't have this enabled?

I haven't. I became aware of this issue after reading this thread on the Flarum discussion board: https://discuss.flarum.org/d/3437-fatal-error-call-to-undefined-function-illuminate-support-ctype-lower

**Comment by alexbowers** [comment]
That's interesting. I guess there is no harm in marking it as a requirement for laravel. Its included by default for pretty much everybody, but I guess that goes to show that there are at least some people who have ran into this in the wild.

**Comment by allanfreitas** [comment]
@JoshyPHP @alexbowers ,
I think, ctype it's a default ext since php 4.2, for performance reasons it's better to use a "compiled" C code instead any other function.
And Laravel 5.3+ requires PHP 5.6.*+ :)

**Comment by timvdalen** [comment]
Just to provide a data point: I just did a fresh install of PHP 7.1.16 on Cygwin, and the ctype extension is not included by default.
