### ISSUE TITLE
 Log::useDailyFiles() duplicates log entries.

### ISSUE THREAD

**Issue by alex-rs** [laravel/framework#14522]
Issue is when Laravel Log:: is used in a loop while using custom daily files:

```
    public static function push($context = "general", $message = "", $level = "info", array $data)
    {
        Log::useDailyFiles(storage_path().'/logs/API_'. strtoupper($context) .'.log', 7);
        Log::log($level, $message . "\n" . json_encode($data));
    }
```
```
            foreach($log as $entry){
                CustomLog::push($entry['sender'], $entry['action'], 'info', ['data' => $entry['data']]);
            }
```

Logs are saved multiple times in defined log file, for example if loop is going thru 3 elements contents of a log is:

```
Log element 1
Log element 2
Log element 2
Log element 3
Log element 3
Log element 3
```

Is this issue with Monolog or is it on Laravel side?

**Comment by Jarlskov** [comment]
Isn't that just because `Log::useDailyFiles()` pushes a new log handler to Monolog? So the first time you run it you add a handler, and ask it to log your data. The second time, you push a handler, and ask your old handler to log your data, then ask the new handler to log your data. 

You should just register your log handler once during bootstrapping, and push your data.
