### ISSUE TITLE
Eloquent increment()/decrement() not touching parent timestamps.

### ISSUE THREAD

**Issue by Nikita240** [laravel/framework#14783]
Say we have a `Comment` model which is configured to touch it's parent `Post` model every time it's updated.

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * All of the relationships to be touched.
     *
     * @var array
     */
    protected $touches = ['post'];

    /**
     * Get the post that the comment belongs to.
     */
    public function post()
    {
        return $this->belongsTo('App\Post');
    }
}
```

Now, let's say we're trying to track how many likes this comment gets. 

```php
$comment = \App\Comment::findOrFail($id);
$comment->increment('likes');
```

With the above code, the Post's `updated_at` timestamp does not get touched.

```php
$comment = \App\Comment::findOrFail($id);
$comment->likes++;
$comment->save();
```

However, with this implementation, Post's timestamps to get touched. This is very inconsistent.

**Comment by sisve** [comment]
This is due to the inherit "magic" in the models and how queries are built. `Comment::increment(...)` will call `(new Comment())->increment(...)` which in turns call `(new Comment())->newBuilder()->increment(...)`. You can find this logic in the `Model::__callStatic` and `Model::__call` methods.

Basically, the increment/decrement methods build database queries which are executed directly against your database. Existing model instances are not used for anything else than grabbing database-related information (like Model::$table). Since this is a direct database query (`UPDATE tbl SET col = col + 1 WHERE ...`) there will be no model-related events; and Eloquent does not know about the relations unless models are involved (and you invoke them).

You'll find that `$comment->increment('likes')` _has not_ incremented $comment->likes, you would need to fetch the model from your database again to get the updated value.
