### ISSUE TITLE
Allow same url routes to be cached when domain is different

### ISSUE THREAD

**Issue by foxted** [laravel/framework#14851]
I was trying to use `php artisan route:cache` and an exception was thrown: 

```
[Exception]
Serialization of 'Closure' is not allowed
```

After some research, I found out that using `php artisan config:cache` with `php artisan route:cache` when using two routes sharing the same url but on two different domains do not work: 

```
Route::group(['domain' => 'app.liftmap.com'], function() {
    Route::get('/', 'AppController@index')->name('application');
});

Route::group(['domain' => 'liftmap.com'], function() {
    Route::get('/', 'AppController@index')->name('application');
});
```

It works fine when using only `php artisan route:cache` but not in combination with `php artisan config:cache`

Is there a way to allow the use of both `php artisan route:cache` and `php artisan config:cache`?

Thanks!

**Comment by KKSzymanowski** [comment]
Route and Config caching are separate operations, hence it's highly unlikely that one causes another to fail.

Check if you have any routes that use a Closure(anonymous function).
You can do that by running `php artisan route:list` and looking for `Closure` word in `Action` column.

Calling `route:cache` basically serializes the Router object that is built based on your route definitions.
To do that, Laravel uses `serialize` method which converts an object to a string. Because PHP doesn't support Closure serialization, in order to cache your routes, you need to use only controller routes.

**Comment by GrahamCampbell** [comment]
You cannot use closures for routing if you want to use route caching.

**Comment by foxted** [comment]
@GrahamCampbell Thanks, but I can read an exception message. 

@KKSzymanowski Thanks for you reply. It seems like one of them affects the other though. 

I have no routes using a closure 

<img width="1680" alt="screen shot 2016-08-25 at 7 39 30 am" src="https://cloud.githubusercontent.com/assets/1385160/17973551/b7caaeb2-6a97-11e6-9592-495a014b0e43.png">

But still, when running `php artisan route:cache` with no other type of caching, works fine. When running `php artisan route:cache` after running `php artisan config:cache`, does not work anymore.

<img width="832" alt="screen shot 2016-08-25 at 7 41 17 am" src="https://cloud.githubusercontent.com/assets/1385160/17973733/6a167b96-6a98-11e6-9439-89026f43f6aa.png">

If I delete the `bootstrap/cache/config.php` file, works perfectly fine. This issue seems to come from having two routes with the same path, just not on the same domain. If I deactivate any of the following routes, `php artisan route:cache` works fine.

<img width="1478" alt="screen shot 2016-08-25 at 7 52 05 am" src="https://cloud.githubusercontent.com/assets/1385160/17973874/def979b8-6a98-11e6-9da6-eaf74324c447.png">

Also, I was loading my domains from the `.env` file:

```
MAIN_DOMAIN=liftmap.dev
APP_DOMAIN=app.liftmap.dev
```

I tried replacing the calls to `env('MAIN_DOMAIN')` and `env('APP_DOMAIN')` by plain text domains in the route group I had, now `php artisan route:cache` works fine, even when using `php artisan config:cache` before. So it seems like we cannot use closure BUT ALSO we cannot use `env()` to load domain information when using `php artisan route:cache`.

**Comment by KKSzymanowski** [comment]
In the example of route definitions you provided there is no `env` call. How does it look like with `env` calls?

**Comment by foxted** [comment]
@KKSzymanowski I am using route group in my `RouteServiceProvider`: 

```
    /**
     * Register application routes
     */
    private function registerAppRoutes()
    {
        Route::group(['middleware' => ['web'], 'domain' => env('MAIN_DOMAIN')], function () {
            Route::group(['middleware' => ['guest']], function () {
                require base_path('routes/guest.php');
            });
            Route::group(['middleware' => ['auth']], function () {
                require base_path('routes/auth.php');
            });
        });
        Route::group(['middleware' => ['web', 'auth'], 'domain' => env('APP_DOMAIN')], function () {
            require base_path('routes/app.php');
        });
    }
```

Replacing the `env()` calls in this method by plain text version of the domains works fine, but I need to keep this information in the `.env` as it is environment dependant.

**Comment by KKSzymanowski** [comment]
I'm sorry but I cannot recreate this error. I setup following routes in `RouteServiceProvider`:
```php
public function map()
{
    Route::group(['middleware' => ['web'], 'domain' => env('MAIN_DOMAIN')], function () {
        Route::group(['middleware' => ['guest']], function () {
            Route::get('/', 'App\Http\Controllers\InquiryController@index');
        });
        Route::group(['middleware' => ['auth']], function () {
            Route::get('/a', 'App\Http\Controllers\InquiryController@create');
        });
    });
    Route::group(['middleware' => ['web', 'auth'], 'domain' => env('APP_DOMAIN')], function () {
        Route::get('/b/{id}', 'App\Http\Controllers\InquiryController@show');
    });
```
Then in `.env` file:
```
APP_DOMAIN="app.liftmap.com"
MAIN_DOMAIN="liftmap.com"
```
Then I ran:
![image](https://cloud.githubusercontent.com/assets/13980973/17976344/5a5eb84e-6aed-11e6-85dc-a172248d2fcb.png)
and everything works fine. Same without config caching.

Can you try to extract some functionality to a separate test project to recreate this error?

**Comment by KKSzymanowski** [comment]
Or maybe look in `storage/logs` for this exception to view the stack trace and find out what is being serialized that is a Closure.

**Comment by foxted** [comment]
I reproduced it in a fresh app using 5.3. The issue seems to come when using two routes, same path but different domains, pointing to different actions: 

## This works

```php
Route::group(['domain' => env('MAIN_DOMAIN')], function () {
    Route::get('/', 'TestController@index');
});
Route::group(['domain' => env('APP_DOMAIN')], function () {
    Route::get('/', 'TestController@index');
});
```

## This DOES NOT work

```php
Route::group(['domain' => env('MAIN_DOMAIN')], function () {
    Route::get('/', 'TestController@index');
});
Route::group(['domain' => env('APP_DOMAIN')], function () {
    Route::get('/', 'TestController@guest');
});
```

Interesting that when I remove `bootstrap/cache/config.php` it works though. I only run in this issue if running both `php artisan config:cache` and `php artisan route:cache`.

Here is a repo demonstrating the issue: https://github.com/foxted/Route-Caching-Issue

**Comment by KKSzymanowski** [comment]
First of all, @GrahamCampbell, this is a bug in the framework, don't jump to conclusions too soon. Even if author did something wrong there obviously should be more informative message.

Most importantly @foxted, I found a solution to your problem.
+ Rename `.env.example` to `.env` - that's kinda obvious
+ Create file `config/routing.php`
```php
<?php

return [
    'main_domain' => env('MAIN_DOMAIN'),
    'app_domain' => env('APP_DOMAIN'),
];
``` 
+ Change routes to:
```php
Route::group(['domain' => config('routing.main_domain')], function () {
	Route::get('/', 'TestController@index');
});
Route::group(['domain' => config('routing.app_domain')], function () {
	Route::get('/', 'TestController@guest');
});
```

After that everything works great.
Thing is `config:cache` caches only `config/*` files, not `.env` files so you have to use your enviroment variables through config in order to be able to cache them.

To prove that this is a bug in the framework here are dumps of RouteCollection objects that the RouteCacheCommand tries to serialize.
+ Using ENV, Without config cache
+ Using ENV, WIth config cache
+ Not using ENV, Without config cache,
+ Not using ENV, With config cache

Last two are the same - it's expected.
First two, well here's the funny story, with config cache, dumped RouteCollection objects takes 5.8 MB(and contains > 2000 Closures) and without it, it takes 8.3 kB(and doesn't contain any Closures). 
Graham, I leave you with examining it, for you now far better what is supposed to be in the RouteCollection object.
To get these dumps I added `var_dump`(not `dd` to get results without coloring) here:
```php
protected function buildRouteCacheFile(RouteCollection $routes) {
	$stub = $this->files->get(__DIR__ . '/stubs/routes.stub');

	var_dump($routes);
	die;

	return str_replace('{{routes}}', base64_encode(serialize($routes)), $stub);
}
```
in `Illuminate\Foundation\Console\RouteCacheCommand`

[with-env.with-config.txt](https://github.com/laravel/framework/files/437717/with-env.with-config.txt)
[with-env.without-config.txt](https://github.com/laravel/framework/files/437716/with-env.without-config.txt)
[without-env.with-config.txt](https://github.com/laravel/framework/files/437715/without-env.with-config.txt)
[without-env.without-config.txt](https://github.com/laravel/framework/files/437714/without-env.without-config.txt)

**Comment by foxted** [comment]
@KKSzymanowski Thanks for investigating. Of course I had a `.env`, just not published in the example :octocat: 

According to your finding, it does seem like the `config:cache` somehow affects the `RouteCollection`. 

Interesting!

**Comment by ldavidsp** [comment]
![image](https://user-images.githubusercontent.com/44006503/54214781-7cc72380-44ac-11e9-890a-f501e77d208c.png)
