### ISSUE TITLE
[5.3] @push order isn't correct

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#14876]
Hi,
The problem is that the pushed content used @push isn't in the correct order.

I have a layouts/html.blade.php

``` blade
<html>
    <head>
        @stack('header-assets')
    </head>

    <body>
        @yield('site')
    </body>
</html>
```

A master.blade.php that extends the html.blade i have the first @push in the following file

``` blade
@extends('layouts.html')

@push('header-assets')
    <link rel="stylesheet" href="{{ url(elixir('css/all.css')) }}">
@endpush


@section('site')
    @include('partials.app._sidebar')
@endsection
```

A partials/app/_sidebar.blade.php, this file contains the second @push

``` blade
@push('header-assets')
    <style>
        .opened_sidebar {
            overflow: visible !important;
        }
    </style>
@endpush
```

When i preview the source code i get 

``` html
     <style>
        .opened_sidebar {
            overflow: visible !important;
        }
    </style>
    <link rel="stylesheet" href="http://fseg.edoc.dev/build/css/all-018dc6ddfb.css">

```

But instead the `<style>` tag should be after the `<link>` tag.

**Comment by fernandobandeira** [comment]
This is caused since @include is rendered before the view that is including it.

Also, this is incorrect for your situation, if for example you had a related content slider and wanted to include the slider plugin via the push inside that partial it would be correct because you would expect to include the carousel plugin before your own style.

So actually there's a need for both orders, i think that we shouldn't change the order of the @include, maybe just add a parameter or create another method like @partial that would render the included view after or append it to the main and render together.

**Comment by shadoWalker89** [comment]
@taylorotwell @themsaid Just a friendly bump.

**Comment by themsaid** [comment]
@shadoWalker89 will look into that, please provide the laravel version.

**Comment by shadoWalker89** [comment]
The version is 5.3.6

Thanks mohamed.

**Comment by GrahamCampbell** [comment]
Have you tried clearing the cached view files

**Comment by shadoWalker89** [comment]
Yes i already did that before submitting the issue, and tried again just now but the problem is the same

**Comment by Decadence** [comment]
Same for me.

**Comment by sisve** [comment]
Probably related commit when the order of @stack/@push changed in 5.2.27. Note the introduction of array_reverse.

https://github.com/laravel/framework/commit/027b14da1669ea1b92781ec7d9b178dbcdd905c6#diff-20743953cccedefbf555dde02b1396b5R722
