### ISSUE TITLE
Difference on eagerloading relationship vs lazy loading it

### ISSUE THREAD

**Issue by dawindk** [laravel/framework#15168]
Defining the following relationship I get two different SQLs with different results depending on how i load the relationship. The relationship adds some additional constraints, there might be a better or more optimal way do define this. 

The need for it is to get me all booking prices that match that customer_id or where the customer_id is 0 (to match all users).

```
public function booking_prices()
{
        return $this->hasMany(EconomyBookingPrice::class, 'customer_id')->orWhere('customer_id', 0);
}
```
```
// Works and gives me the wanted data
Customer::find(1)->booking_prices->count() 

Resulting in SQL:
SELECT * FROM `economy_booking_prices`
WHERE `economy_booking_prices`.`customer_id` = '1' 
and `economy_booking_prices`.`customer_id` IS not NULL 
or `customer_id` = '0'
```

```
// Always return 0 matches as customer_id can never be both 0 and 1
Customer::with('booking_prices')->find(1)->booking_prices->count() 

Resulting in SQL:
SELECT * FROM `economy_booking_prices` 
WHERE `customer_id` = '0' 
and `economy_booking_prices`.`customer_id` in ('1')
```

// The following two also gives the correct count and SQLs as expected
Customer::find(1)->booking_prices()->get()->count();
Customer::find(1)->booking_prices()->count();

One of them is probably the expected behaviour, I would prefer the first, but, atleast the two should be consistent.

**Comment by themsaid** [comment]
I don't think trying to include records where the relationship key doesn't point to the parent model makes sense inside a relation! 

The relationship is meant to bring prices that belong to a customer, but you're trying to bring also prices that belongs to another customer (you can add any value just as you added zero), this breaks the whole idea of relationships IMHO.

I suggest that you achieve this using a normal query rather than a relationship.
