### ISSUE TITLE
Testing withoutMiddleware with Implicit bindings not working

### ISSUE THREAD

**Issue by ppp999** [laravel/framework#15163]
When I use "withoutMiddleware" method in unit test, the implicit binding not working. 
`SubstituteBindings` middleware ignored and cause to skip `substituteImplicitBindings` method in Router.
This caused only since Laravel 5.3 because the implicit binding works as middleware.

Maybe consider to make a mandatory middleware list that is the middlewares that will work even if withoutMiddleware is called.

**Comment by GrahamCampbell** [comment]
Route model bindings are implemented using a middleware in 5.3, so this is the expected behaviour.

**Comment by GrahamCampbell** [comment]
Feel free to discuss proposals in the correct place (the internals repo) as per our contribution guide.

**Comment by andyberry88** [comment]
> Route model bindings are implemented using a middleware in 5.3, so this is the expected behaviour.

That doesn't necessarily mean it **should** be the behaviour. Disabling middleware is very useful for ignoring auth/csrf etc. in tests, but since bindings are implemented in middleware it now makes either bindings or `withoutMiddleware` useless. You can have one or the other but not both.

It's not an ideal workaround but I've added my workaround to http://stackoverflow.com/questions/39235181/laravel-5-3-substitutebindings-middleware-with-withoutmiddleware-issue/39472519#39472519. Comments/improvements from the Laravel team welcome. I'd also like to see this issue re-assessed since it basically breaks `withoutMiddleware`.

**Comment by ppp999** [comment]
That's true. `withoutMiddleware` became useless. Apps with implicit binding can not be tested with `withoutMiddleware`.

**Comment by mcallan83** [comment]
Has anyone opened a discussion in the internals repo for this? I am running into the same issue. I have an API built with passport. I am using implicit binding heavily for a number of controllers, and using `withoutMiddleware` makes these controllers untestable.
