### ISSUE TITLE
[5.3] Model push() method not working if only related models contain changed data

### ISSUE THREAD

**Issue by claasjansen** [laravel/framework#15196]
The push() method on Illuminate\Database\Eloquent\Model will only update the model and all of it relations if the model itself has changed. As the save() method now returns false if the model has not changed since the last time it has been, saved the push() method will skip updating the relations.

**Comment by KKSzymanowski** [comment]
Yes, this is the case because `push` method calls `$this->save()` and it proceeds only if that didn't return false.

Also when you have something like `Issue -> Comment -> Author` and change only the `Issue` and `Author` models leaving `Comment` untouched, the `push` method will only update the `Issue`. Since `Comment` hasn't changed it will not even try to save it's related models.

I suppose you have to explicitly call `save` on related models until it's fixed.

**Comment by themsaid** [comment]
That behaviour was fixed in https://github.com/laravel/framework/pull/15236, however it's not released yet.
