### ISSUE TITLE
Guard artisan clear-optimize against failure

### ISSUE THREAD

**Issue by dereckson** [laravel/framework#15218]
Composer updated on a CI server Laravel from 5.2.7 to 5.2.45, then tried to regenerate the compiled cache:

Fatal error:
Declaration of Illuminate\Auth\SessionGuard::basic() must be compatible with Illuminate\Contracts\Auth\SupportsBasicAuth::basic($field = 'email', 
$extraConditions = Array)
in /home/app/workspace/test-notifications-php/bootstrap/cache/compiled.php on line 462

Same issue here: http://stackoverflow.com/questions/34798659/l5-2-php-fatal-error-declaration-of-illuminate-auth-sessionguardbasic.

It's a little annoying clear-optimize needs Laravel in good standing to be able to work. In such cases, if it I wonder if we shouldn't try/catch such error, and force deletion of the compiled file.

**Comment by themsaid** [comment]
This was fixed in v5.2.25 by the introduction of ComposerScripts, the new approach runs the scripts without having to initialise the whole application. However you need to update your composer.json file for the new update to work, check the difference here:

https://github.com/laravel/laravel/pull/3699/files
