### ISSUE TITLE
Pagination presenters & current page resolver

### ISSUE THREAD

**Issue by chaot1x** [laravel/framework#15268]
Is there any chance that Pagination presenter will come back in 5.3, as it was kinda much better feature than custom views.

About current page resolver, anyone maybe know how could I check if current page isn't larger than last page and set it magically to last page in currentPageResolver method?

**Comment by themsaid** [comment]
IMHO dealing with views is much simpler than a presenter class, that way you can control the final output of the pagination HTML with more flexibility, and blade is a quite nice templating engine to work with.

Regarding your question I believe it's better that you ask on the forums since the "issues" here is for bug reporting only, I believe on the forums your inquiry will have more attention since it's the place people use for questions :)

**Comment by chaot1x** [comment]
@themsaid I know views are simpler than presenter, but still I've rewrited presenter class which includes  bug fixes, which all are declined since 2013 and few new features what I can't make with using views.

**Comment by garygreen** [comment]
@chaot1x then convert your presenters into views. Presenters were annoying as hell in <5.3 -- you shouldn't need to write a class with functions in it to output some basic html. The way it is now is a million miles nicer.

**Comment by chaot1x** [comment]
@garygreen It's not only basic html, but fixed bugs too, for example when there is like 2 pages and you manually set to page 3 it's still showing page with no contents

**Comment by garygreen** [comment]
> for example when there is like 2 pages and you manually set to page 3 it's still showing page with no contents

That's fixed in 5.3.

**Comment by chaot1x** [comment]
> That's fixed in 5.3.
No it's not

**Comment by garygreen** [comment]
Have you tried it? I just did by passing `?page=3` and there are only 2 pages, it doesn't show a extra one. If it doesn't work for you maybe file an issue because it shouldn't be showing an extra page.

**Comment by chaot1x** [comment]
@garygreen Paginator by itself is hidden, but page still loads with no content, in my custom presenter I made that if page is higher than last page, then it's automatically first page. That's why I asked about currentPageResolver, if there is any possibility to "magically" replace current page content with first page content if current page is larger than last page

**Comment by garygreen** [comment]
I see what you mean. You should in theory be able to use `currentPageResolver` but to be honest it's pretty useless because you don't receive the paginator or any information to help you determine what the current page should be. Imo it should at least pass the paginator as an argument.

Also this line https://github.com/laravel/framework/blob/5.3/src/Illuminate/Pagination/LengthAwarePaginator.php#L66

Calls `isValidPageNumber` which should check if it's outside the bounds of the number of available pages (`$lastPage)` but it doesn't even seem to use that at all. Pretty strange.

@themsaid any thoughts on this?

**Comment by chaot1x** [comment]
@garygreen `isValidPageNumber` just checks if page number is an integer

Check this line:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Pagination/AbstractPaginator.php#L105

**Comment by garygreen** [comment]
Hmm seems to stem from this commit: https://github.com/laravel/framework/commit/a038a521710050a92f9d53b7a32ebfc433b17b0e

I kinda agree, it is weird getting pagination for page 1 when you requested for page 5 (but that doesn't exist). If people want to do that though they should be able to make use of the validator instance to determine what page number it should be.

Though you could still do this in the view.... Check to see if it's out of bounds and if so display first link as active.

@chaot1x yes I know it only checks the page number is valid. That's what I said - "It should check if it's outside the bounds, *but it doesn't seem to*"
