### ISSUE TITLE
[5.3] Policy method names transformation

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#15356]
Hi

Today i made this pull request https://github.com/laravel/framework/pull/15339

It transforms a permission or ability containing a dot (example: "article.edit") to a camel case method name on a Policy class.

It got closed and the answer isn't convincing. 
After all the current state will result in an invalid php method name.

And why i'm not allowed to name my abilities or permissions with a dot in it ?

Edit: please don't just close the issue without giving an explanation, if i'm doing something wrong i would appreciate it if you correct me. But i sincerely and humbly think that i have a valid point of view on this one.

**Comment by fernandobandeira** [comment]
IMHO the dot notation isn't the best one to use when naming your permissions or abilities, simply because it specifies an hierarchy so you would have ```root.child.leaf``` for example, ```class.method```.

And in your test you used it like ```update.dot``` that would turn into ```updateDot``` this is confusing because it's inconsistent with how other things work on the framework, so explicitly naming it ```updateDot``` makes more sense.
