### ISSUE TITLE
[5.3] Join 'in' parameter does not recognized.

### ISSUE THREAD

**Issue by metekabak** [laravel/framework#15366]
```
$searchProperty = $this->searchProperty->join('search_property_category',
                function ($join) use ($productCategory, $matches) {
                    $join->on('search_property.id', '=', 'search_property_category.search_propertyid');
                    $join->on('search_property_category.categoryid', 'in', DB::raw('(' . $matches . ')'));
                })
                ->select(['search_property.id', 'name', 'rank', 'searchable'])
                ->toSql();

                dd($searchProperty);

```
dd output

```
"select "search_property"."id", "name", "rank", "searchable" from "search_property" inner join "search_property_category" on "search_property"."id" = "search_property_category"."search_propertyid" and "search_property_category"."categoryid" = "in""
```

It's filling '=' when i use 'in' on join

**Comment by acasar** [comment]
@metekabak you should use ``$join->whereIn(...)``.

**Comment by metekabak** [comment]
okey, but this was working on laravel 5.0, is this option removed? I just upgraded nearly

**Comment by acasar** [comment]
@metekabak This use case was actually never documented as far as I know and it only worked because the operator was never checked before 5.3. Maybe we should add this to the upgrade guide.

``whereIn`` was added in 5.1 and became a recommended approach. In 5.3 the join clause was further enhanced so that you can now use all where clauses offered by the query builder.
