### ISSUE TITLE
[5.3] Database Notification table collides with Spark's notification table

### ISSUE THREAD

**Issue by jschutt** [laravel/framework#15383]
- Laravel Version: 5.3.8
- PHP Version: 7
- Database Driver & Version: Postgres

I'm attempting to use the new Notifications feature in my Spark app and the database channel conflicts with Spark's notification implementation. I am aware that I can use Spark to post DB notifications, but I can't see a way to segment the notifications into different types. In the standard notifications table I could use the either the `type` column or the `notifiable` morph columns to group DB notifications. 

The two options I'm exploring are to 1) find a way to change the config name of the standard 5.3 notifications table so it doesn't conflict with Spark's table structure, or 2) create a manual notification channel that replicates what the default database channel currently does, except points to a different table.

What do you think?

**Comment by themsaid** [comment]
Hello Jesse :)

Well I prefer using the spark notifications schema instead of laravel's, because spark views/js is already reading from it so you won't have to do a lot of work in displaying the notifications and such, what we can do is make sure the spark notifications are as efficient as laravel's.

For now I can see that the only difference is saving the notification type inside the database table, will look into that next week and see if we can come up with an easy way to migrate the schema to save this value.

I've already added this to our list of features so I'm closing this issue here since it's not actually a bug with the framework, for spark related issues please feel free to open an issue on this repo: https://github.com/laravel/spark

Thanks :)
