### ISSUE TITLE
Updating JSON Columns is not working as expected

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#15433]
- Laravel Version: 5.3.9
- PHP Version: 7.0.8
- Database Driver & Version: Mysql 5.7.15

### Description:
I can successfully update the table row with this:
```
DB::table('users')
            ->where('id', 1)
            ->update(['options->enabled' => true]);
```
But this code doesn't work:
```
User::find(1)
            ->update(['options->enabled' => true]);
```
I have to add all json properties to my Model's fillable array to be able to update:

```
protected $fillable = [
        'name', 'email', 'options', 'options->enabled', 'options->language',
    ];
```
I expected that including only `options` be enough.

Additionally if the default value of the JSON column be `null`, updating gets fails and I have to set it to `{}` to make it work. So I can't use
```
protected $casts = [
        'options' => 'array',
    ];
```
because it sets JSON column value to `null` or `"{}"` instead of `{}` and updating gets fail,
Sorry for my English.

### Steps To Reproduce:
1. Use Eloquent update.
2. Try to update a json field that has `null` value.
3. Not Including all `json->property` in Model's fillable array.

**Comment by themsaid** [comment]
There are two issues here, first it's expected that you need to add all fillable fields including the JSON ones, that way you can decide what JSON attributes you want to guard and what may be left fillable.

Second, from MySQL docs for `JSON_SET`:

> Returns NULL if any argument is NULL or path, if given, does not locate an object.

So yeah if the value of the column is NULL no updates will happen.

Regarding casting as array I'm not sure what scenario may lead to this saving `"{}"`?

**Comment by hafezdivandari** [comment]
When storing a `user` record, I set json column value to `{}` because it can't be left `null`, but If I use casting as array, it casts by `json_encode('{}')` that saves `"{}"` in the table instead of `{}` and updates get fails.

About another issue, I think there should be a way to add all json properties to fillable array once, for example by adding `options->*` or just `options` would be enough. What if I had a hundreads of user options I wanted to store? I have to mention all of them in fillable array?!

**Comment by themsaid** [comment]
@hafezdivandari why not make a default value for the DB column, Instead of doing it via eloquent?

Regarding `options->*`, a JSON structure can be very complicated, trying to match fillable like this can be an overhead I'm not sure if it's worth it. IMO if we're to make any change it'd be making all `options` children as fillable if there's a `options` in the fillables array.

**Comment by hafezdivandari** [comment]
@themsaid As I know and tested before, Mysql doesn't accept default value for json fields unfortunetley!

I think making all `options` children as fillable if there's a `options` in the fillables array is acceptable and neccessery.

**Comment by themsaid** [comment]
You can do this then:

```
Table::create([
    'user_id' => 1,
    'json' => new stdClass()
]);
```

This will give the JSON column a default value of an empty object for a newly created model, you can easily update its parameters later. 

For the fillable thing, let me see if I can come up with a clean PR for that.

**Comment by hafezdivandari** [comment]
Thanks, It would be great.

**Comment by themsaid** [comment]
Getting this feedback from Taylor here https://github.com/laravel/framework/pull/15464

The overhead introduced while allowing this sort of thing is unnecessary, so it's better that you explicitly add the JSON Paths you want to make fillable in the $fillable array to avoid that overhead.

I also suggest that you reverse your way of thinking and define $guarded instead of $fillable, so that you may protect only some fields but leave all the rest fillable.

**Comment by arctic-ice-cool** [comment]
The workaround I'm going to use (reluctantly) is to add this to the Model with the JSON field:

```
protected $attributes = array(
        'settings' => '{}'
    );
```
