### ISSUE TITLE
snake_case() not working with lowercase words

### ISSUE THREAD

**Issue by bradbird1990** [laravel/framework#15497]
I think snake_case() is still not working correctly; found it was last fixed here #9535.
Would fix this issue myself but don't know regex.

I expect "hello world" or "Hello World" to convert to "hello_world" regardless of if I use uppercase or lowercase. In fact, I think "HELLO WORLD" should also convert to "hello_world."

Currently it's only working if I use capitals for first letters in a sentence.

**Comment by GrahamCampbell** [comment]
That seems to be correct due to the ctype_lower part.

**Comment by bradbird1990** [comment]
Is there any reason why it checks that a string is not lowercase? Maybe for some other use in the framework? Personally, I wouldn't like to have to to ucfirst() or ucwords() to convert to snake case. Makes more sense it just works for all strings.

**Comment by marktopper** [comment]
@bradbird1990: In your case I would just run this:

```
$string = 'HELLO WORLD';
$string = str_replace(' ', '', $string);
$string = strtolower($string);

echo $string; // outputs "hello_world"
```

Since `snake_case` would not be able to do this for you.

**Comment by PeterDKC** [comment]
> That seems to be correct due to the ctype_lower part.

This is incorrect. the ctype_lower() call simply skips any work if **all** the characters in the string are lowercase ( meaning that it's by definition already "snaked" ). Spaces, digits, or anything else will call the meat of the method.

```
>>> ctype_lower('Random Words Here')
=> false
>>> ctype_lower('random words here')
**=> false**
>>> ctype_lower('random')
=> true
```

It seems like unexpected results to return "snaked" words only if those words or letters start with uppercase and to explicitly ignore a space followed by an letter, a use case which is omitted in the [tests for the method](https://github.com/laravel/framework/blob/b8eec63128b4e8acdfd7f43030209a8441c47d8f/tests/Support/SupportStrTest.php#L194).

```
>>> \Illuminate\Support\Str::snake('Random words Here')
=> "randomwords_here"
>>> \Illuminate\Support\Str::snake('Random wORDS        Here')
=> "randomw_o_r_d_s_here"
```

As a temporary workaround under normal circumstances, one can wrap the argument in ucwords(), but this seems like a patch rather than a fix.

```
>>> \Illuminate\Support\Str::snake(ucwords('random words here'))
=> "random_words_here"
```

**Comment by PeterDKC** [comment]
Added PR targetting [5.5] https://github.com/laravel/framework/pull/18764
