### ISSUE TITLE
[5.3] require doesnt work with array validation anymore

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#15641]
- Laravel Version: 5.3.10 / 5.3.11
- PHP Version: 7.0.9
- Database Driver & Version: NaN

### Description:
required doesnt work on array upload.

### Steps To Reproduce:

```blade
{{ Form::open(['route' => 'store.files', 'method' => 'POST', 'files'=>true]) }}
    {{ Form::file('image[]', ['multiple']) }}
    {{ Form::submit('submit') }}
{{ Form::close() }}
```
```php
$this->validate($request, [
    'image.*' => 'required|image|max:2048'
]);
```

**Comment by themsaid** [comment]
It's an array right? You want to validate that it's filled right? you can't go validate the members of the array because if the array is empty there won't be any members, instead you need to do:

```
'image' => 'required'
```

Which insures the array has members.

Please use the forums/stackoverflow, looks like most of your reporting issues are actually questions. Thank you!

**Comment by ctf0** [comment]
actually it wasn't a question because this was working as usual in the past version v5.2, 
also u could have simply add the functionality in the core by just checking is the array way empty or not and if yes then return the required msg :)
