### ISSUE TITLE
[5.3] Form Requests Not Working, no response recieved, just page refreshed

### ISSUE THREAD

**Issue by maurocasas** [laravel/framework#15761]
- Laravel Version: 5.3.16
- PHP Version: 7.0.11
- Database Driver & Version: MySQL

### Description:

I have setup my application entirely, and I have moved it into a Digital Ocean droplet.
Now, the strangest thing has happened, forms are just redirecting back without any type of response, and the form validations are OK. I'm 100% sure that I'm sending the required fields as I have checked manually.

My whole platform works on Local, but not on production.

I'm using database session driver.

### Steps To Reproduce:

I have only moved from my local to my staging server, the code has not changed whatsoever.

**Comment by themsaid** [comment]
@maurocasas Apparently it's something at your end that's causing this kind of troubles since millions of app are running on laravel already :)

So it's very important that you be specific about your issue and share code to help replicate the problem, because without being able to replicate the issue it won't ever get fixed.

**Comment by maurocasas** [comment]
This is going to sound silly, but I was using Apache 2 + PHP 7.0 on the server, and I decided to give Nginx a shot and ended up working just fine. Quite odd. I'm closing this.
