### ISSUE TITLE
File extension is changed upon upload; breaks file

### ISSUE THREAD

**Issue by timgavin** [laravel/framework#15827]
- Laravel Version: 5.3.17
- PHP Version: 7.0.11
- Database Driver & Version: n/a

### Description:

When uploading an MPG, the file extension is changed to mp4, rendering the movie unplayable. I tested this with an MPEG-2 video.

The file name before uploading

```
test.mpg
```

The code for uploading the file

```
$file = request()->file('file')->store('uploads');
```

The file name after uploading

```
e912e8f2c41bde3cf7731d9e374bdc2a.mp4
```

### Steps To Reproduce:

Fresh install of Laravel.

Add this to routes/web.php

```
Route::post('/upload', function () {
    request()->file('file')->store('uploads');
});
```

Add this to welcome.blade

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form action="/upload" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="file" name="file"><br>
            <input type="submit" value="submit">
        </form>
    </body>
</html>
```

Visit `/` in browser and upload a video file with .mpg extension.

**Comment by themsaid** [comment]
Laravel uses Symfony's mimetype guesser to guess the extension of the file, as for my I couldn't replicate the issue on a fresh laravel installation running valet.

Please run the following command `file -b --mime path-to-file-here 2>/dev/null` with the path to your file set to know what your system think the file mimetype is.

I'm closing this since it does appear to be an environment related issue, but please feel free to ping me if you ever had the chance to get what was causing the wrong behaviour.

**Comment by Jnesselr** [comment]
Why does Laravel change the file extension? I'm having a similar problem where a file type (gcode) that doesn't really have a mime type (it assumes text/plain) gets changed to a .txt extension.
