### ISSUE TITLE
redirectTo property in RedirectsUsers does not allow route names

### ISSUE THREAD

**Issue by EliasZ** [laravel/framework#15834]
- Laravel Version: 5.3

### Description:
`RedirectsUser` trait only returns a relative redirect path using the `redirectTo` property (defaults to `/home`) which is then often passed directly to `\Illuminate\Routing\Redirector::to`.

Maybe adding a `redirectToRoute` property which - if set - will return the path for that route name makes sense?

`trait RedirectsUsers`

```
public function redirectPath()
{
    return property_exists($this, 'redirectToRoute') ? route($this->redirectToRoute) :
               property_exists($this, 'redirectTo') ? $this->redirectTo : '/home';
}
```

**Comment by sisve** [comment]
You could just skip using the `redirectTo` property and instead override `redirectPath()` to calculate the path. This would also support generate routes with parameters, and those using action() instead of named routes. Providing support for all different kinds of route setups using properties will quickly become complex.

**Comment by EliasZ** [comment]
This is a dynamic framework thingy in use by the auth traits (`RegistersUsers`, `ResetsPasswords`, `AuthenticatesUsers`). Controllers using that trait can define a `$redirectTo` property which will be redirected to after some action takes place (logging in et cetera).

On implementation level those traits their redirect-behavior can easily be modified by just setting the property. So I don't see how it can be calculated? It is just inconvenient `$redirectTo` is an absolute path instead of a route name which is then resolved to its absolute path. Adding `$redirectToRoute` solves this issue by allowing to redirect to a route name without breaking the current functionality.

Rewriting `redirectPath` and dropping `redirectTo` will not be backwards compatible. I understand your concern about `action()`-redirects and ending up with a lot of properties (`redirectToAction`), but the ternary operator could be modified to be more sane.

I'm all ears for a better solutions.

**Comment by sisve** [comment]
How about a `$redirectToAction` for those of us that prefers the format `HomeController@getIndex` instead of named routes? And also a `$redirectToRouteParameters` route parameters for those that needs to add dynamic segments like current locale (`/sv/home`)? What if any of these needs to be calculated based on the current request and cannot be hard-coded?

I'm arguing that the default implementation is enough, and anyone that wants to have something more complex can just 1) override the method and do what they want, or 2) set the `$redirectTo` (or `$redirectPath`) property in the constructor.

    public function redirectPath() {
        return route('my-home-route');
    }

    public function __construct() {
        parent::__construct();
        $this->redirectTo = route('my-home-route');
    }

**Comment by themsaid** [comment]
Thank for the suggestion, please feel free to open a PR suggesting the change.

We try to keep the issues of this repository for bug reporting only.
