### ISSUE TITLE
How to override the notification table name 

### ISSUE THREAD

**Issue by webreinvent** [laravel/framework#15847]
- Laravel Version: 5.3.*
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:
I wanted to override the default table for notification. I was not able to find it anywhere on the internet or in documentations.

**Comment by uber1337** [comment]
Hi,

There no such config, however if you will look in the sources you can do the following:

- run: php artisan notification:table. 

- rename the table name in the new generated migration

- extend Illuminate\Database\Eloquent\Model\DatabaseNotification and change $table name

- build your own trait: Illuminate\Notifications\HasDatabaseNotifications by changing to use the extended class above
- build your own trait: Illuminate\Notifications\Notifiable by using the new trait above

Now you can use the new trait for Notifications.

It's kinda' a long way, not sure if many peoples needs this in order to do a PR.

Hope that it helped you.

**Comment by themsaid** [comment]
Sorry but this repo is for bug reporting only :)

**Comment by rexgama** [comment]
even if this is close i still don't find the solution over the internet :(

**Comment by kanushka** [comment]
> * Notifiable

thanks @uber1337 it works me. but it has to extend **DatabaseNotification ** from `Illuminate\Notifications\DatabaseNotification`.
