### ISSUE TITLE
limit on a query should never be set to 0

### ISSUE THREAD

**Issue by warrickhill** [laravel/framework#15886]
- Laravel Version: 5.3.18

### Description:
When using the Query Builder the take and limit methods allow a limit of 0 to be passed though to the sql query. I can't think of any reason you would ever want to run a sql query with limit 0.

### Steps To Reproduce:
Call `$builder->take(0);`

**Comment by themsaid** [comment]
Is it a bug you're trying to fix? What's wrong with having take = 0 ?

**Comment by warrickhill** [comment]
@themsaid take = 0 would run the query on the db with limit 0, this would give you no rows back, which makes it a bit pointless running the query in the first place.

I'm building api in which consumers can pass a limit through, and so in every method of every repository i am having to check that the limit they supplied is > 0 before calling take on the query builder. I'm sure i'm not the only person who has faced this issue and it seams a bit silly that a lot extra code and developers time is spent working around this when a 1 char change would fix it.

**Comment by themsaid** [comment]
Your solution is to remove the limit if zero was provided? so if limit = 0 we return all results?

**Comment by warrickhill** [comment]
Yes and No. My solution is to not set the limit if 0 is passed, so it would follow default behaviour and return all results.

**Comment by themsaid** [comment]
That's a breaking change and might not be desired by everyone, as for myself I don't want this to ever happen in any of my applications, if the API user requested limit = 0 I'd return zero results for him, his call.

Anyway, this doesn't seem to be a bug in the framework but rather a suggested change, I'll close this issue since we keep only bug reports, but please feel free to open a PR on the master branch with the suggested change.

Sorry :)

**Comment by MansourM** [comment]
Something like this could actually have a use case if we change the behavior so that limit(0) doesn't hit the database. This could make Eloquent more efficient.

I found this issue when i was trying to find out if i could make a query not hit the db and return empty, In my case, using Filament’s `getEloquentQuery()` method in a reousrce, I have to return a query that sometimes needs to be empty, based on user permissions. The challenge is to return an empty query without triggering a DB call. Using limit(0) seemed like a possible solution, but it still executes a query.
