### ISSUE TITLE
[5.3] Return of Mail::send is removed

### ISSUE THREAD

**Issue by jonatascabral** [laravel/framework#16272]
## Laravel Version: 5.3.22
- PHP Version: 5.6.16
- Database Driver & Version: MySQL 5.7.14

### Description:
On commit [51f7f695](https://github.com/laravel/framework/commit/51f7f695) @GrahamCampbell explain it is removed because was inconsistent between drivers.
So the question is, exists an easy way I can check if the mail was sent without overriding the Mailer contract??

**Comment by GrahamCampbell** [comment]
If no exception was thrown, it indicates it was sent, ish. Some drivers don't throw exceptions though, so you won't know.

**Comment by michelecurletta** [comment]
In order to properly use services like Mailgun, it would be very useful to access the message-id generated, and returned, by these services whenever they receive a send request.
I’m going to quickly illustrate you the workflow I’m thinking about:
1) laravel app queues the email
2) the queue worker performs the send request in background, obtaining the message id and storing it into a specific db table
3) Mailgun sends the email and triggers the laravel’s webhook passing the message id, informing the application that the email was sent.
@GrahamCampbell @taylorotwell considering this problem, how do you ensure that emails from your applications will be derived (using a service like Mailgun, Sendgrid, etc..)?
