### ISSUE TITLE
Escape namespace for morphedByMany-relationship

### ISSUE THREAD

**Issue by fancenl** [laravel/framework#16302]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.14

### Description:
I have a problem with a morphedByMany-relationship (Laravel 5.3). I think this is a bug in Laravel itself. Seems to be the same issue as #4006 (27 Mar 2014).

`select products.*, categoryables.category_id as pivot_category_id, categoryables.categoryable_id as pivot_categoryable_id from products inner join categoryables on products.id = categoryables.categoryable_id where categoryables.category_id = '1' and categoryables.categoryable_type = 'App\Models\Product'`

is generated automatically, but MySQL does not find anything. When I edit the query manually to

`categoryables.categoryable_type = 'App\\Models\\Product'`

 then it's working!

So, the model-namespace needs to be escaped. Then it will work perfectly.

**Comment by Cyrille37** [comment]
- 2024-01
- laravel/framework 10.10
- MariaDb 10.5

Must define `Relation::morphMap` in AppServiceProvider's boot() method, else it store the full namespace with antislash `\` and sql queries does not escape it, and inevitably returns nothing :-(

```php
public function boot()
{
        Relation::morphMap([
            'operator' => \App\Models\Operator::class,
            'productOwner' => \App\Models\ProductOwner::class,
        ]);
}
```

Like it's not mentioned in the Laravel documentation I think the problem is else where ... I don't understand ...
