### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 67:

### ISSUE THREAD

**Issue by et4m1r** [laravel/framework#16428]
I used default installation of Laravel 5.3. 

and i did
laravel new blog
php artisan make:auth
configuration in .env
php artisan migrate

That's all I did. Everything wen smoothly but when I submit register form I get:
TokenMismatchException in VerifyCsrfToken.php line 67:

**Comment by craigpaul** [comment]
@et4m1r Just followed your exact steps and didn't end up with that problem. I was using a sqlite database, was running on my local macbook (no VM, homestead, etc) with PHP 7.0.9 and its built in server. Can you provide more details on your environment, because it seems like it isn't anything to do with `laravel/framework`.

**Comment by et4m1r** [comment]
i tried it on osx and windows. 
osx was ok. but my installed project on windows is showing error like that. im using mysql.

**Comment by shadoWalker89** [comment]
@et4m1r Did you keep the register form open for too long before submitting it ?
Because csrf token expire in a certain time which depends on the config value of `session.lifetime`

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by et4m1r** [comment]
http://laravel.io/forum/11-16-2016-tokenmismatchexception-in-verifycsrftokenphp-line-68

@GrahamCampbell asked alrdy. no reply now.
@shadoWalker89 i clicked login button immediately. tried after restart server
