### ISSUE TITLE
URL encoding with Hebrew returns gibberish

### ISSUE THREAD

**Issue by Naxon** [laravel/framework#16559]
- Laravel Version: 5.3.24
- PHP Version: 7.0
- Database Driver & Version: MySQL 

### Description:
Using the redirect() method when redirecting to urls with Hebrew characters returns gibberish.
For example: 
`redirect('website.com/1/שער-7')` will redirect to `website.com/1/×©?` .

### Steps To Reproduce:
`redirect('website.com/1/שער-7')`

**Comment by vlakoff** [comment]
Maybe your file has a wrong encoding. Is it UTF-8 as it should?

**Comment by Naxon** [comment]
Yes it is... The file and the database have utf-8 encoding

**Comment by vlakoff** [comment]
I'm not sure the issue is related to Laravel, if you look at methods `to` and `buildCompleteUrl` in [UrlGenerator](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/UrlGenerator.php) you will note they don't do much.

1) Are you using `formatHostUsing` or `formatPathUsing`?

2) What do you get with the following code? (here I have false, false, 10, 7)
```php
$path = '1/שער-7';
var_dump( strpos($path, '?') );
var_dump( mb_strpos($path, '?') );
var_dump( strlen($path) );
var_dump( mb_strlen($path) );
```

3) Can you try adding `ini_set('default_charset', 'UTF-8');` at an early point in your application?

4) Note you can do `redirect('articles/1')` or `redirect('http://example.org/articles/1')`, but not `redirect('example.org/articles/1')`

**Comment by Naxon** [comment]
1. no.
2. false, false, 10, 7.
3. still not working... Now I get this: `××××©××××-××§×××¦×-×ª×©×××¨-150-××××-×¢×-××××¨×©` .
4, Yes, it's a typo in this message. I actually do:
`return redirect('/article/' . $article->id . '/' . $article->slug);`

**Comment by vlakoff** [comment]
Also try `redirect('1/שער-7')->getTargetUrl()`, if it gives you the expected result, I'm pretty sure the issue is not related to Laravel. I even looked at the base Symfony classes.

Most likely the issue is on the HTTP server. You may try using other HTTP servers to isolate the culprit.

**Comment by Naxon** [comment]
OK. I tried it on another server. The problem appears when I use `php artisan serve`, but on my forge server it works fine. Thank's!
