### ISSUE TITLE
Unable to override default unauthorized access error message

### ISSUE THREAD

**Issue by atefth** [laravel/framework#16606]
- Laravel Version: 5.1
- PHP Version: 5.6.10
- Database Driver & Version: Mysql Driver (5.7.11)

### Description:
Passing an extra argument to set a custom error message for unauthorized access **doesn't** return the *custom message*. 
It **always** returns the *default message*, ie: "This action is unauthorized.";

### Steps To Reproduce:

1. Setup a policy for an *Eloquent Model*.
2. Perform an **unauthorized action** by invoking the **`@authorize`** directive from a *Controller*.
3. Pass a *custom error string* along with the *ability string* - 
      `return $this->authorize('delete', 'some customized text');`
4. Calling the directive with the *second argument* should override the *default error message* to the **given argument**.
5. The returned value **does not** get overwritten and thus a **custom error message** can not be set.

**Comment by themsaid** [comment]
What is the `@authorize`? also what's this syntax `$this->authorize('delete', 'some customized text');`? Where did you find it in the docs?

**Comment by themsaid** [comment]
@atefth is that related to the PR you opened?

**Comment by atefth** [comment]
@themsaid yes it is, [this](https://laravel.com/docs/5.3/authorization#via-controller-helpers) is where I found it.

So, I want to make sure that the *Current User* has permissions to perform any (CRUD) operation on any *Related Model*. These permissions, *together with unique **custom error messages** for each operation*, have been defined in the individual **[Policy Classes](https://laravel.com/docs/5.3/authorization#creating-policies)**, for all Related Models.

I am using a Middleware to check before every request, if the user has permission to perform that operation. If they **don't have permission**, I want the raised `AuthorizationException` to contain the message that has been ***configured** in that respective Policy Class*.

Thus I need to be able pass in my custom error message **string/collection** to the `authorize` function, exposed through the controller that's associated with each request; most likely in this manner -

`$message = $controller->authorize('update', 'My custom error message explaining why this operation can not be performed by the current user.')->message();`

FYI, I found this [question](http://stackoverflow.com/questions/40873709/laravel-5-3-passing-authorizationexception-a-message-when-a-policy-fails/40881768#40881768) on stack.

**Comment by mtpultz** [comment]
@themsaid is there anyway to customize a failed policy message for an AuthorizationException? This pull request is related to the same question I posted on stack overflow mentioned above by @atefth where I'm looking for a way to get something equivalent to a validation error bag, but for a failed policies regardless of the policy API used - controller, or via the User model. This is something that I find I come into contact with regularly, and instead of applying what feels like a "clean" solution I'm currently just `abort(403, trans($key));` within the policy so based on the type of failure the policy experiences I can throw back a message.  Maybe using abort is as good as it gets.

**Comment by themsaid** [comment]
There's no such functionality really, I see it's something you'd like to add to the core and taylor answered that no plans for this at the moment.

@mtpultz I'd say implment your own `authorize` function and throw an AuthorizationException with the message you want.

**Comment by themsaid** [comment]
Closing this issue since it's not a bug report, but please feel free to ping me.

**Comment by mtpultz** [comment]
Thanks @themsaid, we're using the model policy - `$user->can(...)`, but maybe I should switch them all up to use `$this->authorize(...) like you suggest.  Are you able to point to why it isn't possible to throw a CustomException in a policy?  Seems to exit the policy, but then keeps on executing, but I'm able to abort(...), which eventually throws an HttpException.  I was hoping I could throw a CustomException with a message and then catch the exception in Handler::render and return a JSON response, but that doesn't work.

**Comment by mtpultz** [comment]
Thanks @themsaid I ended up creating a ErrorMessageException that took a message, and depending how the policy failed throw it with the custom message, and then passed it back as JSON using Handler::render since AuthorizationException doesn't take a message.

I tried to `throw AuthorizationException('with my message since it extends exception')`, but it swaps out my message for `Unauthorized.`
