### ISSUE TITLE
Databases : integers inside enums are not considered as integers

### ISSUE THREAD

**Issue by ifthenelse42** [laravel/framework#16649]
- Laravel Version: 5.3.24
- PHP Version: 7.0.13
- Database Driver & Version: MySQL 15.1

### Description:
When using integers inside an enum in a database column, it's then not considered as integer when used.

### Steps To Reproduce:
Add this column inside any migration : 
`$table->enum('type', [0,1,2,3]);`

Then if you migrate with a seeder that uses any type that is in the enum array, it should become 0, or a value you haven't chosen. Then trying to use this value for anything, like : 
`if($model->type == 2) { exit("good"); } else { exit("wrong"); }`

And if the type is 2 inside the database, it will be considered as 0, or any value you haven't chosen.

I hope it was as clear as possible, as for the way I have fixed it inside my forum, I just changed the column type to smallInteger.

**Comment by KKSzymanowski** [comment]
This is because when you insert a row like this:
```php
Foo::create([
    'enum_column' => 2
]);
```
MySQL understands it as an index from an array of possible values.
If the values are `0,1,2,3`, it is stored in the database as an array like:
```
1 => 0,
2 => 1,
3 => 2,
4 => 3,
```

If you run this query:
```
INSERT INTO foo (enum_column) VALUES (2);
SELECT * FROM foo;
```
you'll see that `1` shows up.

Take a look at Tim Bancroft's comment [here](http://dev.mysql.com/doc/refman/5.7/en/enum.html):

> When using the returned values, you reference them as a text string, unless you use the (0+<enum_col>) format above, which would return the index as an integer.

This works both ways.
If you want to insert actual value of `2`, you need to pass it as a string, eg.
```php
Foo::create([
    'enum_column' => '2'
]);
```

Apart from that, I don't know any reason why enum holding only integers would be better than eg. smallInt or tinyInt.

- Common sense suggests that an integer type should be faster(no value validation, no key-value lookup table)
- You have more flexibility when adding a new value(you don't have to change the db structure unless you run out of range - in that case you'd need to upgrade eg. from tinyInt to smallInt).
- Integer is just a natural column type for storing integer values - more obvious to future code readers.

I would suggest switching from enum to integer because it doesn't carry the risk of producing such weird errors and it simply doesn't make sense to use enum in this case.

**Comment by ifthenelse42** [comment]
I see, so that's it. But then, why was this not a thing in Laravel 5.2 ?

**Comment by sisve** [comment]
I see nothing in this issue that has claimed that this did work in 5.2. This is a mysql behavior, not a php/laravel behavior. Have you perhaps upgraded mysql, php or any php modules? (Changing libmysql to mysqlnd, for example.)

**Comment by KKSzymanowski** [comment]
@sisve, I just tested it in Laravel 5.2 and in fact it works as @ifthenelse42 says.

**Comment by KKSzymanowski** [comment]
### Laravel 5.2

```php
$bindings = $me->prepareBindings($bindings);

return $me->getPdo()->prepare($query)->execute($bindings);
```

`$me` is essentialy an instance of MySqlConnection inside a closure.
PDO here binds all the values to the prepared statement as if it were strings.

### Laravel 5.3

Values are bound to the statement manually:
```php
$statement = $this->getPdo()->prepare($query);

$this->bindValues($statement, $me->prepareBindings($bindings));

return $statement->execute();
```

I don't understand why the connection is once referenced as `$this` and then as `$me` when it's exactly the same object, but nevertheless:
Values are bound as follows:
```php
public function bindValues($statement, $bindings)
{
    foreach ($bindings as $key => $value) {
        $statement->bindValue(
            is_string($key) ? $key : $key + 1, $value,
            is_int($value) || is_float($value) ? PDO::PARAM_INT : PDO::PARAM_STR
        );
    }
}
```
which means when it's an integer as in `Foo::create(['enum_column' => 2]);`, PDO is instructed to treat it as an integer and therefore MySQL thinks it's an index from an array of possible enum values.
If it's a string as in `Foo::create(['enum_column' => '2']);`, PDO treats it as a string and everything behaves properly.

This behaviour was changed with [this](https://github.com/laravel/framework/commit/b44034dcd8d6eebe7ed48d43dc37fc21ef7c1769) commit by @themsaid and in my opinion it's a good decision to treat an integer value as is. It just breaks some edge cases like using enums consisting of integers.

So, OP, you have probably three choices:
- Stick with 5.2
- Change the column type to an integer - I personally recommend that
- Upgrade to 5.3 and overwrite the `Illuminate\Database\Connection::statement()` method to suit your needs in a custom connection class. To do that you can bind mysql connection to a custom `Connection` class - look at `Illuminate\Database\Connectors\ConnectionFactory::createConnection()` for inspiration.

**Comment by ifthenelse42** [comment]
@KKSzymanowski I have already fixed the issue : https://github.com/ifthenelse42/archontos/blob/65f342522267d1dc478a0f4ebd641510b0ca9382/database/migrations/2016_07_11_124745_create_sujet_table.php

I just reported it here in case it was a core issue of Laravel. Thank you for the informations provided, now I perfectly understand why this happened. A smallInteger is enough to suit my needs anyway, I just used enums previously because I find it's a better way to organize my databases, but smallInteger is fine too and allows me to expand it the way I want as you pointed.

I guess I can close this then, thank you everyone.
