### ISSUE TITLE
Testing Mail::assertSentTo give me undefined index email 

### ISSUE THREAD

**Issue by Artessan** [laravel/framework#16684]
- Laravel Version: 5.3.26
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I'm make a simple test 
`       ` Mail::fake();
        $user = factory(User::class)->make();
        $this->visit('register/');

        $this->submitForm('Sign Up', [
            'name'  => $user->name,
            'email' => $user->email,
            'terms' => true,
        ]);

        Mail::assertSentTo([$user], Welcome::class);`

The test fails and the output is:

ErrorException: Undefined index: email

/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:89
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Collection.php:603
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:93
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:47
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:129
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Arr.php:517
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Collection.php:282
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:130
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:29
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php:56
/home/vagrant/dashboard/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
/home/vagrant/dashboard/tests/functional/RegisterTest.php:29

Thanks!

**Comment by ivanvermeyen** [comment]
Hey,

I got the same error, but I'm not passing in a `User`, just an e-mail address.

I have a simple test like this:

```php
Mail:fake();

// Blablabla send the mail...

Mail::assertSentTo('john@example.com', ActivateAccount::class);
```

When I send the mail in my controller the test passes:

```php
Mail::to($email, $name)->send(new ActivateAccount($activation));
```

But when I move the `to($email, $name)` in to the `build()` method in the `Mailable` class, I also get the `Undefined index: email` error:

```php
return $this->to($email, $name)->subject($this->subject)->view('emails.registered');
```

I tried it manually and I did get the e-mail, so the code works.

I think the reason is that [in the `MailFake`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Testing/Fakes/MailFake.php#L89) it is looking for an `email` array key, but [in the `Mailable`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Mail/Mailable.php#L382) it is setting an `address` key instead.

After I changed `email` to `address` in the `MailFake`, both tests passed.

**Comment by philbates35** [comment]
Just hit this error, and agree with @ivanvermeyen's assessment. Here's some psudo-code that demonstrates the error:
```
// App Code
class SendFooEmail
{
    function handle()
    {
        $mail = new FooMail();
        $mail->to('foo@example.com');

        Mail::send($mail);
    }
}

// Test
function test_handle()
{
    Mail::fake();

    $listener = new SendFooEmail();
    $listener->handle();

    Mail::assertSentTo('foo@example.com', SendFooEmail::class); // "Undefined index: email"
}

```

**Comment by DCzajkowski** [comment]
```php
Mail::fake();

$listener = new SendFooMail();
$listener->handle();

Mail::assertSent(FooMail::class, function ($mail) {
    return $mail->to[0]['address'] == 'foo@example.com';
})
```

Cannot reproduce anymore. I think can be closed.

**Comment by Nashon-Juma** [comment]
requires some adjustments
