### ISSUE TITLE
Testing\DatabaseTransactions trait does not support non-default database connections

### ISSUE THREAD

**Issue by jarednipper** [laravel/framework#16682]
- Laravel Version: 5.3.24
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.7

### Description:
The Illuminate\Foundation\Testing\DatabaseTransactions trait does not support non-default database connections.

### Steps To Reproduce:
Make a test that uses a different database connection than the default, the transaction is not rolled back.

**Comment by stebogit** [comment]
Hey @jarednipper did you close this because you found a solution?
I'm using Laravel 5.5.40 and I'm having the same issue, but I'm not sure if that depends on the MySQL version (5.7 in my case as well), as mentioned [here](https://laracasts.com/discuss/channels/laravel/databasetransaction-not-working?page=1), or as you pointed out `DatabaseTransactions` just does not work on non default connections.

**Comment by jarednipper** [comment]
@stebogit unfortunately I don't remember what happened. I think we ended up not using transactions. Not sure why I closed it though.
