### ISSUE TITLE
Application extending the Container.

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#16716]
- Laravel Version:5.3
- PHP Version: 7.0
- Database Driver & Version: PDO

This might seem like a stupid question but hey I am not getting much response elsewhere, and I am trying to figure out how Laravel's container works exactly.

I am curious as why to Laravel extends the container from the Application class. Why exactly does it pass in an instance of $app as to the container? RegisterBaseBindings actually looks like it binds 2 app instances in the container and sets 1 static instance on the container.

- Why is the container not a separate class, why does it extend the Application.php class?
- Why push the Application itself into the container?
- It looks to me like the 2 $this->instance just pushes the Application into the container under 2 seperate names you can resolve. The static call looks to me like it creates shared instances which would be perfect for singletons with config, db connections, etc. Is this correct?

```
protected function registerBaseBindings()
{
    static::setInstance($this);

    $this->instance('app', $this);

    $this->instance('Illuminate\Container\Container', $this);
}
```

The more I get into a bit of higher PHP the less responses on questions I get on places like laracasts and stackoverflow. It might be because this could be better formulated but I hope this is alright to post here. Hopefully someone can clear this up a bit. Cheers :+1:

**Comment by abellion** [comment]
- Extending the application class with the container allows you to use the container methods directly within the app class ; I guess this is to have a fluent syntax, making ```$app->make(...)``` instead of ```$app->container->make(...)```

- Some class in Laravel have a static ```getInstance``` method, which is usually set when the class is instantiated. This is for retrieving the class instance from anywhere, without the need to pass it through the whole application lifecycle.

IMHO this last point is a very bad pattern and goes against the principes of OOP.
The application class should instantiate all the stuff she needs, and this class should be the entry point for using any of the Laravel components.

**Comment by GrahamCampbell** [comment]
You should instead be asking for an instance of the container contract, not the container class.
