### ISSUE TITLE
Translation performance question

### ISSUE THREAD

**Issue by ahmadazimi** [laravel/framework#16781]
- Laravel Version: 5.3.26
- PHP Version: 5.6
- Database Driver & Version: POstgresql 9.6

### Description:

I'm working on complicated framework using Laravel with many translations! And I have a question about translation performance:

Which scenario is better, combining all related translation into one file or separate each section into an specific file.

For example my BPMS module has different sections, exceptions, titles, messages, etc.
Is it better to combine them in one file? Please just consider performance not code readabilty.

**Comment by fernandobandeira** [comment]
Generally a single file since it will be loaded just one time as you can see here:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Translation/Translator.php#L263

Also we keep this for bugs only so in the future try asking this on laracasts, just a gently warning 😄

**Comment by ahmadazimi** [comment]
Thank you @fernandobandeira , okay, I will ask them there ;-)

**Comment by ahmadazimi** [comment]
@fernandobandeira sorry!
But just one question, If they are loaded in the memory, then when in some page I need just exceptions (for example) translations section of my module, all translated values loaded in the memory. So it is not good idea to merge them all in one file. Yeah?

**Comment by fernandobandeira** [comment]
It's better to separate them if they're too specific and there's a chance that they won't be used, but keep in mind that you'll have them loaded in that page even if they aren't needed there but were used before. The best thing would be to see which translations are used more often and which are more specific and separate them accordingly but most of the times it isn't worth it since these "specific" files will be really small...

**Comment by ahmadazimi** [comment]
Thank you so much @fernandobandeira 
I think that is the best suggestion for me :-)
