### ISSUE TITLE
weird/wrong condition query builder

### ISSUE THREAD

**Issue by ChristianYeah** [laravel/framework#16962]
- Laravel Version:5.3.16
- PHP Version: 7.0
- Database Driver & Version:MariaDB 10.1.20

### Description/code:
I run the code below, to get yesterday's data, however, the query builder will generate some strange conditions.

1. check if data exists/if not insert
2.update fields
3.even if in the updateField function, i comment the where function, the query log still shows the condition with the date of today
```php
class someController extends Controller{
    private static $connection;
    public function __construct()
    {
        self::$connection = DB::connection('restaurant')->table('amounts');
    }
    private function isDateExists()
    {
        if(!self::$connection->where('date',$this->date)->count())
            self::$connection->insert( $someData );
        return true;
    }
    public function updateTemp(Request $request)
    {
        //see if need to debug, which means forcing update
        $debug = intval($request->query('debug'));
        // check if date exists
        $this->isDateExists();
        // update fields/field
        $this->updateField(['temp','humidity'],$debug);
    }
    private function updateField($key, $debug)
    {
        DB::connection('restaurant')->enableQueryLog();
        $res = self::$connection->select($key)
//          ->where('date',date('d/m/Y',strtotime('-1 day')))
             ->get();
         dd(DB::connection('restaurant')->getQueryLog());
    }
}
```

DEBUG shows below
```php
array:1 [▼
  0 => array:3 [▼
    "query" => "select `temp` from `amounts` where `date` = ?"
    "bindings" => array:1 [▼
      0 => "25/12/2016"
    ]
    "time" => 0.33
  ]
]
```

**Comment by Edgpaez** [comment]
It looks to me like the "strange conditions" are caused because you're reusing the same `Query/Builder` instance created in this line: `self::$connection = DB::connection('restaurant')->table('amounts');` for different purposes (counting, inserting, updating, selecting).

I think I can help by explaining that when you run `self::$connection = DB::connection('restaurant')->table('amounts');` you don't create a DB connection, you just create a `Query/Builder` instance. 
That object holds the db connection [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Builder.php#L31) which is created by Laravel, so on top of that you don't have to take care of only creating it once.

So I think you can:
# Try injecting the DB connection (or the model) 
# Create one query for each thing you have to do


Or if I got it completely wrong maybe add more details to this "generate some strange conditions." problem.

Cheers

**Comment by ChristianYeah** [comment]
@Edgpaez i think you are right. i thought self::$connection = DB::connection('restaurant')->table('amounts'); is simply to create the connect. I'm going to check it through again.
 Thanks a lot
