### ISSUE TITLE
Auth: Making logging out fast and simple

### ISSUE THREAD

**Issue by khooz** [laravel/framework#16978]
- Laravel Version: 5.3
- PHP Version: Irrelavent
- Database Driver & Version: Irrelavent

### Description:
Hi, 

This is more of a suggestion. The new Laravel `Auth::routes()` register routes for authentication purposes and is by default placed in the `web` routeing group which forces CSRF token verification.

This is all cool but one: the logout route is forced by `POST` and requires CSRF tokens. Not only this is a nuisance to make a form, force a click event to submit that, but a kind of security risk. The logout (as far as I experienced) should have no checks and be an `any` route. anywhere in the process, the client should be able to quit as fast and simple as possible.

Consider this: the user has left his session on for a while; The token which lives shorter than the whole session, expires and another [good willing] user tries to log out and carry on with another task. The third party in question is forced to reload the page, probably see some of first party user's info [unintentionally] and log out through a post request that can't be done unless the page is loaded.

This whole process would have been shorter if the logout button was a link to logout URL, using a get request.

I myself have tried enforcing an exception through redefining `VerifyCsrfToken` in `LoginController`'s constructor, but the `web` group middlewares take precedence naturally.

Thanks

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Feel free to discuss this on the forums. We are happy with our logout implementation at the moment though. It matches what big players such as GitHub and Twitter do too.

**Comment by sisve** [comment]
> the logout route is forced by POST and requires CSRF tokens. Not only this is a nuisance to make a form, force a click event to submit that, but a kind of security risk. 

... or just show a form, and a normal submit button. No need for javascript.

> The logout (as far as I experienced) should have no checks and be an any route. anywhere in the process, the client should be able to quit as fast and simple as possible.

This would also allow the Evil Hacker Sisve to add a `<img src="http://homestead/logout" />` somewhere (perhaps inline in a GitHub comment), to make your browser issue a GET request and log you out.

> Consider this: the user has left his session on for a while; The token which lives shorter than the whole session, expires and another [good willing] user tries to log out and carry on with another task.

The token is stored within the session, and its lifespan should match that of the session. Are you describing a scenario where two users have a shared computer that is left logged in for some time before the next user uses the computer? 

> The third party in question is forced to reload the page, probably see some of first party user's info [unintentionally] and log out through a post request that can't be done unless the page is loaded.

The third party already has full access to everything; he is logged in as the user. The third party could choose not to press the logout anyway, and just go to "view my credit card details" or any other similar page.

Since the complete session has timed out and is no longer available; what you describe is the "remember me" checkbox in the default login dialog. The browser still has enough cookies to login the user again, and the user has authorized the browser to keep this information. The security issue is allowing an untrusted third party to use the same browser while still logged in.
