### ISSUE TITLE
[5.4] View Composers are broken

### ISSUE THREAD

**Issue by brunogaspar** [laravel/framework#17275]
- Laravel Version: 5.4.x-dev 86cf738
- PHP Version: 7.1.0
- Database Driver & Version: _Not relevant_

### Description:

View Composers seems completely broken from a week or so to now.

### Steps To Reproduce:

```php
view()->composer('*', function ($view) {
    $view->with('currentUser', $this->guard()->user());
});
```

The above no longer works but the below works:

```php
view()->composer('*', function ($viewName, $view) {
    $view[0]->with('currentUser', $this->guard()->user());
});
```

The same happens on View Composer classes.

Maybe this is the expected way to use now? Seems weird heh

**Comment by arthurkirkosa** [comment]
Same here

**Comment by taylorotwell** [comment]
Ah, yeah, that's a by-product of how wildcard events are passed to you now. Will look at cleaning that up for view composers because it doesn't make much sense in that situation.

Basically, wildcard events signatures now look like:

Event::listen('*', function ($eventName, array $eventData) {});

This allows you to not have to call Event::firing() etc to get the view name and also be able to get all of the arguments in one array. 

For view composers of course there is only ever one argument so I'll try to fix it for view composers.

**Comment by brunogaspar** [comment]
Thanks for the feedback @taylorotwell

**Comment by taylorotwell** [comment]
Fixed.

**Comment by brunogaspar** [comment]
Working fine now, thanks!
