### ISSUE TITLE
Route parameters return a unexpected value

### ISSUE THREAD

**Issue by Donny5300** [laravel/framework#17297]
Hi!

Using route parameters causes a unexpected result. See my example:

```
Route::group(['domain' => '{route_template}-{presetId}.templates.webshop.dev', 'middleware' => 'domain_handler'], function () {
    Route::get('/', function () {
        dd( __LINE__ . ':[' . __FILE__ . ']' , request()->route()->parameters());
    });
});
```

Lets say i have the URL my-template-2.templates.webshop.dev, the expected result would be `route_template => my-template` and `presetId => 2'. Currently the parameters return a other value: `route_template => my` and 'presetId => template-2`. 

When my url would be `my_template-2.templates.webshop.dev`, it gives me the result i expected. `route_template => my_template` and `presetId => 2`

- Laravel Version: 5.3.26
- PHP Version: 7.0.1

**Comment by themsaid** [comment]
`my-template-2` for `{route_template}-{presetId}` that makes sense, it matches the first `-` and partitions based on that. 

My suggestion is to change the URL signature if you want to be able to match them like `{route_template}-{presetId}`, make sure you only have a single `-` in the URL.

Closing since it's not an issue with the framework.
