### ISSUE TITLE
Create new on other than default connection 

### ISSUE THREAD

**Issue by reno1979** [laravel/framework#17384]
- Laravel Version: beta (used this proposed fix: https://github.com/laravel/framework/pull/16103 scheduled for laravel 5.4) 
- PHP Version: 7.0.1
- Database Driver & Version: Mysql 5.6

The model create method keeps using the default db.
We are using artisan tinker, and tried the following:

```
\App\FeatureGroup::on('otherConnection')->getModel()->create(['name'=>'test']);
// a new row is inserted in the default db, but should be in the otherConnection db
// firstOrCreate does the same :( 

/* OUR WORKAROUND */

$featureGroupModel = new \App\FeatureGroup;
$featureGroupModel->setConnection('otherConnection');
$featureGroupModel->save();

$featureGroupModel->id; // the given id is from the new table row in otherConnection db :)

// or 

\App\FeatureGroup::on('otherConnection')->getModel()->firstOrNew(['name'=>'test'])->save();

```

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest php 7.0.x or 7.1.x.

**Comment by themsaid** [comment]
@reno1979 that fix wasn't related to creating model, just querying related models on the parent connection.

I've submitted a proposal to add a connection argument to the connection method, not sure if it'll pass though since you can already do it by constructing the instance yourself.

https://github.com/laravel/framework/pull/17392

**Comment by reno1979** [comment]
@themsaid Thank you for looking in to this. Constructing a new instance is our current work arround. It just seems odd that the create methods always falls back to the default connection settings.
