### ISSUE TITLE
Laravel Eloquent Union query bug

### ISSUE THREAD

**Issue by rotaercz** [laravel/framework#17438]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version: Using Homestead on virtualbox

### Description:
Union isn't working with orderBy() in certain cases.

### Steps To Reproduce:
So I have the following query:

	$a = Model::where('code', '=', $code)
		->where('col_a', '=' , 1)
		->orderBy(DB::raw('FIELD(layout, "normal", "split", "flip", "double-faced", "") ASC, layout'))
		
	$b = Model::where('code', '=', $code)
		->where('col_b', '=' , 1)
		->orderBy(DB::raw('FIELD(layout, "normal", "split", "flip", "double-faced", "") ASC, layout'))
	
	$a->union($b)->get();

No sorting is happening when I orderBy() first and then union.

When I do query $a or $b individually the orderBy() works fine.

When I do it in the following way orderBy() happens as a whole.

	$a->union($b)
		->orderBy(DB::raw('FIELD(layout, "normal", "split", "flip", "double-faced", "") ASC, layout'))
		->get();

How can I make it so the orderBy() applies for each individually and then union the results back? It seems like it should work.

**Comment by themsaid** [comment]
My suggestion here is that you do the sorting after the query is done completely, but actually do it using `Eloquent\Collection` not via orderBy, this gives you more flexibility on how you'd like to order the items in the collection.

**Comment by themsaid** [comment]
So for example you may select() the output of FIELD() and the order by code+value of field, something like:

`$item->code+$item->field`, this will insure items of same code are after each other and orderd by field.

**Comment by fernandobandeira** [comment]
Yes you can order it afterwards but I think that in the example @rotaercz  gave he needs it individually, i'll give another example for needing this individually:

There's a users table and a leads table, each one has a pagesViewed and email field, now you want to get the email of the users ordered by the pagesViewed (descending) and aftewards you want to get the leads emails ordered by the pagesViewed (descending).
Sorting it afterwards will merge the results so it won't order it as you want...

In the example @rotaercz gave if he wanted to merge the result he wouldn't even be using union since he could just add an orWhere clause on the first select, it's the same table, same order, etc....

**Comment by rotaercz** [comment]
@fernandobandeira What fernandobandeira said is correct. I wanted to do it individually and it seems like a bug that it doesn't work this way.

**Comment by rotaercz** [comment]
One way to solve the ordering would be like this:

	$a = Model::where('code', '=', $code)
		->where('col_a', '=' , 1)
		->orderBy(DB::raw('FIELD(layout, "normal", "split", "flip", "double-faced", "") ASC, layout'))
		->get();

	$b = Model::where('code', '=', $code)
		->where('col_b', '=' , 1)
		->orderBy(DB::raw('FIELD(layout, "normal", "split", "flip", "double-faced", "") ASC, layout'))
		->get();

	$result = $a->merge($b);

But this is not good because it requires n number of queries, in this case 2 queries which are $a and $b, hitting the database instead of a single query.
