### ISSUE TITLE
mysql date and laravel. Not inserting/updating dates with zero

### ISSUE THREAD

**Issue by AucT** [laravel/framework#17464]
- Laravel Version: v5.3.29
- PHP Version: 7
- mysql 5.7: (with 5.6 config)

### Description:
When trying to update insert record with column type **date** with value like '**1980-00-00**' throws error

> Illuminate\Database\QueryException with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '1980-00-00' for column 'birthday' at row 1 (SQL: update `persons` set `birthday` = 1980-00-00 where `id` = 22)'

When using raw php pdo or phpmyadmin same operation (updating date to 1980-00-00) works fine.
### Steps To Reproduce:

`Illuminate\Support\Facades\DB::table('persons')->where('id',22)->update(['birthday'=>'1980-00-00']);
`

**Comment by sisve** [comment]
This is due to the fantastic strict mode that forces people to have correct values and write correct SQL code. I love the strict mode. It's the best thing since the 486.

Anyhow, you are trying to insert an utterly invalid and nonexistant date of 1980-00-00. It's preposterous; why should a database, that has been told to care about your data, allow such a absurd value? You can do these foolish things via "raw" queries or phpMyAdmin because those do not run in strict mode.

Possible solutions;
1) Don't insert senseless data into your database.
2) Disable strict mode in `config/database.php` and hope mysql always does the right thing. https://github.com/laravel/laravel/blob/master/config/database.php#L65

**Comment by GrahamCampbell** [comment]
1980-00-00 is not a valid date...
