### ISSUE TITLE
[5.4] Cross-connection has not working

### ISSUE THREAD

**Issue by chancezeus** [laravel/framework#17624]
- Laravel Version: 5.4.6
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.16

### Description:
I have a similar setup as mentioned in #17515 (two schema's on a single server and a couple of relationships between those). I explicitly specified both connections but as soon as I try a has (and probably whereHas too) query from the model on the first connection to a model on the second connection it fails stating that the second model's table can not be found (using the first connections schema), which is correct but wrong, since the relationship should know to look (since it is explicitly specified) in the second connections schema (probably a simple (pseudocode)
```
if ($model1->getConnectionName() != $model2->getConnectionName()) {
  $model2->{fullyQualifiedColumnName} =
$model2->getConnection()->getSchema().".".$model2->{fullyQualifiedColumnName};
}
```
would suffice to fix the issue (assuming both schema's are on the same database server (otherwise it would never work, since it is near impossible to do subqueries across different server connections))

### Steps To Reproduce:
1. Create two schema's (ie schema1 & schema2)
2. Create two models one in each database (ie model1 (model1 $connection == 'schema1connection') & model2 (model2 $connection == 'schema2connection'))
3. Create a relationship between those models (ie on model1: $this->hasMany(Model2::class))
4. Execute Model1::has('model2relation')->get()

### Expected results
Since both models have their connections explicitly specified I'd expect to see it reflected in the resulting (sub)select (ie
```
WHERE [`schema1`.]`model1table`.`model1column` = `schema2`.`model2table`.`model2column`
```
) with schema1 optional since the query runs on this connection

**Comment by chancezeus** [comment]
A (cleaned up) error message:
```
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'schema1.model1' doesn't exist (SQL: select * from `model2` where exists (select * from `model2` where `model1`.`id` = `model2`.`model1_id`) limit 1)'
```

**Comment by chrislandeza** [comment]
This was already reported here: https://github.com/laravel/framework/issues/4649

**Comment by chancezeus** [comment]
The report you reference seems to be about 2 different servers, my report is about 1 server 2 schema's which is a different situation (since cross schema (ie. on the same server) JOINs/SUBSELECTs are possible, JOINs/SUBSELECT(s) on a different server not)...

**Comment by RemotePhantom** [comment]
Hello,

I have the same problem at the moment. I can get for example cars with motors (i use the with function and can also say wich motors i want) without any problems accross two databases on the same server. 

But if i want for example only cars with motors where the motor has a specific power (the whereHas function) it is not working.

The real code is about adminlogs and the user -> player. I want to search for logs where the player->name is like something. (adminlog and user are in one database and player is in another, but on the same server). You can see the code on the attached screenshot. A workaround is that i can do it only with the with function and filter through the collection and remove the null relations. But that is not a solution because i call later other where and orderBy functions + paginate and this collection can be very big in the end.

sorry for my english.

![screenshot](https://user-images.githubusercontent.com/18661391/27599706-ec906ccc-5b69-11e7-987d-3398b78d6aae.png)

**Comment by skalero01** [comment]
Does this issue continue existing or it was fixed? Regards

**Comment by MalteJanz** [comment]
I didn't tested it until now and that project with the problem is not running anymore. Maybe someone else could try it out (with a very basic example).

Regards

**Comment by maguilar92** [comment]
I added package to manage this issue:

[https://github.com/hoyvoy/laravel-cross-database-subqueries](url)
