### ISSUE TITLE
[5.4] Blade setContentTags removed

### ISSUE THREAD

**Issue by Milananas** [laravel/framework#17640]
- Laravel Version: 5.4.6
- PHP Version: 5.6.29

### Description:

In this [commit](https://github.com/laravel/framework/commit/5e394bb2c4b20833ea07b052823fe744491bdbd5) all methods have been removed for customizing blade tags, and I can't find a reason why this has been done. 

### Steps To Reproduce:

Just put this line somewhere in your routes file for example:

`Blade::setContentTags('[[', ']]');`

**Comment by GrahamCampbell** [comment]
Yes, this feature has been removed.

**Comment by frenkieh** [comment]
I used this method to ensure compatibility with AngularJS. Is there another way to set the tags now? I don't understand why the method (along with setEscapedContentTags and setRawTags) was removed without deprecation notice or explanation

**Comment by mtpultz** [comment]
@GrahamCampbell is there currently a way to ensure compatibility with AngularJS by changing the delimiters?  We load the initial page with blade then the other 99% of the application is AngularJS so we liked being able to change the blade delimiters since the most used technology isn't being altered for developers.

**Comment by crynobone** [comment]
![screenshot_2017-03-03-07-13-51-485_com android chrome](https://cloud.githubusercontent.com/assets/172966/23531415/4988b6bc-ffe1-11e6-9d15-6ba540b16dd6.png)
