### ISSUE TITLE
[5.3] PDO/Query Exception when paginating DB query with custom columns array

### ISSUE THREAD

**Issue by c00p3r** [laravel/framework#17752]
- Laravel Version: 5.3.30
- PHP Version: 5.6.4
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.17, for Linux 

### Description:
When I try to make such query:
```
$weight_log = DB::table('weight_log')
                ->where('user_id', $user->id)
                ->orderBy('created_at', 'desc')
                ->paginate(15, ['weight', 'created_at']);
```
I get 2 Exceptions like this:
```
PDOException in /vendor/laravel/framework/src/Illuminate/Database/Connection.php line 333:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `created_at`) as aggregate from `weight_log` where `user_id` = ?' at line 1
```
and
```
QueryException in /vendor/laravel/framework/src/Illuminate/Database/Connection.php line 770:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `created_at`) as aggregate from `weight_log` where `user_id` = ?' at line 1 (SQL: select count(`weight`, `created_at`) as aggregate from `weight_log` where `user_id` = 1)
```

**Comment by GrahamCampbell** [comment]
Please try with Laravel 5.4 and open a new issue if this remains.

**Comment by c00p3r** [comment]
So v 5.3 no longer supported?
What if I have a big project and can't update laravel version due to risk of more issues may occur in other places?

**Comment by fernandobandeira** [comment]
What are you expecting to get calling:
```php
->paginate(15, ['weight', 'created_at']);
```
?
Are you calling this to have just these columns on your result or is there another reason?
You can call it like this if that's what you need:
```php
$weight_log = DB::table('weight_log')
                ->select('weight', 'created_at')
                ->where('user_id', $user->id)
                ->orderBy('created_at', 'desc')
                ->paginate(15);
```

The problem here is that Laravel is generating this statement:
```sql
count(`weight`, `created_at`)
```

This is invalid, you can only pass 1 column to your count function, I've tested it and MySQL / PostgreSQL throws an error when you use more than 1 parameter. I'm not sure why it's like this but it's the same on 5.4...

Also 5.3 should be receiving bug fixes till 23/02/2017 AFAIK, since it was released on 23/08/2016 and it should have 6 months of bug fixes...

**Comment by c00p3r** [comment]
@fernandobandeira you are right. That's exactly what I expected

The reason I opened this issue: it's misleading when you look at `paginate` method declaration and it says it accepts `columns` parameter but indeed it's not and provokes the exception

**Comment by ifaniqbal** [comment]
I've created step by step to produce this error on this issue: #19298
