### ISSUE TITLE
Extending/Overloading Model::create no longer works

### ISSUE THREAD

**Issue by jahumes** [laravel/framework#17876]
- Laravel Version: 5.4.9
- PHP Version: 7.1.0
- Database Driver & Version: 5.7.16-0ubuntu0.16.04.1

### Description:
When you override an Eloquent Model with `public static function create` and have it call parent::create, you are getting a never ending loop because it sends it to line 1326 `__callStatic` which instantiates a new version of the Model and calls create on it. Because the create method was removed from Model, this just calls your create method again.

It appears that the create method was moved to the Builder class (I can't see any documentation in any release notes) and this causes a breaking change when upgrading to 5.4. Is there a new way to do this?

### Steps To Reproduce:

1. Create a new trait that overrides `public static function create()`
2. Make sure your create uses parent::create
2. Attach to an Eloquent Model
3. Try creating the model

**Comment by jahumes** [comment]
The only option I can see is to modify my query to do `(new static)->newQuery()->create($attributes);`

**Comment by themsaid** [comment]
Copying from the upgrade guide https://laravel.com/docs/5.4/upgrade

## The create & forceCreate Methods

The Model::create & Model:: forceCreate methods have been moved to the  Illuminate\Database\Eloquent\Builder class in order to provide better support for creating models on multiple connections. However, if you are extending these methods in your own models, you will need to modify your implementation to call the create method on the builder. For example:

```
public static function create(array $attributes = [])
{
    $model = static::query()->create($attributes);

    // ...

    return $model;
}
```

**Comment by jahumes** [comment]
@themsaid I can't believe I didn't see that. Thanks!

**Comment by themsaid** [comment]
welcome :) It was only added a few days ago.

**Comment by dsmarion** [comment]
Wow did I need this today!  Thanks!
