### ISSUE TITLE
Pagination Issue - Don't move to the next page

### ISSUE THREAD

**Issue by grimpa** [laravel/framework#17907]
- Laravel Version: 5.4
- PHP Version: 5.6.30
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

### Description:

- The pagination works apparently, but when I click to go to another page the data isn't loaded.
- The links are generated successfully and the parameter is correct and is changed in each click: ?page=2 ?page=3...but it does not load the data from the new page.

### Steps To Reproduce:

My Controller:
`
$data = \App\Model::paginate(10);
return view('myview', ['data' => $data]);
`

My View:
`
{{ $data->links() }}
`

**Comment by themsaid** [comment]
It appears to be working for me, please try to replicate the issue on a fresh laravel installation.

**Comment by grimpa** [comment]
@themsaid I tried to install a new instance of laravel, but the problem persists and nothing appears in the log. I really don't know whats happening.

Any another ideia?

**Comment by eugenevdm** [comment]
I dealing with a similar issue. I had to install Paginator from version 5.4 because I'm running WHMCS and they have heavily outdated components. The closest match I've found to solving this problem is that perhaps your NGinx is not configured properly, see here:

https://laracasts.com/discuss/channels/laravel/pagination-not-rendering-next-results

There they say you have to change in NGinx this:

`try_files $uri $uri/ /index.php$args;`

to

`try_files $uri $uri/ /index.php?$query_string;`

I would be curiously to know if you solved this problem because for me it's not working.
