### ISSUE TITLE
Throttle not working if cache storage is set to array

### ISSUE THREAD

**Issue by msolhao** [laravel/framework#17982]
- Laravel Version: 5.3.30
- PHP Version: 7.1
- Database Driver & Version: sqlite

### Description:
If cache storage is set to **array**, the login throttling doesn't work as expected.

### Steps To Reproduce:
- Fresh Laravel installation
- Set _CACHE_DRIVER=array_ in .env file
- It should allow only 5 login attemps

**Comment by astierler** [comment]
The array cache is simply that, an array in memory **for that request only**. (You are essentially not caching at all if using `array` - unless referencing the same item in the array cache multiple times throughout the request).

There's simply no way around that, since the RateLimiter is part of the Cache object. Not sure if there's a way to overwrite/specify the cache used by the rate limiter.  If you wanted to do it, my suggestion would be to take the `vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php` Middleware and copy into your `Http\Middleware` (or extend it),

and simply overwrite the `__construct` to specify a separate cache (ie. apc would be good if installed and single server application).

```php
    public function __construct(Cache $cache)
    {
        $this->cache = $cache;
    }
```
to
```php
    public function __construct(Cache $cache)
    {
        $this->cache = \Cache::driver('apc');
    }
```

That's kind of hacky, but it may work - I didn't test :smiley:   But you'd probably be better off just using a better cache if possible, even `file` when developing locally.

**Comment by GrahamCampbell** [comment]
> If cache storage is set to array, the login throttling doesn't work as expected.

It does work as expected. The array driver only persists for the lifetime of the single application instance, so the expected behaviour, is for the count to be lost between requests.

**Comment by Tarasovych** [comment]
Same issue.
Laravel Version: 5.6.15
PHP Version: 7.1
Database Driver: mysql

Works fine with `SESSION_DRIVER=file`.
