### ISSUE TITLE
Store session data per key

### ISSUE THREAD

**Issue by denjaland** [laravel/framework#18187]
- Laravel Version: 5.4
- PHP Version:7.1
- Database Driver & Version:

### Description:
We're seeing a lot of issues with concurrent requests to the server where session information is lost.  Seeing on other forums and discussions on the slack channels, I see a lot of use cases where concurrent requests cause for session data to be lost.

Much of the issues could in my opinion be prevented if not ALL session data is stored at the same time, but if laravel would only update session data for those keys that actually require update.

In our project, for instance, we are having a polling mechanism that asks the server for the current session state; each such request however SAVES the session data in its entirety.  If - at the same time - the user is doing a rest request to authenticate, or to log out, or basically to do any action that might require session data to be updated, we're having a lot of risks of the requests to impact one another.

request A: POST/auth/login
request B: GET /session/state

if both these requests are sent to the server, B updates the session because user logs in, but request A was already started, and saves the session after that, the authentication information is lost, and the user is logged out again, even though he just authenticated.

I think it's a "big" change, but it would be better if only session data that is changed, is being saved.  at this time, the entire session data is always being stored, which isn't desirable.

Adding a key to the method that stores data will be breaking for all drivers, and may impact existing users that have implemented drivers.  therefore, I believe it would be advisable that laravel checks the driver method using reflection to see if the driver already supports key-based storing, and if not should log a warning and fallback to old mechanism.  In later laravel version (6?), we could deprecate the old way of dealing with it.

Any thoughts?

**Comment by denjaland** [comment]
Just wanted to add that I noticed the startSession middleware is terminable.
The terminate method is... storing session.

Since the terminate is executed at the very end of a request (even after sending data to the client), it seems to be a potentially long time between the start of the session, and the storage at terminating middleware, and this definitely explains why I'm seeing such strange behaviour.

I also see that it seems to be calling an ageing method of some sort for flash messages, which might explain why this has been done.

I really think this needs to be tackled in some way :-)

**Comment by sisve** [comment]
This is a "known" issue since at least Laravel 5.1. https://github.com/laravel/framework/issues/14385

**Comment by denjaland** [comment]
Hi @sisve!
Thanks for referencing that issue.
I think mine is a bit different though.  I'm not sure that the session is completely wiped out, and the suggested solution in that issue won't fix the real issue that we have.

I'm mainly concerned that - when I checked the bits of code you sent me through slack - there is a small design issue that you won't be able to fix by migrating to database or to redis either.
If I understood correctly from what I briefly saw the sessionmiddle ware that creates the middleware is terminable, meaning there is logic in the terminate() method of that middleware.

In that temination, the session data is saved (I'm thinking because they want to get rid of the flash messages, hence they wait for data to have been sent to the browser before they "age"/remove the flash messages from the session.

The big issue there is that - no matter what little piece of information the session you want to update, ALL session data is being saved again.  So even data that we didn't want to update, is being saved.  So no matter what driver you have behind that, I don't think this will be fixed.

Considering that it's in the terminate of the middleware, you are creating a big timeframe between the start of the request (in which session information is being retrieved), and the final save.  If another concurrent request has meanwhile taken place, you might be saving outdated information to the session.

I believe that when we can avoid the entire session being saved, but make saves key-based, a lot will be fixed, for many use cases.  I understand that the flash messages need to be erased, but if we can achieve that by just updating the session.flash data, and not the entire session, it will be more secure.

The solution of not allowing multiple requests is theoretically a good suggestion; in practice it's not.  I know a lot of users - including myself - tend to open multiple tabs of the same app because it makes switching easier if you need to compare stuff for instance; you can not and should never trust that you can control the number of requests that come in and in what order.

Furthermore - the whole idea of sessions is that the information held by the session is available throughout... the session.  I don't think it's wise to update session information that shouldn't be touched.

I hope this makes sense.  I LOVE Laravel, but this is a real issue that I think we should be able to tackle.


Cheers,
David.

**Comment by denjaland** [comment]
I'm also thinking it might be interesting to load the flash messages at the BEGINNING of the request, save the session there, and get rid of the terminate process.  The flash messages are supposed to just live between two requests, right?  So you could probably get them at the beginning, and try to eliminate the session save at the end.  But that would be a workaround really.  I still believe it's a minor design issue to save data that might have been already updated by another request, since it's supposed to be session-wide.

This whole issue reminds me again of why I always try to eliminate anything that goes into sessions :-)

**Comment by LarsVonQualen** [comment]
Having the exact same issue. Our app is basically useless because of this, and the user experience is terrible, as in load the page (lots of concurrent requests), at the same time issue login request, and we loose the session, and the user is obviously not logged in, because stale session data is written to disc.

The obvious fix would be to stop using sessions and switch to a stateless token based scheme, but that would mean refactoring lots of application code, so another fix could be to change the terminate flow to something along the line of:
1. Lock the session file
2. Reload the data
3. Merge in delta changes
4. Write the file
5. Release the lock

Obviously locking sucks, but what else could possible be done to fix this issue?

The biggest problem in this fix is that this would be really hard to implement into the session Store implementation as it is today, because it's decoupled from the FileSessionHandler. That makes a lot of sense, but it makes this hard to fix.

**Comment by devbazilio** [comment]
storing session data to files is a worst case if you don't use ram as storage. If resource can be modified by different software , always use locking of data , at least mutexes

**Comment by imanghafoori1** [comment]
@denjaland Hi David, I spend more than our reading your nice descriptions to figure out the problem you wrote about.

As I understood you are talking about 2 concurrent requests from the SAME user, but seemingly @LarsVonQualen is talking about many users logging in, which I do not get how could be problematic.

The practical solution came to my mind, is to give a way to manually prevent session saving in request B.
```
request A: POST/auth/login
request B: GET /session/state
```
since these type of concurrent requests are identifiable, and do not randomly happen on each and every route.

It seems that automatic ajax calls, or from a mobile client, can create such a problem.
So if you know that the route you are defining is being hit by ajax calls and there is no need to CHANGE the session data to handle that, you can mark that route manually, and that causes the `StartSessionMiddleware` to just read the session data and skip overriding it at the end of the request on the terminating phase.

Effectively make that specific route a safe one to be concurrent with /login

all and all, it would be the developers job to identify the `session read-only` and `concurrently  hit` route and mark them in the way the framework allows.

this way there is at least a way to survive the situation and it would be fully backward compatible since it only changes the behavior if you explicitly mark your route with a new method that never existed in the old versions of laravel.

What do you think ?

**Comment by taylorotwell** [comment]
I can implement a "fix" for this by simply extending the session expiration in storage if the session data is exactly the same as it was at the beginning of the request. However, this would only work for certain drivers. I think I could make it work for the following drivers: database, redis, memcached, DynamoDB (maybe)...

I would have to add a `touch` method to the Cache contract, so it would be a breaking change.

I know it will definitely not be possible on the file driver.

I'm hesitant to implement it because this would not solve the "problem" of two concurrent requests modifying the session at the same time. Note this is also a "problem" in other web frameworks such as Rails as well.

**Comment by imanghafoori1** [comment]
what if we allow the user to somehow mark some routes as "concurrently",
So the expiration time does not need to be updated on the cookie when a request hits that route.
Basically this allows the server to respond without a cookie.(only on the routes which are marked as "concurenty.")

The user can accept this limitation (not updating cookie expiration time) to alleviate the problem quite a bit.
@taylorotwell

**Comment by msonowal** [comment]
> I can implement a "fix" for this by simply extending the session expiration in storage if the session data is exactly the same as it was at the beginning of the request. However, this would only work for certain drivers. I think I could make it work for the following drivers: database, redis, memcached, DynamoDB (maybe)...
> 
> I would have to add a `touch` method to the Cache contract, so it would be a breaking change.
> 
> I know it will definitely not be possible on the file driver.
> 
> I'm hesitant to implement it because this would not solve the "problem" of two concurrent requests modifying the session at the same time. Note this is also a "problem" in other web frameworks such as Rails as well. 

I think we should have it for these driver as its possible it would be good

**Comment by sisve** [comment]
Could we go the ASP.NET way and implement session locking? When routes are marked for write access to sessions they take out an exclusive lock so that other requests that wants to write to the session are blocked until the first is done.

This would effectively execute all requests with write-access to the session one at a time.

Ref: https://docs.microsoft.com/en-us/dotnet/api/system.web.sessionstate.sessionstatebehavior

**Comment by denjaland** [comment]
I agree with @sisve’s comment 👍

**Comment by taylorotwell** [comment]
@sisve how do you recommend determining which requests have "write access" to the session?

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/pull/32636

**Comment by denjaland** [comment]
@taylorotwell by adding a route middleware?
