### ISSUE TITLE
Handle signals for scheduled tasks registered without overlapping 

### ISSUE THREAD

**Issue by RoyalKnight** [laravel/framework#18202]
- Laravel Version: 5.1.45
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.5

### Description:
For tasks registered `withoutOverlapping()` a lock file is created. After execution the task's lock file is deleted, so the next execution becomes possible. If a system reboot or shutdown is triggered during task execution, the lock file is never deleted, so no task executions will happen until the lock file is deleted manually.

To avoid this behaviour at least `SIGTERM` and `SIGHUP` signals should be handled accordingly, so task execution is possible after system boot without manual interaction.

### Steps To Reproduce:
- Register some long run scheduler task `withoutOverlapping()`
- Trigger execution of scheduler task through `artisan`
- Reboot during task execution
- Trigger execution of scheduler task through `artisan`

**Comment by KKSzymanowski** [comment]
The same thing also happens(on Windows at least) when you "CTRL-C" the `schedule:run` command.

In order to handle signals, the Process Control(PCNTL) extension is required which is not available on non-Unix platforms. The scheduler can however check if the extension is available and attach signal handlers if it is; otherwise operate as it currently does.

**Comment by marconi1992** [comment]
Currently the version 5.4 implemented the cache service to lock tasks in order to solve this issue and others related with scheduled tasks running in enviroment with multiple instances.
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Scheduling/Event.php#L163

The task is unlocked when the cache expire, in this case 24 hours.

However I think problems related with unexpected shutdowns should handled by the developer, I don't use the withOverlapping method in complex scenarios, I prefer use lock on database level like this.

```php
$scheduledTasks = ScheduledTask::all(); // get all the schedule task from the database

foreach ($scheduledTasks  as $scheduledTask) {

    $schedule->call(function () use ($scheduledTask) {

        if (DB::select("SELECT GET_LOCK('task-" . $scheduledTask->id . "', 0) as 'lock'")[0]->lock) {

            $task = TaskBuilder::setScheduledTask($scheduledTask)->build(); // build an instance that implement my Task interface
            $task->run();

            DB::statement("SELECT RELEASE_LOCK('task-" . $scheduledTask->id . "');");

        }

    })
    ->name($scheduledTask->id)
    ->cron($scheduledTask->recurrence);
    
}
```
Therefore if the system go off while the task is running, the lock is released when the database session is closed, also you can set a timeout for realease the lock. https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock

**Comment by iggori** [comment]
I have the same problem. Probably there is some memcache key that I have no idea how to find and kill.

**Comment by symos** [comment]
I also had this problem.

After some digging in Laravel framework files, I found that the key is stored in cache (whichever kind you're using) and the key's name is the following:
'framework'.DIRECTORY_SEPARATOR.'schedule-'.sha1($this->expression.$this->command);

where:
DIRECTORY_SEPARATOR = '/' in Unix or '\' in Windows
expression = the cron schedule, e.g. for "everyMinute" it's "* * * * * *" (note that Laravel uses 6 levels instead of 5).
command = "'path to PHP' 'artisan' commandName" e.g. "'/usr/bin/php7.0' 'artisan' downloadSales"

So, for example, the cache entry name for command "downloadSales" is: "framework/schedule-ccbbea3234eabe830d0476258974ad1e0d8bf557".

You can delete this in tinker with Cache::forget if you want a locked command to start running again.

If, like I do, you have never-ending processes and you don't want them to start again every 24 hours when the default lock expires, you can make the lock much longer (as a parameter in "withoutOverlapping") and then delete the lock manually if the process dies and you need to start it again.

Although I think I'll do it a bit differently. I'll set the lock to a low number (e.g. 5 minutes) so that the command starts again automatically after a reboot, or if it dies etc. and then make the command itself extend its own lock every now and then using the above naming convention. Of course, I'll add a check to see if the cache entry already exists so that I'm alerted in case the naming convention changes.

**Comment by dtbarne** [comment]
If you can live with killing all cache for your application, you can simply `php artisan cache:clear` to release all locks.

**Comment by dtbarne** [comment]
To be clear, it will not cause all tasks to start again; it will just not prevent any currently running tasks from overlapping. In my case, I monitored ps to ensure it was the only process running first.
