### ISSUE TITLE
Request::getFiles returns null for test file

### ISSUE THREAD

**Issue by eberkund** [laravel/framework#18268]
- Laravel Version: 5.4.15
- PHP Version: 7.1

Running this test,

    $this->post('/foo/bar', function () {
        'foo' => [
            'bar' => UploadedFile::fake()->image('image.gif')
        ]
    });

Results in,

    public function index(Request $request) {
        $request->allFiles(); // returns []
        $request->file('some.file'); // returns null
    }

For an HTTP request send through Postman I get back an instance of `UploadedFile` as expected.

**Comment by themsaid** [comment]
A fix was submitted in https://github.com/laravel/framework/pull/18276

**Comment by morrizon** [comment]
@brachycera I have the same issue with PHP 5.6.10. The problem is when you try:

`
$temp = tmpfile();
imagepng(imagecreatetruecolor($width, $height), $temp);
`

If you try to read the file after imagepng you will get an error. I'm not sure why that happens. Looks like the resource is changed:

`
$temp = tmpfile();
var_dump($temp) // show something like resource(2, stream);
imagepng(imagecreatetruecolor($width, $height), $temp);
var_dump($temp) // show something like resource(2, Unknown);
`

A workaround to the problem is:

`
ob_start();
imagepng(imagecreatetruecolor($width, $height));
fwrite($temp, ob_get_clean());
`

**Comment by morrizon** [comment]
@brachycera about your problem, reading the [doc of imagepng](http://php.net/manual/en/function.imagepng.php):

```
The path or an open stream resource (which is automatically being closed after
this function returns) to save the file to. If not set or NULL, the raw image stream
 will be outputted directly.
```

I think that was the problem., the resource will be closed and removed (behaviour of tmpfile when close the resource).
