### ISSUE TITLE
Session name

### ISSUE THREAD

**Issue by EmilMoe** [laravel/framework#18357]
I have had issues keep people authenticated in particular Internet Explorer and also Edge, but only on some machines (I had to set up a VM myself as my main computer worked fine).

I am using SAML2 so the login is done in a Listener without CSRF, but never any problems in Safari, Opera, Chrome and Firefox.

I have been struggling with this issue for months, but today I came across a post that suggested renaming the session name by removing the underscore - which seems to work. I can't give any technical explanation what goes wrong in Microsoft browsers, so I'm not creating a PR on this yet - maybe someone can give the technical description?

I found the recommendation here http://stackoverflow.com/a/40814059/6102188

I have described my issue here on Laracasts, it might add a few more details: https://laracasts.com/discuss/channels/laravel/session-lost-after-login

My reason for this post is that if it's really an issue in some browsers, I think the default name for sessions should be something like `laravelsession`.

**Comment by EmilMoe** [comment]
Here are some additional information to back me up:
https://www.webfactory.de/blog/cookies-broken-in-internet-explorer

**Comment by sisve** [comment]
Those two does not back you up.

> IE does not accept cookies from **domain names** containing an underscore

> After you install security patch MS01-055 for **Microsoft Internet Explorer 5.5 or 6.0**, you may encounter the following problems

Also, I do not give much credibility to the research behind a low-quality "doing this worked for me" answer on Stack Overflow. He may be right, it did work for him, but it doesn't explain _why_. How can we know that this is a framework-wide concern an not a local package issue?  Could you provide a minimal example application (would probably be enough with a single controller that used a session) that we can use to reproduce your problem locally?

**Comment by spsiddarthan** [comment]
Source: https://github.com/expressjs/express/issues/1459#issuecomment-11909889 
Original source: http://www.ietf.org/rfc/rfc1035.txt

Just copying the answer from the issue I have referenced here for ease of reading. 

```
The labels must follow the rules for ARPANET host names. They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen. There are also some
restrictions on the length. Labels must be 63 characters or less.
```
The problem is that IE drops cookies for domain names that don't follow the RFC.

**Comment by sisve** [comment]
All your linked issues is about **domain names** and their effect on IE's cookies, but isn't this issue about the underline character in the **cookie name**?

**Comment by EmilMoe** [comment]
I am still looking for better proof, but a lot of people have had the hands on experiences with this:

http://stackoverflow.com/a/306601/6102188

**Comment by sisve** [comment]
That is just another post about machine/domain names, not cookie names.

If cookie names were to blame, no Laravel installation would work out-of-the-box with Internet Explorer. That would probably have lead to a large amount of bug reports and quick fix if that was the case.

**Comment by laurencei** [comment]
@themsaid - I came here based upon your tweet.

I remember this **exact** issue from my Codeigniter days over 4 years ago.

 @EmilMoe is right that some IE browsers dont like the `_` in the session name. Even CI had a default `_` in the session name IIRC. I dont remember the exact circumstances - but removing the `_` from the session would solve it for my IE6 clients back then.

However, that was a very long time ago. I would be surprised if it still affected IE10/Edge browsers. Especially that the issue would probably have come up by many other people?

Still - what is the harm in not having a `_` in the default session name, even if it only fixes a small edge case?

**Comment by laurencei** [comment]
Lol - Looks like I answered a related SO post about this topic almost exactly 5 years ago: http://stackoverflow.com/a/10150855/1317935

**Comment by Garbee** [comment]
Diagnosing a problem to find the root cause and addressing that is better than stamping a rubber fix onto a problem and hoping that's the end.

Developers that hit this can change the session name in their applications. For already deployed setups, yes you lose current sessions. But the problem is fixed for them. It clearly isn't *everyone* that has this problem with Laravel or there would be many more reports about this. There is some inconsistency that is occurring that causes this.

Anyone who has noticed this issue, have you modified any other session config values? If so could you please share those changes.

Thank you.

**Comment by laurencei** [comment]
Here is a blog post from 2010 about the same issue:

https://rhsumon.wordpress.com/2010/05/25/codeigniter-session-problem-in-ie/

Seems like a common edge case. I agree that the `_` only is probably not the *only* cause - but the removal *seems* to help lots of people *if* you have a session problem.

**Comment by Garbee** [comment]
@laurencei That only confirms in *Domain names* and *Hostnames* not **cookie names** as being discussed here.

**Comment by Garbee** [comment]
This has been shared on the Edge teams mailing list so hopefully someone internal can take a look and see if a problem exists for cookie names within their current code.

**Comment by laurencei** [comment]
@Garbee - the internals issue link I post; yes.

But the other two links talk about the _exact issue_ EmilMoe is discussing for cookie names. One is from 2010. One is from me in 2012.

Seems like the issue is clearly there somewhere.

**Comment by laurencei** [comment]
Given this issue has been blogged about as early as 2010 - but only seems to affect a small subset of installations (otherwise it'll be a bigger issue) - then it is obviously a strange edge case that I doubt we are going to solve on this thread.

It is not directly related to Laravel (since it has been reported in Codeigniter).

If the Edge/IE team want to look into it - sounds good. But simplest solutions seems to be remove the underscore and move on.

**Comment by EmilMoe** [comment]
Simplest solution is to remove it or default yes

**Comment by laurencei** [comment]
Ok - PR done. 

I think we can close this issue now (regardless if the PR is accepted or not) - since we are not realistically going to get any further on this?

/shrug

**Comment by sisve** [comment]
So, did anyone take me up on the request for a minimal example application that has this issue? It wouldn't have to be much, just whatever page/controller you need to _easily_ show that sessions aren't working as they should.

It would be nice if we could get both the source code and have the application hosted publicly. Confirm that the issue exists on that publicly hosted application, and tell us which version of IE you are using.

You know, basic developer stuff for reproducing an issue...

**Comment by themsaid** [comment]
Quoting Taylor in https://github.com/laravel/laravel/pull/4217#issuecomment-293106431:

> this feels somewhat edge case and be changed at the app level. Lots of cookies have underscores.

imo this case is not a framework issue since it's clearly just another IE/Edge non-sense that people have to deal with if they want to support these browsers.

Closing this issue then.

**Comment by themsaid** [comment]
Thank you all for sharing your thoughts and knowledge :)

**Comment by EmilMoe** [comment]
@themsaid What you are saying is that Laravel doesn't support Edge and IE?

**Comment by Garbee** [comment]
@EmilMoe No it supports them just fine. However, this is not something that is a problem with Laravel's compatibility but instead IEs/Edge's compatibility with the web. As has been expressed repeatedly, this issue doesn't affect everyone using Laravel with these browsers (or we'd have numerous more reports) but something else is happening to cause the effect. Which we can't pinpoint since we don't have enough information.

Since there were numerous resources *claiming* Edge/IE have a problem in their handling of cookie names somehow (which again isn't affecting everyone) the team is looking into their code internally at Microsoft. If they find a problem, then they'll address it.

As it is, there is no **evidence** to support the theory that IE/Edge outright cannot handle the dash in the *cookie name*. All there is is theory and conjecture but no solid proof. Which the framework shouldn't act on every case of conjecture or there would  be an abundance of churn over various parts of the codebase.

**Comment by jdcrecur** [comment]
@EmilMoe @Garbee 

I don't think this issue should be closed. We just wasted a good few hours trying to fix issues we had with IE11 and logging in.

What would happen:
1 - Clear all cookies and history from IE11
2 - Load the app and login
3 - Great, all logged in, no problems there.
4 - Logout using a custom logout function that called auth logout.
4 - Try to log back in by posting the credentials again.
5 - Instead of being logged in, we instead saw a 302 redirect to the login page.

We could repeat this circle quite successfully. 

With a release deadline looming and the thought of overtime required to fix this mystrious problem we came upon this post from SO:  http://stackoverflow.com/questions/33240144/laravel-login-not-working-in-edge-and-internet-explorer/40814059#40814059

We removed the _ from the default cookie name and hey presto... it all worked 100% fine.

I cannot explain why removing the underscore fixed everything, but it did. The default name of the session cookie from PHP does not have an underscore, maybe for this very reason.

**Comment by laurencei** [comment]
@Garbee - was there any further activity on the IE internal mail lists? Do you have a link we can see for it?

**Comment by Garbee** [comment]
MS isn't exactly known for their transparency. All I know is, the team is looking into it internally. They'll follow up as needed publicly.

Sufficient to say though, unless someone can show a reproducible scenario this problem is difficult to track down. As it works for most people but some are clearly hitting some problem. However, we don't have any evidence publicly to prove the underscore is the root cause.

**Comment by jdcrecur** [comment]
It would be a responsible idea then to at least inform the users of Laravel about this issue. Either by covering it in config file in the note above where the value is set. Or by covering it within the online documentation.

**Comment by sisve** [comment]
@jdcrecur We've asked for a reproducible setup several times. Can you put one up that we can access with our own Internet Explorer installations, and also share the source code for it publicly? Perhaps a virtual machine with nginx+laravel so that we can run it locally?

I have been using Laravel for some time now, and test it with all^H^H sane versions of IE (IE8+) without seeing this issue, and I am using the default cookie name which includes an underline character.

Internet Explorer has many things that may interfere with your day-to-day happiness, including different security zones (local intranet, trusted sites, internet, restricted, ...), p3p policies and quirks mode. There are many ways for Internet Explorer to decide that you are not worthy of it, and so far we've not been given enough information to reproduce the problem or pinpoint the issue.

**Comment by jdcrecur** [comment]
Sure, but will have to be this evening ;). Will post a simple replication of the build that failed yesterday.

The version of IE I have installed (default from win10 install) is: 11.162.10586.0

**Comment by jdcrecur** [comment]
https://github.com/jdcrecur/laravel-cookie-monsters

On this current machine i have a new version of internet explorer than the one quoted above and the session cookie with underscore appears be functioning ok with the above stripped out app. But the linked repo is a clone of the app in question, so same composer file. 

The app i found the issue with was originally built on 5.1 and migrated through the versions to 5.4 over a time period of about 7 months.
