### ISSUE TITLE
Illuminate\Contracts\Mail\Mailer contract is missing methods

### ISSUE THREAD

**Issue by Jalle19** [laravel/framework#18361]
- Laravel Version: 5.4.15
- PHP Version: 7.0.16

### Description:

The `Illuminate\Contracts\Mail\Mailer` contract doesn't have the `to()` method, so a class cannot depend on the contract without abusing the interface and calling `to()` anyway. It is also not possible to depend on an implementation like `Illuminate\Mail\Mailer` because `Illuminate\Support\Testing\Fakes\MailFake` is not compatible.

### Steps To Reproduce:

Inject `Illuminate\Contracts\Mail\Mailer` and try to do something useful with only the interface methods.

**Comment by Kyslik** [comment]
I just tried this (inject mail contract) and send an email using `...to('email@e.ee')->send(new Mailable...)` and I got mail in mailtrap.

I guess your IDE (as mine) simply does not show methods... you may either inject concrete and develop and after you done just inject contract... (this is bad way to go ofc, just a workaround).

What I am doing is using only `->send()` method and I let Mailable set `$to` and `$subject` itself (in `build()` method). Not sure if this is a way how to do it but it works and mail is "self contained".

---

To test mailables (without using facade) in case I have more dependencies and want to use resolve helper I extend class I am testing and inject MailFake instead of Mailer.

**Comment by Jalle19** [comment]
> I just tried this (inject mail contract) and send an email using ...to('email@e.ee')->send(new Mailable...) and I got mail in mailtrap.

It doesn't show the methods because they aren't technically there, they only appear during runtime because the actual implementations happen to have them.

I'll look into having the `Mailable` itself set addresses and the subject. It would be still be nice if the interface would cover all methods though.

**Comment by Kyslik** [comment]
People are doing some changes to Mail contract atm, they can not change it on current version, I am sure its going to be improved in 5.5.

**Comment by Jalle19** [comment]
Let's hope so. Currently Laravel is many times unusable without facades or without breaking contracts by silently relying on implementation-specific functionality.

**Comment by fernandobandeira** [comment]
Ping @themsaid this should be fixed on 5.5.

**Comment by themsaid** [comment]
yes, will do close to release to prevent complex conflicts.
