### ISSUE TITLE
[5.4] Envoy conflicting mapping variables

### ISSUE THREAD

**Issue by vrubiella** [laravel/framework#18464]
- Laravel Version: 5.4
- PHP Version: 7.1
- Envoy Version: 1.3

If you define a variable inside a task (foreach iterator for example), can't use the same variable on other tasks because it's emtpy (value not mapped)!

### Description:
```
@task('task1', ['on' => 'localhost'])
   @foreach(explode(' ',$domains) as $domain) -d {{$domain}} @endforeach
@endtask

@task('task2', ['on' => 'localhost'])
   echo "{{$domain}}"
@endtask
```

```bash
envoy run task2 --domain=hola.es
```

Task2 always print empty output.

**Comment by themsaid** [comment]
This is a limitation that you need to account for, the above code is compiled to:

```php
<?php $domain = isset($domain) ? $domain : null; ?>
<?php $domains = isset($domains) ? $domains : null; ?>
<?php $__container->startTask('task1'); ?>
<?php foreach(explode(' ',$domains) as $domain): ?>
    -d <?php echo $domain; ?>

<?php endforeach; ?>
<?php $__container->endTask(); ?>

<?php $__container->startTask('task2'); ?>
echo <?php echo $domain; ?>
<?php $__container->endTask(); ?>
```

As you can see the `$domain` variable is overridden in the foreach loop declaration.

**Comment by jhdxr** [comment]
Blade template has the same issue, so I set a rule, always using variable starting with underline inside a block, like `$_domain`,  for myself to avoid this issue.

Fixing this issue is not a difficult mission, but I doubt if this fix itself would be a huge BC break.

**Comment by vincemukiiri** [comment]
Any progress with this? I think one should be able to declare variables within tasks and have them behave as if within a local scope (like variables declared within functions). Like so:
```
@task('task-1')
    <?php $var = 99 ?>
    ...
@endtask

@task('task-2')
    echo {{$var}}
@endtask
```

If I run `envoy run task-2 --var=42` I feel it should output 42 but at the moment it outputs 99 because it is overriden in task-1 even though task-1 isn't run (as explained by @themsaid.)

Maybe we could have a special tag that we can put php code within tasks so that they're only run when the tasks are run. Something like
```
@task('task-1')
    @code
        <?php $var = 99 ?>
    @endcode
    ...
@endtask
```

**Comment by driesvints** [comment]
Can you open up an issue on the envoy repo is you're still experiencing this? https://github.com/laravel/envoy
