### ISSUE TITLE
It has Fatal Error for initial page

### ISSUE THREAD

**Issue by endlessdev** [laravel/framework#18532]
- Laravel Version: 5.4
- PHP Version: PHP7
- Database Driver & Version: MySQL 5.6

### Description:

I'm try to install lumen with composer and deploy my homestead
but it shown this error message 

<pre>
Fatal error: Declaration of Laravel\Lumen\Application::make($abstract) must be compatible with Illuminate\Contracts\Container\Container::make($abstract, array $parameters = Array) in /home/vagrant/Lux/vendor/laravel/lumen-framework/src/Application.php on line 21"
</pre>

### Steps To Reproduce:

1.Install Lumen with composer
<pre>
composer create-project --prefer-dist laravel/lumen <project-name>
</pre>

2.Connect homestead 

Set nginx setting, .env

3.Update and installing composer
<pre>
$ composer install
$ composer update
</pre>

**Comment by devcircus** [comment]
Probably should submit issue in [lumen-framework](https://github.com/laravel/lumen-framework), however, it seems your dependency versions are off. The signature for 'make' has been ```make($abstract)``` since 5.4.0. For some reason, you're pulling in 5.3. 

I just ran ```composer create-project --prefer-dist laravel/lumen``` and everything was correct. 
I would delete your vendor directory and composer.lock.  Then run composer install.

**Comment by endlessdev** [comment]
Sorry for my missing.
