### ISSUE TITLE
Unable to delete cookies via $controller->sendResponse();

### ISSUE THREAD

**Issue by jschlies** [laravel/framework#18833]
- Laravel Version: 5.4.19
- PHP Version:7.1
- Database Driver & Version: Mysql 5.6

In short, returning from Controller method:

        return $this->sendResponse([], 'Logout successfully')
                    ->withCookie(\Cookie::forever('CLIENT_ID_COOKIE', $CLIENT_ID))
                    ->withCookie(\Cookie::forget('XSRF-TOKEN'));

'XSRF-TOKEN is not deleted

while 

        \Cookie::queue(
            \Cookie::forget('XSRF-TOKEN')
        );
        return $this->sendResponse([], 'Logout successfully')
                    ->withCookie(\Cookie::forever('CLIENT_ID_COOKIE', $CLIENT_ID));

works fine

**Comment by Aven30** [comment]
The issue seems to be that Laravel add the XSRF cookie to the response. Thus, it looks as if it never got deleted but technically, it did. It's just that it creates another one afterwards.

And as for why the second example works, it's most likely because the queue is dealt with after the XSRF token has been added to the response.
