### ISSUE TITLE
Console  Schedule call does not call before()

### ISSUE THREAD

**Issue by codepilotde** [laravel/framework#18851]
- Laravel Version: 5.3.9
- PHP Version: 7.0.11

### Steps To Reproduce:

Create a simple call schedule with on callBackfunction and 
a before() and after call(). In my example the before method dd('before') the after dd('after).
```
    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->call(function() {
            echo "this is the output of the cron".PHP_EOL;
        })->everyMinute()
            ->before(function () {
               echo("before").PHP_EOL;
            })
            ->after(function () {
              echo("after").PHP_EOL;
            })->sendOutputTo("/tmp/test.txt")
            ->emailOutputTo('yourmail@yourdomain.de');
    }

```
I chose a minutely interval so you can easily run 
`
php artisan schedule:run 
`

The expected behavior and output should be 

```
Running scheduled command: Closure
before
this is the output of the cron
after
```

**Comment by jhoff** [comment]
Tested this locally and it seems to be isolated to closure based commands:

This does not echo "before"
```
$schedule->call(function() {
    echo "this is the output of the cron".PHP_EOL;
})
->everyMinute()
->before(function () {
    echo("before").PHP_EOL;
});
```

However, this does output "before", as expected:
```
$schedule->command('inspire')
->everyMinute()
->before(function () {
    echo("before").PHP_EOL;
});
```

**Comment by jhoff** [comment]
With a command based scheduling event, by default will "run in the foreground", which means it will wait for the command to finish, so both the before and after callbacks will be executed. If you add `->runInBackground()` then it will start the command and then release the process and finish immedately, so only the before callbacks will be run.

However, in this case, with a closure based event, it may be intentional that the before callback is never called. I suppose the thought process might be that the code to be exectuted is already right there... why not just put it there. Example:

```
$schedule->call(function() {
    echo("before").PHP_EOL;
    echo "this is functionally the same".PHP_EOL;
})
->everyMinute();
```

It'd be easy enough to add `parent::callBeforeCallbacks($container);` to [Illuminate\Console\Scheduling\CallbackEvent::run()](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Scheduling/CallbackEvent.php#L56) and as far as I can tell shouldn't hurt anything.

**Comment by jhoff** [comment]
Submitted a pull request for 5.5 to fix this issue.

**Comment by codepilotde** [comment]
I agree with what you say. And I reproduced the same with call,command and exec exec as @jhoff wrote above. 

```
$schedule->call(function() {
    echo("before").PHP_EOL;
    echo "this is pretty much functionally the same".PHP_EOL;
})
->everyMinute();
```

Right from functional aspects, but what I wanted to do was to generalize some logging functionality for cronjobs with the before() and after() methods and to make it clean and pretty.
But so far I'll use a  work around with artisan functions for my jobs. And use a custom repo with the same  fix you provided above.

**Comment by themsaid** [comment]
Thank you for the report, moving the discussion to the opened PR https://github.com/laravel/framework/pull/18861
