### ISSUE TITLE
Empty string passes 'array' validation rule

### ISSUE THREAD

**Issue by refi93** [laravel/framework#18948]
- Laravel Version: 5.4.6
- PHP Version: 7.1.2

### Description:
The validation rule for an array allows for an empty string which seems weird to me, see the following example:

### Steps To Reproduce:
    $ php artisan tinker
    >>> (\Validator::make( ['field' => ""], ['field' => 'array'] ))->passes();
    => true

Tested with:

```
$ php artisan --version
Laravel Framework Lumen (5.4.6) (Laravel Components 5.4.*)
```

**Comment by marconi1992** [comment]
I think because laravel validation handle the `null, "", []` like empty values.
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/Validator.php#L334

 Therefore you should add the required rule to validate nullables values in the field, I'm don't sure if is a weird behavior or if is expected.

**Comment by refi93** [comment]
@marconi1992 yes, but is ` ""` a valid array? Because due to this behavior my application fails when I pass that field to a function that expects an array.

**Comment by refi93** [comment]
@marconi1992 ok, I see, that the isValidatable method prevents the empty string from being validated, but I find it quite weird, at least, it would be nice to warn the people in the documentation, because if this is the desired behavior, then I find the specification of the `array` rule stating that "The field under validation must be a PHP array." misleading.

**Comment by ConnorVG** [comment]
Maybe `isValidatable` should have a `strict` check option for `null`?

**Comment by trevorgehman** [comment]
It's been this way for a long time, that an empty string is not validated unless there is a `required` or similar rule on it.

This situation was changed somewhat by the `ConvertEmptyStringsToNull` middleware which was introduced in 5.4.  If you use that middleware, it avoids this headache/confusion, since an empty string will be converted to `null` and fail any validation check like `array`, `integer`, etc.

**Comment by ecrmnn** [comment]
For anyone coming here in the future, I had a similar problem and was able to solve it like this:

If ``replies`` was passed as an empy array ``[]`` I wanted it to fail validation.
By adding ``required`` on **both** ``replies`` and ``replies.*`` I was able to achieve this.

```php
[
    'replies' => [
        'required',
    ],
    'replies.*' => [
        'required',
    ],
]
```

⚠️ Caveat: this will be *two different kind* of errors depending on your data.
Either ``replies`` or ``replies.*`` will be in your error message bag.

**Comment by skillaug** [comment]
> 
> 
> It's been this way for a long time, that an empty string is not validated unless there is a `required` or similar rule on it.
> 
> This situation was changed somewhat by the `ConvertEmptyStringsToNull` middleware which was introduced in 5.4. If you use that middleware, it avoids this headache/confusion, since an empty string will be converted to `null` and fail any validation check like `array`, `integer`, etc.

enable ConvertEmptyStringsToNull middleware and it also fails on String, it's a bad solution for me, I can't save an empty string into string data

**Comment by onmigregor** [comment]
hi, I just need know if was fixed


I have an array, which can be
`array:3 [
  0 => "190"
  1 => "56"
  2 => "127"
  3 => "50"
]`

or 

`array:3 [
  0 => ""
  1 => ""
  2 => ""
  2 => ""
]`


But no this way
`array:3 [
  0 => ""
  1 => "56"
  2 => "20"
  2 => ""
]
`

I have been trying validator using validation combinations without success, does anyone know what is needed
