### ISSUE TITLE
hasArgument on Commands returns true instead of false

### ISSUE THREAD

**Issue by dnatabar** [laravel/framework#18963]
- Laravel Version: 5.4.19
- PHP Version: 5.6.15, 7.1.2
- Database Driver & Version:
MySQL 

### Description:
Calling hasArgument() on a command returns true, even if the argument is missing.
This obviously only happens for optional arguments.

### Steps To Reproduce:

Create fresh Laravel Project.
run ``php artisan make:command testCommand``
change signature of command to ``test:testCommand {argument1?} {argument2?}``
add command to Kernel.php
add code below to handle method.
```
        if ($this->hasArgument('argument1')) {
            echo "Hsa Argument1: " . $this->argument('argument1') . "\n";
        }
        if ($this->hasArgument('argument2')) {
            echo "Hsa Argument2: " . $this->argument('argument2') . "\n";
        }
```
Command: ``php artisan test:testCommand arg1 arg2``
Result:
```
Hsa Argument1: arg1
Hsa Argument2: arg2
```
Expected:
```
Hsa Argument1: arg1
Hsa Argument2: arg2
```

Command: ``php artisan test:testCommand arg1``
Result:
```
Hsa Argument1: arg1
Hsa Argument2:
```
Expected:
```
Hsa Argument1: arg1
```

Command: ``php artisan test:testCommand``
Result:
```
Hsa Argument1:
Hsa Argument2:
```
Expected:
```

```

**Comment by devcircus** [comment]
The 'hasArgument' method from Laravel's Command class,
```
    return $this->input->hasArgument($name);
```
defers to the Symfony\Component\Console\Input\Input class,
```
    return $this->definition->hasArgument($name);
```
which defers to the Symfony\Component\Console\Input\InputDefinition class, which checks to see if the argument is part of the InputDefinition
```
            $arguments = is_int($name) ? array_values($this->arguments) : $this->arguments;

            return isset($arguments[$name]);
```
Seems like 'hasArgument' just checks to see if the argument is defined for the Input Definition for the command, not whether or not it was actually included in the call.
Either way, since this is a symfony question, it might be best to ask on [their repo](https://github.com/symfony/symfony/issues)

**Comment by dnatabar** [comment]
I'l post it on The Symfony repo, thanks for the heads up =)

**Comment by rulatir** [comment]
@dnatabar If by chance you did post it on the Symfony repo, could you please link to that issue here?

**Comment by uuf6429** [comment]
The symfony documentation clearly states that it checks the definition:
> Returns true if an InputArgument object exists by name or position.

whereas the laravel documentation says otherwise:
> Determine if the given argument is present.

I'd say either the laravel code is wrong (considering the PHPDoc) or at least the documentation is wrong. There's nothing to ask on the symfony side...

**Comment by kirkbushell** [comment]
Went looking at the docs to see what I was doing wrong, this seems like a bug, surely?

If the option has not been provided, this should return false.

**Comment by kirkbushell** [comment]
> I'l post it on The Symfony repo, thanks for the heads up =)

@dnatabar Anything ever happen with this?

**Comment by uuf6429** [comment]
@kirkbushell it's more of a misunderstanding.

Anyway, you could also ask @themsaid why the ticket was closed without justification.

**Comment by kirkbushell** [comment]
@uuf6429 of how they function, yes - without a doubt, but that doesn't make it the right UX for the feature.

Working with them, I've had to set default values (false) for those I want to check, but because false values are strings and not actually booleans, it results in really bizarre, checks, like this:

```php
if ($this->getOption('option') !== 'false)) // do thing
```

It's just a weird API to work with. Imho, if the option has not been provided, a boolean false value should be returned, not null, as null is also the value when the option IS provided without a value (which imho, is correct).

**Comment by sundayz** [comment]
strange that `hasOption` returns true for an option that was not provided, is it possible that it gets replaced with a default value like null somewhere along the line and that's considered as being "present" now? I ended up just checking if option() returns null in my command

**Comment by kirkbushell** [comment]
> strange that `hasOption` returns true for an option that was not provided, is it possible that it gets replaced with a default value like null somewhere along the line and that's considered as being "present" now? I ended up just checking if option() returns null in my command

It's almost like the hasOption check simply checks whether or not such an option is defined as part of the command, which is again, an odd UX outcome.
