### ISSUE TITLE
map-function modifies objects inside collection?

### ISSUE THREAD

**Issue by SahinU88** [laravel/framework#19105]
- Laravel Version: 5.4.20
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I noticed, that if you have Objects inside a collection and you call the `map` function, the objects itself are modified. Is that by purpose or a little bug? See the following code sample in the next section.

### Steps To Reproduce:
```
$a0 = new stdClass();
$a1 = new stdClass();
$a2 = new stdClass();
    
$a0->name = 'a0';
$a1->name = 'a1';
$a2->name = 'a2';
    
$a = [ $a0, $a1, $a2 ];
    
dump( $a );
collect( $a )->map( function( $i ){
    $i->name_foo = 'foo';
});
dump( $a );
```

**Comment by thecrypticace** [comment]
This is intentional. Furthermore, it's not fixable because PHP. Objects are passed by-reference in PHP which means that any variable pointing to an object and modify that object. If the object has value semantics (read: has been set up to prevent modifications from the outside) the modifications shouldn't have any effect.

**Comment by SahinU88** [comment]
oh yeah, makes sense. Just got a little confused when I noticed it, because the documentation says, that it returns a new collection and the original one is not modified. But I also think, that the code sample is kind of a "bypass" and not the right way to use the `map` function.

thanks for the quick reply!
