### ISSUE TITLE
Foundation package depends on an "Auth" package

### ISSUE THREAD

**Issue by daftspunk** [laravel/framework#19164]
- Laravel Version: 5.5@dev
- PHP Version: 7
- Database Driver & Version: N/A

### Description:

*Foundation package appears to depend on having an Auth package*.

This is more a line of inquiry than anything else, should there be an `if (class_exists('Auth'))` expression in here to decouple them?

Reference code:
https://github.com/laravel/framework/blob/841b36cc005ee5c400f1276175db9e2692d1e167/src/Illuminate/Foundation/Exceptions/Handler.php#L130-L133

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo or use the forums / slack channel to solve your issue

**Comment by daftspunk** [comment]
> This is not a bug.

@Dylan-DPC, replication instructions:

1. Remove the [Auth provider](https://github.com/laravel/laravel/blob/323e553f336b7e7b189a27fba4102a3c3851ee1b/config/app.php#L143)
2. Throw an exception
3. Class "auth" is not registered

**Comment by crynobone** [comment]
> should there be an if (class_exists('Auth')) expression in here to decouple them?

If you're loading `laravel/framework`, `Auth` class does exist. You should check if `App::bound('auth')` etc.

**Comment by daftspunk** [comment]
@themsaid? Should this be a pull request?

**Comment by themsaid** [comment]
I don't see a scenario where you need to load Foundation without the framework, and if you have the framework then `Auth` is there already.

**Comment by daftspunk** [comment]
This is to use the framework without loading Auth, currently not possible as it is coupled to the Foundation exception handler.

**Comment by themsaid** [comment]
I don't think it's possible to use the whole Framework except for a specific component, I understand though using different components together.

**Comment by LukeTowers** [comment]
This is a bug, or at least a poorly thought through feature. It was only added last month by Taylor: https://github.com/laravel/framework/commit/23b7d6b45c675bcd93e9f1fb9cd33e71779142c6. 

This is meant to add context to logs for easier searching through them; which is all well and good, but not the way it's currently implemented. I suggest that it would be better to fire an event here or something similar to allow applications to define their own context information that they would like to add to the logs instead of just assuming that the information provided by the Auth package is useful. Several applications may not use the Auth package at all, and other applications may have other information that is more useful to provide as context in the logs than the theoretical user ID and email.
