### ISSUE TITLE
Wrong COM_STMT_PREPARE response size. Received 7.

### ISSUE THREAD

**Issue by nazmulcse** [laravel/framework#19183]
- Laravel Version: #.#.#
- PHP Version: 7.0
- Database Driver & Version: MariaDB & 10.1.20-MariaDB - MariaDB Server
- Laravel 5.2
### Description:
I have a blog that is developed using laravel. In my local pc everything is ok. But when I upload it in live shared hosting server it throws error like below

   ```
 ErrorException in MySqlConnector.php line 124:
    Wrong COM_STMT_PREPARE response size. Received 7
```

**Comment by sisve** [comment]
This looks like an issue with using mysqlnd instead of libmysql.

> In general mysqlnd is more verbose than libmysql when it comes to low-level network errors and protocol parsing problems. We need those warnings as an aid to detect MySQL client server protocol differences between different MySQL versions. [...] Examples of warnings that may come whenever the client communicates with MySQL:
> * Wrong COM_STMT_PREPARE response size. Received n
>
> I suggest users shall report those warnings on bugs.php.net together with the MySQL server version, the PHP version and - important - a reproducible short (<20 lines) script.

Source: https://wiki.php.net/doc/todo/mysqlnd_vs_libmysql

**Comment by themsaid** [comment]
Please ask on the forums.

**Comment by bedo89** [comment]
After researching everywhere I came to conclusion that the problem is in the database engine of the shared hosting, maybe a permission or something, so the solution I found was to create the database in a separate service. I used sql9.freemysqlhosting.net and is working fine so far.
This text above is copied but i tried it, and it works successfully
