### ISSUE TITLE
Password reset form has no flood protection

### ISSUE THREAD

**Issue by xel1045** [laravel/framework#19238]
- Laravel Version: 5.4.22
- PHP Version: any
- Database Driver & Version: any

### Description:
Currently, a user can request a password reset an infinite amount of time. Thus, a user can exhaust system resources or could potentially flag a server as spam.

### Steps To Reproduce:
Request a password reset N times and N emails will be sent.

### Proposed solution
Add a verification rule to check if a token was generated less that X minutes ago.

**Comment by ankurk91** [comment]
May be **throttle** the requests like on login form.

**Comment by ConnorVG** [comment]
This seems like it would make more sense to use a middleware honestly, rather than delegating to a new feature for something that is already an implemented functionality.

I guess this sort of an interesting topic in the sense that it would make sense to utilise the login throttling here but that doesn't necessarily solve the issue of token build up.
