### ISSUE TITLE
HTML entities in plain text notification

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#19290]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4

### Description:

I've got object names that contains single or double quotes that are being mentioned in notifications:

```php
$message = (new MailMessage)
    ->line('This line "contains" double quotes.')
```

The HTML source part of the notifications ends up containing **un-encoded** double quotes, however the plain-text part contains HTML entities:

```html
This line &quot;contains&quot; double quotes.
```

Which obviously shouldn't happen and doesn't read well.

I'm not sure if this a bug, or if I should just run `html_entity_decode()` in my `/markdown` templates.

**Comment by HashiDev** [comment]
After having done `php artisan vendor:publish --tag=laravel-notifications`
Your can go in `resources/views/vendor/notifications/email.blade.php` and edit `{{ $line }}` by this following syntax : `{!! $line !!}`, because the `{{ }}` statements are automatically sent through PHP's htmlspecialchars function to prevent XSS attacks.
