### ISSUE TITLE
[5.4] Non copiable ErrorExeption

### ISSUE THREAD

**Issue by eddilou** [laravel/framework#19438]
- Laravel Version: 5.4.24
- PHP Version: 5.6.30
- Database Driver & Version: libmysql - mysqlnd 5.0.11-dev - 20120503

**Description**:
After the version has been updated, the output of the errors has changed, everything is beautiful and good, but the problem is that the error in the gray background can not be copied, and if you look for a problem on the Internet, you need to type each time how to disable the prohibition on copying?

**Steps To Reproduce:**
Allow any error in the code to throw an exception

**Comment by thecrypticace** [comment]
This is related to Symfony's 3.3 release, not Laravel. When you ran composer update it also updated Symfony's Debug component to 3.3 which has these changes.

cc @javiereguiluz, @nicolas-grekas: This seems like a usability regression. I've frequently copied exception messages to search for them and it appears I'm not alone here. Was this change intentional?

**Comment by javiereguiluz** [comment]
@thecrypticace this was a bug. It's already fixed in https://github.com/symfony/symfony/pull/22968 and it will be part of the next Symfony 3.3.1 version. Thanks!

**Comment by thecrypticace** [comment]
Nice. Looked for a PR but didn't see one. Glad to see that it has been fixed. Thanks!
