### ISSUE TITLE
DatabaseMigrations is too slow for each test, how to fix ?

### ISSUE THREAD

**Issue by mg-freelancer** [laravel/framework#19824]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:

When I run phpunit testing it takes long time to complete process because of migrations and seed, so how to fix this problem ?

**Comment by RikSomers** [comment]
Instead of using DatabaseMigrations, migrate and seed your database before testing and use the `DatabaseTransactions` trait. This should speed it up a bit.

**Comment by mg-freelancer** [comment]
@RikSomers the migrations and seed commands are too slow

**Comment by jhoff** [comment]
Is your mysql database local or on a separate machine? Any reason you're using mysql for testing instead of sqlite in memory? Do you need database migrations on every test? Are you using them selectively? Are you doing more than just schema changes in your migrations ( like data updates / api calls to hydrate data / etc )?

Any additional information would be useful. Just saying it's slow doesn't really give us much to work with. Way too many variables.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.

**Comment by lucasroman** [comment]
> Instead of using DatabaseMigrations, migrate and seed your database before testing and use the `DatabaseTransactions` trait. This should speed it up a bit.

Thanks!. That's worked for me. You don't forget add:
`use Illuminate\Foundation\Testing\DatabaseTransactions;`
