### ISSUE TITLE
Testing a class with database call on __destruct() is causing errors after updating laravel.

### ISSUE THREAD

**Issue by luisguilhermemsalmeida** [laravel/framework#19897]
- Laravel Version: 5.4.28
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.18

### Description:
I have a buffer class I wanted to test that has a `Model::insert(array $values)` on the class `__destruct()` method. However after updating from Laravel v5.4.23 to v5.4.28 (and PHPUnit from 5.7.20 to 5.7.21), the tests were passing, but causing fatal errors after running.
(https://github.com/laravel/framework/issues/9733) I managed to "fix" it by removing the line 1124 (`$this->instances = [];`) on vendor/laravel/framework/src/Illuminate/Container/Container.php (\Illuminate\Container\Container)

The error is: 
`PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('config')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('config')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('config')
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('config')
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('config')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(256): Illuminate\Container\Container->offsetGet('config')
#6 /var/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(86):  in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
PHP Stack trace:
PHP   1. {main}() /var/www/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /var/www/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:186
`

### Steps To Reproduce:

It's very hard to reproduce that, but after including tests for a class with a database call on the __destruct() method (create a instance of that class on a test and let it pass, run that test with the current test suite) it started to fail. Running only that test will pass without problems.

I'm including a gist with a Class and Test Example https://gist.github.com/luisguilhermemsalmeida/f6391a58cbc71733382b214deddeec7e

**Comment by themsaid** [comment]
While the app is terminating after running a test all container instances are flushed, while your class is being destructed these instances won't be available.

**Comment by luisguilhermemsalmeida** [comment]
So you would advice not to use the __destruct() method like that? When I implemented it the first time I thought that it wouldn't be safe to leave responsibilities to the destruct method, but I wasn't sure at that time.

**Comment by themsaid** [comment]
You can use it but keep in mind that there's no guarantee that container instances will be available while running tests since they're flushed before the script dies (the time when __destruct is called).

**Comment by satyago** [comment]
@themsaid Hi, sorry to have to re-open this but has any discussion on the matter happened so far?

I'm having a slight issue with the lack of being able to clean up a multi-tenant application's TDD testing remains and have no clear answer in my head. Also, I haven't been able to do enough code diving to be able to propose a pull request, so trying my luck on here …

See, the way I create tenant databases for all my tests is with the test case's `setUp()` method, then performing the removal during `tearDown()`. But  whenever there's an error (during TDD or otherwise) the testing database remains.

The destructor would be the perfect place to handle clean up tasks of this and similar kind in general, but at that point (as you've stated it sone nicely above), there's no access to any of the Laravel specific features anymore.

I imagine it is not too often that someone depends on this, but it would make sense to support an option for these cases, I think …

I mean, unless there's an undocumented Laravel way to the PHP `register_shutdown_function`?
