### ISSUE TITLE
Mailable->hasFrom doesn't work.

### ISSUE THREAD

**Issue by gumplei** [laravel/framework#20056]
- Laravel Version: 5.4.28
- PHP Version: 7.0.18
- Database Driver & Version: Mysql

### Description:
I set the sender in my mailable class, and I want to write a simple test to make sure the mail is sent by the correct sender. However, the Mailable->hasFrom always return false. and I dump the $mail in my test, the from property is empty.

### Steps To Reproduce:

```
<?php
// My mailable class
namespace App\Mail;

use Illuminate\Mail\Mailable;

class MyMail extends Mailable
{
    public function build()
    {
        return $this->from('mail@example.com')
            ->text('test mail');
    }
}
```

```
<?php
// My Test class
namespace Tests\Unit;

use App\Mail\MyMail;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class MyMailTest extends TestCase
{
    /** @test */
    public function the_email_with_correct_sender()
    {
        Mail::fake();
        $myMail = new MyMail();
        Mail::to('user@example.com')
            ->send($myMail);
        Mail::assertSent(MyMail::class, function ($mail) {
            return $mail->hasFrom('mail@example.com');
        });
    }
}
```

**Comment by nivanmorgan** [comment]
I'm running into the same issue. I post this about this a few days ago to. One of the contributers @themsaid just closed it because I had Laravel 5.3.31 installed and he said it wasn't supported and closed my thread. After that another developer posted that his wasn't working on 5.4 and I upgraded my framework to 5.4 and it still throws the exact same error. 

This is my post which shows the error I get.https://github.com/laravel/framework/issues/20059

**Comment by Douglasdc3** [comment]
I did some testing it happens because of the `build` method not being triggered when you use `MailFake` if you use the following code it would work this is not a fix of course...

```<?php
// My Test class
namespace Tests\Unit;

use App\Mail\MyMail;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class MyMailTest extends TestCase
{
    /** @test */
    public function the_email_with_correct_sender()
    {
        Mail::fake();
        $myMail = new MyMail();
        Mail::to('user@example.com')
            ->send($myMail);
        Mail::assertSent(MyMail::class, function ($mail) {
            $mail->build(); // <-- add this 
            return $mail->hasFrom('mail@example.com');
        });
    }
}
```

The code in the `MailFake` looks as follows

    /**
     * Send a new message using a view.
     *
     * @param  string|array  $view
     * @param  array  $data
     * @param  \Closure|string  $callback
     * @return void
     */
    public function send($view, array $data = [], $callback = null)
    {
        if (! $view instanceof Mailable) {
            return;
        }

        $this->mailables[] = $view;
    }

As you can see if you pass it a mailable it will just return and do nothing while the `Mailable` real method will call the `build` method.

**Comment by gumplei** [comment]
Thanks @Douglasdc3, my simple test pass after added $mail->build().

**Comment by wadleo** [comment]
Hello @nivanmorgan has your problem been solved by this?

**Comment by gumplei** [comment]
@wadleo The problem solved by @Douglasdc3 solution.

**Comment by wadleo** [comment]
Ok cool

**Comment by alexjoffroy** [comment]
Hi, I run into the same issue and @Douglasdc3's solution works.

But is there a good reason to include this directly in MailFake::send ?

```
/**
 * Send a new message using a view.
 *
 * @param  string|array  $view
 * @param  array  $data
 * @param  \Closure|string  $callback
 * @return void
 */
public function send($view, array $data = [], $callback = null)
{
    if (! $view instanceof Mailable) {
        return;
    }
    // Call build here fix the problem
    $this->mailables[] = $view->build();
}
```
