### ISSUE TITLE
Losing data when using Storage::append

### ISSUE THREAD

**Issue by oasmichael** [laravel/framework#20074]
- Laravel Version: 5.2 or higher
- PHP Version:5.6
- Database Driver & Version:

### Description:
10+ queue worker processes reading messages from queue and using Storage::append (driver:local) to store in one file,data will lose a lot and also it may cause memory exhausted when writing a big file.Please check!

**Comment by sisve** [comment]
Laravel 5.2 is no longer supported. With that said; are you talking about several workers appending to the same file? Have you implemented any locks at all?

The append method isn't atomic, it consists of a read and a write. It's fully possible for multiple parallell processes to read the same initial content, all append individual data, and the last writer that wrote last to the file will se the content persisted. (A writer will overwrite existing content, so the last one "wins".)

Ref: [FilesystemAdapter::append](https://github.com/laravel/framework/blob/f94fc026c64471ca5a5b42919c9b5795021d783c/src/Illuminate/Filesystem/FilesystemAdapter.php#L214-L221)

**Comment by farazirfan47** [comment]
I am having the same issue what should be the best solution for this ? anyone ?

**Comment by dyachkovD** [comment]
Laravel 5.6 have same issue

**Comment by sisve** [comment]
@dyachkovD It doesn't sounds like you have the same problem at all. Do you really have lots of processes writing to the same file?

**Comment by dyachkovD** [comment]
@sisve I have no parallel IO operations, but binary data becomes unreadable due to extra bytes and I losing my data too.

**Comment by kevariable** [comment]
Hi guys, perhaps this is the solution

```php
 // Consistency without losing data
 file_put_contents(
    $yourPath,
    $data,
    FILE_APPEND
);

// Consistency with overwrite data
Storage::append($yourPath, $data);
```

**Comment by code-creeper** [comment]
`Storage::append($filePath, $content);`

It appends the content but starts new line like:

`Storage::append($filePath, "Hello how");`
`Storage::append($filePath, "are you.");`

It will be like this:

Hello how
are you.

It will start appending content in the new line so that's why our file is corrupted.

It can be solved using NULL as separator:

`Storage::append($filePath, "Hello how", null);`
`Storage::append($filePath, "are you.", null);`

So it will write:

Hello how are you.

so your file will not be corrupted.

Note:

`Storage::append($filePath, $content);`

It Will download the stored content of the file, store it in the RAM, concatenate the new content with it, and then save it in the file, which exhausts my server RAM memory.
