### ISSUE TITLE
Schema name not always working properly for MSSQL

### ISSUE THREAD

**Issue by iamvitali** [laravel/framework#20231]
- Laravel Version: 5.4.28
- PHP Version: 7.0.20
- Database Driver & Version: Microsoft SQL Server 2016 (SP1-GDR) (KB3207512) - 13.0.4199.0 (X64)   Nov 18 2016 15:56:54   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

### Description:
Hi, this is a question/issue.
1. Question part: Is it possible to specify a schema name for the Schema Builder (specifically for migrations)? I know you can do Schema::connection('name'), and Schema::table('name') but there doesn't seem to be a ... Schema::schema('name')?
2. Issue: So I have tried to simply concat the schema name with a table name, using it like `Schema::create('schemaName.tableName')` and it works for `create`, but if try to do `Schema::dropIfExists('schemaName.tableName')` it doesn't delete the table. I did `DB::getQueryLog()` and it comes back with:
```
 "query" => "if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_N
AME = 'schemaName.tableName') drop table "schemaName"."tableName""
    "bindings" => []
    "time" => 52.01

```
So I assume the drop table part would have worked but in `INFORMATION_SCHEMA.TABLES` there is no `TABLE_NAME = 'schemaName.tableName'`, what it actually has in the DB is: `TABLE_SCHEMA = 'schemaName'` and `TABLE_NAME = 'tableName'`.

### Steps To Reproduce:
1. Create a schema in the MSSQL DB, say `schemaName`
2. Create a migrations file.
3. In `up()` add:
```
Schema::create('schemaName.tableName', function (Blueprint $table) {
            $table->increments('id');
            $table->string('test');
        });
```
3. In `down()` add:
```
    public function down()
    {
        Schema::dropIfExists('schemaName.tableName');
    }
```
4. Run `php artisan migrate`
5. Run `php artisan migrate:rollback`
6. It should create a table `tableName` in the `schemaName` schema BUT it won't delete it on the rollback.

**Comment by gmsantos** [comment]
Can you try to use only the table name on down?

```
    public function down()
    {
        Schema::dropIfExists('tableName');
    }
```

**Comment by iamvitali** [comment]
```
0 => array:3 [
    "query" => "if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_N
AME = 'tableName') drop table "tableName""

    "bindings" => []
    "time" => 75.01
  ]
```

It ignores the schema in this case.... :/

**Comment by themsaid** [comment]
@iamvitali I don't see multi-schema support in the current sql server schema builder implementation or query builder, I've never used MSSQL myself so if you're willing to add support for such thing please let me know.

**Comment by gmsantos** [comment]
@themsaid PostgreSQL works in [the same way](https://www.postgresql.org/docs/9.1/static/ddl-schemas.html) as SQL Server for schemas. 

Do you know if PostgreSQL schemas is handled by Laravel?

**Comment by themsaid** [comment]
@gmsantos yes they're handled but you have to configure the schema in your config.database file, you can't use it as per migration.

**Comment by gmsantos** [comment]
I think its valid to port the schema config as is in PostgreSQL to SQL Server and handle a dynamic schema by table in other PR.

I could tackle this port during this week @themsaid

**Comment by miscbits** [comment]
Hey. So for your second issue in the original post @iamvitali the reason why delete doesn't work is because `if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_N
AME = 'schemaName.tableName')` is false. schemaName.tableName won't be in the TABLE_NAME column. 

The Schema is stored in the SchemaName column so the query would have to be 

```
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_N
AME = 'tableName' and SCHEMA_NAME = 'schemaName') drop table "schemaName"."tableName"
```

@gmsantos if you want to implement this still, this is something you should be looking out for if you haven't discovered it already that is.

**Comment by gmsantos** [comment]
@miscbits thanks for the note. My idea is to use the same logic as PostgreSql schemas are handled by Laravel, so will be possible to define a custom schema for the whole application.

Its a first step before building a proper Schema handling, like define a schema by Model, Schema creating and drop via migrations. This next step will work for both PostgreSql and SQL Server.

**Comment by miscbits** [comment]
mhm. The issue with schema handling right now is that the search path is set in the grammar class which is in the connection class so to get the actual schema name you must run

`$schema->getConnection()->getDoctrineSchemaManager()->getSchemaSearchPaths();`

I might be wrong and there could be an easier way, but as far as I know this is the best way to get the schema in the Builder class. There is no $schema attribute in the  Builder class which is what the schema facade calls. the best you could do is get connection name then call `Config::get('database.connections.'.$schema->getConnectionName().'.schema')` but that wouldnt be usuable in the builder class. Only in the migration would that be useful at all. the underlying code wouldn't be able to do that or we couldnt really make a reasonable test for it (due to things like sqlite that dont have a schema)

actually the more I look at that the more refactoring it looks like it might take. good luck. I really think you have a lot of work to look forward too. I hope some of this is useful.

**Comment by themsaid** [comment]
Please feel free to submit a PR when you get a chance or move the discussion to https://github.com/laravel/internals repo.

**Comment by MoElkhateeb** [comment]
I'm looking for something like that, as you mentioned @gmsantos 
> My idea is to use the same logic as PostgreSql schemas are handled by Laravel, so will be possible to define a custom schema for the whole application.

Is there any way to set a specific schema name for the whole laravel app?

my case:
"I was asked to replace MariaDB with already existed MS Sql Server db which is already has it's own other database schemas and my new one will be alongside with those existed ones"

**Comment by miscbits** [comment]
@MoElkhateeb This thread is on a 5 year old version of Laravel so chances are your issue is not related to what's going on here. The issue in the original thread here is the behavior of migrations when we have a multi-schema application. As far as I can tell what you are trying to do is specify the schema in your database config file. Either edit this line or add DB_DATABASE to your environment. 

`'database' => env('DB_DATABASE', 'forge'),`
