### ISSUE TITLE
pluralizer adds s to data

### ISSUE THREAD

**Issue by jonnylink** [laravel/framework#20426]
- Laravel Version: 5.4.*
### Description:
Artisan wants to pluralize "data," despite it being in the pluralizer as uncountable. No such thing as "datas."

### Steps To Reproduce:
php artisan make:model MyData -mrc

**Comment by JeroenVanOort** [comment]
What would you want the pluralizer to do instead? Make the table name 'my_data' (thereby betraying it's own naming convention)? Refuse to create anything at all? And would there be any more cases where you wouldn't want the pluralizer to add the s?

As far as I am aware, the pluralizer deliberately only adds an s, because giving in to any exceptions to that simple rule would create a large amount of rules without ever being able to handle every possibility. If you can't do it good, better not to do it at all. And, specially when it's just a generator like this, I believe the responsibility to use good naming rests with the developer. I don't think 'MyData' is a good model name.

**Comment by jonnylink** [comment]
The pluralizer already has rules built in. The naming convention of frameworks like Laravel is predicated on the idea that naming should match linguistic conventions. That's why if you use `php artisan make:model MyChild -mrc` the table will be called "my_children" and *not* "my_childs." More to the point, data _already_ in the pluralizer as a non-count noun. For some reason that rule in the pluralizer isn't being honored though.

And yeah, obviously MyData isn't a good name for a model. That's what we call an example, my friend.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo
