### ISSUE TITLE
Api Resource whenLoaded not working for belongsTo relationships, only collections

### ISSUE THREAD

**Issue by ashgibson** [laravel/framework#21011]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
It appears that the whenLoaded only works on relationships that are oneToMany and not belongsTo, is this intended?

'status' => new StatusResource( $this->whenLoaded('status') )

**Comment by themsaid** [comment]
It works for belongsTo as well, make sure you eager loaded the status relationship on your model.

**Comment by ashgibson** [comment]
What if the relationship has loaded but it is empty. I get errors trying to access property of null object. For example:

Item
- id
- name
- status (Status)

Status
- id
- name

// StatusResource.php
function toArray() {

return [
'id' => $this->id,
'name' => $this->name
]
}

I get errors trying to access property of null object which makes sense.

If I put logic at the top of the toArray() to return null if $this->resource doesn't exist, it returns an empty array rather than a null object.

**Comment by themsaid** [comment]
As of 5.5.2 if a relationship is loaded and has value = null, `null` will be returned. Make sure your app is on latest laravel version.

**Comment by ashgibson** [comment]
It works, thanks.

**Comment by ragingdave** [comment]
Figured I would chime in here before creating a new ticket, but I'm on the latest 5.5.13 and experiencing this same issue.

For example:
User Model:
id
employee_id
...
relationship to Employee via belongsTo

Employee Model:
id
....

if I don't load the employee relation via eager or otherwise, I would expect that the employee key would be blank in this example Resource:

public function toArray($request)
{
...
'employee' => new EmployeeResource($this->whenLoaded('employee')),
...
}

However the EmployeeResource proceeds to try and process the employee resource as if it was there and had properties.
