### ISSUE TITLE
Attribute cast is ignored when setting attribute to NULL

### ISSUE THREAD

**Issue by AidasK** [laravel/framework#21123]
- Laravel Version: 5.5.2
- PHP Version: 7.1

### Description:
Attribute cast is ignored when setting attribute to NULL
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1059

### Steps To Reproduce:
```php
class Text extends Model 
{
    protected $table = 'text';

    protected $guarded = [];

    protected $casts = [
        'notes' => 'string',
    ];
}
$text = new Text();
$text->fill(['notes'=>null]); // Null should be casted to '' which is equal to default ''
$text->isDirty('notes');//true, should be false instead
```

**Comment by themsaid** [comment]
This is intended, null is returned as is, there's a difference between `""` and `null`.

**Comment by telkins** [comment]
Related: According to the PHP docs (http://php.net/manual/en/language.types.string.php#language.types.string.casting), "`NULL` is always converted to an empty string."

**Comment by telkins** [comment]
@themsaid FYI...I also just noticed the OP's issue was *assigning* `null`.

That's not my issue.

Rather, it's *reading* the attribute.  If the value of an attribute is `null`, but it's cast to `string`, then shouldn't one expect an empty string...?

**Comment by mfn** [comment]
`null` is treated as "not a value" and therefore a cast does apply.

If you need such behaviour, you can implement your own getter. The cast behaviour cannot be changed (it will break every other users code out there).

**Comment by telkins** [comment]
@mfn Hi, and thanks for the reply.

Yes, I understand the concept of `null` and I understand that Laravel's casting behavior doesn't cast a value if it's `null`.   I also understand that one can write accessors to cast attributes that have `null` values...which is what I've had to do.

I was writing to understand *why* the decision was made to do this.  I felt that the explanation given earlier was not sufficient, especially since the whole point of casting is to force a value to be a specific type, which often means changing from one type to a different type....and casting `null` to various types is often handled without issue and yields non-`null` values.

The Laravel documentation presents this functionality as a kind of convenience.  It likens it to how one would normally cast using "pure" PHP.  This is not the case, however, and the documentation doesn't make this clear.  It caught me by surprise because this was not the expected behavior, which is what led me to this issue....looking for an explanation as to why it was written this way in the first place.

Not particularly relevant, but since you brought it up...making changes that are not backward compatible is not the end of the world.  PHP has and will continue to do it.  Laravel has and will continue to do it.  It's normal.  (Please note, I'm not suggesting that any changes be made...except for the documentation.  I wouldn't be opposed to it, but without having a better understanding of the rationale behind the decision to implement it this way, I am wont to argue for it.)

So...perhaps you know why it was written this way...?  Perhaps you would agree that the documentation could make it clear that any attribute, regardless of type or cast, will return `null` if its underlying value is `null`...?

Again, thanks for your input....I hope you can better understand what I'm looking for now.  :-)

**Comment by ed-bbwmc** [comment]
Another problem is, if any of the nullable field is included in the casts it stops casting the other fields that are not null.

**Comment by NicoHood** [comment]
I'd expect that a `string` would always cast `null` to and empty string. The current behavior that `null` will be accepted sounds more like a nullable `?string` to me.
