### ISSUE TITLE
Why don't you remove the bundled frontend components?

### ISSUE THREAD

**Issue by smithyj** [laravel/framework#21239]
Why don't you remove the bundled frontend components?
I feel Laravel forced to bind the frontend Vue very stupid

**Comment by devcircus** [comment]
```php artisan preset none```
Boom no frontend

**Comment by overtrue** [comment]
![tenor](https://user-images.githubusercontent.com/1472352/30575816-e68ea514-9cc8-11e7-968a-d8ba4eb96ef4.gif)

**Comment by Dylan-DPC** [comment]
@smithyj This repo is for bug tracking. As pointed out earlier you can do so with `preset`. You can close the issue

**Comment by arfar-x** [comment]
Laravel is a fullstack framework. Since it provides feature-rich REST API development, it would be nice to allow Laravel to be fully headless without any frontend boiler-plate. Obviously, it would also optimize the application loading process as it doesn't have to load the entire views and template engine.
