### ISSUE TITLE
artisan queue restart does not restart the queue

### ISSUE THREAD

**Issue by concept-core** [laravel/framework#21251]
- Laravel Version: 5.4.36
- PHP Version: 7.0.20
- Database Driver & Version: MySQL 5.6.35

### Description:
We are using a `queue worker` to convert pdf files to a image which normally runs fine, but the moment we deploy our project and we need to restart the `queue worker` it doesn't work.

it does not restart the `queue worker` which means our `queue` is not being processed anymore.

We have looked through some of the issue's on github but we did not find any solution.

We managed to hardkill the `queue worker` process with the following command : `kill -9 {PID ID}` but this isn't iddeal.

### Steps To Reproduce:

1. Run one of the following commands : `ps aux | grep queue:work` (mac) or `ps faux | grep queue:work` (linux)
2. Make sure a queue worker is running : `artisan queue:work --deamon`.
3. Open a new terminal window and run the following command `artisan queue:restart`.
4. Check if the queue process is still active with one of the commands at ( point number 1 ).

**Comment by themsaid** [comment]
Can't replicate, calling `artisan queue:restart` kills the process if no jobs are running, if a job is running the process won't die unless the worker finishes whatever jobs its working on.

**Comment by sisve** [comment]
Your issue is unclear. Are you reporting that it doesn't start up again, or that it doesn't stop at all?

The name of `queue:restart` does indeed suggest an actual restart, but that isn't what it does. It only stops processing jobs, and expect a process manager like supervisor or systemd to start it again.

Internally `queue:restart` sets a flag in the cache that tells all workers that sees it to restart. This means that your workers need to use the cache that the artisan command is using. It also means that it will restart all workers that uses the same cache, in case of a shared redis/memcached setup and several workers.

The documentation under [Queues > Supervisor Configuration](https://laravel.com/docs/5.5/queues#supervisor-configuration) has an example setup.

**Comment by themsaid** [comment]
Given:

> We managed to hardkill the queue worker process with the following command : kill -9 {PID ID} but this isn't iddeal.

I assumed the issue is that it doesn't kill the worker process, and yes it won't if the process is busy.

**Comment by jafar690** [comment]
@wotta try changing the cache driver to redis
