### ISSUE TITLE
Error on refreshing a model called through pivot table: Call to undefined relationship [pivot] on model

### ISSUE THREAD

**Issue by MBeckers** [laravel/framework#21402]
- Laravel Version: 5.5.13
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7 

### Description:
After a model is loaded through a many-to-many relationship, the origin pivot is saved in the relations, with the key 'pivot'. When trying to refresh the model the following error is thrown
"Call to undefined relationship [pivot] on model"

This could be fixed in Illuminate\Database\Eloquent\Model.php by replacing Line 985 with:

```
$relations = array_keys($this->relations);
Arr::forget($relations, 'pivot);
$this->load(array_keys($relations));
```

### Steps To Reproduce:
```
Post.php:
<?php
public class Post extends Model
{
    public function comments() 
    {
        return $this->belongsToMany(Comment::class);
    }
}
?>


SomewhereElse.php:
<?php
...
$comment = $post->comments->first();
$comment->refresh(); // <-- Causing the error
?>
```

**Comment by AuditeMarlow** [comment]
Also experiencing this.
 * Laravel 5.5.3
 * PHP version 7.1.10
 * MariaDB 10.1.26

**Comment by AuditeMarlow** [comment]
I've managed to resolve the problem I had by instead of depending on `->refresh();` to reload my relations, I've just manually listed what relations I wanted loaded by using `->load([ ... ]);` on the model.

**Comment by IlCallo** [comment]
Laravel Version: 5.4.36
PHP Version: 7.1
Database Driver & Version: mysql 5.7

I got a similar problem.
While testing my model instance got updated on database but when using refresh in the test method to update the model and check if changed took effect, it didn't synchronized with the update I did on the controller.

After some debugging I guess the problem is that while refreshing, relations are loaded **before** synchronizing attributes. In my case this lead to use previous null value of BelongsTo relation local_key instead of using the new value which was actually present on the database.

Here is the method in which relations are loaded before refreshing attributes.
https://github.com/laravel/framework/blob/39a4b3276d059e65e3c10b35d8748c0f5e09683c/src/Illuminate/Database/Eloquent/Model.php#L975

Is there a reason I'm missing because relations are loaded before getting a fresh copy of the attributes from the database?

Of course if you call refresh() and subsequentially reload the relation you need, it works (also if you use fresh() method instead).

**Comment by themsaid** [comment]
PR submitted to https://github.com/laravel/framework/pull/21713
