### ISSUE TITLE
make:migration allowed to begin with numbers

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#21459]
- Laravel Version: 5.5
- PHP Version: 7.1

### Description:
When creating a migration it's possible to create one that starts with numbers which will break the Artisan migration commands because a class is created of the same name and classes cannot start with numbers:

### Steps To Reproduce:

`php artisan make:migration 404logs_table`

`php artisan migrate`

>  [Symfony\Component\Debug\Exception\FatalThrowableError]                                   
>   Parse error: syntax error, unexpected '404' (T_LNUMBER), expecting identifier (T_STRING)

### Solution:
It would be better if a check was done first and refused to create the migration if it started with a number:

I'm trying to figure out how to submit a pull request now, but it should be as simple as.

```php
if(preg_match('/^[0-9]+/', $name)) {
    $this->error('Migrations cannot start with a number.');
}
```

or 

```php
if(is_numeric($name[0])) {
    $this->error('Migrations cannot start with a number.');
}
```

**Comment by uber1337** [comment]
Hi, is this the correct way of doing it ? For example you can also make a migration with with special chars, like "$". Seems that there is more than fixing numeric classes. 
Also there the other features affected not only this one (i.e.: make:command).

From my opinion we should leave the current feature as it is in order to not complicate the code too much and if is really annoying this bug to find a better solution for treating all cases in all console commands that could generate it. 

What do you think about my suggestion ?
