### ISSUE TITLE
[Inquiry/Confirmation] required_if does not bail. Is it the right behaviour?

### ISSUE THREAD

**Issue by edsamonte** [laravel/framework#21631]
- Laravel Version: 5.5.14
- PHP Version: 7.1
- Database Driver & Version:

Running the following code snippet:
```php
try{
    Validator::validate([
        'user_type'  =>  'patient',
        'practitioner_license_number'   =>  null,
    ],[
        'user_type' =>  'required|in:patient,doctor',
        'practitioner_license_number'   =>  'required_if:user_type,doctor|string|min:6'
    ]);
}catch (\Illuminate\Validation\ValidationException $e){
    dd($e->errors());
}
```
... the output is 
```php
array:1 [
  "practitioner_license_number" => array:2 [
    0 => "The practitioner license number must be a string."
    1 => "The practitioner license number must be at least 6 characters."
  ]
]
```

Is this really the expected behaviour? By my understanding, `required_if` should bail since it is not failed but the succeeding rules should no long be executed. Am I right on this?

Browsers submits everything inside the form regardless if the fields are related to each other, so it is a valid concern to expect null values from the client.

**Comment by 36864** [comment]
This isn't the place for this type of questions. You should use the forums or slack channel.

required_if does not bail because, while a field may be optional in some cases, if it is present you'd still want to validate it.
Use nullable for optional fields.
`'practitioner_license_number'   =>  'required_if:user_type,doctor|nullable|string|min:6'`

**Comment by edsamonte** [comment]
@36864 that actually works. Thank you very much. I'll just close this issue.
