### ISSUE TITLE
Timestamps error when ->using('PivotModel')

### ISSUE THREAD

**Issue by projct1** [laravel/framework#21766]
- Laravel Version: 5.5.17

### Description:
```php
class Order extends Model
{
    public function sms()
    {
        return $this->belongsToMany('App\Sms')->using('App\OrderSms')->withTimestamps();
    }
}

class Sms extends Model
{
    public $timestamps = false;

    protected $fillable = ['subject', 'template'];
}

class OrderSms extends Pivot
{
    protected $table = 'order_sms';
}

App\Order::first()->sms()->attach($smsId, $pivotAttributes);
//or
OrderSms::create(array_merge([
    'order_id' => $this->order->id,
    'sms_id' => $this->order->status->sms_id,
], $pivotAttributes));
```
As result is `Call to a member function getUpdatedAtColumn() on null`

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by projct1** [comment]
But ist bug! Expected behaviour is updating timestamps on OrderSms table.

**Comment by projct1** [comment]
@themsaid I just cant store pivot record!

**Comment by zecipriano** [comment]
I also think this is a bug. @themsaid, please review.

The issue is that when you load a Pivot Model directly (like in the example above) the `$pivotParent` property is not set. 

Then, the `getCreatedAtColumn()` and `getUpdatedAtColumn()` functions fail because [they reference that `$pivotParent` property](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Relations/Pivot.php#L211).

A possible solution is to return the model own timestamps when no `$pivotParent` is set.
