### ISSUE TITLE
Http\Request validate() method declaration conflict with FormRequest validate()

### ISSUE THREAD

**Issue by lelu85** [laravel/framework#21838]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Now at Iluminate\Http\Request, there is a phpDoc describing validate function as:
- @method array validate(array $rules, array $messages = [], array $customAttributes = [])

This has a conflict at Iluminate\Foundation\Http\FormRequest as it extends from Iluminate\Http\Request and uses Iluminate\Validation\ValidatesWhenResolvedTrait where the method is defined as:
- @method void validate()

This leads to code analisys errors as super class definition conflics if you overwrite the validate method at your own FormRequests.

**Comment by themsaid** [comment]
what errors?

**Comment by lelu85** [comment]
I am not saying its an error, I am saying its a phpDoc collision that leads to lots of code warnings, and its quite an important warning check to disable if you are using PHPStorm or any IDE, or using PHP Code Sniffer and Mess Detector.

**Comment by Dylan-DPC** [comment]
Hi. This repo is for bug tracking. So if you have a proposal to impove this you can create an issue in laravel/internals repo.

**Comment by sisve** [comment]
The problem originates from https://github.com/laravel/framework/pull/20866 where the docblock was added, but this is for a macro'ed function from FoundationServiceProvider in https://github.com/laravel/framework/pull/19063. Either the validate method is on the Request object, since we have the ownership of both places, or it is FoundationServiceProvider.

The current solution, where it is in one place but slightly known to Request by a docblock, is weird.

**Comment by themsaid** [comment]
Feel free to open a PR and change the docblock or remove it.
