### ISSUE TITLE
Route::redirect('/old', route('namedRoute')) does not work.

### ISSUE THREAD

**Issue by adampatterson** [laravel/framework#21925]
- Laravel Version: 5.5.*
- PHP Version: 7.1.0 OSX

### Description:

I really like the new routes for views and redirects as I have a tone of them.

I know that the documentation says 'simple redirects' so maybe this is not a simple redirect.

But one thing I have noticed is that a named route that is a collection of old monthly promotions that redirects to a current promotion. For this to work I have a named route that I attach to the appropriate route path and then point it at a controller.

Using `Route::redirect` however does not work with named routes.

### Steps To Reproduce:

**Works**
```
Route::get('/old', function(){
    return redirect()->route('newNamedRoute');
});
```

**Works**
`Route::get('/old', 'HelperController@currentPromotion');`

**Does not work**
`Route::redirect('old', route('namedRoute'));`

**Comment by sisve** [comment]
Your routes.php files are processed and put into the RouteCollection. Those are just static php calls; `Route::get('/path', 'ExampleController@myAction')` means that you're calling the Route facade's get() method, and it will add a route with the path and the provided string.

`Route::redirect('old', route('namedRoute'));`, however, is different, because it calls `route('namedRoute')`  to resolve a route from your current routes, and then pass that value to Route::redirect. This is during the creation of all routes, so it's 1) weird and 2) possible that the route "namedRoute" isn't registered yet. There's also a possibility that other things Laravel needs to resolve routes aren't available this early in the application life cycle.

**Comment by themsaid** [comment]
Example for simple redirects from the docs: 

> Route::redirect('/here', '/there', 301);

**Comment by adampatterson** [comment]
@themsaid any plans for named route support? 

It makes managing a lot of redirects much easier.

**Comment by themsaid** [comment]
@adampatterson well I think it's cool but not sure if Taylor would think the same since it's already pretty simple to just do that in a controller method, the helper aims to make a single case easy, not sure if supporting named routes would be easy specially that the router registerer won't be done reading all routes at this point.

**Comment by adampatterson** [comment]
@themsaid Yea, I had a look and redirect calls any() but the action is hardcoded to `\Illuminate\Routing\RedirectController`.
