### ISSUE TITLE
Echo .listen not working with default event class name

### ISSUE THREAD

**Issue by projct1** [laravel/framework#22313]
- Laravel Version: 5.4.21

### Description:
Try to broadcast event `broadcast(new CallOrderCreated(Order::first()));`
```php
class CallOrderCreated implements ShouldBroadcastNow
{
    public $order;

    public function __construct(Order $order)
    {
        $this->order = $order;
    }

    public function broadcastOn()
    {
        return new PrivateChannel('calltouch');
    }
}
```
Previously subscribing on this:
```javascript
Echo.private('calltouch').listen('CallOrderCreated', response => {
    console.log(response);
});
```
This not working (console is empty), although docs https://laravel.com/docs/5.5/broadcasting#defining-broadcast-events says:
> By default, Laravel will broadcast the event using the event's class name.

Authorization on private channel passes good.

But if i add method `broadcastAs` in my event class:
```php
public function broadcastAs()
{
    return 'call.order.created';
}
```
And subscribe `.listen('.call.order.created',`, its work.

**Comment by sisve** [comment]
The event's class name would also include the namespace. Try listening for it on `'App\\Zomg\\Something\\CallOrderCreated'` instead.

If this doesn't help and the problem really is in Laravel Echo, file the issue at https://github.com/laravel/echo

**Comment by projct1** [comment]
Yea, i tried this. I will duplicate this issue, thanks.

**Comment by themsaid** [comment]
Closing for the sake of https://github.com/laravel/echo/issues/156

**Comment by Chris25602** [comment]
So after perusing the various threads I think this is the right place to report this. I experienced this exact issue. I could even see the websocket traffic in dev tools flowing into the page however I couldn't use the data because the the listen closure was not executing on the event. this was a simple fix once I discovered it but, it is not listed in the official laravel broadcasting docs...tldr;

` <script type="text/javascript" src="http://xxxxxhostxxxxx::6001/socket.io/socket.io.js"></script>`

without this include the listen function cannot store your callback for socketio to execute on the event.
