### ISSUE TITLE
Disabling caching for Jobs and Controller

### ISSUE THREAD

**Issue by Modelizer** [laravel/framework#22356]
- Laravel Version: 5.3.31
- PHP Version: 7.0.21
- Database Driver & Version: MySQL

After upgrading to Laravel 5.3 we saw controllers are been cached and it is hampering our multi-tenant architecture.

1. Setup laravel and create multiple connections.
2. There must be at least 2 host example `a.example.com` and `b.example.com`
2. Inject those models in controller.
3. Insert test data from both the hosts.

Notes: We don't want to disable entire caching mechanism we just want to disable jobs and controller.

Thanks

**Comment by sisve** [comment]
> ... controllers are been cached ...

Could you clarify this? What type of caching are you trying to avoid?

> Inject those models in controller.

Which models?

> Insert test data from both the hosts.

What test data?

Your issue isn't clear on the actual problem. What are you seeing that you would like to stop seeing?

Also, Laravel 5.3 are no longer supported. Upgrade to Laravel 5.5.

**Comment by Modelizer** [comment]
1. Laravel default caching.
2. By default we have User module we can create multiple user from multiple hosts (Point the same host on different domain example).
```
127.0.0.1 a.example.com
127.0.0.1 b.example.com
```
3. Create LogRegistry class which will be load different configuration depending on host..

Here Laravel Cache Controller which is depended on LogRegistry and not loading config file. This is creating a whole mess..

**Comment by sisve** [comment]
There is no "default caching". There are only built-in cache drivers that you're calling yourself, and it is your responsibility to call it correctly. Can you show the code that isn't loading the correct config file?

**Comment by Modelizer** [comment]
Default caching is array. Laravel take care of caching file default. There is no intervention of my responsibility.

It is simple Laravel is caching controller and it is affecting in multi-tenant environment. We should have functionality to disable or controller it.

1 repository but multiple databases and domain.

**Comment by sisve** [comment]
I have no idea what you're saying. Can you give us some code that explains the problem? Are you saying that two different http requests has the same cache, even when you're using the array cache driver?

**Comment by deleugpn** [comment]
I work mainly with multi-database multi-tenant application, I've written two articles on the matter and I honestly cannot understand what is going on here.

**Comment by ersoy-insider** [comment]
Hi all;

Let me explain the situation in details. We have more than 500+ customer databases and one main database to rule them all. we get the customer name from subdomain;  **customera.client.example.com** and refresh our database connection -> because laravel already bootstrap database connection with default values.

Models are injected into repositories 
Repositories are injected into controllers

In one of our repository constructor we are initializing one of our models to get log types. (attached the screenshot below) - this model is in every partner database. 

![screenshot at dec 11 15-42-02](https://user-images.githubusercontent.com/17027410/33831629-e07f38f2-de89-11e7-9423-2cc6e8a44d2a.png)

so this method is called in the constructor of one of our repositories. We inject this repository into constructor of our controller. So whenever a framework boots itself, this repository also initialized. Which means that it's constructor initialized. which also means that the methods called in the constructor initialized (setLogTypes() method in that case)

Here is the problem; laravel bootstraps with default connection and it gets the logTypes of default customer database (Because i injected repository in the controller constructor) instead of refreshed customer database connection.

To prevent this what i did is; i injected the repository into method of controller instead of constructor of controller. Even controllers are booted (which means their constructors) the methods in the controllers are not booted.

Is there any other solution to prevent this ?

Thanks all @sisve @deleugpn

**Comment by deleugpn** [comment]
To me it doesn't make sense what you're saying. The flow is: 

```
index.php -> Service Providers -> Routes -> Middleware -> Controllers
```

By the time Laravel instantiate your Controller (and consequently your Repository and your Model), it already went through all of the previous steps. If you're changing the database setup in the Middleware or in the Routes, you should be set to go in the Controller, regardless if it's the constructor or a specific method.
If you're trying to setup the tenant database connection during Service Provider, that could be an issue since Eloquent is not ready yet in that stage.
Anyway, it would be more productive if you could install a fresh Laravel project and come up with the minimum necessary files in order to reproduce your issue. Chances are you're either going to find your issue yourself or you're going to be able to reproduce an actual Laravel bug or limitation. From that point we may be able to help you.
As a side note, what I can offer is the solution I work with: I have a `master` database connection and a `tenant` one. The `master` connects to the one-db-to-rule-them-all and the `tenant` is a null connection that doesn't work. In a middleware, I can recognize which tenant is responsible for the request, connect to the master database, grab the credentials for the tenant-specific database and configure the `tenant` connection. Tables in the `master` database have their model with `$connection = 'master';` and tables in the tenant-specific database have their models with `$connection = 'tenant';`.

**Comment by Modelizer** [comment]
@deleugpn for me your side note does not make sense.
1. You are always connect to master and then connect to tenant which will end up in performance compromise.
2. Have you thought about what will happen if your master database get hacked? Hacker can connect to any database easily and on system which we are working on will take weeks to reset database credentials.

All I want to say now is I don't see community is open for help or suggestions with respecting other views and opinion. Thank you for your time.
