### ISSUE TITLE
Bootstrap normalize from box problem.

### ISSUE THREAD

**Issue by berpcor** [laravel/framework#22376]
My story is... I wrote complex responsive html-code using latest version (4 beta) of twitter bootstrap. After all I started ios safari, ios chrome, mac os safari and found out problems I didn't see in other browsers. I started to dig deeper, and found out that problem comes from Laravel installation. I am using cdn version of bootstrap, I repeat latest version. In laravel app.css you have normalize bootstrap code.  And I didn't see for some reasons from the very beginning. Yes, my fault. But why did you include this old code to the app.css? You don't use any js for bootstrap but use css. Where is logic? It is should not be part of framework. Actual version of normalize is 7, but you use 3. Guys, strange thing.  You created a big problem for me.

**Comment by sisve** [comment]
It sounds like your problem is with https://github.com/laravel/laravel/ and not this repository. It also sounds like you're asking why laravel/laravel isn't using a beta non-stable version of Bootstrap. And then you go on a story about normalize and javascript and versions. It doesn't make sense.

Close this issue, and open one at https://github.com/laravel/laravel/. Make sure you include links to the files you have questions about, because as I understand it, there's no normalize going on in https://github.com/laravel/laravel/blob/master/resources/assets/sass/app.scss

**Comment by berpcor** [comment]
Ok, I'll close, but how to create issue at https://github.com/laravel/laravel/, there is no such possibility?.. 
I used **composer create-project laravel/laravel** and I've got this - https://github.com/laravel/laravel/blob/master/public/css/app.css.
I knew that somebody'll say that - "why laravel/laravel isn't using a beta non-stable version of Bootstrap". My bad, I didn't explain my point view exactly.
Thing you are talking about is not the point. I mean that you are not expect to get some version of bootstrap (as it is optional feature and not backend thing) when you install php framework.

**Comment by sisve** [comment]
Ah. That is the generated css from https://github.com/laravel/laravel/blob/master/resources/assets/sass/app.scss. The structure of the output indicates that it is indeed bootstrap-sass that is using normalize v3. This can be verified by looking in the sourcecode of the bootstrap-sass project; https://github.com/twbs/bootstrap-sass/blob/3.3-stable/assets/stylesheets/bootstrap/_normalize.scss

If you have any question about the version of normalize.css, ask them.
