### ISSUE TITLE
Dates stored as YmdHis are interpreted as timestamps

### ISSUE THREAD

**Issue by carestad** [laravel/framework#22385]
- Laravel Version: 5.5.23
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.1/PDO

### Description:

A legacy table I have stores dates in a varchar(20) column as YmdHis. In `Database/Eloquent/Concerns/HasAttributes.php` and in the function `asDateTime()`, there is a `is_numeric()` check on `$value`. If `$value` is a string containing only numbers it returns true and Laravel assumes this is a timestamp and creates a new Carbon instance via `::createFromTimestamp()`.

### Steps To Reproduce:

```php
class Foo extends Model {
  const CREATED_AT = 'createdDate';
  const UPDATED_AT = 'updatedDate';

  protected $dateFormat = 'YmdHis';
  protected $table = 'foo';
  protected $fillable = ['*'];
}

Foo::create(['id' => 1, 'name' => 'fooooo']);
dd(Foo::select('id', 'createdDate')->find(1));
```

**Comment by themsaid** [comment]
`asDateTime()` only runs when you explicitly say this attribute is a date, here you use `CREATED_AT` and `UPDATED_AT` which is translated by eloquent as dates.

**Comment by carestad** [comment]
Well if it is not `asDateTime()` that is causing this then some other method is interpreting it wrong.

If I fetch the `createdDate` column while `$timestamps = true`:

```json
{
  "id": 1,
  "createdDate": 6411700327231724
}
```

When setting `$timestamps = false`:

```json
{
  "id": 1,
  "createdDate": 20171211142644
}
```

Wouldn't you say that this is a somewhat unexpected behavior when I have set `$dateFormat = 'YmdHis';` and the dates are actually stored in this format, just not displayed correctly?

**Comment by 36864** [comment]
How can this be fixed?

If we try to parse the date using the defined dateformat before checking for a timestamp value, a date format of "YmdH" would, for example, take a current timestamp and produce a valid date which would be radically different from the date the timestamp represents.
I don't see a way to make the function continue working with timestamps and still accept entirely numeric formats.

**Comment by themsaid** [comment]
Isn't this your created_at and updated_at fields? so they're dates right? why don't you want them to be used as dates?

**Comment by 36864** [comment]
@themsaid They are dates, but the format is "YmdHis" instead of something sensible like "Y-m-d H:i:s". The whole problem here is that they are being used as dates, and as the date is saved as a numeric string, the framework decides it's a timestamp and tries to parse it as a timestamp instead of a string with the "YmdHis" format.

**Comment by themsaid** [comment]
I see, seems like that's the current behaviour and can't be changed in 5.5 since it'd be breaking, what do you suggest?

**Comment by 36864** [comment]
Maybe we could check the defined dateformat, and if it consists entirely of alphanumeric characters, try to create from that format before falling back to timestamp?

**Comment by themsaid** [comment]
I don't think it's easy to make such change without breaking, I suggest that you override this method in your Base Model and make it work for your own case.

**Comment by sisve** [comment]
Override asDateTime() in your models to remove the is_numeric check?

**Comment by 36864** [comment]
Please correct me if I'm wrong, but any date format that is only made up of letters ("ymd", "dmY", etc.) would be used with numeric datetime values ("171211" and "111217" in this example) which are valid timestamps. That means a simple regexp check on the date format would let us decide how to handle the date value.
If the change is made so that a model that defines a numeric date format parses dates using that format instead of as timestamps, then it would only break for someone who is storing the dates as timestamps but using a $dateFormat value that would simply be wrong for the existing data, is currently being ignored, and the developer saw that the dateformat was being ignored and just shrugged it off.

I'm not saying it's not a breaking change, but it should only break in quite specific cases where the feature is being misused. 

I would also understand if supporting numeric date types isn't a priority. Apparently they've never been supported, and frankly I'm a bit surprised that this is the first time I've seen the issue come up, but it does go to show that they're not that common (or anyone using them knows they're an edge case and probably handles it as @sisve suggested).

I'm not sure whether to call this a bugfix or a feature implementation.

**Comment by carestad** [comment]
I've tried @sisve's suggestion and added the following method to my model, and it is seemingly working okay:

```php
    protected function asDateTime($value)
    {
        if (is_numeric($value) && strlen($value) == 14) {
            return \Illuminate\Support\Carbon::createFromFormat(
                $this->getDateFormat(), $value
            );
        }

        return parent::asDateTime($value);
    }
```

Since this is the only model where dates are stored like this (luckily), I really don't mind the extra overriding method there.
