### ISSUE TITLE
Warning unlinking non-existent session file in tinker

### ISSUE THREAD

**Issue by phpguru** [laravel/framework#22514]
- Laravel Version: 5.5.27
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 5.6

### Description:
Minor issue. When using Auth::attempt( ) in tinker and using the Filesystem session driver, a PHP warning is displayed trying to unlink non-existent session file.

### Steps To Reproduce:
    # php artisan tinker
    Psy Shell v0.8.16 (PHP 7.1.11 — cli) by Justin Hileman
    >>> Auth::attempt(['email' => 'you@yoursite.com', 'password' => 'yourpassword'])
    PHP Warning: unlink(/Projects/myproject/storage/framework/sessions/yC9WluwkHxFwxkzIn2tLzBNo44FUCxn2HUSsno6d): No such file or directory in /Projects/myproject/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 183

Just need to check if `file_exists` or `is_file` before unlinking to avoid warning. The @ symbol in the [try-catch around lines 182-188](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/Filesystem.php#L182-L188) doesn't suppress the warning.

**Comment by sisve** [comment]
Why doesn't  `@` suppress the warning? Do you have screaming enabled in xdebug? Using file_exists/is_file is still susceptible for racing conditions where two parallel requests attempt to delete the same file.

**Comment by vicmarconi** [comment]
When using Auth::login(User::first()) (or any user), PHP warns about unlinking an non-existing file.
```
Auth::login($u)
PHP Warning:  unlink(/Workspace/Project/storage/framework/sessions/bxH9ZY08LSB61t8Mx2DjkF1Olj03Pn6aW20DDBiG): No such file or directory in /Workspace/Project/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 18
```

**Comment by mizan-cs** [comment]
same problem

**Comment by sisve** [comment]
@mizan-cs Are you using xdebug with screaming enabled? Check the `xdebug.scream` setting.

https://xdebug.org/docs/all_settings

**Comment by faozimipa** [comment]
is any body have a solusion to this problem?

**Comment by sisve** [comment]
There is no solution to the problem because no-one is bothered to answer that very simple and specific question; Do you have screaming enabled in xdebug?

> xdebug.scream
> Type: boolean, Default value: 0, Introduced in Xdebug >= 2.1
> If this setting is 1, then Xdebug will disable the @ (shut-up) operator so that notices, warnings and errors are no longer hidden.

You can find your setting in your configuration, or by doing `var_dump(ini_get('xdebug.scream'));`. Make sure you do it in the correct environment; preferably once in the terminal and once from a controller called via http, just to be sure that it's disabled in both.

@phpguru @vicmarconi @mizan-cs @faozimipa You're welcome to report your result in this issue. If you have screaming enabled, disable it. If you have screaming disabled, then there's an issue we need to debug further.

**Comment by Hacktivista** [comment]
I can confirm that screaming is disabled in my case
![image](https://user-images.githubusercontent.com/5282749/38872717-51d4ac90-422a-11e8-9667-c27dc8a92217.png)

**Comment by MarkVesterskov** [comment]
![skaermbillede 2018-05-31 kl 20 39 59](https://user-images.githubusercontent.com/7515900/40803717-9a083dda-6519-11e8-8e68-436b6af157ff.png)

Another buzz for this issue. 

It might be just a nuisance, but I have a slight hunch that it might be causing my queues to silently fail, because i have issues running them on my Homestead box whenever something session-touchy is involved. They get called but die silently.

Even tried updating php.ini's error_reporting to only E_ERROR on both FPM and CLI, to no avail.

**Comment by BautistaJB** [comment]
Same problem here, using PHP 7.0 and Laravel 5.4.

I realized this problem was in my project because the authentication stopped working when I installed the project in a new environment. Then I tried using Auth::attempt directly from php artisan tinker and saw the "unlink warning":

![image](https://user-images.githubusercontent.com/10666229/43119967-6077bdf6-8ecd-11e8-86bc-6e150947a643.png)

Just to be sure, I tried to fix it adding this lines where the error ocurrs (vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:183):

![image](https://user-images.githubusercontent.com/10666229/43120179-29ad0104-8ece-11e8-8b51-aca8cd528ea6.png)

Now the Warning is gone, but I cannot still log in my app.

**Comment by AristardusSkywatcher** [comment]
Same problem here with PHP 7.1.17 and Laravel 5.6.18.

I haven't enabled xdebug yet.

**Comment by martijnimhoff** [comment]
Also having this problem: php 7.2.15 and Laravel v5.6.39

**Comment by marcosdipaolo** [comment]
any solution?

not using xdebug here

**Comment by jeremiahsherrill** [comment]
also looking for a solution

**Comment by riyuk** [comment]
@sisve  @themsaid this error even occurs in **forge** - where no xdebug is present.

**Comment by riyuk** [comment]
You guys all use Honeybadger? Dunno if that produces the error in the Middleware `if (app()->bound('honeybadger') && $request->user()) {`

**Comment by marcosdipaolo** [comment]
What wa the answer to this problem?

**Comment by riyuk** [comment]
See my Ticket on honeybadger. This error is supressed by default (with a @). You will get errors anyway if you have defined a custom error reporter or use xdebug it seems.

**Comment by r9software** [comment]
I'm having the same error, but in live site, its preventing all my operations to work
