### ISSUE TITLE
laravel error when  integrate ckfinder

### ISSUE THREAD

**Issue by ckfindererror** [laravel/framework#22647]
When I integrate ckfinder there is an error
Symfony\Component\Debug\Exception\FatalThrowableError Call to undefined method Symfony\Component\HttpFoundation\Cookie::isRaw();

link image https://imgur.com/a/oxOa1

thank you so much!

**Comment by sisve** [comment]
The default issue report template asks for steps to reproduce. You have not provided any. We cannot even start to look into this without some idea on how to reproduce the problem.

It sounds like you're using symfony/http-foundation 3.0, which doesn't have Cookie::isRaw, but that wouldn't really be possible since laravel/framework requires a newer version of symfony/http-foundation.
