### ISSUE TITLE
 SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter    table `users` add unique `users_email_unique`(`email`)) In Connection.php line 458:   SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by evaldnadj** [laravel/framework#22660]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by m1guelpf** [comment]
@evaldnadj See [this Laravel News article](https://laravel-news.com/laravel-5-4-key-too-long-error) for a fix.

**Comment by devcircus** [comment]
Also in the [official documentation](https://laravel.com/docs/5.5/migrations#creating-indexes)

**Comment by sisve** [comment]
Keep in mind that those articles goes with the easy and wrong solution. It's like chopping of part of your foot because your socks doesn't fit.

The correct answer (to buy a new sock) is a bit more complex since it requires you to go to the store again. In this case it requires you to configure your mysql instance, and that isn't as copy/pastable as a wrong answer, so we keep propagating the wrong answer. We want to seem copy/pastable and easy to use, right?

You forgot to specify which Laravel or mysql version you are using. The problem occurs because you are using an older mysql (or newer with wrong settings).

1. Set [innodb_file_format](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_file_format)=Barracuda
2. Set [innodb_large_prefix](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix)=1
3. Set [innodb_default_row_format](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_default_row_format)=dynamic

If you do not have the innodb_default_row_format setting (introduced in 5.7.9), then you have to change your `config/database.php` to use `'engine' => 'innodb row_format=dynamic'`.

The engine setting was introduced in Laravel 5.2.14, so I hope you have something newer than that.

**Comment by abodehq** [comment]
# sdfsfsdds sdfdf

**Comment by sv7874** [comment]
Had simmilar issue.
Error was at:
CREATE INDEX path ON digital_object (path)

I already had  innodb_large_prefix set

Mysql manual says:
When this option is enabled, index key prefixes longer than 767 bytes (up to 3072 bytes) are allowed for InnoDB tables that use DYNAMIC or COMPRESSED row format.

What I did:
ALTER TABLE digital_object ROW_FORMAT=DYNAMIC;

After that, upgrade was succesful.

**Comment by jaymaggssa** [comment]
Hi 

Where do you get this config/database.php file in. mautic just not having any luck.

**Comment by ifranHugo** [comment]
> en que archivo se hacen esas configuraciones ALTER TABLE digital_object ROW_FORMAT=DYNAMIC;

**Comment by matteusbarbosa** [comment]
`ROW_FORMAT=DYNAMIC` did the trick for my sql dump file import. thanks guys!
