### ISSUE TITLE
resource controller can't get id

### ISSUE THREAD

**Issue by xhh110** [laravel/framework#23119]
- Laravel Version: #.#.# laravel 5.5
- PHP Version: 7.1.3
- Database Driver & Version: mysql

### Description:
resource controller 
if my uri is a group , such as 
```
Route::middleware ( [] )->prefix ( 'view/{name}' )->group ( function () {
    Route::resource ('content/teacher', 'TeacherController', ['names' => 'view.teacher']);
}

// url in blade
route('view.teacher', ['name' => 'test', 'id' => 1])

// the url in browser [view.teacher]
http://laravel.test/view/test/content/teacher/1

// show function 
public function show ($id)
{
    dd ($id);
}
// output is  "test"
```

**Comment by rs-sliske** [comment]
parameters in the controller methods are in order of the route wildcards

your first wildcard is name from the route group, so that gets passed as the first parameter

im not 100% sure if route model binding can get around this, but i would recommend taking all the parameters in your controller method, and using the same name as the wildcard

**Comment by xhh110** [comment]
@rs-sliske  i have a lot of user, In order to distinguish between them, they can only choose to use name，So the name prefix can't be removed

**Comment by xhh110** [comment]
@lancepioch it's solve.. thanks

**Comment by andileka** [comment]
how pleas help

**Comment by xhh110** [comment]
@andileka 
```
// show function 
public function show ($name, $id)
{
    dd ($name, $id);
}
```
