### ISSUE TITLE
Jobs not processed for first time in artisan tinker

### ISSUE THREAD

**Issue by vincemukiiri** [laravel/framework#23167]
- Laravel Version: 5.5.34
- PHP Version:  7.1.7

### Description:
When using artisan, the job doesn't dispatch the first time I call `TestJob::dispatch()` but does so in subsequent calls. This is the case for both the queue worker `php artisan queue:worker` and horizon `php artisan horizon`

### Steps To Reproduce:
Run `artisan tinker` and dispatch a job. The queue worker doesn't process it. If you try to dispatch the job again, it will be processed.

**Comment by vincemukiiri** [comment]
I found a similar issue in laravel/tinker#28 with the solution to instead run `Bus::dispatch(new TestJob())` or `Queue::push(new TestJob())`. As one of the users said, it would be nice to have a warning in the docs for queues.

**Comment by DragosMocrii** [comment]
The issue is that tinker will keep the generated `PendingDispatch` object in memory, to supposedly allow the user to use it in subsequent commands. The Job will be truly dispatched when that object is destroyed. https://github.com/laravel/tinker/issues/28#issuecomment-530473307 recommends to use `->__destruct()` on the returned object to force destroying the object and thus dispatch the job, however I noticed that would make the job dispatch twice for some reason.

My simple "solution" is to simply add another statement after the job dispatch, to force tinker destroy the PendingDispatch object:
`App\Jobs\MyJob::dispatch()->onConnection('redis');1;` , notice the `;1;` at the end

**Comment by shrimpwagon** [comment]
Oh my goodness... I lost a few hours because of this issue. I finally realized it was a Tinker issue. @DragosMocrii 's solution didn't seem to work. I finally solved it by putting the ::dispatch in a Laravel command and just ran the command, ie not using Tinker.

**Comment by judgej** [comment]
Laravel 9, 2022, the ";1;" suffix worked for me, after much head scratching.

Even bringing up tinker, dispatching once, then exiting tinker failed to add the job to the queue. That seems to be new for Laravel 9 - never seen that in 8. I guess tinker does not (or no longer does, or can't) handle the dispatching of the last job in its process shut-down.

**Comment by jelledruut** [comment]
Thanks so much for the ';1;' suggestion. Spent many hours figuring out why manual dispatching wasn't working, while dispatchSync was working just fine and all scheduled jobs were also working just fine..

**Comment by alu-** [comment]
Here comes me with 2023. Same problem and same solution, adding any statement after the dispatch _solves_ this. :sheep:

**Comment by skmidland** [comment]
2024... Same.

**Comment by dylannykolyszyn** [comment]
2025...same

**Comment by AndrewMast** [comment]
This behavior with Tinker is documented in a [warning](https://laravel.com/docs/12.x/artisan#usage):

> [!NOTE]
> The `dispatch` helper function and `dispatch` method on the `Dispatchable` class depends on garbage collection to place the job on the queue. Therefore, when using tinker, you should use `Bus::dispatch` or `Queue::push` to dispatch jobs.
