### ISSUE TITLE
chunk() method is missing half the results

### ISSUE THREAD

**Issue by nidalo91** [laravel/framework#23277]
- Laravel Version: 5.5.33
- PHP Version: 7.1.13
- Database Driver & Version: Mysql 5.6

### Description:
I have a problem with Laravel's ORM Eloquent chunk() method. It misses some results. Here is a test query :
```php
Model::orderBy('id')->chunk(500, function ($models) {
   foreach ($models as $model) {
        $model->delete();
   }                 
});
``` 
I have 10075 rows in my table and after excuting this code, i still have 5000 rows. 
<br />
In order to delete all records in my table i use ``while()`` :
```php
while(Model::count() > 0){
   Model::orderBy('id')->chunk(500, function ($models) {
      foreach ($models as $model) {
           $model->delete();
      }                 
   });
}
```

**Comment by sisve** [comment]
You need to use chunkById instead since you're doing things to the models that affect which pages they end up at.

Imagine a page size of 2, and the models A, B, C, D, E. Doing a chunk will return model A and B, which you delete. Next chunk is page two, which is a skip(2)+take(2), but since you removed A and B you only have C, D and E left. This the second chunk will contain E, and you've missed C and D.

**Comment by nidalo91** [comment]
Thank you this is was helpful
