### ISSUE TITLE
`tightenco/collect` version constraints

### ISSUE THREAD

**Issue by brendt** [laravel/framework#23366]
- Laravel Version: 5.6.4 or higher
- PHP Version: 7.2

### Description:

This commit sets the replacement version of `tightenco/collect` to `<5.5.33`: https://github.com/laravel/framework/commit/5caa88acde3d8a82fcbb9bbec8dde45dc49d4b7b 

This means that packages depending on `tightenco/collect:^5.6` aren't able to install with the latest laravel version. An example is our crawler package: https://github.com/spatie/crawler

Is this intentional?

**Comment by sisve** [comment]
Yes, because tightenco/collect changed the namespace of their Collection class from Illuminate\Support to Tightenco\Collect\Support in 5.5.33. We cannot claim that we replace another package if we do not have classes in the same namespaces.

If I understand the entries correctly, this means that we can replace releases before tightenco/collect 5.5.33, but that releases including and after tightenco/collect 5.5.33 should still be installed.

A fresh new Laravel 5.6.7 project can install the spatie/crawler package (I got 4.0.3) without any issues, and it installs tightenco/collect 5.6.7 for me.

**Comment by it-can** [comment]
@sisve and if you try to install ```composer require spatie/laravel-sitemap``` ?

**Comment by mathieutu** [comment]
Duplicate : https://github.com/laravel/framework/issues/23272

**Comment by sisve** [comment]
I was wrong in my initial test, I messed up my folders.

I _cannot_ install spatie/cralwer into a new laravel/laravel project. I'll update #23272 with details.
