### ISSUE TITLE
5.5.34 Eager loading the specific fields on a model does not return the eager loaded model

### ISSUE THREAD

**Issue by cosecantt** [laravel/framework#23424]
- Laravel Version: 5.5.34
- PHP Version: 7.2
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

### Description:
Eager loading the specific fields on a model does not return the eager loaded model.

### Steps To Reproduce:
The following:
````
Store::with('user)->get(['id', 'store_name']);
````
returns: 
````
['id'=>1, 'storename'=>'blabla', 'user'=>[]]
````
Following just works as expected:
````
Store::with('user)->get(); 
````
returns:
````
['id'=>1, 'storename'=>'blabla', .... 'user'=>['id'=>1, ....]]
````

**Comment by tomhatzer** [comment]
@cosecantt 
I would say this works as intended. You told the get() method that you only want the id and store_name of Store, so there is no user_id that the relation could have worked with.

**Result:** You won't get a relation because there is nothing that can be used to look up the user in the users table.

If you add the field that builds the relation with the user table to the array, that you are handing over to the get() method, then you'll also get a user model in return.

So your code should look something like this (if user_id contains your users id and is responsible for the relationship) for the eager loading to work:
```
Store::with('user')->get(['id', 'store_name', 'user_id']);
```

**Comment by staudenmeir** [comment]
@laurencei Can be closed.
