### ISSUE TITLE
[5.5+] artisan migrate:fresh doesn't work on Azure SQL

### ISSUE THREAD

**Issue by soltmar** [laravel/framework#23463]
- Laravel Version: 5.5.38
- PHP Version: 7.1
- Database Driver & Version: SQLSRV on Azure

### Description:
Azure SQL doesn't contain 'sp_MSforeachtable' and therefore it is impossible to run `artisan migrate:fresh` as it relies on this stored procedure.

There is a way to make this command Azure friendly:
[https://edspencer.me.uk/2013/02/25/drop-all-tables-in-a-sql-server-database-azure-friendly/](https://edspencer.me.uk/2013/02/25/drop-all-tables-in-a-sql-server-database-azure-friendly/)

I've tested it though and found there must be one additional table check added to query.

Working example should look something like this:
```
while(exists(select 1 from INFORMATION_SCHEMA.TABLES where TABLE_NAME != '__MigrationHistory'  AND TABLE_NAME != 'database_firewall_rules'))
begin
 declare @sql nvarchar(2000)
 SELECT TOP 1 @sql=('DROP TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME
 + ']')
 FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_NAME != '__MigrationHistory' AND TABLE_NAME != 'database_firewall_rules'
exec (@sql)
 PRINT @sql
end
```

**Comment by laurencei** [comment]
Which database driver are you using in Laravel? The mySQL driver - or a specific Azure SQL driver?

**Comment by soltmar** [comment]
I'm using "sqlsrv" provided by laravel

**Comment by laurencei** [comment]
Ultimately the problem is going to be that we cannot change the `sqlsrv` driver just for Azure when it works fine inside of MS SQL (which the driver was designed for).

You would want to create an Azure driver, and then make the required changes there.

Or alternatively (and more simply) - just create a custom command that drops all tables in Azure and run that for your testing.
