### ISSUE TITLE
Empty email views will no longer send attachment

### ISSUE THREAD

**Issue by roni-estein** [laravel/framework#23580]
- Laravel Version: 5.6.12
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
attaching an existing pdf file to an empty email, no longer shows the attachment. Mailtrap will show it as raw text with no attachment, apple mail shows nothing.

Putting anything in the email view will allow the attachment. However this conflicts with the api of some email fax services which need an empty email with a pdf attachment. This worked as of 5.5.37

### Steps To Reproduce:

Controller:

```
// token is just a field to secure a private file on a public drive for the few seconds this file is available and has no bearing.

Mail::to($email)->send(new EmailPdfAttachment($this->token,$this->subject));

```

Laravel 5.6 mailable EmailPdfAttachment.php

```
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class EmailPdfAttachment extends Mailable
{
    use Queueable, SerializesModels;

    public $token;
    public $subject;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($token,$subject)
    {
        $this->token = $token;
        $this->subject = $subject;

    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('emails.empty.single')
            ->attach('storage/'.$this->token.'/output.pdf',['mime' => 'application/pdf'])
            ->subject($this->subject);
    }
}

```

View emails/empty/single.blade.php

```

// this was just an empty file, which worked perfectly in 5.5.37, after a half a day i added the 
// follwing text and now it works, but it has the text attach a pdf.



attach a pdf
```
Here is screen shot from email

<img width="491" alt="screen shot 2018-03-16 at 11 52 59 pm" src="https://user-images.githubusercontent.com/8517475/37551797-c1992e52-2975-11e8-8871-8dc24ad8f654.png">

It's too clever and whitespace won't fool it.
The same code will run in laravel 5.5.x

Cheers,

please let me know if there is anything else I can do to help fix this.

**Comment by it-can** [comment]
I think Laravel is using Swiftmailer for sending emails, maybe test a couple of versions of swiftmailer if it triggers the same error?

**Comment by roni-estein** [comment]
Sure, I’ll look into it, the only change on our end was the shift from laravel 5.5 to 5.6 but I’m sure that many of the dependency versions were bumped. I’ll restore an older version to check. But if there is a way to make it work with the current technology stack that’s always preferable.

**Comment by etelford** [comment]
I just experienced this same issue.

I had been using mandrill and attaching PDFs successfully in v5.5 and just upgraded to 5.6 yesterday.

I have a view that I use as a dummy view so that the mailable will send without any errors — my actual templates are in MailChimp and set via the `X-MC-Template` header.

I added just an HTML comment to my dummy view and attachments now work as expected.

**Comment by roni-estein** [comment]
Thanks for the comment, I’d like to go back and test that, I know the single character in my case was being parsed by the external service and I ended up just downgrading to not add hours to the project. But that’s seems like a great idea!

**Comment by driesvints** [comment]
Hmm I see your point but you could argue that this is standard behavior and you would have to be explicit about any content you place in the email. Since this is more a behavioral change if we would have to add some sort of dummy comment if an email was empty I suggest to open up an issue at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
