### ISSUE TITLE
Weird issue with orderBy

### ISSUE THREAD

**Issue by BenjaminHoegh** [laravel/framework#23603]
- Laravel Version: 5.6
- PHP Version: 7.1.12
- Database Driver & Version: MySQL 5.6.38

### Description:

When using `groupBy()` it returns the wrong order!?!

E.g If we have a database with a column named address and then type in a lot of address

#### example:
```
someRoadName 5 
someRoadName 22 
someRoadName 2 
someStreetName 18 
someStreetName 16 
someStreetName 15 
someRoadName 13
```

#### Then it returns:

```
someStreetName 18 
someStreetName 16 
someStreetName 15 
someRoadName 5 
someRoadName 22 
someRoadName 2 
someRoadName 13
```

What happened to the numbers and why is orderBy not using those two?

**Comment by staudenmeir** [comment]
What query are you using?

**Comment by BenjaminHoegh** [comment]
@staudenmeir 
`DB::table("myTable")->where('id', '=',  $id)->orderBy('street_address', 'desc')->get();`

**Comment by staudenmeir** [comment]
In the title and in the question it says "groupBy()". You mean "orderBy()"?

**Comment by BenjaminHoegh** [comment]
@staudenmeir Oh! sorry my bad and yes i mean orderBy

**Comment by staudenmeir** [comment]
The reason is that you are sorting strings and they are sorted character after character. 

So "someRoadName 5" is higher than "someRoadName 22" because the database compares "someRoadName 5" with  "someRoadName 2". Only then it looks at the second "2".

You could solve it by storing road name and number in different columns.

**Comment by ColinLaws** [comment]
Recommend this one to be closed based on response from @staudenmeir
