### ISSUE TITLE
homestead mysql migrations with renameColumn changes 'null' columns to 'not null'

### ISSUE THREAD

**Issue by ashgibson** [laravel/framework#23821]
- Laravel Version: 5.6.15
- PHP Version: PHP 7.2.0-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: 5.7.20-0ubuntu0.16.04.1 (Ubuntu)

### Description:
I am doing a rename column on a nullable unsigned integer column but started getting this error after update to latest homestead

Warning: 1265 Data truncated for column 'site_id' at row 2 (SQL: ALTER TABLE items CHANGE location_id site_id INT NOT NULL)

The value for location_id in row 2 is NULL.

The sql that should have been generated is: ALTER TABLE items CHANGE location_id site_id INT UNSIGNED

### Steps To Reproduce:
Create a migration that creates a table with nullable unsigned integer field
Create data with null in that field
Create a migration to change that column using $table->renameColumn('a','b');

**Comment by piperone** [comment]
I'm on Laravel 5.5.40 and am also seeing this bug. In MySQL (5.7.21 running on Valet, macOS 10.13.3), renaming a column of type ```text```, also changes the datatype to ```longtext```. Renaming a ```timestamp```-column changes the datatype to ```datetime```. In all cases, the default value is removed and ```allow null``` is set to false.

**Comment by dbpolito** [comment]
Related to https://github.com/doctrine/dbal/issues/3091

**Comment by ajoy39** [comment]
@dbpolito it doesn't look like this bug is related to that issue, instead see this commit https://github.com/doctrine/dbal/commit/d51e918054f5d50b72b2274657d6da517e00fd21#diff-688c20898c96ed1017c40a3f9b12d051

It looks like dbal fixed a bug that was skipping adding some options to queries and NOT NULL just happened to be the default value, which was previously being skipped. This is admittedly and assumption on my part but it's the only change I can see in 2.7 that could have caused this

**Comment by piperone** [comment]
@ajoy39 Would this commit affect behavior such that datatypes are erroneously being changed as well? That's the behaviour I'm seeing.

**Comment by ashgibson** [comment]
This was a doctrine/dbal issue and has been fixed in 2.7.1 - https://github.com/doctrine/dbal/issues/3091
