### ISSUE TITLE
Double quotes(") are used to wrap table and columns instead of backtick(`) when calling toSql()  on query builder

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#23975]
- Laravel Version: 5.5.24
- PHP Version: 7.2
- Database Driver & Version: v5.7

**Comment by tillkruss** [comment]
Please provide examples and an in-depth explanation.

**Comment by dmitrijs** [comment]
For anyone confused by this behaviour and arriving here, please note:
This happens when calling toSql() from unit tests (because tests are run on sqlite, and sqlite does support double quotes).
While debugging, change SQL grammar by calling `DB::connection()->setQueryGrammar(new MySqlGrammar());`  to make toSql() generate a valid MySQL query.
