### ISSUE TITLE
array to string conversion when attach an array in extra field

### ISSUE THREAD

**Issue by mitismirza** [laravel/framework#24009]
hi guys,
sorry for consider this in here , i'm not sure this is an issues but i search alot and find noting useful.
i'm using laravel 5.5
i want to attach an array in extra field but give me an error that say array to string conversion!
this is my code with example data:
`

        $res_id=1;
        $count=2;
        $pluck=[1,2];
        $count_each_food=array(3,7);
        $reserve_detail=auth()->user()->reserved_detail()->create([
            'reserve_id'=>$res_id,
            'food_count'=>$count,
            'Coupon'    =>'sad265'
        ]);
        $reserve_detail->food()->attach($pluck,[ 'count'=>$count_each_food ]);
        return 'insert successful!';
`
the error is for $count_each_food array , laravel don't accept it and just accept simple variable
i solve it by using a loop :

`

        for($i=0 ; $i<count($pluck) ; $i++){
            $reserve_detail->food()->attach($pluck[$i],[ 'count'=>$count_each_food[$i] ]);
        }

`
but is must be a better way to handle it , in laravel [documention](https://laravel.com/docs/5.6/eloquent-relationships#updating-many-to-many-relationships) explain that if you want to use an array you can do it in this way:

`
$user->roles()->attach([
    1 => ['expires' => $expires],
    2 => ['expires' => $expires]
]);
`

but its not useful for me. because i don't know how many food i will have for attach!
plz help😕

**Comment by mcglonelevi** [comment]
Hey mitismirza,

I am having a little bit of trouble understanding what your exact issue is, but this does not look like a problem with Laravel.  It looks like you are having some issues with your array syntax.  Your issue is here:

`$reserve_detail->food()->attach($pluck,[ 'count'=>$count_each_food ]);`

$count_each_food is an array, but you need a simple value.  You can also use the array syntax like you suggested.  You might consider mapping the array as follows:

```
$count_each_food_mapped = array_map(function ($item) {
    return ['count' => $item];
}, $count_each_food);

$reserve_detail->food()->attach($pluck, $count_each_food_mapped);
```

You might also want to consider using the collections interface.  https://laravel.com/docs/5.6/collections

Hope this helps!

**Comment by mitismirza** [comment]
thanks @mcglonelevi  , this is better solution.

**Comment by MuhamadAhmadin** [comment]
thanks @MmKargar for explaining my issue, thanks also to @mcglonelevi for solving this problem. u guys great!
