### ISSUE TITLE
SQLSTATE[HY000] [2006] MySQL server has gone away

### ISSUE THREAD

**Issue by shankhadevpadam** [laravel/framework#24046]
- Laravel Version: 5.5.40
- PHP Version: 7.0.28
- Database Driver & Version: 5.7.22-0ubuntu0.16.04.1 - (Ubuntu)

### Description:
I have block 2 ip using iptable in ubuntu 16.04

iptables -I OUTPUT 1 -d 45.55.255.55 -j DROP

iptables -I OUTPUT 1 -d 45.55.41.223 -j DROP

after run these 2 command i am unable to connect the laravel project using DB_HOST=127.0.0.1 everytime say SQLSTATE[HY000] [2006] MySQL server has gone away while run php artisan server in terminal.

### Steps To Reproduce:
```
php artisan serve
```

**Comment by sisve** [comment]
There's nothing in this issue that shows that it's Laravel's fault. The fact that you're using iptables to block traffic for Sublime Text's license check makes me thing you're also doing other shady things.

Can you expand on your debugging in this issue that shows that this is Laravel's faults, instead of, let's say, something else on your machine that you've messed up?

**Comment by shankhadevpadam** [comment]
But i have no idea how to fix this issue, the laravel work very fine before run this command but after i got this issue but it work when we change 127.0.0.1 to localhost in DB_HOST in .env file.

**Comment by Blueright101** [comment]
This issue was happened for me when I inserted big image into quill text editor.
If I try small image, error was gone.
I think this is size problem.
