### ISSUE TITLE
Blade parsing problem

### ISSUE THREAD

**Issue by divdax** [laravel/framework#24078]
Laravel Version: 5.6.18
PHP Version: 7.1

---

### Problem

When render content with a single template for regular and ajax requests there is a problem when rendering the template with the regular http request. The layouts.main is rendered after CONTENT.

##### Sample Code:

```
@if(! request()->ajax())
	@extends('layouts.main')
	@section('content')
@endif

C O N T E N T

@if(! request()->ajax())
	@stop
@endif
```

**Comment by divdax** [comment]
###### Edit:

> The layouts.main is rendered after CONTENT.

**Comment by 36864** [comment]
I'm seeing the opposite behavior with your code. A normal http request will render correctly, while an ajax request will first render the content and then the layout.

In either case, this is a blade limitation - The `@extends` directive should always be the first statement, and there should only ever be one call to it in a file.

A workaround would be to use a ternary condition to determine the base layout, and creating a blank blade file to server as the "template" for ajax calls.
```
@extends( request()->ajax() ? 'layours.ajax' : 'layouts.main')
@if(! request()->ajax())
	@section('content')
@endif

C O N T E N T

@if(! request()->ajax())
	@stop
@endif
```

**Comment by divdax** [comment]
Yes you're right... sorry man... 🤦‍♂️ 

For now i use this workaround with multiple files, but it would be nice to use just one template and my sample code works correctly. 😉

**Comment by 36864** [comment]
The issue here is that blade has to "lift" the @extends directive so it knows where to put stuff as it's parsing sections and such.

I would be nice, but the extra complexity would probably slow down blade parsing, and be open to a host of other problems when people start trying to extend inside sections or pushing @extends directives to stacks.

I think a reasonable solution would be adding a new `@extends_if( $condition, $file)` directive for these cases,
