### ISSUE TITLE
Why withoutOverlapping don't use flock to get lock file ? 

### ISSUE THREAD

**Issue by alexwbaule** [laravel/framework#24194]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MariaDB

### Description:
Im trying to use withoutOverlapping, but it's have a strange behavior. The lock has a "life time", default is 1440 minutes, só if you pass to run every 10 minutes and don't set the "timer" to at last that, the scheduler don't run, because it locked.

I Thing, that correct it's use flock to lock the execution. Reading the issues , i saw many users with problems, about "after restarting the schedule, the lock don't get removed"... Using the flock all this problems has gone. Flock get locked only when the code is in execution, if you close the lock or kill the schedule, the lock get removed.

Someone agree with me ? 

Tks !!

**Comment by sisve** [comment]
Well, `flock` locks a local file resource. It wouldn't work to coordinate a lock between several machines.

> Reading the issues , i saw many users with problems, [...]

Please provide links to the issues, or anything to back this up.

> "after restarting the schedule, the lock don't get removed" [...] or kill the schedule [...]

This sounds like someone has a really weird deployment script that does `killall -9 php` instead of properly stopping cron to stop firing schedule:run. It also sounds like the scheduler is executing code that takes a long time instead of dispatching jobs to queue workers that are meant for asynchronous long running tasks.

This issue doesn't read as a bug report. Should it perhaps be closed and moved onto a forum or Slack chat?
