### ISSUE TITLE
Generated filename is not unique

### ISSUE THREAD

**Issue by panstromek** [laravel/framework#24217]
There is a line in the docs that says that when you call $uploadedFile->store():

>By default, the store method will generate a unique ID to serve as the file name.

But when I look at the actual code, it just calls Str::random(), which doesn't seem unique.

**Comment by tillkruss** [comment]
It's random, not unique. If you store Exabytes of files you might run into collisions.

For example `random_bytes(16)` has 128 random bits, so you have a 50% chance of seeing a collision after approx. 2^64 generated file names.

**Comment by panstromek** [comment]
Yes, but even though probability is very low, it can happen anytime and than it overrides existing files, right? Wouldn't it be better to prevent that?

**Comment by tillkruss** [comment]
I won't happen, you're more likely to win the lottery every year until you die.

**Comment by panstromek** [comment]
The thing is that it's not guaranteed. I wouldn't use it in production no matter how low the probability is.

Sure I can add check if file exists or generate true unique name in every application but why not on framework level.

And when the collision happens, does laravel override the file or throws some collision exception?

**Comment by rs-sliske** [comment]
if it is really important to you, you could generate the filename yourself.

the only real solution here is to keep trying to generate a filename until you get one that doesnt exist.

i have used this solution in the past 
![https://i.imgur.com/Qb6xPAz.png](https://i.imgur.com/Qb6xPAz.png)

an alternative which i have also used in the past, would be to use a hashing function rather than random. this would mean if the same file was uploaded multiple times, only 1 copy would be stored. 

both of these techniques suffer from pigeon hole problem. there are more possible files than filenames.
