### ISSUE TITLE
Packets out of order when losing connection

### ISSUE THREAD

**Issue by peterlupu** [laravel/framework#24255]
- Laravel Version: 5.6.22
- PHP Version 7.2.3
- Database Driver & Version:  mysql driver, connecting to 10.2.15-MariaDB-10.2.15+maria~stretch-log

### Description:

After some time trying to debug weird "Packets out of order" in my Laravel app, I think I've managed to consistently reproduce the issue. When the MariaDB (maybe MySQL as well, did not test it) restarts while a Laravel script is running, Laravel will not attempt to reconnect if we receive a "Packets out of order." exception.

### Steps To Reproduce:

1. Fresh debian stretch install.
2. MariaDB 10.2.15.
3. Database itself doesn't matter, we're not doing any operations on it.
4. Fresh laravel app, create a new job:

```php
public function handle()
{
    while (true) {
        dump(\DB::select('select connection_id()'));
        sleep(10);
    }
}
```

This will basically connect to the database and output the connection ID every 10 seconds.

Everything is okay thus far, but, for the sake of testing, let's lower MariaDB's `wait_timeout` setting to 5 seconds.

5. Edit `/etc/mysql/my.cnf` and set `wait_timeout = 5` (under `[mysqld]`).

6. Run the job. I used tinker, just for the sake of easier debugging.

`php artisan tinker`
`>>> (new \App\Jobs\TestJob)->handle()`

You'll see outputs like:

```
array:1 [
  0 => {#2313
    +"connection_id()": 9
  }
]
array:1 [
  0 => {#2301
    +"connection_id()": 10
  }
]
array:1 [
  0 => {#2313
    +"connection_id()": 11
  }
]
```

And in MariaDB's logs you'll see 

```
2018-05-20  1:01:44 140013519836928 [Warning] Aborted connection 9 to db: 'homestead' user: 'test' host: 'localhost' (Got timeout reading communication packets)
2018-05-20  1:01:54 140013519836928 [Warning] Aborted connection 10 to db: 'homestead' user: 'test' host: 'localhost' (Got timeout reading communication packets)
2018-05-20  1:02:02 140013519836928 [Warning] Aborted connection 11 to db: 'homestead' user: 'test' host: 'localhost' (Got an error reading communication packets)
```

Notice the same connections id.

Everything is okay thus far.

We start the job, a DB connection is established, and then while the job is working, MariaDB is killing connections that time out. That's no problem here, since Laravel's using its `Illuminate\Database\DetectsLostConnections` trait that will take care of reconnecting to the DB. The exception that triggers the reconnectiong is "MySQL Server has gone away", which **is** handled by this trait.

But let's do the following:

Start the job, and after the first connection id returned (or more, doesn't matter), restart your MariaDB server **while** the job is running:

```
array:1 [
  0 => {#2310
    +"connection_id()": 9
  }
]
--- here the job is sleeping ---
--- $ systemctl restart mariadb ---
--- job is still sleeping, mariadb just successfully restarted and can accept connections ---
--- a new connection will not be attempted by the script, and: ---
Illuminate/Database/QueryException with message 'PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=30 in /Users/peter/tmp/testapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 326 (SQL: select connection_id())'
```

I've google for this problem quite a bit, and some people suggested setting ` PDO::ATTR_EMULATE_PREPARES => false` to the connection options. This returns the same error `Illuminate/Database/QueryException with message 'PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=30 in /Users/peter/tmp/testapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 330 (SQL: select connection_id())'` **but** notice that the line number has changed.

My point being, this is a case of losing the connection itself to the server, because the server restarts and doesn't know about that connection any more. Maybe we should add `'Packets out of order.'` to `DetectsLostConnections::causedByLostConnection()` method? But maybe this error will be triggered in other scenarios, where a lost connection doesn't actually happen.

Any suggestions would be appreciated, thanks.

Edit: Also, I noticed #23925 is somewhat related; a solution that issue would be a way to customize the "connection lost" messages in the trait.

**Comment by RoussKS** [comment]
@peterlupu not sure if this has been fixed in any PRs, but we have a similar issue.

If this is mainly affecting jobs, instead of adding that error to the trait's options, would it be better to reschedule a job 1 min later for example, in order to allow the sql server to restart?

Just a suggestion, not sure how easy it is to implement it. Or if this will not affect other aspects.

**Comment by driesvints** [comment]
A PR was merged for this. If you're still experiencing issues with this after this feel free to report back.

**Comment by adeel-raza-azeemi** [comment]
I am also experiencing this issue (but instead of arising from job; it arsing from stored procedure call. 
I am using laravel 7.6. PHP 7.2.
First i though laravel can't call a stored procedure. (but when i created a rudimentary procedure and it not giving this error (packet out of order). Then i though maybe it because of the empty inputs (procedure needed 17 input (its basically a customize report  based on the given inputs). This was also not the case because rudimentary procedure didn't complained. For cation i had replaced all the new line characters from the returned record set. still no luck. 

Funny thing is there is no error in the procedure because it work perfectly from terminal.  
procedure is of 800 line code. Basically it (procedure) first checks the input arguments and based of whether a value is given or not create a filter (concatenated string) on the main table. then its loops through the secondary detail table and takes some values from secondary detail table. then finally based on those values fetches info from detail tables (profiles). On terminal it takes 0.036 sec to execute. 

But a call from laravel and mariadb gives  Aborted connection to db (Got an error reading communication packets).

2020-06-22 12:56:05 15 [Warning] Aborted connection 15 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
2020-06-22 12:56:08 14 [Warning] Aborted connection 14 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
2020-06-22 12:56:08 68 [Warning] Aborted connection 68 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
2020-06-22 12:56:08 67 [Warning] Aborted connection 67 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)

**Comment by adeel-raza-azeemi** [comment]
For now I had pin it down; that the error emerge only when laravel calling a stored procedure that had a  CURSOR opened.

**Comment by adeel-raza-azeemi** [comment]
Dries Vints @driesvints i had read that issue before issuing this several times. And PR didn't solved this issue.

**Comment by basepack** [comment]
Still have this problem, which arises when using Jobs, Notifications and Events related to queue usage. 

Can we reopen this issue?

**Comment by uaoleg** [comment]
Having the same issue with queue job on Yii2 ))
