### ISSUE TITLE
强烈建议！laravel官方引入swoole来加速laravel

### ISSUE THREAD

**Issue by zmou** [laravel/framework#24314]
强烈建议！！！
laravel官方引入swoole来加速laravel，因为laravel实在太笨重，导致项目庞大了以后，运行速度急速下降，目前民间有人适配了swoole来加速laravel，但是还存在各种各样的问题，希望官方适配swoole，用户可以选择使用或者不使用swoole来加速。
强烈建议！！！

**Comment by scil** [comment]
consider [LaravelFly](https://github.com/scil/LaravelFly/) which uses swoole and avoids data pollution.

**Comment by fifsky** [comment]
**First**, you should use English to give advice. You can use translation software to assist.

**Second**, performance is not the only requirement in a large-scale architecture. Project stability, robustness, and scalability are all worthy of attention.

**Third**, we have too many solutions to solve performance problems, such as distributed deployment, caching, asynchronous queues, and so on. You can even use other higher-performance compiled languages on key nodes (APIs) to solve problems, such as Golang.

**Fourth**, we can develop Swoole as an extension of the Laravel framework (as @scli said) instead of writing Swoole directly into the framework. This is a very violent compromise.
