### ISSUE TITLE
Storage::disk('local')->append method run out of memory

### ISSUE THREAD

**Issue by fatrbaby** [laravel/framework#24439]
- Laravel Version: 5.6.23
- PHP Version: 7.1.18
- Database Driver & Version: --

`Storage::disk('local')->append(...)` method runs out of memory when the operating file is large (tens of M).

**Comment by sisve** [comment]
Increase your memory limit. An append will read the file content into memory, build a new content, and write that new content. There's no optimized version of append available in the [league/flysystem](https://github.com/thephpleague/flysystem/) package, because some adapters like S3 does not support it.

**Comment by fatrbaby** [comment]
@sisve thx 4 your advice

**Comment by yaroslawww** [comment]
Yes if you use Storage methods. Than laravel get content of **TWO** files and merge it.
If will use only **LOCAL FILESYSTEM** you can use standard php fuction - in this case php will load to memory only appended content.
Simple example:
```php
        $file    = $request->file( 'file' );
        $storage = Storage::disk( 'local' );
        $path    = "chunks/{$file->getClientOriginalName()}";

        if (! $storage->exists($path)) {
            $storage->put($path, '');
        }

        file_put_contents($storage->path($path), $file->get(), FILE_APPEND);
```
