### ISSUE TITLE
Named routes inside domain group fails

### ISSUE THREAD

**Issue by BadKnees** [laravel/framework#24545]
- Laravel Version: 5.6.24
- PHP Version: 7.2.5

### Description:
Using route('myroute') inside a template fails with:
```
Missing required parameters for [Route: myroute] [URI: myroute].
```
when myroute is defined inside a domain group.
### Steps To Reproduce:

Create a brand new Lavavel project with:
```
# laravel new test
```

Edit routes/web.php to look like this:

```
Route::get('/', function () {
    return view('welcome');
});

Route::domain('{subdomain}.test.dev')->group(function () {
	Route::get('/myroute', function(){
		return view('welcome');
	})->name('myroute');

});

```
Confirm:
```
#php artisan route:list
+-----------------------+----------+----------+---------+---------+--------------+
| Domain                | Method   | URI      | Name    | Action  | Middleware   |
+-----------------------+----------+----------+---------+---------+--------------+
|                       | GET|HEAD | /        |         | Closure | web          |
|                       | GET|HEAD | api/user |         | Closure | api,auth:api |
| {subdomain}.test.dev | GET|HEAD | myroute  | myroute | Closure | web          |
+-----------------------+----------+----------+---------+---------+--------------+
```
Add this to your resource/views/welcome.blade.php

```
<a href="{{ route('myroute') }}">My Route</a>
```

And view  mysubdomain.test.dev in the browser:

```
ErrorException (E_ERROR)
Missing required parameters for [Route: myroute] [URI: myroute]. (View: /Users/abo/Sites/test/resources/views/welcome.blade.php)
```

**Comment by staudenmeir** [comment]
Since the route has a `{subdomain}` parameter, you have to specify a value for it:

```php
route('myroute', ['mysubdomain'])
```

**Comment by BadKnees** [comment]
But route() and php artisan route:list do not see things eye to eye. Changing web.php to:

```

Route::get('/', function () {
	return view('welcome');
});

Route::domain('{subdomain}.test.dev')->group(function ($subdomain) {
	Route::get('/subdomain', function(){
		return "subdomain";
	})->name('home');
});

Route::domain('test.dev')->group(function () {
	Route::get('/system', function(){
		return "system";
	})->name('home');
});
```
php artisan route:list
```
+-----------------------+----------+-----------+------+---------+------------+
| Domain                | Method   | URI       | Name | Action  | Middleware |
+-----------------------+----------+-----------+------+---------+------------+
|                       | GET|HEAD | /         |      | Closure | web        |
| {subdomain}.test.dev | GET|HEAD | subdomain | home | Closure | web        |
| test.dev             | GET|HEAD | system    | home | Closure | web        |
+-----------------------+----------+-----------+------+---------+------------+
```

But on sub.test.dev using the route('home', ['sub']) renders:
```
 <a href="https://test.test/system?sub">My Route</a> 
```
Should be:
```
 <a href="https://sub.test.test/subdomain">My Route</a> 
```

And on test.dev using the route('home') renders:
```
 <a href="https://test.test/system">My Route</a> 
```

I don't see how to use route() helper in a multitenant system where i group by subdomain, and subdomain is dynamic. 

if route() saw the routes like php artisan route:list it would work.

**Comment by 36864** [comment]
You're defining two routes with the same name. How did you expect laravel to handle this sort of conflict?

**Comment by BadKnees** [comment]
By Domain. It's different. Laravel handles it just fine. It's just the route() helper that lags a bit behind. 
But this i maybe not a bug. So Im closing it.

**Comment by aleangelico** [comment]
> 
> 
> By Domain. It's different. Laravel handles it just fine. It's just the route() helper that lags a bit behind.
> But this i maybe not a bug. So Im closing it.

I think this is a bug, but the workaround is what @staudenmeir suggested:
`route('myroute', ['mysubdomain'])`

you can get the group parameter with something like (this is what took me a while to figure out):

```
public function index()
    {
            $subdomain = Route::current()->parameter('subdomain');
            return view('welcome', compact('subdomain'));
    };
```
and in your view:
`{{ route("home", [$subdomain] )}}`

**Comment by zeshan77** [comment]
@aleangelico Perfect, it worked like a charm!

The only suggestion I would make is to place that bit of code in a service provider or one of the middlewares and then share the variable with all the views rather than passing it from every controllers. Will make life much easier.

I added the code to one of my middlewares as shown below:

`\View::share('subdomain', \Route::current()->parameter('subdomain'));`

**Comment by sankety** [comment]
This is a legit bug.
Passing $subdomain to each route helper manually is not a solution, also the View::share idea is good and does the trick but it is in a way hack.

**Comment by colynb** [comment]
I've decided to abandon using the route domain group because of this. It's not working great with Laravel Fortify. In the fortify.php config file, you can specify that the fortify routes need to be included in a domain group, but there are downstream consequences. For various features like email verification, Laravel tries to redirect to a named route but with domain grouping enabled, I get the error that it's missing the required parameters. That aside, the user experience, in general, working with domain groups, has not been worth it.

**Comment by michelterstege81** [comment]
2022 and this is still an issue. I'm currently implementing a multitenancy app with 2fa. I have subdomains for the tenants and their admins. Luckily the 2fa middleware has an extra parameter to set a custom redirect route. So I can do:

`
Route::middleware([
     '2fa.enabled:tenant.admin.2fa.setup'
])->group(function () {
    Route::view('/', 'tenant.dashboard')->name('dashboard');
});
`

On a higher level I have Route::name('tenant.admin.)->domain('{subdomain}.'.env('APP_URL', ''))->group('path/to/route/file');

Now when the 2fa middleware wants to redirect to the tenant.admin.2fa.setup route it throws an exception because it's missing the subdomain there.
