### ISSUE TITLE
wrong version of php requirement

### ISSUE THREAD

**Issue by Aro777** [laravel/framework#24598]
- Laravel Version: 5.4.*
- PHP Version: 5.6.*

#### doctrine/inflector

This package is needed in laravel 5.4, but this package requires the version of php 7.1 and for laravel 5.4 need a php 5.6

**Comment by staudenmeir** [comment]
Only the latest version of `doctrine/inflector` requires PHP 7.1. If you install Laravel 5.4 with PHP 5.6, Composer installs `v1.1.0` which only requires PHP 5.3.2.

**Comment by tillkruss** [comment]
https://laravel.com/docs/5.6/releases#support-policy

**Comment by staudenmeir** [comment]
Please check the installed version of `doctrine/inflector` with `composer show`.

**Comment by dtunes** [comment]
Hi,

illuminate/support requires doctrine/inflector: ~1.1 or ~1.0 depending on the version of illuminate/support, the problem is that doctrine/inflector 1.2 and up require php 7*, requiring ~1.1 will install doctrine/inflector 1.3.

Is it possible if I submit a PR to get this fixed and merged into 5.3 and tag 5.3.24?

Can someone point me in the right direction here, I submitted one to illuminate/support repo, but realized now its a read only repo.
