### ISSUE TITLE
bindValue function use PDO::PARAM_INT in MySqlConnection.php will cause error when the value is int64

### ISSUE THREAD

**Issue by JihanZhuang** [laravel/framework#24663]
- Laravel Version: 5.4.*
- PHP Version:5.6.30
- Database Driver & Version:pdo_mysql 5.6

### Description:
`App\Flight::where('active', 1)
          ->where('destination', 'San Diego')
          ->update(['delayed' => 144115188075858910]);`
when the type of "delayed" is bigint in mysql ,I update it,but it does not the value what I want.

I finally found that it is because bindValue function use PDO::PARAM_INT in MySqlConnection.php.
I delete the code and change it like this:
` public function bindValues($statement, $bindings)
    {
        foreach ($bindings as $key => $value) {
            $statement->bindValue(
                is_string($key) ? $key : $key + 1, $value,
                PDO::PARAM_STR
            );
        }
    }`

### Steps To Reproduce:
- Perform an update statement
- use a number larger than int32,and mysql column type is bigint
- found that the number can not correctly show in mysql

**Comment by staudenmeir** [comment]
One of your version numbers is incorrect: You can't use Laravel 5.6 with PHP 5.6

**Comment by JihanZhuang** [comment]
@staudenmeir        sorry，I make a mistake.the correct information is :
 "php": ">=5.6.4",
        "laravel/lumen-framework": "5.4.*",

**Comment by vlakoff** [comment]
I did some quick researches. Refs stackoverflow: [bigint truncated via PDO?](https://stackoverflow.com/questions/36155966/bigint-truncated-via-pdo)

This use case is expected to be supported. The problem is not at the Laravel level. You should do a review of your web server setup: all components compiled x64, mysqlnd library, etc.

Using `PDO::PARAM_STR` is a wrong solution (could lead to other cast errors, apparently significantly slower, etc.). You should aim to avoid it.

**Comment by JihanZhuang** [comment]
@vlakoff oh,I see,thank you for helping me to deal with this problem.
