### ISSUE TITLE
Validator 'date' does not allow dates greater than 2038

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#24696]
- Laravel Version: 5.6.26
- PHP Version: Tested on 7.2.5
- Database Driver & Version: N/A

### Description:
When using the validator 'date', a date like `2068-01-01 00:00:00` will fail validation because it exceeds the 32-bits from PHP function `strtotime` (http://php.net/manual/en/function.strtotime.php). Therefore the validator returns false. This is also known as the "year 2038 problem".

### Steps To Reproduce:
Create a validator instance in a controller like:
```
$validator = \Illuminate\Support\Facades\Validator::make([
            'my_expired_date' => '2068-06-28 14:51:15'
        ], [
            'my_expired_date' => 'required|date'
        ]);

        // returns "true"
        dd($validator->fails());
```

**Comment by bert-w** [comment]
Workaround:
`['my_expired_date' => 'required|date_format:Y-m-d H:i:s']`

**Comment by dwightwatson** [comment]
I would say this is expected behaviour - you're trying to use the date validator to validate a datetime. If you use the date validator to validate a date beyond the "year 2038 problem" like the 20th of January, it works as expected.

```php
Validator::make(['date' => '2038-01-20'], ['date' => 'required|date'])->passes();
```

Using the `date_format` validator instead isn't a workaround, it's the proper way to validate that input.
