### ISSUE TITLE
Lazy service resolving

### ISSUE THREAD

**Issue by ed-fruty** [laravel/framework#24753]
I want to up question about closed PR #24294 and hear a community mind.

@freekmurze , @GrahamCampbell , @sisve  and other community memebers, what do you think about this?

Please read my [comment](https://github.com/laravel/framework/pull/24294#issuecomment-391616154) and description at all.

**Comment by 36864** [comment]
This isn't a bug, please use the ideas repo.

**Comment by ed-fruty** [comment]
@36864 I think it's a bug. For example, my application - is only API, no views even maybe translations. But they still resolving in bootstrapping application.

**Comment by 36864** [comment]
Is the view provider in the `providers` array of your `app.php` config file?

**Comment by ed-fruty** [comment]
@36864 if you read PR details, you'll know, it's not by providing `ViewServiceProvider`. It's by `PaginationServiceProvider` in this case. but the question is not about this providers, but about configuration via `loadViewsFrom` and similar in **any service provider**.

**Comment by 36864** [comment]
None of what you're describing is a bug.

This is either a feature request or a performance patch, but you're not actually fixing anything that is currently broken.

I'm not saying I disagree with what you want to do, but this issue is clearly not a bug report and, as such, does not belong in this repository. Please use the ideas repo. It would also be a good idea to describe the issue in your post rather than just linking to old posts.
