### ISSUE TITLE
Laravel generate cache config.php without mysql password

### ISSUE THREAD

**Issue by betterapp** [laravel/framework#24959]
- Laravel Version: 5.6.28
- PHP Version: 7.2
- Database Driver & Version: MariaDB

### Description:
When i run php artisan config:cache artisan creates cache without mysql password.
password is set in database.php config and .env file

**Comment by fians** [comment]
I just test it, and it's working fine. Database credentials is imported to cache config file, which is in `bootstrap/cache/config.php`. 

What do you mean by having "password in database.php config and .env file"? Do you have password in both files? Because usually database credentials is set .env and imported in `database.php` using `env()`

**Comment by betterapp** [comment]
I use .env file. But after last laravel update, cache config was generated without password.
So I put credentials do database.php config file. I know this no make sens.
Then i cleared cache and generated it again and the cached password is empty.

**Comment by staudenmeir** [comment]
I assume you can't post the password here? Does it contain spaces? Can you try a simple alphanumeric password?

**Comment by betterapp** [comment]
I tried different password. I will debugging it

**Comment by betterapp** [comment]
ok. I have found it.
this is becouse of vlucas/phpdotenv check: if ENV value is not in double quates and have # sign then it is interpreted as comment and function return empty string.
I needed to set password in double quotes and now it is working
