### ISSUE TITLE
Laravel Logging-Aes-Blob

### ISSUE THREAD

**Issue by Temario** [laravel/framework#25032]
- Laravel Version: 5.6.28
- PHP Version: 7.1.10
- Database Driver & Version:  mysql version: 10.1.28-MariaDB
### Description:
We have a problem with the log-in of laravel. 
Currently we have the credentials in database stored in Blob type (username and password) and aes encrypted.
For some reason, when you login with some users, laravel indicates that the credentials don´t match. 
We believe that the error comes from converting the blob type to utf-8 because changing that username to another one works correctly.

ex: 'RAHERGARCONSULTINGSL' => don´t work.
ex: 'RAKBELS' => it´s works (an another also works fine).

We suppose that when decrypting this user we encrypted it with the function "openssl_encrypt($string, 'aes-128-ecb', $key, OPENSSL_RAW_DATA);" returns a different result than it should.

We have tried to change the length, bigger or smaller, without generating the error.

### Steps To Reproduce:
Login and password with Blob type, in the database.
I´ve created one method to hash the password in the user model: 
    public function getAuthPassword()
    {
        return \Hash::make($this->pass);
    }
## Without this function, the logging function doesn´t work properly.

In our LoginController, we have add this functions: 

public function username() {
      return 'login';
}

protected function credentials(Request $request) {   
       $credentials = $request->only($this->username(), 'password');
       $credentials['login'] = mysql_AES_ENCRYPT($credentials['login'], env('DB_AES_PASSWORD', 'doc3w_apli'));
        
        return $credentials;
 }

In the credentials function, only encrypt the username because our ddbb´s login is encrypted with aes. (password really too, but we don´t know how it returns both) 

This is ours aes encrypt and decript functions:
function mysql_AES_ENCRYPT($cadena, $key) {
    return openssl_encrypt($cadena, 'aes-128-ecb', $key, OPENSSL_RAW_DATA);
}
function mysql_AES_DECRYPT($cadena_cifrada, $key) {	
    return openssl_decrypt($cadena_cifrada, 'aes-128-ecb', $key, OPENSSL_RAW_DATA);
}

**Comment by sisve** [comment]
Encrypting the password, instead of hashing them, goes against normal security practices.

It sounds like you should build your own UserProvider implementation, with a custom validateCredentials method. So far I don't see how your issue is a problem with the framework.

https://github.com/laravel/framework/blob/ab62f037fe7d2b611722801f73f2541a1c7553ec/src/Illuminate/Auth/EloquentUserProvider.php#L138-L143

**Comment by Temario** [comment]
We actually have our password encrypted and we use hash too.
We think the problem is something about special chars because when we change the login, it works.

NEW INFO:
I have encrypted the string that generates the error and compared it to that same string with small modifications:

ORIGINAL STRING ( DOESN'T WORKS )
 b"`ÌO\x07F@À¬G╝ej£\x1F%╝\x1Dö"½Æ:b¶P¼ì│\x1E╚X³"

ORIGINAL STRING WITH ONE MORE CHAR ( WORKS )
 b"`ÌO\x07F@À¬G╝ej£\x1F%╝+*'ØM®¬&\x00§¥ bÌë¹"

ORIGINAL STRING REMOVING ONE CHAR ( WORKS )
 b"`ÞO\x07F@·ªG¼ejœ\x1F%¼ã1\x1A¢áqšŸ%Nª\efØ°÷"

**Comment by sisve** [comment]
You have not yet shown how this is a bug or problem in the framework. It appears to be an issue in your application code.

I have no idea why your random attempts at manually editing the ciphertext is relevant or changes anything.

It's unclear what the problem is, why you're using the framework's bug reporting tool to tell us about it, and what you expect to get out of it. Have you tried using a forum or Slack instead?
