### ISSUE TITLE
Using real-/full path with blade compiler exceptions

### ISSUE THREAD

**Issue by kasperhartwich** [laravel/framework#25215]
Hi. Is there a speciel reason why we are showing the full path for a blade view, when an exception occurs?
https://github.com/laravel/framework/blob/d6b96ce6b097c55b9f31bc3839938ae286de4843/src/Illuminate/View/Engines/CompilerEngine.php#L90

My issue is that I want the exception message to be unique. 
But when an error happens with the full path and when using paths with timestamp/deploymentid like for example Envoyer, the path will not be unique.

Why not use the base path of the application?

**Comment by sisve** [comment]
I don't understand the use case. Is the full path not unique?

**Comment by mfn** [comment]
> I don't understand the use case. Is the full path not unique?

Not in his deployment, because:
>  full path and when using paths with timestamp/deploymentid

I think this is more suited for laravel/ideas TBD first.

**Comment by sisve** [comment]
I didn't really get that part. All these paths are unique. What am I missing?

    /var/www/domain.com/release-20180814-commit-ca11ab1e/
    /var/www/domain.com/release-20180815-commit-b01dface/
    /var/www/domain.com/release-20180815-commit-5ca1ab1e/

**Comment by mfn** [comment]
Yay, this is a real funny one. Indeed, OP says:
- wants exception unique
- paths aren't unique

When in fact, I'm pretty sure, OP means the exact _opposite_:
- wants exception to be not unique
- but paths are unique

I understood it this way automagically because I too use an external exception aggregation system which works on a few factors to group things, and error message content is one of them. And the full realpath being one of them makes each exception unique and thus not useful for aggregation.

@kasperhartwich you better confirm this or I feel stupid 😄

**Comment by kasperhartwich** [comment]
I added a pull request to solve this.

**Comment by mfn** [comment]
You're keep mixing up "unique" vs. "non-unique" that's why @sisve asked about it.

There are **unique** exceptions; each one is unique / different from each other:
- `Use of undefined constant reference - assumed 'something' (View: /var/www/domain.com/release-20180814-commit-ca11ab1e/resources/views/dashboard/index.blade.php)`
- `Use of undefined constant reference - assumed 'something' (View: /var/www/domain.com/release-20180815-commit-b01dface/resources/views/dashboard/index.blade.php)`

You want them **not** to be unique so you can group them. I get and support your point.

**Comment by kasperhartwich** [comment]
I agree. They are different from each other and that is the problem. I want them to be the same. All exception/ticket systems is looking at the exception message.

These are not unique, as they are different from eachother:
- Use of undefined constant reference - assumed 'something' (View: /var/www/domain.com/release-20180814-commit-ca11ab1e/resources/views/dashboard/index.blade.php)
- Use of undefined constant reference - assumed 'something' (View: /var/www/domain.com/release-20180815-commit-b01dface/resources/views/dashboard/index.blade.php)

This would be the same, so they will end on same "ticket":
- Use of undefined constant reference - assumed 'something' (View: /resources/views/dashboard/index.blade.php)
- Use of undefined constant reference - assumed 'something' (View: /resources/views/dashboard/index.blade.php)

**Comment by laurencei** [comment]
Could you just override this in your `app\Exceptions\Handler.php` file?

**Comment by driesvints** [comment]
I think it's best to open up an issue in https://github.com/laravel/ideas first to see how others feel about it. If you can gather support for your use case there, it could be considered.
