### ISSUE TITLE
It isn't possible to access an entry tagged with multiple tags by providing just one of this tags [Cache Tags]

### ISSUE THREAD

**Issue by sgasser** [laravel/framework#25234]
- Laravel Version: 5.6.29
- PHP Version: 7.2

https://laravel.com/docs/5.6/cache#cache-tags

### Description:
It is possible to invalidate all entries tagged with multiple tags by providing just one of this tags, but to access an entry you have to pass all tags in the exact order. It would be great if you could access all entries tagged with multiple tags by providing just one of this tags.

---

#### Example for my case:
I'm creating a package to cache eloquent queries.

#### Storing
List of authors
```Cache::tags(['author-1', 'author-2', 'author-3', 'author-all'])->put('List'.$checksum, $authorList, $minutes);```

#### Invalidate
Invalidate author (for example update author)
```Cache::tags(['author-1'])->flush();```
Invalidate list (for exampe I added a new author)
```Cache::tags(['author-all'])->flush();```

#### Accessing
To get the list I have to know all tags:
```Cache::tags(['author-1', 'author-2', 'author-3', 'author-all'])->get('List'.$checksum);```

#### Better solution
```Cache::tags(['author-all'])->get('List'.$checksum);```

**Comment by driesvints** [comment]
This is unfortunately how it works. If you want to propose a different behavior it's best to propose an idea at https://github.com/laravel/ideas

**Comment by alexryall** [comment]
Looked into this as it would have been a useful feature for something I was trying to do. The way the cache currently works in Laravel is quite far from this working because in the key names it has a hash of all the tags combined.

`Cache::tags(['author-1', 'author-all'])->put('List'.$checksum, $authorList, $minutes)`
`Cache::tags(['author-2', 'author-all'])->put('List'.$checksum, $authorList, $minutes)`

So the above would create 2 different records, but we'd need this to only create 1 record for it be accessible when only having some of the tags. Possible with Redis but would be a pretty breaking change with how Laravel currently works.

**Comment by kolirt** [comment]
I faced the same problem and after spending a lot of time searching I found the problem

The problem is in this line
https://github.com/laravel/framework/blob/81a0b5b60ff83d7a47177675741c41c1dfe78967/src/Illuminate/Cache/TaggedCache.php#L102
It leads to excessive duplication of data in the cache when you use multiple tags. If you return only `$key`, everything works as expected. After testing for a long time, I did not find any side effects


You can copy this modified file with the fix [Overrides/TaggedCache.php](https://github.com/kolirt/laravel-cacheable/blob/master/src/Overrides/TaggedCache.php) or just install my [kolirt/laravel-cacheable](https://github.com/kolirt/laravel-cacheable) package if it's useful to you

And then you need to add the following code to composer.json and specify either your path to the new file or use the file from the package if you installed it

```json
{
    "autoload": {
        "exclude-from-classmap": [
            "vendor/laravel/framework/src/Illuminate/Cache/TaggedCache.php"
        ],
        "files": [
            "vendor/kolirt/laravel-cacheable/src/Overrides/TaggedCache.php"
        ]
    }
}
```
After updating the composer (`composer dump-autoload`), the new file will replace the file from Laravel and everything will work as you expect
