### ISSUE TITLE
User email reset should always return successful

### ISSUE THREAD

**Issue by ikari7789** [laravel/framework#25291]
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Auth/Passwords/PasswordBroker.php#L62-L64

By showing the user that the email doesn't exist in the system, it could allow an attacker to enumerate over email addresses and find which ones have valid accounts on a website. Rather email reset should always return that it has sent a reset email regardless of whether or not the user actually exists within the system.

**Comment by JayBizzle** [comment]
Surely the problem will still exist even after changing this?

If you have a registration form, it will alert you if the email address you are trying to register with already exists in the system.

**Comment by ikari7789** [comment]
@JayBizzle I've updated the original code location to more appropriately show what should be removed.

**Comment by laurencei** [comment]
This has been discussed at length before.

Essentially almost all services have a signup page - so you can **always** see if a user is registered or not, because you need to be a unique email there. So this doesnt solve the issue you think it does, but reduces UX for end users without adding anything back.
