### ISSUE TITLE
Breaking security release 5.6.36

### ISSUE THREAD

**Issue by staudenmeir** [laravel/framework#25515]
The security release 5.6.36 escapes the output of `@lang` calls (https://github.com/laravel/framework/commit/d3c0a369057d0b6ebf29b5f51c903b1a85e3e09b). This broke a lot of applications and even Laravel features like the links of simple pagination and the user verification email (#25408, #25430, #25501).

But there is still no additional information on the release (AFAIK), not even a *crucial* entry in the upgrade guide.

As [suggested](https://github.com/laravel/framework/pull/25408#issuecomment-418642559) by @stayallive, can't we just escape the parameters? Shouldn't the application's language files be considered a secure input?

**Comment by X-Coder264** [comment]
I completely understand breaking stuff for security reasons, but unlike the cookie serialization stuff this didn't even get a tweet, let alone a mention in the documentation even though it broke a huge amount of applications.

**Comment by daniesy** [comment]
This is still open after 19 days?

**Comment by marcbelletre** [comment]
There has been many issues opened about this and I don't understand neither why all of them are still ignored. @at-dro proposed a solution 10 days ago in [#25408](https://github.com/laravel/framework/pull/25408#issuecomment-421966886) that sounds good. Is there any chance this could be implemented?

I stopped updating my Laravel apps since this release because it would take way too much time to replace everything. Of course I could just search and replace every `@lang()` directive with `{!! __() !!}` but this would make no sense for two reasons:

- This would reintroduce the XSS vulnerability as @at-dro said in his comment
- This would be totally useless for strings that do not contain any HTML

**Comment by drakakisgeo** [comment]
I downgraded and locked the laravel-framework dependency. I will wait a few weeks more for this one, it really broke everything in so many ways.... so I'll hope a clean solution will be found, before renaming everything.

**Comment by markovic-nikola** [comment]
> I downgraded and locked the laravel-framework dependency. I will wait a few weeks more for this one, it really broke everything in so many ways.... so I'll hope a clean solution will be found, before renaming everything.

Same here

**Comment by taylorotwell** [comment]
I'm reverting this entire dumpster fire. Will just document if you use @lang its up to you to escape.
