### ISSUE TITLE
File mime validation fails when faking upload in tests

### ISSUE THREAD

**Issue by unlikenesses** [laravel/framework#25571]
- Laravel Version: 5.7.2
- PHP Version: 7.1.18
- Database Driver & Version: MySQL Ver 15.1 Distrib 10.3.7-MariaDB

### Description:
When testing uploading a file of type `mp3`, the validation which looks for `mp3` mimes fails.

### Steps To Reproduce:
```
/** @test */
public function audio_test()
{
    Storage::fake('public');

    $file = UploadedFile::fake()->create('audio.mp3',3000);

    $object = [
        'audio' => $file
    ];

    $response = $this->postJson($this->endpoint, $object);

    dd($response->getContent());
}
```

Validation:
```
public function rules()
{
    return [
        'audio' => 'required|mimes:mp3'
    ];
}
```
Result:

> The audio must be a file of type: mp3.

EDIT: 

Adding `audio/mpeg` to a list of `mime-types` in the validation fixes the issue. But it seems inconsistent behaviour.

**Comment by Marat555** [comment]
It looks like each browser sends its variation of a mime type for a specific file.
For more info check out this answer on [stackoverflow](https://stackoverflow.com/a/28021591/10303343)

**Comment by X-Coder264** [comment]
@Marat555 What does a browser have to do with this issue? We are talking here about a test that fails and tests do not use browsers, they do internal requests to the app :)

@unlikenesses For a list of valid mime types and to what extension they map check Symfony's `MimeTypeExtensionGuesser`  `$defaultExtensions` array (which is taken from https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types) which Laravel uses under the hood when it performs the `mimes` type validation.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by maxalmonte14** [comment]
Hello everybody 👋, I don't think this is already solved, in fact I just ran into this same problem, it doesn't seem to be a problem related to the browser because a test will throw the same results, I tried this in a Laravel  v5.7.28 application as well as with a new demo application using the latest version of Laravel (v5.8.18).

I made a little demo repo to illustrate the problem, here are the relevant files:

https://github.com/maxalmonte14/laravel-mp3-mime-error-demo/blob/master/app/Http/Requests/StoreFileRequest.php

https://github.com/maxalmonte14/laravel-mp3-mime-error-demo/blob/master/resources/views/files/create.blade.php

https://github.com/maxalmonte14/laravel-mp3-mime-error-demo/blob/master/tests/Feature/FileTest.php

It would be awesome if the root of this behavior could be traced.

Thanks in advance for taking the time to read my comment, I hope you all have a good rest of the day.

**Comment by maxalmonte14** [comment]
Well, it looks like more than a "bug" this is a side effect of Symfony's [MimeTypeGuesser](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php#L628), and replacing `mp3` with `mpga` should work just fine. This seems more like a workaround than an actual solution, it would make more sense if the [Mime type by file extension rule](https://laravel.com/docs/5.8/validation#rule-mimes) could map to the correct mime type with any valid file extension, but since this feature relies on symfony functionality I guess is not possible (or not that easy at least).

Describing this tricky behavior (when a mime type is a valid for more than one file extension only the default one will map to the mime type) in the documentation could be a good way to avoid people getting confussed in the future.
