### ISSUE TITLE
why call to $request->user() in ThrottleRequests middleware

### ISSUE THREAD

**Issue by mhndev** [laravel/framework#25623]
- Laravel Version: 5.7.3
- PHP Version: 7.2.4

### Description:
I implemented my own auth user provider and gaurd,
I got stuck in a situation that every single request which even doesn't have auth middleware is calling my auth class and I understood that when I comment throttle middleware It's ok,
I change my guard class user method not to throw exception just return null if user not exist.
but I believe there is no need to call user in this middleware.
as a laravel user I don't expect such a middleware to has to do something with request user.

**Comment by sisve** [comment]
How would the ThrottleRequests middleware work per-user without querying `$request->user()`?

**Comment by mhndev** [comment]
It could check request is in a life cycle which need authentication.
If I'm on a route which doesn't need user to be authenticated so there shouldn't be any call to user method.
a simple check (check if current request life cycle needs  user to be authenticated) would eliminate the issue.

**Comment by sisve** [comment]
How would such a check be implemented? How would the middleware know if the current request needs authentication?

And how can we be sure this is correct behavior? What if I want to implement a per-user quota, allowing more api calls for authenticated users than for anonymous users? That way we need the method call to check if they are authenticated, but don't require authentication.

I believe I have answered your question why the method is called. I believe you're trying to change another part of the system, the ThrottleRequests middleware, just because you didn't implement your UserProvider contract properly the first time. You're supposed to return null if the user does not exist.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
