### ISSUE TITLE
request()->getClientIp() is returning right-most IP instead of left-most IP.

### ISSUE THREAD

**Issue by andreshg112** [laravel/framework#25684]
- Laravel Version: 5.6.35
- PHP Version: 7.2.5

### Description:
I have logged this in a AWS server.
```json
{
"getOriginalClientIp":"190.9.199.83",
"getClientIp":"70.132.5.137",
"getClientIps":["70.132.5.137","190.9.199.83"],
"x-forwarded-for":"190.9.199.83, 70.132.5.137"
}
```

`getOriginalClientIp()` is a custom function.
`getClientIp` is `request()->getClientIp()`. You can see it is returning the right-most IP in `x-forwarded-for`.
`getClientIps` is `request()->getClientIps()`. You can see is sorting inversely IPs that comes from x-forwarded-for.
`x-forwarded-for` is `request()->header('x-forwarded-for')`. This is the header received from AWS API Gateway.

Custom function:
```php
function getOriginalClientIp(Request $request = null) : string
    {
        $request = $request ?? request();
        $xForwardedFor = $request->header('x-forwarded-for');
        if (empty($xForwardedFor)) {
            // Si está vacío, tome la IP del request.
            $ip = $request->ip();
        } else {
            // Si no, viene de API gateway y se transforma para usar.
            $ips = is_array($xForwardedFor) ? $xForwardedFor : explode(', ', $xForwardedFor);
            $ip = $ips[0];
        }
        return $ip;
    }
```

getClientIp():
```php
/**
     * Returns the client IP address.
     *
     * This method can read the client IP address from the "X-Forwarded-For" header
     * when trusted proxies were set via "setTrustedProxies()". The "X-Forwarded-For"
     * header value is a comma+space separated list of IP addresses, the left-most
     * being the original client, and each successive proxy that passed the request
     * adding the IP address where it received the request from.
     *
     * @return string|null The client IP address
     *
     * @see getClientIps()
     * @see http://en.wikipedia.org/wiki/X-Forwarded-For
     */
    public function getClientIp()
    {
        $ipAddresses = $this->getClientIps();

        return $ipAddresses[0];
    }
```

app/Http/Middleware/TrustedProxies.php:
```php
<?php

namespace App\Http\Middleware;

use Fideloper\Proxy\TrustProxies as Middleware;
use Illuminate\Http\Request;

class TrustedProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies = '**';

    /**
     * The headers that should be used to detect proxies.
     *
     * @var string
     */
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
}
```

I want to use this package https://github.com/antonioribeiro/firewall, but It uses $request->getClientIp(). So I have to make it work in order to use the package.

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/15859884/45700123-5f368400-bb31-11e8-94ef-8e044706b67d.png)

**Comment by staudenmeir** [comment]
Please close the issue.

**Comment by eleracmp** [comment]
I have the same Issue. I think it is a bug.  The header has the format:
X-Forwarded-For: <client>, <proxy1>, <proxy2>
and the name of the method id getClientIp not getMostTrustedIp or getLastProxyIp so, it has to give the client ip. It doesn't matter what people trust.

**Comment by jleonardolemos** [comment]
Sorry about resurrect this issue again.
I have two proxies(1 - Cloudflare, 2 - AWS Load Balancer). What would be the best and secure way to retrieve the real client IP in this scenario???

Is there a easy way to retrieve the client real IP from request()->ip()???
For sure i can do a "smart logic" to realize this but is there a "Laravel Way" for do this?

**Comment by jleonardolemos** [comment]
Just an update from anyone that see this thread in the future.
I was able to solve the problem setting the "preserve mode" attribute for XFF header in my load balancer.
This can be a serious security issue because allow tempering the XFF header then you need to make sure that your load balancer is receiving requests only from the CloudFlare. Just allow only the cloudflare IPS in the LB security group.

**Comment by AlbinoDrought** [comment]
In my opinion, this is a Laravel-specific issue:

- According to [the Laravel "Trusting All Proxies" docs](https://laravel.com/docs/11.x/requests#trusting-all-proxies), use the Laravel `TrustProxies` middleware with the value `*`
- Use a multi-hop `X-Forwarded-For` header like `curl -H "X-Forwarded-For: 1.2.3.4, 5.6.7.8" http://localhost/your/endpoint`
- Access `$request->ip()`
- You'll be given the IP of the proxy, `5.6.7.8`, instead of the IP of the client, `1.2.3.4`

Internally, yes, Laravel uses the Symfony `getClientIp` method. However, this relies on data provided to it by the Laravel `TrustProxies` middleware.

When `*` is the trusted proxy value, the Laravel `TrustProxies` middleware configures the request's IP as the trusted proxy: https://github.com/laravel/framework/blob/eab1e939474458e7faa1f3c2f96a37a9b92b4d1e/src/Illuminate/Http/Middleware/TrustProxies.php#L56-L58

Symfony correctly strips all trusted proxies from the list returned by `getClientIps`. In this case, Symfony has been incorrectly informed by the Laravel `TrustProxies` middleware that the only trusted proxy is the request's IP. Instead, it should be informed that any address is a trusted proxy.

To work around this issue, try setting the trusted proxy value to `0.0.0.0/0,::/0`. All proxies will now be successfully trusted and your calls to `$request->ip()` will return the left-most address in the `X-Forwarded-For` header.

Sample code:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SampleController extends Controller
{
    public function index(Request $request)
    {
        return response()->json([
            'cip' => $request->getClientIp(),
            'cips' => $request->getClientIps(),
            't' => $request->isFromTrustedProxy(),
        ]);
    }
}
```

Before:

```sh
$ curl -H "X-Forwarded-For: 1.2.3.4, 5.6.7.8" http://localhost/your/endpoint
{"cip":"172.21.0.1","cips":["172.21.0.1","5.6.7.8","1.2.3.4"],"t":true}
```

After:

```sh
$ curl -H "X-Forwarded-For: 1.2.3.4, 5.6.7.8" http://localhost/your/endpoint
{"cip":"1.2.3.4","cips":["1.2.3.4"],"t":true}
```
