### ISSUE TITLE
Laravel 5.7 session initially doesn't work as expected when redirecting to multiple pages

### ISSUE THREAD

**Issue by giorgifti** [laravel/framework#25774]
- Laravel Version: v5.7.4
- PHP Version: PHP 7.2.8 (cli) (using docker image: `webdevops/php-nginx:7.2`)
- Database Driver & Version: mysql:5.7 (using docker image: `mysql:5.7`)

#### Application Info & Flow:
I am using SPA with angular for frontend and Laravel for API and authentication.
Basic idea is that I am trying to implement authentication with third party application using SAML. The flow is following: if user is not authenticated on frontend it will redirect to Laravel app, then user is redirected to third party authentication application, from there once user passes authentication the third party application redirects user to my Laravel app and from there I am generating JWT token manually and passing to UI.

#### Issue:
When user is redirected from my SPA to Laravel App (for authentication) it passes tenant name as query parameter, I am handling this parameter by custom middleware, storing that tenant name in session and then using session to retrieve tenant information, but the problem is that if I clear application cookies for Laravel App and then try to go authentication url, it looks like that it creates session and it works until app is redirected to authentication third party application and when I receive call back info to my Laravel application, session doesn’t exist. But once laravel generates cookies and if I try to repeat the same step then everything works…  I have tried exactly the same stuff with PHP’s native session and everything’s working as expected.  Any suggestions/ideas what might be the issue?

I’ve tried web middleware as well but still no luck. This is how my kernel’s middleware array looks like:
```
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Barryvdh\Cors\HandleCors::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\HandleTenancy::class,
    ];
```

### Steps To Reproduce:
Create new laravel application, make middleware that stores some key in session (only with single url). Open laravel application, clear Application -> Cookies, then go to url that redirects to another third party application and when you are getting the callback request back from that third party application check if session with given key still exists. 

 If you try the same steps once you have laravel session information in Application -> Cookies, then you will be able to get given session key from the last step.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Looking at your question - I dont see any problem. If you clear your application cookies on the browser, then you lose your session - that is expected behavior.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by laurencei** [comment]
Laravel needs to set the cookie to store the session, and if you redirect to another page, then the headers&cookie wont be set.

> PHP's native SESSION works normally with exact same steps, that's why I considered this issue as a bug.

Yes - the Laravel sessions intentionally work slightly differently to the PHP session.

I dont think this is a bug - just a limitation of the implementation.
