### ISSUE TITLE
Scheduler taking time to load, task not fired

### ISSUE THREAD

**Issue by danielcharrua** [laravel/framework#25834]
Laravel 5.5
PHP 7.1

I have a strange issue on production server that delays the scheduler so tasks are not fired on time. It seems that for some reason the command `artisan schedule:run` sometimes takes time to load.
If I run `artisan schedule:run` from console, it runs immediately, the issue is when is fired with the cron job.
I have set the cron to fire by 5 minutes instead of all minutes to see more clear.

Cron log:
```
Sep 29 10:05:01 localhost CROND[17311]
Sep 29 10:10:01 localhost CROND[17846]
Sep 29 10:15:01 localhost CROND[18165]
```

Scheduler log:
```
Received ping at Saturday, 29-Sep-2018 10:06:11 EDT 
Received ping at Saturday, 29-Sep-2018 10:10:01 EDT 
Received ping at Saturday, 29-Sep-2018 10:18:55 EDT
```

The only task the scheduler has is a simple closure to measure time, no complex tasks.
```
$schedule->call(function () {
            return true;
        })
        ->everyMinute()
        ->pingBefore('...')
```

Somebody told me this could be a server load issue or clock sync, after running `uptime; sar -q; etc` the results are `10:52:05 up 4:29, 1 user, load average: 0,02, 0,04, 0,05` and clock is on sync.

The real issue is that if I have a task set to run eg at 10:05, it never runs, because the scheduler is loaded at 10:06.

Any ideas?

**Comment by laurencei** [comment]
Just get the cron to run every minute like it was designed. Then you can see if any other issues occur from there?

**Comment by danielcharrua** [comment]
Hi @laurencei the same result is happening when I run the cron every minute, the cron job is on time but not the scheduler. Any ideas of what can be causing this behavior?

**Comment by danielcharrua** [comment]
Hi @laurencei  I have fresh results:

I have discovered that if I execute any artisan command during the "hang up" it takes forever. Lets say you run any artisan command at 16:24 this command is not resolved until  16:27:31 (when the system is "locked out")

I have no more ideas... Have looked in logs and all that but NO CLUE. I think is not Laravel, maybe is a server issue. Server load is really little, is a droplet for a private app with 15 users. Mysql queries are not slow (I have activate the slow query log)

Cron log:

```
Sep 30 16:20:01 localhost CROND[28616]
Sep 30 16:21:01 localhost CROND[854]
Sep 30 16:22:02 localhost CROND[988]
Sep 30 16:23:01 localhost CROND[1062]
Sep 30 16:24:01 localhost CROND[1132]
Sep 30 16:25:01 localhost CROND[1199]
Sep 30 16:26:01 localhost CROND[1255]
Sep 30 16:27:01 localhost CROND[1315]
Sep 30 16:28:01 localhost CROND[1411]
Sep 30 16:29:01 localhost CROND[1508]
Sep 30 16:30:01 localhost CROND[1599]
Sep 30 16:31:01 localhost CROND[1670]
Sep 30 16:32:01 localhost CROND[1742]
Sep 30 16:33:01 localhost CROND[1807]
Sep 30 16:34:01 localhost CROND[1874]
Sep 30 16:35:01 localhost CROND[1936]
Sep 30 16:36:01 localhost CROND[1995]
Sep 30 16:37:01 localhost CROND[2062]
```

Scheduler log:

```
2018-09-30 16:20:12] production.INFO: schedule call  
[2018-09-30 16:21:01] production.INFO: schedule call  
[2018-09-30 16:22:02] production.INFO: schedule call  
[2018-09-30 16:23:01] production.INFO: schedule call  
[2018-09-30 16:27:31] production.INFO: schedule call  
[2018-09-30 16:27:31] production.INFO: schedule call  
[2018-09-30 16:27:31] production.INFO: schedule call  
[2018-09-30 16:27:31] production.INFO: schedule call  
[2018-09-30 16:28:01] production.INFO: schedule call  
[2018-09-30 16:29:01] production.INFO: schedule call  
[2018-09-30 16:30:01] production.INFO: schedule call  
[2018-09-30 16:31:01] production.INFO: schedule call  
[2018-09-30 16:32:02] production.INFO: schedule call  
[2018-09-30 16:33:01] production.INFO: schedule call  
[2018-09-30 16:37:53] production.INFO: schedule call  
[2018-09-30 16:37:53] production.INFO: schedule call  
[2018-09-30 16:37:53] production.INFO: schedule call  
[2018-09-30 16:37:53] production.INFO: schedule call  
```

**Comment by mfn** [comment]
I'm experiencing the same issue on our system. Here's a screenshot of hourly generated emails which actually do contain the time the jobs were started in the subject:
![image](https://user-images.githubusercontent.com/87493/46262702-35a03400-c505-11e8-9a70-d3686954f633.png)
- at 04:00 no job was started
- but the system did not forget about it, it was held back
- ran it the next iteration together with the current iterations job

or another example, because for every scheduler job we track start/end time (to discover exactly such or other things):
![image](https://user-images.githubusercontent.com/87493/46262738-c4ad4c00-c505-11e8-8e70-5483e007f87c.png)




> I have discovered that if I execute any artisan command during the "hang up" it takes forever. Lets say you run any artisan command at 16:24 this command is not resolved until 16:27:31 (when the system is "locked out")

That's a very interesting observation. I've never dug much into the issue on our side (as it practice it's not a problem), thus never created an issue here. But this seems a perfect match.

In my case I can't rule out other artisan commands are running. But I can rule out someone is calling them _manually_. So anything running is something automated (cron, queue).

Is there any kind of locking ongoing (did I brief source grep of Laravel console, found nothing)?

**Comment by mfn** [comment]
The emails/screenshots above are from some time ago from our system but I just looked into the current data I've which is on Laravel 5.7 and it's still there; so it's also not a 5.5/5.6 specific issue:
![image](https://user-images.githubusercontent.com/87493/46262795-8fedc480-c506-11e8-9121-b029f492b498.png)

**Comment by laurencei** [comment]
Hey @mfn @danielcharrua - this is still not a framework issue. It is something with your server and your setup.

The only other thing it could be is if you are using `withoutOverlapping()`, `onOneServer()` or you are running other cron tasks and they are hogging the system first.

Laravel does no other locking. However - an incorrectly configured server would easily cause the issue above (not enough FPM resources, network issue etc etc).

But ultimately I think you'll find the issue is not anything to do with the code in Laravel...

**Comment by mfn** [comment]
Thanks for your feedback. That's the reason I didn't report it before. I can't pinpoint this anywhere; at all.

> The only other thing it could be is if you are using withoutOverlapping(), onOneServer() or you are running other cron tasks and they are hogging the system first.

We're not using this feature.

> an incorrectly configured server would easily cause the issue above (not enough FPM resources, network issue etc etc).

In this case, the server does not run nginx or fpm => it's only for background jobs, so it runs cron, redis and PHP (but it also runs other non-Laravel PHP parts, too).

**Comment by laurencei** [comment]
Is it always at 04:00 that skips? Do you run any other schedules, they will run chronongical unless you are running them in background

**Comment by danielcharrua** [comment]
In my case it skips randomly, not always at the same time. I do not run any other schedules. My setup is CentOS 7.4 x64, 1vcpu, 2gbRAM, using Plesk and PHP-FPM 7.1.
I undersand at this point that this is no framework related and more of a server fault/issue as you said.

**Comment by mfn** [comment]
> Is it always at 04:00 that skips? Do you run any other schedules, they will run chronongical unless you are running them in background

Ops. Thanks for actually doing my job, but yes, there's another job running at that time.

> they will run chronongical unless you are running them in background

Hmm .. well, now I'm not sure I understand
- all the jobs I'm talking about are managed via `App\Console\Kernel::schedule`
- one runs every hour and finishes in a few minutes
- the other only runs at 04:00 and may take _hours_ to complete
- it's using laravels scheduling, e.g. `* * * * * …/artisan schedulerun`

TBH I wans't really aware that jobs are run within the same process/structure (?) so multiple jobs hitting at the same time are sequentially executed? (I thought forking is going on but TBH I never checked)

**Comment by mfn** [comment]
Yep, confirmed: any jobs being eligible by the scheduler to run are run sequential. That means jobs that take longer will skew other jobs destined to run at the same minute.

Maybe I should have known this, but coming from a background using cron for years this is unexpected. Due to forking it's background jobs, cron cannot have this issue.

For now we fixed it by changing the time of one particular long running job to run when no other scheduled job will hit.

Obviously this doesn't scale well: if you've many jobs, it becomes hard to figure out when's the right time and it's easy to make errors.

The way I see it these are the current other practical fixes:
- using the scheduler: use a background job
  downside: have to add extra code to track running time of job
- don't use the Laravel scheduler for such jobs but create separate cron entries
  downside: have to add extra code to track running time of job, extra work for deployment

**Comment by laurencei** [comment]
Just use `->runInBackground()` to fork the process
