### ISSUE TITLE
 symfony/process should be required by \Illuminate\Support

### ISSUE THREAD

**Issue by scottconnerly** [laravel/framework#26110]
- Laravel Version: 5.7
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
symfony/process is required by \Illuminate\Support\Composer::getProcess() yet it is not required by Illuminate/Support/composer.json 

### Steps To Reproduce:
Attempt to re-use the Database subtree split to manage migrations. When executing the make:migration command, (aka MigrateMakeCommand), the dependency is called out.

**Comment by laurencei** [comment]
ping @GrahamCampbell - your the expert at this stuff. Thoughts?

**Comment by laurencei** [comment]
ping @GrahamCampbell - your the expert at this stuff. Thoughts?

**Comment by laurencei** [comment]
@scottconnerly - I checked - and it's already listed there?

https://github.com/laravel/framework/blob/c3b7a12f36b3eec1bdd7633c61a2dc1b7d6043f3/src/Illuminate/Support/composer.json#L43

**Comment by laurencei** [comment]
Arh. Ok.

I’ll fix it when I get home shortly.



On 20 Oct 2018, at 1:27 am, Scott Connerly <notifications@github.com> wrote:

Its "suggested". It should be "required"

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/issues/26110#issuecomment-431381388>,
or mute the thread

**Comment by deleugpn** [comment]
That's the whole point of suggest. Illuminate\Support is used A LOT by people that don't need the `Composer` class. If you require support to use, say, collection, then you don't need it.
It should not install Symfony Process by default

**Comment by devcircus** [comment]
Definitely should be in "suggest". That's the purpose of "suggest". No change needed.
