### ISSUE TITLE
'sometimes' and 'required_with' validation rule not working in array

### ISSUE THREAD

**Issue by range-of-motion** [laravel/framework#26179]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:

In my app I'd like users to be able to import data. To facilitate this I built a form with multiple rows. Each row has inputs for the data as well as a checkbox. If checked, the row gets imported. If not, it gets ignored.

Unchecked rows don't get imported. Therefor it's desired not to validate the row if the checkbox is unchecked. To make this happen I use `sometimes|required_with:rows.*.import`. This should stop validating the data in that row if the checkbox (named import) isn't checked.

The issue is that the row attempts to be validated even when the checkbox is left unchecked.

### Steps To Reproduce:

**Step 1 - Have a form**

```
@foreach ($errors->all() as $error)
    {{ $error }}
@endforeach
<form method="POST">
    {{ csrf_field() }}
    <div>
        <input type="checkbox" name="rows[0][import]" />
        <input type="text" name="rows[0][data]" value="This is not an integer" />
    </div>
    <div>
        <input type="checkbox" name="rows[1][import]" />
        <input type="text" name="rows[1][data]" value="This is also not an integer" />
    </div>
    <button>Submit</button>
</form>
```

**Step 2 - Validate**

```
$request->validate([
    'rows.*.data' => 'sometimes|required_with:rows.*.import|integer'
]);
```

**Step 3 - Try**

As you can see, despite leaving the checkbox unchecked, you will still receive an error about the data input not being an integer.

**Comment by MHoMartirosyan** [comment]
@wuwx

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by staudenmeir** [comment]
@driesvints This is a valid bug, please reopen.

**Comment by driesvints** [comment]
Okay. It seemed like this has something to do with formatting your rules properly. So I wanted to check if it could first be proven that it was an actual validation bug.

**Comment by donnysim** [comment]
From my point of view this is not a bug.

`sometimes` rule executes when the field is present - in this case `data` is always present so it will always validate it. The `required_with:rows.*.import` does not stop it from validating further, it just checks if the field exists and then checks if the value is not null or present, which further leaves the `number` validation, because the field exists and it is not a number, it fails.

**Comment by reinink** [comment]
So, my inclination would be to treat the `required_*` rules the same with `sometimes` as it currently does with `nullable`, which is to still perform that validation rule. Consider this example:

```php
'country' => ['sometimes', 'nullable', 'required_with:region', new Country()],
'region' => ['sometimes', 'nullable', new Region(Request::get('country'))],
```

This is a real validation situation I have in my app. I have two custom validation rules, `Country` and `Region`, which work together to verify that the correct country and regions are being set. For example, if you choose "Canada" as the country, then the region must be a valid Canadian province. Note that a country can be set without a region, but a region cannot be set without a country.

The `sometimes` "rule" is helpful when doing patch requests, because it allows you to only validate the fields that are present. However I'd argue that in situations where a field is referenced in a `required_*` rule, those columns should no longer respect the "sometimes" option, since they are intended to be validated together.

**Comment by themsaid** [comment]
Hey everyone. This is not a bug, `sometimes` with `required_with` won't stop the `integer` or any other rule from running.

**Comment by taylorotwell** [comment]
I'm not sure a slick way to achieve this with validation rules only at the moment. However, you can always massage your data a bit before sending it to the validator:

```php
    $data = request()->all();

    $data['rows'] = collect($data['rows'])->filter(function ($row) {
        return ($row['import'] ?? null) == 'on';
    })->all();

    $validator = Validator::make($data, [
        'rows.*.data' => 'sometimes|bail|required_with:rows.*.import|integer'
    ])->validate();
```

**Comment by taylorotwell** [comment]
For future reference, the answer to @reinink's problem is simply to remove "sometimes". It is unneeded in that scenario.

**Comment by reinink** [comment]
🤦
