### ISSUE TITLE
Env does not assign a default value

### ISSUE THREAD

**Issue by DmitrySkibitsky** [laravel/framework#26190]
- Laravel Version: 5.7.9
- PHP Version: 7.2.11

### Description:
Env does not assign a default value

script
```php
        \App\Providers\AppServiceProvider::boot

        $name_company = Setting::getItem('name_company')->value; //line 33
        dump($name_company); //line 34
        env('APP_NAME', $name_company); //line 35
        dump(env('APP_NAME')); //line 36
```
dump

```log
 -------- -------------------------------------- 
  date     Fri, 19 Oct 2018 14:56:29 +0000       
  source   AppServiceProvider.php on line 34     
  file     app/Providers/AppServiceProvider.php  
 -------- -------------------------------------- 

"Dentel Laboratory"

 -------- -------------------------------------- 
  date     Fri, 19 Oct 2018 14:56:29 +0000       
  source   AppServiceProvider.php on line 36     
  file     app/Providers/AppServiceProvider.php  
 -------- -------------------------------------- 

"Laravel"

```

**Comment by staudenmeir** [comment]
`env()` can only get environment variables, but not set them.

**Comment by X-Coder264** [comment]
Of course `env` does not assign anything. The second parameter of `env` is the default value that `env` is gonna return if the `env` variable that is requested does not exist.

btw, you should not use the `env` function outside of your config files as you won't be able to cache your config in production (because all `env` calls outside of the config files will return `null`).

**Comment by DmitrySkibitsky** [comment]
@staudenmeir , @X-Coder264  thanks

**Comment by staudenmeir** [comment]
Please close the issue.

**Comment by DmitrySkibitsky** [comment]
Pass the value through view()->composer()
