### ISSUE TITLE
PivotModel: pivotParent attributes are empty if using eager loading.

### ISSUE THREAD

**Issue by bastian-schur** [laravel/framework#26237]
- Laravel Version: 5.7.10
- PHP Version: 7.2.10
- Database Driver & Version: Mysql 5.7.23

### Description:
I have two basic models with a belongsToMany Relation ( Order and Article ). Now i created a Pivot Model OrderArticle. In this PivotModel i can use the pivotParent property to get the order where i have started. It all works fine. If i now enable eager loading, the pivotParent returns a Order Model, but the attributes property is empty.

### Steps To Reproduce:
1) Create two models Order and Article.
2) Order has a belongsToMany Relation to Article with using OrderArticle Pivot Model
3) Create a function in OrderArticle Model which return "$this->pivotParent->id"

This example works, an dumps 1:
>foreach ( Order::find( 1 )->articles as $article ) {
>   dump( $article->pivot->a_pivot_model_function_returns_pivotParent_id() );
 >}

This example works not, an dumps null:
>foreach ( Order::with( 'articles' )->find( 1 )->articles as $article ) {
>  dump( $article->pivot->a_pivot_model_function_returns_pivotParent_id() );
>}

**Comment by eemrekaya** [comment]
Did u try?

```php
foreach ($order = Order::with('articles')->find(1) as $order->articles) {
    //
}
```

**Comment by staudenmeir** [comment]
Please post the relationship and the pivot model.

Is the result of `dump( $article->pivot);` different in the second example?

**Comment by bastian-schur** [comment]
Here are the code snippets:

**Order.php**
```
public function articles()
        {
            return $this->belongsToMany( Article::class , 'order_articles' )
                ->withPivot( 'amount' , 'additional_amount' , 'amount_done' , 'status' )->using( OrderArticle::class );
        }
```

**OrderArticle.php**
```
class OrderArticle extends Illuminate\Database\Eloquent\Relations\Pivot
    {
        private function a_pivot_model_function_returns_pivotParent_id()
        {
            return $this->pivotParent->id;
        }
    }
```

@staudenmeir : Yeah the results of `dump( $article->pivot);` are different. But the only difference i can see, is that the `dump( $article->pivot->pivotParent);` property has no attributes when using eager loading. It's very confusing to see an empty model! And this is not only an "new Order()" Object, becaus the "exists" property in this model is in both examples true!

**Comment by staudenmeir** [comment]
I can reproduce this, but I don't see a simple way to fix it.

I'm also not sure whether the `pivotParent` property is even supposed to be used like this.
I would suggest that you pass the parent to the method:

```php
$order = Order::find(1);
foreach ($order->articles as $article) {
    $article->pivot->a_pivot_model_function_returns_pivotParent_id($order));
}
```

**Comment by bastian-schur** [comment]
Of course, this would be a possibility that I already thought of. But in my opinion this is a complicated way to use it with the base model every time. The pivotParent is exactly for this case, it just does not work with EagerLoading.

Can you describe it in more detail, where exactly this error occurs?

**Comment by staudenmeir** [comment]
Taylor doesn't (normally) respond to pings.

I'm pretty sure it's not meant for cases like this. Laravel only uses the `pivotParent` model to get the timestamp columns. For this, an empty model is sufficient.

It doesn't work with eager loading because Laravel initializes the relationship with an empty model.

**Comment by fitztrev** [comment]
I've run into this same issue, though in a different way.

I have a User MorphToMany Roles. My User model has an appended attribute:

```php
class User extends Eloquent
{
    protected $appends = ['permalink'];

    public function getPermalinkAttribute()
    {
        return route('profile', $this->username);
    }
}
```

When `pivotParent` is an empty `User` model, `$this->username` is `NULL` which is an invalid argument for my `/profile/{username}` route.

In my specific case, I'm using Clockwork which adds middleware that `->toArray()`'s the entire object. `->toArray()` tries to add the appended data, which triggers the error.

So there are a few things at play that all contribute:

1. Having a pivot relationship that is eager loaded
2. Having an appended attribute that relies on the Model existing
3. Calling `->toArray()` (because of Clockwork logging in my case) on the entire object which tries to add the appended accessors

**Comment by taylorotwell** [comment]
The `pivotParent` property was not really designed to be user facing construct and making it work with eager loading would be quite complicated. It is not documented as a feature of the framework.
