### ISSUE TITLE
BUG whereIn When PK != integer [HELP]

### ISSUE THREAD

**Issue by jffsx** [laravel/framework#26603]
- Laravel Version: 5.7.14
- PHP Version: 7.1
- Database Driver & Version: PostgreSql

### Description:

Hi guys,

I am developing a project where the requesting company asked for the table identifiers to be uuid (as much as I did not agree), so in my models I configured it like this

```
/ **
  * Indicates if the IDs are auto-incrementing.
  *
  * @var bool
  * /
public $ incrementing = false;
```

```
/ **
  * Boot uuid.
  *
  * @return void
  * /
public static function bootUuid ()
{
     static :: creating (function ($ model) {
         $ model -> {$ model-> getKeyName ()} = (string) Str :: uuid ();
     });
}

```

This worked until version 5.7.13, but now in 5.7.14 is giving the error

`SQLSTATE [42883]: Undefined function: 7 ERROR: operator does not exist: uuid = integer`

How can I get around this?

Thank you

**Comment by CrixuAMG** [comment]
I just tried the same, but using a mysql database instead of PostgreSql, and it ran successfully. 
A quick google resulted in the following page:

https://stackoverflow.com/questions/46433459/postgres-select-where-the-where-is-uuid-or-string

In the stackoverflow page they stated casting the column to uuid helped: `uuid::uuid`

**Comment by jffsx** [comment]
@CrixuAMG, 

But because in the version of laravel 5.7.13 it works normally and in version 5.7.14 it does not? Would it be a database error?

**Comment by bonzai** [comment]
#26582

**Comment by jffsx** [comment]
@bonzai, wow!

Thank you very much guy.
