### ISSUE TITLE
Make JsonResource Macroable

### ISSUE THREAD

**Issue by hassanzohdy** [laravel/framework#26618]
Hello,

I'm suggesting that `Illuminate\Http\Resources\Json\JsonResource` class should be `Macroable`.

The use case that i'm facing that led me propose this feature is that some data in many resources need to be adjusted in similar way so instead of creating another base `JsonResource` class the `Macroable` trait would make it much easier.

For example i've **price** property in few resources which i want to format all prices + adding the currency code beside the formatted price.

**Comment by CrixuAMG** [comment]
You could also (for now) put the methods in a trait, then apply the trait to the models and call `$this->resource->[METHOD_NAME]();`

**Comment by peterfox** [comment]
Sounds like an odd use case to use macros for. Sounds like you're better off making your own price formatting helper class or simply a global function. Macros are more for extending the functionality of the thing you use.

Worse case you should probably just make a trait and add it to the resources where you need it (or the model like @CrixuAMG mentioned) rather than adding a macro.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
