### ISSUE TITLE
moveDirectory with overwrite option deletes target even if source doesn't exists.

### ISSUE THREAD

**Issue by FelipeeDev** [laravel/framework#26682]
I've notice that while usuing:

`\Illuminate\Filesystem\Filesystem::moveDirectory`

method with overwrite option - the target directory can be deleted (if it exists) even if the source directory doesn't exists. I think this is not natural behavior - because as the intention: we want to overwrite "directory" and not empty value with directory - so it's more like delete behaviour.

**Comment by driesvints** [comment]
Hmm, I see what you mean. But since this is the default behavior of the `rename` function of PHP I don't necessarily believe this is totally unexpected. If you want to change the behavior of this function it's best to open an issue at [laravel/ideas](https://github.com/laravel/ideas) to see if others feel the same.
