### ISSUE TITLE
Base model is overwritten by intermediate table (morphedByMany) when executing get() on the EloquentQuery

### ISSUE THREAD

**Issue by phillipfickl** [laravel/framework#26928]
- Laravel Version: 5.7.19
- PHP Version: 7.2.11
- Database Driver & Version: mysqlnd 5.0.12

### Description:
When connecting two models with a Many To Many (Polymorphic) relationship, normally querying related models is not a problem. 
Take the following as an example:
_A user can manage many flats and/or many properties.
And a flat/property can be managed by many users._

A simple _$user->flats()->get()_ would get you a collection of Eloquent Flat-Models with the pivot table included as a 'pivot' (MorphPivot) object. So far so good.
![image](https://user-images.githubusercontent.com/1156835/50296046-7444eb00-0471-11e9-8418-0692eb8a5929.png)

But if you run _$user->flats()->getQuery()->get()_ (for instance to pass the base query to Spaties QueryBuilder), Laravel merges the attributes of pivot table into the base model, without a _pivot__ prefix.
![image](https://user-images.githubusercontent.com/1156835/50296095-8aeb4200-0471-11e9-919d-62f2c466e771.png)
This is especially bad because of the id that gets overwritten (see how the flat got id '5' now)

If this is for the same reason as https://github.com/laravel/framework/issues/20805 and https://github.com/laravel/framework/issues/23548 - then it should at least be documented somewhere.

If you need sample code to reproduce the issue: https://github.com/phillipfickl/laravel-getquery-bug

Let me know if you need more information, or if this works as designed in your opinion.

**Comment by staudenmeir** [comment]
This is the expected behavior. `->getQuery()->get()` calls [`Builder::get()`](https://github.com/laravel/framework/blob/ab50ddc42ce8177cbce03d43cbe22b7f9445326e/src/Illuminate/Database/Eloquent/Builder.php#L493) which doesn't know anything about the relationship and just executes the query. 

The pivot relation can only be hydrated by calling `BelongsToMany::get()`. For the same reason, methods like `chunk()` and `paginate()` have their own implementations in the `BelongsToMany` class.

It's not related to #20805 and #23548.

**Comment by phillipfickl** [comment]
Alright, thanks for explaining!
