### ISSUE TITLE
Email verification 403 invalid signature.

### ISSUE THREAD

**Issue by lperry65** [laravel/framework#26930]
When clicking in the "Verify Email Address" button in the verify email, I get the following error when using either Sendgrid or AWS SES: 

403
Invalid signature.

 GO HOME

However, when i test in Mailtrap it works and the email address is verified!

**Comment by driesvints** [comment]
Hmm, I think it's probably related to some misconfiguration. I've already used this with SES. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Claud** [comment]
I have the same problem. laravel version v5.7.19

**Comment by lperry65** [comment]
@Claud  I fixed the issue by changing the APP_URL to match the domain the request is coming in on, obviously you need to config:cache etc.

Hope this helps :)

**Comment by lmj0011** [comment]
> I fixed the issue by changing the APP_URL to match the domain the request is coming in on, obviously you need to config:cache etc.

Wow, took me a few hours to stumble on this

**Comment by driesvints** [comment]
@lmj0011 sure, send in a PR

**Comment by freeman3s** [comment]
The same problem in Laravel 5.8.10

> @Claud I fixed the issue by changing the APP_URL to match the domain the request is coming in on, obviously you need to config:cache etc.
> 
> Hope this helps :)

This doesn't help(

**Comment by Zontir** [comment]
I have the same problem. I made the request from postman for an api route, and I'm going in to check the email by browser.
Would I have any conflicts if I did so? The above solution did not solve my problem either.

**Comment by olivernybroe** [comment]
For me the problem was that I had enabled `valet secure`, so all my url's were changed to https. It was still signing the url's with http, so of course it wasn't valid when it checked with a url from https.

**Comment by kaxias** [comment]
this continues happened on laravel 5.8.31 if time expires you got error 403.

**Comment by GIVasco** [comment]
Hello, i'm working on Laravel 5.8.15 and i have the same error ! 

I did set the .env file
APP_ENV=production
APP_URL=https://domain.co/
APP_USE_HTTPS=true

in the AppServiceProvider
public function boot(UrlGenerator $url)
    {
        URL::forceScheme('https');
    }

In web.php and api.php
if (App::environment('production')) {
    URL::forceScheme('https');
}

and in the TrustProxies file 
protected $proxies = '*';

but I still getting the same error (403 | Invalid signature.) on the email verification!
someone can helpme ?

**Comment by dhrumil4u360** [comment]
This issue is mainly introduced by adding following in your code,

`URL::forceScheme('https');`

If you are just trying to fix SSL URL links (When SSL is terminated in your load balancer & laravel server is receiving requests on port 80), you should not above approach. Instead, use approach given by Laravel. It will take care of exact this scenario.

https://laravel.com/docs/6.x/requests#configuring-trusted-proxies

If you have to have `forceShceme` anyway, make sure you configure `TrustedProxies`

**Comment by syedskspgon** [comment]
same issue faced..but i solved it by commenting few lines in "VerificationController" 

public function __construct()
    {
       // $this->middleware('signed')->only('verify');
       // $this->middleware('throttle:6,1')->only('verify', 'resend');
    }

I hope this will works.
i think, it mainly disabling email expiry time

**Comment by pathros** [comment]
It's 2020 and I still get the same problem on production with Laradock.

I have applied several times 

`$ php artisan key:generate`

I have updated my .env file at `APP_URL` to match the https://my-domain.com, which works well, since right at mailtrap, the email verify URL matches perfectly the domain. 

So then why do I still get that 403 invalid signature error?

I tried `URL::forceScheme('https');` and it didn't work. I don't feel like trying `TrustedProxies`. Will it actually work?

Does clear cache work?

Does anybody know how to fix this?

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
