### ISSUE TITLE
ErrorBag content lost after FormRequest redirect

### ISSUE THREAD

**Issue by pastebimas** [laravel/framework#27032]
Hi,

If I use my own custom FormRequest with validation there, if data is not valid, redirect back is made by FormRequest itself, and after rendering page with 200 status, errors bag from session is cleared and I can't display corresponding error messages in the view.

https://stackoverflow.com/questions/54005142/laravel-requests-validation-loose-errors-on-redirect

**Comment by driesvints** [comment]
I think there's something wrongly configured in this case because you should have access to your errors after a validation redirect from a request class. Can you try a few more places besides StackOverflow? Particularly the Laracasts forums will probably provide some help for you.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by pastebimas** [comment]
Wrapping everything in routes/web.php to "Route::group(['middleware' => ['web']], function () {" fixed the issue. But shouldn't everything in web.php file be assigned to "WEB" middleware? 

app/Providers/RouteServiceProvider.php I see, that it is already named as "web". 
Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));

Is it really OK that I have to wrap all my routes?

**Comment by devcircus** [comment]
Can you possibly reproduce on a fresh app and push to github so we could take a look. You definitely shouldn't have to add the "web" middleware to your web.php routes. The service provider takes care of that.
