### ISSUE TITLE
Phpunit when visiting same endpoint twice controller __construct called once

### ISSUE THREAD

**Issue by if4lcon** [laravel/framework#27060]
- Laravel Version: 5.7.19
- PHP Version: 7.2.8
- Database Driver & Version: sqllite

### Description:
When using phpunit to test an endpoint calling a url twice to make some assertions __construct in the controller will be called only once . While in the browser not having this issue

**Comment by SjorsO** [comment]
I've had this problem in the past too.

**Comment by X-Coder264** [comment]
@mfn Where has it been noted that constructor injection should be avoided? If anything the complete opposite should be true - constructor injection should be the only way to specify the required dependencies (with the exception of the request as that's basically only a value object).

The thing that should be avoided at all costs is writing a test which makes multiple requests as the framework gets booted only once per test meaning such a test doesn't reflect the real way the app would work if the request was made via a browser. Doing multiple requests per test is a good indicator that the test is testing more than one thing (which it shouldn't do) and that the test should be split in smaller tests with each of them having its own proper "arrange" step.

**Comment by SjorsO** [comment]
Like @X-Coder264 said, this seems to only happen when you do two requests in one test method. The tests in the example below pass when you only do a single request in each test method.

**Route:**
```php
Route::get('constructor/{text}', ['uses' => 'ConstructorController@index', 'as' => 'constructor']);
```

**Controller:**
```php
class ConstructorController
{
    protected $value;

    public function __construct(Request $request)
    {
        $this->value = $request->segment(2);
    }

    public function index()
    {
        return $this->value;
    }
}
```

**Test:**
```php
/** @test */
function it_constructs_the_controller_twice()
{
    $this->get(route('constructor', 'FirstTest'))
        ->assertStatus(200)
        ->assertSee('FirstTest');

    $this->get(route('constructor', 'SecondTest'))
        ->assertStatus(200)
        ->assertSee('SecondTest');
}
```

This tests fails because the constructor only gets called once:
![image](https://user-images.githubusercontent.com/7202674/50680210-25698a80-1007-11e9-9782-27ea2e0f072e.png)


Being able to do multiple requests in a single test method is convenient. The only time i've had any problems with this was when i had conditional logic in the controllers constructor. 

Is there a way this could be fixed?

**Comment by if4lcon** [comment]
@X-Coder264 I thought that too I already did a split. it would be nice if we find a permanent solution . thanks for supporting __construct

**Comment by driesvints** [comment]
Please use separate test methods when testing route calls. There isn't any guarantee that tests will pass if you use double calls in a single test.

**Comment by X-Coder264** [comment]
> Being able to do multiple requests in a single test method is convenient. The only time i've had any problems with this was when i had conditional logic in the controllers constructor.
Is there a way this could be fixed?

@SjorsO  It's not "convenient", it's just simply wrong, as you are putting the application in a state that cannot exist in a real word scenario (and in doing so a test that should pass can potentially fail or vice versa which is really bad). And I think it should be "fixed" yes, but by "fixing" it I mean throw an exception the second time somebody calls that in the same test.

**Comment by mfn** [comment]
@X-Coder264 
> Where has it been noted that constructor injection should be avoided? If anything the complete opposite should be true - constructor injection should be the only way to specify the required dependencies (with the exception of the request as that's basically only a value object).

Thanks, you're totally right! My generalization was actually meant about the `Request` which is irrelevant in this context.

**Comment by X-Coder264** [comment]
If you know how the framework is being booted you'd understand that the only flaw here is that the exception should've been raised from the very start so that such tests couldn't be written in the first place and in doing so ensuring that issues such as this one wouldn't be opened here on the issue tracker.

Your test should mimic the behavior of a real HTTP request coming to the app. If the framework allows to write a test which does something that can't happen in a production scenario then it means that there is something wrong (in this case that an exception isn't being thrown to inform the developer that he shouldn't be doing what he just did).

Just because you don't wanna split every route call in a separate tests doesn't mean that the framework should somehow magically be forced to do something that can't even happen in a real world scenario.

If the concern here is code duplication, you can easily put the common part of the test in a private method which would be called in each test before (or after) the route call is being made thus solving the problem. Forcing the framework to do something unnatural just because you want it to work that way would be very weird.

**Comment by mfn** [comment]
> real world scenario

I wonder how that scenario looks like if you're using technologies like swoole or php-react? In that case, the framework a) only boots once but b) serves multiple requests.

I haven't looked at the code so I don't know what would be different to that and what would need to happen in-between two simulated requests in a test to emulate this behaviour to still create "request boundaries".
