### ISSUE TITLE
logoutOtherDevices only work on default guard

### ISSUE THREAD

**Issue by kiendaotac** [laravel/framework#27125]
- Laravel Version: 5.7.20
- PHP Version: 7.2.12
- Database Driver & Version:

### Description:
I can logout other devices but it only work on default guard. When i change default guard, it work correctly.

### Steps To Reproduce:
- create new guard and admin table.
- use logoutOtherDevices on new guard ( it not work ).
- change default guard to new guard and use logoutOtherDevices on default guard ( it work) but still not work on web guard ( not a default guard)

**Comment by ahinkle** [comment]
Can you give us some more context with code examples if this is an issue/bug with the framework itself? 

If this is not an issue or bug with the framework, there are many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by menkaff** [comment]
it is not working in laravel 5.7 
` Auth::logoutOtherDevices($data['password'], 'password');` 
and 
` Auth::guard('web')->logoutOtherDevices($data['password'], 'password');` 
are ok but below code is not working
` Auth::guard('custom')->logoutOtherDevices($data['password'], 'password');`

@driesvints i can't find any solution or asked question on forums or stack over flow and i test it with Auth::attempt or Auth::loginUsingId but not working

and the i comment this in middlewareGroups **AuthenticateSession** 
and use web middelware in all routes but not working with custom guard
to solve this problem i used [this answer](https://stackoverflow.com/questions/19510220/single-session-login-in-laravel)

**Comment by ameerbjs** [comment]
From my side also is not working in laravel 5.7 

I have implement with different variations but can't work , Please suggest me any solution thank you

**Comment by ameerbjs** [comment]
> it is not working in laravel 5.7
> ` Auth::logoutOtherDevices($data['password'], 'password');`
> and
> ` Auth::guard('web')->logoutOtherDevices($data['password'], 'password');`
> are ok but below code is not working
> ` Auth::guard('custom')->logoutOtherDevices($data['password'], 'password');`
> 
> @driesvints i can't find any solution or asked question on forums or stackoverflow and i test it with Auth::attempt or Auth::loginUsingId but not working
> 
> and i also uncomment this in middlewareGroups **AuthenticateSession**
> and use web middelware in all routes but not working with custom guard
> to solve this problem i used [this answer](https://stackoverflow.com/questions/19510220/single-session-login-in-laravel)

**Comment by evanstinger** [comment]
I'm using Laravel 7.x and 8.x, can confirm this method didn't work on custom guard, only on default (web) guard.
This is annoying, tbh.

**Comment by ghbob** [comment]
I ran into this issue as well, the "problem" seems to lie with the `AuthenticateSession` middleware (which needs to be active for `logoutOtherDevices` to work):
It works fine when the `defaultDriver` is set to the guard one wants to use.
e.g. `Auth::setDefaultDriver('customguard');` in the `__construct()` of the controller in use.
Another solution I could find is a custom middleware that simply does this as well ([e.g. here](https://stackoverflow.com/questions/49071605/setting-the-default-guard-on-a-route-group)).

Since some other middleware work this way (e.g. `Authenticate` with [...guards](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/Middleware/Authenticate.php#L40)), maybe it would be a good solution to pass the wanted guard as a parameter? Like `auth.session:customguard` - if I find the time I'll try to right a proper feature request.

Now I am having the issue that I can't control where the logged out sessions are forwarded to, it throws a `AuthenticationException` which (I think) always defaults to `redirectTo=null` ([here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/AuthenticationException.php#L31) and [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Exceptions/Handler.php#L461)) and therefore the fallback named route: login, so nothing guard specific here.

I was browsing the changes for the AuthenticateSession and this commit (https://github.com/illuminate/session/commit/661d81b72fa13c9ecaa89c521ab83fe176baf2f9) states:
> Added guard name for handling redirection.

But I couldn't figure out how it would?
The `AuthenticationException` would take a third parameter for the redirect target.
