### ISSUE TITLE
Misspelling "nullable" in a migration doesn't raise an exception

### ISSUE THREAD

**Issue by Stokoe0990** [laravel/framework#27140]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7.23-0ubuntu0.18.04.1

### Description:
This was highlighted by a colleague of mine and upon testing in my environment, I found it to misbehave too. (He runs Windows, I'm on Mac with Homestead).

In a database migration, if you misspell "nullable" and run your migrations, the migration WONT fail, will not show any errors and will not mark the field nullable.

### Steps To Reproduce:
See above.

![screenshot 2019-01-11 at 14 12 53](https://user-images.githubusercontent.com/2981213/51038418-16f11500-15ab-11e9-9f36-2a6f6a6d74c0.png)

<img width="374" alt="screenshot 2019-01-11 at 14 13 12" src="https://user-images.githubusercontent.com/2981213/51038417-16f11500-15ab-11e9-8ac0-5f041694777a.png">

<img width="845" alt="screenshot 2019-01-11 at 14 13 23" src="https://user-images.githubusercontent.com/2981213/51038416-16f11500-15ab-11e9-97ae-318b65188819.png">

**Comment by staudenmeir** [comment]
This is basically the expected behavior.

Column modifiers like `nullable()` are implemented using the [`Fluent`](https://github.com/laravel/framework/blob/d0e1331227e8acd68177760d85b4bac399bef757/src/Illuminate/Support/Fluent.php) class. There is no list of valid values, the migrations just check for particular attributes. If the column has a `nullable()` modifier, the column will be adjusted. So if the column has an invalid/unknown modifier, nothing happens.

**Comment by driesvints** [comment]
This is indeed expected behavior from the `Fluent` class.
