### ISSUE TITLE
`Illuminate\Cache\Repository#put()` type signature incompatible with `Illuminate\Support\InteractsWithTime#parseDateInterval()` leads to unexpected results

### ISSUE THREAD

**Issue by Ocramius** [laravel/framework#27160]
- Laravel Version: `master`
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:

Following this trace:

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Cache/Repository.php#L191-L199

Then reaching `getMinutes`:

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Cache/Repository.php#L199-L207

Then `parseDateInterval`:

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Cache/Repository.php#L573-L581

Which is defined as follows:

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Support/InteractsWithTime.php#L41-L53

There are some type issues here:

 1. `Illuminate\Cache\Repository#put()` has a possible `null` as TTL
 2. `Illuminate\Cache\Repository#getMinutes()` does not accept `null` as TTL, but can return `null`
 3. `Illuminate\Support\InteractsWithTime#parseDateInterval()` does not support `null` parameters

Besides being a type declaration issue, this leads to the weird side-effect of calling `Illuminate\Cache\Repository#put('foo', 'bar', null)` being valid, yet not producing a cache entry.

Another (worse) design issue is that `Illuminate\Cache\Repository#put('foo', 'bar')` (no third argument) is valid according to specification, but effectively dead/misleading code.

This is a design issue strictly related with https://github.com/laravel/framework/issues/10504

### Possible fixes

A possible fix is to:

 * introduce a deprecation warning for `null` being passed to the method
 * add a throwing assertion on the given parameter, so that the 5 supported types of `CacheRepository::put()` are checked
 * remove support for `null` in a major release (`6.0`)

The assertion is completely optional, as a type check in userland would suffice, but the interface is indeed too broad due to the type being too extensive.

**Comment by driesvints** [comment]
Heya, thanks for sending this in! I do however believe the current implementation to be the correct one. 

`Illuminate\Cache\Repository` implements `Illuminate\Contracts\Cache\Repository` which implements `Psr\SimpleCache\CacheInterface`. As `put` is an alias of `set` (see below) it conforms to the same interface.

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Cache/Repository.php#L220-L226

The description of the `$ttl` argument is the following: 

> If no value is sent and the driver supports TTL then the library may set a default value for it or let the driver take care of that.

It's the `may` keyword here that concerns me. Judging from the sentence above there's no obligation to require a TTL or default value so a value of `null` is valid and just results in the passed value not being stored at all. This results in the `put` method returning false.

This is also the reason why the docs always have examples which explicitly add the `$minutes` parameter: https://laravel.com/docs/5.7/cache#storing-items-in-the-cache. This is simply because we offer no default value.

Please let me know if you see this differently and I'll gladly get to the bottom of this with you 👍 

PS.: We follow a different versioning scheme than SemVer so we could perform an update in the next minor release (5.9): https://laravel.com/docs/5.7/releases#versioning-scheme

P.P.S.: One thing that does concern me is that the TTL for the PSR interface is represented in seconds and instead of minutes. We might need to revise this but this is a different issue than the one above. https://www.php-fig.org/psr/psr-16/#12-definitions

**Comment by nunomaduro** [comment]
> PS.: We follow a different versioning scheme than SemVer so we could perform an update in the next minor release (5.9): https://laravel.com/docs/5.7/releases#versioning-scheme

The next minor version is 5.8 - the target is `laravel:master` branch.

**Comment by driesvints** [comment]
@nunomaduro Yeah, sorry, that's what I meant :)

**Comment by Ocramius** [comment]
There's a 100% issue with the type declarations in there, as they are incompatible with each other (twice).

As for this bit:

 > I do however believe the current implementation to be the correct one.
 > The description of the `$ttl` argument is the following:
 > 
 > > If no value is sent and the driver supports TTL then the library may set a default value for it or let the driver take care of that.

The driver is not being reached at all, according to following block:

https://github.com/laravel/framework/blob/5bd78e1ea1c4107782a8bfe9d9a4eecf4f819703/src/Illuminate/Cache/Repository.php#L207

**Comment by driesvints** [comment]
> There's a 100% issue with the type declarations in there, as they are incompatible with each other (twice).

They are indeed not a one-on-one match but the general gist of handling the TTL/minutes parameter should be the same. However, you're right about the contract not having the `null` type as well. I'll send in a fix for this.

> The driver is not being reached at all, according to following block:

Now *this* is indeed an issue. Thanks for pointing that out. The `is_null` is indeed unnecessary and indeed prevents a driver from implementing a default. I'll check if I can send in a fix for this.

> I'm aware: I was just being pushy about adopting sensible conventions for versioning.

On a personal note I also am more in favor of SemVer but this has been a discussion which has been held a lot in the past. In the end we decided to go for the current one because it allows us to make minor breakages in point releases (which we do every half year) while still keeping large architectural changes for major releases. Otherwise we'd have to release a new major release every half year. Not that this is an excuse or anything, just the way we decided to handle our releases.

**Comment by driesvints** [comment]
I've made a PR which should properly implement the PSR spec: https://github.com/laravel/framework/pull/27166

Basically since Laravel doesn't provides a default TTL of its own, it should at least allow you to create a driver which does. Maybe in a follow up PR we could add support for a default TTL.

**Comment by daguilarm** [comment]
Updating laravel/framework (v5.7.2 => v5.7.27) and has this issue trying to login..

**Comment by driesvints** [comment]
Closing this as this is fixed for the next release.
