### ISSUE TITLE
Bug on update field

### ISSUE THREAD

**Issue by hanzkid** [laravel/framework#27165]
First i run this eloquent :
$course = App\Course::where([['period',2018],['student_id', $student_id],['course_code',$course_code]])->first();
its output in debugbar like this : 
select * from "courses" where ("period" = 2018 and "student_id" = 58887 and "course_code" = 'CMJ240') limit 1
but when i run
$course->grade = "A";
$course->save();

it output in debugbar like this:
update "courses" set "grade" = "A" where "student_id" =58887

So, all grade that student are updated, why the other parameter disappear?

**Comment by dkulyk** [comment]
Maybe you specified student_id as PK?

**Comment by hanzkid** [comment]
yeah, student_id field is PK

**Comment by dkulyk** [comment]
You fetch first record from you query where You PK is 58887 and updated this record where PK is 58887.

Your code does exactly what it should.

**Comment by gpressutto5** [comment]
@hanzkid So that's the expected behavior... If you want to update only the select you should do something like this:

```php
App\Course::where([['period', 2018], ['student_id', $student_id], ['course_code', $course_code]])
    ->update(['grade' => 'A']);
```

Please, avoid creating issues on this repositories for questions. If you have any doubt you should use [laracasts forum](https://laracasts.com/discuss), [stackoverflow](https://stackoverflow.com/) or any other Q&A website.

**Comment by hanzkid** [comment]
$course = App\Course::where([['period',2018],['student_id', $student_id],['course_code',$course_code]])->first(); 
is not is update the previous object?

Oh okay, my bad , sorry
