### ISSUE TITLE
Migration is successful while function does not exist. 

### ISSUE THREAD

**Issue by ItsWendell** [laravel/framework#27297]
- Laravel Version: 5.7.22
- PHP Version: 7.2.14
- Database Driver & Version: PostgresSQL 11.1-1.pgdg90+1

### Description:
I changed this issue from an issue I thought I have with nullable, stupidly enough it was just a typo that I just didn't see. Yet migrations 'work' even when functions don't exist in the table scheme, like for example `nullabe()` or `doSomething()`.

Is this intentional and shouldn't it error?

### Steps To Reproduce:
* create a column for example with type string, with a migration function that doesn't exist, for example: `$table->string('address')->doSomething()`, this will run fine without any errors.

**Comment by mfn** [comment]
> Is this intentional and shouldn't it error?

Basically intentional due to the underlying code being based on the `Fluent` class which acts as a "accepting everything" bucket.

So first everything is set in the Fluent classes and then the respective database driver codes look into it what they support and act on it.

It's not ideal but the whole Blueprint code is based on this, so any changes are unlikely to happen soon. Many have complaint about this…

The "best" we've right now is the IDE introspection support I guess :|

**Comment by driesvints** [comment]
Please see the explanations above.
