### ISSUE TITLE
FTP : File Storage - exists() & allFiles() root directory bug

### ISSUE THREAD

**Issue by srdante** [laravel/framework#27298]
- Laravel Version: 5.7.2
- PHP Version: 7.2.13

### Description:

I was trying to access a folder with my laravel ftp. The folder that I wanted to access was `/var/www/storage/` and the default directory of FTP user was `/root`.

### Steps To Reproduce:

To access that folder I put the `['root']` paramater on storage config file to `/var/www/storage/`. 

When I use the following function:

`Storage::disk('ftp')->allFiles();`

This function return the files of the `/var/www/storage/` folder. The folder have only one file: **video.mp4**. 

But if I try the following function:

`Storage::disk('ftp')->has('video.mp4');`
`Storage::disk('ftp')->size('video.mp4');`
`Storage::disk('ftp')->exists('video.mp4');`

The function say that the file do not exists, after I saw this, I made a test, and I saw that `exists()` function is still searching files on `/root`. (default directory of FTP user)

**Comment by driesvints** [comment]
I suspect that this is due to some sort of file restrictions or that the calls are being made with a user with insufficient permissions. 

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by srdante** [comment]
I was using root user...
