### ISSUE TITLE
Model::where completely freezes my pc (infinite loop?)

### ISSUE THREAD

**Issue by nybbom** [laravel/framework#27353]
- Laravel Version: 5.7.22
- PHP Version: 7.3.1
- Database Driver & Version: Mysql 5.6
- System: Manjaro Linux with i3 desktop

### Description:
Hello, I got a weird problem today. When I wanted to get users from database I just wrote a below code in mine controller:
```
$users = User::where('is_admin', false);
var_dump($users);
```
Then I just refreshed my localhost to check the results and weird thing happen: my processor usage increased dramatically (site was still loading) and few seconds later I couldn't even move my cursor and had to hold power button to do force-shutdown (it was completely froze and I couldn't do nothing with).

When I executed same code in tinker it worked well and returned Illuminate\Database\Eloquent\Builder.

I'm using docker-compose but I think it's not related with a problem.
Nothing logged.

### Solution (or not?)
I just added `->get()` and it executed without any problems:
```
$users = User::where('is_admin', false)->get();
var_dump($users);
```

### Steps To Reproduce:
1. Create a route, controller and method.
2. Migrate a database.
3. Add a code to controller:
```
$users = User::where('id', 1);
var_dump($users);
```
4. Refresh a page.
5. Force-shutdown your pc.

(sorry for my English, I was trying to describe an issue as best I can)

**Comment by ahinkle** [comment]
Your issue is that you are using a query builder but not declaring what you are wanting to do. `->get()` retrieves the results from your query builder.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by nybbom** [comment]
So, this is an ordinary behavior. I never met PHP code which froze my pc before. 

Nice to know, thanks!
