### ISSUE TITLE
dd() in Chrome v.72 shows blank in AJAX response

### ISSUE THREAD

**Issue by s-patompong** [laravel/framework#27428]
- Laravel Version: v5.7.25
- PHP Version: 7.2
- Chrome Version: 72

### Description:
I was debugging my AJAX request using dd() as I usually do on my Google Chrome browser. This time instead of showing object information in the preview tab, it shows me a blank (white background).

Note:
- This happens inside incognito mode as well. So I don't think Chrome extension is the problem here.
- This happens in Brave browser as well.
- This doesn't happens on Firefox.

### Steps To Reproduce:
1. Create a test route call /test-dd in the route file and put some dd() code it in (just a simple array is fine).
2. Create a new blade file and put a script tag that does AJAX call to /test-dd route (in my case I use fetch API).

![screen shot 2562-02-06 at 15 26 58](https://user-images.githubusercontent.com/3887531/52328873-b2976900-2a23-11e9-996d-034a50c12e42.png)

**Comment by romainSaya** [comment]
Yes, same probleme for me,
I get a blank in preview tab. but in response tab it shows me raw code

Preview Tab :
![2019-02-06_11h21_46](https://user-images.githubusercontent.com/37927655/52334967-76531100-2a01-11e9-8ec2-a967922c2501.png)

Response Tab :
![2019-02-06_11h22_33](https://user-images.githubusercontent.com/37927655/52334994-88cd4a80-2a01-11e9-9f5f-0bc4e316bbee.png)

**Comment by d-pollard** [comment]
This is probably due to the fact that `preview` in the chrome developer console doesn't run Javascript and `dd()` relies heavily on it to give a "developer/user"-friendly display:

![screen shot 2019-02-06 at 10 36 42 am](https://user-images.githubusercontent.com/16292606/52357149-3721c180-29fb-11e9-80a8-5e62b7bdda60.png)

A solution could be to potentially add in a CSS + HTML based solution inside the `noscript` tag. Sounds like an opportunity for a PR!

**Comment by s-patompong** [comment]
Found this on Chrome Dev-Tool forum: https://groups.google.com/forum/#!topic/google-chrome-developer-tools/6btEa32ISEA

Seem like people have been having this problem for a while now. Some has it since Chrome 62. It's weird that I just have this problem now, the previous version of Chrome works perfectly fine for me.

Now, I no longer think this is Laravel problem. I'm not sure if Laravel team will consider this as a big problem at all because people can just use dump-server to see the dump data now.

**Comment by driesvints** [comment]
Seems like this is a Chrome issue rather than an issue with the framework.

**Comment by lukas-pierce** [comment]
I solved this problem by installing Google Chrome Dev Edition (v74)

**Comment by s-patompong** [comment]
That mean Chrome's dev bring back the feature in v74. I'll wait until it releases then.

**Comment by browner12** [comment]
seems to be working again in Chrome 73, released yesterday.

**Comment by s-patompong** [comment]
Yep, can confirm that it's back to work now on v73. Tested on Laravel 5.7.

**Comment by acv-namtd** [comment]
Oh chrome version 73 has fixed it

**Comment by ErnestStaug** [comment]
Still not working for me...
![image](https://user-images.githubusercontent.com/17262977/55279102-5400b400-531d-11e9-81a9-b84c6ecbd905.png)
![image](https://user-images.githubusercontent.com/17262977/55279108-64189380-531d-11e9-990f-9d2790819e42.png)

While it works fine on FIrefox
![image](https://user-images.githubusercontent.com/17262977/55279123-9a561300-531d-11e9-8bbf-91e21a90b84d.png)

**Comment by s-patompong** [comment]
@ErnestStaug does it work if you change from null to something else like an array?

**Comment by ErnestStaug** [comment]
Nope, nothing works... checked on colesgues computer same issue :)

**Comment by s-patompong** [comment]
Just an update, for me this issue shows up again in Chrome 75.

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
