### ISSUE TITLE
Eloquent: Where like - backslashes doesn't escaped in value

### ISSUE THREAD

**Issue by mbMovamo** [laravel/framework#27533]
- Laravel Version: 5.7.26
- PHP Version: 7.2
- Database Driver & Version: 10.2.21-MariaDB

### Description:
When i save a FQDN Classname in my database, and will getting call them through a LIKE operator, laravel can't find that match, because the backslashes aren't escaped.

### Steps To Reproduce:
`
>>> \App\Models\UserFeed::where('model_class', 'LIKE',  App\Models\Types\Gift::class)->where('user_id', 14805)->get();
=> Illuminate\Database\Eloquent\Collection {#4135
     all: [],
   }

>>> \App\Models\UserFeed::where('model_class', 'LIKE', addslashes( App\Models\Types\Gift::class) )->where('user_id', 14805)->get();
=> Illuminate\Database\Eloquent\Collection {#4115
     all: [
       App\Models\UserFeed {#4123
         id: 1,
         user_id: 14805,
         model_class: "App\Models\Types\Gift",
         model_id: 187402,
         created_at: "2019-02-14 08:58:21",
         updated_at: "2019-02-14 08:58:21",
       },
     ],
   }
`

**Comment by driesvints** [comment]
You shouldn't save FQNS in your DB because your code can change and you'd have to update them accordingly. Granted, we do this now for polymorphic relationships but we provide a way to prevent this with morph maps: https://laravel.com/docs/5.7/eloquent-relationships#custom-polymorphic-types

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
