### ISSUE TITLE
route with prefix placeholder not producing correct output

### ISSUE THREAD

**Issue by katsamsoft** [laravel/framework#27639]
- Laravel Version: 5.7
- PHP Version:7
- Database Driver & Version:mysql

### Description:
Ok so i have tested this issue on two places and its not giving expected output.
Whenever we define the prefix in web.php for route having parameter it will not produce right output.

### Steps To Reproduce:
add following code in routes/web.php

Route::group(['prefix' => '{api}'], function ()
{
    Route::get('main_service/products/{main_service_id}', function ($main_service_id) {
      dd($main_service_id);
    });
});
//url to hit http://localhost:8000/api/main_service/products/1
//when we will hit this URL it will dd "api" not the "1" we are sending
//but when i put this route outside prefix it will word fine

**Comment by mace015** [comment]
That is because your prefix contains a route parameter.

Your entire route will look like this: `{api}/main_service/products/{main_service_id}`.
So when you hit `api/main_service/products/1`, `api` will be the first route parameter and `1` will be the second.

You can see this for yourself by changing your function to this:
```php
Route::group(['prefix' => '{api}'], function ()
{
    Route::get('main_service/products/{main_service_id}', function ($api, $main_service_id) {
        dd($api, $main_service_id);
    });
});
```

**Comment by laurencei** [comment]
Alternatively you can do

   Route::group(['prefix' => 'api'], function () {

And just hardcode the `api` name if that is what you want.
