### ISSUE TITLE
PHP Unit 8 Compatibility

### ISSUE THREAD

**Issue by georgehanson** [laravel/framework#27676]
- Laravel Version: 5.8.0
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7

### Description:
After upgrading to Laravel 5.8, my tests are failing despite still requiring PHPUnit 7. Looking at my installed dependencies I can see that I have PHPUnit 7.5.6 installed. The docs mention that you need to add return types if you are using PHPUnit 8.

### Steps To Reproduce:

Create a new Laravel 5.8 project. Ensure you are using PHPUnit 7. Update the TestCase file to add a `setUp` method. The following code fails:

```php
public function setUp()
{
    parent::setUp();
}
```

However the tests then fail with the message: `PHP Fatal error:  Declaration of Tests\TestCase::setUp() must be compatible with Illuminate\Foundation\Testing\TestCase::setUp(): void`

Updating the declaration to include the return type fixes this issue.

The only reason I raised this is because the docs say you have to include the return type if you are using PHPUnit 8 only.

**Comment by driesvints** [comment]
Heya. This is indeed a mistake in the upgrade guide. You'll always need to add the void return type to those methods now. I'll fix this in the upgrade guide. Thanks for reporting!

**Comment by optiroot** [comment]
Sorry for re-opening this, but in the [actual documentation](https://laravel.com/docs/5.8/testing#creating-and-running-tests) (see very page bottom), there is just written:

> If you define your own setUp / tearDown methods within a test class, be sure to call the respective parent::setUp() / parent::tearDown() methods on the parent class.

The problem is that while in the [upgrade from 5.7 to 5.8 docs](https://laravel.com/docs/5.8/upgrade) there is written that the void type return declaration is required, in the actual docs there is no mention about this.
I know it is pretty trivial to *solve* this issue, but I think it should be written in docs for clarity.

**Comment by devcircus** [comment]
As this noted in the upgrade guide, and nothing about the signature is mentioned here, seems like you should obviously check the signature of a method you're calling.
