### ISSUE TITLE
[PROPOSAL] anytime() frequency for the Command Scheduler

### ISSUE THREAD

**Issue by clementblanco** [laravel/framework#27877]
I'd like to propose two additional functions for `Illuminate\Console\Scheduling\ManagesFrequencies`:

```php
/**
 * Schedule the command at a random time.
 *
 * @return $this
 */
public function anytime()
{
    return $this->at(random_int(0, 23) . ':' . random_int(0, 59));
}

/**
 * Schedule the command at a random time between two times.
 *
 * @param  string  $startTime
 * @param  string  $endTime
 * @return $this
 */
public function anytimeBetween($startTime, $endTime)
{
    $startSegments = explode(':', $startTime);
    $endSegments = explode(':', $endTime);

    $startHour = (int) $startSegments[0];
    $startMinutes = (int) ($startSegments[1] ?? 0);

    $endHour = (int) $endSegments[0];
    $endMinutes = (int) ($endSegments[1] ?? 59);

    return $this->at(random_int($startHour, $endHour) . ':' . random_int($startMinutes, $endMinutes));
}
```

This way I should be able to schedule commands using for example:
```php
$schedule->command('foo:bar')
    ->daily()
    ->anytime();

$schedule->command('foo:bar')
    ->weekdays()
    ->anytimeBetween('9:00', '17:00');
```

I would also probably recommend to rename the already existing function `between()` to `onlyBetween()` as it cannot be used to schedule a job but instead can be used to make sure a command is executed (or not) within a time frame. I find the current name misleading. It's more of a security/limitation measure than actually scheduling something. A command can be scheduled at `'23:00'` but if `between('9:00', '17:00')` is used it will never be called.

What do you think? Did I miss something?

**Comment by rs-sliske** [comment]
I dont think this would actually work. (the chance that your job wouldnt end up running at all would be pretty high)

my understanding of how the scheduler works is every minute you call the command, which then check what jobs are scheduled to run now, and runs those.

if the time is random you are relying on the random time being current time for the job to run

**Comment by mfn** [comment]
Randomly executing jobs is never a smart idea.

If you really need that feature, use randomes _within_ your task to decide whether to run it or not.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community. Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

I will add as someone who does alot of deep work within the scheduler, that the idea of a random schedule wont work, because as @rs-sliske said - it would "randomly" reallocate the job each time the scheduler runs.

It would make more sense just to define a time such as "09:27" and be in control.

Thanks in advance.

**Comment by clementblanco** [comment]
@rs-sliske is spot on I think. I forgot the scheduler was executed within one cron job and wasn't really writing entries in a crontab file. Like @mfn pointed, I think I will have to either:

- push jobs onto the queue at 9:00am but randomly delay it throughout the day using [Delayed Dispatching](https://laravel.com/docs/5.8/queues#dispatching-jobs), hoping I can delay up to 8 hrs with redis/database drivers.
- maintain some kind of internal randomised schedule for each job

@laurencei thanks but I think I was just being silly and I don't need to raise anything on `laravel/ideas`.
