### ISSUE TITLE
islocal() method of Application is missing in Contract

### ISSUE THREAD

**Issue by lk77** [laravel/framework#27971]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:

Hello, 

there is a isLocal() method in the Application class, 
but there is no such method in the Application contract.

The use of the islocal() method is advised in the documentation, 
for loading dev providers, and i think it the interface should declare it, 
if it's meant to be publicly used.

thanks.

**Comment by driesvints** [comment]
Hey there,

Not all methods of the application instance are available on the contract because they'd provide little use to implementations outside the framework itself. In any case this like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by lk77** [comment]
It's a bad practice to use a method if it's not part of the contract,
it means that instances are not swappable anymore.

**Comment by driesvints** [comment]
Actually, I believe that the real culprit here is the application contract since it provides no value at all. A framework in general should not be swappable by a framework created contract. In any case this is something that's best discussed in the laravel/ideas repo.

**Comment by devcircus** [comment]
Plus the method isn't used anywhere in the framework. Any additional methods used should be added to your implementation. IMO, a contract should cover what is needed for an implementation to work out-of-the-box. It shouldn't cover every possible method that could ever be used. 

However, like Dries mentioned, the Application contract doesn't make much sense anyway.
