### ISSUE TITLE
url('') in blade HTML triggers Controller action twice

### ISSUE THREAD

**Issue by KeithTurkowski** [laravel/framework#28017]
- Laravel Version: 5.8.7
- PHP Version: 7.2.16
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.6.27-75.0

### Description:
Using or generating the text url(), url(''), url("") any number of times inside a blade template will cause the Controller action method (that called the blade template) to be called a second time.

### Steps To Reproduce:
1. Create a standard controller with routes, etc. (e.g. TestController)
2. Modify one of the action methods (e.g. TestController@index)
`Log::debug('this happens twice'); return view('test.index');`
3. Modify the test/index.blade.php file to include the text: url('')
`<div style="background-image: url('')"></div>`
4. Open the route in a web browser (e.g. /test)
5. Observe two log messages

I'm not sure what is going on, or why url('') is being parsed out as code somehow when it should be treated as HTML text. It's not inside {{}} and view source on the web browser shows it as intended. At the very least it should generate an error.

**Comment by driesvints** [comment]
Hmmm, I can reproduce this. That's very odd indeed. Gonna mark this as a bug. Appreciating any help with investigating this.

**Comment by KeithTurkowski** [comment]
This also happen when you use a function that ends with url() in a blade.
`{{ $team->logo_url() }}`

In this instance, however, it was calling the action method defined for the root url (e.g. Route::get('', RootController@index);)

I'm guessing this is caused a blade parsing pass looking for the url helper function.
https://laravel.com/docs/5.8/helpers#method-url

**Comment by KeithTurkowski** [comment]
I'm concerned that their may be keywords other than url that have this issue.

**Comment by 36864** [comment]
This is expected behavior. You're basically trying to use the current page as a background image. Your browser will load the page and attempt to use it as an image.

Basically, if you're on `www.example.com` and have a div with `background-image: url('')`, your browser will attempt to use `www.example.com` as the source for that image.

You can observe this in your browser's development tools, on the network tag. You can try it even here on github, inspect any element on the page and add a `background-image: url('')` rule to it, after having loaded the network tab. You will see an additional request being made to this current page, with "Cause" set to "img".

In your second example, is `$team->logo_url()` also empty, and being used as either an image source or a background-image source?

**Comment by driesvints** [comment]
@36864 ah, very good thinking. That didn't occur to me.

**Comment by KeithTurkowski** [comment]
Yes, you're correct.

I'm surprised that an empty src="" or url('') works that way.
