### ISSUE TITLE
Apply Short List Syntax via StyleCi

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/framework#28028]
We have applied `Short List Syntax` for 5.7 version https://github.com/laravel/framework/pull/25966

So, I have proposing to apply https://docs.styleci.io/fixers#short_list_syntax in StyleCi to Laravel from v5.8 branch

@taylorotwell , @GrahamCampbell, @driesvints

**Comment by driesvints** [comment]
That's perfectly fine for me. I've still got a todo left open to roll out StyleCI for all Laravel repos along with a config file so people can see the actual configuration instead of it being hidden in the StyleCI service. I'll try to make work of this but I need @taylorotwell's help with it because I'm not an admin of the repositories so I can't do this myself.

**Comment by driesvints** [comment]
@GrahamCampbell can we maybe add this fixer to the Laravel preset in StyleCI? It would save me from having to add it to every single styleci file in every Laravel repo.

**Comment by GrahamCampbell** [comment]
> I'll try to make work of this but I need @taylorotwell's help with it because I'm not an admin of the repositories so I can't do this myself.

I can let you see the config. Just let me know which repos you need, and I get look at the settings page for you, for each. :)

**Comment by driesvints** [comment]
@GrahamCampbell we're currently rolling out styleci files on every repo so that's unnecessary. Please see my reply to the DM.

**Comment by driesvints** [comment]
@GrahamCampbell I tried to disable the preset already on a 7.0 supported branch but get this error: https://github.styleci.io/analyses/8bnk5a

Reverting for now.

**Comment by driesvints** [comment]
This will be applied to the `laravel` preset on Sunday.
