### ISSUE TITLE
Migrations are not creating foreign keys

### ISSUE THREAD

**Issue by wemersonrv** [laravel/framework#28051]
- Laravel Version: 5.8.8
- PHP Version: 7.2.11
- Database Driver & Version: MySQL 5.7.24 - Community Server

### Description:
Migrations are not creating foreign keys

### Steps To Reproduce:
Run these two migrations

**CreateEmpresasTable** migration:
```php
Schema::create('empresas', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('cnpj', 14)->unique();
    $table->string('razaoSocial');
    $table->string('nomeFilial');
    $table->string('regiao');
    $table->boolean('ativo')->default(true);
    $table->datetime('dataAtivacao');
    $table->datetime('dataExpiracao')->nullable();
    $table->string('logomarca')->nullable();
    $table->timestamps();
});
```
**CreateTanquesTable** migration
```php
Schema::create('tanques', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('descricao');
    $table->string('combustivel')->default('Óleo Diesel');
    $table->boolean('ativo')->default(true);
    $table->unsignedBigInteger('empresa_id')
        ->references('id')
        ->on('empresas')
        ->onDelete('cascade');
    $table->timestamps();
});
```

Tables are created normally, but without the foreign key in the table **tanques**

**Comment by staudenmeir** [comment]
Are your tables using the `InnoDB` engine?

**Comment by ahinkle** [comment]
Possibly related to #27717. 

Try utilizing `$table->bigInteger('id');` instead of `$table->bigIncrements('id');`.

**Comment by ahinkle** [comment]
Take a look at #27717 - there may be a resolution for you there.

**Comment by driesvints** [comment]
I was just about to link to the issue above, this seems to be a duplicate one.

**Comment by webdev12-v** [comment]
> Are your tables using the `InnoDB` engine?

In my case the issue with non-working foreign keys had 3 layers to go down to resolve:
1) The key and foreign key columns type mismatch due to Laravel replaced `increments()` with `bigIncrements()` in migrations, but I did not.
2) The tables I linked with foreign keys were MYISAM (with no foreign keys support) instead of InnoDB.
3) My local dev machine WAMP did not want to accept InnoDB as the default DB engine unitl I realized that I had to restart the DB server.

Funny how it sometimes goes.

**Comment by Javier1995** [comment]
Bro! you neee to add foreign('empresa_id')->references('id')->on('empresas')

**Comment by nathanheffley** [comment]
@driesvints this is not actually a duplicate issue, but just an incorrect usage of the `references` function. There is no `references` function on a column model (what is returned when you call `$table->unsignedBigInteger()`) so in the code snippet above the problem is that a non-existent function is being called. Because of the way the functions work though, no exception is thrown and it just silently fails to call `references`.

@Javier1995 is correct that the snippet where @wemersonrv is trying to add the foreign key should be change to this:

**CreateTanquesTable** migration

```
Schema::create('tanques', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('descricao');
    $table->string('combustivel')->default('Óleo Diesel');
    $table->boolean('ativo')->default(true);
    $table->unsignedBigInteger('empresa_id');
    $table->foreign('empresa_id')
        ->references('id')
        ->on('empresas')
        ->onDelete('cascade');
    $table->timestamps();
});
```

Note how `foreign('empresa_id')` is called directly on `$table`, and then `references()` is called on top of that.

**Comment by mazenn99** [comment]
Try to change this 
$table->unsignedBigInteger('empresa_id')
        ->references('id')
        ->on('empresas')
        ->onDelete('cascade');
to this
$table->foreign('empresa_id')
        ->references('id')
        ->on('empresas')
        ->onDelete('cascade');
