### ISSUE TITLE
hasManyThrough ambiguous id

### ISSUE THREAD

**Issue by pYr0x** [laravel/framework#28078]
- Laravel Version: 5.5
- PHP Version: 7.0.1
- Database Driver & Version: MySQL

### Description:
i have a very strait forward database setup:

table: auftraggeber
- id
- name

table: leistungsempfaenger
- id
- name
- auftraggeber_id

table: objekt
- id
- street
- leistungsempfaenger_id

i have an `Auftraggeber` Model where i want to get all entities from `objekt` table. so i use `hasManyThrough`.

```
class Auftraggeber extends Model {
....

 public function objekte() {
        return $this->hasManyThrough(
            'app\models\Objekte',
            'app\models\Leistungsempfaenger',
            'auftraggeber_id',
            'leistungsempfaenger_id',
            'id',
            'id'
        );
    }
}
```

### Steps To Reproduce:
1. use the Has-Many-Through-Relationship above.
2. i only want the ID's from the `objekt`-table releated to the  `auftraggeber` table. so i used `Eager Loading Specific Columns`
3. `$ag = Auftraggeber::with('objekte:id')->find(18);`
4. Error: 
```
 Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: 

select 
---> `id`, <---
`leistungsempfaenger`.`auftraggeber_id` 
from `objekte`
inner join `leistungsempfaenger`
on
`leistungsempfaenger`.`id` = `objekte`.`leistungsempfaenger_id`
where
`leistungsempfaenger`.`auftraggeber_id` in (18))
```

the `id` column from `objekte` should be specified as well.

**Comment by staudenmeir** [comment]
You have to specify the table name and you also have to include the foreign key from the intermediate table (necessary for matching the eager loading results to their parents):

```php
$ag = Auftraggeber::with('objekte:objekte.id,auftraggeber_id')->find(18);
```

**Comment by staudenmeir** [comment]
Do you mean that Laravel should automatically replace `id` with `objekte.id`?

**Comment by pYr0x** [comment]
yes

**Comment by staudenmeir** [comment]
`HasManyThrough` is a special case, as the other relationship queries don't have a `JOIN` clause (except `BelongsToMany`).

I don't think Laravel can automatically qualify the colum name. You could want to include a column from the intermediate table: `Auftraggeber::with('objekte:id,name')`

**Comment by pYr0x** [comment]
`Auftraggeber::with('objekte:id,name')` didn't work, too.

can you reproduce the issue with the given table relationship?

**Comment by staudenmeir** [comment]
I can reproduce the issue, but you've already posted the solution: `Auftraggeber::with('objekte:objekte.id')->find(18)`

`Auftraggeber::with('objekte:id,name')` was meant to show why this can't be fixed. Laravel can't automatically qualify the column name because it doesn't know which table the column belongs to.

**Comment by driesvints** [comment]
I'm afraid I have to agree with @staudenmeir. Seems like this wouldn't be possible to fix. Can you try the alternative solution posted above?

**Comment by mfn** [comment]
I wonder if we should add something to the docs regarding the qualifying of columns.

User only find out by trial and error (or rather: error, then trial) that something is wrong.

My team made it a rule that **all** columns, no matter in what context, always have to be qualified. As a result: never head issues with joins and ambiguous column names (which is also affected but even more subtle because same-column name on models get silently overwritten and you end up with nonsensical models) and other related methods of building queries/relations.

**Comment by marufmax** [comment]
Having same issue

**Comment by mwargan** [comment]
> yes,
> quick workaround is `$ag = Auftraggeber::with('objekte:objekte.id')->find(18);` but it seems odd to set the tablename.

This didn't work for me as it still keeps the original 'id' in the select.

**Comment by halvardssm** [comment]
Was a fix for this issue implemented? I am currently facing the same problem.

**Comment by driesvints** [comment]
@halvardssm no, please read the entire issue.

**Comment by Siscoh** [comment]
I am using laravel 7 and I am facing the same problem.

```
Facade\Ignition\Exceptions\ViewException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous (SQL: select exists(select * from `rents` inner join `tenant_room` on `tenant_room`.`id` = `rents`.`tenancy_id` where `tenant_room`.`deleted_at` is null and `tenant_room`.`room_id` = 1 and month(`created_at`) = 08 and year(`created_at`) = 2020 and `rents`.`deleted_at` is null) as `exists`) (View: D:\projects\houses\resources\views\admin\property\rent\index.blade.php)
```

**Comment by hfoletto** [comment]
> I am using laravel 7 and I am facing the same problem.
> 
> ```
> Facade\Ignition\Exceptions\ViewException
> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous (SQL: select exists(select * from `rents` inner join `tenant_room` on `tenant_room`.`id` = `rents`.`tenancy_id` where `tenant_room`.`deleted_at` is null and `tenant_room`.`room_id` = 1 and month(`created_at`) = 08 and year(`created_at`) = 2020 and `rents`.`deleted_at` is null) as `exists`) (View: D:\projects\houses\resources\views\admin\property\rent\index.blade.php)
> ```

I'm facing this exact same issue. Did you manage to fix it?

**Comment by egantz** [comment]
At least for me, the issue was when I created a trait with scopes that I used across different models in eloquent scopes with a `->where('some_column', '=', 'some_value')` in it. That caused the ambiguity. The real solution is to wrap the column with `$this-qualifyColumn()` that exists on the model already. The code will look like: `->where($this->qualifyColumn('some_column'), '=', 'some_value')`.

Hope that helps others that might bump into this issue!
