### ISSUE TITLE
A method for retrieving a cached item's lifetime

### ISSUE THREAD

**Issue by gabrielanhaia** [laravel/framework#28095]
@taylorotwell @driesvints 
I was looking for a solution and i found this issue #2356 

What do you think if I implement this in an abstract way, making sure all the cache drivers work?
I believe it's a good idea for some developers, currently i and my team need this implementation.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

In your linked ticket, Taylor has already said if you got it working across all drivers it would be fine, so that's probably a good indication.

Thanks in advance.
