### ISSUE TITLE
Dependency injection of two dates from route fails

### ISSUE THREAD

**Issue by axlon** [laravel/framework#28201]
- Laravel Version: 5.8.10
- PHP Version: 7.2.16
- Database Driver & Version: does not seem relevant

### Description:
When trying to dependency inject two Carbon instances into a Controller from a route the framework will fail to create a second Carbon instance which will generate the following error: 

```
Argument 2 passed to MyController::myFunction() must be an instance of Carbon\Carbon, string given
```

Interesting is that the first date is correctly converted into a Carbon instance (which is proven by the fact that PHP is not complaining about the first argument, but rather about the second)

### Steps To Reproduce:
- Create a controller `MyController` with function `myFunction(Carbon $start, Carbon $end)`
- Create a GET route `/my-route/{start}/{end}/stats.json` which points to `MyController@myFunction`
- Attempt to access the route e.g. `/my-route/2019-04-01/2019-04-10/stats.json`
- You should now see the exception, you may even confirm that the first Carbon is properly created by removing the second argument from the function and dumping the first

**Comment by staudenmeir** [comment]
This is caused by:

https://github.com/laravel/framework/blob/b984b71e0ef05ce3c31e7a2a29871f4c20e276cf/src/Illuminate/Routing/RouteDependencyResolverTrait.php#L76

`alreadyInParameters()` returns `false` for the first date but `true` for the second one.

The questions is why this method is necessary. Who's the resident routing expert?

**Comment by driesvints** [comment]
Hmm, we should indeed look into this. What happens to the test suite when the check is removed?

**Comment by staudenmeir** [comment]
@driesvints It causes failing tests.

**Comment by laurencei** [comment]
> The questions is why this method is necessary. Who's the resident routing expert?

According to Git Blame, it was @taylorotwell over 4 years ago. So I guess he is? 😆 🤣

**Comment by staudenmeir** [comment]
`alreadyInParameters()` is necessary for model binding.

I don't think parameter binding with `Carbon` dates is actually supported. Even with a single date, it doesn't work for me: I always get a `new Carbon()` instance that completely ignores the value from the URL.

**Comment by laurencei** [comment]
> The questions is why this method is necessary.

The comments above that function give a good indication:

```
If the parameter has a type-hinted class, we will check to see if it is already in
the list of parameters. If it is we will just skip it as it is probably a model
binding and we do not want to mess with those; otherwise, we resolve it here
```

**Comment by laurencei** [comment]
> I don't think parameter binding with Carbon dates is actually supported

I agree in principle, because logically you'd want to validate the supplied dates first are what you expect (both range and format) - then cast to Carbon if you agree with it? Otherwise your passing user input directly to an object, and we've seen multiple instances over the past few weeks where this ends up down a dark path in unexpected behaviour...

**Comment by driesvints** [comment]
I just indeed realized that this is unwanted since you can't expect an object to get auto-resolved from its own. The first Carbon instance is actually just resolved from the container and thus contains today's date and not the one from the route. Implicit routing is only available for Eloquent models. Please see the docs on adding resolution logic for Eloquent models: https://laravel.com/docs/5.8/routing#route-model-binding 

Out-of-the box support for Carbon & DateTime sounds cool and could perhaps be supported but you should open up an issue on the ideas repo in this case.

Thanks to everyone for helping figuring this out.

**Comment by axlon** [comment]
My bad, I missed that little detail! Thanks guys.
