### ISSUE TITLE
Failed to get the installation page

### ISSUE THREAD

**Issue by Chimiste** [laravel/framework#28284]
I got this error :

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in C:\xampp\htdocs\attendize\bootstrap\autoload.php on line 35

After : 

if(!defined('LARAVEL_START'))
define('LARAVEL_START', microtime(true));

C:\xampp\htdocs\attendize>php artisan serve
Laravel development server started: <http://127.0.0.1:8000>
[Sat Apr 20 23:42:12 2019] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in C:\xampp\htdocs\attendize\bootstrap\autoload.php on line 35
[Sat Apr 20 23:42:12 2019] 127.0.0.1:58189 [200]: /favicon.ico

**Comment by Chimiste** [comment]
Install URL http://127.0.0.1:8000/install

**Comment by crynobone** [comment]
1. Laravel doesn't have any installation page.
2. Error message clearly show that it run out of memory while trying to load the request.
3. You should be able to reconfigure max memory limits or look at what's the code trying to do and debug why it's runs out of memory. We can't help you on this since we have no knowledge about this "Installation page"

**Comment by Chimiste** [comment]
Hello,
Thanks i fixed the issue.

**Comment by staudenmeir** [comment]
Please close the issue.
