### ISSUE TITLE
Return true in Listeners without Queue stops propagation

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#28331]
- Laravel Version: 5.5.45
- PHP Version: 7.1.24
- Database Driver & Version: MySQL 5.7

### Description:
When you create an Event and multiple Listeners but you dont add ShouldQueue and you return true from handle method then next listener is not triggered and stops at 1st listener.

### Steps To Reproduce:
Create an Event "InvoicePaid"
Create 2 Listeners , "DoSomethingA","DoSomethingB" and add returns :bool in your handle method
In "DoSomethingA" return true in handle 
See that "DoSomethingB" is not triggered

**Comment by driesvints** [comment]
This isn't a bug but this was specifically implemented as such: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Events/Dispatcher.php#L209-L214

However, I do agree that it's kind of odd since I wouldn't expect a listener to return a response and also not know of each other's result. It's handle method is marked by default as void. Maybe this is something that can be taken up in the ideas repo.

**Comment by mariosvasiliou** [comment]
@driesvints Thanks for your reply. 
I knew that if you return false it will stop as meant to be...but returning true is not consider anywhere in the code or in the documentation that stops the propagation.
In fact its a problem because by default $halt = false and the response is not null, so it should not stop the listeners and continue to next one...is not an idea...it is a problem ....
If you add queue to your listeners, even if you return true it continues to other listeners but this is not happening to sync listeners without queue.
