### ISSUE TITLE
routing with subdomain middleware : Route::domain() vs ->domain()

### ISSUE THREAD

**Issue by Grummfy** [laravel/framework#28452]
hello,

- Laravel Version: 5.7.28
- PHP Version: 7.3.3
- Database Driver & Version: mariadb and it's not relevant ;)

### Description:
Issue related to routing

#### Working
```php
Route::get('/foo', function()
{
    return 'domain none - say hello';
});
Route::domain('domain1')->get('/foo', function()
{
    return 'domain 1 - say hello';
});
Route::domain('domain2')->get('/foo', function()
{
    return 'domain 2 - say hello';
});
```
php artisan route:list give 3 route, and it's ok

a r:l --path foo 
```
+------------------+----------+-----+------+---------+------------+
| Domain           | Method   | URI | Name | Action  | Middleware |
+------------------+----------+-----+------+---------+------------+
| jdomain1 | GET|HEAD | foo |      | Closure | web        |
|                  | GET|HEAD | foo |      | Closure | web        |
| jdomain2        | GET|HEAD | foo |      | Closure | web        |
+------------------+----------+-----+------+---------+------------+
```

#### error
```php
Route::get('/foo', function()
{
    return 'domain 1 - say hello';
})->domain('domain1');
Route::get('/foo', function()
{
    return 'domain 2 - say hello';
})->domain('domain2');
Route::get('/foo', function()
{
    return 'domain none - say hello';
});
```
got one route, the one without domain
a r:l --path foo
```
+--------+----------+-----+------+---------+------------+
| Domain | Method   | URI | Name | Action  | Middleware |
+--------+----------+-----+------+---------+------------+
|        | GET|HEAD | foo |      | Closure | web        |
+--------+----------+-----+------+---------+------------+
```

But if I got 3 different path I have no issue, the three route are there.

#### note:
Route::group(['domain' => ... or Route::domain('... have the same behavior

For me writing a fix or make a comment in the documentation are the same. But the behavior is quiet surprising.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by Grummfy** [comment]
well closing this directly without letting me the time to check on 5.8 is a bit unpleasant...

**Comment by driesvints** [comment]
Hey @Grummfy, there's a note about this when you open up a bug report:

<img width="745" alt="Screen Shot 2019-05-09 at 13 57 49" src="https://user-images.githubusercontent.com/594614/57451767-7a8e0500-7262-11e9-93cd-bb7638ae604d.png">

I've also said:

> Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

So please feel free to do so. Don't take a closed issue as a way that you can't reply anymore.

**Comment by Grummfy** [comment]
Hello,
I confirm it's the same behaviour on the actual version 5.8.16. I have edited the example to ease the test for you (just add the route to a new project and print the route list)




For the closing of the issue, even if you openly write "feel free to reply", it make a bad impression *on me*. Perhaps adding something about closing the issue in your comment. Or perhaps it's only me that have this impression/interpretation and you should not worry about it :man_shrugging:

**Comment by driesvints** [comment]
Hey @Grummfy, the way you want to use the `domain` feature for routes is always with groups. `->domain(` doesn't work (and this isn't documented to be used as such).

Using the following will work:

```php
Route::domain('domain1')->group(function () {
    Route::get('/error-foo', function()
    {
        return 'domain 1 - say hello';
    });
});

Route::domain('domain2')->group(function () {
    Route::get('/error-foo', function()
    {
        return 'domain 2 - say hello';
    });
});
Route::get('/error-foo', function()
{
    return 'domain none - say hello';
});
```

Gives me:

![Screen Shot 2019-05-10 at 13 30 34](https://user-images.githubusercontent.com/594614/57524384-f00fd900-7327-11e9-8241-90ef97a3fb3a.png)

About the ps: adding something about re-opening the issue is a good idea, I've added this to my saved replies, thanks for your suggestion :)

Please realize that I deal with quite a lot of issues daily and a lot of them ignore what's in the issue templates or don't bother to search other issues first. In fact, this is something you could have asked first on a support channel before coming here. We can't give support on how to use the framework because otherwise we would only be busy with answering questions instead of building new things and fixing bugs. I realize that when you experience a problem when trying to use something in a way you *think* is correct you immediately think it's a bug but very often it's something that's misunderstood. For that reason always try to ask on a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

We're only with three people in Laravel and although we get a lot of great help from other community with the issues we can't possible answer every single support issue. So please, please try using one of the links above before posting an issue 🙏 

Hope you understand. 

Thanks!
