### ISSUE TITLE
[Validation Rules: max + integer] max validates if number is greater instead of digit count

### ISSUE THREAD

**Issue by Bcryp7** [laravel/framework#28483]
- Laravel Version: 5.8.*
- PHP Version: 7.3.5
- Database Driver & Version: MySQL 14

### Description:
When using `max` and `integer` validation rules, `max` validates if the parameter is greater than the number passed to the request but not the character count. So `max:10` means the number must be less than the number 10 not less than 10 digits.

In suggestions of other similar issues, the rule `digits` is suggested but the `digits` is when the lenght is known as the Documentation says: *The field under validation must be numeric and must have an exact length of value.*

### Steps To Reproduce:
`'price' => ['required', 'max:10', 'integer'];`

I tried it placing integer first then max, or max rule + numeric.

*Note: The Validation message for max rule varies if you use only max it shows the regular message: **The price may not be greater than 10 characters.** but when using both rules the Validation messages changes to: **The price may not be greater than 10.**

**Comment by 570studio** [comment]
I was working on some validation issues recently, so this is all pretty fresh for me. But, I think what you're describing as an issue **may be expected behavior**. 

When you add the `integer` validation rule, the attribute/field is added to the [Validator class's](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Validation/Validator.php) `$numericRules` array. And then when the `getSize` method is called in the [ValidatesAttributes class](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Validation/Concerns/ValidatesAttributes.php), the first `if` statement is truthy. Since the value passed in the `$price` field `is_numeric` and the `$hasNumeric` is also true (because the attribute/field is in the `$numericRules` array, stated above). 

Hence the `value` returned is the numeric value of `$price`. As opposed to the `strlen`, which you would get if you don't assign the `integer` (or any other numeric) validation rules. 
```
return $this->getSize($attribute, $value) <= $parameters[0];
```

```
    protected function getSize($attribute, $value)
    {
        $hasNumeric = $this->hasRule($attribute, $this->numericRules);

        // This method will determine if the attribute is a number, string, or file and
        // return the proper size accordingly. If it is a number, then number itself
        // is the size. If it is a file, we take kilobytes, and for a string the
        // entire length of the string will be considered the attribute size.
        if (is_numeric($value) && $hasNumeric) {
            return $value;
        } elseif (is_array($value)) {
            return count($value);
        } elseif ($value instanceof File) {
            return $value->getSize() / 1024;
        }

        return mb_strlen($value);
    }
```
I hope this helps. And if I am misunderstanding the issue you are stating, I apologize.

**Comment by laurencei** [comment]
So if the field is `integer` and you want a maximum of 10 digits - then just do

`required|integer|max:9999999999`

however - this only works if you are running a 64bit PHP version, because a 32bit PHP version has a max `int` value of `2,147,483,647`

**Comment by driesvints** [comment]
I'm not sure I follow. What is it that you exactly are trying to do? I think you're trying to do what @laurencei is proposing?

**Comment by fitztrev** [comment]
Here's a test file showing what's happening. The first 2 tests pass, but the 3rd fails.

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Support\Facades\Validator;

class Issue28483Test extends TestCase
{
    public function testMax()
    {
        $validator = Validator::make([
            'foo' => 123,
        ], [
            'foo' => 'max:10',
        ]);

        // strlen(123) < 10 so this should pass (and does)
        $this->assertTrue($validator->passes());
    }

    public function testInteger()
    {
        $validator = Validator::make([
            'foo' => 123,
        ], [
            'foo' => 'integer',
        ]);

        // 123 is an integer so this should pass (and does)
        $this->assertTrue($validator->passes());
    }

    public function testMaxAndInteger()
    {
        $validator = Validator::make([
            'foo' => 123,
        ], [
            'foo' => ['max:10', 'integer'],
        ]);

        // but when both "max" and "integer" are combined, this should pass (but doesn't)
        $this->assertTrue($validator->passes());
    }
}
```

If it's not a bug, I would agree it's at least confusing.

**Comment by 570studio** [comment]
@fitztrev

The above test failure has is caused by the explanation in [the comment above](https://github.com/laravel/framework/issues/28483#issuecomment-491465990). 

It's definitely strange, but in a nutshell, by adding the `integer` validation rule, the `foo` field is treated as numeric by the `getSize` method. And therefore it returns the value of `123`, which is obviously greater than the max validation rule of `10` listed in your example. 

That being said, if you don't pass the `integer` validation rule, the `foo` field is treated as a `string` by the `getValue` method, and it simply returns the `mb_strlen`, which is `3` and passes the `max:10` validation rule. 

This stuff can get a bit hairy, I just went through [a similar process](https://github.com/laravel/framework/pull/28474) with the `gte`, `lte` and other similar validation rules and strange results that can be returned if you're not explicit with your Validation rules.

**Comment by rs-sliske** [comment]
overall, i feel the scenario where max is comparing numeric value makes more sense than length comparison if we had to choose one.

im also confused about what the use case is for checking how many digits (in base 10) a number has, especially with larger numbers. if you are working with 32bit integers 10 digits is going to cause an overflow for > 1/2 the values your rule allows (nearly 4/5 if you are using unsigned)

**Comment by driesvints** [comment]
> The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value. For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.

I feel like the docs need a bit more clarifying that when you want to validate a number as a maximum amount you need to explicitly add the `numeric` or `integer` rule. At the moment this all works as expected but I agree it's a bit confusing. 

So in your examples @fitztrev it's normal that your third example fails because 123 is larger than 10. The value is being validated as a number because of the presence of the `integer` rule.

Look at the comment here to see the internals: https://github.com/laravel/framework/issues/28483#issuecomment-491465990

We're open to PRs for this, otherwise I'll send one in once I get to it.

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/docs/pull/5803
