### ISSUE TITLE
Pluck ignoring results of first

### ISSUE THREAD

**Issue by DrRoach** [laravel/framework#28549]
- Laravel Version: 5.8.17
- PHP Version: 7.1.26
- Database Driver & Version: MySQL

### Description:
Calling `pluck()` on `first()` result ignores query and performs `pluck()` on whole DB table.

### Steps To Reproduce:
- Create DB table with multiple rows
- Get record from table using `first()`
- Perform `pluck()` on result of query

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by staudenmeir** [comment]
@driesvints They mean something like `User::first()->pluck('id')`.

@DrRoach This is the correct behavior. The `Model` class doesn't have a `pluck()` method, so it instantiates and executes a new query. It's equivalent to `User::pluck('id')` or `(new User)->pluck('id')`.

The same applies to other methods like `count()` or `exists()`.

**Comment by driesvints** [comment]
@staudenmeir you're right.

**Comment by alexbowers** [comment]
This has caused some issues for us.

Is it possible for there to be something that would trigger an exception if you try to pluck on a model because the current behaviour is not intuitive

Or perhaps, the model `pluck` method, should take the place of the `get` and return just the single property that is asked for as a new collection?

**Comment by alexbowers** [comment]
I can produce a test case showing this error if necessary.

**Comment by staudenmeir** [comment]
This behavior wasn't necessarily a conscious decision.

When you call a method that doesn't exist in the `Model` class (e.g. `pluck()`), `__call()` instantiates and executes a new query. This is necessary to make `User::pluck()` work.

We could differentiate between existing and non-existing models, but that's not an option. I've seen plenty of people *deliberately* using existing models to execute new queries.

Personally, I think this is just a user error. I don't see why you would call `pluck()` on a *single* model.

**Comment by alexbowers** [comment]
This was an unintended side effect of having old code that used to be `Model::conditions()->limit(1)->get()->pluck('data')` which was changed to `Model::conditions()->first()->pluck('data')`.

The way we worked around it is to have `->data` instead of plucking it.

Is there a deliberate use for `$one_product->pluck('data')` to give you a collection of all products, and not just the `data` property from the record you are already on?

I can understand using the model for these methods if you aren't directly on an actual record, but if you're trying to call these methods on a record, it should only interact with that / those records right?

**Comment by alexbowers** [comment]
Is there a way that we can check if the record is an already existing one, and if it is, then change the behaviour, and if it isn't, pass the call through to the parent model?

**Comment by staudenmeir** [comment]
> Is there a deliberate use for $one_product->pluck('data') to give you a collection of all products, and not just the data property from the record you are already on?

I've seen people using this in controllers. They have a model property and use it to execute new queries:

```php
$users = $this->user->where('foo', 'bar')->get();
```

> Is there a way that we can check if the record is an already existing one, and if it is, then change the behaviour, and if it isn't, pass the call through to the parent model?

Do you mean in the framework or in your personal application?

**Comment by alexbowers** [comment]
In the framework. I feel this is a trap people may unwillingly fall into because it isn’t obvious. Perhaps it just needs documenting but as it stands it isn’t clear why this would happen

**Comment by staudenmeir** [comment]
We could "fix" it by checking `$this->exists`, but it would be a major breaking change.

**Comment by devcircus** [comment]
IMO this doesn't  seem feasible. Eloquent has always worked this way and many use it like this. Would we do this check on all methods passed through via "__call"? Whitelist certain.methods? Only check for "pluck"? Seems like a tradeoff for the things that make Eloquent such a pleasure to use.
