### ISSUE TITLE
Loss of decimal precision when logging with Facades Log

### ISSUE THREAD

**Issue by keepchen** [laravel/framework#28559]
- Laravel Version: 5.5.45
- PHP Version: 7.0.33
- Database Driver & Version: Mysql Version: 5.7.26
- OS: Ubuntu 16.04 x64 (Linux 4.15.0-50-generic kernel)
### Description:
When I use the log component to log in the middleware, when some of the request parameters are decimal, there is a case where the precision is lost.

### Steps To Reproduce:
> ~app/Http/Middleware/LogMilddleware.php

```php
<?php
namespace App\Http\Middleware;

use Illuminate\Support\Facades\Log;
use Closure;

class LogMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        Log::info("--------------------------------------------");
        Log::info($request->ip());
        Log::info($request->url());
        Log::info($request->all());
        return $next($request);
    }
}
```
> ~/app/Http/Kernel.php

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\LogMiddleware::class,  // <--------------Here
    ];
...
```
> request data

```json
{
	"datetime":"2019-05-17 12:00:00",
	"account_name":"KKK",
	"platform_bank_id":"100001",
	"platform_bank_name":"BANK",
	"amount":100.52,
	"total_amount":200.51
}
```

> log info

```info
[2019-05-17 14:43:47] local.INFO: --------------------------------------------
[2019-05-17 14:43:47] local.INFO: 192.168.0.134
[2019-05-17 14:43:47] local.INFO: http://127.0.0.1:8000/api/info/receive
[2019-05-17 14:43:47] local.INFO: array (
  'datetime' => '2019-05-17 12:00:00',
  'account_name' => 'KKK',
  'platform_bank_id' => '100001',
  'platform_bank_name' => 'BANK',
  'amount' => 100.52,
  'total_amount' => 200.50999999999999,
)
```
### However
The data I get when I use the `$request->get("total_amount")`  receive parameters is correct.

**Comment by driesvints** [comment]
I just tested this with the exact same setup and it works for me. Maybe there's some php.ini setting that could cause this? 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

This issue is also not locked and everyone is still free to discuss solutions to your problem!

Thanks!
