### ISSUE TITLE
Wrong value type for typeBoolean

### ISSUE THREAD

**Issue by mason-chase** [laravel/framework#28646]
- Laravel Version: 5.8.x
- PHP Version: 7.#.#
- Database Driver & Version: MySql 5.7.x

### Description:
typeBoolean in `MySqlGrammer.php` is returning wrong type `tinyint` which must change to `bit(1)` for standard MySQL for boolean value.

### Steps To Reproduce:
`MySqlGRammar.php`
```
  protected function typeBoolean(Fluent $column)
    {
        return 'bit(1)';
    }
```

**Comment by mfn** [comment]
> which must change to `bit(1)` for standard MySQL for boolean value.

Where does it say so?

I can only find https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html as well as https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html :
> BOOL, BOOLEAN
>
> These types are synonyms for TINYINT(1). A value of zero is considered false. Nonzero values are considered true: 

🤷‍♀️

**Comment by mason-chase** [comment]
hi mfn,

using `tinyint` means you are using 8 bits of data for storing only 1 bit, unless if you have values other than 0 and 1 or false and true, using tinyint is only adding 8 times more data/load to the SQL server.

Here is the link : https://dev.mysql.com/doc/refman/8.0/en/bit-type.html

**Comment by MattWohler** [comment]
Related to PR: #28650

**Comment by rs-sliske** [comment]
computers cant address individual bits, the smallest they can address is bytes

to store individual bits, you either need to waste 7 bits of space, or do extra processing to store multiple bits in the same byte (eg if you have multiple boolean fields you could store them in the same byte rather than 1 byte each)

it would depend on use case etc but in most situations the wasted bits are generally taken over the extra processing to pack/unpack

**Comment by driesvints** [comment]
We probably won't be changing this anytime soon. If you have a viable use-case for this and would like to see this changed, feel free to open up an issue on the ideas repo to discuss this. Thanks.
