### ISSUE TITLE
`Builder::where()` with only one parameter acts like `whereNull()`

### ISSUE THREAD

**Issue by liam-wiltshire** [laravel/framework#28664]
- Laravel Version: 5.8.2
- PHP Version: 7.2.16
- Database Driver & Version: mySQL (MariaDB) 10.3.12

### Description:
Making a call to `Builder::where()` with only a single `$column` param makes the method act like `whereNull()`. Even in a 'worst case' scenario, I'd expect it to be the opposite (i.e. where not null), although I'd argue it's better to just disallow calling `where()` with a single param.

### Steps To Reproduce:
Create a basic DB call using where with a single param - e.g.:

`echo DB::table("staff")->select("*")->where("name")->toSql();`

the output will look like ```select * from `staff` where `name` is null```

### Notes
It looks like this is the case as all other columns default to null, but the `prepareValueAndOperator` method only acts when there are exactly two params passed, so value is still `null`.

Assuming this isn't expected behaviour (I cannot see documentation anywhere suggesting it should be!), I would suggest that trying to call `where` with only one param should throw an exception, or _maybe_ act as where not null, but that still doesn't make much sense.

Happy to submit a PR assuming it's confirmed this isn't expected/intended behaviour.

**Comment by driesvints** [comment]
I think it's a matter of perspective in this case. For me personally this is the expected behavior. The method signature is the following:

```php
where($column, $operator = null, $value = null, $boolean = 'and')
```

So for me it's a `where` clause with the default operator and a value of `null`. I'd expect that to act like `whereNull`.

If you wish to change this behavior feel free to open up an issue on the ideas repo to get support for your idea. After that you can submit a PR. If this is changed then the best branch to target this is `master`.
