### ISSUE TITLE
Request url/segments are not available while unit testing

### ISSUE THREAD

**Issue by MarekGogol** [laravel/framework#28773]
- Laravel Version: v5.8.21
- PHP Version: 7.2.17
- Database Driver & Version: mysql 5.7

### Description:
request()->url() and request()->segments() are not available while service providers are under register/boot state, but this happens only in phpunit environment. In normal laravel app environment this variables are fully available in this states. Also when testing with dusk, variables are available, problem is just in phpunit.

### Steps To Reproduce:
routes/web.php
```
Route::get('/one/two', function () {
    return "\n".request()->url();
});
```

AppServiceProvider.php
```
public function boot()
{
    echo request()->url();
}
```

tests/Feature/ExampleTest.php
```
public function testBasicTest()
{
    $response = $this->call('GET', '/one/two');

    dd($response->getContent());
}
```

### Expected behavior in phpunit?
This is also normal behavior in basic laravel app while testing in browser. First AppServiceProvider returns echo with correct url, and then route returns second time same correct url.
![image](https://user-images.githubusercontent.com/11134410/59158918-06918780-8ac2-11e9-976b-81e1fafb5296.png)

### Actual behavior in phpunit
First AppServiceProvider returns wrong url path, but route returns correct url.
![image](https://user-images.githubusercontent.com/11134410/59158922-19a45780-8ac2-11e9-854a-656da3d0db66.png)

### Where would problem happen with this kind of behaviour?
- If someone would register routes in RouteServiceProvider with some conditions from url, in normal app it will work, but in phpunit developer would have problem. For example I register language prefix for all routes dynamically, but I do not want register in every pages, because It cost me DB queries...
- if someone would set global app language in AppServiceProvider, but for example just for everything if first segment is /admin route.

### Same issue from 2017 #18678
I found same issue from 2017th, but I could not find answer for this issue.
https://github.com/laravel/framework/issues/18678

Thank your for reply,
have a nice day.

**Comment by driesvints** [comment]
I have to admit that I'm not sure why the behavior is different. I think it's because you're operating in a CLI context for the unit test and the request isn't bootstrapped for that context. But not entirely sure. I'll leave this open for a bit to see if someone else can provide some other insights.

**Comment by meyer59** [comment]
Same problem here

**Comment by R1Daneel** [comment]
is there any news about this issue?

**Comment by crynobone** [comment]
> I think it's because you're operating in a CLI context for the unit test and the request isn't bootstrapped for that context.

@driesvints has given the complete answer on this, Matter of fact in PHPUnit a request object is only generated after the app is has booted and when the test actually called `call()`, `post()`, `get()`, `put()`, `delete()` request.

Can this be fixed? Not possible in PHPUnit because you to prepare the request before booting the app, but you need to app to prepare the tests such as running migration etc.

This is why you don't have this issue with Laravel Dusk.

**Comment by driesvints** [comment]
Thanks for the explanation @crynobone. It doesn't seems that we can fix this but if anyone wants to give it a go feel free to send in a PR.
