### ISSUE TITLE
Add tests to the RedisManager

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/framework#28852]
We need to add tests for the RedisManager as it was discussed in the https://github.com/laravel/framework/pull/28830

**Comment by LS05** [comment]
Hey @TBlindaruk do you think this is doable for a first-time contributor? :)

**Comment by TBlindaruk** [comment]
@LS05 , I think yes )

**Comment by LS05** [comment]
I'm trying to test the RedisManager class. 

My plan is to check if the configuration provided to the connector, contains the following values: `scheme`,  `host`, `password`, `port`, `database`. I was thinking to do this by using a mocked connector, getting its configuration (that has been parsed by the RedisManager), and do the necessary assertions in the test method.

The problem is that the method that instantiate a connector, is `protected`, so I cannot configure it to return my mocked class.

How can I work around this? I don't think using reflection is the best idea, because it will not be a clean solution.

**Comment by TBlindaruk** [comment]
@driesvints

**Comment by driesvints** [comment]
I'm sorry but I don't have any time to look at this myself atm. @mathieutu can you maybe help out with this since you sent in the original PR?

**Comment by LS05** [comment]
I can also try to create a PR with the changes for testing :)

**Comment by mathieutu** [comment]
Hi, sorry but I will not investigate on that. I'm not using Redis on my side, and will not have time to do it. However, I'd be glad to review some code. 

Please feel free to try @LS05!

**Comment by LS05** [comment]
Could one option be to change the `RedisServiceProvider`?

So when the `RedisManager` is [instantiated](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Redis/RedisServiceProvider.php#L21), we already know which driver is being used, or configured to be used.
So we can instantiate the connector in the `register` method of the `RedisServiceProvider`, and provide it to the constructor.

Something like this (where `getConnector` is a private method of the `RedisServiceProvider`):

```
public function register()
{
    $this->app->singleton('redis', function ($app) {
        $config = $app->make('config')->get('database.redis', []);
        $connector = $this->getConnector($config);

        return new RedisManager($app, $connector, $config);
    });

    $this->app->bind('redis.connection', function ($app) {
        return $app['redis']->connection();
    });
}
```

What do you guys think?

**Comment by TBlindaruk** [comment]
@LS05 , you can send a separate PR with these changes with an explanation of why it is needed.

**Comment by Vendin** [comment]
@mathieutu @TBlindaruk 
Hello, today I learned about the "enhancement" label.
I will be happy to help, I added the test.
The test fails without commit https://github.com/laravel/framework/pull/28830/commits/74b4267278c0b80c1aec36b21dab16ba69689d20 , checked.
PR https://github.com/laravel/framework/pull/29455
