### ISSUE TITLE
Validator can't validate fields with integer names

### ISSUE THREAD

**Issue by f0rtis** [laravel/framework#29116]
- Laravel Version: 5.8.21
- PHP Version: 7.1.26
- Database Driver & Version: doesn't matter
### Description:
In-built validator can't validate fields if field name is an integer. It replaces field names to 0,1,2,...
The issue is located in \Illuminate\Validation\Validator::addRules:842
```
$this->rules = array_merge_recursive(
    $this->rules, $response->rules
);

```
### Steps To Reproduce:
Create validator with rules like `['12' => 'required']`, E.g. 
```
$validator = Validator::make(['12' => 'test'], ['12' => 'required']); 
$validator->getRules() === [0 => ['required']]; // true
```

PS. I know it's how PHP behaves when doing array_merge_recursive and I can avoid this by adding any letter to the field name, but in my case we need to have name as integer.

**Comment by driesvints** [comment]
We could use the + operator instead but that would change the behavior and lead to the problem that any duplicates of the second array are ignored. There isn't a real solution to this I'm afraid. I suggest you always indeed prefix array keys because numeric keys are always tricky to work with in PHP.
