### ISSUE TITLE
Pivot Tables and support for non auto incrementing IDs

### ISSUE THREAD

**Issue by GlitterCakes** [laravel/framework#29153]
- Laravel Version: 5.8.28
- PHP Version: 7.2.9
- Database Driver & Version: MySQL

### Description:
Eloquent methods such as sync(), attach(), and detach() will not function correctly when the primary key column requires assignment and is not an "auto incrementing" column. Model events such as "creating" are never called, which is a common place to add automatic assignment (such as UUIDs). The query looks to be manually fired off with no events involved and thus no way to auto assign these via a hook.

### Steps To Reproduce:
Call sync() on a pivot table whose primary key is not setup for auto incrementing, where manual assignment is required for each row.

**Comment by staudenmeir** [comment]
This functionality has been added in #27571.

What does your relationship and pivot model look like?

**Comment by GlitterCakes** [comment]
PAGES
===
id CHAR(36), primary key

TAGS
===
id CHAR(36), primary key

PAGE_TAGS
===
id CHAR(36), primary key
page_id CHAR(36)
tag_id CHAR(36)
[Unique index placed on page_id and tag_id]
[Foreign keys from page_id to pages table and tag_id to tags table]

**Comment by staudenmeir** [comment]
The table schema doesn't help us. We need to see the `BelongsToMany` relationship and the pivot model.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by perezale** [comment]
Hi, I've came across this too (Currently with Laravel 6), this has been here for a while

It's like the [Many to Many](https://laravel.com/docs/6.x/eloquent-relationships#many-to-many) example from Laravel docs but with this change:
```
role_user
    id - no_autoincrement
    user_id - integer
    role_id - integer
```

In our case, we added a 'uuid' id column. 
This is our relationship definition (we've got an AlertTrigger instead of Role):

```php
// App\AlertTrigger.php

public function alert_trigger_users()
{
    return $this->belongsToMany(\App\User::class, 'alert_trigger_users', 
       'alert_trigger_id', 'user_id','id')->withTimestamps();
}
```

To make _attach()_ work, we can either create records through a custom intermediate table model like _AlertTriggerUser::create()_, which handles Uuid generation like any other model or by using attach() but providing a generated uuid:

``` $alertTrigger->alert_trigger_users()->attach($user, ['id'=> Uuid::generate()])```

Perhaps we're messing up with the uuid solution (webpatser/laravel-uuid) but I'm not really sure. I think it's about non-autoincrementing columns in these intermediate tables.

I'll try to reproduce this behavior on a separate project
