### ISSUE TITLE
Logout cycles remember token

### ISSUE THREAD

**Issue by halaei** [laravel/framework#29244]
- Laravel Version: 5.8 (Irrelevant)
- PHP Version: 7.2 (Irrelevant)
- Database Driver & Version: MySql (Irrelevant)

### Description:
Logging out via `Illuminate\Auth\SessionGuard::logout()` updates the user's remember token to a random string, therefore logs the user out in all other devices as well. I guess it is not the intention of the user to logout from other devices as well when they hit logout.

### Steps To Reproduce:
* log-in to a Laravel app with remember me option in a trusted browser.
* log-in to the same Laravel app in a second browser.
* log-out in the second browser.
* Close the trusted browser and wait for config('session.lifetime').
* Reopen Laravel app in trusted browser. You should be logged in, but you are not.

To me it is a bug that logout somehow acts like a "Logout from all devices" feature. If there is a reason behind it, it should be documented and letting us know how safely disable it.

### Reset password
Reset password changes remember token as well. It is not that bad though.

**Comment by florentpoujol** [comment]
It must be an intended behaviour because the `SessionGuard` hasn't changed much these past years,  and it is actually tested in `\Illuminate\Tests\Integration\Auth\AuthenticationTest::test_logging_in_out_via_attempt_remembering()`

```php
    public function test_logging_in_out_via_attempt_remembering()
    {
        $this->assertTrue(
            $this->app['auth']->attempt(['email' => 'email', 'password' => 'password'], true)
        );
        $this->assertInstanceOf(AuthenticationTestUser::class, $this->app['auth']->user());
        $this->assertTrue($this->app['auth']->check());
        $this->assertNotNull($this->app['auth']->user()->getRememberToken());

        $oldToken = $this->app['auth']->user()->getRememberToken();
        $user = $this->app['auth']->user();

        $this->app['auth']->logout();

        $this->assertNotNull($user->getRememberToken());
        $this->assertNotEquals($oldToken, $user->getRememberToken());
    }
```

**But I definitely agree with you that login out (or in) shouldn't cycle the remember token.**

--- 

The method `\Illuminate\Auth\EloquentUserProvider::retrieveByToken()` return null if the user exists but its token (in the DB) is not the one from the remember cookie.

So, yeah, _changing the remember token effectively log-out from all devices where the user has an obsolete session_.

But funny thing (but also an unintended behavior ?): the `SessionGuard::logoutOtherDevices()` method do not change the remember token, just the password.  
It means that if you have a remember cookie, with the old password but the right user id and remember token _and that you do not use the `AuthenticateSession` middleware_ you will still be considered as logged-in.

The `\Illuminate\Auth\Middleware\Authenticate` middleware and the Session guard do not check the password from the remember cookie: the existence of the user id, and the match of the remember tokens is enough to log the user in.

---

If someone from the Laravel team could confirm that the current behaviour is indeed bogus, my suggestion for a fix (of both behaviours described) would be simply to cycle the remember token in `logoutOtherDevices()` but not in `logout()`.

**Comment by driesvints** [comment]
I agree that this probably is a bug. Welcoming help with figuring this out.

**Comment by driesvints** [comment]
> Laravel also provides a mechanism for invalidating and "logging out" a user's sessions that are active on other devices without invalidating the session on their current device. 

Just realized that the current behavior is indeed the correct one and this isn't a bug. 

Use `logout` => logs you out from all devices.
Use `logoutOtherDevices` logs you out from all devices but the current one.

Maybe the docs could be updated on this though.

**Comment by dwightwatson** [comment]
`logoutOtherDevices` requires the user entering their password though. 

`logout` does it across all devices from really doesn't seem like the expected behaviour here - what other website do you log out from then then logs you out across all other devices?

Is there a sanctioned way to log the user out on just their current device?

**Comment by driesvints** [comment]
@dwightwatson no, don't think so. Maybe this could be a good new feature as a `logoutCurrentDevice` method?

**Comment by halaei** [comment]
@driesvints I am a little confused about why this issue is closed.

**Comment by driesvints** [comment]
@halaei you said: 

> I guess it is not the intention of the user to logout from other devices as well when they hit logout.

But it is. Hence is why the issue was closed.

**Comment by halaei** [comment]
@driesvints Have you even checked out how logout button works in either of Google, Facebook, Instagram, Telegram, WhatsApp, GitHub, Gitlab, Bitbucket, Trellto, ...?

I hope it is a soon to be fixed issue no matter the disagreement. But it is not my first time I bring an issue regarding auth and it gets closed without being fixed. I need a chance to discuss it in a constructive way, but I don't see enough interest :(

**Comment by driesvints** [comment]
@halei again: this isn't a bug but the expected behavior. Also see the discussion on the PR by @dwightwatson here: https://github.com/laravel/framework/pull/29376

**Comment by halaei** [comment]
@driesvints Having a wrong expected behaviour is a bug. Your exception is against all the majority of popular applications, sites and games.

**Comment by crynobone** [comment]
> Having a wrong expected behaviour is a bug.

The behaviour was introduce in `v5.0.30` and has gone through 2 LTS and 6 major releases (See commit <https://github.com/laravel/framework/commit/c5ac19e1eb809c486b04e0f6867aeaf0e81e7afd>). It was introduced based on proposal <https://github.com/laravel/framework/issues/2444>. 

It's not a bug because it was changed to cover specific behaviour. What you are asking is a different behaviour to be covered as well because you have a requirement for it.

**Comment by halaei** [comment]
@crynobone I seems the behaviour exists in prior versions as well:
Laravel 4.0:
```php
class Guard {...
	public function logout()
	{
		$user = $this->user();
		// If we have an event dispatcher instance, we can fire off the logout event
		// so any further processing can be done. This allows the developer to be
		// listening for anytime a user signs out of this application manually.
		$this->clearUserDataFromStorage();
		if ( ! is_null($this->user))
		{
			$this->refreshRememberToken($user);
		}
...
```
Even if you are right about when this behaviour was introduced, it is still a bug introduced by wrong understandings about how logout button should work.

I don't know why you make it so difficult and why you are so attached to this bug. What do you like about this bug:
1. When you login to your google account on your friends computer and then you log out when you are done, do you expect to be logged out on your own mobile as well?
2. If someone tells you Laravel Auth is terrible because it has inconvenient behaviours and you shouldn't use it in your projects, referring to issues like this one, how can you defend Laravel?

Again this is not my first time I bring such issues about Auth and the core team closes the issue without any fix. As an occasional contributor to Laravel source code I am telling you it is a terrible attitude and it hurts a lot.

**Comment by driesvints** [comment]
@driesvints Having a wrong expected behaviour is a bug. Your exception is against all the majority of popular applications, sites and games.

Like @crynobone said, this behavior has been in the core for quite a while already. If we would change it now it would be too much of a breaking change for everyone relying on this behavior.

> wrong understandings about how logout button should work

You're basically saying here that your way is the only correct way.

> it is a terrible attitude and it hurts a lot.

We need to account for more people than just you. There's so many people using the framework. If we change this default behavior then it'll break someone else's app. 

Let's see how the PR from above goes. At least you'll then have a method which you can use for your use-case.

**Comment by halaei** [comment]
> You're basically saying here that your way is the only correct way.

Yes exactly. I am 100% against any other ways regarding how logout button should work.

> We need to account for more people than just you.

I understand the value of your job. You are doing amazing and I am thankful. What I am trying to say is to give feedback about an aspect that I believe needs change: the way you close issues like this. Again if we can't understand each other regarding this, it is still fine.

> There's so many people using the framework. If we change this default behavior then it'll break someone else's app.

We shouldn't consider breaking changes between major releases when fixing a bug or improving a behaviour. We need to ensure smooth upgrade process though.

> Let's see how the PR from above goes. At least you'll then have a method which you can use for your use-case.

I hope the PR goes well. Also please consider a chance for my use-case being the default one, because it is not really only "my" use-case.
Sorry for all the trouble.

**Comment by driesvints** [comment]
>  the way you close issues like this. 

But this issue tracker isn't for feature requests or if you want to change additional behavior. It's only for tracking bugs. That's clearly indicated when you open up an issue with the issue templates. That's why I closed it. I understand that you opened the issue first because you thought it was a bug. But it's better now if you take this up in an issue on the ideas repo for further discussion.

> We shouldn't consider breaking changes between major releases when fixing a bug or improving a behaviour. We need to ensure smooth upgrade process though.

We should definitely do so. Letting people upgrade without too much hassle is always a better choice unless a breaking change is really warranted. The next Cashier release, for example, will have lots of breaking changes but that's because the underlying Stripe API also changed a lot so it was warranted.

> I hope the PR goes well. Also please consider a chance for my use-case being the default one, because it is not really only "my" use-case.

You can always attempt a new pr at the same time and let Taylor choose which one he thinks is the better approach.

> Sorry for all the trouble.

No worries. We're all adults. It's good that you brought this to our attention because I wasn't aware of the default behavior either. We all learned something. Overall I really like your comments and replies on the Laravel repositories. You're always a great help 👍
