### ISSUE TITLE
job is not dispatching

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/framework#29298]
- Laravel Version: 5.8.28
- PHP Version: 7.2
- Queue Driver: Redis + Laravel Horizon
- Redis Client: PhpRedis 4.3
- Redis Server: RedisLabs -> Redis Version Compliance 5.0.4

### Description:
Roughly 10,000 jobs are queued and processed per hour. I notice that some jobs are not dispatched. I assume that a lot more jobs are not dispatched but these particular jobs are important so I put logging into them

```
    // dispatch important job
     ImportantJob::dispatch($task)->onQueue('urgent'); 
```

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Support\Facades\Log;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class ImportantJob implements ShouldQueue
{

    public function handle()
    {
        Log::channel('slack')->alert('Processing Job for Task#' . $this->task->id);
        // do important thing
    }

    /**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed(Exception $exception)
    {
        Log::channel('slack')->alert('Failed to execute Task#' . $this->task->id);
    }
```

I consistently do not receive some of the jobs and I don't receive any errors reported. So I have to assume that the jobs are not dispatched to Horizon to process. 

I don't know if this has to do with Redis 5.0.4 (#29029 ). Out of 10,000 jobs are queued per hours, roughly 100 of important jobs are queued. Roughly 20 of them are not dispatched. That is roughly 20 out of 10,000 jobs I know for sure that do not dispatch. The number of non-dispatched jobs may higher.

Any suggestions?

### Steps To Reproduce:
Use Redis Queue with Horizon, create a script that queues roughly 200 jobs per minutes. some of the jobs will not dispatch

**Comment by mfn** [comment]
> Any suggestions?

Use the Job Events https://laravel.com/docs/5.8/queues#job-events to perform a detailed tracking; there two more which are not in the docs and might be useful:
- `::exceptionOccurred`
- `::failing`

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by kapsampelis** [comment]
I have the same problem.
Im using database queue .
@michaelnguyen547 did you solved it ?

**Comment by fico7489** [comment]
same here

**Comment by katjackson** [comment]
I'm having the same issue. I can't tell if the jobs are never dispatched, or if they are dispatched but not picked up.

**Comment by zacharias-pavlatos** [comment]
> I'm having the same issue. I can't tell if the jobs are never dispatched, or if they are dispatched but not picked up.

Well in my case i have done something wrong with the controllers so  my job was never dispatching because i was never calling it . I know its a stupid answer but make sure you are dispatching the job first before you dive deeper .

**Comment by cxyguopong** [comment]
I have the same issue

**Comment by katjackson** [comment]
In my case, it was an issue with redis memory.

**Comment by aidangoodman7** [comment]
I was having a similar issue with inconsistency in dispatching when using the database queue driver. Most jobs were dispatching, but some in particular weren't. Fixed by getting rid of uniqueId() and ShouldBeUnique implementation. I may have been implementing it wrong, but didn't need it anyway.

**Comment by ugurarici** [comment]
Today, I encountered a similar issue on my development machine.

After thorough investigation, I identified the root cause. The problem stemmed from the usage of `ShouldBeUnique` and a caching issue.

The particular job in question was designed to be unique, implementing the `Illuminate\Contracts\Queue\ShouldBeUnique` interface. During my debugging attempts on the development machine, I utilized `die()` within the job. Surprisingly, this action terminated the process, but the cache associated with the job's uniqueness was not cleared. This discrepancy occurred because the worker remained unaware that the process had concluded, given that I had abruptly terminated it using `die()`.

My understanding is that the queue handler failed to receive the end-of-process signal, resulting in the failure to clear the dependent cache key. In cases where a job is unique, the application generates a cache key using the formula: `'laravel_unique_job:'.get_class($job).$uniqueId`. (For more details, refer to: [link](https://github.com/laravel/framework/blob/59c509b298f755d066b8423ed7fb193fb44f6553/src/Illuminate/Bus/UniqueLock.php#L61-L74))

To resolve the issue, I executed `php artisan cache:clear`. Instead of employing `die()` or `dd()` within jobs for debugging purposes, I opted for a more effective approach:
```php
dump($foo);
return;
```

This adjustment successfully addressed the problem I was facing.

**Comment by ugurarici** [comment]
Today, I had a similar problem on my computer while working on a project.

I found out that the issue was caused by using `ShouldBeUnique` and a cache problem.

The specific task I was dealing with needed to be unique, following the `Illuminate\Contracts\Queue\ShouldBeUnique` rules. When I tried to debug by using `die()` in the task on my development machine, it stopped the process, but the cache related to the task's uniqueness didn't get cleared. This happened because the worker didn't know that the process had finished, as I had forcefully stopped it with `die()`.

In simple terms, the queue handler didn't get the signal that the process had ended, so it didn't clear the necessary cache.

For unique tasks, the application creates a cache key using the formula: `'laravel_unique_job:'.get_class($job).$uniqueId`. You can check it [here](https://github.com/laravel/framework/blob/59c509b298f755d066b8423ed7fb193fb44f6553/src/Illuminate/Bus/UniqueLock.php#L61-L74).

To fix the problem, I ran `php artisan cache:clear`. Instead of using `die()` or `dd()` for debugging inside tasks, I now use a simpler approach:
```php
dump($foo);
return;
```

This change solved my problem.

**Comment by NBA707** [comment]
I am running into this.   A controler has:

```
Log::info('VendorQuoteImport: Dispatched ' . $cacheKey);
ProecessVendorQuoteProcess::dispatch($cacheKey);
```

Job has:

```
public function handle()
    {
        Log::info('Process Vendor Quote Process: ' . $this->cacheKey);
        \Artisan::call("vq:process " . $this->cacheKey);
    }
```

The log shows the log entry from the controller but not the job itself.  I had thought based on searching that the ShouldBeUnique is causing the issue but it is not.

```
class ProecessVendorQuoteProcess implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
```

Issuing the artisan cache:clear does resolve it but not helpful.   I add that as a cron job to execute every hour.   

I changed from file cache to redis cache and am testing now, but I really need ::dispatch to work all the time

**Comment by tom-it** [comment]
> In my case, it was an issue with redis memory.

please elaborate, I'm facing the same issue, clear cache, optimize, nothing helps, jobs dont get dispatched :(

**Comment by phendron** [comment]
Anyone else who comes across this problem;
If you dispatch without a parameter for time urgency you just initialise the extended job class so you never reach handle. 

`RTFM::dispatch()->withoutDelay();`
`RTFM::dispatch()->delay(now()->addMinutes(10));`

From @michaelnguyen2021 job dispatch snippet l:

`  // dispatch important job
     ImportantJob::dispatch($task)->onQueue('urgent');`

It is never dispatched due to the missing `withoutDelay()` or `delay(time)` functions.
