### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by ronssij** [laravel/framework#29323]
- Laravel Version: 5.8
- PHP Version: 7.2.20
- Database Driver & Version: Mysql 5.7.19

### Description:

I created a Custome validation with these rules:

```
return [
 'name'        => 'required',
 'image'       => 'required',
 'category'    => 'required',
 'description' => 'required',
];
```

On the Rest Client, It is working. but when I used it on Axios (NuxtJs) the validation does not apply.

```
return this.$axios.post('/api/user/upload-image', data, {
        headers: {
          'Content-type': 'application/x-www-form-urlencoded',
        }
      });
```

### Steps To Reproduce:

I had changed the rules with this.

```
form: {
 description: '',
 category: '',
 image: null,
 name: '',
}
```

Why do I need to make all the value to be an empty string just to fill up the `required` rule?

**Comment by ahinkle** [comment]
`Required` is null, an empty string, an empty array, empty Countable object or an uploaded file with no path.

https://laravel.com/docs/5.8/validation#rule-required

If you need further assistance creating your validation rules, please reach out on our community channels instead of this issue area:`
- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)

**Comment by ronssij** [comment]
I do understand how the `required` rule work. but in the instance of having all fields with null value using FormData().

And i'I'll try reach on the community communication channels.

**Comment by mikerockett** [comment]
@ronssij The reason for that is because FormData isn't type-safe (the value of each boundary is always either a Blob (such as a file) or a USVString (a unicode scalar values string).

So, if your object-payload includes a value of `null`, it is seen as a string of `'null'`, which means validation will pass.

To solve this, I split the payload into two concerns: the first is the boundaries for each file, and then a single boundary containing a JSON payload that needs to remain type-safe. A little middleware trickery then comes into play to extract the payload and merge it into the request before passing it to the rest of the pipeline, which means you can access the request payload as normal, and validation will also continue to work as normal.

Here's the JS helper that converts a JSON payload accordingly:

```js
// form-data.js
export default object => {
  let data = new FormData(), json = {}

  Object.keys(object).reduce((object, key) => {
    if (object[key] instanceof File) {
      data.append(key, object[key])
    } else {
      json[key] = object[key]
    }
    return object
  }, object)

  data.append('json', JSON.stringify(json));

  return data
}
```

```js
import formData from './form-data'

this.$axios.post('/api/user/upload-image', formData(data), {
  headers: {
    'Content-type': 'application/x-www-form-urlencoded',
  }
});
```

And here's the middleware you can use to parse the payload and merge it into the request:

```php
<?php
namespace App\Http\Middleware;

use Closure;

class ParseFormData
{
  /**
   * @param  \Illuminate\Http\Request  $request
   * @param  \Closure  $next
   * @return mixed
   */
  public function handle($request, Closure $next)
  {
    $isFormData = str_contains(
      $request->headers->get('content-type'),
      'multipart/form-data'
    );

    if ($isFormData && $request->has('json')) {
      $request->merge(json_decode($request->json, true));
      $request->request->remove('json');
    }

    return $next($request);
  }
}
```

To confirm, this is not a problem with Laravel's validation, but rather with the source of the data.

**Comment by ronssij** [comment]
@mikerockett 
Thanks for explaining! I am using the FormData() to upload an image.

Pertaining to this statement.
> So, if your object-payload includes a value of null, it is seen as a string of 'null', which means validation will pass.

Why is it `it is seen as a string of 'null'` on the validation but then when you dump the `$request->all()` all object-payload with null value is seen as null not 'null'?  

Custom validation uses this `Illuminate\Foundation\Http\FormRequest;` which has also Request base on `Illuminate\Http\Request;` which is used by the controller.

It's a little bit confusing. But your explanation might help and I'll try it. I'll close this one until some will also encounter this one :D
