### ISSUE TITLE
Laravel Mix - Hot file issue

### ISSUE THREAD

**Issue by jonathanmacgregor** [laravel/framework#29621]
- Laravel Version: 5.8.32
- PHP Version: 7.3.3
- Database Driver & Version: 

### Description:
When using Laravel mix to load assets, the URL generated includes the Hot reload domain and port. Even when not using hot reload.
`<link href="{{ mix('/css/app.css') }}" rel="stylesheet"/>` 
Returns the following
`<link href="http://localhost:1022//css/app.css" rel="stylesheet"/>` 
It looks like a file called `hot` is specified within the public folder, which causes the problem, as this file exists and is created automatically by Laravel and is checked for in `Mix.php`
The `hot` file contents are:
`http://localhost:1022/`

### Steps To Reproduce:
Fresh install of Laravel, edit welcome.blade.php and add `<link href="{{ mix('/css/app.css') }}" rel="stylesheet"/>`
Check the console, an incorrect URL appears and the assets cannot be found at that URL.

**Comment by ankurk91** [comment]
You can manually delete the `public/hot` file and the `mix()` blade helper should behave normal now.
Usually [laravel-mix](https://github.com/JeffreyWay/laravel-mix) should auto delete this file, but it may left there for various reasons.

In order to delete the `public/hot` file properly, we need to add this patch 
```js
// Make sure to delete the `hot` file when user press CTRL+C
// https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js
process.on('SIGINT', () => {
  deleteHotFile();
  process.exit(0);
});

// Detect IDE window close action
process.on('SIGHUP', () => {
  deleteHotFile();
  process.exit(0);
});
```
The same approach works fine with my custom made webpack solution, [laravel-bundler](https://github.com/ankurk91/laravel-bundler)

**Comment by nmfzone** [comment]
@jonathanmacgregor Are you sure the `Steps To Reproduce` just like that? Fresh install of Laravel don't include `mix-manifest.json`, so if you just write `mix('/css/app.css')`, it should throw an error, since you haven't run `yarn run hot/dev`.

Anyway, I think this is not an issue, it's just use don't use it correctly. Since the `hot` file is still exists, it means you just run `yarn run hot` before, then you stop it, just open the web without build the assets using `yarn run dev`.

**Comment by jonathanmacgregor** [comment]
Apologies, i missed the `yarn run dev` command off the steps to reproduce. I haven't ever run `yarn run hot` command before. and it still does it.

**Comment by nmfzone** [comment]
@jonathanmacgregor Ah ok if that the case. Ok now, are you sure you don't run `yarn run hot` before? So why the `hot` file inside your public folder (`It looks like a file called hot is specified within the public folder`)? The default Laravel instalation doesn't come with `hot` file :/

**Comment by jonathanmacgregor** [comment]
@nmfzone it isn't there when i install. But when i run the application it is created automatically.

**Comment by nmfzone** [comment]
@jonathanmacgregor Huh, what do you mean run the application? What `laravel-mix` version you're using?
Actually I've follow your step, but can't reproduce your issue. Could you try to reproduce again with fresh Laravel installation?

**Comment by devcircus** [comment]
How are you creating a "fresh install"? The first I've ever heard of this happening. 

I just installed with "laravel new" and couldn't reproduce. 

Probably better to ask around on some of the community support channels.

**Comment by jonathanmacgregor** [comment]
I've spent the last few hours reinstalling my mac completely. I believe it was an issue with Laravel valet somehow. 
It works now without issue.
