### ISSUE TITLE
unsetEventDispatcher disables events for all models

### ISSUE THREAD

**Issue by rebaz88** [laravel/framework#29727]
- Laravel Version: 5.8.33
- PHP Version: 7.2.19
- Database Driver & Version: Mysql 5.7.27

### Description:
The Model::unsetEventDispatcher() disables events for all models in the same function

### Steps To Reproduce:
1- Create two different models each with a different event.
2- FirstModel::unsetEventDispatcher();
3- FirstModel::save();
4- SecondModel::save();

The event for Second model should still run because we have only unset the first model's event. But now events for all models inside tge function will be disabled

**Comment by X-Coder264** [comment]
This is the expected behavior. The event dispatcher is a static property of the base Eloquent `Model` class. It means that all models share the same event dispatcher and that calling `FooModel::unsetEventDispatcher();` is the same as calling `\Illuminate\Database\Eloquent\Model::unsetEventDispatcher();`. That is why when you unset the event dispatcher on `FirstModel` it's also unset on `SecondModel` and on all other models too.

**Comment by rebaz88** [comment]
@X-Coder264 then the dispatcher has to be set again.
unset dispatcher
run FooModel
set dispatcher
run BarModel

Is there a reason why it is a static property? if so why is it neccessery to specify the model, instead of one global set/unset for the base Eloquent Model?

**Comment by X-Coder264** [comment]
The event dispatcher is a static property that is set by the framework during booting (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/DatabaseServiceProvider.php#L25).

It's made this way because the `illuminate/database` package must be usable as a standalone component without the `illuminate/events` package (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/composer.json#L38).

Yes, if you set the dispatcher again before running `BarModel::save()` the events for that model will be properly dispatched. To prevent this confusion always set or unset the dispatcher by referencing the `\Illuminate\Database\Eloquent\Model` class.

**Comment by rebaz88** [comment]
Thank you @X-Coder264

**Comment by Maxcrazy1** [comment]
I share a solution 🚀


`// getting the dispatcher instance (needed to enable again the event observer later on)
$dispatcher = YourModel::getEventDispatcher();

// disabling the events
YourModel::unsetEventDispatcher();

// perform the operation you want
$yourInstance->save();

// enabling the event dispatcher
YourModel::setEventDispatcher($dispatcher);`

**Comment by dealense7** [comment]
I just found same error, so you can use `saveQuietly` method in case to disable events on the model :))
