### ISSUE TITLE
queue:work --timeout=0 stops after average 321 processes

### ISSUE THREAD

**Issue by Silassiai** [laravel/framework#29926]
Hi Guys,

I am running laravel 5.8 
I have a listener (AddSubscribersToQueue) that adds subscribers (in chunks of 500) to an event (SendCampaign).
The listener (SendCampaignToSubscriber) corresponding to the event SendCampaign is processing this subscribers without any errors.
While processing the subscribers in (SendCampaignToSubscriber) the listerner adds a new record into my database for each subscriber.

The strange thing is that the second listener (SendCampaignToSubscriber) stops after the average 320 successfull processess. 
My failed_jobs table is empty. i increased my memory_limit from 2048 to 4096 without any success.
The max_execution_time is set to 0

The command that i run is. (same as my supervisor that stopped) >
`php artisan queue:work --timeout=0`

When i run the command again, it stops again after the next average 320
![Screenshot_5](https://user-images.githubusercontent.com/18419961/64563485-d1f6cb80-d34f-11e9-96e6-aff16d602756.jpg)

Hope someone can help me out 👍

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is actually by design. Once your queue worker exceeds a certain amount of memory usage (by default 128MB), it will exit with error code 12. You need to supervise the process, and start it again after it shuts itself down so your system can reclaim the memory.

NB The memory limit is not related to your PHP memory limit. I'd recommend diving into the source code of the framework actually, so you get to see what's really going on: https://github.com/laravel/framework/blob/v5.8.35/src/Illuminate/Queue/Worker.php, https://github.com/laravel/framework/blob/v5.8.35/src/Illuminate/Queue/WorkerOptions.php.

**Comment by GrahamCampbell** [comment]
I'd recommend having a read of the docs at https://laravel.com/docs/5.8/queues#running-the-queue-worker also. In particular:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/2829600/64568015-8c3b0280-d351-11e9-81c1-e1977c0159d9.png">

**Comment by Silassiai** [comment]
Hi @GrahamCampbell,

Thanks for your awnser. Found that it hits the error code 12.
But... my supervisor does not finishes the job, while it it still running.

Does it has something to do with a new event inside the listener?
