### ISSUE TITLE
[6.0] Increasing memory with QueryExecuted event.

### ISSUE THREAD

**Issue by kevinvdburgt** [laravel/framework#29952]
- Laravel Version: **6.0.0**
- PHP Version: **7.3.6**
- Database Driver & Version: **mysqld  Ver 8.0.16 for osx10.14 on x86_64 (Homebrew)** 

### Description:
I have some memory issues using Laravel 6.0, while migrating over 1.5 million clients from an old legacy system to a new Laravel app we keep running out of memory.

When we remove the code `$this->event(new QueryExecuted($query, $bindings, $time, $this));` from the [Connection.php (line 683)](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Connection.php#L683) the memory stops increasing and everything works as expected.

### Steps To Reproduce:

Sample console command:
```php
/**
 * Execute the console command.
 *
 * @return mixed
 */
public function handle()
{
    $db = DB::connection('mysql_legacy');

    DB::disableQueryLog();

    $db->table('clients')->orderBy('id', 'asc')->chunk(1000, function ($clients) {
        $clients->each(function ($client) {
            $user = User::find($client->id);

            // ...
        });

        $this->info('Memory: ' . memory_get_usage());
    });
}
```

Result with the line `$this->event(new QueryExecuted($query, $bindings, $time, $this));`:
```
Memory: 30296064
Memory: 30933784
Memory: 31632872
Memory: 32233856
Memory: 32964904
```

Results with the line `$this->event(new QueryExecuted($query, $bindings, $time, $this));` removed:
```
Memory: 29567744
Memory: 29638008
Memory: 29638568
Memory: 29638256
Memory: 29638008
```

**Comment by crynobone** [comment]
Do you have any packages that might listen to those events and cause the memory spike?

**Comment by kevinvdburgt** [comment]
@crynobone That seems to be the case, coming from `facade/ignition`.

**Comment by mpskovvang** [comment]
I too experienced OOM errors after upgrading to Laravel 6.0, but it wasn't until now, I found the that Ignition package is being the root cause.

At first, all our custom Artisan commands running as daemons started restarting. Because of the automatic failure restart, we didn't investigate further at the time.

Today, a team member was importing data into the database by uploading files through our web UI. The file is handled in chunks and uses batch insertion to reduce memory usage.

After some time troubleshooting, we too tried to disable the event dispatching in the `Connection` class as the author and the issue disappeared. Short after, we found that `facade/ignition` was listening and storing these queries with its bindings.

I wasn't even aware of this reporting feature, and it turns out the default `flare.reporting.maximum_number_of_collected_queries` isn't working for this kind of workload.

We're solving this issue by disabling `flare.reporting.report_queries`.

Perhaps, reporting shouldn't be the default option but instead, show a recommendation in the Debug tab when an exception is being rendered.

Otherwise, this feature should probably be mentioned in the package description and maybe in the Laravel Docs too.

Even though we don't use the reporting feature because of the use of [laravel/telescope](https://github.com/laravel/telescope), I see the potential of the feature in this package while debugging. Having to turn it entirely off to support different use cases is a pity. Perhaps some methods like `withoutRecording`, `stopRecording`, `startRecoding` etc. inspired by the Telescope is useful?
