### ISSUE TITLE
Miss ConfirmPasswordController

### ISSUE THREAD

**Issue by felipe-balloni** [laravel/framework#30227]
- Laravel Version: 6.2.0
- PHP Version: 7.3.9

### Description:
After update today, i'm getting the error:
ReflectionException::("Class App\Http\Controllers\Auth\ConfirmPasswordController does not exist")
//vendor/laravel/framework/src/Illuminate/Container/Container.php:804

I tink it's missing in PR #30214

### Steps To Reproduce:
Just update to version 6.2.0 and use route:list

Thanks

**Comment by felipe-balloni** [comment]
Thanks to your help...

**Comment by jlaswell** [comment]
Since this breaks applications following an update, there should at least be documentation under the upgrades section of the `6.x` version.

I know with the move to v6, we've [adopted Semantic Versioning](https://laravel.com/docs/6.x/releases#versioning-scheme) and explicitly state that "minor and patch releases should **never** contain breaking changes." I think a PR to make this a opt-in is an nice workaround for a feature like this. What do you think about this sort of implementation, @driesvints?

As annoying as it may be, a patch version to fix compatibility should be applied to adhere to with Semantic Versioning.

**Comment by thejacer87** [comment]
sorry @jlaswell, im not following you. what happened in my repo that i needed to add this file?

**Comment by alagoroVigo** [comment]
> the `ConfirmPasswordController` is a userland file, it does not live in the Framework repository. You'll need to manually add it to your project.
> 
> You can copy it from the `laravel/laravel` repo here:
> 
> https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/ConfirmPasswordController.php

What next? 
still same error just creating the file. I tried composer autodump but same result:

$ php artisan route:list

   Illuminate\Contracts\Container\BindingResolutionException  : Target class [App\Http\Controllers\Auth\ConfirmPasswordController] does not exist.

  at /opt/.../vendor/laravel/framework/src/Illuminate/Container/Container.php:806
    802| 
    803|         try {
    804|             $reflector = new ReflectionClass($concrete);
    805|         } catch (ReflectionException $e) {
  > 806|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    807|         }
    808|
