### ISSUE TITLE
Mail sending without ShouldQueue but isn't when implemented

### ISSUE THREAD

**Issue by Cranavvo** [laravel/framework#30241]
**Laravel:** 6
**PHP:** 7.2
**Mail Driver:** Mailgun

Hello all, 

I'm running into this strange issue when it comes to added queues to my mail (which is using mailgun).

When I create a mailable using `php artisan make:mail StandardMail` and then use the `Mail` facade to send an email, it works fine.

However, when I add `implements ShouldQueue` and then run `php artisan queue:work` and resend the email, the queue processes (shown clearly in my console), however, no mail is sent and there is no error (and nothing to show in the logs files either).

I'm using Windows to develop on, is there something I'm missing or have I found something buggy?

**Comment by Cranavvo** [comment]
I just fixed it... apparently... using `php artisan queue:work` isn't the same as `php artisan queue:listen`.

When using `php artisan queue:listen` the mail sends, but not when I'm using `php artisan queue:work`.

**Comment by driesvints** [comment]
Glad you found it 👍

**Comment by mfn** [comment]
@Cranavvo both should send the email, though.

`work` is the preferred choice for production: it boots the framework once and then processes all jobs

`listen` OTOH creates a new process for each job on the queue (wastes resources, slower) but boots the framework everytime => suitable for development to see your source changes immediately reflected (otherwise you would have to stop the `work` command and run it again to see them).

So, from that perspective, they're not expected to be different in what they can achieve 🤷‍♀️

**Comment by Cranavvo** [comment]
> @Cranavvo both should send the email, though.
> 
> `work` is the preferred choice for production: it boots the framework once and then processes all jobs
> 
> `listen` OTOH creates a new process for each job on the queue (wastes resources, slower) but boots the framework everytime => suitable for development to see your source changes immediately reflected (otherwise you would have to stop the `work` command and run it again to see them).
> 
> So, from that perspective, they're not expected to be different in what they can achieve 🤷‍♀️

For me it is. `queue:work` runs the process however nothing happens, however, `queue:listen` runs and performs the action(s).
