### ISSUE TITLE
[6.x] VerifiesEmails.php fails with $request->route('hash'), passes with $request->get('hash')

### ISSUE THREAD

**Issue by LiamBull** [laravel/framework#30240]
- Laravel Version: 6.2.0
- PHP Version: 7.2.23
- Database Driver & Version: MySQL 5.7.27

### Description:
In \Illuminate\Foundation\Auth\VerifiesEmails.php, line 39 fails with `$request->route('hash')`, but passes with `$request->get('hash')`. I am not sure if this is a bug, but I see nothing I have done that would somehow break this function specifically right here. I have not modified my VerificationController.php file from the core either.

The `$request->route('id')` above works, but the passed ID in this route is not a parameter, but directly in the path whereas the hash is affixed as ?hash=myhash.

For reference, here is my URL: `http://localhost:8000/email/verify/8edd16a5-ad04-4782-b0fe-33f0f482d080?expires=myexpiryhere&hash=myhashhere&signature=mysignaturehere`

### Steps To Reproduce:
Attempt to verify an email. It should fail with a 403. However it doesn't seem other people are having this problem, so I am lost as to what is in fact causing this issue.

**Comment by driesvints** [comment]
We've had quite a few issues with this and most were because a route parameter was forgotten.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by chinleung** [comment]
For those who are having the same issue, the answer is right here: https://stackoverflow.com/a/58343510/5556440
