### ISSUE TITLE
[5.7] Fresh installation of Laravel 5.7.28 failed

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/framework#30257]
- Laravel Version: 5.7.28
- PHP Version: 7.3.5

### Description:
Fresh installation of Laravel 5.7.28 failed after updating step:
```
Installing laravel/framework (v5.7.28)
  - Installing laravel/framework (v5.7.28): Downloading (100%)
Created project in C:\Users\KyleK\WebCoding\framework
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/nexmo-notification-channel 1.0.x-dev requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - laravel/nexmo-notification-channel v1.0.0 requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - laravel/nexmo-notification-channel v1.0.1 requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - Conclusion: don't install nexmo/client 1.9.0
    - Installation request for laravel/nexmo-notification-channel ^1.0 -> satisfiable by laravel/nexmo-notification-channel[1.0.x-dev, v1.0.0, v1.0.1].
```

I discover the last version of 5.7 can no longer be installed with automated scripts to check Laravel compatibility. I would understand as this version is no longer supported it may not worth it to fix it. Feel free to close and I would remove this version from my compatibility tests.

### Steps To Reproduce:
```
composer create-project laravel/framework:5.7.*
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by kylekatarnls** [comment]
Hi @driesvints I don't use Laravel 5.7, as I said, I just check the compatibility of my package across different versions of Laravel (with Travis-CI) and can no longer test my package in Laravel 5.7 as it just can no longer be installed using composer.

I just felt like even if not supported it may not be "expected" to stop working. So I warned. But for me, it's fine to remove Laravel 5.7 from my .travis.yml file.

**Comment by driesvints** [comment]
@kylekatarnls sorry, we can't offer support anymore for 5.7

**Comment by devcircus** [comment]
I just installed using ```composer create-project laravel/framework:5.7.* testapp``` and ran tests without any problems. Using PHP 7.3.8. Is there another step I missed that would cause the problem?

**Comment by kylekatarnls** [comment]
No, this is my exact input (cached cleared):
```
composer create-project laravel/framework:5.7.* aa
```

And the exact output:
```
Installing laravel/framework (v5.7.28)
  - Installing laravel/framework (v5.7.28): Downloading (100%)
Created project in aa
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/nexmo-notification-channel 1.0.x-dev requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - laravel/nexmo-notification-channel v1.0.0 requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - laravel/nexmo-notification-channel v1.0.1 requires nexmo/client ^1.0 -> satisfiable by nexmo/client[1.9.0].
    - Conclusion: don't install nexmo/client 1.9.0
    - Installation request for laravel/nexmo-notification-channel ^1.0 -> satisfiable by laravel/nexmo-notification-channel[1.0.x-dev, v1.0.0, v1.0.1].
```

Same result on Travis. And the same happens with PHP 7.2.3 or --ignore-platform-reqs.

@devcircus Please show your output to see packages versions installed. But I guess you just have cache that install the oldest state.

**Comment by mbergann** [comment]
I had the same problem at work (we are still on laravel 5.7 on our business-internal software because for the switch to 5.8 or 6.0 we have to change all our excel-exports (that are a lot...) and we had no time for this yet...) 

but found the reason of this problem and a solution:

**what went wrong?**

nexmo changed the project-name of https://github.com/Nexmo/nexmo-php in composer.json from "nexmo/client" to "nexmo/client-core" and built a new project https://github.com/Nexmo/nexmo-php-complete which they named "nexmo/client"

the reason for that: they wanted to decouple the nexmo-client from guzzle6-adapter. now they just require the virtual package php-http/client-implementation instead.

the new "nexmo/client" (nexmo-php-complete) package is now a wrapper that combines the nexmo/client-core with the guzzle6-adapter. **BUT**: while the old nexmo/client 1.8.1 (now nexmo/client-core) did depend on php-http/guzzle6-adapter ^1.0, the new nexmo/client (starting with version 1.9.0) requires for version 1.9.0 the nexmo/client-core ^1.0 (so it uses also the 1.8.1) and php-http/guzzle6-adapter **^2.0** (don't ask me why - maybe they were drunk...)


**my solution:**

I created a new project nexmo-php on our local gitlab server and then I moved Nexmo's "nexmo-php"-project to our local project but with latest version 1.8.1 (so that the lookup at HEAD will say "that is project 'nexmo/client' - not 'nexmo/client-core'! "):

- git clone https://github.com/Nexmo/nexmo-php.git
- cd nexmo-php
- git checkout 1.8.1
- git branch -d master
- git checkout -b master
- git tag -d 2.0.0
- git remote set-url origin `<OUR-LOCAL-EMPTY-GITLAB-PROJECT>`
- git push -u origin master
- git push --tags

Then I added this project to our internal satis-repository and I added the repository to the composer.json of our laravel 5.7 project - now composer finds our self-hosted nexmo/client 1.8.1 and everything works fine.

**Comment by mbergann** [comment]
> I just installed using `composer create-project laravel/framework:5.7.* testapp` and ran tests without any problems. Using PHP 7.3.8. Is there another step I missed that would cause the problem?

delete your composer-cache (maybe in ~/.cache/composer or ~/.composer) and have a next try ;-)
