### ISSUE TITLE
Pivot models use wrong key for parent relationships when attaching arrays

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30260]
- Laravel Version: 6.2.0
- PHP Version: 7.2
- Database Driver & Version: sqlite

### Description:

I'm trying to use pivot models to set default values to the intermediate table. For example, I have a `statuses` table that has a `default_message` column, which serves a default value for the `message` column on the `order_statuses` pivot table, when no second argument is passed to `attach()`.

I'm using an accessor, to show a default value in Nova, and a `creating` event callback to set the value when attaching:

```php
// OrderStatus extends Pivot

public static function boot()
{
    parent::boot();

    static::creating(function (OrderStatus $orderStatus) {
        $orderStatus->message = $orderStatus->getMessageAttribute() ?? null;
    });
}

public function status()
{
    return $this->belongsTo(Status::class);
}

public function getMessageAttribute()
{
    return $this->attributes['message'] ?? $this->status->default_message;
}
```

This works when attaching a single model:
```php
$order->attach($status1);
```
**However, when I'm attaching multiple models, the `status` relationship is empty and the `status_id` attribute gets the `Status` model.**
```php
$order->attach([$status1, $status2]);
```

### Steps To Reproduce:

Here's a gist with my models: https://gist.github.com/stancl/8314edb2513738496141e0366c301eb4

**Comment by driesvints** [comment]
Hi there,

A *lot* has changed to pivot models recently and quite a few issues recently turned out to be misunderstandings how things worked.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by stancl** [comment]
@driesvints It's definitely a bug that the table has a `status_id` key, yet the `status_id` attribute is a Status model instance.
