### ISSUE TITLE
Filesystem::makeDirectory() should not set hardcoded directory permissions (chmod 0775) by default, but should follow process umask

### ISSUE THREAD

**Issue by Vanav** [laravel/framework#30367]
- Laravel Version: 6.x, 5.x
- PHP Version: 7.3

### Description:
When creating directories, default behaviour of PHP's [`mkdir()`](https://www.php.net/mkdir) is to follow process `umask`. Default `umask` for users on Debian/Ubuntu/CentOS/RHEL is `0777`, so directories are created with permissions `0775`. This is good, because it allows to write to storage directories by webserver and other privileged users in the same group.

The same behaviour is default for system `mkdir` command too.

The same behaviour is default for creating files in [`Filesystem::put()`](https://github.com/laravel/framework/blob/998179da75ab56fa8622c95283c2dd1c6e026bf5/src/Illuminate/Filesystem/Filesystem.php#L122), or creating directories in [`Filesystem::copyDirectory()`](https://github.com/laravel/framework/blob/998179da75ab56fa8622c95283c2dd1c6e026bf5/src/Illuminate/Filesystem/Filesystem.php#L506), or creating files in [`Filesystem::replace()`](https://github.com/laravel/framework/blob/998179da75ab56fa8622c95283c2dd1c6e026bf5/src/Illuminate/Filesystem/Filesystem.php#L142).

But [`Filesystem::makeDirectory()`](https://github.com/laravel/framework/blob/998179da75ab56fa8622c95283c2dd1c6e026bf5/src/Illuminate/Filesystem/Filesystem.php#L460) creates directories by default with hardcoded permissions `0755`. This doesn't follow default behaviour of PHP, Linux or other Laravel methods, and it disallows other users (like developers, deploy or cron) to write to created directories.

I suggest to not set hardcoded permissions by default, but to follow default `umask` settings.

### Steps To Reproduce:
Tests with default `umask 0002` and different permissions.
Good:
```
developer@server:/srv/site/current/public/data$ php -r "var_dump(mkdir('test1'));"
bool(true)
developer@server:/srv/site/current/public/data$ stat test1
Access: (2775/drwxrwsr-x)  Uid: ( 1000/deployer)   Gid: (   33/www-data)
```
Good too:
```
developer@server:/srv/site/current/public/data$ php -r "var_dump(mkdir('test3', 0777));" 
bool(true)
developer@server:/srv/site/current/public/data$ stat test3
Access: (2775/drwxrwsr-x)  Uid: ( 1000/deployer)   Gid: (   33/www-data)
```
Bad:
```
developer@server:/srv/site/current/public/data$ php -r "var_dump(mkdir('test2', 0755));" 
bool(true)
developer@server:/srv/site/current/public/data$ stat test2
Access: (2755/drwxr-sr-x)  Uid: ( 1000/deployer)   Gid: (   33/www-data)
```

### Workaround:
Specify `0777` permissions, following [`mkdir()`](https://www.php.net/mkdir) default behaviour:
```
Storage::disk('public')->makeDirectory('directory', 0777);
```

**Comment by driesvints** [comment]
This has always worked properly and we haven't had any issues with this yet. If you want to change the default for this it's probably best to open up an issue in the ideas repo. Thanks.

**Comment by Vanav** [comment]
OK, opened suggestion: https://github.com/laravel/ideas/issues/1904

**Comment by slano** [comment]
Is there any chance this issue can be reopened? It is still present in 8.27.0. It is causing problems in environments, where the web server (or php-fpm process) and other users (for example support users, or users running scheduled tasks) share the same group on the system, with umask set to 0002. In such cases users are not able to modify directories created.

It's strange that umask is respected for files but not for directories.

### Steps To Reproduce:
```
❯ php artisan tinker
Psy Shell v0.10.6 (PHP 7.4.3 — cli) by Justin Hileman
>>> umask(0002);Storage::put('0002/0002.txt', 'writable by user and group');
=> true
>>> umask(0022);Storage::put('0022/0022.txt', 'writable by user');
=> true
>>> umask(0222);Storage::put('0222/0222.txt', 'writable by noone');
=> true
```

```
❯ ll storage/app 
total 16K
drwxr-xr-x 2 slano slano 4,0K Feb 11 20:20 0002
drwxr-xr-x 2 slano slano 4,0K Feb 11 20:20 0022
drwxr-xr-x 2 slano slano 4,0K Feb 11 20:19 0222
```

```
❯ ll storage/app/????
storage/app/0002:
total 4,0K
-rw-rw-r-- 1 slano slano 4 Feb 11 20:20 0002.txt

storage/app/0022:
total 4,0K
-rw-r--r-- 1 slano slano 4 Feb 11 20:20 0022.txt

storage/app/0222:
total 4,0K
-r--r--r-- 1 slano slano 4 Feb 11 20:19 0222.txt
```

**Comment by raydekker** [comment]
I can confirm this issue is still present in v10, even though I have set the permissions in `config/filesystems.php` (disks.public.permissions.dir.public in my case) to for example 0775 it still only get 0755 by default.

I am bypassing this issue as well by passing the 2nd parameter ie. in my case `Storage::disk('public')->makeDirectory('files/dir1', 0775)`

**Comment by theVosCache** [comment]
Like already mentioned in https://github.com/laravel/ideas/issues/1904

> it also doesn't seem possible to do makeDirectory('directory', 0777) via the Storage facade anymore, which makes this even more important.

**Comment by frizus** [comment]
So, on Laravel 11 you can create:
**app/Services/Filesystem.php**
```php
<?php

namespace App\Services;

class Filesystem extends \Illuminate\Filesystem\Filesystem
{
    private const LARAVEL_FILESYSTEM_DIR_PERMISSIONS = 0755;

    /**
     * @param $mode
     * @param $swap
     * @return int
     */
    private function swapMode($mode, $swap): int
    {
        if (!$swap) {
            return $mode;
        }

        $defaultDirPermissions = config('filesystems.default_dir_permissions', self::LARAVEL_FILESYSTEM_DIR_PERMISSIONS);

        if ($mode !== $defaultDirPermissions) {
            $mode = $defaultDirPermissions;
        }

        return $mode;
    }

    /**
     * @inheritdoc
     */
    public function ensureDirectoryExists($path, $mode = self::LARAVEL_FILESYSTEM_DIR_PERMISSIONS, $recursive = true)
    {
        parent::ensureDirectoryExists($path, $this->swapMode($mode, func_num_args() < 2), $recursive);
    }

    /**
     * @inheritdoc
     */
    public function makeDirectory($path, $mode = self::LARAVEL_FILESYSTEM_DIR_PERMISSIONS, $recursive = false, $force = false)
    {
        return parent::makeDirectory($path, $this->swapMode($mode, func_num_args() < 2), $recursive, $force);
    }
}

```

rebind `\Illuminate\Filesystem\Filesystem` with `\App\Services\Filesystem` in
**app/Providers/AppServiceProvider.php**
```php
class AppServiceProvider extends ServiceProvider
{
    // ...
    public function register(): void
    {
        // ...
        $this->app->bind(\Illuminate\Filesystem\Filesystem::class, fn(\Illuminate\Contracts\Foundation\Application $app) => new \App\Services\Filesystem());
        // ...
    }
    // ...
}
```

and configure default dir permissions via `config/filesystems.php` parameter:
```php
<?php

return [
    // ...
    'default_dir_permissions' => 0775, // for example, I needed permissions to allow group edit
    // ...
];
```

**Comment by OliverWich** [comment]
We are also facing issues with this behaviour and would like to see this issue repoened!

We have two users that interact with the Laravel instance.
One is our webserver user (we are using nginx), so `www-data`.
The other (`application`) is the user that is running CI/CD steps (artisan commands & co.) as well as the queues and crons. (It is also part of the www-data group).

We don't think this is a very unusual deployment setup and are surprised, that this causes so much trouble.

All files in our setup need to be owned by the www-data group and the `application` user, so that both users have access to them, especially files in /storage/app.

Now, even with everything I could configure (setting guid bit, using `facl`, chowning in numerous configurations, ensuring the php-fpm systemd service had a umask 0002 set), there was no way for me to get Laravel to properly set permissions for folders it creates.

Every folder it creates uses ` drwx--S--- 1 www-data www-data` which makes it inaccessible to the `application` user.
This **will** break async jobs from the queue if they need to interact with a folder like this!

Uploaded files however use `-rw-rw-r-- 1 www-data www-data ` which is completely fine.

A very stupid test file in `public` did respect the umask and the `application` user can access that folder, so it is a Laravel thing and not a php-fpm / nginx thing.
```
<?php
// umask_test.php
$current_umask = umask();
echo "The umask for this PHP process is: 0" . decoct($current_umask);

$dirName = 'test_directory';
if (!is_dir($dirName)) {
    mkdir($dirName, 0777);
    echo "<br>Created a directory. Please check its permissions via SSH.";
}
?>
```

So please Laravel devs add some way to configure this again, or, even better, respect the umask of the process when creating folders!

I _think_ you are already doing this for files (https://github.com/laravel/framework/blob/cd2761f5c5943e200d124a24e195f03f2d084297/src/Illuminate/Filesystem/Filesystem.php#L228) but for `makeDirectory` you dont (https://github.com/laravel/framework/blob/cd2761f5c5943e200d124a24e195f03f2d084297/src/Illuminate/Filesystem/Filesystem.php#L649-L655) and the `$mode` option is not exposed via a config key or even via the Facade for a direct call (https://github.com/laravel/framework/blob/cd2761f5c5943e200d124a24e195f03f2d084297/src/Illuminate/Contracts/Filesystem/Filesystem.php#L211)



-----

Edit:

We worked around this by manually setting the permissions after the `makeDirectory` call:

```
$this->getDisk()->makeDirectory($path);
$this->getDisk()->setVisibility($path, 'public');
```

We also put this in ` config/filesystems.php`
```
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'throw' => true,
            'permissions' => [
                'file' => [
                    'public' => 0664,
                    'private' => 0600,
                ],
                'dir' => [
                    'public' => 0775,
                    'private' => 0700,
                ],
            ],
        ]
```

-----

Edit 2:

`->setVisibility` improved things, but it *did not* use the configured `0775`, it kept using `0755`.

We now opt for this:
```php
$fullAbsolutePath = $this->getDisk()->path($path);
@chmod($fullAbsolutePath, 0775);
```
