### ISSUE TITLE
How to customize/disable facade/ignition?

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#30438]
facade/ignition debugbar

1. still do not highlight LINE where errors happened. White on white. Old panel did it "black on black"

2. by some reason it forces bootstrap for 12 cols with 70 rem max-width. seriosly, i have 2560 monitor and have to F12 each time to remove max-width property? Damn, it preffers to cut filenames because left sidebar is smaller than class names!!!

3. where is the FUNCTION ARGUMENTS of each step?

Who decide to install it in Laravel by default?

**Comment by rimace** [comment]
First of all, it may be because of cultural differences, but your writing seems very aggressive.
If the view isn't optimized for 2560 monitor, I guess the maintainer doesn't have that. Please always feel free to send pull requests if you know how to make something better or pay a developer to solve those issues for you.
If you just want to remove the package (as written in the issue title) run 
`composer remove facade/ignition` on the command line.
And last but not least: this is the repository for the laravel framework. encountered issues should always be reported to the package that causes it. So for the third party package in this case you can use [this one ](https://github.com/facade/ignition)to report bugs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by 6562680** [comment]
Once the capital will give you for 3 years along only 300 euros and nobody wants to listen, you understand that "cultural difference" :D

I was angry about replacing old ignition that gives nothing except hiding db password for these guys who upload on production with DEBUG=true.

i'd like to see removed all the debug panels because old one was hardcoded, but `facade\ignition` replaces `filp\whoops`. i trieds to launch `whoops` manually - theres no method "catch" or something, i need to explore whole handler laravel module to understand that "handlers" flow.

i still dont understand how to configure or how it works, and yes, when i remove both of debug bars inside "App\Handler.php" - it works as expected.

i think its bad way - installing libraries that does "something" like "we expect" instead of well configurable

**Comment by bradietilley** [comment]
Beautiful - `composer remove facade/ignition` works as expected. Clean. Now I don't get false-positive security vulnerability warnings every time there's an exception during development :grin:
