### ISSUE TITLE
Making HTTP requests in tests affects the state of the application

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30430]
- Laravel Version: 6.4.0
- PHP Version: 7.3.8
- Database Driver & Version: MySQL 5.7.27

### Description:

The application making a "request" in a test using `$this->call()` receives the state changes made by the request.

### Steps To Reproduce:

```php
// dd(tenant()); // NULL
$response = $this->getAuthToken();
// dd(tenant()->id); // test
```

```php
protected function getAuthToken()
{
    return $this->call('POST', self::HOST.'/v1/oauth/token', [
        'client_id' => '1',
        'client_secret' => '...',
        'grant_type' => 'password',
        'password' => 'password',
        'scopes' => '*',
        'username' => 'admin@admin.com'
    ]);
}
```

The controller for that route binds `Tenant` into the service container.

**Comment by JapSeyz** [comment]
The request being made by PHPUnit uses Laravels current state / connections, instead of starting fresh. It's not emulating a stateless request.

**Comment by stancl** [comment]
One could say that this is the expected behavior, because "how else would the calls be made" and that `$this->call()` is just an abstraction over calling the route's controller directly.

However, the docs state that:
> The get method **makes a GET request** into the application, while the assertStatus method asserts that the returned response should have the given HTTP status code.

Which implies that this is equivalent to making an external HTTP request, such as calling the Stripe API. That does not pull Stripe's state into your application.

At the very least, the docs are misleading in that claim. Under the hood, `MakesHttpRequests::call()` really just reuses instances that are already bound to the service container:

```php
$kernel = $this->app->make(HttpKernel::class);
```

```php
$response = $kernel->handle(
    $request = Request::createFromBase($symfonyRequest)
);
```

**Comment by JapSeyz** [comment]
A practical example of this would be a test for testing Laravel Passport Refresh tokens, the flow would go like this.

(Password Grant Request) <-- This sets the Laravel connection to the tenant-connection, both in the request and in the test outside the request.

(Refresh Token Grant Request) <--- This sets the Laravel connection again, purging the old connection, making Laravel Passport fail on [line 77](https://github.com/laravel/passport/blob/8e9448f527b2c2b35fc2361646086faa9f7ffda6/src/Bridge/RefreshTokenRepository.php#L77) because the `$this->database` connection no longer exists, although it's supposed to be a stateless request.

**Comment by driesvints** [comment]
I think this is expected. Like you said: it makes uses of already bound instances. If you feel that the docs could be more clear about this then feel free to send in a pr.
