### ISSUE TITLE
[6.x] Possible to deadlock artisan, by writing wrong cache driver

### ISSUE THREAD

**Issue by Nander-MultiSafepay** [laravel/framework#30455]
- Laravel Version: 6.4.0
- PHP Version: 7.3.9
- Database Driver & Version:
MariaDB 10.3.17 database server

### Description:
You can deadlock artisan and entirety of laravel effectively by writing an invalid default in the config/cache.php file and saving it.
will write cache.default = NULL to the bootstrap/config.php
results in the following error 
cache store [] is not defined
### Steps To Reproduce:
1)Open config/cache.php
2) change the default line to something invalid.
E.G '    'default' => env('CACHE_DRIVER', 'memcached'),' 
To the following:
    'default' => env('memcached'),
3) now save the config file using php artisan optimize (or config:clear)
4) now run any php artisan command
5) observe the 'cache store [] is not defined' error

### Workaround
Change app/bootstrap/config.php.
find the line with 'cache' =>
change 'default' => NULL into anything valid like:
'default => file. or 'default'=>'memcached',

**Comment by driesvints** [comment]
Just make sure you have a correct cache driver defined.

**Comment by Nander-MultiSafepay** [comment]
> Just make sure you have a correct cache driver defined.

Problem is you cant reset your driver as long as you mess it up once, at it will try to write from the bootstrap file. from which it needs data from the bootstrap file. 

stating just make sure you have the right driver. what kinda response is that, the whole issue is that you cant fix the driver after you made a mistake to it. 

Which isn't mentioned on the laravel docs neither is the correct format for the default driver. or why it is constructed like that.

**Comment by AegirLeet** [comment]
OP didn't describe the issue very well.

Actual steps to reproduce:
1. Run `php artisan config:cache` once with a **valid** cache driver set, like `'driver' => 'file'`.
1. Check *bootstrap/cache/config.php* - it will contain a valid config with `'driver' => 'file'`.
1. Run `php artisan config:cache` again with an **invalid** cache driver set, like `'driver' => 'foobar'`
1. Check *bootstrap/cache/config.php* again - it will now contain a config with `'driver' => 'foobar'`
1. Try running any `artisan` command - it will fail because Laravel won't be able to bootstrap with the invalid cache driver being loaded from the cached config file.

At this point, the only solution is to manually edit or delete *bootstrap/cache/config.php*.

Shouldn't be much of an issue in the real world because you'd usually only run `config:cache` or `optimize` as part of your production deployment and you probably would've noticed an invalid driver during development or testing, but I can see how it could still be somewhat annoying.

**Comment by driesvints** [comment]
We don't consider this a bug sorry. Please just define your cache driver properly.

**Comment by Nander-MultiSafepay** [comment]
So if its not a bug, what would the proposed solution be to redefine your driver cache?

Surely it can't be to hack into your bootstrap and fix it manually.
