### ISSUE TITLE
RefreshDatabase trait does not reset increment counters.

### ISSUE THREAD

**Issue by theomessin** [laravel/framework#30467]
- Laravel Version: 6.x
- PHP Version: 7.3.9
- Database Driver & Version: Postgres 11.5

### Description:
Laravel's RefreshDatabase will reverse individual transactions after each test when using a conventional database (ie. not in-memory). I assume this is done for speed and efficiency. However, this method does not reset auto-increment counters (at least for the version of Postgres mentioned above). This can cause some issues:

### Steps To Reproduce:
The following test will pass when using an in-memory sqlite database, **but will fail when using Postgres**.
```php
<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    // This will pass.
    public function test_a()
    {
        factory(User::class)->create();
        $this->assertNotNull(User::find(1));
    }

    // This will fail, no user with id 1.
    public function test_b()
    {
        factory(User::class)->create();
        $this->assertNotNull(User::find(1));
    }

    // This will fail, $user->id is now 3.
    public function test_c()
    {
        $user = factory(User::class)->create();
        $this->assertEquals(2, $user->id);
    }
}
```

Each subsequent test will create a user but the id will not be `1`, **it will be `1` then `2` then `3`**.

Any fix will probably be done here: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L45-L64

Using the old DatabaseMigrations trait will fix this. Don't know whether this should be fixed or if people should just be using DatabaseMigrations in this situation. I thought the point of RefreshDatabase was to replace DatabaseMigrations and DatabaseTransactions.

**Comment by mfn** [comment]
That's expected because, as you said, for performance reason the database is only refreshed _once_ before all tests; each test just runs within a transaction but [Postgres is known not to rollback sequences](https://www.postgresql.org/docs/current/functions-sequence.html).

A couple of thoughts:
1. having tests relying on such IDs is a bad idea, better to refactor the tests
2. you can use phpunit `--process-isolation` which runs _each_ test in total isolation; of course this comes with a hefty overhead of truly refreshing the database every time
3. if you rely on "future IDs" and you can't change 1), you can write code which looks up what the next sequence number will be

For 3) I use code like this:
```php
    /**
     * Gets the next id for autoincrement/sequences
     *
     * This is mostly necessary due sequences in postgres not being
     * transaction safe, which leads to some extra work.
     *
     * @param Model $model
     * @return int
     */
    public function getNextSequenceId(Model $model): int
    {
        $sequenceName = $this->getSequenceName($model->getTable(), $model->getKeyName());
        $result = $this->pdo->query(
            "SELECT * FROM $sequenceName",
            PDO::FETCH_OBJ
        )->fetchAll();
        $result = $result[0];

        return $result->is_called
            ? $result->last_value + 1
            : $result->last_value;
    }

    /**
     * @param string $tableName
     * @param string $columnName
     * @return string
     */
    protected function getSequenceName(string $tableName, string $columnName): string
    {
        return $tableName . '_' . $columnName . '_seq';
    }
```
`$this->pdo` in this case is extracted from the models connection, i.e. something like `(new $model)->getConnection()`

`getSequenceName` doesn't really look up the name but generates it based on some convention; might fail if you use different approach here.

Transaction will always cause these kind of troubles in Postgres for sequences. I first saw that e.g. CakePHP2 had out of the box support for this; I believe they used another approach and did reset the sequences after every transaction or something (could be wrong here).

HTH

**Comment by driesvints** [comment]
I think @mfn explained this pretty well, thanks.
