### ISSUE TITLE
`Illuminate/Http/Request.php` misses `@method validate()` annotation

### ISSUE THREAD

**Issue by HenkPoley** [laravel/framework#30462]
- Laravel Version: 6.4.0
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
[Validation # Writing The Validation Logic](https://laravel.com/docs/6.x/validation#quick-writing-the-validation-logic) describes using `$request->validate()`. Editors with PHP integration will (correctly) mark 'validate' as not found in `Illuminate\Http\Request`. 

I think the annotation should be something like.

```php
/** @method public array validate(array $rules) */
```
[or](https://github.com/barryvdh/laravel-ide-helper/issues/608#issuecomment-460125301):
```php
/** @method bool|array|null validate(array $rules, ...$params) */
```

`use Illuminate\Http\Request;` was an autogenerated import when creating a Controller with `php artisan make:model <name>`. E.g. it is not that some Facade should be used. Not that `Illuminate\Support\Facades\Request` annotates `validate()`. Maybe add the annotation there too. 

Or somewhere deeper in the inheritance tree of course.

**Comment by X-Coder264** [comment]
I don't think that it should be documented as a docblock in the `Illuminate\Http\Request` class because that method exists on the request only [when it's added as a macro in a full framework setup](https://github.com/laravel/framework/blob/v6.4.1/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php#L52). That means that method doesn't exist when the `illuminate/http` component is used as a standalone package.

**Comment by driesvints** [comment]
See the answer above.
