### ISSUE TITLE
[5.8] Use of undefined constant STDOUT

### ISSUE THREAD

**Issue by lazosweb** [laravel/framework#30571]
- Laravel Version: 5.8.35
- PHP Version: 7.3.11
- Database Driver & Version: 
- OS: Windows Server 2016
- IIS: 10

### Description:
Symfony Console 4.3.7 introduced a new method to return whether STDOUT has vt100 support (some Windows 10+ configurations)

When calling from a controller Artisan::call("demo:command");

This method errors with the following "Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)"

### Steps To Reproduce:
Call an artisan command from a controller on a Windows 2016 Server and IIS 10.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by lazosweb** [comment]
I create a sample Laravel 6 project and run a simple built in command such as "cache:clear" and the problem persists even in Laravel 6.

See attached photo.

![Screenshot_2019-11-12 🧨 Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version ](https://user-images.githubusercontent.com/19972355/68692892-ef7a2880-057e-11ea-9655-a3d8e15161fd.png)

**Comment by mfn** [comment]
`STDOUT` is only defined for CLI, not in web server SAPIS.

As such, calling console commands from within a web server will not work anymore with this change from Symfony.

It's possible to shim the constant, google gives you workarounds for that.

Hard to say who's at fault:
1. why do you call a console command from within a web server?
2. why does Laravel not provide such a shim out of the box (of course because this is new, etc.)
3. why didn't the Symfony developers take the absence of this constant into account (probably same answer as 1) … )

The easiest way is simply to not do that. If you have code you need to execute, refactor it so you can call it directly or use a background job 🤷‍♀️

**Comment by lazosweb** [comment]
@mfn I see your point.

1) Since Laravel provides us with a way to call a command from the web server that's why I or any one else does it.
3) I guess you are right about that one. I do not thing Symfony console was meant to be called from the web server. Some Symfony examples I saw online are call from the command line.

**Comment by lazosweb** [comment]
Symfony will fix this bug. I do not know if Laravel has to do anything from their end until they release a bug fix.

https://github.com/symfony/symfony/pull/34344

**Comment by mfn** [comment]
Nothing to be done for Laravel. Users hitting this problem can pin due an older Symfony version for that package until this is fixed.
