### ISSUE TITLE
Event listeners not firing

### ISSUE THREAD

**Issue by innoflash** [laravel/framework#30591]
- Laravel Version: 6.5.0
- PHP Version: 7.2.24
- Database Driver & Version:

### Description:
I have created some listeners and the listeners are working perfect without implementing the `ShouldQueue` interface but when i implement it it does not work

### Steps To Reproduce:

`class MyListener { }` works good (calls the handle function)

`class MyListener implements ShouldQueue` does not call the handle function but its showing to be processed on the terminal on queue:work

but when I override `shouldDiscoverEvents` the handle is called with the `ShouldQueue` interface

**Comment by driesvints** [comment]
Since this feature is used a lot and this is the first report we get from it being broken, I believe there's something amis within your own app/setup.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
