### ISSUE TITLE
$model->only() doesn't respect casting

### ISSUE THREAD

**Issue by dorkyboi** [laravel/framework#30716]
- Laravel Version: 5.8.* (up to v6.5.2)
- PHP Version: ^7.2
- Database Driver & Version: irrelevant

Consider having following code:
```
$user = \App\User::find(1);
dd($user, $user->only(['id', 'created_at']), json_encode($user->only(['id', 'created_at'])));
```

This would produse the following:
![image](https://user-images.githubusercontent.com/23461412/69877555-d386be80-12c2-11ea-9bb8-e473542102cc.png)

As you may see, `$model->only()` gave us an array with `Carbon` instance (instead of formatted string imo) which lead us to having wrong date format in json string, because `Carbon` is now out of `$model`'s instance and thus cannot be formatted automatically.

**Comment by mfn** [comment]
This is expected. It's like you access the property directly of a model.

The following are supposed to be equivalent:
- `[$model->a, $model->b]`
- `$model->only(['a', 'b'])`

Which means it's expected to return the cast'ed attributes (and naturally invokes custom getters) and _not_ the raw model attributes as required by the database.

So, in essence and contrary to your issue title, it actually doe respect casting when getting the data from the model.

IMHO there is no bug here. This is expected behaviour; but probably not the right one for your use-case.

**Comment by dorkyboi** [comment]
It seems there is a bit of misunderstanting here, allow me to clarify:

Both of your cases return Carbon instance (as supposed to), but the issue is wrong date format in the output.
- [$model->a, $model->b] => `2019-11-29 15:01:29`
- $model->only(['a', 'b']) => `2019-11-29T15:01:29.000000Z`
And, as i conclude, this is happening because, when casting to string, `Model` has automatic format applied and regular `Carbon` (which is what we get from `$model->only()`), obviously, does not?

**Comment by driesvints** [comment]
This is expected. `only` returns the attributes unformated (so with Carbon instances).
