### ISSUE TITLE
Changing unsigned columns in migration causes loss of signing

### ISSUE THREAD

**Issue by frodeknutsen** [laravel/framework#30849]
- Laravel Version: 6.7.0
- PHP Version: 7.4.0
- MySQL Version: 8.0.18

### Description:
Doing any `ALTER` with `CHANGE` in migration on columns with `UNSIGNED` causes them to lose their signed state.

### Steps To Reproduce:
Let's try changing the length of `foo.bar` from 3 to 1:
```php
Schema::create('foo', function (Blueprint $table) {
  $table->bigIncrements('id');
  $table->unsignedTinyInteger('bar', 3);
});

Schema::table('foo', function (Blueprint $table) {
  $table->unsignedTinyInteger('bar', 1)->change();
});
```
Result:
```sql
ALTER TABLE foo CHANGE bar bar TINYINT(1) DEFAULT '0' NOT NULL
```
Expected:
```sql
ALTER TABLE foo CHANGE bar bar TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL;
```

**Comment by driesvints** [comment]
That indeed seems unwanted. I'm wondering if we can tackle this together with https://github.com/laravel/framework/issues/30539

**Comment by nsaliu** [comment]
@frodeknutsen are you sure that you can pass the length of the `bar` field using `unsignedInteger()`?
Reading the method signature in codebase seems not possible `public function unsignedInteger($column, $autoIncrement = false)`

Furthermore, if I run your code an Exception is thrown due to double primary key creation (according to method signature).

Can be more detailed?

**Comment by driesvints** [comment]
There indeed seems to be no way to set length this way. @frodeknutsen can you please verify that the example above is correct?

**Comment by frodeknutsen** [comment]
I was a bit quick on the trigger with my example. I still have a problem converting a `tinyint(3) unsigned` column to a "boolean" type (`tinyint(1) unsigned`), but since it is not a native MySQL datatype it is not a very important issue.
