### ISSUE TITLE
Command::execute() should always return int - deprecate returning null

### ISSUE THREAD

**Issue by halaei** [laravel/framework#30845]
- Laravel Version: 5.8.35 (I think it is in 6.x as well)
- PHP Version: 7.2.25
- Database Driver & Version: MySql 5.7
- Symfony/Console: >= 4.4.0

### Description:
According to https://github.com/symfony/symfony/issues/33747, a change in Symfony, Command::execute must always return an integer value. I don't think it was a good change, but if it is supposed to remain, in Laravel, either the doc blocks for the generated commands' handle() function should change, or add some handy code can be added in Lavavel's override of execute()  to convert return values to integer. I guess the plan is to not support non-ingeter return values in Symfony 5. 

### Steps To Reproduce:
Run a command that doesn't return null inside tinker to see the warning:

    PHP Deprecated:  Return value of "App/Console/Commands/...::execute()" should always be of the type int since Symfony 4.4, NULL returned. in ....php on line ...

**Comment by stloyd** [comment]
>  Even in a strictly typed language like C I can have an int function that returns nothing, it will be automatically converted to 0. Also you can define main as being void. So why C is more flexible than Symfony here?

This has nothing to do with C vs Symfony, cause Symfony is framework based on PHP, which from the beginning converts method call without declared return type to `null`, that the problem here.

The points to force the return type is to make code more clear (often on error there was `return 1` without `return 0` on success) output, easier maintenance, less potential hacks which convert `null` into `0`, easier portability between systems etc. all of those were described in related PR/issues IIRC.

Also if you dont like that deprecation, then make your code use exactly the version before it was added, there is no force to use latest.

**Comment by halaei** [comment]
@stloyd If this makes the code cleaner I am fine with it, even though I really don't get it. I don't think I will stick with the old versions just because of some deprecation message. I'd rather to fix either my console commands or see some changes in the Laravel, or better in my opinion, a revert in Symfony.

**Comment by halaei** [comment]
If Symfony remains as it is, I think for the next major version of laravel this change will be fine:
```php
    /**
     * Execute the console command.
     *
     * @param  \Symfony\Component\Console\Input\InputInterface  $input
     * @param  \Symfony\Component\Console\Output\OutputInterface  $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $result = $this->laravel->call([$this, 'handle']);
        return is_int($result) ? $result : 0;
    }
```

**Comment by RFreij** [comment]
Next major version of laravel already supports symfony 5: https://github.com/laravel/framework/pull/30610

**Comment by halaei** [comment]
@RFreij Oh, I didn't noticed that. I guess this issue is closed then. Thanks
