### ISSUE TITLE
factory(<Model>::class)

### ISSUE THREAD

**Issue by IlyaVorozhbit** [laravel/framework#30865]
- Laravel Version: 6.5.1
- PHP Version: 7.2.24

### Description:

When I'm use:
`$users = factory(User::class)->create()`, and then do:
`$users->pluck('id')->toArray()`

I expect array contains 1 id

When in tests I create 2 users in setUp method, and then in test **method** I again use factory to create 1 user, and then I call `$users->pluck('id')->toArray()` I get array with 3 ids instead of 1

### Steps To Reproduce:

```
class SomeTest extends TestCase {

    public function setUp(): void
    {
        parent::setUp();
        $this->admin = factory(User::class)->state('admin')->create();
        $this->user = factory(User::class)->create();
    }
        
    public function testExample()
    {
        $users = factory(User::class)->create();
        dd($users->pluck('id')); // there I have 3 ids
    }

}
```
But if in **testExample** I write:
```
$users = factory(User::class, 2)->create();
```

and then
```
dd($users->pluck('id'));
``` 
I will get array of 2 ids. So, is it bug, or feature, that factory `remember` all created models?

**Comment by driesvints** [comment]
The first example is to be expected. You're creating three user models in total so you get three ids back. The setUp method is called before you run the test so anything happening inside of it will be executed and taken into account in the test method.

The second example is also expected because when you specify an amount on the factory you get back an Eloquent collection and not a model instance. Therefor the `pluck` method is performed on the Eloquent collection and not on the Eloquent Builder class like in the first example. And thus you only get back the ids of the collection.
