### ISSUE TITLE
illuminate/database component incorrect behavior on lost connection

### ISSUE THREAD

**Issue by NogaevPN** [laravel/framework#30916]
- Laravel Version: 5.8.27 (and upper)
- PHP Version: 7.2.24
- Database Driver & Version:
Mysql 5.7.28
### Description:
If standalone component used in application without error_hander that throws warnings as Exception (php default behavior), and connection to mysql is lost before ManagesTransactions::commit() or ManagesTransactions::beginTransaction only warning is raised, that not prevent code execution.
Database changes is missed and application don't know about it.

### Steps To Reproduce:
1) Start transaction and update field. 
2) Before transaction end set sleep(10) and restart mysql server.
3) Get updated value - it doesn't change.

**Comment by mfn** [comment]
I wager this is expected.

Everything in Laravel relies on exception handling, not just the database component. Though probably this one has a very high operational impact.

IMO it's simply a requirement "in todays age of PHP" that your execution environment converts everything to exception to work properly. Since Laravel does it, so it's base requirement if you use the components standalone.

From what I can see, you've to adapt your environment.

I'm not aware of a dedicated documentation how to properly use the standalone components. Some have their own README, some don't. But if such a thing would exist, it should probably mention this fact I guess.

**Comment by NogaevPN** [comment]
It is necessary to indicate in the component documentation (https://github.com/illuminate/database) that the correct behavior will only be if there is a special error handler.
And use it in examples.

**Comment by mfn** [comment]
@NogaevPN you can try a PR for that

**Comment by driesvints** [comment]
Feel free to send in a pr to the docs
