### ISSUE TITLE
Routing continuous requests too fast and then throw 404 or 500。Log content：“production.ERROR: No application encryption key has been specified.”

### ISSUE THREAD

**Issue by Sirlhy** [laravel/framework#31010]
- Laravel Version: 6.9.0
- PHP Version: 7.2.18
- Database Driver & Version:  MySQL 5.7.26

### Description:
When you refresh the page twice in a row, a 404 or 500 error will be thrown！

From the log, you can see: production. Error: no application encryption key has been specified. {"exception": "[object] (runtimeException (Code: 0): no application encryption key has been specified. At D: \ \ me \ \ project \ \ laravel \ \ lts6 \ \ server \ \ vendor \ \ laravel \ \ framework \ \ SRC \ \ illuminate \ \ encryption \ \ encryptionserviceprovider. PHP: 44)

But appkey has been set，I refresh once normally, and the page can be displayed normally....

After many tests, it is found that this happens occasionally in the following situations:
1. Page with iframe
2. AJAX

The common phenomenon when they have problems is that the access route is too fast in one time！

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sisve** [comment]
This sounds like you're using the .env file to set environment variables, and you're using Apache on Windows. The default behavior of the environment variables are to unset them after the request has been executed. This works with php-fpm and setups where there's one request per process, since environment variables are per-process. 

However, the default configuration for Apache on Windows is to execute concurrent php requests within the same process, which means they share the environment variables. When the first requests unsets the variables, the second concurrent request loses them too. This will also affect concurrent requests to different sites, where one site may be using environment variables from another site, when there are concurrent requests to both sites.
