### ISSUE TITLE
Backward compactibility broken with markdown raw html issue fix

### ISSUE THREAD

**Issue by MarekGogol** [laravel/framework#31081]
- Laravel Version: 6.10.1
- PHP Version: all
- Database Driver & Version:

### Description:
I think we should consider the way of fixing issue #31065 . With fix applied on this issue will bug persist for all users who have published vendor mail templates before v6.10.0, including users who will migrate from v5 to v6. Many users could publish vendor templates also without touching file panel.blade.php and others...

https://github.com/laravel/framework/issues/31065#issuecomment-572280878

**Comment by driesvints** [comment]
Since the changes which caused this were made as a security patch we unfortunately won't be reverting them. I realise this is unfortunate but please update your templates.

**Comment by gdav** [comment]
Sorry for jumping in,

@driesvints I do not know  why you are closing reported issues, which are not fixed.
If the Laravel core team thinks this solution is fine, than the upgrade instructions should be updated as minimum.

Current state and handling of this new behavior and the related is not professional, many upgraded projects will be broken and the issues is hard to find.

I tried to post this in https://github.com/laravel/framework/issues/31065, but you already closed this thread.

ps.:
You should update your comment https://github.com/laravel/framework/issues/31065#issuecomment-628685766, because this issue occurs not only in 7.x, 6.x is effected too.

Again: as minimum I expect an explicit notice about this in the upgrade instructions.
