### ISSUE TITLE
#find#pluck chain punches through multitenancy 

### ISSUE THREAD

**Issue by dsounded** [laravel/framework#31200]
- Laravel Version: 5.8
- PHP Version: 7.2.9
- Database Driver & Version: MySQL

### Description:
Having Eloquent model let's say `User`(id: int, name: string, company_id: foreign key|int), you can actually chain the stuff like:

`User.find(1).pluck('company_id');` even though it doesn't make much sense still it's possible to call, and guess what ? It returns all the `company_id`s from that table, which can cause a really really terrible bugs

### Steps To Reproduce:
`User.find(1).pluck('company_id');` # [array of all the company ids in this table `users`]

**Comment by 36864** [comment]
This repository is for reporting bugs in the framework. Laravel does not support multitenancy out of the box, so this is not a bug in the framework.

Additionally, 5.8 is no longer supported. Please upgrade to laravel 6.

When you call `->pluck` on a model instance, it forwards the call to the underlying query builder instance. This is usually a mistake, but we can't prevent developers from preferring something like `(new User())->pluck('foo')` instead of `User::pluck('foo')`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
