### ISSUE TITLE
Optional strings containing only spaces are not validated, 'password' fields in particular.

### ISSUE THREAD

**Issue by mk-relax** [laravel/framework#31331]
I am implementing a JSON API that allows users to change their account settings, including (but optionally) their password. The validation rule is:
```
'password' => 'nullable|string|min:6|confirmed'
```
The problem is that this rule accepts `" "` (a single space) as password (or any number of spaces). The `min:6` rule is not enforced for such strings.

Normally, strings are trimmed (and set to null) by the `TrimStrings` and `ConvertEmptyStringsToNull` middleware. However the `password` field is explicitely excluded by `TrimStrings` by default. So generally this only happens for nullable `password` fields, but if a website has `TrimStrings` middleware disabled, this could happen for any nullable field.

This is caused by the `isValidatable()` method of the validator. Its `presentOrRuleIsImplicit()` _trims_ the value and then decides that is is "not present, so not validatable", see [Validator.php:494](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Validation/Validator.php#L494)

In my opinion, the `trim()` should be removed there. _Any_ (non zero-length) string that makes it to the server should have its validation rules applied to it, even if it only contains spaces (e.g. with `TrimStrings` disabled or, by default, when it's a password field).

It's just not up to the validator to decide that such strings are "not validatable".

Experiencing this in 5.5, but looking at the code this is still the case in 5.8 and 6.x.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by mk-relax** [comment]
If I use a Validator with a `min:6` rule to make sure strings have at least 6 characters, I would definitely consider it a bug that it accepts a single space. The fact that this happens to password fields even makes it a potential security issue. But I'll post to `laravel/ideas` instead. Thank you for your reaction.

**Comment by johanrosenson** [comment]
Strange that this is taken as a feature request, this feels like a bug, and as mk-relax says, a potential security issue.

**Comment by rs-sliske** [comment]
there are 2 sides here, while it looks like there might be a bug with how validation rules treat a string that only contains whitespace, i think the use case presented is a scenario which is asking for issues.

- i think i would probably give password changing its own endpoint but maybe a little less convenient in an api
- i would use the presence of the the field, rather than its value to decide whether to act on it
- im not sure on whether trimming password or not is better, but im leaning towards saying trim every field
- maybe a single space shouldnt pass the validation, but what if someone passes 6 spaces? surely that shouldnt pass either, but even without this bug your rules would allow that
