### ISSUE TITLE
Laravel MIME issue while validating .csv file

### ISSUE THREAD

**Issue by zavre-c** [laravel/framework#31501]
- Laravel Version: 6.x
- PHP Version: 7.2

### Steps To Reproduce:

```php
$request->validate([
  'fileinput' => ['required','file','mimetypes:text/csv']
]);
```
Upload a csv file
fails validation even if _Content-Type: text/csv_
is set in request

#### Response
```json
{
    "message": "The given data was invalid.",
    "errors": {
        "fileinput": [
            "The fileinput must be a file of type: text/csv."
        ]
    }
}
```

Also,
```php
$request->file('fileinput')->getClientMimeType()
```
**gives text/csv**

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ragingdave** [comment]
@driesvints After running into this as well, it's not a question for support, it's an actual bug in even Laravel 7.27. When uploading a csv file, the resulting UploadedFile instance is populated with:
```
Illuminate\Http\UploadedFile^ {#3437
  -test: false
  -originalName: "test.csv"
  -mimeType: "text/csv"
  -error: 0
  #hashName: null
  path: "/tmp"
  filename: "phpRejfeQ"
  basename: "phpRejfeQ"
  pathname: "/tmp/phpRejfeQ"
  extension: ""
  realPath: "/tmp/phpRejfeQ"
  aTime: 2020-09-03 15:13:26
  mTime: 2020-09-03 15:13:26
  cTime: 2020-09-03 15:13:26
  inode: 1835052
  size: 599489
  perms: 0100600
  owner: 1006
  group: 1006
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
}
```

The resulting code check to validate the mime type ends up detecting this file as `txt` for the call to guessExtension in the mime validation method, https://github.com/laravel/framework/blob/7.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1209, which then ends up with a validation error of `The file must be a file of type: csv.`

This is likely due to reading the filename/extension of the UploadedFile rather than the mimeType of the upload or even the original file. I'm not sure why this issue was closed so quickly seemingly without any actual investigation to determine if this was a valid issue or not.

**Comment by ragingdave** [comment]
In further testing, this is even more widespread as it also affects the `store` method when saving uploaded files. This causes the stored file to get an extension of `txt` rather than the correct `csv`.

**Comment by driesvints** [comment]
@ragingdave we're using the mime component from Symfony for this so please report this there. There's nothing we can do about it.

https://github.com/laravel/framework/blob/c6cf38139d2524a7c3accb606e3fb1b035c98d6a/src/Illuminate/Filesystem/Filesystem.php#L11
