### ISSUE TITLE
Unable to use faker locales with WithFaker trait

### ISSUE THREAD

**Issue by jamesfairhurst** [laravel/framework#31614]
- Laravel Version: 6.14.0
- PHP Version: 7.4.0
- Database Driver & Version: n/a

### Description:
After recent changes to the WithFaker trait on https://github.com/laravel/framework/pull/30992 trying to use a different locale when testing no longer works.

Also related to https://github.com/laravel/framework/issues/30345

### Steps To Reproduce:
New up a laravel, attempt to create a locale faker instance:

```
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, WithFaker;

    protected function setUpFaker()
    {
        $this->faker = $this->makeFaker('en_GB');

        // attempt to output locale number, always from Faker\Provider\en_US\PhoneNumber
        dd($this->faker->phoneNumber);
    }
}
```

**Comment by AegirLeet** [comment]
This happens because https://github.com/laravel/framework/blob/32d1ed55dd46dcd706ff2e45bb7965be7320b87d/src/Illuminate/Foundation/Testing/WithFaker.php#L49 passes the locale as a parameter to `make()` when getting the Generator from the container, but DatabaseServiceProvider, which binds the Generator at https://github.com/laravel/framework/blob/32d1ed55dd46dcd706ff2e45bb7965be7320b87d/src/Illuminate/Database/DatabaseServiceProvider.php#L77-L79, doesn't use that value at all .

**Comment by jamesfairhurst** [comment]
@AegirLeet yeah, personally I would be leaning to revert https://github.com/laravel/framework/pull/30992 as the use case was quite specific and could be handled in an overridden `setUpFaker`.
