### ISSUE TITLE
PHP 7.4 broke (?) Eloquent casts to array

### ISSUE THREAD

**Issue by IlyaVorozhbit** [laravel/framework#31674]
- Laravel Version: 6.17.1
- PHP Version: 7.4.3

That issue is duplicate of https://github.com/laravel/framework/issues/30737

### Description:
I have updated php from 7.2 to 7.4.3.
I made: composer update. Before update Laravel was of version 6.5.1 now is 6.17.1

### Steps To Reproduce:
- Create any model, that casts one or more attributes to array. 
- Save that model, but leave this attribute with array cast empty. (After save it must be null)
- Make: $a = $user->settings['nickname'];
You will get:
PHP Notice:  Trying to access array offset on value of type null 

So, in PHP 7.4. backward incompatible changes it is on first place: 
https://www.php.net/manual/en/migration74.incompatible.php

At PHP 7.2 when you are doing: 
```
$a = $user->settings['nickname']
```
While $user->settings == null, it just makes $a equal to null

**Comment by AegirLeet** [comment]
You will probably have to work around this yourself. Making array casts fall back to an empty array on null values is possible, but it would certainly break 6.x's BC promises.

> At PHP 7.2 when you are doing:
>
> `$a = $user->settings['nickname']`
>
> While $user->settings == null, it just makes $a equal to null

Even in PHP < 7.4.0, this will generate a notice (undefined index), so you shouldn't be doing it anyway.

Possible workarounds:

* Use the null coalescing assignment operator to get a default value: `$a = $user->settings['nickname'] ?? 'default value goes here';`
* Use `$attributes` on your model to set a default value (like `'{}'`) when inserting new instances.
* Use an accessor to return a non-null value
* Ensure your code always sets the attribute to an empty array instead of leaving the null default and ideally set your DB column to `NOT NULL`
* Do `is_array()`/`isset()` checks before accessing the attribute.

**Comment by driesvints** [comment]
Please try some of the solutions from above.

**Comment by khanks** [comment]
I think dropping this kind of change into a minor version ranges from misguided to evil. Who on the PHP team had a bad hangover & decided that an empty array is not 'countable' ?  This kind of stuff is why I don't ever "upgrade" to the 'latest'.

**Comment by mfn** [comment]
> that an empty array is not 'countable'

This is not the case, I think you have mixed up something.

`null` was made "not countable", and if you think about it, correctly so. But yes, it ~is~ was a PITA.

**Comment by khanks** [comment]
I'm just relaying the error message that PHP 7.2 gave me when I did "count($myArray)", which was _**"Warning: count(): Parameter must be an array or an object that implements Countable"**_. The array was empty (because, yeah, sometimes it will be). When I 'cast'  it BEFORE doing the count, the Notice was not invoked and there were no other issues. And yes, it was defined in the same function as $myArray = array(), and then populated with a key=>value pair which may or may not be empty. 

Just to check, I also evaluated  **empty($myArray) ? 'true' : 'false';**  and **is_null($myArray) ? 'true' : 'false';** and they both evaluated to **true** when it was empty and when it was null. So I'm not going to debate with anyone about it being 'not the case' -- I'm pointing out what happened and how I fixed it, so hopefully it will help others. 

You are right about it being a PITA, and I believe it was an unnecessary one for a 'minor' release.

**Comment by GrahamCampbell** [comment]
All PHP minor releases are semver major releases, actually. There's never been a minor release that didn't make breaking changes in the history of the language.

**Comment by AegirLeet** [comment]
@khanks 

> The array was empty (because, yeah, sometimes it will be). When I 'cast' it BEFORE doing the count, the Notice was not invoked and there were no other issues. And yes, it was defined in the same function as $myArray = array(), and then populated with a key=>value pair which may or may not be empty

> Just to check, I also evaluated empty($myArray) ? 'true' : 'false'; and is_null($myArray) ? 'true' : 'false'; and they both evaluated to true when it was empty and when it was null.

That's not how it works. `count()` on an empty array works just fine and `is_null()` on an empty array will return false. You must have accidentally set `$myArray = null` at some point. See https://3v4l.org/YOagV.

**Comment by stephenjude** [comment]
I decide to confirm 

> @khanks
> 
> > The array was empty (because, yeah, sometimes it will be). When I 'cast' it BEFORE doing the count, the Notice was not invoked and there were no other issues. And yes, it was defined in the same function as $myArray = array(), and then populated with a key=>value pair which may or may not be empty
> 
> > Just to check, I also evaluated empty($myArray) ? 'true' : 'false'; and is_null($myArray) ? 'true' : 'false'; and they both evaluated to true when it was empty and when it was null.
> 
> That's not how it works. `count()` on an empty array works just fine and `is_null()` on an empty array will return false. You must have accidentally set `$myArray = null` at some point. See https://3v4l.org/YOagV.

Same here. I tried it on phpsandbox.io and everything works fine. You can [check it here](https://phpsandbox.io/n/small-mountain-gkxw)

**Comment by khanks** [comment]
I'm proud for you....
