### ISSUE TITLE
toArray uses incorrect timezone.

### ISSUE THREAD

**Issue by kdion4891** [laravel/framework#31722]
- Laravel Version: 7.0
- PHP Version: 7.3
- Database Driver & Version: Mysql 5.6

### Description:

When using the `toArray()` method on a modal, it does not show the timestamps in the correct timezone.

### Steps To Reproduce:

1. Set the `app.php` timezone to `America/Toronto`
2. Insert some rows for any model you want
3. Create a blade file with this code for the model:

        created_at: {{ $model->created_at }}
        <br><br>
        via array: {{ print_r($model->toArray(), true) }}

You can clearly see that `$model->created_at` is showing the correct date via the exact database value, and for whatever reason `toArray` is deciding to change it to UTC.

**Comment by dwightwatson** [comment]
That's intentional: https://laravel.com/docs/7.x/upgrade#date-serialization

**Comment by zhmuyu** [comment]
> 这是故意的：[https](https://laravel.com/docs/7.x/upgrade#date-serialization) : [//laravel.com/docs/7.x/upgrade#date-serialization](https://laravel.com/docs/7.x/upgrade#date-serialization)

But the time zone is wrong. The real-time environment variable is set

**Comment by driesvints** [comment]
This is expected. Carbon will format the (string) typecast according to its `__toString` function and the `toArray` method will serialize it with the new serialization.

**Comment by taylorotwell** [comment]
Note the upgrade guide specifies how to keep the old behavior if you want.

**Comment by kdion4891** [comment]
OK thanks. I just ended up using an accessor for now.

**Comment by viirre** [comment]
I know this issue is closed but I'm trying anyway with a similar problem caused by this change. 

There are some cases where this change might cause issues for a lot of apps, ours included. Consider:
```
php
        $invoiceModel = Invoice::make(['number' => 'foobar', 'date' => '2020-03-01']);
        $customer->invoices()->updateOrCreate(
            ['number' => $invoiceModel->number],
            $invoiceModel->attributesToArray()
        );
```

If the `Invoice` model has a `date` cast for the the `date` attribute, the date will be saved as `2020-02-29` instead of the correct `2020-03-01` because our timezone is set to `Europe/Stockholm` and not `UTC`. 

The solution is to either set the timezone to `UTC` (which of course is not an option), set the cast as `date:y-m-d` or use the suggested upgrade guide solution of declaring our own `serializedDate` method on the model. 

Is this really intended behaviour for`attributesToArray/toArray` regarding the `date` cast?

**Comment by rentalhost** [comment]
@viirre @taylorotwell I really think it is wrong. `Carbon::toJSON()` method will create a copy of current `$date` and set it to `utc()`, ignoring the `app.timezone`. So non-UTC dates will have a wrong output when `toArray()` or similar is called. It is really intentional?

A simple solution is modify how `serializeDate()` works by calling `toISOString(true)` instead of `toJSON()`. The `true` on `toISOString(true)` means "do not set timezone to UTF, keep as is".

**Comment by markking79** [comment]
I was able to solve by adding the following method to my model...

```
use DateTimeInterface;
...
...

    protected function serializeDate(DateTimeInterface $date)
    {
        return \Carbon\Carbon::instance($date)->toISOString(true);
    }
```

**Comment by bilogic** [comment]
@markking79 

Can show how your model `created_at` when `fill()` and `getTimezone()` are called?
```PHP
>>> $u = \App\Models\User::make()->fill(['created_at'=>'2022-04-05T11:52:53.000000Z']);
=> App\Models\User {#6225
     created_at: "2022-04-05 11:52:53",
   }

>>> $u->created_at->getTimezone()
=> Carbon\CarbonTimeZone {#6207
     timezone: Asia/Singapore (+08:00),
   }

>>>
```

**Comment by markking79** [comment]
@bilogic 

```
>>>  $u = \App\Price::make()->fill(['created_at'=>'2022-04-05T11:52:53.000000Z']);
=> App\Price {#4138
     created_at: "2022-04-05 11:52:53",
   }

>>> $u->created_at->getTimezone()
=> Carbon\CarbonTimeZone {#4139
     timezone: America/New_York (-04:00),
   }

>>> 
```

**Comment by bilogic** [comment]
@markking79 

In that case, it still has an issue. Your timezone is `-04:00`, so after `fill()`, `created_at` should become `07:52:53` (11 - 4)

**Comment by markking79** [comment]
@bilogic I might have misunderstood the original issue the creator of this post was having. For me, I was able to insert the date/time correctly and even query the correct date/time (even though I am not using UTC time). I store everything in the database in American EST. Everything worked correctly until I wanted to use ->toArray (). When I used ->toArray () then it gave me the EST + 4. 

If I had 2022-01-01 12:00:00 in the database, then ->toArray () gave me 2022-01-01 16:00:00 

After adding the code I included above, now ->toArray () gives me the correct date/time just like it is stored in the database (2022-01-01 12:00:00).

**Comment by markking79** [comment]
@bilogic 

I have the following in my config/app.php

`'timezone' => 'America/New_York',`

**Comment by bilogic** [comment]
@markking79 

This issue is tricky to understand, I tried to explain as best I could in the post https://github.com/laravel/framework/issues/31722#issuecomment-1131875330 above and more details in #42447 

1. We normally insert and read datetimes with the assumption that they are all in the same timezones as the system, in your case -04:00.
2. The tricky bit about `2022-04-05T11:52:53.000000Z` is that it is a datetime + zone, i.e. UTC+0
3. Since you are on -4, after filling, `created_at` has to show `07:52:53`, and we can see that `serializeDate` did not correct that

Don't get me wrong. My concern is that this issue is hard to understand, so making it clear what does not work will better help everyone who reads this.

**Comment by bilogic** [comment]
@markking79 

What I'm suggesting is that, perhaps we can delete our series of messages as it did not fix the issue.

**Comment by markking79** [comment]
@bilogic I'm not going to delete my post. From what I can see, the original poster is saving the datetime in the America/Toronto time zone. Not UTC. He was getting the wrong datetime when he tried to use ->toArray (), but did get the correct datetime when he used ->created_at. My solution will work for him.

**Comment by bilogic** [comment]
@markking79 

Just to go a step further, I would check `SELECT @@global.time_zone, @@session.time_zone;` to see if it was `-04:00`, if it is not, I would go further and say that, all the datetimes in your MySQL are likely wrong, i.e. they have the numerical values you want, but the timezone is wrong. That might explain why `toArray()` was not giving you the correct values.

**Comment by andreamattioli** [comment]
My solution is a custom trait that I use in my models. It contains `serializeDate` function only (copied from original one), that I've modified to call `toISOString` with true param.
Be aware of Laravel updates that changes `serializeDate` behavior, this comes from version 8.


```
trait HasAttributes {
    protected function serializeDate(DateTimeInterface $date): string {
        return $date instanceof DateTimeImmutable ?
            CarbonImmutable::instance($date)->toISOString(true) :
            Carbon::instance($date)->toISOString(true);
    }
}
```

**Comment by xaledzebari** [comment]
add this to your models
```
protected function serializeDate($date){
        return $date->format('Y-m-d H:i:s');
 }
```
