### ISSUE TITLE
Type Hinting Illuminate\Http\Request::get($key, $default = NULL)

### ISSUE THREAD

**Issue by vladoa** [laravel/framework#31822]
- Laravel Version: 7.0.6
- PHP Version: 7.3.11

### Description:
Similar like in #31803 , a fresh Laravel install shows the following warning:

`Declaration of Illuminate\Http\Request::get($key, $default = NULL) should be compatible with Symfony\Component\HttpFoundation\Request::get(string $key, $default = NULL) in /usr/www/users/myuser/mydomain.com/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 20`

### Steps To Reproduce:
Install Laravel 7.0.6 and hit the welcome route.

**Comment by stevenhardy-digital** [comment]
Experiencing the same issue after upgrading to version 7. I changed the file that it is suggesting however I then get a further error:
```
Declaration of Carbon\Translator::trans($id, array $parameters = Array, $domain = NULL, $locale = NULL) must be compatible with Symfony\Contracts\Translation\TranslatorInterface::trans(string $id, array $parameters = Array, ?string $domain = NULL, ?string $locale = NULL) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Carbon\\Translator::trans($id, array $parameters = Array, $domain = NULL, $locale = NULL) must be compatible with Symfony\\Contracts\\Translation\\TranslatorInterface::trans(string $id, array $parameters = Array, ?string $domain = NULL, ?string $locale = NULL) at /home/vagrant/folder/website/vendor/nesbot/carbon/src/Carbon/Translator.php:18)
```

**Comment by vladoa** [comment]
Yeah me too. I think something is missing in our production environment. Because my Laravel app works fine locally on Homestead.

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/framework/pull/31826

@stevenhardy-digital you'll have to open an issue on Carbon for that. Ping @kylekatarnls

**Comment by stevenhardy-digital** [comment]
@driesvints Thank you! I have raised an issue there. Getting a 500 error now, hope we can resolve this :)

**Comment by kylekatarnls** [comment]
Hi @driesvints, @stevenhardy-digital `trans($id)` is supposed to be a valid override of `trans(string $id)` since PHP 7.2 and our tests are passing well for PHP 7.3 and Symfony 5:
https://travis-ci.org/briannesbitt/Carbon/jobs/658182113?utm_medium=notification&utm_source=github_status

I'm also not ready to drop PHP 7.1, Symfony < 5 and Laravel < 7 regarding the maintenance effort it can add. So I would not change the `Carbon\Translator` until digging deeper to know exactly how and why this is raised.

@stevenhardy-digital Please check that composer run the same PHP version when it installs the dependencies that the one your run for the webserver.
