### ISSUE TITLE
ViewComponentAttributeBag behaviour is incorrect

### ISSUE THREAD

**Issue by mfullbrook** [laravel/framework#31898]
- Laravel Version: 7.0.8
- PHP Version: 7.4.0
- Database Driver & Version: n/a

### Description:
I believe the behaviour of the View Component `$attributes->merge()` is incorrect.   Blade Components are top down.  When a view declares a component on the page and specifies an attribute, if the component has a _default_ attribute of the same name, in the current implemenation only the default value will be used.

The docs state:

> Sometimes you may need to specify default values for attributes or merge additional values into some of the component's attributes. 

My interpretation (and the ViewComponentAttributeBag makes extensive use of the name 'defaults') is that a component can specify a default but the page declaring the component can **override** the default.  Currently this is not the case.  I believe the intention of this API is to have a similar behaviour to Vue.

### Steps To Reproduce:
```php
<?php
use Illuminate\View\ComponentAttributeBag;

// this is akin to <x-my-component width="600" /> 
$bag = new ComponentAttributeBag(['width' => '600']);

// this is akin to {{ $attributes->merge('width' => '100%']) }}
dump($bag->merge(['width' => '100%']))
```
```
Result:
Illuminate\View\ComponentAttributeBag {#1623
  #attributes: array:1 [
    "width" => "100%"
  ]
}
```

### Suggestions

* I've created a PR to change this behavour - see link below.

* But maybe the naming of the method `merge()` is misleading?  Would `defaults()` be more appropriate ?  I appreciate that the method is in fact merging the special case of `class` attributes.

Thoughts?

**Comment by perifer** [comment]
I agree the that `<x-my-component>` should override default attributes. Naming is tricky, especially since `merge()` is what we have now...

Probably unrelated, but I'll mention it here anyway: When looking up how "boolean attributes" (`disabled`, `checked` etc) are handled I run into an issue where the output differs when using `$attributes` and `$attributes->merge()` (Note that nothing is merged in). This test illustrates that:

```php
public function testAttributeBag()
{
    $bag = new ComponentAttributeBag(['test' => true]);

    $this->assertSame('test="test"', (string) $bag); // Fails, actual output: test
    $this->assertSame('test="test"', (string) $bag->merge());

    $bag = new ComponentAttributeBag(['test' => false]);

    $this->assertSame('', (string) $bag); // Fails, actual output: test=""
    $this->assertSame('', (string) $bag->merge());
}
```

The result when using `$attributes->merge()` is actually pretty neat, but might be unintentional. It means that `<x-input :checked="false">` renders as `<input>` and `<x-input :checked="true">` renders as `<input checked="checked">` with this blade template:

```
<input $attributes->merge()>
```

Might indicate that attributes should have a bigger overhaul than just the handling of defaults?

**Comment by mfullbrook** [comment]
(Copied from the PR) This is a better illustration of the merge issue. 

With a component that defines some default attributes:

```blade
<table {{ $attributes->merge(['width' => '600', 'class' => 'mb-4']) }}>
  ...
</table>
```

If the component is used like this

```html
<x-my-table width="100%" class="mt-2" />
```

We would expect the rendered template to be:
```html
<table class="mb-4 mt-2" width="100%">
  ...
</table>
```

But the current implementation renders:
```html
<table class="mb-4 mt-2" width="600">>
  ...
</table>
```
