### ISSUE TITLE
Laravel Validation for array of images fails

### ISSUE THREAD

**Issue by ssi-anik** [laravel/framework#31931]
- Laravel Version: Laravel Framework Lumen (6.3.3)
- PHP Version: PHP 7.4.1
- Docker version: 19.03.5, build 633a0ea
- Docker-compose version: 1.25.4, build 8d51620a
### Description:
I have a validation like the following,

```php
'image' => 'required|array',
'image.*' => 'image',
```
- If I don't submit any image, it shows error
- If I submit images as an array, solves the problem.
- If I add a text field and add to that array it doesn't show any error.
- It starts to show the error as soon as I add three text fields. 

Please check the attached video. --->>>>[Validation ERROR](https://demotelenor-my.sharepoint.com/:v:/g/personal/sirajul_anik_dh_health/Efvq1KrLkyBBv8nfqbU4tRQB7kZgKQLlKkTrehAl0THbTw?e=cPBCZL)

**Comment by themsaid** [comment]
Please share code we can copy to reproduce the issue.

**Comment by DavidNgugi** [comment]
Of course if you set the rule to `required`, it will show an error if the input is `null`. Image input must be an image (jpeg, png, bmp, gif, or svg). 
I believe adding `nullable` should do the trick. @themsaid can advise.

```php
'image' => 'required|array|nullable',
'image.*' => 'image|mimes:jpeg,png,jpg,gif,svg'
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by ahmedash95** [comment]
Hey @ssi-anik,
I tried to reproduce the issue and here is the explanation of what is happening.

First, PHP provides $_FILES for serving file uploads and $_GET&$_POST for normal inputs.

Laravel's [Concerns/InteractsWithInput.php:184](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Concerns/InteractsWithInput.php#L184) is using `array_replace_recursive` to merge files & inputs into one array. so in your case, what happens is
```php
// Merging & Replacing keys recursivly
'Inputs' => [
    image[0],    => 'text'
    image[1].    => 'text'
];
// With
'Files' => [
    image[0],   => 'profile-1.png'
    image[1],    => 'profile-2.png'
];
```
Outputs 
```php
'all' => [
        image[0],   => 'profile-1.png'
        image[1],    => 'profile-2.png'
]
```
That's because `array_replace_recursive` replaces the ids of inputs by files.

that's why when you add 3rd field as a text it throws the exception because `array_replace_recursive` appends 3rd one from input because it has no alternative in files_array.

replacing `array_replace_recursive` with `array_merge_recursive` would solve the issue of displaying the error if one of the inputs is not a file. but it will display the wrong filed number `image[0] or image[1]` 

So you should depend on your serve files first. if there are 2 files and 2 strings then laravel will ignore the 2 strings for you.

**Comment by ssi-anik** [comment]
@themsaid, @ahmedash95 explained the problem thoroughly. Thanks brother. 
@DavidNgugi, Nah brother. you didn't get the problem. It's explained above. 
And thanks to everyone.
