### ISSUE TITLE
Avoid global scope for cookies

### ISSUE THREAD

**Issue by Donorhan** [laravel/framework#31999]
- Laravel Version: 6.12.0 & 5.8.37
- PHP Version: 7.2 & 7.4
- Database Driver & Version: -

### Description:
I'm currently working on a website with a main domain and sub-domains like this:
- mywebsite.com
- dev.mywebsite.com
- staging.mywebsite.com

When I go on my main domain the cookies are created and everything is fine. If I visit on one of the subdomains I end up with the cookie for the subdomain + the cookie of the parent website, which causes CSRF token errors. (I have one instance of Laravel per domain and subdomain) 

When I look in the Chrome console I can see that the cookie of the parent domain is present on my subdomains because it is in the format ".mywebsite.com". (The dot between the domain)

**The problem is that Laravel automatically adds a "." in front of the domain which increases the scope of the cookie**. In the file session.php I have well indicated "mywebsite.com" and "dev.mywebsite.com", without success, the "." is still here.

Example:
`SESSION_DOMAIN=laratest.test`

Result:
![Capture d’écran 2020-03-17 à 11 43 42](https://user-images.githubusercontent.com/3781087/76849667-1c4c8e00-6846-11ea-9ccd-7bf41886c9ce.png)
Sadly the cookie will be active on dev.laratest.com too.

### Steps To Reproduce:
- Go to the networks tab of Chrome and take a look to the Domain column
- Try changing the SESSION_DOMAIN value, a dot is automatically added

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by moham96** [comment]
Hi I have faced a similar issue that caused all my projects to stop working

I can't run two Laravel apps if one of them on the main domain and the other is on a subdomain
it messes up the `XSRF-TOKEN`
the issue only appears if I set `SESSION_DOMAIN` on the main app
so if the main app is on `example.lh`
and the second app is on `beta.example.lh`
and in the main app, i set `SESSION_DOMAIN=example.lh`

then in Firefox and Chrome the cookie will have a domain of `.example.lh` (notice the additional . at the start)
which will cause the XSRF-TOKEN cookie to have a broader scope and be applied to requests on the secondary app, so all requests on the secondary app will fail with 419 error
I did notice that when the `SESSION_DOMAIN` is set that laravel sends the correct domain example.lh (i.e without the additional dot) in the Set-Cookie header
so the set cookie header looks like this:



`set-cookie: XSRF-TOKEN=SomeRandomString;  expires=Sat, 01-Jul-2023 23:34:37 GMT; Max-Age=7200; path=/;  domain=example.lh; samesite=lax`

but somehow all the browsers interpret it as a global cookie and add a dot at the beginning,
so the cookie in the `storage` tab in firefox/chrome show the `XSRF-TOKEN` cookie having a domain of `.example.lh`
So I'm not sure if this is a bug in Laravel/PHP or the browsers

This is a serious issue @driesvints  can this be reopened? at least we should know if this issue is from laravel or if we should report it to the browsers vendors
