### ISSUE TITLE
Login attempt stucks and fails when first time login. Works after refreshing the page

### ISSUE THREAD

**Issue by ScriptingBeating** [laravel/framework#32102]
- Laravel Version: 7.2 & 7.3
- PHP Version: 7.3
- Database Driver & Version: MYSQL 8.0

### Description:
First attempt to login (post route) after starting the server fails and stuck on loading and if you refresh the page and try again it works. This issue is in both Laravel's default login and even when you create login from scratch.

### Steps To Reproduce:
Create a new laravel project with authentication and try to login the first time

**Comment by timrspratt** [comment]
All my laravel sites have been suffering from this recently. At one point I thought php 7.4 may have fixed it, but it seems to be happening with 7.4 too

**Comment by timrspratt** [comment]
@ScriptingBeating what browser? For me it is Chrome only

**Comment by ScriptingBeating** [comment]
@timrspratt  Yup it's in chrome. My old websites are working fine. But my two new websites are suffering from this. I am also using LastPass.

**Comment by ScriptingBeating** [comment]
Both lastpass and 1password creating the same problem ?

**Comment by driesvints** [comment]
I'm currently running a project on 7.3 where the login works just fine.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mark1282** [comment]
This is happening for me too when logging in for the first time in Chrome. Using homestead. I'm on Laravel 6.x. Did anyone have any further information on this happening?

**Comment by blaab2** [comment]
Others and me are facing the same problem. (https://laracasts.com/discuss/channels/laravel/laravel-got-stuck-after-login-laravel-58)

@ScriptingBeating have you found a solution for the problem?

**Comment by ScriptingBeating** [comment]
@blaab2 Yeah the problem is related to the behaviour of some browser extensions like lastpass. This has nothing to do with the framework. Either disable your extensions or try in incognito mode.

**Comment by shingo0620** [comment]
I'm facing the same problem these days with Laravel 7.x, but I did not use any password related chrome extension. Guessing maybe this issue is related to telescope?

**Comment by DoubleTime** [comment]
Laravel 5.8 also facing this issue.
Way to reproduce:
1) php artisan cache:clear
2) Access using chrome incognito mode
3) Try login, stucked

**Comment by webdevmike** [comment]
I am experiencing the same issue. Login gets stuck in Chrome, although the user is actually logged in, it just doesn't redirect. If I refresh after it being stuck for a while, it redirects properly. Using Laravel 7, Chrome Incognito mode (so no browser extensions causing this), and using the default Laravel and Authentication setup. No customization.

**Comment by mark1282** [comment]
Just out of curiousity what session driver is everyone using? Has anyone tried changing it from file based to an in memory driver such as redis to see if that makes any difference?

**Comment by webdevmike** [comment]
Hey @mark1282 I'm using the default Laravel 7 setup. I created a brand new Laravel project yesterday, ran `php artisan ui vue --auth` registered a user, tried to log in and experience the issue. It happens both locally (using Valet) and in Production (using Forge).

I think it may actually be a bug in Chrome, because I don't see it happen in any other browser.

**Comment by mark1282** [comment]
I'm having this issue on my local homstead evironment on Windows 10. Just worried this is a more widespread issue.

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
