### ISSUE TITLE
ThrottlesLogin trait missing

### ISSUE THREAD

**Issue by jorisatabix** [laravel/framework#32203]
- Laravel Version: 7.4.0
- PHP Version:  7.3.13
- Database Driver & Version: - 

### Description:

I am in the process of upgrading to laravel 7, and it seems that currently `Illuminate\Foundation\Auth\ThrottlesLogins;` is missing 

Missing in 7.x: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Auth/ThrottlesLogins.php

But available in 6.x: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Auth/ThrottlesLogins.php).

Looking at the upgrade guide, there is no mention of it: https://laravel.com/docs/7.x/upgrade

Is it moved? Or deleted?

**Comment by dinhquochan** [comment]
See in: https://github.com/laravel/ui/blob/2.x/auth-backend/ThrottlesLogins.php

**Comment by robSIG** [comment]
I had the same problem and the above answer was not clear what was going on, but it's as simple as doing:

`composer require laravel/ui`

For some reason the file has the same namespace rather than being under a laravel/ui namespace so after that there's nothing you need to do if you were already using it.

Also copying the error message I had for easier googling since it took me a while to find this:

"Trait 'Illuminate\Foundation\Auth\ThrottlesLogins' not found"
