### ISSUE TITLE
Discrepancy between routes and cached routes with APP_URL having a subfolder

### ISSUE THREAD

**Issue by berndulum** [laravel/framework#32236]
- Laravel Version: 7.4.0
- PHP Version: 7.3.16
- Database Driver & Version: -

### Description:

If Laravel is installed in a subfolder of a domain and the routes are cached the route for "/" is not working. Without routes caching the route is working as expected.

The expected behaviour is, that route caching does not change the handling of routes. With and without caching should result in the same behaviour.

Maybe the root cause is the same as #32228 or #31768.

### Steps To Reproduce:

- Create a symlink from public/test to public: `ln -s . test`
- Set APP_URL in .env to `http://localhost/test`

Open "http://localhost/test" in a browser. It works as expected

- Cache routes: `php artisan route:cache`

Open "http://localhost/test" in a browser. It throws an exception:

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: HEAD.

Other routes, e.g. /login are working.

- Clear routes cache: `php artisan route:clear`

It works again.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but installing Laravel in a sub-folder is not suported.

**Comment by mo3000** [comment]
I don't know what your route file look like but I think's it is not laravel's problem. Usually web server don't follow sym links due to security reason. Symbolic links can be configured in your web server such as nginx like:
```
disable_symlinks off;
```

**Comment by berndulum** [comment]
Interessting that it is not supported. The setup was working till Laravel 7.0.8. Then the commits 3d58cd9 and ac6f3a8 introduced the problem. 

@mo3000 as the setup is working without caching I think it is not related to the webserver.

**Comment by berndulum** [comment]
For reference, I got this working with a custom middleware:
```php
public function handle(Request $request, Closure $next)
{
    if ($request->path() === '/') {
        $newURI = $request->server->get('REQUEST_URI') . 'index.php';
        $request->server->set('REQUEST_URI', $newURI);
    }

    return $next($request);
}
```
This appends `index.php` to the requested uri and prevents the removal of the '/' suffix.

**Comment by devzeroized** [comment]
@GrahamCampbell I don't see where in the documentation it is shown that placing laravel in a subfolder is unsupported. I can only find that there is a security concern in [directory configuration](https://laravel.com/docs/7.x/installation#directory-configuration) (which can be avoided). 

The route caching did work for laravel version 5.x -> 7.0.8 and is now only broken for the '/' route and not for any other routes. The breaking change is introduced in [ac6f3a8](https://github.com/laravel/framework/commit/ac6f3a8bd0e94ea1319b6f278ecf7f3f8bada3c2) as mentioned by @berndulum . 

The issue seems to be located in src/Illuminate/Routing/CompiledRouteCollection.php 

```php
protected function requestWithoutTrailingSlash(Request $request)
...
$trimmedRequest->server->set(
    'REQUEST_URI', rtrim($parts[0], '/').(isset($parts[1]) ? '?'.$parts[1] : '')
);
...
```

This modifies the request object and messes up both the pathInfo and basePath (when using laravel in a subfolder)

**Before** protected function requestWithoutTrailingSlash(Request $request)
```php
Illuminate\Http\Request {
...
  pathInfo: "/"
  requestUri: "/lar73/"
  baseUrl: "/lar73"
  basePath: "/lar73"
  method: "GET"
  format: "html"
...
}
```

**After** protected function requestWithoutTrailingSlash(Request $request)
```php
Illuminate\Http\Request {
...
  pathInfo: "/lar73"
  requestUri: "/lar73"
  baseUrl: ""
  basePath: ""
  method: "GET"
  format: "html"
...
}
```

It's unclear to me if this is intended behaviour. I dont know how to continue from here as I'm unsure if laravel in "subfolders" is unsupported or not.

**Comment by driesvints** [comment]
@devzeroized https://laravel.com/docs/7.x/installation#directory-configuration

**Comment by DerekPixieset** [comment]
Just wanted to throw some extra weight behind this as well. I have the exact same problem as my organization runs different applications on different "subfolders" for load balancer routing purposes. 

Since the upgrade to Laravel 7.x everything works fine until we do a `php artisan route:cache` and suddenly our root `'/'` GET route is broken and shows the following in the browser: 

> Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
> The GET method is not supported for this route. Supported methods: HEAD.

The `route:list` still looks correct after caching. Our `APP_URL` is `APP_URL=https://mydomain.local/subfolder`

`+------------------+----------------------------------------+-----------------------------------------+-----------------------------+-------------------------------------------------------------------------+------------------------------------------------------+
| Domain           | Method                                 | URI                                     | Name                        | Action                                                                  | Middleware                                           |
+------------------+----------------------------------------+-----------------------------------------+-----------------------------+-------------------------------------------------------------------------+------------------------------------------------------+
| mydomain.local        | GET|HEAD                               | / `

**Comment by jrbecart** [comment]
Same problem as in [#32832](https://github.com/laravel/framework/issues/32832)

I found a solution to bypass the problem. If you add the route "/your_subfolder" instead of "/" in your web.php it should work with the caching. 

I think Laravel members want to close their eyes on this problem. I **CAN'T** believe that Laravel 7.x in a sub-folder is not supported.

**Comment by driesvints** [comment]
Hey @jrbecart. It's true, we don't support Laravel in a sub directory. See https://laravel.com/docs/8.x#directory-configuration

**Comment by jrbecart** [comment]
Hi @driesvints, I don't see where it says it's not supported.
Like others you pointed out to this part of the doc, but it doesn't say we can't have multiple websites on the same server in different directories.

Here is what you point out from Laravel doc:
Directory Configuration
Laravel should always **be served out of the root of the "web directory"** configured for your web server. You **should not attempt to serve a Laravel application out of a subdirectory of the "web directory"**. Attempting to do so could expose sensitive files present within your application.

But what we mean here it's to have: (also called **subfolders websites**)
https://domain1.com/website1
https://domain1.com/website2
https://domain1.com/website3

On the server side the root web directory of each website is, for example:
root /var/www/website1/public;
root /var/www/website2/public;
root /var/www/website3/public;

So I don't see here where there is something wrong with that, and the **doc doesn't say it's not supported**!

Please explain us why we can't have website1, website2, website3 on the same server, in different directories, served out of the root of the "web directory".

Also **it works fine without caching**.
Also **it was working fine before with caching**.

Regards,

**Comment by driesvints** [comment]
@jrbecart think you're just confusing the term "subfolder" to be different from "subdirectory" which it is not. It's pretty explicitly explained in the section I linked to.

**Comment by jrbecart** [comment]
@driesvints no I am not confusing, but the doc is not explicit as you said. Without mentioning subfolder or subdirectory, what we are referring to here is: can we have website like https://domain1.com/website/ working with laravel and the caching option enabled, because without caching it works.

If a laravel website is not possible in https://domain1.com/website/ it should be more explicit in the doc:, like:
You can't have a website under https://yourdomain/website 

And if it's really the case it's unbelievable, because many many websites and  web apps, are like that.

Can we have a confirmation/explanation from another laravel team member?

And please, please let us know why:
it works fine without caching?
it was working fine before with caching?

**Comment by derekps** [comment]
Throwing some additional support behind @jrbecart here. I agree it is absolutely not explicit in the linked documentation. 

To further complicate the matter it has worked fine until Laravel 7.x and still works fine in Laravel 7.x as long as you do not use cached routes. I can't see any way that the framework team could disagree that there is a bug present.

At the very least the discrepancy between cached/non-cached routes is a bug that needs dealt with.

**Comment by khanks** [comment]
@berndulum Where did you put this logic? What did you extend? Thanks...

> 
> 
> For reference, I got this working with a custom middleware:
> 
> ```
> public function handle(Request $request, Closure $next)
> {
>     if ($request->path() === '/') {
>         $newURI = $request->server->get('REQUEST_URI') . 'index.php';
>         $request->server->set('REQUEST_URI', $newURI);
>     }
> 
>     return $next($request);
> }
> ```
> 
> This appends `index.php` to the requested uri and prevents the removal of the '/' suffix.

**Comment by kmuenkel** [comment]
I landed on something similar. Thanks very much to @berndulum for the inspiration. But I believe that was only half the equation. `Symfony\Component\HttpFoundation\Request::getPathInfo()` doesn't re-retrieve path from the server value if it's already been identified by a previous process:

```php
    public function getPathInfo()
    {
        if (null === $this->pathInfo) {
            $this->pathInfo = $this->preparePathInfo();
        }

        return $this->pathInfo;
    }
```

However, `Illuminate\Http\Request` supplies a convenient `createFrom()` method that will build a brand new `Request` object based off the server values within an existing one. So the solution I arrived at identified the root path from the APP_URL, strips it from the existing Request path, redefined it, _then_ regenerates (effectively resetting) the entire object per the new state of the old one.


```php
<?php

namespace App\Http\Middleware;

use Closure;
use Throwable;
use Illuminate\Http\{Request, Response, JsonResponse, RedirectResponse};

class RootPath
{
    /**
     * @param Request $request
     * @param Closure $next
     * @return Response|RedirectResponse|JsonResponse
     * @throws Throwable
     */
    public function handle(Request $request, Closure $next)
    {
        $appUrl = parse_url(config('app.url'));
        $rootPath = trim($appUrl['path'] ?? '', '/');
        $path = preg_replace('/^('.preg_quote($rootPath, '/').')(.*)/', '$2', $request->path());
        $request->server->set('REQUEST_URI', trim($path, '/'));

        return $next(Request::createFrom($request));
    }
}

```

**Comment by khanks** [comment]
> 
> 
> Hey @jrbecart. It's true, we don't support Laravel in a sub directory. See https://laravel.com/docs/8.x#directory-configuration

Sounds to me like that says regardless of how many websites I'm maintaining on a server, I should *always* have the laravel application served out of (for example) the 'public_html' or 'www' directory. That would mean the websites would 'share' the app, model, config, database, and 'whatever' directories. I'm just reading this verbatim, so that's what it seems to imply. If so, that's patently ridiculous. If not, then a solid example of how to manage multiple websites would benefit users of this documentation. One picture is worth a thousand ambiguous words. If we had to have a different server (even virtual) for each website on my host, it would cost us $2000 a year. We're not doing that.

**Comment by GrahamCampbell** [comment]
One server can serve multiple websites...

**Comment by khanks** [comment]
> 
> 
> One server can serve multiple websites...

Yes, thank you, I think most of us are aware of that. I think the question is, what directory structure is recommended/required. My account is under /home/myaccount. So is _/home/myaccount/public_html/site-to-sell-junk/_ , _/home/myaccount/public_html/site-for-music-streaming/_, and _/home/myaccount/public_html/frank-zappa-lyrics/_ with a laravel 'installation' (possibly different laravel versions) under each of those websites a 'correct' way? Or is it _/home/myaccount/laravel-installation/site-to-sell-junk_ , _/home/myaccount/laravel-installation/site-for-music-streaming/_ , and _/home/myaccount/laravel-installation/frank-zappa-lyrics/_ that is being recommended? If none of those, then what IS it? If you have multiple websites on the same server, how are you structuring your directories? That would be helpful to those of us who are new to laravel & who are still confused by this piece of the documentation.
