### ISSUE TITLE
Increment method doesn't trigger the updated

### ISSUE THREAD

**Issue by mcpraps** [laravel/framework#32567]
- Laravel Version: 7.2.1
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.6.47

### Description:
I'm not sure exactly if it'is a bug, but I think it is. If I create an observer and I want to catch the updated event, it doesn't work if I use the eloquent increase method on the specified model. So the increase method doesn't trigger the updated event. It's so annoying because it updating the updated_at field also by default. That's why I'm think it's a real update event, why it should to trigger the updated event.

### Steps To Reproduce:
Create a model with a counter field, increase this field and check the model's updated event in the the model's observer.

**Comment by driesvints** [comment]
These methods indeed do not trigger these events. Please see other issues on this tracker.

**Comment by mcpraps** [comment]
Thanks but the "bug" wasn't be "fixed". What kind of issues are you thinking of?

**Comment by driesvints** [comment]
This isn't a bug. It's the current expected behavior.

**Comment by driesvints** [comment]
Taylor let me know that we should look into fixing the behavior for increments/decrements on single models. This will need to be targeted to master as it's a breaking change. We'll need to keep the behavior for relationships as we can't emit events for mass updates.

**Comment by MattStrauss** [comment]
Maybe I am looking at this naively, but can't we just add two lines to the `incrementOrDecrementAttributeValue` method ([here](https://github.com/laravel/framework/blob/f27c2192d05e941268522df2ebe30a7764027212/src/Illuminate/Database/Eloquent/Model.php#L611)):

```
  protected function incrementOrDecrementAttributeValue($column, $amount, $extra, $method)
    {
        $this->{$column} = $this->{$column} + ($method === 'increment' ? $amount : $amount * -1);

        $this->forceFill($extra);

        // add this line to fire the 'updating' event and give the dev a chance to stop the model update
        if ($this->fireModelEvent('updating') === false) {
            return false;
        };

        $this->syncOriginalAttribute($column);

        // add this line to fire the 'updated' event on model
        $this->fireModelEvent('updated', false);
    }
```
This will fire the updating and updated events when `increment` or `decrement` is called on a given model. If the dev increments a field on all models, the events should not be fired as the below line in the the `incrementOrDecrement` method ([here](https://github.com/laravel/framework/blob/f27c2192d05e941268522df2ebe30a7764027212/src/Illuminate/Database/Eloquent/Model.php#L587)) will catch that scenario:

```
if (! $this->exists) {

            return $query->{$method}($column, $amount, $extra);
        }
```
There was some [prior conversations](https://github.com/laravel/framework/issues/18802#issuecomment-593031090) about this issue whereas the concern was that the dev wouldn't be able to access the clean or dirty values of the incremented field, but, I just tested it briefly and through the `getDirty` and `getOriginal` methods I was able to access the incremented fields' prior and incremented values in the updating event method. 

I did not consider anything for the saving/saved events for increment/decrement, because I believe that incrementing a field is always an update event the way things are currently set up in `model.php`. I didn't focus too deeply on this, so if that is the incorrect line of thought I apologize.

**Comment by taylorotwell** [comment]
@MattStrauss well, the model hasn't actually been updated in the database at the point where you are firing the `updated` event in your example.

**Comment by taylorotwell** [comment]
Note that, sure, we can add the events to this method; **however**, there is no way to gurantee that the dirty / changed values are actually what the values are going to end up being in the database. We must always run this query as a query that looks like `update table set column = column + 1` because multiple processes could be trying to increment the column at the same time.

Therefore, it is impossible for us to know what the new column value will actually be until after we run the query, so the "dirty" value in the `updating` event would always be a guesstimate. It could never be guaranteed to be correct.

**Comment by taylorotwell** [comment]
Note that I guess no dirty / changed values in any updated hook are ever guaranteed to be a representation of what is actually in the database.

**Comment by taylorotwell** [comment]
Decided to let `updating` and `updated` fire on increment / decrement on 8.x.
