### ISSUE TITLE
Cookie or Session being set on redirect()->away($url)

### ISSUE THREAD

**Issue by colinhall17** [laravel/framework#32815]
- Laravel Version: 7.7.0
- PHP Version: 7.3

### Description:

Not sure if this a bug or intended behaviour. 

When setting a cookie or session and then doing a redirect away to an external site neither cookie or session are persisted.

The use case is for an OAuth2 implementation where the OAuth2 Authentication requires a state to be sent in the query string that can then be checked when the response is returned back to the call back url to ensure its come from the correct source.

### Steps To Reproduce:

In a controller method

Cookie::queue(Cookie::make('oauth2state', 'random-string', 10));
return redirect()->away($url);

When navigating back to the Laravel site there is no oauth2state cookie set

In a controller method

session(['oauth2state' => 'random-string']);
return redirect()->away($url);

When navigating back to the Laravel site there is no oauth2state set in session

**Comment by taylorotwell** [comment]
Works fine for me on Laravel 7.x:

Sessions:

![image](https://user-images.githubusercontent.com/463230/81943122-9a1be400-95c0-11ea-9989-d2ff6627281c.png)

Cookies:

![image](https://user-images.githubusercontent.com/463230/81943195-b15ad180-95c0-11ea-8e4d-b770eaa61898.png)

**Comment by colinhall17** [comment]
Feel stupid, my routes were in a package and I forgot to apply the web middleware.  Lost a few hours of my life to that. Apologies for wasting your time.

**Comment by giovanniledda** [comment]
I'm experiencing the same problem.

Laravel version: 10

I'm doing exactly what @taylorotwell suggested but when I check the landing page, no cookie is set.
I'm doing this to set a cookie to pass an "AWS WAF" rule to access a file via AWS Cloudfront: if I manually set the cookie with the browser inspector, I finally get the file...otherwise, I get 403 error.


I've tried this two alternatives:

1):

```
            Cookie::queue('mycookie', 'myvalue', 5);

            return redirect()
                ->away($encodedUrl);
```


2):


```
$cookie = cookie('mycookie', 'myvalue', 5);

            return redirect()
                ->away($encodedUrl)
                ->withCookie($cookie);
```


My config/session.php file is set like that:

`
    'same_site' => 'none',
`

...but I also tried with:


`
    'same_site' => 'lax',
`

**Comment by colinhall17** [comment]
Is that attached to web routes directly in the framework or are the routes in a package?

If in a a package make sure to apply the 'web' middleware.

**Comment by colinhall17** [comment]
OK, presume you have checked to make sure one of these are true?

if ($request->hasValidSignature() || auth()->check()) {

**Comment by giovanniledda** [comment]
Yes, absolutely. I've a Spatie ray() function that is firing inside those "if" statements.
I'm getting 403 from AWS (because cookie is missing) by the way, not from Laravel.

**Comment by colinhall17** [comment]
Ah OK, that makes sense, I thought you were hitting the 403 on your own app.

The cookie you set here will only set it in your application, and won't send it on to AWS, It would be a security risk to be able to set cookies on other sites so easily.

If its a Cookie that you need to set for an external site then it will likely need to be in the header of the request or somehow used in the url.

Sorry, I don't know enough about AWS WAF and CloudFront but maybe worth looking at the SDK

**Comment by giovanniledda** [comment]
I'm not sure about that. 
Look at @taylorotwell 's code above, for example: he is setting up a cookie then is redirecting to https://google.com...that's basically what I need to do.

**Comment by giovanniledda** [comment]
Okay, thanks @colinhall17 for the clarification. What I need is a cookie on the AWS domain, which is not possible to set from my application...I think I'll give the "set-cookie" solution a try.

Basically, it wasn't a Laravel issue. I'm sorry..

P.S.

To be completely honest, I'm still confused because my real need is to set a cookie in the request to AWS WAF, which is basically a firewall integrated with Cloudfront. With WAF, you can configure a WebACL and associate a rule with it. The rule in my case was "if there isn't a cookie X with value Y, block the request". I simply thought "if they give you the possibility to set a rule like that, there will probably be a way to send a cookie in the request". :-) 

Nevermind...I'll try with the Header.
