### ISSUE TITLE
Running Artisan Command calls __construct methods of every command

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/framework#32905]
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:

I have Some Database Query which is running in `__construct ` method of my Custom Artisan Command while i was trying to run a different command it's actually performing a call to database from my custom command.

### Steps To Reproduce:

1. Make Custom Artisan Command.
2. Perform some operations in `__construct` method
3. Try to run a different command such as `php artisan inspire`

now you will see all those actions which is defined in `__construct ` method of all commands  will be executed .

is this a expected behaviour. ??

Alternatively you can clone my sample repo  [here](https://github.com/ManojKiranA/commandtest)

i have added logging classname to log file.

after cloning try to run and `artisan command ` such as 

`migrate`,`inspire`,`serve`(will log only after stoping the serve ), etc.

**Comment by GrahamCampbell** [comment]
Yep, this is expected. Every command is newed up during registration.

**Comment by GrahamCampbell** [comment]
Don't put database queries in your command constructor, unless you want them to run always.

**Comment by ManojKiranA** [comment]
> Don't put database queries in your command constructor, unless you want them to run always.

so i can do that in handle method.

there must be some warning or note in the documentation.

@GrahamCampbell

**Comment by GrahamCampbell** [comment]
I was thinking it should be obvious because you specify the name of a command using an instance property... so clearly the command must be instantiated in order for the framework to work out its name.

**Comment by skeets23** [comment]
[no](https://github.com/laravel/framework/issues/13789), [it's](https://github.com/laravel/framework/issues/26570) [not](https://github.com/laravel/framework/issues/26427) [obvious](https://github.com/laravel/framework/issues/46528).

This is why outside input is so useful. Of course it will seem obvious how various aspects of any piece of software work to the people who contributed the most to it (Honestly and truly, thank you for your many contributions!). It's precisely because you've contributed so much that it would be difficult for you to immediately understand how this behavior is anything but expected to the average developer.

Personally, if I were to look at the current docs and guess how the command name was retrieved from the instance property (and note that I wouldn't normally even think about this unless prompted!), I would have guessed that it uses a `ReflectionClass` to get the command name, since instantiating all the commands to get their names, knowing they could have custom constructors, seems a bit reckless (and yes, maybe that perspective is a bit naive).

Retrieving the name without an instance of the command isn't overly difficult though:

```
class MyClass{
	public $name = "Fred";
}

$class = new ReflectionClass(MyClass::class);
$defaults = $class->getDefaultProperties();

print_r($defaults["name"]);
```

... Prints `Fred`.

... That said, I know switching to a method like this *now* would be difficult because it would break backwards compatibility, since command signatures can be modified in the constructor currently. Maybe there's a better solution here though... or perhaps a very visible warning at the very top of the ["Artisan Console" documentation](https://laravel.com/docs/12.x/artisan) would be a good compromise.

**Comment by GrahamCampbell** [comment]
How else could the we know the command name - it is an instance property of the class - we need an instance of it to read from. It can also be set dynamically, and doesn't have to be hard-coded.

**Comment by skeets23** [comment]
Wow I think you replied to my post to a 5 year old post within 60 seconds, that has to be some kind of record 😲

I did address the "it might be set dynamically" issue in the last paragraph of my post - fixing this *would* break backwards compatibility - and a new way to dynamically set the command name would be required to make it viable at all. So I don't know what the real "answer" would be. That's why I was saying a bold "warning" in the documentation might be a good compromise.

**Comment by GrahamCampbell** [comment]
I wouldn't object to a PR to the documentation, but I also don't get to decide what PRs get merged. :P
