### ISSUE TITLE
relation unwanted loading

### ISSUE THREAD

**Issue by thisismhp** [laravel/framework#32900]
- Laravel Version: 7.11.0
- PHP Version: 7.4.2
- Database Driver & Version: dosn't matter

### Description:
Let me explain this issue with an example

In `Post ` class when we use 
```
    protected $appends = ['user_name'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getUserNameAttribute()
    {
        return $this->user->name ?? null;
    }
```
Everything is ok , but in response, post array has user full data  and we have to use  : `protected $hidden = ['user'];` to remove it!

response :
```

{
"id": 2,
"title": "foo",
"body": "bar",
"user_id": 1,
"user_name": "thisismhp",
"user": {
.
.
.
.
}
},
```

**Comment by netpok** [comment]
This is expected, you need to load the relation to read a value from it and probably eager load it to have a decent performance. You can either hide the user with the hidden attribute, hide the user on the fly with the makeHidden method or define a resource which hides this for you.

**Comment by thisismhp** [comment]
thats right!
laravel has to  load relation but can hide this!

**Comment by netpok** [comment]
But how would it know that it should hide it?

Given this code:
```php
return Post::with('users')-get();
```

Is this means you're eager loading users because you want to return them or just it is needed for that attribute? What if you access your user_name attribute then still wants to return the user with the rest of the post, should the framework automagically unhide it?

If you don't want to show it just hide with any of the mentioned solutions.
