### ISSUE TITLE
conflict replace in JSON requests

### ISSUE THREAD

**Issue by raftx24** [laravel/framework#33117]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: mysql

### Description:
if we want to replace an attribute of query request in a JSON request, it won't work!  

### Steps To Reproduce:
clone a clean laravel.
adds below to api
```
Route::get('/test', function (Request $request) {
    $request->replace(['name' => 'bar']);

    echo $request->get('name');
});
```
and run the below curl command.
```
curl --location --request GET 'http://127.0.0.1:9000/api/test?name=foo' \
--header 'Content-Type: application/json;charset=UTF-8'
```

it should print `bar` but it prints `foo`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by raftx24** [comment]
@driesvints , it's a bug!

**Comment by derekmd** [comment]
Laravel applications should call `$request->input()` or `$request->json()` for query parameters.

https://github.com/laravel/framework/blob/2f00b61b67f7b0f64fb6fe3ec45b790838783bca/src/Illuminate/Http/Request.php#L330-L339

The `get()` method is defined in the base Symfony `Request`. It can return unexpected results because Laravel adds the `replace()` method and there are `Request`-mutating middleware like `TrimStrings` and `ConvertEmptyStringsToNull`.
