### ISSUE TITLE
Soft Deletes returning the data even the deleted_at is not null anymore

### ISSUE THREAD

**Issue by jackwander** [laravel/framework#33182]
- Laravel Version: 7.11.0
- PHP Version: 7.2.24
- Database Driver & Version:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.30-0ubuntu0.18.04.1 - (Ubuntu)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

### Description:
Even though im using the Soft Delete its still returning the data even the item is deleted (deleted_at not null anymore).

Im using a global scope on the specific model.

### Steps To Reproduce:

Scope:
$builder->where('user_id', auth('api')->user()->id);

**Comment by driesvints** [comment]
I doubt this is broken or otherwise we'd be flooded with issues. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jackwander** [comment]
@driesvints eveytime i use the withouthGlobalScopes() it nulls the softDeletes function. But thanks for the feedback. Will ask in discord.
