### ISSUE TITLE
Database driver failed jobs error for primary key

### ISSUE THREAD

**Issue by randohinn** [laravel/framework#33407]
- Laravel Version: ^7.0
- PHP Version: 7.4.7
- Database Driver & Version: mysql, 5.7.24

### Description:

Using the database driver for queues. When a job fails, and there is already a failed job ahead of it, this error pops  up: 
```
{"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY' (SQL: insert into `failed_jobs` (`connection`, `queue`, `payload`, `exception`, `failed_at`)
```
### Steps To Reproduce:

Use the db queue driver and `php artisan queue:work`. Get two jobs to fail after each other. The second job will error.

**Comment by driesvints** [comment]
I doubt this really is an issue because the default table has an auto increment. This is probably something related to either a custom change or your database environment. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
