### ISSUE TITLE
MySQL 5.6 is not supported

### ISSUE THREAD

**Issue by micaelmendes-flymaster** [laravel/framework#33469]
- Laravel Version: 7.18.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.6.44

### Description:
The documentation states that [MySQL 5.6+ is supported](https://laravel.com/docs/7.x/database#introduction), however this isn't the case since several `json_*` methods that are currently used were only added in version 5.7.

I chose to create this issue here instead of in the docs repo because I'm not sure if the best solution is to just change the documentation or change the code, since some users might have chosen their requirements based on the docs.

### Steps To Reproduce:
Use any MySQL grammar that calls JSON methods.

**Comment by willrowe** [comment]
The [documentation states](https://laravel.com/docs/7.x/queries#json-where-clauses):
> Laravel also supports querying JSON column types on databases that provide support for JSON column types. Currently, this includes MySQL 5.7, PostgreSQL, SQL Server 2016, and SQLite 3.9.0 (with the JSON1 extension).

If you have a database installed that supports JSON column types then you can use those features, if you do not then they are not supported. The part of the docs that you linked is correct, since MySQL 5.6 is supported. It makes no mention of JSON column types there.

**Comment by micaelmendes-flymaster** [comment]
Yes, you're right. I should have read it better. Thanks and sorry!
