### ISSUE TITLE
Signed relative route

### ISSUE THREAD

**Issue by ilzrv** [laravel/framework#33506]
- Laravel Version: 7.19.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7.28

### Description:
A signed relative route does not pass through the middleware `signed` because validation uses the `hasValidSignature` method with the `absolute` parameter which is always `true` in this case

### Steps To Reproduce:

1. Create signedRoute:
```php
\Illuminate\Support\Facades\URL::signedRoute('signed', [], null, false);
// /signed?signature=8e591dced99a709ae641fbca76c601fc2e38e6e20efcbe21a6b88e58276e5eba
```

2. Try to access the route by url `/signed?signature=8e591dced99a709ae641fbca76c601fc2e38e6e20efcbe21a6b88e58276e5eba`: 
```php
Route::get('/signed', function () {
    return view('welcome');
})->name('signed')->middleware('signed');
```

3. Error 403

**Comment by GrahamCampbell** [comment]
I think this is by design, to avoid security problems from accidental bad usage.

**Comment by ilzrv** [comment]
Do you think app works correctly? I am creating a relative link and it is actually non-working. 

What if update the middleware `signed` like this:
```php
public function handle($request, Closure $next, $absolute = true)
{
    $absolute = filter_var($absolute, FILTER_VALIDATE_BOOLEAN);

    if ($request->hasValidSignature($absolute)) {
        return $next($request);
    }

    throw new InvalidSignatureException;
}
```
And use it like this: `signed:false`

Or do you have other ideas?

It was broken in this commit https://github.com/laravel/framework/commit/eec3eb63c21919baa50e1efc787f8fe339d81555

**Comment by sebdesign** [comment]
@GrahamCampbell I had a similar issue recently.

I have a laravel project at `app.example.com` and a SPA at `example.com`. I'm using Sanctum for authentication and I wanted to send verification emails using the `VerifyEmail` notification. However, the verification signed URL is `https://app.example.com/email/verify...` but I needed it to be `https://example.com/email/verify...`.

So extended the `VerifyEmail` notification to override the `verificationUrl` to use relative a URL like @ilzrv did.
But the `signed` middleware failed because `$request->hasValidSignature()` is called without the `$absolute` flag which is defaults to true, so the signatures do not match.

So I extended the `ValidateSignature` middleware to accept an `$absolute` parameter:

```php
class ValidateSignature
{
    public function handle($request, Closure $next, $absolute = true)
    {
        if ($request->hasValidSignature($absolute)) {
            return $next($request);
        }

        throw new InvalidSignatureException;
    }
```

And in the `VerificationController`s contstructor I use it like this:
```php
$this->middleware('signed')->only('verify:0');
```

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/pull/33137
