### ISSUE TITLE
env() returning null variables after "php artisan config:cache" -> NOT CACHING

### ISSUE THREAD

**Issue by terremoth** [laravel/framework#33613]
- Laravel Version: 6.18.1
- PHP Version: 7.3.10
- Database Driver & Version: MySQL 14.14 distrib. 5.7.30

### Description:
I would create this issue on repo https://github.com/laravel/laravel but I cannot create issues there, don't know why.

The problem is: after execute ```php artisan config:cache``` when I enter my app via Tinker, the env() variables are returning null!
I understand  ```php artisan config:cache``` is to CACHE the configuration, and not the other way around!

### Steps To Reproduce:
as an example:
```$ php artisan config:cache```
```$ php artisan tinker```
```php
>>> env('DB_DATABASE')
=> null
```

**Comment by brunogaspar** [comment]
It's expected. Once you call the `config:cache` command, you can no longer use the `env()` helper.

Check here https://laravel.com/docs/7.x/configuration#configuration-caching

**Comment by driesvints** [comment]
@brunogaspar thanks for explaining.

**Comment by terremoth** [comment]
So is just "right" typing a command to cache that does not caches at all?

I discovered this problem in **production** when my Schedule routines were running connecting another server via API.
The documentation says clearly:

>You should typically run the php artisan config:cache command as part of your production deployment routine

My routines running in production and yet happens.

**Comment by terremoth** [comment]
@brunogaspar even in production, in my controllers or models, if I call env() after running ```config:cache``` it would not work?

**Comment by driesvints** [comment]
@terremoth as said before: don't use the `env` helper outside your config files.

**Comment by terremoth** [comment]
@driesvints @brunogaspar 
So, if env() does not work, nor Config::get() in these cases (I've tested here now in controller), what would be the solution to get env variables in my controllers/routes etc after run ```config:cache```?

Or so, should I never use ```config:cache``` if I need env()?

**Comment by terremoth** [comment]
Sorry to ask you guys all this doubts. This "problem" seems to be (or was) a lot of people problem, take a look:

https://www.google.com/search?q=env+variables+after+config%3Acache+returning+null+laravel

**Comment by brunogaspar** [comment]
Going to try to explain, but the majority of it is on the documentation, specially on how to access config values: https://laravel.com/docs/7.x/configuration#accessing-configuration-values

In your example above, you seem to want to access the database table name, so that's a tad more "tricky" since the path of the configuration value can vary due to the different drivers being used, but here's an example:

```php
Config::get('database.connections.mysql.database')
```

You can make this somewhat dynamic based on the selected driver if you so desire.

But either way, that's how you should use it.

---

Now if you have your own environment variables (which is totally normal), you'll need to either create a config file or add inside an existing config file like `config/app.php`, then inside this config file, access them through the `env()` helper and then elsewhere inside your application you retrieve those values through the `Config::get()`.

Here's an example:

#### On your ".env" file

```sh
FOO=bar
```

#### Create a "config/somefile.php" file

```php
<?php

return [
    'foo' => env('FOO'),
];
```

#### Access the values elsewhere on your application 

```php
dump(Config::get('somefile.foo')); // should return "bar"
```

---

> This "problem" seems to be (or was) a lot of people problem, take a look:
> 
> https://www.google.com/search?q=env+variables+after+config%3Acache+returning+null+laravel

The majority of those posts are either lack of reading the documentation or misunderstanding how the Laravel configuration works.

---

Hope it helps and that i haven't mentioned anything wrong or at least not super wrong lol

**Comment by terremoth** [comment]
I understood, thank you for explain. Have a nice weekend :)

**Comment by agumaxwellforcode** [comment]
Run
```
php artisan cache:clear
php artisan cache:clear
```

**Comment by agumaxwellforcode** [comment]
Run
```
php artisan cache:clear
php artisan config:clear
```

**Comment by agumaxwellforcode** [comment]
> Run
> 
> ```
> php artisan cache:clear
> php artisan config:clear
> ```

**Comment by agumaxwellforcode** [comment]
> Run
> 
> ```
> php artisan cache:clear
> php artisan config:clear
> ```

**Comment by mohamadimani** [comment]
t

> Run
> 
> ```
> php artisan cache:clear
> php artisan config:clear
> ```

it worked for me thanks
