### ISSUE TITLE
Issues adding foreign key reference to BIGINT

### ISSUE THREAD

**Issue by bhavesh-hirani** [laravel/framework#33642]
https://github.com/laravel/framework/blob/474cdd83e0d1721f3c0a96a29e77070e82db3006/src/Illuminate/Database/Schema/Blueprint.php#L563

Can this be changed back to `INT`. With `BIGINT`, I am not able to add a foreign key reference.

**Comment by bhavesh-hirani** [comment]
Hi Dries,
Why was this closed without any explanation?

Regards,

**Comment by devcircus** [comment]
This has been the default in Laravel for almost 2 years. You can add foreign keys, you just need to be sure the column types match. You're free to change these as needed for your app. 

Since this repo is for reporting bugs in Laravel, I'm sure this was closed because it's not a bug in the framework itself.
