### ISSUE TITLE
Guarded columns are not refreshed when a DB schema is changed

### ISSUE THREAD

**Issue by besanek** [laravel/framework#33849]
Guarded columns are not refreshed when a DB schema is changed

- Laravel Version: v6.18.35
- PHP Version: v7.3.18
- Database Driver & Version: MariaDB 10.2.31

### Description:

Guarded columns are not refreshed when a DB schema is changed. It is broken by commit https://github.com/laravel/framework/commit/897d107775737a958dbd0b2f3ea37877c7526371

It is a problem for data seeding in migrations.

### Steps To Reproduce:

Model _Setting.php_
```php
class Setting extends Model
{
    /** @var array */
    public $guarded = ['id'];
}
```

Migration _2020_01_01_000000_create_table_settings.php_
```php
public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('key');
            $table->text('value');
        });

        Setting::query()->firstOrCreate(
            [
                'key' => 'min_password_length',
            ], [
                'value' => '10',
            ],
        );
    }
```

Migration _2020_02_02_000000_add_module_to_table_settings.php_
```php
public function up()
    {
        Schema::table('settings', function (Blueprint $table) {
            $table->string('module')->default('system');
        });

        Setting::query()->firstOrCreate(
            [
                'module' => 'eshop',
                'key' => 'max_order_weight',
            ], [
                'value' => '100',
            ],
        );
    }
```

The result is that in Laravel v6.18.35 is model `(key: 'max_order_weight', module: 'system')`, but in versions <v6.18.35 is model `(key: 'max_order_weight', module: 'eshop')`.

It is because `static::$guardableColumns[get_class($this)]` is now filled in first migration and is not longer reflecting schema changes.

**Comment by driesvints** [comment]
Don't put eloquent models in your migrations. Use the DB facade.

**Comment by besanek** [comment]
We have about ~500 migrations. So we need get through each migration and rewrite every use of any model? 

All because of this bug? Really?

**Comment by driesvints** [comment]
I really don't recommend using any app-logic in your migrations. Simply because it's changeable and you're hard wiring your app layer to your database model. This leads to this kinds of problems. More changes could happen in the future to Laravel or your app that could lead to you having to update your migrations regardless.

Migrations are also something you run just once against your production data. When your data has been migrated you usually don't need any logic in your migrations anymore that modify data because it's already been updated. You can safely discard code in those migrations afterwards.

Laravel 8 will come with a `schema:dump` command btw allowing you to squash previous migrations so you don't need to update them. It'll be out in a little under a month.

**Comment by besanek** [comment]
I agree that we are using migrations probably wrongly. But this is BC break and should be in major version, not in patch version.

We can not discard this code from migration due that settings are required for feature tests :slightly_smiling_face:

**Comment by driesvints** [comment]
This was a security vulnerability fix. So this doesn't counts to a BC promise. We try to avoid that as much as possible but sometimes, like now, we didn't have a choice.

> We can not discard this code from migration due that settings are required for feature tests 🙂

Sounds like you need seeders/factories for this instead? If you hop onto discord I'd be happy to take a look at an example if you have one. hmu in #help

**Comment by besanek** [comment]
Ok, thank you for your patience :slightly_smiling_face: 

For now i've put a composer.json conflict with Laravel >= v6.18.35 to our testing package and create high priority backlog task for refactoring migrations.

**Comment by shengslogar** [comment]
@driesvints This is a SUPER old issue, but I'm wondering if your stance on not having model logic inside a migration has changed since [the introduction of `foreignIdFor` in Laravel 8.x](https://github.com/laravel/framework/commit/29e4df7497bf0224ff82d6772ee7f109424990dc).

It strikes me a bit odd that [`Eloquent\Concerns\GuardsAttributes`](https://github.com/laravel/framework/blob/25ab9ef34e105e6e135d87fdc5992eb399533444/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L215-L229) is responsible for "caching" a table's schema, and not [`Schema\Builder`'s `getColumnListing` method](https://github.com/laravel/framework/blob/25ab9ef34e105e6e135d87fdc5992eb399533444/src/Illuminate/Database/Schema/Builder.php#L251-L258). Even if this overall GH issue isn't a desired use-case, could it make sense to move this logic into `Builder`? — and if so, exposing a way to reset the `Builder`'s cache wouldn't seem that far off in my opinion.

`getColumnListing` seems like a pretty critical underpinning of how Laravel talks to the database, so I wouldn't be surprised if I'm making a major oversight here.
