### ISSUE TITLE
Later method buggy

### ISSUE THREAD

**Issue by hakuno** [laravel/framework#33942]
- Laravel Version: 7.22.4
- PHP Version: 7.4
- Database Driver & Version: NONE

### Description:
If I follow the documentation with `now` helper based on Carbon, it has no problem.

But I can't do the same with the `DateInterval` object.

The `later` method from `mailer` doesn't have the same behavior.

The Carbon object got delayed. But the other one is sent without delay.

The method accepts the parameter properly by type hinting. No effect with `DateInterval` though.

### Steps To Reproduce:

I extracted from my class...

```
        $strtime = "+3 minutes";
        $now = new DateTime;
        $timing = (new DateTime)->setTimestamp(strtotime($strtime));
        $interval = $timing->diff($now);
```

And so on...

```
        ...
        $mailer = app('mailer');
        $mailer->to($sendTo)
                ->later($interval, $mailable);
```

The e-mail is sent at moment. No waiting.

---

__UPDATE__

It works with `Illuminate\Support\Carbon` and `DateTime` objects. But `DateInterval` object doesn't.

If it isn't designed for, so the [method](https://laravel.com/api/7.x/Illuminate/Mail/Mailer.html#method_later) needs to be reassigned.

**Comment by ahmedsayedabdelsalam** [comment]
I think it is not an issue but using `diff` method is misleading it is like `2->diff(5)` :D 
your code will return -3 minutes (in the past) not +3 minutes so the mail is sent at moment
I tried to replace the two params `$interval = $now->diff($timing);` and it is working fine after 3 minutes

of course you need to use any queue driver not sync queue because it has not any implementation for delaying.

<img width="1440" alt="Screen Shot 2020-08-20 at 4 03 58 AM" src="https://user-images.githubusercontent.com/29691074/90708849-19dddc80-e29b-11ea-98da-c757e38f87c3.png">
