### ISSUE TITLE
$guarded unexpected behaviour

### ISSUE THREAD

**Issue by milivojsa** [laravel/framework#33978]
- Laravel Version: 7.24
- PHP Version: 7.4.8
- Database Driver & Version: MySQL 8.0.21

### Description:
Until the v7.23 there were no issues with $guarded. 

Recently when the app was updated to v7.24 and after that to v7.25, in both versions, $guarded started to behave unpredictably.

Mutator is not called when there is at least one key in $guarded or $fillable.

Here is an example:

```php
class Article extends Model {
    // attributes table: id, headline, content, updated_at, created_at
    protected $guarded = []; 

    public function setThumbnailAttribute($value) {
        // do some logic even if thumbnail attribute not exists in articles table
    }
}

// use example

$article = Article::create(...);

// $guarded set as above: []
$article->isFillable('headline'); // true
$article->isFillable('content'); // true
$article->isFillable('thumbnail'); // true - as expected

// $guarded set as: ['headline']
$article->isFillable('headline'); // false
$article->isFillable('content'); // true
$article->isFillable('thumbnail'); // false - there you can see unexpected behaviour

// $guarded set as: ['dummy_test_attribute']
$article->isFillable('headline'); // true
$article->isFillable('content'); // true
$article->isFillable('thumbnail'); // false - there you can see unexpected behaviour
```

This issue is connected to the: [Security Release: Laravel 6.18.35, 7.24.0](https://blog.laravel.com/security-release-laravel-61835-7240) and to the: #33975 issue.

### Steps To Reproduce:

1. Set:
```php
protected $guarded = [];
```

2. Check isFillable result for some model attribute and some dummy key (which not exists in the model table)

3. Set:
```php
protected $guarded = ['some_existing_model_key'];
```

4. Repeat step 2

5. Set:
```php
protected $guarded = ['some_not_existing_model_key'];
```

6. Repeat step 2

7. Downgrade laravel/framework to v7.23

8. Repeat steps from 1. to 6. and compare results with previous steps

**Comment by driesvints** [comment]
You can't set attributes that don't exists as table columns.

**Comment by florentpoujol** [comment]
Just for documentation, I came accors this "issue" while upgrading a v5.8 app to v6+.

As we also have quite a few dynamic attributes that exists only because they have getter or setter, my solution was to override the `isFillable()` method in our base model to also check if the attribute has a setter, like so :

```php
    public function isFillable($key): bool
    {
        return parent::isFillable($key) || $this->hasSetMutator($key);
    }
```
See also 
- https://blog.laravel.com/security-release-laravel-61834-7232
- https://blog.laravel.com/security-release-laravel-61835-7240

**Comment by trip-somers** [comment]
"You can't set attributes that don't exists as table columns."

That's an interesting position to take on a breaking change introduced in a minor version release, no?

It is verifiable that this works in previous versions -- and has always worked -- as long as the actual setting that takes place in the mutator occurs on a real database field. For example:

```php
public function setFakeFieldAttribute($value)
{
    $this->attributes['real_field'] = strtolower($value);
}
```

In many cases, operations like this are used to avoid form/input conflicts and allow for a greater range of assignment possibilities.

**Comment by driesvints** [comment]
> That's an interesting position to take on a breaking change introduced in a minor version release, no?

We never officially supported that.

**Comment by trip-somers** [comment]
Explicitly, that may be true. Implicitly, I don't think that's true. Why wouldn't a developer see something like this:

"You may also use accessors to return new, computed values from existing attributes:"

```php
public function getFullNameAttribute()
{
    return "{$this->first_name} {$this->last_name}";
}
```

... and not think they can do something like this, _especially since it has worked since it was introduced_:

```php
public function setFullNameAttribute($value)
{
    $name = explode(' ', $value);
    $this->attributes['first_name'] = $name[0];
    $this->attributes['last_name'] = $name[1];
}
```

**Comment by driesvints** [comment]
@trip-somers how would that even work if there aren't database columns for those attributes?

**Comment by trip-somers** [comment]
In that example, `full_name` does not exist but `first_name` and `last_name` do.

Practically, it's a decent method of providing backwards compatibility for updates to legacy systems when database updates are required ahead of ability to update every piece of code related to it.

Building on the example I provided above, let's say `full_name` used to exist, but for reasons beyond the developer's control, that field was replaced by `first_name` and `last_name`. All of the code references `full_name` -- form inputs, commands, templates, etc. -- so if the developer can only use `getFullNameAttribute()`, only half of the problem is solved.

**Comment by trip-somers** [comment]
That's obviously just one example -- and it is not perfect -- but there definitely people out there setting pseudo-fields in order to mutate them to real fields.

**Comment by trip-somers** [comment]
Having read up on the release information, it seems like this would work if we just switched to using `$fillable` instead of `$guarded` on these models, and added the pseudo-fields to the `$fillable` array.

Would a patch similar to what @florentpoujol posted be feasible, or would that re-expose the problem this update was trying to solve?

**Comment by milivojsa** [comment]
You can still use mutators on fake attributes if $guarded array is empty. 

I agree with @trip-somers , it is a very good feature and accessors still suport fake columns so it seems logic to enable this on mutators too. @trip-somers provided much better example why this can be of huge help to the developer.

We had an issue with this patch release because now you can't recreate this behaviour without modifying or extending Laravel behaviour. Also, custom cast feature is fully related to the db column so it is not much of help to achieve this.

**Comment by aksonnic** [comment]
> @trip-somers how would that even work if there aren't database columns for those attributes?

That's kinda the point of wanting the feature. 

How do the `get*Attribute` methods work without database columns for those attributes?

**Comment by judgej** [comment]
@florentpoujol great workaround for this inconsistent behaviour. For Laravel v8 upwards it is worth extending it to include property casting:

```php
    public function isFillable($key): bool
    {
        return parent::isFillable($key) || $this->hasSetMutator($key) || $this->hasCast($key);
    }
```

This change broke a lot of sites for me, requiring restructuring of the way some models were created and updated. This workaround gets things back on track to keeping the code cleaner. HTH
