### ISSUE TITLE
$this->faker has no providers loaded in model factories

### ISSUE THREAD

**Issue by edgrosvenor** [laravel/framework#34209]
- Laravel Version: 8.0.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.7.29

### Description:

Any attempt to use Model::factory()->create() where $this->faker is used in the definition() method will result in Faker complaining of an unknown formatter. It appears that by default there are no providers loaded.

### Steps To Reproduce:

Write a test in a fresh Laravel 8 installation that uses the User factory that ships with it and run it.

```
public function testBasicTest()
    {
        User::factory()->create();
    }
```

Results in

```
 Unknown formatter "name"

  at vendor/fzaninotto/faker/src/Faker/Generator.php:248

```

**Comment by edgrosvenor** [comment]
Same problem if I try to use the withFaker trait on a test.

**Comment by taylorotwell** [comment]
You are attempting to do this in a unit test class. Unit test classes do not boot the framework at all.

**Comment by Darival** [comment]
@taylorotwell @JeffreyWay 
this is the source of confussion:
[What's new in laravel 8, episode 8](https://laracasts.com/series/whats-new-in-laravel-8/episodes/8)

Jeffrey creates a unit test in tests/Unit but use Test/TestCase instead of the PHPUnit\Framework\TestCase used when
`php artisan make:test --unit`

**Comment by JeffreyWay** [comment]
If you want your unit tests to boot the framework, yes you need to extend `Tests\TestCase`. 👍
