### ISSUE TITLE
Route redirect not working in api routing

### ISSUE THREAD

**Issue by Orrison** [laravel/framework#34201]
- Laravel Version: 7.25.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:
`Route::permanentRedirect` and `Route::redirect` do not seem to work as expected in `api.php`. It does not seem to work at all and you can only use the Route::redirect's within `web.php`

None of the following work in `api.php`:
```php
Route::redirect('/my/route', '/my/otherroute');
Route::permanentRedirect('/my/route', '/my/otherroute');
Route::redirect('/api/my/route', '/api/my/otherroute');
Route::permanentRedirect('/api/my/route', '/api/my/otherroute');
```

But the following DOES work in `web.php`:
```php
Route::redirect('/api/my/route', '/api/my/otherroute');
Route::permanentRedirect('/api/my/route', '/api/my/otherroute');
```

I would assume that these redirect helpers would work in `api.php` as well as possibly even auto including the `api` prefix, but that does not seem to be the case.

### Steps To Reproduce:

1. Make a route in `api.php`, something like:
```php
Route::get('/my/route', function () {
    return 'hello';
});
```
2. Try to create a redirect to it using either `Route::permanentRedirect` or `Route::redirect` in `api.php` including or not including the `api` prefix, something like:
```php
Route::redirect('/my/otherroute', '/my/route');
//or
Route::redirect('/api/my/otherroute', '/api/my/route');
```
3. It should return a 404 as it does not seem to create the redirect

**Comment by taylorotwell** [comment]
Works fine for me.

**Comment by nazrulcst** [comment]
I am novice in Laravel 7.x.
Can you guys please clear this Redirect Routes Point .

Routes/web.php
Route::redirect('/','BasicController@SayHello');
Its say 404.

Route::redirect('/here', '/there', 301);
 can i use ( there ) any controller??

**Comment by csimpi** [comment]
@taylorotwell 's usual awesome support handling

**Comment by simonhampel** [comment]
Just for the benefit of anyone else finding this closed issue via a web search (like me!), the issue with the OP's redirect was that the redirect destination must have the `/api` prefix added.

So the correct redirect in the original example is:

```
Route::redirect('/my/otherroute', '/api/my/route');
```

Note that the global api prefix (from `api.php`) is automatically applied to the source, but not to the destination - I assume because it doesn't want to assume that you are redirecting to another api route. As such, you need to add the api prefix yourself to the destination.
