### ISSUE TITLE
Artisan Down `--allow` option

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#34446]
Can the removal of the `--allow` option on the `artisan down` command be reconcidered?

It was heavily used within my deployment scripts to allow for criticalcss generation. I can no longer do this effectively without the option being provided

Sample Deploy Script
```
...
publicIp=`host roi-dev.ecoproducer.com | awk '{ print $4}'`

# Enable maintenence mode
$FORGE_PHP artisan down --allow=$publicIp || true

...

yarn run prod
# Yarn run prod calls critical css which calls the website and snapshots the css used. 
# It ends up using the server's public ip to access the site which is why I have it in the --allow option
```

**Comment by taylorotwell** [comment]
No plans to do this.

**Comment by gofish543** [comment]
From a developer prospective, how come?
Is there an alternative solution you would recommend?

**Comment by tobz-nz** [comment]
@taylorotwell 

Adding my opinion for this as well - having the `--allow` flag was very useful, in my case we have a micro service running on a windows server due to a background process that's required - we only have 1 instance of this server for licensing reasons of this background process - at times we need to take take it down from production (`artisan down --status=204`) for maintenance and testing. but for proper testing we need the staging app (another laravel instance) server to be able to access it in a stateless way. 
`--allow` used to .. allow.. this.

I'd also settle for being able to pass the `secret` as a header, if that's an acceptable solution.

**Comment by rodrigopedra** [comment]
@gofish543 and @tobz-nz 

You can add a `handle` method to your app's `PreventRequestsDuringMaintenance` middleware to bypass the maintenance mode:

~~~php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance as Middleware;

class PreventRequestsDuringMaintenance extends Middleware
{
    /**
     * The URIs that should be reachable while maintenance mode is enabled.
     *
     * @var array
     */
    protected $except = [
    ];

    public function handle($request, \Closure $next)
    {
        if (! $this->app->isDownForMaintenance()) {
            return $next($request);
        }

        // read IP from config, or use another codition you need
        if ($request->getClientIp() === '127.0.0.1') {
            return $next($request);
        }

        // delegate to the base middleware
        return parent::handle($request, $next);
    }
}
~~~

Hope this helps.

**Comment by tobz-nz** [comment]
@rodrigopedra Thanks.
I still would like to see a built in way to bypass maintenance mode in a stateless fashion, but this is a good option for now.

I mean, you currently cannot bypass maintenance mode in a API unless your client is stateful (in my case, server to server, it is not). Not ideal.

But thanks again for this solution :)
