### ISSUE TITLE
Latest version of carbon breaks ISO8601 date format support in eloquent

### ISSUE THREAD

**Issue by njaremko** [laravel/framework#34474]
- Laravel Version: 8.6.0
- PHP Version: 7.4.8
- Database Driver & Version: 

### Description:
Latest release of carbon breaks iso8601 date formating on models. Version 2.39.0 of carbon works fine, 2.40.0 breaks.

### Steps To Reproduce:
Have Carbon >2.39.0 installed
- Set `protected $dateFormat = 'c';` on a model
- Set some datetime (for example `updated_at`) to `Carbon::now()->toIso8601String()`
- Save

You'll get 

vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:662
vendor/laravel/framework/src/Illuminate/Support/DateFactory.php:217
vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:919
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:944
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:649
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1641

**Comment by taylorotwell** [comment]
I don't maintain Carbon. @kylekatarnls

**Comment by kylekatarnls** [comment]
Hello, this sounds actually to be a bug in PHP which was muted by Carbon until 2.40.0.

If I check:
```php
var_dump(DateTime::createFromFormat('c', (new DateTime())->format('c')));
```
This fails, we get `false` instead of a date. And calling `DateTime::getLastErrors()` gives the error you have: "The format separator does not match" + "Trailing data".

Until 2.40, `Carbon::hasFormat()` silently returned `false` for `c` format. Then Laravel fallback to `Carbon::parse()` which gives the expected result with an ISO8601 string.

Since 2.40, it returns `true` (which is right since the string output of `toIso8601String()` is strictly identical to the `c` format). So `createFromFormat()` is called and not `parse()`.

I will check if a bug is tracked for that from PHP side and will provide a work-around in `createFromFormat` to make `c` format properly supported.

**Comment by kylekatarnls** [comment]
Actually a bug has been opened bug it has be wrongly qualified as duplicated and closed 😢  https://bugs.php.net/bug.php?id=72592

**Comment by kylekatarnls** [comment]
Until there, you can use `'Y-m-d\TH:i:sP'` instead which is actually `'c'` but does not fail with createFromFormat().

**Comment by kylekatarnls** [comment]
You can now use `c` format again with by updating Carbon to [2.40.1](https://github.com/briannesbitt/Carbon/releases/tag/2.40.1)

`c` is currently replace with `Y-m-d\TH:i:sP` on the fly until having input from PHP developers about the bug.

**Comment by kylekatarnls** [comment]
https://bugs.php.net/bug.php?id=72592 has been re-opened :) as feature request 👍 

> Re-opened as this is a new feature request: to add support for the 'c' format, which is not currently one of the supported formats for DateTime::createFromFormat()[1].
>
>[1] https://www.php.net/manual/en/datetime.createfromformat.php

cmb recommended to use `DateTimeInterface::ATOM` instead of `'c'`
