### ISSUE TITLE
7.28.3 Broken array item validation in tests?

### ISSUE THREAD

**Issue by AlexMordred** [laravel/framework#34627]
- Laravel Version: 7.28.3
- PHP Version: 7.4.10
- Database Driver & Version: NA

### Description:

I have a many-to-many categories relationship on an entity. I have the following validation rules in a FormRequest class for that entity:

```php
'categories' => [
    'required',
    'array',
    'min: 1',
],
'categories.*' => [
    'required',
    'numeric',
    'distinct',
    'exists:categories,id',
],
```

### Steps To Reproduce (Tests):

In a test I have the following code:

```php
$data = [
    'categories' => [100, 101],
];

$this->actingAs($this->admin)
    ->postJson(route('articles.store'), $data)
    ->assertStatus(422)
    ->assertJsonValidationErrors(['categories']);
```

The provided category IDs don't exist and should produce an error, but I get `Failed asserting that an array has the key 'categories'.`. The `->assertStatus(422)` assertion passes as the validation fails for other expected fields, but the the `'categories.*'` rule group is ignored completely. On the other hand, the same 'categories'.` validation seem to work in the browser on the site.

**Comment by MortezaPoussaneh** [comment]
This is not a bug, you should assert `categories.0` and `categories.1` since there is no validation error for `categories`. The error message is saying that it can not see `categories` in error messages which is right. Now you have `categories.0` and `categories.1` errors in your error bag. `assertJsonValidationErrors` searches for the key string you provided and there is no error by `categories` key.

**Comment by AlexMordred** [comment]
@MortezaPoussaneh you're right, thank you!
