### ISSUE TITLE
Use empty() with collections always returning false

### ISSUE THREAD

**Issue by andreladocruz** [laravel/framework#34731]
- Laravel Version: v8.9.0
- PHP Version: 7.3.22
- Database Driver & Version: Mysql 5.7.22

### Description:
When using empty() to test if a collection has items, is always returning false;

### Steps To Reproduce:
$item = collect();
dd(empty($item));

**Comment by AegirLeet** [comment]
What were you expecting here? According to the [PHP docs](https://www.php.net/manual/en/function.empty.php):
>  `empty ( mixed $var ) : bool`
> Determine whether a variable is considered to be empty. A variable is considered empty if it does not exist or if its value equals FALSE.

Since `$item` obviously exists (you just declared it), `empty($item)` will return false.

Use [`$item->isEmpty()`](https://laravel.com/docs/8.x/collections#method-isempty), [`$item->isNotEmpty()`](https://laravel.com/docs/8.x/collections#method-isnotempty) or [`$item->count()`](https://laravel.com/docs/8.x/collections#method-count) to check whether a collection contains any items, as documented.

**Comment by andreladocruz** [comment]
@AegirLeet ,

I totally agree. 

So, the question is why it worked in laravel < 8 and there are no warnings in 8.x documentation upgrade guide??

**Comment by AegirLeet** [comment]
This can't work and it never has.

**Comment by mfn** [comment]
Maybe some framework result previously was _not_ a collection and now is?
