### ISSUE TITLE
[8.x] Server returns 200 instead of 404 when throwing NotFoundHttpException

### ISSUE THREAD

**Issue by flxbe** [laravel/framework#34747]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL, 5.7.31

### Description:
After Updating from 7.x to 8.9, the server returns the wrong status code. This only occurs in our CI pipeline (bitbucket) when serving the application with `php artisan serve` and executing our frontend integration tests. I am not able to reproduce the issue locally, not even by executing the tests in the exact same image we use in our pipeline, using the same .env file.

We have additional Laravel HTTP tests. In those, the correct status code is returned.

The specific route is a JSON endpoint to retrieve a single model instance. This is the exact controller code: 
```php
public function findOne($eventId)
{
    $event = Event::withMailRecords()->withContacts()->withContingents()->findOrFail($eventId);

    return new EventResource($event);
}
```

### Steps To Reproduce:
Cannot reproduce locally. I am however happy about any tips on how to make it work.

**Comment by driesvints** [comment]
Since you've only been able to reproduce this issue in a very specific situation I feel that this is more something for a support channel. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
