### ISSUE TITLE
Can't

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#35141]
- Laravel Version: 8.13.0
- PHP Version: 7.4.12
- Database Driver & Version: 12.4

### Description:
Can't get notification id.

### Steps To Reproduce:
1. Create test:
```php
public function testMarkAsReadV1(): void
{
    $notification = Notification::query()
        ->where('notifiable_id', $this->user->id)
        ->where('type', User::class)
        ->whereNull('read_at')
        ->get()
        ->random();

    $b = $notification->id; // 0, but $notification has id = eeaccfdb-6de6-3bf5-a503-25347507c57b, as shown in below screen
    // ...
}
```
after that we get `0` as ID
![image](https://user-images.githubusercontent.com/42643563/98439592-2e3fb180-20f3-11eb-9b58-160aa7bbcaa0.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LocalHeroPro** [comment]
Consider not closing issues and resolve it in framework to casting uuid to string, not to int.
Because it's standard Laravel migration - to add uudi on PK column on notifications.

**Comment by rodrigopedra** [comment]
The issue is that you added a custom Notification model to your project (`App\Models\Notification`). 

Then you should configure its `$keyType` to be string.  This is not an error in Laravel as a framework.

Add this property to your project's `App\Models\Notification` model:

~~~php
    protected $keyType = 'string';
~~~

Or use the `DatabaseNotification` model provided by Laravel:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Notifications/DatabaseNotification.php

This model, which is shipped with the framework, already has its `$keyType` set to string.
