### ISSUE TITLE
dontReport does not work as it is expected

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/framework#35222]
- Laravel Version: 7.29.3
- PHP Version: 7.4.10

### Description:

According to [documentation](https://laravel.com/docs/8.x/errors#ignoring-exceptions-by-type) adding a class to  `dontReport` array inside `App\Exceptions\Handler` will make it unreportable. But does not explicitly says that removing them will do nothing. Personally by removing any of these classes from `dontReport` array I would expect to make them logged. I suppose that's the purpose of being prefilled after all.

### Steps To Reproduce:

1) Remove `Authorization::class` from `dontReport` array 
1) throw an `AuthorizationException`
1) Go to see the logs

**Comment by dionysiosarvanitis** [comment]
Just show that `dontReport` is not prefilled as I said and therefore my issue is untenable.

**Comment by rodrigopedra** [comment]
The base exception handler has a `$internalDontReport` array it merges with userland `$dontReport` before assessing if it needs to report an exception.

- `$internalDontReport` definition:

https://github.com/laravel/framework/blob/bced05ea1f9548b0745f20dd6ee72a7fbb8858f6/src/Illuminate/Foundation/Exceptions/Handler.php#L55-L69

- `$internalDontReport` usage:

https://github.com/laravel/framework/blob/bced05ea1f9548b0745f20dd6ee72a7fbb8858f6/src/Illuminate/Foundation/Exceptions/Handler.php#L139-L152

As you are using Laravel 7 I linked code samples for that version.

You could either:

- Override the `$internalDontReport` property  in your app's exception handler and remove the exception you want to report
- Override the `shouldntReport(...)` method in your app's exception handler and add a `if` clause to check for the exception you want to report, then return true, otherwise return `parent::shouldntReport($e)`

**Comment by dionysiosarvanitis** [comment]
Overriding the `$internalDontReport` is what I did. 

I think it is better for internalDontReport to not include AuthenticationException::class and AuthorizationException::class. These classes must be reported according to audit logging guidelines and therefore belongs to the userland.
