### ISSUE TITLE
Issue with modifing column type

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#35435]
- Laravel Version: 8.15.0
- PHP Version: 7.3.#
- Database Driver & Version: PostgreSQL

### Description:
Issue with: https://laravel.com/docs/8.x/migrations#modifying-columns

### Steps To Reproduce:
1. Have column with type `text`
2. Run that migration:
```php
Schema::table('users', function (Blueprint $table) {
    $table->unsignedBigInteger('fk_id')->nullable()->change();
});
```
get:
```bash
  Illuminate\Database\QueryException 

  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "fk_id" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING fk_id::bigint". (SQL: ALTER TABLE users ALTER fk_id TYPE BIGINT)

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LocalHeroPro** [comment]
No. It wasn't a question, it's report a another bug on that framework that you close without resolving it.

**Comment by driesvints** [comment]
The explanation of the problem is in the error message you posted. Besides, Laravel uses doctrine/dbal behind the scenes to alter table columns so this isn't a direct issue with Laravel.

This isn't the first time you've posted an issue which is basically a support request. I'm gonna have to ask you to post the problems you're facing on a support channel first before you post them on the issue tracker. There's multiple channels available for you to use with hundreds of people ready to help you out. Don't assume that every problem you're facing is a bug in the first place.

Now I'd really appreciate it if you showed a little more respect to OSS maintainers. You're using free software here. Don't assume that anyone owes you anything.

**Comment by LocalHeroPro** [comment]
At least don't close bugs as they don't ever exists.
Thanks.

**Comment by taylorotwell** [comment]
Bugs regarding changing columns aren't Laravel bugs - they are doctrine/dbal bugs. We don't manage the logic for changing columns.
