### ISSUE TITLE
When the request content-type is json, can not get the modified value after use offsetSet() modify the query value

### ISSUE THREAD

**Issue by phpcxy** [laravel/framework#35543]
- Laravel Version: 7.29.3
- PHP Version: 7.4.3
- Database Driver & Version: mysql 5.7

### Description:
If the request content-type is `application/json`, i try to use `$request->offsetSet()` to modify the query value. After that, i use `$request->get()` can not get the modified value.

If i delete the request header `content-type:application/json`, I can get the modified value.

### Steps To Reproduce:
Here is my code:
```
Route::get('/test', function () {
    $request = request();
    dump($request->get('key')); //foo
    
    // modify
    $request->offsetSet('key', 'bar');
    
    dump($request->get('key'));
    dump($request->key);
});
```
0.access the url `http://my-domain.test/test?key=foo`

1.request header is `content-type:application/json`, the output is:
```
foo
foo
bar
```

2.delete header `content-type:application/json`, the output is:
```
foo
bar
bar
```

**Comment by derekmd** [comment]
Call `$request->input('key')` instead of `$request->get('key')`.

Laravel's `Request` class puts JSON parameters into a `ParameterBag` object that the methods `input()`, `all()`, `offsetSet()`, `merge()`, `replace()`, etc. interact with. The `get()` method is defined in the parent Symfony class and it doesn't touch that JSON object.

There was talk of adding a `@deprecated` annotation to `Illuminate\Http\Request::get()` but it's still considered an active Symfony method that some Laravel applications use. Instead a docblock comment was added to suggest avoiding use of that method. Maybe the language could be updated to specifically mention don't use it if you want JSON input.

https://github.com/laravel/framework/blob/2f00b61b67f7b0f64fb6fe3ec45b790838783bca/src/Illuminate/Http/Request.php#L330-L373

More history:

* https://github.com/laravel/framework/pull/24689
* https://github.com/laravel/ideas/issues/114
* https://github.com/laravel/framework/pull/24699
