### ISSUE TITLE
Storage::assertExists(null) intended behaviour

### ISSUE THREAD

**Issue by gandesc** [laravel/framework#35576]
- Laravel Version: 8.18.1
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8

### Description:

When using in tests, `Storage::assertExists(null)` does not thow an exception (due to the use of `Array::wrap()` on the method's first line).

While such cases can be addressed with another assertion, is this the intended behaviour? Would it not make sense to throw an exception?

Thank you

### Steps To Reproduce:

Open tinker and type `Storage::assertExists(null)`.

**Comment by taylorotwell** [comment]
We wouldn't change it now because it would be a breaking change.

**Comment by aocneanu** [comment]
@taylorotwell Could you provide more details ?

Right now `Storage::assertExists($path)` attempts to do under the hood `PHPUnit::assertTrue(Storage::exists($path)`, which would throw a `PHPUnit\Framework\ExpectationFailedException`

Because `Arr::wrap(null)` returns `[]` the assertion is never made.

We could add before the foreach, without breaking anything, something like :

`$paths = $path === null ? [null] : Arr::wrap($path)`

It's ugly but it fixes the problem until the breaking change is afforded.

RIght now every `Storage::assertExists($this->file->path)` where path is null will pass, which it's a false positive with a relevant impact.

```php
public function assertExists($path, $content = null)
    {
        $paths = $path === null ? [null] : Arr::wrap($path);

        foreach ($paths as $path) {
            PHPUnit::assertTrue(
                $this->exists($path),
                "Unable to find a file at path [{$path}]."
            );

            if (! is_null($content)) {
                $actual = $this->get($path);

                PHPUnit::assertSame(
                    $content,
                    $actual,
                    "File [{$path}] was found, but content [{$actual}] does not match [{$content}]."
                );
            }
        }

        return $this;
    }
```
