### ISSUE TITLE
Running psalm is not possible.

### ISSUE THREAD

**Issue by stanimirdim92** [laravel/framework#35620]
- Laravel Version: 8.17.x, 8.19.0
- PHP Version: 7.4.6+
- Database Driver & Version: MySQL 8.0.22

### Description:
Trying to install psalm with PHPStorm 2020.03. All composer packages are fully upgraded to latest versions. Laravel files are up to date according to Laravel 8.

### Steps To Reproduce:
1. Run ```composer require --dev vimeo/psalm```
2. Navigate to the root of the project and run ```./vendor/bin/psalm --init --debug``` 

Output:
```
Using reflection to locate file for Doctrine\DBAL\Driver\PDOMySql\Driver
Using reflection to locate file for Illuminate\Database\PDO\MySqlDriver
PHP Fatal error:  Declaration of Illuminate\Database\PDO\Concerns\ConnectsToDatabase::connect(array $params) must be compatible with Doctrine\DBAL\Driver::connect(array $params, $username = null, $password = null, array $driverOptions = []) in /var/www/html/nettoffice-api/vendor/laravel/framework/src/Illuminate/Database/PDO/MySqlDriver.php on line 16
Fatal error: Declaration of Illuminate\Database\PDO\Concerns\ConnectsToDatabase::connect(array $params) must be compatible with Doctrine\DBAL\Driver::connect(array $params, $username = null, $password = null, array $driverOptions = []) in /var/www/html/nettoffice-api/vendor/laravel/framework/src/Illuminate/Database/PDO/MySqlDriver.php on line 16
```
Desired output:
It should generate psalm.xml

**Comment by driesvints** [comment]
We don't optimize for tools like Psalm, sorry.

**Comment by jason-klein** [comment]
_This issue page is one of the only matches found when I search online for the error, so I thought I'd share my workaround in case you (or anyone else who encounters this error) would like to use Psalm with a Laravel project. My apologies to Dries if this reopens the issue. It can be closed again._

@stanimirdim92 I encountered the exact same error when following the [Psalm Getting Started](https://psalm.dev/docs/running_psalm/installation/) instructions for a Laravel project. The problem is that Psalm, by default, attempts to analyze all code (including vendor code, such as the Laravel Framework files). Follow the instructions below to have Psalm skip the vendor code and only analyze your project code.

1. Open a terminal window and change to your project directory
`cd ~/Code/MyLaravelApp`
2. Run Psalm Init with a directory parameter "app" and an error level parameter "8"
`./vendor/bin/psalm --init app 8`
3. Run Psalm
`./vendor/bin/psalm`


Step 2 above will create the following `psalm.xml` configuration file that will scan your "app" directory with the most lenient ruleset. Adjust the [error level](https://psalm.dev/docs/running_psalm/error_levels/) accordingly (values 1 to 8). The configuration automatically skips the "vendor" directory, which you would not normally want to scan. If your Laravel code lives in a different directory, change "app" to your project directory name.

    <?xml version="1.0"?>
    <psalm
        errorLevel="8"
        resolveFromConfigFile="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    >
        <projectFiles>
            <directory name="app" />
            <ignoreFiles>
                <directory name="vendor" />
            </ignoreFiles>
        </projectFiles>
    </psalm>

You can modify the `psalm.xml` configuration file to include other directories that contain PHP code you would like to scan. For example, I manually added config, database, resources, and routes directories to my config file as shown below. Run Step 3 again after modifying your config file to perform another code analysis.

    <?xml version="1.0"?>
    <psalm
        errorLevel="8"
        resolveFromConfigFile="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    >
        <projectFiles>
            <directory name="app" />
            <directory name="config" />
            <directory name="database" />
            <directory name="resources" />
            <directory name="routes" />
            <ignoreFiles>
                <directory name="vendor" />
            </ignoreFiles>
        </projectFiles>
    </psalm>
