### ISSUE TITLE
$job->backoff and $job->retryAfter don't override connection's retry_after setting

### ISSUE THREAD

**Issue by mikolajzieba** [laravel/framework#35633]
- Laravel Version: 8.18.1
- PHP Version: 8.0
- Database Driver & Version:

### Description:
I have a job, that may have a different timeout, and it's specified right before running as `$job->timeout = X`.
As the docs says, retry_after should be higher value than timeout, but I'm not able to set it for a job. Setting $job->retryAfter and $job->backoff don't make any change, I made it as follows:
`$job->backoff = $job->timeout + 5`
`$job->retryAfter = $job->timeout + 5`

Is there any way to override queue connection `retry_after` setting on a job level?

**Comment by taylorotwell** [comment]
Regarding backoff: 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/463230/102366368-330f4500-3f7e-11eb-95bf-8d33dfe3c852.png">

Regarding retry_after, there is no way to set that on a job level. It is set at the queue connection level.

**Comment by mikolajzieba** [comment]
@taylorotwell ok, but we have backoff and retry_after defining the time needed to retry the job, but which one is being took into account when backoff is defined for a job? 
Is there any logic allowing me to keep adjustable job timeout, and not being duplicated (when retry_after is too low) or wait to retry a job too long (when retry_after is too high)? 
Thanks.

**Comment by graemlourens** [comment]
@mikolajzieba From your last reply i assume that you're not quite understanding how retry_after (connection), backoff & timeout (job) work together (its not that trivial, and was very confusing for me at the beginning)

The retry_after in connection settings is a safety measure in case jobs die (php process dies, exits ungracefully, for example on a fatal error) in order that workers will eventually pick up the job again. This is not job specific.

This retry_after in your connection has to be set slightly higher than the maximum timeout of ANY of your jobs. If your longest job runs 2 Minutes, your retry_after should be set to 2 Minutes and 5 seconds to make sure that a job is never picked up again (on a connection level) with the possibility that a job is currently still processing.

The timeout on your jobs in this case always HAVE to be smaller than the retry_after of your connection.
If you have only a certain few very long running jobs and do not want other jobs to 'suffer' for this very high protection retry setting, you can always make 2 different connections.

This all however has nothing to do with backoff. 

If you're using queues in a professional environment, i'd highly suggest reading https://learn-laravel-queues.com/ it goes into depths with all you need to know about how laravels queues work (which are rock solid, but not everything is easily understood initially)

**Comment by mikolajzieba** [comment]
@graemlourens Thank you for your explanation, some of the things are clearer now, but I think, that my problem is still remain unresolved, and it's a case, that couldn't be solved in any way with the current Laravel's worker implementation. 
 
Description of the job:
Long running job (depends on a job, it can be between 30min - 24h)
$job->timeout = depends on the job, it's being set between 35min - 24h
connection retry_after: 25h (the longest possible job on this connection)

Case #1
$job->tries = 1
On exception: OK
On timeout: OK

Case #2
$job->tries = 2 (or more)
On exception: OK
On timeout: Job is dangling, waiting for picking up. No exception. Job is not failed, it's showing as running in horizon, but actually the process was killed. 

I cannot do anything with the case #2. When job timeouts with `tries` set to more than 1, then it's not being run again (as it should). 
As I understand, in Case #1, the code from Worker in method `markJobAsFailedIfWillExceedMaxAttempts` handles the failed job. But in the Case #2, it's not fired, because there are more attempts waiting to be performed. 
I think, that it's waiting to hit `retry_after` set on connection, to be picked up again and handled properly. 

As you can see, with a variable value in the $job->timeout, it's imposible to pick up job right after timeout, because it must wait to hit retry_after, which is the longest time possible ever for any job on this connection, so in my case, job could wait even 24h to be retried after timeout.

**Comment by graemlourens** [comment]
@mikolajzieba yes, you have accurately described how the queues work, and indeed in case 2 the workers will only pickup that job again for the second attempt after the set period in retry_after. This is necessary because there is NO way to reliably know if a job died or timed out. This is why it waits the amount of retry_after to be absolutely sure that that job is not being processed anywhere else anymore.

Think of retry_after as a safety net to re-run jobs that may have not been processed for various reasons (network interruptions, timeouts, memory overflows, killed processes etc)

If you have vastly different job runtimes, then it is suggested for you to setup 2 queue connections (both can point to the same driver) with different retry_after values, but you then have to make sure that you push the long running jobs to the right queue connection (not queue, i'm talking about connections).

On a side-note: it is bad practise to have such long running jobs. Nowadays with laravels queue batches and other methods there in most cases are ways to split up long running jobs into multiple smaller ones. Consider when you want to update your app, you would have to wait worst case 24h to update as your old job is still running. The chance of something happening to a long running job grows exponentially in my experience when going over the 60 second mark. Our rule is < 120s and its served us rather well.

**Comment by mikolajzieba** [comment]
@graemlourens Jobs that we are running, must be long-running and we accept all inconveniences related to this solution, it's just fine for us, especially that we don't need to write dedicated solution for that.
The only problem is with `retry_after` when job timeouts. Current implementation of workers won't work in our scenario. It would be the best, to be able to define `retry_after` on job individually.
Do you have any suggestion for a solution, how to keep long running jobs with different timeout times, but to restart them on failure right after they timeout?

**Comment by graemlourens** [comment]
@mikolajzieba to my knowledge this is not possible in the current way that jobs & queues are implemented. You would have to build some custom logic that currently i do not see an easy way to do without a large overhead. This is the downside of having long running jobs.

The only solution here is to write your own custom logic. One solution would be that your long running job sends out 'heartbeat' signals somewhere (for example logs). You monitor those logs, and when you see that there is no heartbeat from that specific job, you dispatch a new job to the queue (the jobs would have to have $tries set to 1 in that case, as they will never be retried). But i honestly have to say that this sounds like a very difficult solution to make reliable.

I guess we'd have to end the discussion here as this is not an issue of laravel or queues. Its by design and has its reasons.

**Comment by mikolajzieba** [comment]
@graemlourens The problem is, that I would prefer keeping laravel jobs, and make the smallest effort to make them work in my case. I think, that maybe using my own queue connection implementation for that, would do the job.
Anyway, thanks for help and understanding, I really appreciate that.

**Comment by nikemeal** [comment]
I have a similar issue in that a job can run for a varying amount of time (based on the data it receives) so I can set the timeout dynamically based on previous runtimes.
From what I can tell with the following command `artisan queue:work --tries=1` this would be true
- `public $timeout = 10` would be set on job run, and would tell it to timeout after 10 seconds (this is an example time only!)
- the process itself is then killed after 10 seconds, and another is not started
- when queue:work runs again it will check to see if the retry_after value is passed and if tries=1 it will fail the job allowing it to be run again

the issue here is that although its only set to try once, it will have to retry for a second time to see that it shouldn't, and then fail it.

i was hoping to be able to tell a job to run once only, and when the timeout is exceeded to fail the job and that's it.  not to then have to rely on a retry piece of logic when it isn't retrying it
