### ISSUE TITLE
Route rate limiting is not working properly when routes are cached

### ISSUE THREAD

**Issue by julianpoma** [laravel/framework#35649]
- Laravel Version: 8.3
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Named route rate limits are not working properly when the app routes are cached with `php artisan route:cache`. 

### Steps To Reproduce:

1. Define a rate limiting 
```php
RateLimiter::for('test', function (Request $request) {
    return Limit::perMinute(20)->by($request->ip());
});
```

2. Attach it to a route
```php
Route::get('/test', TestController::class)->middleware('throttle:test');
```

3. Hit the route. You should be able to hit the route 20 times / minute, and headers shows 20 max attempts as configured.

3. Run the command `php artisan route:cache`

4. I can only hit the endpoint once. After the second request, I get a `429 Too Many Requests` status. The headers shows 0 request available.

### Extra information

It seems that when the routes are cached, on the `Illuminate\Routing\Middleware\ThrottleRequests`, `->handle()` method, the condition `$this->limiter->limiter($maxAttempts)` is failing. It returns null when it should return the route limit instance that I defined. 

The `RateLimiter->limiters` prop is an empty array. This is not the case when the routes are not cached.

This also happens with both `ThrottleRequests` and `ThrottleRequestsWithRedis` middlewares

**Comment by driesvints** [comment]
Please upgrade to the latest version and try again.

**Comment by julianpoma** [comment]
Hi @driesvints !

I am on the latest Laravel version, 8.19.0, and I just ran `php composer update` just in case.

Same behavior.

**Comment by driesvints** [comment]
@julianpoma I can't reproduce it with your steps from above. I can hit the endpoint a maximum of 20 times even when I cache my routes. 

If you need further help please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by peter-at-bpt** [comment]
@julianpoma I'm experiencing this and am able to reproduce it consistently.

Framework version 8.49.2, this is a release branch upgrading from 7.x.

Just as you've described, `RateLimiter::limiters[]` does not contain any callback registered with `RateLimiter::for()` when routes are cached. Further the `RouteServiceProvider@configureRateLimiting()` method is never called when routes are cached, I assume because this service provider is never instantiated when they're cached.

Were you ever able to find a resolution to this? I've gotten about as far as you got when you opened this issue and that's all so far.

**Comment by raminhti25** [comment]
it would work if you call method '$this->configureRateLimiting();' in boot method.

**Comment by fgilio** [comment]
All of this has roots in this commit https://github.com/laravel/laravel/commit/ced3e50bca279f5a499a6d513fcdfd2a020c28ce
Since that moment, the `configureRateLimiting()` method must be called when booting the provider instead of in the deprecated `map()` method.

By making those changes everything works perfectly fine and as expected.

---

👋  Hola @julianpoma, lo solucionamos! 🎉 Saludo de Nacho y mío
