### ISSUE TITLE
Checking email field on 'Form request' validation

### ISSUE THREAD

**Issue by zeravcic** [laravel/framework#35826]
### Environment:
- Win10 / VirtualBox v6.1.16 / laravel/homestead v9.5.1
- Laravel Version: 8.20.1
- PHP Version: 7.4.5
- Database Driver & Version: 5.7.29-0ubuntu0.18.04.1

### Description:
It seems that there is bug with checking `email` on '[form request](https://laravel.com/docs/8.x/validation#creating-form-requests)'...or even something more serious? :confused:

```php
namespace Some\Namespace\app\Http\Requests\Auth;

use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;
// use Illuminate\Auth\Events\Registered;
// use Illuminate\Support\Facades\Hash;

class UserRegistrationRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'name' => 'required|string|min:3|max:100',
            'email' => 'required|string|email|max:100|unique:users', //   <=== *  here...
            // 'email' => 'regex:/^.+@.+$/i',                        //   <=== ** here too
            'password' => 'required|string|min:8|max:100|confirmed',
        ];
    }

    // public function createUser(): User { ... }
}
```

\* https://laravel.com/docs/8.x/validation#rule-email
\*\* https://laravel.com/docs/8.x/validation#rule-regex

### Steps To Reproduce:

Valid and invalid POST request and response statuses:
- [x] `some.address@example.com` ===> expected status: _PASSES_;  actual status: _PASSES_
- [ ] `some.address@example` ===>  expected status: _422 EXCEPTION THROWN_;  actual status: _PASSES, user created_

I really hope I'm just wrong somewhere...somehow...
Please, can anyone confirm or refute my suspicions?

**Comment by rodrigopedra** [comment]
Laravel changed the email validation in 5.8 release

https://laravel.com/docs/5.8/upgrade (search for "Email Validation")

https://laravel.com/docs/5.8/validation#rule-email

The default validation since then follows RFC 6530, to which the `some.address@example` is considered a valid email.

If you want to keep the behavior from before Laravel 5.8 you can specify which validation mechanism to use on the `email` validation rule:

~~~php
'email' => 'required|string|email:filter|max:100|unique:users',
~~~
