### ISSUE TITLE
Laravel <= v8.4.2 debug mode: Remote code execution

### ISSUE THREAD

**Issue by xzd** [laravel/framework#35880]
https://www.ambionics.io/blog/laravel-debug-rce

**Comment by driesvints** [comment]
Don't enable debug mode in production. Also: please don't post issues about security vulnerabilities (see our readme).

https://laravel.com/docs/8.x/configuration#debug-mode

<img width="746" alt="Screenshot 2021-01-14 at 11 59 49" src="https://user-images.githubusercontent.com/594614/104582330-083d0d00-5660-11eb-96fe-24d1e9830aa2.png">

**Comment by lucaspanik** [comment]
@driesvints 

I am having the same problem in my homologation and staging environment.

After upgrading from Laravel 7 to Laravel 8.27.0, these errors started to appear in my staging environment, but they don't appear in my production environment.

After analyzing the differences between environments, I thought it could be something related to `APP_DEBUG=true` in my staging environment, and `APP_DEBUG=false` in my production environment.

And I found this links:
- [PSA: Laravel <= 8.4.2 has vulnerability (CVE-2021-3129)](https://www.reddit.com/r/laravel/comments/lh6r5h/psa_laravel_842_has_vulnerability_cve20213129/)
- [Laravel <= v8.4.2 debug mode: Remote code execution (CVE-2021-3129)](https://www.ambionics.io/blog/laravel-debug-rce)


When executing the command `ps aux | grep kde` on my staging server, I identified the process `kdevtmpfs` running, as you can see in the image below.
![image](https://user-images.githubusercontent.com/7035554/113092518-840d1700-91c4-11eb-8344-207bc09cc931.png)

The problem as described in the first link is referencing the "facade/ignition" package that deals with the new Laravel error page  and that the problem can be seen at https://github.com/facade/ignition/pull/334.

In summary, I think the case is happening for applications that have been upgraded from Laravel less than 8 to 8.x, because they suffered this "invasion" before the update.

Even knowing that debugging should not be enabled in the production environment, how to work with debugging in the staging environment? What do you recommend to me?

My question is what to actually do to deal with this vulnerability since I am already in version 8.27.0 of Laravel. 
Remove the ["facade/ignition"](https://github.com/facade/ignition) package? 
Do I update the ["facade/ignition"](https://github.com/facade/ignition) package (I am currently in the `"facade/ignition": "^2.3.6")` ?

Thank you for your attention, I hope I have helped, I am waiting for help to make the right decision.

**Comment by tudorradubarbu** [comment]
Absolutely nobody from Laravel offers support on this one. It's just blank.
