### ISSUE TITLE
 -1 0 1 Bus::batch()->finally() callbacks not called after an exception is caught

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#36076]
- Laravel Version: 8.25.0
- PHP Version: 7.4.10
- Database Driver & Version: n/a

### Description:
The finally callback on bus::batch(...)->catch(...)->finally(...) not get called when a job throws an exception?
The catch(...) callbacks are, but not the finally ones - which should be called both when exceptions are caught and when all jobs run successfully... shouldn't it?

is this a bug, or do I just not understand something?

### Steps To Reproduce:

```php
Bus::batch([
    new JobThatThrowsAnException
]->catch(function() {
    dump('This runs');
})->finally(function () {
    dump('this does not run, but it should');
}););
```

**Comment by driesvints** [comment]
```php
        Bus::batch([
            new JobThatThrowsAnException
        ])->catch(function() {
            dump('This runs');
        })->finally(function () {
            dd('this does not run, but it should');
        })->dispatch();
```

Works for me

**Comment by NilsEvers** [comment]
@driesvints The only reason your test works is because you only have one job.
If you add another job **after** the one that throws an exception, finally won't get called.

```php
Bus::batch([
    new JobThatThrowsAnException,
    new Job,
])->catch(function() {
    dump('This runs');
})->finally(function () {
    dd('this does not run, but it should');
})->dispatch();
```

If you look at the [implementation](https://github.com/laravel/framework/blob/3d687d93b4fe4232ecfd13efae29aa540c5b17c7/src/Illuminate/Bus/Batch.php#L339) you will see that the finally callbacks will only run if all jobs have ran:

```php
if ($counts->allJobsHaveRanExactlyOnce() && $this->hasFinallyCallbacks()) {
    $batch = $this->fresh();

    collect($this->options['finally'])->each(function ($handler) use ($batch, $e) {
        $this->invokeHandlerCallback($handler, $batch, $e);
    });
}
```

At the current state `finally` is useless and does not behave like a regular `finally` everyone is used to.

**Comment by driesvints** [comment]
@NilsEvers atm that's the way things work but I agree it's a bit confusing. I'll bring it up internally.

**Comment by NilsEvers** [comment]
@driesvints I think it is not only confusing, it is more or less useless right now. 
I can hardly think of a use case for the current implementation. 
And you could always reproduce the current behaviour with a regular `finally`.

The only workaround I see right now is putting the same code in `then` and `catch` but that makes `finally` kind of obsolete 😄 

Thanks for bringing it up.

**Comment by driesvints** [comment]
@NilsEvers it seems this is discussed in the docs and you should call `->allowFailures()` explicitly if you want the behavior you're after: https://laravel.com/docs/8.x/queues#allowing-failures

**Comment by NilsEvers** [comment]
@driesvints not quite. If I set `allowFailures` the other jobs in the batch will also be processed.

**Comment by driesvints** [comment]
I don't think we're going to take any action ourselves here atm, sorry. Feel free to propose something through a PR if you like 👍

**Comment by bernardwiesner** [comment]
above should actually not be an issue. `finally` **does** get called even if there is a failed job due to an exception even when allowFailures is not used.

The reason probably its failing in tests is if you use a sync driver the first exception causes the other jobs to stop being processed. If a redis driver is used, other jobs will keep being processed and it should reach the finally.

TBH bus batch is not very usable with the sync driver, as it stops execution and rollbacks DB transactions if any job fails.
