### ISSUE TITLE
Mass update Model::find(id)->update([...]) does not work, only if has where()

### ISSUE THREAD

**Issue by terremoth** [laravel/framework#36406]
- Laravel Version: 6.20.7
- PHP Version: 7.3.5
- Database Driver & Version: MySQL 8.0.17

### Description:
Hello friends.

Something like

```php
User::find(2)->update(['level' => 2]);
// returns true (??????)
```
does not work (does'nt change the `level` column value), only if has where(), like:

```php
User::where('id', 2)->update(['level' => 2]);
// returns 1
```

### Steps To Reproduce:
I made on artisan to exemplify

Obs: if this is intended to happen that way, can we made this method ->update() works for ->find() too? 

Thanks o/

**Comment by luanfreitasdev** [comment]
Hello,

I think it is not possible because:

When we call the 'first' method, under the hood it calls first() as an array;

It would have to be something like:

Usually when we use find:

`User::find(1);`

After implementation, it would look like this:
`User::find(1)->first();`

that is, the first of the so-called `Illuminate\Database\Eloquent\ Builder.php` would have to be removed and then implemented:

``
public function find ($ id, $ columns = ['*'])
    {
        if (is_array ($ id) || $ id instanceof Arrayable) {
            return $ this-> findMany ($ id, $ columns);
        }

        return $ this-> whereKey ($ id) -> first ($ columns);
    }
``

But a `firstUpdate` method would fit in the next versions.
Correct me if I said nonsense!

Then your code would look like this, assing the first parameter the id, and the second the fields:

User::findUpdate(2, ['level' => 3]);

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by terremoth** [comment]
Hey @driesvints o/

Well, this seems to be a bug for me, at least.
Do you want me to make a post on these channels to ask more people to see if they have the same?

**Comment by driesvints** [comment]
Yes, please try a support channel first. Thanks

**Comment by rs-sliske** [comment]
the difference is find returns an instance of Model, while where returns an Eloquent\Builder

**Comment by terremoth** [comment]
Yeah, I know that.
I am suggesting that update() can work with Model instance too, and that should not return true if not updates.
