### ISSUE TITLE
eloquent event deleting and deleted fired with softdelete but can't change model

### ISSUE THREAD

**Issue by TassoPeperone** [laravel/framework#36450]
- Laravel Version: 8.30.0
- PHP Version: 7.3.19
- Database Driver & Version:

### Description:
Eloquent model with softdelete. When you delete the model the events "deleting" and "deleted" are fired, but if you try to change some data inside the model you can't. But if you do a normal delete had sense, but with softdelete make sense to change also data inside the model

### Steps To Reproduce:

inside a model with softdelete..

protected $guarded = [''];

protected static function booted()
    {
        static::deleting(function ($model) {
            $model->field_inside_model = 1;            
        });
    }

**Comment by taylorotwell** [comment]
Yeah - I think to change this would possibly break people's applications that are depending on this behavior at the moment. I know you want it to work this way because a soft delete is more like an "update" than a real delete but we in the framework still treat it as a "delete" operation in which no other columns are updated. If you need to update another column you'll need to either do that separately or executed your own update statement that updates both columns at once and sets the `deleted_at` column to the current timestamp.
