### ISSUE TITLE
is_required validation rule is broken with boolean values (regression)

### ISSUE THREAD

**Issue by dvlpp** [laravel/framework#36540]
- Laravel Version: 8.32.0
- PHP Version: 7.4.0
- Database Driver & Version: irrelevant

### Description:

It seems that [this PR](https://github.com/laravel/framework/pull/36504) broke `required_if` validation rule with boolean values. Here's a validation rule which worked until 8.31:

```php
[
   "is_organization" => ["required", "boolean"],
   "personal_occupation" => ["required_if:is_organization,0"]
]
```

But since 8.32.0 this will pass without ValidationException with `is_organization` send to false and `personal_occupation` to null (or empty).

**Comment by jessarcher** [comment]
Hi Philippe,

First off, I'm sorry that my PR has caused this bug for you.

The underlying issue is when and how `'0'` and `'1'` should be interpreted as a boolean vs. an integer. For example, in the following scenario you would expect `foo` *not* to be required, because the validation rule is clearly specifying numeric values rather than booleans.

```php
Validator::validate(
    ['age' => false],
    ['foo' => 'required_if,age,0,1,2']
);
```

Prior to my bugfix (which addressed a different scenario) `foo` would have been mistakenly required because of the loose comparison.

I can't think of any way to make both of our examples work as we each expect. However, because your example was previously working, I feel my bugfix should probably be reverted for 6.x and 8.x.

There is probably a bigger discussion to be had about how this should work in future versions though, because ultimately I feel the stricter validation is preferable, even if it means you may need to specify `required_if:is_organization,false,0`

**Comment by taylorotwell** [comment]
@dvlpp why do you have `required_if:is_organization,0` and not `required_if:is_organization,false` if `is_organization` is a boolean field?

**Comment by dvlpp** [comment]
@jessarcher you're right, the solution is `required_if:is_organization,0,false` which works in all cases (I didn't thought I could set multiple values here).
I close this since my syntax was incorrect.

**Comment by timacdonald** [comment]
Although I agree with the easy suggest fix, just wanna bring to light that the validator, as per the docs, considers `[true, false, 1, 0, "1", and "0"]` as a boolean - or at least validates them as a boolean.

I think perhaps something in the docs around this might be useful.

```
boolean

The field under validation must be able to be cast as a boolean. Accepted input are true, false, 1, 0, "1", and "0".
```

**Comment by taylorotwell** [comment]
@timacdonald yeah I did consider that actually and that made me think a bit about this. My thinking was "required_if" is not really boolean related - to me it seems like it should be a fairly literal check.

**Comment by SjorsO** [comment]
Just wanted to report that this same issue caused problems in my applications.

The validation rule below worked fine before v8.31, but broke unexpectedly after a `composer update`. 
```php
'subject' => 'exclude_unless:with_action,1|required|string|max:255',
```

**Comment by driesvints** [comment]
Yeah this ship has sailed I'm afraid.

**Comment by SjorsO** [comment]
> Yeah this ship has sailed I'm afraid.

Too bad, I probably won't be the last one to get bitten by this breaking change
