### ISSUE TITLE
SerializesAndRestoresModelIdentifiers->restoreCollection() should load relations when use a queue 

### ISSUE THREAD

**Issue by z-golly** [laravel/framework#36824]
- Laravel Version: 8.0.0
- PHP Version: 7.4.0
- Database Driver & Version:  MySQL&8.0

### Description:
job accepts as collection when use a queue, it miss relations after unserialize.
```php
    protected function restoreCollection($value)
    {
        if (! $value->class || count($value->id) === 0) {
            return new EloquentCollection;
        }

        $collection = $this->getQueryForModelRestoration(
            (new $value->class)->setConnection($value->connection), $value->id
        )->useWritePdo()->get();     // *************->load($value->relations ?? [])

        if (is_a($value->class, Pivot::class, true) ||
            in_array(AsPivot::class, class_uses($value->class))) {
            return $collection;
        }

        $collection = $collection->keyBy->getKey();

        $collectionClass = get_class($collection);

        return new $collectionClass(
            collect($value->id)->map(function ($id) use ($collection) {
                return $collection[$id] ?? null;
            })->filter()
        );
    }
```

### Steps To Reproduce:

```php
namespace Golly\Elastic\Jobs;


use Golly\Elastic\ElasticEngine;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

/**
 * Class MakeSearchable
 * @package Golly\Elastic\Jobs
 */
class MakeSearchable implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * The models to be made searchable.
     *
     * @var Collection
     */
    public $models;

    /**
     * Create a new job instance.
     *
     * @param Collection $models
     * @return void
     */
    public function __construct(Collection $models)
    {
        $this->models = $models;
    }

    /**
     * @param ElasticEngine $engine
     * @return void
     */
    public function handle(ElasticEngine $engine)
    {
        $engine->update($this->models);
    }
}
```
relations can not load

**Comment by driesvints** [comment]
No, this is by design to not overload queued jobs on large relationship collections.

**Comment by skaesdorf** [comment]
Since the relations are serialized anyways, I don't understand why we should not load them when unserializing the collection. 
Additionally there was a merge "[10.x] Add WithoutRelations attribute for model serialization #47989" that allows to exclude relations when serializing.
Therefore it doesn't make sense to me to not load relations when unserializing.

**Comment by skaesdorf** [comment]
Hi @driesvints 

Since the relations are serialized anyways, I don't understand why we should not load them when unserializing the collection.
Additionally there was a merge "[10.x] Add WithoutRelations attribute for model serialization https://github.com/laravel/framework/pull/47989" that allows to exclude relations when serializing.
Therefore it doesn't make sense to me to not load relations when unserializing.

**Comment by driesvints** [comment]
@skaesdorf isn't that just to not serialise the model identifiers?

**Comment by skaesdorf** [comment]
@driesvints 
When a `QueueableEntity` aka `Model` or a `QueueableCollection` aka a `EloquentCollection` is serialized using the `SerializesModels` trait, all loaded (queueable-)relations are serialized as an array of relation names. The mentioned PR #47989 just makes this relation serialization optional.

When unserializing a `Model` the serialized relations are loaded after querying the `Model` in `framework/src/Illuminate/Queue
/SerializesAndRestoresModelIdentifiers.php`:
```php
    public function restoreModel($value)
    {
        return $this->getQueryForModelRestoration(
            (new $value->class)->setConnection($value->connection), $value->id
        )->useWritePdo()->firstOrFail()->load($value->relations ?? []);
    }
```

For a serialized `QueueableCollection` on the other hand, the relations that are serialized are not loaded after unserializing the collection's Models. See: https://github.com/Neol3108/framework/blob/c4271001aa15a34af41b8205674ce62cd6c7aaaf/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php#L66

This behaviour makes no sense to me, since the names of the relations are serialized and used when unserializing a model but not when unserializing a collection.

Cheers

**Comment by driesvints** [comment]
Thanks for the detailed explanation @skaesdorf. But as said before this is by design to not make queueable jobs explode when loading a collection of models with their relations.

**Comment by skaesdorf** [comment]
@driesvints 
Thanks, yeah I got that case. But since there is an option added by #47989 to choose not to serialize relations, why not allow the users to choose for collections as well as for models? If the default would be to not serialize relations for a collection, the current behaviour would be untouched.

As a workaround i extended the `SerializesModels` trait but it would be a cool core feature imo.

**Comment by driesvints** [comment]
I just don't think we're going to add that as we don't want to encourage this.
