### ISSUE TITLE
Clear queue doesn't remove unique job locks

### ISSUE THREAD

**Issue by joostdebruijn** [laravel/framework#36927]
- Laravel Version: 8.36.2
- PHP Version: 8.0.3
- Database Driver & Version: MariaDB 10.5.9 en Redis 6.2.1 as cache/queue driver

### Description:
When the queue is cleared, lock keys will not be cleared. This will prevent new jobs with the same unique key to run later.

### Steps To Reproduce:
1. Define a unique queueable job (`ShouldQueue`, `ShouldBeUnique`).
2. Dispatch the job (but don't run artisan queue:work at that moment).
3. Run `artisan:clear`.
4. Look in redis, the lock keys (`laravel_unique_job`) still exists. Any new job with the same unique id will not run until the lock keys are cleared.

**Comment by paras-malhotra** [comment]
It isn't really recommended to clear queues in production. If you want to do this, this would have to be done in userland because once the jobs are dispatched, there is no track of which locks exist and when they expire.

If you want to do this in production, a good way might be to implement unique jobs using taggable cache drivers and when you clear the queue, just delete the tagged cache keys.

**Comment by joostdebruijn** [comment]
I didn't do this in production. I just noticed it in my development environment and it was unclear to me why this happened in this way. The documentation didn't mention this behavior. Although your explanation is understandable for a production environment, it took some unnecessary time for me during development to troubleshoot why the jobs did not run.

**Comment by gokigoks** [comment]
hi, @joostdebruijn how did you clear the lock?

**Comment by joostdebruijn** [comment]
@gokigoks Clearing your cache will release the locks.

**Comment by gokigoks** [comment]
Thank you.. @joostdebruijn by chance, is there a specific key I could clear to avoid affecting other cached data?

**Comment by devplaylogiq** [comment]
I use file cache on my system. It's deployed on AWS, with load balancer and multiple instances turned on/off on-demand.
Cache is working fine (in a shared EFS disk between all instances), but idk why my unique jobs were not being dispatched.
So, i defined the uniqueVia method on my BaseJob (where all my jobs extend), and now the unique existence of a job seems to work properly.

BUT (there is always a BUT), i find a job scheduled every day at 00:30 is not being queued as expected.
If i dispatch the job "by hand" from tinker, it is queued and processed OK, but i don't see the lock of this job in cache_locks table.
It doesn't happend on my local environment (i mean, when a unique job is queued, there is always one row with this key at the cache_locks table).
I tried clear cache manually on AWS, but it doesn't fix anything.

How can i check if there is a lock when cache driver is "file" ?

**Comment by curruwilla** [comment]
> It isn't really recommended to clear queues in production. If you want to do this, this would have to be done in userland because once the jobs are dispatched, there is no track of which locks exist, which queues they belong to and when they expire.
> 
> If you want to do this in production, a good way might be to implement unique jobs using taggable cache drivers (tag the job lock cache keys) and when you clear the queue, just delete the tagged cache keys.

How would you mark the jobs to separate the unique job in redis?
Today I use it like this, but they are all marked together

```php
public function uniqueVia()
    {
        return Cache::driver('redis');
    }
```

**Comment by resslinger** [comment]
The issue exist furthermore. To clear the cache had not an effect. We use redis as cache driver and database as queue driver. Only deleting the key "laravel_unique_job" from redis cache solved the issue.

**Comment by alecpl** [comment]
Same issue here. `queue:clear` should release the locks. It is a bug that it does not. Also `cache:clear` does not work for redis locks database.

**Comment by jul3z** [comment]
I don't now why this issue is closed, we searched for this bug 1 day.

Workaround:
In `config/cache.php` 
Create a new store stores.redis_clear_lock.
`stores.redis_clear_lock.connection` should be the same as `stores.redis.lock_connection`
```
[
'stores' => [
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
            'lock_connection' => 'default',
        ],
        'redis_clear_lock' => [
            'driver' => 'redis',
            'connection' => 'default',
            'lock_connection' => 'default',
        ],
]
]
```

After that you can run following command and it deletes all queue locks: 
`artisan cache:clear redis_clear_lock`


Super Annoying after clearing the queue and you cannot add new jobs.

**Comment by brisp-jelle** [comment]
Same issue

**Comment by tom-it** [comment]
> I don't now why this issue is closed, we searched for this bug 1 day.
> 
> Workaround: In `config/cache.php` Create a new store stores.redis_clear_lock. `stores.redis_clear_lock.connection` should be the same as `stores.redis.lock_connection`
> 
> ```
> [
> 'stores' => [
>         'redis' => [
>             'driver' => 'redis',
>             'connection' => 'cache',
>             'lock_connection' => 'default',
>         ],
>         'redis_clear_lock' => [
>             'driver' => 'redis',
>             'connection' => 'default',
>             'lock_connection' => 'default',
>         ],
> ]
> ]
> ```
> 
> After that you can run following command and it deletes all queue locks: `artisan cache:clear redis_clear_lock`
> 
> Super Annoying after clearing the queue and you cannot add new jobs.

would it not just work with artisan cache:clear redis ? whats the upside on having the redis_clear_lock connection in there? 

we are facing the same issue where on production sometimes jobs fail to dispatch again because the lock is not removed at all :(

**Comment by zackAJ** [comment]
any updates on this ?

**Comment by pawel-omniaz** [comment]
While this issue is closed, is there any proper solution for this instead of that workaround with new connection?

**Comment by astorozhevsky** [comment]
We encountered the same problem. The command php artisan queue:clear redis --queue={queueName} should ideally release the locks as well. Alternatively, the documentation (https://laravel.com/docs/11.x/queues#clearing-jobs-from-queues) should clearly state that clearing the queue does not release locks and that the Redis cache must be manually cleared to address this issue.

**Comment by Bencute** [comment]
I am posting my developments on this issue for those who stumble upon it (Config: **Laravel 12** and **Redis** cache). I took the information from the current thread and https://github.com/laravel/framework/issues/29298.
First, the reason why the problem does not arise in turn. It is related to `MustBeUnique`, and the fact that the lock is not removed for some reason, for example - the task is killed before it is completed.
It is assumed that there is no such behavior on production and the task is always either successful or not, as a result of which the lock is then removed.
But it is assumed that you still got into the current situation, such as how to choose from it:
1) It is necessary to delete all Redis databases, because here storing the locks, execute Tinker `Cache::connection()->command('flushall');`
It is necessary to take into account that all data in Redis and the cache are deleted, if it is configured for Redis.
1) It is possible to more precisely clean up the database in Redis that is used for locks. We execute `Cache::lockConnection()->command('flushdb');` in the tinker;

Let me explain for you:
The following is in the Redis cache config:
```
'Redis' => [
  'Driver' => 'Redis',
  'Connection' => env('REDIS_CACHE_CONNECTION', 'cache'),
  'lock_connection' => env('REDIS_CACHE_LOCK_CONNECTION', 'default'),
],
```
The `default` database is used for locks, unlike the cache database.
DB config:
```
'default' => [
  'url' => env('REDIS_URL'),
  'host' => env('REDIS_HOST', '127.0.0.1'),
  'username' => env('REDIS_USERNAME'),
  'password' => env('REDIS_PASSWORD'),
  'port' => env('REDIS_PORT', '6379'),
  'database' => env('REDIS_DB', '0'),
],
'cache' => [
  'url' => env('REDIS_URL'),
  'host' => env('REDIS_HOST', '127.0.0.1'),
  'username' => env('REDIS_USERNAME'),
  'password' => env('REDIS_PASSWORD'),
  'port' => env('REDIS_PORT', '6379'),
  'database' => env('REDIS_CACHE_DB', '1'),
],
```

We see that the difference is in `env('REDIS_DB', '0')` and `env('REDIS_DB', '1')`, different databases are used, so `Cache::flush();` does not work, because it clears the `command('flushdb')` for the **cache** database, but not for **default**.

One of the solutions can still be used in the Job `public $uniqueFor = 3600;` which indicates the lifetime of the lock.

**Comment by FaisalBudiono** [comment]
Anyone know how to reproduce this issue? I got this issue on my dev server. I'm trying to test it on my local

**Comment by Bencute** [comment]
> Anyone know how to reproduce this issue? I got this issue on my dev server. I'm trying to test it on my local

1) Make job `MustBeUnique`
2) Use redis for cache
3) Hard terminate job, I think `exit `or `die `might help, or Ctrl+C while job executing
Done.

**Comment by RyanPaiva56** [comment]
I'm also able to reproduce this. Basically I had a bunch of jobs fail and now they silently wont re-queue. When I remove `ShouldBeUnique`, they start working again. I tried clearing the cache and that didn't work. Running `Cache::lockConnection()->command('flushdb');` fixed the issue.

**Comment by RyanPaiva56** [comment]
Posted here in the horizon repo: https://github.com/laravel/horizon/issues/1678

**Comment by PEscar** [comment]
i solved this setting up the TTL of the unique job cache key

On my jobs, setting up something like this

public $uniqueFor = 60 * 20; // 20 minutes

(i calc this based on the execution periodicity of each job)
