### ISSUE TITLE
Possible bug in serialize call from HasAttributes::addCastAttributesToArray

### ISSUE THREAD

**Issue by bluemmb** [laravel/framework#36950]
- Laravel Version: 8.32

### Description:

In the `if` statement below which is in file [Illuminate/Database/Eloquent/Concerns/HasAttributes](https://github.com/laravel/framework/blob/ef99cffd4938759cecfe2cb19888e9ff3e942b87/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L256).

```php
protected function addCastAttributesToArray(array $attributes, array $mutatedAttributes)
{
    foreach ($this->getCasts() as $key => $value) {
        
        // ...

        if ($attributes[$key] && $this->isClassSerializable($key)) {
            $attributes[$key] = $this->serializeClassCastableAttribute($key, $attributes[$key]);
        }

        // ...       
    }

    return $attributes;
}
```

It seems that the condition checks for the existence of `serialize` method in resulted class from casting (Castable), 

But inside if, it tries to run the `serialize` method from caster class itself which comes from Castable::castUsing() result.

### Steps To Reproduce:

- Create class A which implements Castable class
- Create caster class B which implements CastsAttributes
- Return an instance of B from A::castUsing method

- Make sure A has `serialize` method
- Make sure B doesn't have `serialize` method

- Define a field inside a Model to be casted to A
- Calling Model::toArray() will give you an exception saying that B doesn't have `serialize` method

### Where did you encounter this?

This might help for testing. I was using [spatie/laravel-model-states](https://github.com/spatie/laravel-model-states) which it's caster class already does not have `serialize` method. Putting that method inside a State inherited class will cause this exception.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new laravel-issue-36950 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by taylorotwell** [comment]
If you believe there is a bug please write a simple test case and fix and send a PR.
