### ISSUE TITLE
HTTP Client Multipart with multidimensional array inputs

### ISSUE THREAD

**Issue by omzy** [laravel/framework#37174]
- Laravel Version: 8.37.0
- PHP Version: 7.3.13
- Database Driver & Version: MySQL 5.7.32

### Description:

The fix applied in https://github.com/laravel/framework/issues/32058 does not work for multidimensional array inputs.

### Steps To Reproduce:

HTML:

```
<form method="post" action="" enctype="multipart/form-data">
    <input type="text" name="data[Product][user_id]">
    <input type="text" name="data[Product][supplier_id]">
    <input type="file" name="file">
</form>
```

PHP:
```
public function index(Request $request)
{
    $url = 'my-url';
    $post_data = $request->post();

    // Example of how $post_data will look
    $post_data = [
        'data[Product][user_id]' => 123,
        'data[Product][supplier_id]' => 456,
    ];

    $contents = fopen($request->file('file'), 'r');

    return Http::attach('file', $contents)
        ->post($url, $post_data);
}
```

This produces an error: `A 'contents' key is required`.

A `print_r()` of `$laravelData` (line 714 `src/Illuminate/Http/Client/PendingRequest.php`) outputs the following:

```
Array
(
    [0] => Array
        (
            [Product] => Array
                (
                    [user_id] => 123
                    [supplier_id] => 456
                )
        )

    [1] => Array
        (
            [name] => file
            [contents] => Resource id #439
        )
)
```

As you can see, it does not format the input variables into `name` and `contents` pairs, like it has done with the file input.

**Comment by omzy** [comment]
In the meantime, I have used the code in this answer here to reformat the POST array: https://stackoverflow.com/a/53731825/372630

It would be great if we could integrate something like this in to the library, as the error isn't helpful and it took me a while to figure out the problem.

**Comment by omzy** [comment]
Any potential solution would need to take in to account:

- POST array containing a mixture of standard inputs and multidimensional array inputs
- POST array containing a numerically indexed array, e.g: 

```
<input type="text" name="data[categories][]" value="1">
<input type="text" name="data[categories][]" value="2">
```

**Comment by taylorotwell** [comment]
Are you able to submit a PR?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by nickfls** [comment]
This is definitely happening:

```php
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\File;

$path = storage_path('file.txt');

Http::acceptJson()
    ->attach('attachments[]', File::get($path), File::basename($path))
    ->post($destination, [
        'name' => 'John Smith',
        'providers' => [1,2,3]
]);
```
with throw `InvalidArgumentException with message 'A 'contents' key is required'`
where as will be just fine

```php
Http::acceptJson()
    ->attach('attachments[]', File::get($path), File::basename($path))
    ->post($destination, [
        'name' => 'John Smith',
        'providers' => '1'
]);
```

**Comment by renwarkurd** [comment]
Same issue here.

**Comment by mikecummings10** [comment]
This is still an issue. Please re-open.

**Comment by codoffer** [comment]
@mikecummings10 @renwarkurd @nickfls Have you found any fix for this issue?

**Comment by Astriel** [comment]
Still bugging for me on Laravel 10.

**Comment by spider4216** [comment]
the same in Laravel 10

**Comment by bernardwiesner** [comment]
still happening, no one seems to care about fixing this one...

**Comment by RomainMazB** [comment]
> still happening, no one seems to care about fixing this one...

I made a PR to fix it but it sounds like it won't be merged.

After more investigations on what happens and what would be the proper/simple way to tackle this. Here is my final thoughts.

### Why
When using Laravel client to upload a file or with the `asMultipart` method, Laravel internally uses the [Guzzle `multipart` option](https://docs.guzzlephp.org/en/stable/request-options.html#multipart), which states:
> The value of multipart is an array of associative arrays, each containing the following key value pairs:
> - name: (string, required) the form field name
> - contents: (StreamInterface/resource/string, required) The data to use in the form element.
> - headers: (array) Optional associative array of custom headers to use with the form element.
> - filename: (string) Optional string to send as the filename in the part.

As you can see, the `contents` parameter can't handle an array. And Laravel won't convert your fields to a Guzzle well-formatted format. If you pass a value as an array into Laravel, the value is passed "as is" [due to this modification](https://github.com/laravel/framework/commit/c72697db4666070540e904da5d59bbed00ba8b60)

### How
Now this is known, you understand that it's up to us to prepare the nested array to the Guzzle format.
Happily, [Symfony's FormDataPart class](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Mime/Part/Multipart/FormDataPart.php) can do most of the job for us
```php
// The data with nested array
$data = [
  'products' => [
    [
      'id' => '123',
      'quantity' => '1',
    ],
    [
      'id' => '321',
      'name' => '2',
    ]
  ]
];

// Use the FormDataPart from Symfony to flatten our nested array values into a one level array
$formParts = (new \Symfony\Component\Mime\Part\Multipart\FormDataPart($data))->getParts();

// Convert each part to the name/contents Guzzle format
$guzzleData = array_map(fn ($field) => [
    'name' => $field->getName(),
    'contents' => $field->bodyToString()
], $formParts);

$request = Http::asMultipart()->post($url, $guzzleData);
```

### Requirements
There is only one requirement that I faced: Symfony's class only accepts a string as value.
All the values in your nested array should be strings, boolean should be converted to `"true"`, integer `1` should be converted to a string value `"1"` and so on...
