### ISSUE TITLE
🚨 Potential Command Injection - Generic (CWE-77)

### ISSUE THREAD

**Issue by huntr-helper** [laravel/framework#37197]
👋 Hello, @taylorotwell, @GrahamCampbell, @themsaid - a potential high severity Command Injection - Generic (CWE-77) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-laravel/framework** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

✏️ **NOTE**: If we don't hear from you in *14 days*, we will proactively source a fix for this vulnerability (and open a PR) to ensure community safety.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by themsaid** [comment]
Please follow the instructions in the Security Policy for reporting a vulnerability: https://github.com/laravel/framework/security/policy

**Comment by adam-nygate** [comment]
> Please follow the instructions in the Security Policy for reporting a vulnerability: https://github.com/laravel/framework/security/policy

Hey @themsaid, the report is hosted on the https://huntr.dev bug bounty platform. We'd request that your security contact registers with our platform so that they may review and validate the report, and take action, if necessary.

To ensure the security of the community, if we don't hear from you, we may open the report to the public so that PRs can be prepared as a worst-case scenario.
