### ISSUE TITLE
Caching routes when using closures and using the missing model behaviour

### ISSUE THREAD

**Issue by timrspratt** [laravel/framework#37285]
- Laravel Version: 8.39.0
- PHP Version: 8.0.5

I have the following route definition:

```php
$route->get('/{model}', fn (Model $model) => view('something', compact('model'))->middleware(...)->name('name')->missing(fn () => redirect()->route('home'));
```

When the model is missing and the routes are not cached, all works ok, and the browser is redirected to the home route (/). However, when `php artisan route:cache` is ran, it results in the following error:

```
Illuminate\Routing\RouteFileRegistrar::{closure}(): Argument #1 ($model) must be of type App\Models\Model, Illuminate\Http\Request given
```

It appears to only happen when using the `->missing()` behaviour.

**Comment by taylorotwell** [comment]
I am unable to recreate this using the following route:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/463230/117321532-d2ac7180-ae52-11eb-8603-0589f2d11b46.png">

**Comment by timrspratt** [comment]
I've had a play and it looks like if the route closure is using arrow functions that it results in the error. If you update your example to does it break? I'm happy to re-write mine (or move them into controllers) but might be something to look into (if you're able to reproduce).

```php
Route::get('/users/{user}', fn (User $user) => $user)->missing(fn () => redirect('https://laravel.com'));
```

Thanks

**Comment by rodrigopedra** [comment]
Hey @timrspratt 

There was a similar issue not long ago and I was playing around to try finding the error then. Can't remember now which issue number it was.

From my assessment back then - and I tried again with your code sample - the issue seems to be the way closures are serialized. Their serialized form keeps a reference to the line numbers of their start and end lines and source file.

On your example both closures (arrow functions) start and end on the same line, therefore it seems when unserializing the closure passed to the `->missing()`  method, Laravel actually tries to execute the one passed as the route resolver as both closures start and end at the same line.

My guess is that this is a limitation on the underlying library used for closure serialization. If you try breaking lines like this:

~~~php
Route::get('/users/{user}', fn (User $user) => $user)
    ->missing(fn () => redirect('https://laravel.com'));
~~~

Both cases works (existing user, and user not found).

As an evidence of this behavior you can try this using regular closures:

~~~php
Route::get('/users/{user}', function (User $user) { return $user; })->missing(function () { return redirect('https://laravel.com'); });
~~~

Which is valid PHP, albeit not very common code-style, you will see this:

- Existing user: **works**
- User not found: **error**

Which seems to be the same behavior you opened this issue for.

Again, I think this is a limitation on how closure serialization works. 

One solution would be adding a note into the docs to warn about this limitation (if the limitation is confirmed, I don't know a lot about the library used for serialization). 

Another solution would be erroring when two cached closures have overlapping start and end lines, so the developer is aware. 

If this is actually a limitation, my shot would be adding a warning to the docs, as this is easy to solve and maintaining the code to detect conflicts for this could add a lot of complexity.

Hope this helps.

**Comment by timrspratt** [comment]
@rodrigopedra thanks, this makes total sense thinking about it! I can confirm that putting them on new lines works as expected.

I was trying to be clean with my route definitions on one line, but with this in mind I'll reconsider and go about it the conventional approach (I never normally bother caching routes anyway, there aren't that many 🙈).

Thanks for the assistance with this, apologies @taylorotwell for taking your time.
