### ISSUE TITLE
Model toArray() with "date" or "datetime" casts serializes dates using timezone, whereas date casts with custom format don't

### ISSUE THREAD

**Issue by Nyratas** [laravel/framework#37465]
- Laravel Version: 8.42.1
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 8.0.18

### Description:

When setting a timezone (for instance: `APP_TIMEZONE="Europe/Brussels"` in `.env`), all `$model->toArray()` calls will transform `date` and `datetime` casted attributes using the app's timezone, unless the cast uses a custom datetime format such as `datetime:Y-m-d H:i:s`. This inconsistent behavior comes from the [`HasAttributes::serializeDate()`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1093) method, which is called for the default `date` and `datetime` casts, but not for custom datetime casts (see lines [`243`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L243) and [`248`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L248)).

IMO dates should never be automatically transformed using the `.env`'s `APP_TIMEZONE` for the following reasons :
- Dates might already be stored correctly using the app's timezone, in which case they don't need to be transformed anymore. Assuming all dates are stored in UTC seems a little bit dangerous.
- The default usage of `date` and `datetime` casts is not automatically timezone-transformed, meaning there will be inconsistencies between regular date usage in views such as `$date->format('d.m.Y')` and dates that are JSON serialized.

### Steps To Reproduce:

Set your app's `.env`'s timezone in something else than an UTC value, for instance : 

```
APP_TIMEZONE="Europe/Brussels"
```

Create a migration containing an extra date column : 

```php
Schema::create('articles', function (Blueprint $table) {
    $table->id();
    $table->timestamp('published_at')->nullable();
    $table->timestamps();
});
```

Create a model : 

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $casts = [
        'published_at' => 'datetime',
    ];
}
```

Seed one or more database entries :

```php
namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Seeder;

class ArticlesTableSeeder extends Seeder
{
    public function run()
    {
        Article::create([
            'published_at' => now()->startOfDay(),
        ]);
    }
}
```

Try the following route : 

```php
Route::get('/', function() {
    $article = \App\Models\Article::find(1);

    return [
        'formatted' => $article->published_at->format('Y-m-d H:i:s'),
        'model' => $article
    ];
});
```

It should return the following JSON : 

![image](https://user-images.githubusercontent.com/5635557/119352721-51ead380-bca2-11eb-8dfa-cdf0c47b57d1.png)

Now, in your `App\Models\Article` model, change the datetime casting as follows : 

```php
class Article extends Model
{
    protected $casts = [
        'published_at' => 'datetime:Y-m-d H:i:s',
    ];
}
```

The JSON now contains the correct datetime (notice the 2 hours difference in `model.published_at` with the previous screenshot) : 
 
![image](https://user-images.githubusercontent.com/5635557/119353153-d50c2980-bca2-11eb-8adb-9d957ac6f45e.png)

**Comment by AegirLeet** [comment]
There's no 2 hour difference, it's just displayed for a different timezone. 22:00 in UTC and 00:00 in Europe/Brussels (CEST/UTC+2) are the same thing.

I'd recommend you always include the timezone (as is done in the default RFC 3339 output). That way, any consuming code doesn't have to make any assumptions.

**Comment by driesvints** [comment]
There's indeed no difference. Both dates are the same.

**Comment by Nyratas** [comment]
Yes, I'm aware it's the same date. But that's not the point : I'm saying there is a difference in behavior between : 

```php
    protected $casts = [
        'published_at' => 'datetime',
    ];
```

... and for instance : 

```php
    protected $casts = [
        'published_at' => 'datetime:Y-m-d H:i:s',
    ];
```

... when the model gets serialized using `toArray()`.

**Comment by driesvints** [comment]
A few things first:

`APP_TIMEZONE` doesn't exists in Laravel. [You set the timezone directly in the config file.](https://github.com/laravel/laravel/blob/131a10260e73e83e6b1cd63788b8f6584dd3e98a/config/app.php) Make sure you always clear your config cache when working with changes in config files.

A general tip: you're linking to lines of code using the direct path provided by the browser. Because it's been a few days the file has changed and the lines don't match what you wanted to indicated anymore. Before sharing lines of code, make sure you press "Y" on your keyboard so you get a hotlink to the line of code from the current commit. That way it'll always link to the correct line of code.

> When setting a timezone (for instance: APP_TIMEZONE="Europe/Brussels" in .env), all $model->toArray() calls will transform date and datetime casted attributes using the app's timezone, unless the cast uses a custom datetime format such as datetime:Y-m-d H:i:s.

This isn't true. It'll cast to `UTC` and append the timezone by default. It's only when you provide a specific format for `datetime` that it'll apply the timezone from the app. So it's actually the other way around (as your example shows).

> IMO dates should never be automatically transformed using the .env's APP_TIMEZONE

Yet this is what you seem to want? Your last example you say: "The JSON now contains the correct datetime" which indicates that you *want* that the date automatically transforms using the app's timezone? This is a bit confusing.

> Dates might already be stored correctly using the app's timezone, in which case they don't need to be transformed anymore. Assuming all dates are stored in UTC seems a little bit dangerous.

We don't assume this. Dates are indeed stores in the app's timezone. I don't know why you seem to think that? The fact that dates are output as UTC with `toArray` is a design decision because we use Carbon's `->toJSON` method which converts the datetime to UTC. See:

https://github.com/laravel/framework/blob/593f0dde0b64f6850a226ebcdb36700ad4ca6276/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1110

And: https://github.com/briannesbitt/Carbon/blob/210cc733e1004fc4fb2ab2f9ee8503e54a8f6ead/src/Carbon/Traits/Converter.php#L540

> The default usage of date and datetime casts is not automatically timezone-transformed, meaning there will be inconsistencies between regular date usage in views such as $date->format('d.m.Y') and dates that are JSON serialized.

Now this is something we can agree on. I indeed also think that there's an irregularity between a default `datetime` cast and one with a custom timezone. I've figured out how to change this. If I change the line from above to:

```php
protected function serializeDate(DateTimeInterface $date)
{
    return Carbon::instance($date)->toISOString(true);
}
```

Then it'll get the behavior I think you're after. The dates are still valid and their correct timezone is appended so it's still a valid ISO 8601 timestamp. 

Now the question still remains if this is wanted. In all essence the timestamp is a valid and and it'll follow the app's timezone. But people might expect UTC by default. I'm wondering is @kylekatarnls has any insights here on why the timestamp is converted to UTC by default for `toJSON()`?

**Comment by Nyratas** [comment]
Thank you for providing this detailed response. I didn't know about the `Y` shortcut on GitHub, that's good to know! 🙂 

Indeed, I forgot that `APP_TIMEZONE` was something we added on our project, which was referenced in our `config/app.php` file using `'timezone' => env('APP_TIMEZONE', 'UTC')`. When I referred to `APP_TIMEZONE`, it was that timezone configuration I was talking about, my bad. I see I went a little bit fast on the issue description also, sorry about that.

To summarize, here's a simpler, better and corrected explanation of what I was trying to point out (but I guess you figured it out) :

> The date stored in the database is `2021-05-24 00:00:00`, which as you said is stored in the app's timezone (in this case: `Europe/Brussels`).
> When casting the date attribute using a simple `datetime` cast type, `toArray()` will indeed output the date as UTC: `2021-05-23T22:00:00.000000Z`.
> When casting the same date attribute using a custom format, such as `datetime:Y-m-d H:i:s`, it will no longer output the date as UTC, but will remain in the app's configured timezone: `2021-05-24 00:00:00`.
> These are two different behaviors, which is a little bit unexpected. However, I agree it wouldn't make sense if the date was outputed as UTC when the timezone is not specified in the requested format.

That being said (and my initial issue description put aside), I think it would make more sense to always use the app's timezone, even when outputting the default `datetime` cast, meaning that the changes you suggested for the `serializeDate` method would make perfect sense.

I understand the current behavior has been put there by design, it's quite a tricky question (as always when working with timezones).

Maybe adding a cast type option would be a possible answer ? Something like `datetime:utc` which could also be formatted use `datetime:utc:Y-m-d` ? I don't know, it's only a suggestion 😄

**Comment by driesvints** [comment]
Thanks @Nyratas. Another option would be to add a new property `$serializeDatesAsUTC = true` to control the behavior.

I'm gonna wait a bit until @kylekatarnls has had a chance to reply here on what he thinks is best.

**Comment by kylekatarnls** [comment]
I know, it's not the point, but first I wish to advice not having APP_TIMEZONE="Europe/Brussels" or such kind of global application timezone. It's even worse when the default timezone has DST, because when you will store `31 oct 2021 2h30` in your DB it can refer to 2 different moments (2h30 GMT+1 or 2h30 GMT+2, both exists in Brussel) and you will have absolutely now way to know from which offset it came when you retrieve it from the DB. For a query `SELECT * FROM messages ORDER BY date DESC` all messages sent before 2AM GMT+2 and 3AM GMT+2 will be mixed with those send in the next hour. + Plenty of other DST bugs coming directly from PHP: https://bugs.php.net/search.php?cmd=display&search_for=timezone&x=0&y=0

And it's even even worse the this timezone is driven by an env var which means it can change if you change the env var and so you will get mixed timezones dates in your DB.

Last it does make any sense to store them with Brussels if you're sending them as UTC anyway.

I detailed the position in this article: https://kylekatarnls.medium.com/always-use-utc-dates-and-times-8a8200ca3164

So be kind with your future you, stick your application timezone and DB timezone to UTC. You actually don't need Europe/Brussel, UTC is just fine to represent universally a given instant making your database agnostic from where the server, company or any other stuff lives. It does not prevent to display dates in any timezone properly to the users.

For the tip having an already existing application is not a blocker, you can make it offline for maintenance, change date values then apply the new UTC settings so even previously stored dates will be correct.

Now, even if I don't think Laravel should encourage to switch timezone at model level, this is still the business responsibility to be strict or not with this.

Carbon has a `$keepOffset` in `toISOString` (`toISOString($keepOffset = false)`) which is actually what needed here to get the Brussels offset used so `$serializeDatesAsUTC` like proposed by @driesvints could be easily linked in: `$date->toISOString(!$this->serializeDatesAsUTC)` but we still have an inconsistency or BC change as the offset is kept with the default JSON serialization but no longer as soon as a custom format is used.

So, a syntax like `datetime:America/Toronto@Y-m-d H:i:s` would be a bit better because:
- it allows to use something else than `config('app.timezone')` or `UTC`
- it allows to customize each property differently
- default behavior can be more easily documented:
  - if format is specified but not timezone, `config('app.timezone')` is used
  - if timezone is specified but not the format, `Y-m-d\TH:i:s.uP` is used
  - if none are specified, `Y-m-d\TH:i:s.uP` is used as format, `UTC` is used as timezone
It does not get rid of the inconsistency but allow to control it in a single point. And it will be more easy on a next major version to enforce one or the other.

But there is a need to precise the syntax, `datetime:Europe/Brussels:Y-m-d H:i:s` is not possible because we can't know if `:` is a separator between format/timezone or simply between units (like in `H:i` format side, or in `GMT+02:00` timezone side), and we can't detect what is a timezone or a format in a smart way, for instance `GMT` can be both a valid timezone or a valid date format. That's why we need a dedicated separator such as `@` in my example.

And we can replace empty string as timezone with `config('app.timezone')` so `datetime:@Y-m-d H:i:s` is Brussels with the given custom format in our example.

The same way, we could have the shortcut `datetime:America/Toronto@` to set the timezone and keep the default format, but it would actualy be a small BC: currently `'datetime:'` use `""` as a date format. I can't see any reason to do that so I don't think, it would impact any real user but still worth to be known so if anyone has a better idea for a non-ambiguous backward-compatible syntax that would not prevent from using default values, it would be even better.

**Comment by driesvints** [comment]
Hey @kylekatarnls. Thank you so much for the thorough explanation. I definitely want to talk with you in person more about timezone behavior in Laravel but for the sake of keeping things simple for this specific issue, would you agree that adding a `$keepOffset = false` property to the Eloquent model class in 8.x could solve things here for @Nyratas and then maybe making `$keepOffset` `true` by default in 9.x would be a valid thing to do?

That's beside the point of the timezone/DST issues you highlighted when working with databases. I'll ping you on Discord to discuss that separately.

**Comment by driesvints** [comment]
@Nyratas so I talked to Kyle about all this on Discord. What the best solution for now is going to be is to document the behavior you're experiencing. I'll send in a PR for that.

To unblock you: you can override `serializeDate` in your models for now with the below so all of your serialized dates are in the same timezone as your app:

```php
/**
 * Prepare a date for array / JSON serialization.
 *
 * @param  \DateTimeInterface  $date
 * @return string
 */
protected function serializeDate(DateTimeInterface $date)
{
    return Carbon::instance($date)->toISOString(true);
}
```

**Comment by Nyratas** [comment]
Hi @driesvints, I just realized I didn't come back to you in time when I posted this issue. Sorry about that and thank you very much for all the great work you and @kylekatarnls provided over the years (not only in this issue), it is very much appreciated! Keep up the good work guys :)

**Comment by dyanakiev** [comment]
I just had similar issue and i was going nuts, i'm using carbon dayOfWeek and i was wondering why my date was wrong... the model was returning the wrong date.. I have had set the correct timezone in app.config and also date_default_timezone_set, thanks for the fix 🏆  ❤️

**Comment by bernardwiesner** [comment]
Is there no way to disable this behaviour globally? Its annoying to have toArray cast created_at and updated_at to UTC by default. I understand the intention behind this being especially dealing with dates in JS making it easier to handle using UTC, however there are many use cases where this is not needed, such as just backend jobs/batches, where you dont want UTC when using toArray.

It would be good to have a global setting to disable this conversion not having to do it one by one on every Model. Having an option inside app.php such as `date-serialization => false`

**Comment by kylekatarnls** [comment]
> backend jobs/batches, where you dont want UTC when using toArray

If you want it done correctly, you want UTC there even more than for communicating to clients. Machine should talk in UTC between themselves there is absolutely no good reason for backend stuff to use human timezone over UTC.

**Comment by bernardwiesner** [comment]
@kylekatarnls 
 One such use case would be migration to different DBs. If my dates are already non UTC datetime in DB and then I try migrating using 

SomeBigTable::insert($records->toArray());

This would cause issues due to converting the dates to UTC.

**Comment by kylekatarnls** [comment]
I would say then you're way more in control, doing your migration like this explicitly over asking a (risky) global settings to be applied on Laravel level:

```php
$dateFields = [
  'created_at' => 'America/Chicago',
  'updated_at' => 'America/Chicaco',
];

$record = $records->toArray();

foreach ($dateFields as $field => $timezone) {
  $record[$field] = Carbon::make($record[$field])->tz($timezone)->format('Y-m-d H:i:s.u');
}

SomeBigTable::insert($record);
```

**Comment by kylekatarnls** [comment]
Side not if you have such problem, it's likely also because you don't declare the column as a datetime, if the `$record` uses Carbon objects and the model is aware of which columns are datetime, you won't get such errors.

**Comment by bernardwiesner** [comment]
This issue is in relation to upgrading to Laravel 9, one of the cases I faced was with that DB migration batch, but there are loads of other batches in the codebase that also use toArray with different use cases and its to cumbersome to go and check every case.

What i just did was extend a new BaseModel on all of my models and include this in my BaseModel to get back the old behavior of toArray.

```php
protected function serializeDate(DateTimeInterface $date)
{
    return Carbon::instance($date)->toISOString(true);
}
```
