### ISSUE TITLE
Datatype mismatch using Eloquent Model

### ISSUE THREAD

**Issue by ss-wiking** [laravel/framework#37544]
- Laravel Version: 8.44.0
- PHP Version: 7.4.19
- Database Driver & Version: PostgreSQL 13.3 with pgBouncer

### Description:
When using `save()` method on PostgreSQL database with `\PDO::ATTR_EMULATE_PREPARES => true`, DB connection cast boolean to integer in the prepareBindings and bindValues methods.

### Steps To Reproduce:

```
Uses::create([
    'name' => 'Laravel user',
    'password' => 'password',
    'is_suspended' => false,
]);
```

Error: `SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "is_suspended" is of type boolean but expression is of type integer`

**Comment by driesvints** [comment]
Are you sure you're on PHP 7.4.19? Is your CLI version also the same one as the web server one? There was a bug in PHP 7.4.18 that caused this.

**Comment by ss-wiking** [comment]
> Are you sure you're on PHP 7.4.19? Is your CLI version also the same one as the web server one? There was a bug in PHP 7.4.18 that caused this.

I ran a command on the server: `docker exec -it laravel php -v`
Execution result
```
PHP 7.4.19 (cli) (built: May 12 2021 13:21:40) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by driesvints** [comment]
It would strike me as odd that nobody has ever run into this before. Since my experience with PostgreSQL is limited I'm going to have to ask you to first try a support channel to actually verify this bug. Maybe somebody with PostgreSQL experience can help you out. If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
