### ISSUE TITLE
Route::redirect changes priority after running route:cache

### ISSUE THREAD

**Issue by imacrayon** [laravel/framework#37639]
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version: MYSQL

### Description:

`Route::redirect` has a different priority after running `artisan route:cache`.

### Steps To Reproduce:

In  `web.php` I had routes set like this:
```
Route::redirect('/organizations/{organization}', '/organizations/{organizations}/overview');
Route::patch('/organizations/{organization}', ...); 
```
`get` and `patch` requests to these routes were working normally until I ran `artisan route:cache`. After the cache command all `patch` requests were intercepted by the redirect route.

The fix for me was to swap the ordering of these two routes, but I wonder, is there a code change that could be made to make this behavior more consistent? If not, maybe there can be more guidance around route order/priority in the documentation?

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new horizon-issue-982 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by imacrayon** [comment]
@driesvints here you go: https://github.com/imacrayon/framework-issue-37639

Clicking the submit button on the homepage will display "Success". But you get a different page on submit after running `artisan route:cache`.

**Comment by driesvints** [comment]
Thanks, that was very helpful. I see the same thing happening. I'm trying to recollect what the expected behavior is here as I remember we've been looking into something similar when we introduced the new Symfony compiled routes feature. I'll take a look at this when I find some time. Otherwise we're also welcoming PR's.

**Comment by driesvints** [comment]
Seems like this behavior has existed ever since we introduced route caching. I'm not sure on an easy way to solve this. Maybe we can re-order redirect routes.

**Comment by driesvints** [comment]
I can't find a decent solution for this. I've tried to rewrite the `toSymfonyRouteCollection` method to the following:

```
    public function toSymfonyRouteCollection()
    {
        $symfonyRoutes = new SymfonyRouteCollection;

        $routes = $this->getRoutes();
        $controller = $route->action['controller'] ?? '';

        // Add redirect routes...
        foreach ($routes as $route) {
            if (! $route->isFallback && is_a($controller, RedirectController::class, true)) {
                $symfonyRoutes = $this->addToSymfonyRoutesCollection($symfonyRoutes, $route);
            }
        }

        // Add regular routes...
        foreach ($routes as $route) {
            if (! $route->isFallback && ! is_a($controller, RedirectController::class, true)) {
                $symfonyRoutes = $this->addToSymfonyRoutesCollection($symfonyRoutes, $route);
            }
        }

        // Add fallback routes...
        foreach ($routes as $route) {
            if ($route->isFallback && ! is_a($controller, RedirectController::class, true)) {
                $symfonyRoutes = $this->addToSymfonyRoutesCollection($symfonyRoutes, $route);
            }
        }

        return $symfonyRoutes;
    }
```

But that won't work because the conflicting route can also be above the redirect route. We can't just move all redirect routes to the bottom.

**Comment by donnysim** [comment]
It's not really redirect only problem, it's a problem in general:

```php
Route::any('/test', function () {
    return '1';
});

Route::get('/test', function () {
    return '2';
});
```

Outputs the same problem - `2` is displayed without cache and `1` is displayed with cache.

**Comment by nfangxu** [comment]
Why not cache the laravel route, but convert it into a symfony route for caching? @driesvints

**Comment by aanfarhan** [comment]
> * Laravel Version: 8.12
> * PHP Version: 7.4
> * Database Driver & Version: MYSQL
> 
> ### Description:
> `Route::redirect` has a different priority after running `artisan route:cache`.
> 
> ### Steps To Reproduce:
> In `web.php` I had routes set like this:
> 
> ```
> Route::redirect('/organizations/{organization}', '/organizations/{organizations}/overview');
> Route::patch('/organizations/{organization}', ...); 
> ```
> 
> `get` and `patch` requests to these routes were working normally until I ran `artisan route:cache`. After the cache command all `patch` requests were intercepted by the redirect route.
> 
> The fix for me was to swap the ordering of these two routes, but I wonder, is there a code change that could be made to make this behavior more consistent? If not, maybe there can be more guidance around route order/priority in the documentation?

Yes this is true. Because cached routes of method `Route::redirect` and `Route::patch` with same path '/somepath' has the same method `PATCH` so the first written route will be the one being called which is `Route::redirect`. 

If you investigate the cached route file and in array of '/somepath' it will has array of methods like this:
```php
// redirect 
array (
            'GET' => 0,
            'HEAD' => 1,
            'POST' => 2,
            'PUT' => 3,
            'PATCH' => 4, // this will match the method of request
            'DELETE' => 5,
            'OPTIONS' => 6,
          ),

// patch
array (
            'PATCH' => 0,
),
```
If you remove or commented out the `'PATCH' => 4`, value then it's gonna work like you expected. So I was wondering why the `Route::redirect` method generate all the http methods instead of only `GET`? @driesvints

**Comment by driesvints** [comment]
@aanfarhan this issue isn't specifically to PATCH. It's for all HTTP methods.

**Comment by lk77** [comment]
well, if you do a redirect, it's for every method, not only get requests.

**Comment by aanfarhan** [comment]
What I'm trying to say is maybe it would be better if you can configure redirect route to work only on certain HTTP methods. Because logically if you call to the same endpoint with the same HTTP method it will only generate one result right?

**Comment by driesvints** [comment]
@aanfarhan that's not really in the scope of this issue. Let's keep this issue focused on the issue at hand.

**Comment by JohnKlein1991** [comment]
@driesvints maybe just invert order in routes' list for cache file, like this:
```
    protected function getFreshApplicationRoutes()
    {
        $collection = new Collection();
        $routes = new RouteCollection();
        foreach ($this->getFreshApplication()['router']->getRoutes() as $route) {
            $collection->prepend($route);
        }
        foreach ($collection as $route) {
            $routes->add($route);
        }
        return tap($routes, function ($routes) {
            $routes->refreshNameLookups();
            $routes->refreshActionLookups();
        });
    }
```

In this case last routes override previous ones, but I don't know how to write it more beauty

**Comment by imanghafoori1** [comment]
The root cause of this problem is that when the routes are cached we use "symfony matcher" to match a route based on request data and when the routes are not cached we use "Laravel matcher". so the implementation of the match method is very different and they behave differently when there are two candidates to choose from.

You can run this in case of cache being present and being deleted to see the output of dd.
![image](https://user-images.githubusercontent.com/6961695/126501322-db4302a8-9708-42e1-9f7d-a920ea5ed273.png)

I still believe that this PR can solve the problem: #38095

**Comment by derekmd** [comment]
https://laravel.com/docs/8.x/routing The docs now have callout about ordering route definitions unambiguously. So if a non-breaking code change can't be agreed upon, this issue can be closed.

![route-me](https://user-images.githubusercontent.com/823566/135912772-65efc3e2-357d-4d8f-9149-2bc4b2ebf4cc.png)

**Comment by driesvints** [comment]
@derekmd I agree that's the best solution to this really. It's a hard problem to solve otherwise.

**Comment by imanghafoori1** [comment]
@driesvints @taylorotwell Laravel can provide an artisan command so that the users can scan their routes to see if there is any overriding is going on and resolve the situation for themselves.
I have already implemented such a thing almost year ago on laravel-microscope for inspection purposes.
`php artisan check:routes` will do the job and informs if routes are conflicting.
