### ISSUE TITLE
DB insertUsing prepends prefix to database name, on cross database queries

### ISSUE THREAD

**Issue by A-Lawrence** [laravel/framework#37840]
- Laravel Version: 8.47.0
- PHP Version: 8.0
- Database Driver & Version: MariaDB  10.5.9

### Description:

When using the insertUsing() DB method, with a cross-database query as the $query argument, the table prefix is prepended to the database name (twice) and not the table name.

This appears to be caused by `Illuminate/Database/Query/Builder.php:352` prepending the table name with the database name too early.

### Steps To Reproduce:

Add a table prefix to the database connection being used in the 2nd argument. In this example, `oc_` is being used.

```php
DB::connection('pims')->table('product_listings')->insertUsing([
            'channel',
            'listing_id',
            'product_id',
            'status',
        ], DB::connection('opencart')->table('product')
            ->select([
                'channel',
                'pos_id AS listing_id',
                'product_id',
                'status',
            ])
        );
```

The resultant query is:

```sql
(SQL: insert into `product_listings` (`channel`, `listing_id`, `product_id`, `status`) select `channel`, `pos_id` as `listing_id`, `product_id`, `status` from `oc_oc_opencart`.`product`)
```

Whereas it should be:

```sql
(SQL: insert into `product_listings` (`channel`, `listing_id`, `product_id`, `status`) select `channel`, `pos_id` as `listing_id`, `product_id`, `status` from `opencart`.`oc_product`)
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
