### ISSUE TITLE
syncWithoutDetaching performance issues

### ISSUE THREAD

**Issue by olegcm** [laravel/framework#37874]
- Laravel Version: 6.20.29 (same for the 8.47.0)
- PHP Version: 7.2.34
- Database Driver & Version: MySQL 5.7

### Description:
There is a real performance issue in the `syncWithoutDetaching` method ( and also `sync` cause that's the method which actually works under the hood).
When you have hundreds of thousands of rows in pivot table the loading of currently attached pivots consumes enormous amounts of memory.

Simple case: let's say you have lists and customers with a many to many relationship.
And there are 150K customers in list A already, then trying to use a `syncWithoutDetaching` method on one single customer will cause the framework to load all 150K to memory and perform array manipulations there.
Also as far as I understand this array is duplicated multiple times during this action so even more memory used.

While it could be done with performing a single query to DB to test if the customer is present in the pivot table already for the given list or at least limiting the query to the requested ids only.

I don't think it's a good idea to perform array manipulations on large amounts of data anyway. 

### Steps To Reproduce:

1. Create two models with many to many relationship
2. Seed the DB with 150K of records in the pivot table
3. Try to use the `syncWithoutDetaching` on a single model
4. Measure the memory usage

**Comment by driesvints** [comment]
Think this is more of a case of optimizing in your app. It's true that all models are loaded into memory but this is intended. In fact, the `getCurrentlyAttachedPivots` is used in more places than just `sync. If you're having memory issues with pivot's I suggest you consider to refactor the pivots to an actual Eloquent model.

Otherwise we're always welcoming PR's that improve the framework. Thanks
