### ISSUE TITLE
Eloquent dirty check for collections

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#37961]
- Laravel Version: 8.x
- PHP Version: all

### Description:
Currently, the eloquent model dirty checks are not working correctly for collection attributes if a value changes between `boolean` and `string`.

### Steps To Reproduce:
```php
use Illuminate\Database\Eloquent\Model;

class Test extends Model
{
    protected $casts = [
        'collection' => 'collection',
    ];
    protected $fillable = [
        'collection',
    ];
}

$model = new Test(['collection' => ['key' => true]]);
$model->syncOriginal();
$model->fill(['collection' => ['key' => 'value']]);

$model->isDirty(); // false but should be true
```

### Reason for this behaviour:
The attributes are casted within the `HasAttributes` trait to a collection and checked with php's equality logic:
1. `$this->castAttribute($key, $attribute) == $this->castAttribute($key, $original);`
2. When using the comparison operator (==), object variables are compared in a simple manner, namely: Two object instances are equal if they have the same attributes and values (values are compared with ==), and are instances of the same class. [[PHP: Comparing Objects]](https://www.php.net/manual/de/language.oop5.object-comparison.php)
3. $a == $b | Equality | true if $a and $b have the same key/value pairs. [[PHP: Array Operators]](https://www.php.net/manual/en/language.operators.array.php)

So, the values are checked with PHP's simple equality check, which is now showing the typical unsafe type checks with strings. In my opinion, the model should be marked as dirty. Depending on the opinion whether this is a bug or expected behavior, I would propose doing strict dirty checks for next major release.

**Comment by driesvints** [comment]
Hey @tpetry, this is more of a feature request I think. Feel free to attempt a PR to see if Taylor would accept it 👍

**Comment by tpetry** [comment]
I wouldn't call it a feature request if my models at the moment don't save their updated values to the database because of the actual behavior of the dirty check algorithm.

**Comment by driesvints** [comment]
@tpetry we could maybe add another `strict-collection` besides the current one. Please try a PR if you're willing. If it's not accepted you can always use if in your own code base.

**Comment by tpetry** [comment]
The same problem is happening for `array`, `object`, maybe `AsArrayObject::class` and `AsCollection ::class`. @taylorotwell Is this expected behavior, or a bug? If it's a bug, i can write a PR for `8.x` or `9.x` if it is declared a breaking change.

**Comment by krnsptr** [comment]
I think this is a bug. I had unknown bug for years because of this.

When my collection attribute is changed from `[null]` to `[0]`, eloquent treats it as unchanged because of loose comparison. Therefore, saving the model won't work. I will stop using collection cast and just use plain array until this issue is fixed.

https://github.com/laravel/framework/blob/88dd075b9f1beaff93796a0ee51818796ca04654/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1413-L1415

It is unsafe to compare collections using loose comparison. It wouldn't make sense to use strict comparison either, since two different objects always yield different even if their values are same.

I would suggest using raw attributes (JSON string) to check for dirty objects/collections.

**Comment by krnsptr** [comment]
Related: https://github.com/laravel/framework/pull/38774#issue-994150768

I think this is intended behavior: collections should be converted to arrays and then compared using strict comparison.
