### ISSUE TITLE
Unable to make spy of the "Schema" facade

### ISSUE THREAD

**Issue by awjudd** [laravel/framework#37983]
- Laravel Version: 8.49.2
- PHP Version: 8.0.7
- Database Driver & Version: N/A

### Description:
When testing and trying set up the spy on the `Schema` object (i.e. `Schema::spy()`), you receive an exception.

### Steps To Reproduce:

1 - Create a test case
2 - Call the following:
```php
Schema::spy();
```
3 - When you run the test case, you will receive the following error:
```
TypeError: Illegal offset type in isset or empty

/Users/judda/code/schema-facade/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:128
/Users/judda/code/schema-facade/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:52
/Users/judda/code/schema-facade/tests/Feature/ExampleTest.php:18
```

Commit with the issue:
https://github.com/awjudd/laravel-schema-issue/commit/9040182ce26fc4572c6c79f6200d13d12ddc8042

### Extra Information

When digging a little deeper, it looks like there are at least 2 spots that have the same issue. In `src/Illuminate/Support/Facades/Schema.php` the following methods:
* `swap`
* `isMock`

I believe that it has to do with the following change:
https://github.com/laravel/framework/commit/63d87d78e08cc502947f07ebbfa4993955339c5a

The reason being, at this point in time the method no longer could be trusted to only return a string, so doing the dictionary lookup was ignored in one spot (https://github.com/laravel/framework/commit/63d87d78e08cc502947f07ebbfa4993955339c5a#diff-85c2ee3096a7c4457f3abe3785b2584af93e1672402207cee10195543acbba49R167)

**Comment by taylorotwell** [comment]
Why do you need to spy on the `Schema` facade?

**Comment by awjudd** [comment]
I was trying to write a test for something that was calling the `hasTable` method on this object.  I just tried and verified that it also happens when you use `partialMock`.

**Comment by taylorotwell** [comment]
It's unclear at the moment if this is solvable on our side due to our the schema stuff is setup.

My best suggestion is to put your Schema operations you want to test behind another class like `App\Schema`. Within that class, make methods for the schema operations you want to mock, then inject that class into whatever needs to interact with the schema. Basically, put the schema operations behind another class / layer that you can inject and mock.

**Comment by driesvints** [comment]
Going to close this one now. @awjudd there doesn't seems to be an easy way for us to fix this so please try the suggestions by Taylor.

**Comment by driesvints** [comment]
I sent in a possible solution for this here: https://github.com/laravel/framework/pull/38017

Btw @awjudd, while investigating I noticed you have a slight issue in your code. It should be `shouldHaveReceived` instead of `shouldReceive`. Former is used in combination with spying while the latter is used for mocking.

**Comment by awjudd** [comment]
Good catch - about the `shouldHaveReceived`, it was a copy and paste from my previous example where I was defining them all upfront.
