### ISSUE TITLE
Running `artisan model:` prunes models

### ISSUE THREAD

**Issue by musa11971** [laravel/framework#38129]
- Laravel Version: 8.51.0
- PHP Version: 7.4.18
- Database Driver & Version: not applicable

### Description:

Calling `php artisan model:` runs `php artisan model:prune`. This may cause "unexpected" pruning, seeing as you would expect a list of commands in the model namespace.  
For example, running `php artisan make:` shows you a list of commands in the make namespace, rather than running a (default?) command.

This does not just happen for `model:`, but even for shorter variants, like `php artisan mo:`:
<img width="517" alt="Screenshot 2021-07-25 at 20 32 12" src="https://user-images.githubusercontent.com/21341801/126909558-47141d28-45bf-4e85-b840-b03b545ac228.png">

### Steps To Reproduce:
1. Run one of the commands: `artisan mo:`, `artisan mod:`, `artisan model:`.
2. Models will be pruned.

**Comment by NickSdot** [comment]
Side note: same happens with `artisan schema:` or `artisan schem:` or any other commands with only one available command starting with the specific string. In contrast `artisan sche:` will return alternatives as described with `artisan make:` by @musa11971. But only because in this case there is also `artisan schedule:`.

The reason is that Symfony is only offering alternatives, if there are any other roughly matching results. Otherwise it uses the only available macth. 

```php
if (\count($commands) > 1) {
    $suggestions = $this->getAbbreviationSuggestions(array_filter($abbrevs));

    throw new CommandNotFoundException(sprintf("Command \"%s\" is ambiguous.\nDid you mean one of these?\n%s.", $name, $suggestions), array_values($commands));
}
```
 
https://github.com/symfony/symfony/blob/ff545130e0e16caee772633f6ea1ef8fef3aa04c/src/Symfony/Component/Console/Application.php#L720-L724

**Comment by ankurk91** [comment]
Such commands should implement this trait

use Illuminate\Console\ConfirmableTrait;

Which will ask for confirmation on production

**Comment by driesvints** [comment]
This is standard Symfony behavior and nothing we can do about ourselves. We won't be adding the confirmable trait atm since it's a breaking change. If you want to attempt a PR for Laravel v9 feel free to send one in to see if it'll be accepted. Thanks.
