### ISSUE TITLE
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'date_field' at row 1

### ISSUE THREAD

**Issue by EgorGruzdev** [laravel/framework#38828]
- Laravel Version: 8.61.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL 8 (strict mode)

### Description:

Colleagues, when working in strict mode with a database, we get an error, because after the implementation of this functionality #38720, the date fields are saved to the database in the format specified in the grammar, ignoring the caster parameters, i.e. in case of mysql format "Y-m-d H:i:s", although the database for the date type expects "Y-m-d".

In version 8.60, the format coincided with the format specified in the caste.

### Steps To Reproduce:

```php
class TestModel1 extends Model
{
    public $table = 'test_model1';
    protected $guarded = [];

    public $casts = [
        'date_field' => 'date:Y-m-d',
    ];
}

TestModel1::create([
          'date_field' => '2019-10-01',
]);
```

**Comment by EgorGruzdev** [comment]
Also, if the $dateFormat property is specified, then in version 8.60, if there was a caste on the field, then this format was ignored and taken from the caste attributes. In version 8.61, the caste attributes are ignored and the $dateFormat property is always used.

**Comment by daniser** [comment]
I agree, since 8.61 $dateFormat or grammar's default date format have priority over custom caster format. In fact, caster format is never used anymore.

**Comment by derekmd** [comment]
Last week's pull request fixed `Model@setAttribute()` falsely marking an attribute as dirty when assigning  `Carbon` objects. However the new test case added didn't have coverage for assigning _strings_ which is the common use case when `$request->validated()` is filled into the model.

This is a `setAttribute()` change that could potentially fix it: https://github.com/laravel/framework/compare/8.x...derekmd:fix-setattribute-custom-cast-date-format?expand=1

However I need to figure out a more ~~eloquent~~ graceful solution to conditionally invoke `fromDateTime()` with the custom date format without introducing a new argument in 8.x. That commit introduces some duplicate code with `addCastAttributesToArray()` so the casting lifecycle is now a bit weird.

**Comment by Ilyes512** [comment]
I also came across this issue because of an failing test case. I have a model "Company" with an date field 'founded_at':

```php
class Company extends Model
{
    protected $casts = [
        'founded_at' => 'date:Y-m-d',
    ];
}
```

In my tests I use `assertDatabaseHas` and I need to set different `founded_at` values for different versions of Laravel.

When I use it with Laravel version `8.61.0` to make it pass the assertion I need to do:

```php
$this->assertDatabaseHas(
    Company::class,
    ['id' => 10, 'founded_at' => '1991-01-27 00:00:00'],
);
```

While with Laravel version `8.60.0` (and older) it needs to be:

```php
$this->assertDatabaseHas(
    Company::class,
    ['id' => 10, 'founded_at' => '1991-01-27'],
);
```

So in my case this is for a (Laravel) library I am not sure how to solve this issue so it will work for version `8.61.0` and previous versions. I can lock it on `^8.6.1.0`, but in case the mentioned PR is rolled back it would break it again.

**Comment by derekmd** [comment]
There are two app-level solutions for strict SQL date format until/if the framework fixes this:

### Elouqent set mutator

https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator

This avoids the new `setAttribute()` behaviour, although you'd need to define a new method for every date column requiring an exact date format.

```php
use Illuminate\Support\Facades\Date;

class Company extends Model
{
    protected $casts = [
        'founded_at' => 'date:Y-m-d',
    ];

    public function setFoundedAtAttribute($value)
    {
        $this->attributes['founded_at'] = $value === null ?
            null :
            Date::parse($value)->format('Y-m-d');
    }
}
```

### Custom cast

https://laravel.com/docs/8.x/eloquent-mutators#custom-casts

A re-usable solution that doesn't require a new mutator method for each database column.

```php
namespace App\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Illuminate\Contracts\Database\Eloquent\SerializesCastableAttributes;
use Illuminate\Support\Facades\Date;

class DayCast implements CastsAttributes, SerializesCastableAttributes
{
    public function get($model, string $key, $value, $attributes)
    {
        if ($value !== null) {
            return Date::parse($value);
        }
    }

    public function set($model, string $key, $value, $attributes)
    {
        if ($value !== null) {
            return Date::parse($value)->format('Y-m-d');
        }
    }

    public function serialize($model, string $key, $value, array $attributes)
    {
        return $this->set($model, $key, $value, $attributes);
    }
}
```

```php
class Company extends Model
{
    protected $casts = [
        'founded_at' => \App\Casts\DayCast::class,
    ];
}
```

---

For both snippets, `Date::parse()` may not be the catch-all solution since protected method [`Model@asDateTime()`](https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1048) used by `setAttribute()` has some additional ways it constructs a new Carbon object.

**Comment by driesvints** [comment]
Ping @macbookandrew

**Comment by taylorotwell** [comment]
Probably have to revert. Might make it a policy to reject all changes to casting / "is dirty" behavior.

**Comment by taylorotwell** [comment]
Reverted.

**Comment by macbookandrew** [comment]
I’m so sorry for the problems as a result of #38720.

@EgorGruzdev / @derekmd / @Ilyes512 if you have a chance, would you mind testing #38994 to see if it fixes the issues you had? As far as I can tell, it restores the formatting for the database bindings while retaining the comparison check I was attempting to fix.

@taylorotwell would you reconsider your possible policy change for that followup PR?
