### ISSUE TITLE
Jetstream BelongToMany Pivot withTimestamp not follow Model definition

### ISSUE THREAD

**Issue by xicond** [laravel/framework#38820]
- Laravel Version: v8.58.0
- PHP Version: 7.4.22
- Database Driver & Version: 10.5.8-MariaDB-log
- Doctrine/dbal: 2.13.2

### Description:
Pivot withTimestamp not follow Model definition
I have legacy user table definition that too many dependency, so I need to adapt the timestamp fieldname.
When I modified timestamp field for User.php, calling Auth::user()->teams causing errors
The error indicated, the timestamp field changed is in team_user, instead of team_user follow default fieldname as team_user.created_at

```
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'team_user.create_at' in 'field list' in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79
Stack trace:
#0 /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(79): PDO->prepare('select teams....', Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(352): Doctrine\DBAL\Driver\PDOConnection->prepare('select teams....')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(685): Illuminate\Database\Connection->Illuminate\Database\{closure}('select teams....', Array)
```

### Steps To Reproduce:

app\Models\User.php
```
    const CREATED_AT = 'create_at';
    const UPDATED_AT = 'last_modified_at';
```

My workaround is just disabled the withTimestamp
```
// originally
public function teams()
    {
        return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
                        ->withPivot('role')
                        ->withTimestamps()
                        ->as('membership');
    }
```

```
// become
public function teams()
    {
        return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
                        ->withPivot('role')
                        ->as('membership');
    }
````

Any better workaround would be appreciate, or where's exactly part that better to adapt ?

**Comment by derekmd** [comment]
1. Although https://laravel.com/docs/8.x/eloquent-relationships#retrieving-intermediate-table-columns doesn't cover it, the `withTimestamps()` method allows two arguments for custom timestamp column names:
https://github.com/laravel/framework/blob/7e0e0d0c3dec9f0978d4e616681d86c5749c0b00/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L1250-L1258

   ```php
   public function teams()
   {
       return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
           ->withPivot('role')
           ->withTimestamps('create_at', 'last_modified_at')
           ->as('membership');
   }
   ```
2. This GitHub repository's issues are for laravel/framework bugs. The Laravel Jetstream package has a separate repo for reporting bugs: https://github.com/laravel/jetstream/issues Since this is a question about customizing Jetstream's scaffolding, support channels like [Laracasts Forums](https://laracasts.com/discuss), [Laravel.io Forums](https://laravel.io/forum), [StackOverflow](https://stackoverflow.com/questions/tagged/laravel), etc. are more appropriate.

**Comment by driesvints** [comment]
Thanks @derekmd
