### ISSUE TITLE
How can we access the value inside the callback of Rule::when(), when the field is an array.

### ISSUE THREAD

**Issue by itxshakil** [laravel/framework#38865]
- Laravel Version: 8..55.0
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
**How can we access the value inside the callback of Rule::when(), when the field is an array.**

- The problem is we don't know the iteration(key), so we can't access it from request.

I guess we may pass the current value as the second parameter to the callback.

`$validator = Validator::make($request->all(), [`
`     'openings.*.from' => ['required_with:openings.*.id', 'date_format:H:i'],`
`     'openings.*.to' => ['required_with:openings.*.id', Rule::when(function($a){`
`              //  Need the current value for conditional check`
`         },['date_format:H:i']), 'after:openings.*.from'],`
 ` ]);`

If we wanted to add validation(date_format:H:i) on the basis of the current value of openings's to.

But I can not access the value of current openings to.

_Originally posted by @itxshakil in https://github.com/laravel/framework/issues/38361#issuecomment-920947533_

### Steps To Reproduce:
- Add an array field for validation (For eg. : request()->validate([ 'abc.*' => ['required'] ]);
-  Try to add conditional validation on the basis of the value of field.

**Comment by derekmd** [comment]
The `Rule::when()` closure argument is only given the `$validator->getData()` / `$request->all()` payload so the nested array key context isn't available. The code that invokes the closure also doesn't have that context available since the `Rule::when()` filter happens before the request's nested array payload is traversed during validation.

https://github.com/laravel/framework/blob/1b2107e35fe5fbfa2fb0a130044d63ffce680e4a/src/Illuminate/Validation/ValidationRuleParser.php#L285-L307

---

> // Need the current value for conditional check

This is the most important part of your question that has been excluded. What is the conditional you need to check? Some other validation features may cover the requirement.

1. Use one of the `required_with*` [rules](https://laravel.com/docs/8.x/validation#rule-required) such as `required_with_all:openings.*.id,openings.*.from`
2. Create a `ValidatorAwareRule` rule object that will be given the nested array key being validated and can also access the full data payload: https://laravel.com/docs/8.x/validation#using-rule-objects

   ```php
   $validator = Validator::make($request->all(), [
       'openings.*.from' => [
           'required_with:openings.*.id',
           'date_format:H:i'
       ],
       'openings.*.to' => [
           'required_with:openings.*.id',
           new DateRangeEndRule,
       ],
   ]);
   ```

   ```php
   use Illuminate\Contracts\Validation\Rule;
   use Illuminate\Contracts\Validation\ValidatorAwareRule;

   class DateRangeEndRule implements Rule, ValidatorAwareRule
   {
       public function setValidator($validator)
       {
           $this->validator = $validator;
       }

       public function passes($attribute, $to)
       {
           // $attribute is 'openings.0.to', 'openings.1.to', etc.

           $key = preg_replace('/\.to$/', '.from', $attribute);
           $from = $this->validator->getData()[$key] ?? null;

           if (from === null) {
                return true;
           }

           // compare $from and $to, then conditionally run validation
           // for 'date_format:H:i' & 'after:openings.*.from'
       }

       public function message()
       {
           // ...
       }
   }
   ```

**Comment by itxshakil** [comment]
Thanks, it solved the issue.
I was not aware that the code that invokes the closure also doesn't have that context available since the Rule::when() filter happens before the request's nested array payload is traversed during validation.

**Comment by driesvints** [comment]
Thanks @derekmd
