### ISSUE TITLE
Cannot type-hint dependencies in prepareForValidation()

### ISSUE THREAD

**Issue by ol1s** [laravel/framework#38906]
### Description:

- Laravel Version: 8.50.0
- PHP Version: 7/4/23
- Database Driver & Version:

In Laravel [form requests](https://laravel.com/docs/8.x/validation#form-request-validation) the `authorize()` method allows dependencies to be injected from the container by type-hinting the method args. However, the `prepareForValidation()` method does not allow this and throws the following error:

```php
Method 'App\Http\Requests\ExampleRequest::prepareForValidation()' is not compatible 
with method 'Illuminate\Foundation\Http\FormRequest::prepareForValidation()'
```

### Steps To Reproduce:

It would be useful to to inject dependencies into a form request class during the `prepareForValidation()` method. 

For example:

```php
class ExampleRequest extends FormRequest
{
    private ExampleModel $resource;

    public function prepareForValidation(ExampleRepository $repository)
    {
        $resourceId = $this->route('resourceId');
        $resource = $repository->find($resourceId);

        if (!$resource) {
            throw new NotFoundHttpException();
        }

        $this->resource = $resource;
    }

    public function authorize()
    {
        if ($this->user()->can('update', $this->resource)) {
            return true;
        }

        return false;
    }
}
```

**Comment by derekmd** [comment]
From the `prepareForValidation()` [docs](https://laravel.com/docs/8.x/validation#preparing-input-for-validation):
> If you need to prepare or sanitize any data from the request before you apply your validation rules...

This example is loading dependencies for authorizing the request, unrelated to validation, and it uses `prepareForValidation()` like a constructor/setter. Shouldn't that resource dependency come through the `authorize()` arguments that support method injection? Global helper `app()` is also an option:

```php
class ExampleRequest extends FormRequest
{
    private $resource;

    public function authorize(ExampleRepository $repository)
    {
        $this->resource = $repository->findOrFail($this->resourceId);
        // $this->resource = app(ExampleRepository::class)->findOrFail($this->resourceId);

        return $this->user()->can('update', $this->resource);
    }
}
```

---

`FormRequest` already allows method injection in `validator()`, `authorize()`, and `rules()`. A `prepareForValidation()` change would have to be introduced in 9.x since it breaks the current method signature:

https://github.com/laravel/framework/blob/21de9d5e8a2db323c9273d67358678158b7ed549/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php#L15-L17

https://github.com/laravel/framework/blob/21de9d5e8a2db323c9273d67358678158b7ed549/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php#L32-L40

```php
trait ValidatesWhenResolvedTrait
{
    public function validateResolved()
    {
        if (method_exists($this, 'prepareForValidation')) {
            return $this->container->call([$this, 'prepareForValidation']);
        }

        // ...
    }

    // empty prepareForValidation() definition removed

    // Since $this->container doesn't exist on the trait, need to assume
    // the trait-using class has this method? Anti-pattern time.
    abstract public function setContainer(Container $container);
```

I think this will require a stronger example if such a breaking change were to be introduced. Either way, this is a feature request and not a bug report: https://github.com/laravel/framework/discussions

**Comment by ol1s** [comment]
Thanks @derekmd for your reply.

My take-home from your response......move the NotFoundHttpException logic into the repository and happily load the resource in the `authorize()` method of the form request.
