### ISSUE TITLE
shouldSend does not get called or change outcome of "assertNotSent" or other notification assertions

### ISSUE THREAD

**Issue by mrpritchett** [laravel/framework#38909]
- Laravel Version: 8.61.0
- PHP Version: 8.0.3
- Database Driver & Version: mysql 5.7

### Description:
It looks like the PR:

https://github.com/laravel/framework/pull/37930#issue-684438049

that gave us `shouldSend()` on `Notification` does not give us that behavior when checking assertions like `assertNotSent`. 

### Steps To Reproduce:
- Create a new notification
- Set `shouldSend` to return false
- Create a test where that notification should send without `shouldSend` and try to assertNotSent based on `shouldSend`.
- Test fails because notification is sent regardless of shouldSend

**Comment by gbradley** [comment]
There is some slightly mixed use of "sent" in the Notification classes. The `assertSent`, `assertNotSent` methods on the Notification facade more accurately assert the notification was / not passed to the ChannelManager via `notify()`, `send()` or `sendNow()`.

What it doesn't assert is that the underlying `Illuminate\Notifications\NotificationSender` class decided to actually send the notification to the relevant channel(s), which happens in `shouldSendNotification()`. The same behaviour existed prior to #37930 when listening for the `NotificationSending` event and returning false.

I do agree this is confusing & happy to submit a PR to include the `shouldSendNotification()` check inside the assertion code, if someone from the team thinks this is the right way to go (rather than creating separate assertions on the NotificationSender itself).

**Comment by mrpritchett** [comment]
I'd be happy to submit a PR, but would like to get some team guidance on if this is something that is desired or if another solution is preferred.
