### ISSUE TITLE
Relation can return first element from table instead real related model.

### ISSUE THREAD

**Issue by votintsev** [laravel/framework#38926]
- Laravel Version: 8.61.0
- PHP Version: 7.4.21
- Database Driver & Version: -

### Description:
Relation can return first element from table instead real related model. It is can occur when relation building inside another relation query. Abstract example:

```
Post::whereHas('myRelation')->get();

class Post extends Model
{
    public function myRelation()
    {
       auth()->user()->relation->id;
       return $this->hasOne...;
    }
}
```

`auth()->user()->relation` inside `myRelation` will return first element of users table, and query will be like: `select * from "users" limit 1`

But if preload it will work correctly:
```
auth()->user()->relation->id;
// will work, because loaded
Post::whereHas('myRelation')->get();
```

Of course, we may not use such code, but it's definitely unexpected behavior. It is related to this method: https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Database/Eloquent/Relations/Relation.php#L96-#L110 after ` static::$constraints = false;` where statement will remove for all relations.

### Steps To Reproduce:
I forked and created test. So just copy test: https://github.com/votintsev/framework/commit/fbf613f15876761783cd66984529b605b572fc4e and run it
```php ./vendor/bin/phpunit tests/Integration/Database/EloquentHasOneWrongLoadTest.php```

**Comment by derekmd** [comment]
1. Relationship methods should avoid using model state when building the relation query. Instance state (`$this->column`) breaks eagerloading `load()` / `with()` and global state (`auth()->user()->relation`) can be affected by constraints on `has()`, etc. which is the issue you're encountering. https://laravel.com/docs/8.x/eloquent-relationships avoids such examples as those snippets only reference `$this` to call the query-building methods.

   The constraint would need to be applied at runtime:

   ```php
   $posts = Post::has(
       'attachment.signature',
       fn ($query) => $query->where('member_id', auth()->id())
   )->get();
   ```
2. This can be broken down further into per-model scopes:
   ```php
   class Post extends Model
   {
       public function attachment()
       {
           return $this->hasOne(Attachment::class);
       }

       public function signedAttachment()
       {
           return $this->attachment()->signed();
       }
   }
   ```

   ```php
   class Attachment extends Model
   {
       public function post()
       {
           return $this->belongsTo(Post::class);
       }

       public function signature()
       {
           return $this->hasOne(Signature::class);
       }

       public function scopeSigned($query)
       {
           $query->has('signature', fn ($query) => $query->ofCurrentUser());
       }
   }
   ```

   ```php
   class Signature extends Model
   {
       public function scopeOfCurrentUser($query)
       {
           $query->where('member_id', auth()->id());
       }
   }
   ```

   ```php
   $posts = Post::has('signedAttachment')->get();
   ```
3. Ignoring the scopes above, those model classes can also be used with a get mutator on the member class to get that user's signed posts:
   
   ```php
   class Member extends Model
   {
       public function attachments()
       {
           return $this->hasManyThrough(Attachment::class, Signature::class);
       }

       public function getPostsAttribute()
       {
           return $this->attachments->pluck('post');
       }
   }
   ```

   ```php
   $posts = auth()->user->posts;
   ```

4. Instead of a get mutator, https://github.com/staudenmeir/eloquent-has-many-deep can be used on the above class to define a 3-deep `Member@posts()` relationship.
5. Or filter signatures by global scope for the current logged in user so they can never see other members' signatures:

   ```php
   <?php
   
   namespace App\Scopes;
   
   use Illuminate\Database\Eloquent\Scope;
   
   class CurrentUserScope implements Scope
   {
       public function apply($builder, $model)
       {
           $builder->where('member_id', auth()->id());
       }
   }
   ```

   ```php
   // put in the controller action for a single request
   // or Signature::booted() for every request
   Signature::addGlobalScope(new CurrentUserScope);
   ```

   I believe this query would then only returns posts for the logged in user:

   ```php
   $posts = Post::has('attachment.signature')->get();
   ```

**Comment by votintsev** [comment]
@derekmd Thank you, for such a detailed answer and advices! Very clarifying. Thank you for taking the time to dive into this. Appreciate it.

**Comment by driesvints** [comment]
Thanks @derekmd
