### ISSUE TITLE
Redis Cluster does not have support for pipeline (Job batch)

### ISSUE THREAD

**Issue by 4ice** [laravel/framework#38923]
- Laravel Version: 8.61.0
- PHP Version: 8.0.8
- Database Driver & Version: Clustered Redis v6.0.5

### Description:
When trying to use job Batches  to dispatch a series of jobs to a redis cluster queue, an 500 exception is thrown.

```
Call to undefined method RedisCluster::pipeline() {"userId":2,"exception":"[object] (Error(code: 0): Call to undefined method RedisCluster::pipeline() at /project/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:402
```

### Steps To Reproduce:

* Setup redis cluster for queue management according to these instructions: https://laravel.com/docs/8.x/redis#clusters
* try to dispatch jobs as a batch according to these instructions: https://laravel.com/docs/8.x/queues#job-batching

**Comment by 4ice** [comment]
For further information regarding phpredis, redis cluster and pipeline, it can be found here: https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#pipelining

**Comment by derekmd** [comment]
Given the "phpredis/phpredis" package doesn't support pipelines on a cluster setup, there doesn't seem to be much Laravel can do except:

* add a callout in the documentation
* throw a custom `PipelineUnsupportedException`, although the current exception about `RedisCluster::pipeline()` might communicate enough when paired with a docs callout.

Have you tried configuring "predis/predis" instead of "phpredis/phpredis"?

---

"phpredis/phpredis" docs state:

> It would be possible to implement [pipelining] support as an option if there is demand for such a feature.

So anyone that reaches this issue can send their upvote to https://github.com/phpredis/phpredis/issues/1910

**Comment by 4ice** [comment]
> Have you tried configuring "predis/predis" instead of "phpredis/phpredis"?
I triend to switch to predis, but I got stuck in this issue: https://github.com/predis/predis/issues/695 and I gave up on that approach. 


I guess Laravel could have override the pipeline-function in `PhpRedisClusterConnection.php` and just execute the command instead of executing it via the pipeline?

**Comment by driesvints** [comment]
This is a feature request so I'm moving this to discussions.
