### ISSUE TITLE
Safari does not accept the default date format returned by Laravel

### ISSUE THREAD

**Issue by cmmartin** [laravel/framework#38929]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0.25

### Description:
When returning JSON to the client for use in Vue/React/etc, the date format returned is considered invalid by Safari

### Steps To Reproduce:

1) Convert any Eloquent model or collection with a timestamp to JSON
2) Take the timestamp, for example `2021-03-12 21:03:32`, open the Safari javascript console and paste `new Date('2021-03-12 21:03:32')` and you'll see it returns `Invalid Date`

Safari seems to be the only browser that doesn't support this format. It requires the empty space to be replaced with `T`. So `2021-03-12 21:03:32` should be `2021-03-12T21:03:32`

How is everyone using a front-end javascript framework handling this? I know I can cast the dates in my model, but it's tedious and error prone to copy the casting logic to each model. Is there a way to globally set the date format anytime a date is serialized to JSON?

**Comment by derekmd** [comment]
https://laravel.com/docs/8.x/eloquent-mutators#date-casting-and-timezones

Use `$model->toArray()`, `$model->toJson()`, or [API resources](https://laravel.com/docs/8.x/eloquent-resources) to send PHP payloads to JavaScript. Laravel will automatically cast date columns to UTC ISO-8601 date strings (including the `T` character) that JavaScript's `Date` constructor can handle.

Model columns `created_at` and `updated_at` are cast to dates by default, then the `$casts` property is used for the additional date columns.

---

```
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

```php
App\Models\User::first()->toArray();
// => [
//      "id" => 1,
//      "name" => "Foo",
//      "email" => "foo@bar.com",
//      "email_verified_at" => "2021-09-24T00:03:02.000000Z",
//      "created_at" => "2021-09-16T22:28:13.000000Z",
//      "updated_at" => "2021-09-16T22:28:13.000000Z",
```

---

API resources will convert `Carbon` objects to UTC ISO-8601, including the custom `timestamp` key below:

```php
namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'name' => $this->name,
            'email' => $this->email,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'timestamp' => now(),
        ];
    }
}
```

```json
{
  "data": {
    "name": "Foo",
    "email": "foo@bar.com",
    "created_at": "2021-09-16T22:28:13.000000Z",
    "updated_at": "2021-09-24T00:03:20.000000Z",
    "timestamp": "2021-09-24T00:13:31.992710Z"
  }
}
```

---

Otherwise you'll need to use a 3rd party JS date library, some recommendations are here: https://momentjs.com/docs/#/-project-status/recommendations/ e.g., https://date-fns.org/v2.24.0/docs/parse

**Comment by cmmartin** [comment]
Thanks so much for the detailed response. I now realize that Laravel is not doing the formatting on these and this is just the MySQL datetime format being returned. So it makes sense that I need to cast them myself in their models

**Comment by lk77** [comment]
Hello,

i'm doing that :

```
parseDate(date) {
                const parsed = Date.parse(date);

                if (!isNaN(parsed)) {
                    return parsed;
                }

                // safari
                return Date.parse(date.replace(/-/g, '/').replace(/[a-z]+/gi, ' '));
            },
```
