### ISSUE TITLE
Using https://laravel.build does not work if the current path contains spaces

### ISSUE THREAD

**Issue by NiclasvanEyk** [laravel/framework#39182]
- Laravel Version: 8.64.0
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:

Since https://laravel.build is not open source (at least I did not find it), I am reporting it here instead.

The recommended way of creating a new Laravel application using

```
curl -s "https://laravel.build/example-app" | bash
``` 

does not work the path to the current directory contains spaces, due to an unquoted string in the returned shell script.

### Steps To Reproduce:

Go to a folder containing spaces
```
mkdir "$HOME/I contain Spaces" && cd "$HOME/I contain Spaces"
```

Try to create a new Laravel app using the recommended approach
```
curl -s "https://laravel.build/example-app" | bash
```

This leads to
```
Unable to find image 'contain:latest' locally
docker: Error response from daemon: pull access denied for contain, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
bash: line 16: cd: example-app: No such file or directory
```

### Solution

Current output: https://laravel.build/example-app
When binding the current directory to `/opt` inside the container, the output of `$(pwd)` is not quoted. This is why spaces can lead to the command being invalid and the above error.

Solution:
```bash
# ...

docker run --rm \
    -v "$(pwd)":/opt \      # <-- The $(pwd) is now quoted
    -w /opt \
    laravelsail/php80-composer:latest \
    bash -c "laravel new example-app && cd example-app && php ./artisan sail:install --with=mysql,redis,meilisearch,mailhog,selenium"

# ...
```

**Comment by driesvints** [comment]
Thanks for reporting this. I've sent in a PR to fix this. I'll get back to here when it's live.

**Comment by driesvints** [comment]
We merged that fix and it should be live soon. Thanks for reporting.

**Comment by zlatevbg** [comment]
@driesvints
I experience similar problem when the Laravel application directory path contains dot character like:
`curl -s https://laravel.build/laravel.test | bash`

the output from the bash shell is:
```
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
```
because the server is returning 404 Error.

If I clear my browser cache the first time I open this URL [https://laravel.build/laravel.test](https://laravel.build/laravel.test) in my browser I'm redirected to [https://laravel.build/](https://laravel.build/) and get 404 Error.

However If I first open the following URL [https://laravel.build/laravel](https://laravel.build/laravel) and then try to open [https://laravel.build/laravel.test](https://laravel.build/laravel.test) in my browser I'm redirected to [https://laravel.build/laravel](https://laravel.build/laravel)

![Untitled-1](https://user-images.githubusercontent.com/8568201/155695260-7325434e-a470-409a-b50a-f194c07a8a8f.jpg)

**Comment by driesvints** [comment]
@zlatevbg I'll have a look soon.

**Comment by driesvints** [comment]
I've sent a PR for a more descriptive message and to fix the redirect loop: https://github.com/laravel/sail-server/pull/9. However, I cannot solve the bash error message. Therefor, I've opted to clarify allowed characters in the docs: https://github.com/laravel/docs/pull/7749 as you cannot use dots in an app name.
