### ISSUE TITLE
`escapeWhenCastingToString` is visible when dumping collection items

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#39450]
- Laravel Version: 8.68.1
- PHP Version: 8

### Description:
I just updatad laravel and saw this property on the collection dump :

```php

dd(collect([1, 2]));

```

![image](https://user-images.githubusercontent.com/53290883/139905827-6c8f6b73-8f20-4ebc-81dd-e624bd901b8c.png)

is it intended?

**Comment by DarkGhostHunter** [comment]
Intended #39319

**Comment by florentpoujol** [comment]
Related to this there is a probably unintended deprecation : passing a collection as bindings of the `whereRaw()` method isn't supported any more because it will insert `false` as the last binding and thus cause a `"PDOException(code: HY093): SQLSTATE[HY093]: Invalid parameter number"` exception.

Steps to reproduce : `User::whereRaw('id in (?)', new Collection([1]))->get();`

Executing `User::whereRaw('id in (?)', new Collection([1]))->dd()`outputs : 
```
"select * from `users` where id in (?) and `users`.`deleted_at` is null"
array:2 [
  0 => 1
  1 => false
]
```

This is because the method just cast the passed bindings to array, whatever type it is.  
A priori, an easy fix would be to not do that when the bindings are a collection and instead cal `toArray()` or `all()` on it.

**Comment by DarkGhostHunter** [comment]
You should make a new issue.
