### ISSUE TITLE
Schema:dump not working when working with multiple databases

### ISSUE THREAD

**Issue by ZekLouis** [laravel/framework#39476]
- Laravel Version: 8.69.0
- PHP Version: 8.0.10
- Database Driver & Version:
2 databases MySQL 5.7

### Description:

Hello, we're seeing an issue when we're trying to squash our migrations. 

We have 2 databases, our main db and our data db. When we're running migrations, we're precising the database using `Schema::connection('data')->table(...` so we can create the table where we want. This end's up having 1 migrations table inside our main db (which is perfect).

It looks like we can't run `php artisan schema:dump --prune` for 2 db at the same time. So we decided to run it twice using the `--database=` parameter. But this command is looking for a `migrations` table inside both db, and we don't have / need a `migrations` table inside our data db.

It seems to be working properly if we create a fake `migrations` table inside our data db (which is very dirty imo).

### Steps To Reproduce:

1. Set up 2 databases called "db-main" and "db-data".
2. Create migrations and tables for "db-main" like "users"
3. Create migrations and tables for "db-data" like "data-users" (using ::connection)
4. Run your migrations
5. Run `php artisan schema:dump --prune --database=db-main` (this should work)
6. Run `php artisan schema:dump --prune --database=db-data` (this should fail because it's gonna be looking for the migrations table)

**Comment by driesvints** [comment]
This is by design. Both connections need a migrations table.

**Comment by AntoninG** [comment]
I had the same problem, thank you for the answer !

But there is some things that are still not clear to me and I can't find the right documentation page clarifying them.

1. The command creating the `migrations` table is `php artisan migrate`. I already use it and this never created any migrations table in my second connection. How to make this table creation implicit ? 
2. If both connections need a migrations table, then I guess I am supposed to run `php artisan migrate --database=dbX` for both my connections. Does this use the property `$connection` of the migration file to guess if the migration is related to the database provided ? Or does it execute it anyway ? Because I have some migration files with the property set to my second connection, and I don't have any `migrations` table, but maybe it's because I use the simplest version of the command `php artisan migrate` ?

**Comment by AntoninG** [comment]
Because [the documentation says](https://laravel.com/docs/8.x/migrations#setting-the-migration-connection) to use the property `protected $connection = 'pgsql';` to set 

> The database connection that should be used by the migration.

But I use it and it never considers that the value of the property is supposed to be the default connection within the migration file. Is it because this is not its purpose ? Like it's supposed to be used in addition to the command's `--database` parameter ?
