### ISSUE TITLE
Replace swiftmailer/swiftmailer package with symfony/mailer

### ISSUE THREAD

**Issue by NikolaKG80** [laravel/framework#39766]
- Laravel Version: 8.73.2
- PHP Version: 8.0.13
- Database Driver & Version: MariaDB - 10.5.12

### Description:
When I try to `run composer update`, I get the following message: 

> Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

### Steps To Reproduce:
Type `composer update` into the console

**Comment by driesvints** [comment]
https://github.com/laravel/framework/issues/39737

**Comment by NikolaKG80** [comment]
Sorry for creating a duplicate, Google Search came up empty for this issue.

On the other hand, [Release Notes](https://laravel.com/docs/8.x/releases) say that Laravel 8 will be actively supported until July 26th, 2022.

I think that replacing abandoned projects should be a part of active support. How can I explain to my clients that Laravel is the best framework, with the best support, if it uses abandoned packages?

**Comment by X-Coder264** [comment]
Replacing Swift Mailer with Symfony Mailer introduces breaking changes to Laravel, the list of which can be seen in the PR for Symfony Mailer -> https://github.com/laravel/framework/pull/38481

Breaking changes can't be done on minor versions (those are allowed only on major versions) so there's nothing the Laravel team can do here about that.

Besides it's not like Swift Mailer magically stopped working all of a sudden just because Symfony Mailer was released. Swift Mailer had little development going on for years as it's an old and stable/mature library. And Laravel 9 is gonna be released on January 25th which is just two months away.
