### ISSUE TITLE
getOriginal and getRawOriginal returns incorrect values then used within Observer that has afterCommit enabled

### ISSUE THREAD

**Issue by tarkis** [laravel/framework#39943]
- Laravel Version: 8.75.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL Server 8.0.26

### Description:
If you update a Model in transaction and later call `getOriginal` or `getRawOriginal` within Observer that has `public $afterCommit = true;` you are presented with incorrect values.

### Steps To Reproduce:

1. Create Observer

```php
<?php

namespace App\Observers;

use App\Models\User;

class UserObserver
{
    public $afterCommit = true;

    public function updated(User $user)
    {
        dump("wasChanged('name') value in observer - " . $user->wasChanged('name'));
        dump("getChanges()['name'] value in observer - " . $user->getChanges()['name']);
        dump("getOriginal('name') value in observer - " . $user->getOriginal('name'));
        dump("getRawOriginal('name') value in observer - " . $user->getRawOriginal('name'));
    }
}
```

2. Register Observer

```php
User::observe(UserObserver::class);
```

3. Run a script that updates the value in transaction

```php
$user = User::firstOrCreate(['name' => 'First', 'email' => 'test@test.localhost', 'password' => bcrypt('password')]);

DB::transaction(function () {
    User::first()->update(['name' => 'Transaction']);
});

$user->delete();
```
---
The outcome of this test is:
```shell
"wasChanged('name') value in observer - 1"
"getChanges()['name'] value in observer - Transaction"
"getOriginal('name') value in observer - Transaction"
"getRawOriginal('name') value in observer - Transaction"
```
getOriginal('name') or getRawOriginal('name') should return "First" instead of "Transaction". 

If you remove `public $afterCommit = true;` from an Observer or run update outside the transaction it all works:
```shell
"wasChanged('name') value in observer - 1"
"getChanges()['name'] value in observer - Transaction"
"getOriginal('name') value in observer - First"
"getRawOriginal('name') value in observer - First"
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by elliottpost** [comment]
I am able to replicate this issue @tarkis  and @driesvints. Basically `isDirty()` returns false when using `$afterCommit` making it difficult to use observers for `updating()` because you have no way of knowing what the previous value was unless you do not use a transaction. If you do not use a transaction and the updates fail, then you are triggering events that should not be triggered.

**Comment by driesvints** [comment]
I'll talk to the team about this but it seems like an unsolvable issue to me. Transactions and these events seem incompatible.

**Comment by elliottpost** [comment]
@driesvints thank you! I am currently considering a work around by removing the updating() method from the observer and handing those events in a separate event listener with $afterCommit set to false and making that event queueable. This would require some sort of flflag in the database to determine if the transaction was successful and whether or not it should process or cancel the queued tags, but that can be solved with a history table or something similar. I'd be curious if anyone has any thoughts on a good/scalable approach for that.

As for the observer, I think this only effects the updating method and the rest work fine/as expected with events and afterCommit set to true and that could be left as-is.

**Comment by taylorotwell** [comment]
This behavior, while maybe unintuitive at first glance, is expected I think. By stating that the listener should run after all database transactions have committed you have deferred the normal execution of these events to a later time than they would normally run. Even the `updating` event is now actually being run after the model has been full persisted to the database. That is why the `getOriginal` value returns the "updated" value - the model has been persisted to storage and is now considered in a "clean" state where the "updated" value is now the original value - just like if you queried the model fresh from the database.

**Comment by n8rowley** [comment]
I think part of the reason it is unintuitive is because the `getChanges` (and `wasChanged`) method tracks changes from the last time a model was saved (in the current request cycle). Since the observers are called in the same request cycle, `getChanges` works just fine.  _Intuition_ says that that there should be a way to access the values before the change, and `getOriginal` sounds like something that would do the trick, though it's behavior wasn't meant for dealing with models that have been saved. Though `getOriginal` isn't the answer, there should definitely be a way to get the pre-saved values.

`getChanges` returns an associative array where the keys are the attributes that changed and the values are the new attributes. Having the values be the newly updated ones is redundant. We have the newly updated values available on the model. Instead, if `getChanges` returned the old values, we would have access to what attributes changed and what their values were before they were saved.
