### ISSUE TITLE
Specifying $collects in any Resource Collection breaks the response

### ISSUE THREAD

**Issue by ggeorgiadis** [laravel/framework#40360]
- Laravel Version: 8.78.0
- PHP Version: 8.0.10

### Description:

Specifying the `$collects` property in a Resource Collection throws an error when trying to create a response.

### Steps To Reproduce:

- Create a User Resource Collection and set the $collects property
```php
<?php

namespace App\Http\Resources;

use App\Models\User;
use Illuminate\Http\Resources\Json\ResourceCollection;

class UserResourceCollection extends ResourceCollection
{

    public $collects = User::class;

    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return parent::toArray($request);
    }
}
```

- Return this collection in an endpoint
```php
Route::get('/users', function () {
    return new \App\Http\Resources\UserResourceCollection(\App\Models\User::all());
})->name('users');
```

- Expected response would be a 200 response with the json payload
- The actual response is 500 and the following is logged:
```
BadMethodCallException: Call to undefined method App\Models\User::jsonOptions()
```

The repository which includes the failing test [https://github.com/ggeorgiadis/laravel-json-options-bug-report](https://github.com/ggeorgiadis/laravel-json-options-bug-report)

**Comment by Sunhat** [comment]
I believe the $collects is meant to point to an individual Resource Class, not a Model class.

I may be wrong.

**Comment by mrcat323** [comment]
Hi, you shouldn't write there the model name, that's is used for custom __Resource representation__ in a case if that's important. 
![image](https://user-images.githubusercontent.com/23054662/149274381-405a5f7e-bc1b-4cce-a564-ec353223adf5.png)

Sorry to refer you back to documentation, but that's it, you have to use Resource class instead of Model one. That's used (resource class here), for custom field and its data representation

**Comment by ggeorgiadis** [comment]
Oh I see it now. It can be misleading tbh because the resource has the same name as the model, and the rest of the documentation appends `Resource` to all resources :D . So it's really easy to miss if you don't look close to the `use` of this example. 

Thanks for the responses

**Comment by Sunhat** [comment]
@ggeorgiadis Can we consider this to still be an issue? In the screenshot provided, you can see 

```
public $collects = Member::class
```

1. There's no example of Member or import of it
2. Member sounds like a Model, not a MemberResource

Can we consider this a bug/issue with the documentation as the example is somewhat unclear?

**Comment by bert-w** [comment]
I think this issue is valid. Something has definitely changed between versions 8.64.0 and 8.80.0. I am getting the exact same error `Call to undefined method SomeModel:jsonOptions()`. 

I traced it down to https://github.com/laravel/framework/commits/8.x/src/Illuminate/Http/Resources/CollectsResources.php (Jan 3 + Jan 5 2022 commits)

I am using many `$collects` properties in my ResourceCollections and have always pointed them to my Eloquent models which worked perfectly. I did not have to create a Resource in many cases (nor do I think that is necessary if you are going to use the exact `ToArray()` representation of the Eloquent model).

Imho it should work with regular Eloquent models. I can fix my local issue by just defining a `public function jsonOptions() { return 0; }` on my Model but it would be nice if this could be the default (or rework the `src/Illuminate/Http/Resources/CollectsResources.php` trait so it can be applied to the Eloquent Model class, because currently it also needs a `$collects` property for it to work).

@ggeorgiadis  can you please reopen this issue?

**Comment by ggeorgiadis** [comment]
> I think this issue is valid. Something has definitely changed between versions 8.64.0 and 8.80.0. I am getting the exact same error `Call to undefined method SomeModel:jsonOptions()`.
> 
> I traced it down to https://github.com/laravel/framework/commits/8.x/src/Illuminate/Http/Resources/CollectsResources.php (Jan 3 + Jan 5 2022 commits)
> 
> I am using many `$collects` properties in my ResourceCollections and have always pointed them to my Eloquent models which worked perfectly. I did not have to create a Resource in many cases (nor do I think that is necessary if you are going to use the exact `ToArray()` representation of the Eloquent model).
> 
> Imho it should work with regular Eloquent models. I can fix my local issue by just defining a `public function jsonOptions() { return 0; }` on my Model but it would be nice if this could be the default (or rework the `src/Illuminate/Http/Resources/CollectsResources.php` trait so it can be applied to the Eloquent Model class, because currently it also needs a `$collects` property for it to work).
> 
> @ggeorgiadis can you please reopen this issue?

I do not believe it is an issue, but as @Sunhat mentioned, the documentation could be improved. After reading the documentation more carefully, the `collects` field is intended to collect `Resource` classes instead of Models.

**Comment by allanlaal** [comment]
the class set by `collects` also needs to be an instance of `JsonResource` class
