### ISSUE TITLE
Getting "Data missing" exception when setting date attribute

### ISSUE THREAD

**Issue by tflori** [laravel/framework#40737]
I know you don't like it not to use your template but I'm a busy man and this issue is in every version.

When setting an attribute that is casted to date (-time) and the value is before 1000-01-01 AD carbon throws an error because it checks with the following function if it is a "standard date format"

https://github.com/laravel/framework/blob/411d5243c58cbf12b0fc89cab1ceb50088968c27/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1327

The standard date format allows years before 1000 - so every format should be valid. You can try this with Carbon or even vanilla PHP:

```php
$date = \DateTime::createFromFormat('Y-m-d', '97-10-10');
$date = \DateTime::createFromFormat('Y-m-d', '1-1-1');
```

I'm very wondered why you accept single digits for month and date but not for year.

The correct regular expression should be:
```php
return preg_match('/^(\d{1,4})-(\d{1,2})-(\d{1,2})$/', $value);
```

**Comment by driesvints** [comment]
Resubmit this with a filled out template and don't ignore it.

**Comment by tflori** [comment]
@driesvints you misunderstood me: I don't care if you fix it in your framework. It's 1m to fix it in all my models and 5m to write an issue. I will not spend 10m to fill your template.

Instead of appreciating that someone is pointing out an issue you demand him to spend even more time with it...

**Comment by driesvints** [comment]
Okay I'll try to be a bit pragmatic here: 

We do appreciate you pointing this out, however, this is not the right place to do this. As the issue templates indicate, this tracker is only for bugs in the framework. When you post an issue we expect you to fill out the issue template as it helps us to debug it more efficiently. 

The problem you highlight is definitely valid but better ways to do this would be:

- Send in a PR to the docs to note the specific behaviour 
- Send in a PR to the framework to adjust the behaviour (to master for breaking changes, or 8.x for non-breaking changes)
- Do a blog post or tweet about this to inform others
- Post in the Discussions section about this

The thing that bothers me with this is:

> I know you don't like it not to use your template but I'm a busy man and this issue is in every version.

You admit you know that we don't like that issues are posted without a template and yet still proceed to do so. You also note that you're busy but completely disregard that we are as well. You also ignore the fact that all of Laravel is provided to you for free and that we maintain this repo free of charge. We try to do our utmost best at making sure that everything stays stable and fix broken things while also providing the community with new features. One of the few things we ask in return is to follow our processes when you submit issues or want to provide feedback so we can stay productive and help everyone as well as possible. We simple don't have the bandwidth to answer/help everyone and that's why we direct support questions to other support channels such as the forums and Discord. 

> Instead of appreciating that someone is pointing out an issue you demand him to spend even more time with it...

We don't demand anything. The only thing we ask is that you use the proper channels which are clearly indicated in our issue templates and documentation.

I do appreciate you pointing the above out but wish you'd be more considerate of the work that we do. We're not inconsiderate or demanding just because we ask you to follow our guidelines.

Hopefully next time we can resolve this in a better way 👍
