### ISSUE TITLE
[Queue] Not deserializing a model with constrained relations eager loaded

### ISSUE THREAD

**Issue by samdharris** [laravel/framework#40804]
- Laravel Version: 8.82.0
- PHP Version: 8.0.13
- Database Driver & Version: MySQL v8.0.27

### Description:
When you provide a model (or collection of models) with an eager loaded relationship that was constrained in a query, said data isn't serialized and upon deserialization loses the eager loaded data. This means that if you attempt to access said relationship in a queue job, it will load perform a lazy load and load in all the related data rather than what you had previously constrained.

### Steps To Reproduce:
1. Have a controller action that performs an eloquent query that eager loads a relation with some sort of constraint
2. Have a queue job that accepts data from step 1 as its constructor and the handle method log that data out
    1. **Expected** it should restore the model and subsequent models correctly

Bug Replication Repository: https://github.com/samdharris/laravel-queue-serialization-bug-replication

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. **Can you please recreate a repository with the command below**, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
To be honest, I think this is a limitation and should probably be documented.

**Comment by driesvints** [comment]
It seems this is indeed not supported. Last time someone attempted a PR it caused quite a few breaking changes. We'll get this documented.

**Comment by driesvints** [comment]
See https://github.com/laravel/docs/pull/7653

**Comment by samdharris** [comment]
> See [laravel/docs#7653](https://github.com/laravel/docs/pull/7653)

Thanks man! Hopefully one day the framework will be able to support this use case

**Comment by driesvints** [comment]
@samdharris hope so too. Sorry that you stumbled into this one!
