### ISSUE TITLE
Postmark mailer requires additional Symfony dependency

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#40906]
- Laravel Version: 9.0.1
- PHP Version: 8.0.13
- Database Driver & Version: MySQL 5.6

### Description:
I've upgraded two Laravel 8 projects to Laravel 9. I use Postmark in production so replaced `wildbit/swiftmailer-postmark` with `symfony/postmark-mailer`. After deployment I started receiving this exception:

```
You cannot use "Symfony\Component\Mailer\Transport\AbstractHttpTransport" as the HttpClient component is not installed. Try running "composer require symfony/http-client".
```

This wasn't mentioned in the upgrade docs, and I'm also a little surprised that `symfony/postmark-mailer` just doesn't require `symfony/http-client` itself.

Adding the package as suggested seems to resolve the issue. Should we add it this requirement to the upgrade/Postmark mailer docs?

### Steps To Reproduce:

* Install `symfony/postmark-mailer`
* Use the `postmark` mailer
* Attempt to send an email

I have a fresh Laravel app with a replication handy if it's helpful.

**Comment by X-Coder264** [comment]
The Symfony postmark mailer package provides the HTTP API and SMTP transports. If you use the SMTP transport you don't need a HTTP client - it's optional so that's why it isn't a hard dependency. On the other hand Laravel 9 currently always creates (and I'm not sure why that choice was made) the HTTP API transport (and that's hardcoded in the MailManager class so there's no way currently to specify that you want the SMTP transport via config).

**Comment by alexmck** [comment]
@dwightwatson this does affect the Mailgun driver too.

**Comment by driesvints** [comment]
The need for Symfony's HTTP client is noted in the suggest of Laravel's composer.json which should output when you install Laravel: https://github.com/laravel/framework/blob/9.x/composer.json#L162

However, this should be made clear in the docs and upgrade guide as well. I'll document this. Thanks

**Comment by driesvints** [comment]
https://github.com/laravel/docs/pull/7694
