### ISSUE TITLE
.env.example - defaults for MAIL_FROM_ADDRESS

### ISSUE THREAD

**Issue by atomtigerzoo** [laravel/framework#40940]
Hi!
I hope that I'm at the right place here. I've upgraded an app to Laravel 9 and hit my head to the wall after like 45 minutes, after I found out that I did not had a default set in my `.env.testing` (copied from _.env.example_) and that failed a test to send out mails with the new Symfony mailer. I had one set in my default `.env` so didn't notice it in the real world.

I got this error in my test:
```
The following exception occurred during the request:
Symfony\Component\Mime\Exception\LogicException: An email must have a "From" or a "Sender" header. in \vendor\symfony\mime\Message.php:132
```

The new mailer needs a from email address but the default `MAIL_FROM_ADDRESS` is set to null. This fails now with the mailer, but passed with the old.

Maybe the default might/could be changed to something like _info@example.com_ to keep others from running into this pitfall.

If not - just close this issue and maybe others find this useful in the future 🙈 Thank you for your time ✨

**Comment by driesvints** [comment]
I'm not sure that's correct? Afaik that env variable always needs to be set. I've always known things to fail without it being set.

**Comment by WyattCast44** [comment]
Just to add an additional datapoint, I also ran into this issue when upgrading to Laravel 9 -- updating the `MAIL_FROM_ADDRESS` from `null` to `random.email@domain.com` worked for me. 

The `mail.php` file does have a default value but it is not being applied because the default `.env` value is set to null, a simple fix would be to set the `MAIL_FROM_ADDRESS=` to nothing to allow the default value in the config file to take effect.
