### ISSUE TITLE
Middleware added via pushMiddlewareToGroup on L9 does not fire

### ISSUE THREAD

**Issue by cannycookie** [laravel/framework#41065]
- Laravel Version: 9.1.0
- PHP Version: 8.1
- Database Driver & Version: mysql 8.0.27

### Description:
In my package this code is working on Laravel 8
```php
        if(config('laraconsent.middleware.enable')){
              $router = $this->app->make(Router::class);
              $router->pushMiddlewareToGroup('web', ForceRedirectToUnapprovedConsents::class);
        }
```

But on laravel 9, the web middleware group is updated with the ``ForceRedirectToUnapprovedConsents::class`` but it does not fire.  

If I manually add the class into ``App\Http\Kernel.php`` middleware web group everythings peachy.

This works fine on a L8 install.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Feel free to post that link to a test repo and I'll reopen this.

**Comment by shijie1991** [comment]
我也遇到了相同的问题
