### ISSUE TITLE
TrustProxies middleware + Log façade mockery in phpunit = status code 500

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#41155]
- Laravel Version: v8.83.1
- PHP Version: 7.4.27
- Database Driver & Version: no

### Description:

Some unknown error in mocked Log façade in unit tests is returning http response 500 when \App\Http\Middleware\TrustProxies::class middleware is attached.

It was all working fine for me, but it got broken when I upgraded 3 of my composer packages

  - Upgrading laravel/framework (v8.73.2 => v8.83.1)
  - Upgrading laravel/ui (v3.4.2 => v3.4.4)
  - Upgrading symfony/var-dumper (v5.3.3 => v5.4.3)

### Steps To Reproduce:
1 ) set up a route 

    Route::post('/foo-foo', function () {
        return redirect()->back();
    })->name('foo-foo');

2 ) make sure your  `the App\Http\Kernel` has

    protected $middleware = [
        ...
        \App\Http\Middleware\TrustProxies::class,
        ...

3 ) make a unit test

    public function test_foofoo()
    {
        \Log::shouldReceive('error')->once();
        $response = $this->call('POST', route('foo-foo'));
        $response->assertStatus(302);
    }

4 ) run unit test, 

you will see 

    Expected response status code [302] but received 500.

but you should see 

    Mockery\Exception\InvalidCountException: Method error(<Any Arguments>) from Mockery_0_Illuminate_Log_LogManager should be called  exactly 1 times but called 0 times.

5 ) remove `\App\Http\Middleware\TrustProxies::class,` from `protected $middleware` of the `the App\Http\Kernel` and you will get back your 

    Mockery\Exception\InvalidCountException: Method error(<Any Arguments>) from Mockery_0_Illuminate_Log_LogManager should be called  exactly 1 times but called 0 times.

just as you should have received it on the first place

PS.
It is doesnot matter what is inside of the TrustProxies, the error comes anyway. I have 2 lines there

    class TrustProxies extends Fideloper\Proxy\TrustProxies
    {
        protected $proxies = '*';
        protected $headers = Illuminate\Http\Request::HEADER_X_FORWARDED_ALL;
    }

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DeepDiver1975** [comment]
Just in case somebody else is coming across this issue - it seems that https://github.com/laravel/framework/commit/c48540dfa84f94189b353035315b4470d1c8b344 is causing this in case deprecated code is used.

For me and obviously the original reporter TrustProxies was using deprecated code:
```php
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
```
which I replaced with 
```php
    protected $headers =
        Request::HEADER_X_FORWARDED_FOR |
        Request::HEADER_X_FORWARDED_HOST |
        Request::HEADER_X_FORWARDED_PORT |
        Request::HEADER_X_FORWARDED_PROTO |
        Request::HEADER_X_FORWARDED_AWS_ELB;
```

**Comment by DeepDiver1975** [comment]
While this fixes the symptom it feels wrong to me ... :shrug:

**Comment by Eugene-Melbourne** [comment]
`DeepDiver1975`, thank you very much for your reply.
Yes, the proposed solution does fix the issue.

But this is very wrong.

I find the [ upgrade guide ](https://laravel.com/docs/9.x/upgrade#the-assert-deleted-method) that talks about deprecating `HEADER_X_FORWARDED_ALL` . It is an upgrade guide to get to version 9 of Laravel. I'm still using Laravel v8.83.1

I'm particularly upset with `driesvints`, for closing this bug report without trying to understand the problem.

**Comment by X-Coder264** [comment]
There's no issue here. The Laravel deprecation handling is now behaving exactly as expected as of https://github.com/laravel/framework/commit/c48540dfa84f94189b353035315b4470d1c8b344

On the other hand `HEADER_X_FORWARDED_ALL` is a Symfony constant which has been deprecated as of Symfony 5.2.  Laravel 8.0.0 shipped with Symfony >= 5.1 so that's why there's no mention of that in the Laravel 8 upgrade guide. The latest Laravel 8 versions require Symfony 5.4 so the Laravel 9 upgrade guide thing about `HEADER_X_FORWARDED_ALL` can be applied to Laravel 8 wihout needing to even update to Laravel 9.

**Comment by DeepDiver1975** [comment]
From developer experience point of view it is inconvenient that deprecated code somewhere in the code base is resulting in a mock no longer working properly. I think we can agree on this - right?

**Comment by X-Coder264** [comment]
On a general basis I can agree that it is inconvenient for a mock to suddenly stop working.
In this concrete example though I'd say the problem is with the mock/test itself.

Calling `\Log::shouldReceive('error')->once();` and then calling a route where the entire application executes is:

1) very fragile by definition and was bound to sooner or later break like it just did
2) brings zero value to your test suite

If testing that logging works as expected is needed then create a proper unit (or integration) test just for the service that is supposed to do the logging that is being tested. That way the test actually brings value to the test suite and is not fragile.

**Comment by DeepDiver1975** [comment]
I can answer this with: it depends ;-)

It could be a quite valid part of a feature test to assert that log messages are written - various scenarios can come to one's mind.

**Comment by X-Coder264** [comment]
No, it does not "depend". This "issue" is a great example of how/why this is a bad idea. There's nothing that more specific/scoped tests like unit or integration tests couldn't cover that you would actually need a feature test for regarding logging.

**Comment by Eugene-Melbourne** [comment]
Making tests that (as you said) "very fragile by definition and was bound to sooner or later break like it just did" is a good idea. 
Because it covers more functionality at one go. 
This is how integration testing works by definition.

**Comment by X-Coder264** [comment]
You are mixing the concept of a test being fragile vs testing more functionality in one go. One has nothing to do with the other. 

Usually feature tests are less fragile than unit tests because a lot of unit tests are usually too much coupled to the implementation and do not actually test the behavior (you change one method name and the test fails because the mock wasn't updated etc).

No one is saying that it's bad to test more functionality at one go, but I'm saying that in this specific instance how the logging was tested was fragile/bad.
