### ISSUE TITLE
Cache::spy returns an exception: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/framework#41721]
- Laravel Version:  9.5.1
- PHP Version: 8.0.16
- Database Driver & Version: MySQL 8

### Description:
I'm not sure why but when I'm trying to make use of Cache::spy, I'm getting this exception:
`Trying to access array offset on value of type null`

### Steps To Reproduce:
The issue can be reproduced with a fresh install:

**web.php**
```php
Route::get('/', function () {
    $key = Cache::get('test-key');
    return view('welcome');
});
```

**ExampleTest.php**
```php
public function test_cache()
{
    Cache::spy();

    $this->get('/')->assertStatus(200);

    Cache::shouldHaveReceived('get')->with('test-key')->once();
}
```

If you remove the `assertStatus(200)`, the test passes as expected, otherwise the exception is thrown.

**Comment by derekmd** [comment]
Unfortunately `Cache::spy()` and `Cache::get()` can't be mixed due to how the Mockery package proxies the spied `CacheManager` instance. It causes the wrong `CacheManager` method to be called.

https://github.com/laravel/framework/blob/a2708abc306ef7941e7206c706de5dbea450acd1/src/Illuminate/Cache/CacheManager.php#L80-L83

https://github.com/laravel/framework/blob/a2708abc306ef7941e7206c706de5dbea450acd1/src/Illuminate/Cache/CacheManager.php#L416-L419

`Cache::get('test-key')` call stack:

1. `Illuminate\Support\Facades\Cache::get('test-key')`
2. `Illuminate\Support\Facades\Facade::__callStatic('get', ['test-key'])`
3. 
   * Without Mockery spy:
      * `Illuminate\Cache\CacheManager::__call('get', ['test-key'])`
      * `Illuminate\Contracts\Cache\Repository::get('test-key')` ✔️ 
   * With Mockery spy
      * `Illuminate\Cache\CacheManager::get('test-key')` _(protected)_ ❗ 

So the Mockery spy is allowing a protected `CacheManager@get()` method to be externally invoked when the real world scenario accesses the Cache store (Redis, etc.) through `CacheManager@__call()` -> `CacheManager@store()->get()`.

---

You likely need to change this to a regular `shouldReceive()` mock setup:

```php
Cache::shouldReceive('get')
    ->once()
    ->with('test-key')
    ->andReturn('foo');

$this->get('/')->assertStatus(200);
```

**Comment by driesvints** [comment]
Thanks @derekmd
