### ISSUE TITLE
ParseError: syntax error, unexpected 'EnvironmentInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by bilalswiftsolutions** [laravel/framework#41724]
- Laravel Version: 8.6
- PHP Version:8,7.4 
- Database Driver & Version:

### Description:

we are using php version 7.4 on the production server but on my local server I updated to php 8. Now I am facing this error on production server 

```
ParseError: syntax error, unexpected 'EnvironmentInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/G9S5K.png

How I can solve this issue?

**Comment by AegirLeet** [comment]
Use the same PHP version on both servers. Otherwise you risk pulling in package versions that are compatible with one version but not the other.

Also, are you sure your production server is actually running 7.4? Looks like whatever PHP version you're using doesn't support typed properties - so it can't be 7.4.

**Comment by driesvints** [comment]
Thanks @AegirLeet
