### ISSUE TITLE
Validation: empty string passes the `array` rule

### ISSUE THREAD

**Issue by danilopolani** [laravel/framework#41734]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: Not relevant

### Description:
Using an empty string as value for the `array` rule passes but it should not.

**Note**: this is an intentional duplicate of #18948, but since that issue has never been solved I decided to open a new one. In that issue there was a discussion about `ConvertEmptyStringsToNull` but that's _incorrect_, since we could use the validation outside of HTTP requests.

### Steps To Reproduce:
```php
\Validator::make(['field' => ''], ['field' => 'present|array'])->fails(); // false, WRONG

\Validator::make(['field' => null], ['field' => 'present|array'])->fails(); // true, correct
\Validator::make(['field' => 0], ['field' => 'present|array'])->fails(); // true, correct
\Validator::make(['field' => false], ['field' => 'present|array'])->fails(); // true, correct
```

**Comment by driesvints** [comment]
This is expected since this is considered an empty value. You're not requiring the value and thus the validation passes.

**Comment by danilopolani** [comment]
@driesvints yes, but it's required to be an array, or am I getting it wrong? I thought this was the correct way to say "it must be an array, but it can also be an empty array".

Or how should the rules become to achieve that?

**Comment by driesvints** [comment]
There doesn't seems to be a way atm to require an empty array.

**Comment by ElteHupkes** [comment]
@driesvints I'll make sure to do that once I have a slightly better idea what I'm talking about and where such a piece of information belongs. Clearly my thoughts coming in are a bit different than how it's actually designed, so I'm a bit hesitant about telling people what's up now 😉.

What sent me down the rabbit hole is that I was trying to create a rule that passes:

- `['foreign_id' => 123]` (field is an integer)
- `['foreign_id' => null]` (field is null)
- `[]` (field not specified)

`required` and `filled` are out the window, because they ignore `nullable`. All non-implicit rules aren't evaluated for whitespace strings. Without turning the middleware back on, I could only solve this with a custom rule, which seemed a bit odd to me.

**Comment by liquid207** [comment]
@ElteHupkes 
I quite agree with you. 
Now Validator can work normally on the basis that the data has been processed by middleware `ConvertEmptyStringsToNull`. But, not all Laravel application have `ConvertEmptyStringsToNull` enabled; Validator doesn't just process the data in the request that processed by `ConvertEmptyStringsToNull`.

If the [special treatment of empty string](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Validation/Validator.php#L777) is removed, this issue will disappear. @driesvints Do you think this modification is ok?

**Comment by driesvints** [comment]
No I don't sorry. This has been in the framework since forever and modifying it could break tons of apps. I'm sorry about this but we're not changing this.

**Comment by liquid207** [comment]
@driesvints 

Got it, thanks.

**Comment by macropay-solutions** [comment]
We just had a production incident about this BUG. Empty string is not validated.

```php
'currency' => 'sometimes|size:3|in:EUR,USD',
```

```php
    protected function isValidatable($rule, $attribute, $value)
    {
        if (in_array($rule, $this->excludeRules)) {
            return true;
        }

        return $this->presentOrRuleIsImplicit($rule, $attribute, $value) && // this returns false
```

```php

    protected function presentOrRuleIsImplicit($rule, $attribute, $value)
    {
        if (is_string($value) && trim($value) === '') {
            return $this->isImplicit($rule); // returns from here false 
        }

        return $this->validatePresent($attribute, $value) ||
               $this->isImplicit($rule);
    }
```

The field should be validated only when present so this is clearly a bug. 

Asking for the user to specify that it must be required via 'sometimes|required|size:3|in:EUR,USD' is nonsence since the size and the in rules should be applied.

We are thinking of removing `$this->presentOrRuleIsImplicit($rule, $attribute, $value)` call to fix this by overwriting the validator because we have it overwritten for the latest security bug anyway.

Update 
or just remove this code

```php

        if (is_string($value) && trim($value) === '') {
            return $this->isImplicit($rule);
        }
```

Which will result in

```php
        Validator::validate(['t'=> 2, 'tt' => 3], [
            't' => 'in:1',
            'ttt' => 'in:1',
            'tt' => 'in:2'
        ]);
//or

        Validator::validate(['t'=> 2, 'tt' => 3], [
            't' => 'sometimes|in:1',
            'ttt' => 'sometimes|in:1',
            'tt' => 'sometimes|in:2'
        ]);
```
=>
```json
{
  "message": "The given data was invalid.",
  "errors": {
    "t": [
      "The selected t is invalid."
    ],
    "tt": [
      "The selected tt is invalid."
    ]
  }
}
```

but


```php

        Validator::validate(['t'=> null, 'tt' => ''], [
//            't' => 'sometimes|nullable|in:1',
//            'ttt' => 'sometimes|in:1',
            'tt' => 'present|nullable|in:2'
        ]);
```
=>
```json
{
  "message": "The given data was invalid.",
  "errors": {
    "tt": [
      "The selected tt is invalid."
    ]
  }
}
```

So a fix would be:
```php
        Validator::validate(['t'=> null, 'tt' => ''], [
//            't' => 'sometimes|nullable|in:1',
//            'ttt' => 'sometimes|in:1',
            'tt' => 'present|nullable|string|in:2,'
        ]);
```

Or use [ConvertEmptyStringsToNull](https://laravel.com/docs/10.x/validation#a-note-on-optional-fields).

UPDATE:
We saw why this code
```php

        if (is_string($value) && trim($value) === '') {
            return $this->isImplicit($rule);
        }
```
was put there.
HTML forms submission will send empty string for inputs/selects that have not been filled so, the above handles that. it is also documented that if the field must not be empty string , you should use required.

Still this fixed one thing and broke another. FE should not send invalid values.
