### ISSUE TITLE
CC version of mail loses some arguments

### ISSUE THREAD

**Issue by andries230** [laravel/framework#41934]
- Laravel Version: 9.5.1
- PHP Version: 8.0.11
- Database Driver & Version: 5.7.33-0ubuntu0.16.04.1

### Description:
When I CC an email the last paremeter get's lost and thus the cc version of the mail actually looks different then the original (tested in mailhog).

The CC's subject ends up being "Hello ", while the main mail's subject that's send to $request->email is (correctly) "Hello John Smith"

The same goes for within the mail's html, e.g.:

`<h1>Dear {{ $customer_name }},</h1>`

It ends up being "Dear ," in the CC... While it does work for the main mail.

The weird thing is that the $concepts and $authenticated_user work in BOTH mails. Only the $customer_name get's lost (in the cc only).

### Steps To Reproduce:

```
$concepts = session()->get('concepts');
$name = $request->first_name .' '. $request->name_joiner .' '. $request->last_name;


Mail::to($request->email)->cc(['admin@example.com'])->send(new ConceptOverviewMail($concepts, Auth()->user(), $name));
```

Part of the mail class:

```
public $customer_name;
public $concepts;
public $authenticated_user;

public function __construct(Collection $concepts, User $authenticated_user, string $customer_name)
{
    $this->customer_name = $customer_name;
    $this->authenticated_user = $authenticated_user;
    $this->concepts = $concepts;
}

public function build()
{
    return $this->subject('Hello ' . $this->customer_name)->view('mails.Concepts');
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll reopen once you provide a repo. Thanks
