### ISSUE TITLE
Issue generating URL when specifying a 'root' filesystem path

### ISSUE THREAD

**Issue by bennettblack** [laravel/framework#41964]
- Laravel Version: 9.8
- PHP Version: 8.1.3
- Database Driver & Version: DB2 for IBM iSeries (third party driver)

### Description:
I'm using Digital Ocean Spaces to host website assets. If I specify a 'root' path in `filesystems.php` for any DO disk, I run into issues retrieving the files. If I remove the 'root' key and write the folder path manually, I don't have any issues.  Specifically, it looks like the end path character "/" is being converted to "%5C". Note, I only encountered this issue after upgrading from L8 to L9.

Here's how I'm generating the URL in my Blade:
 
`
<img src="{{ Storage::disk('vendor-logos')->url($vendor->image) }}" alt="{{ $vendor->name }}">
`

Here's the HTML that produces:
`
<img src="https://bwi.nyc3.digitaloceanspaces.com/vendor-logos%5Cb574d580c91d97b6b12155708ecc61a3c0779750" alt="BASF">
`

Note how the `src` path above is missing a `/` , right after the root location 'vendor-logos'. Any file I display like this gets prepended with a `%5C`. I could be going in the wrong direction, but a quick Google search shows that 5c is the hex ASCII representation of "backslash".

**Disk:**

```php
'vendor-logos' => [
    'driver'        => 's3',
    'key'           => env('DIGITALOCEAN_SPACES_KEY'),
    'secret'        => env('DIGITALOCEAN_SPACES_SECRET'),
    'endpoint'      => 'https://nyc3.digitaloceanspaces.com',
    'region'        => 'nyc',
    'bucket'        => 'bwi',
    'root'          => 'vendor-logos',
    'visibility'    => 'public',
],
```
Here's a snippet of my `vendor` model's underlying table. The highlighted record is the one used in my example above.
![image](https://user-images.githubusercontent.com/51721783/163275262-782b1275-0488-4b25-bea8-f4f185dded12.png)

### Steps To Reproduce:

1. Setup a disk in L9 that uses digital ocean spaces. 
2. Define a 'root' key in the filesystem config for that disk
3. Make sure the asset in your digital ocean space is in the folder that corresponds to the 'root' path you specified in `filesystems.php`
4. Try to display the asset in a blade.

**Comment by driesvints** [comment]
Since Laravel v9 switched to Flysystem v3, I suspect this is either a configuration issue or a Flyststem issue.

Can you first please try the Flysystem issue tracker or one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by sibihaseb** [comment]
'directory_separator' => '/',

https://github.com/statamic/cms/issues/5894#issuecomment-1115257599
