### ISSUE TITLE
Grouping the result of a query by an enum casted attribute

### ISSUE THREAD

**Issue by C14r** [laravel/framework#42031]
- Laravel Version: 9.8.1
- PHP Version: 8.1.4
- Database Driver & Version: mysql & 10.4.13-MariaDB

### Description:

I have a Customer model, whicht casts the status attribute to an php 8.1 enum.

```php

namespace App\Models;

use App\Enums\CustomerStatus;

class Customer extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'status' => CustomerStatus::class,
    ];
}
```

and I'm trying to group the result of a query by status

```php
Customer::all()->groupBy('status'));
```

I'm getting the following error: `array_key_exists(): Argument #1 ($key) must be a valid array offset type` in `..vendor\laravel\framework\src\Illuminate\Collections\Collection.php: 497`.

```php
if (! array_key_exists($groupKey, $results)) {
    $results[$groupKey] = new static;
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by C14r** [comment]
Hey, thanks for the answer.

If created the repository `C14r/bug-report` with the laravel/installer 4.2.10 and made a commit with everything to reproduce the bug.

### Steps To Reproduce:

- gh repo clone C14r/bug-report
- php artisan migrate --seed
- php artisan serve
- start the browser and call http://localhost:8000/

**Comment by agus24** [comment]
i think the problem within `valueRetriever` of `EnumeratesValues` trait it should be check if the value is enum or not. cmiiw.
```
    protected function valueRetriever($value)
    {
        if ($this->useAsCallable($value)) {
            return $value;
        }

        return function ($item) use ($value) {
            $outputValue = data_get($item, $value);
            if ($outputValue instanceof UnitEnum) {
                return $outputValue->value;
            }

            return $outputValue;
        };
    }
```

**Comment by driesvints** [comment]
Hi there, this is actually a feature request. Collections don't support these yet. We'd welcome PR's for this, thanks.

**Comment by ziadoz** [comment]
Another solution is to do: `->groupBy('status.value')`

**Comment by devfaysal** [comment]
> Another solution is to do: `->groupBy('status.value')`

How cool is that! I was looking to do an implode of enum values and it just works like this.
