### ISSUE TITLE
Constaints on multiple hasMany relations of the model broken

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#42165]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 5.7

### Description:
If a model `A` defines two hasMany relationships on model `B`, each with it's own constraints, and you attempt to eager load both of the relations, it breaks with `SQLSTATE[HY093]: Invalid parameter number (SQL: select * from files where type in (1, 2, 3) and files.parent_id in (16) and files.deleted_at is null)`. The bindings are messed up: `[1, 2, 3, 4]`.

I can't pinpoint a specific version where it broke, but it used to work up until & including 8.80 and doesn't work from 9.0.0 and above.

### Steps To Reproduce:
```php
class File extends Model {}

class User extends Model {
    public function files(): HasMany {
        return $this->hasMany(File::class, 'parent_id')
            ->whereIn('type', [1, 2, 3]);
    }

    public function otherFiles(): HasMany {
	return $this->hasMany(File::class, 'parent_id')
            ->where('type', 4);
    }
}

User::with(['files', 'otherFiles'])->get();
```

I'm unsure if this kind of code is expected to work. If so, I'll provide a GitHub repo.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by oprypkhantc** [comment]
Turned out to be a problem with [builder serialization package](https://github.com/AnourValar/eloquent-serialize).

Sorry for bothering.
