### ISSUE TITLE
Chansning email in user profile forces the user to a new email verification process.

### ISSUE THREAD

**Issue by ArneAnka** [laravel/framework#42179]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- Database Driver & Version: SQLITE3, 3.37.0

### Description:
Signed user throws out from application when changing email.

### Steps To Reproduce:

Using the Inertia stack and was changing the email in the profile, and I noticed that if the user has a already verified email. The new email gets unverified, and the user is thrown out from the application.

Don't know if this behavior is expected...

- If the application requires verified emails, even changing email should be verified.
- What if the user incorrectly enters his/hers new email? They will loose the account.

**Comment by driesvints** [comment]
Yes this is currently the expected behavior. I get that this is not ideal in all situations but right now this is how things work. I will bring this up internally however to see if there's anything we can do to improve this.

Otherwise I suggest you ignore Jetstreams routes for now with `Jetstream::ignoreRoutes()` in your service provider, overwrite them in your own routes file and implement your own behavior with a custom middleware.
