### ISSUE TITLE
Retrieve by credentials:  undefined array key password

### ISSUE THREAD

**Issue by korkoshko** [laravel/framework#42233]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- Database Driver & Version: SQLite Library => 3.31.1

### Description:
Hi! 

I just researched auth providers (database & eloquent) and found some issue in the  method "[retrieveByCredentials](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php#L110)", which using "str_contains" to check "password" key in the array credentials . 
This means that we can pass as a key any string that contains the substring "password", for example, "super_password", but the method "[validateCredentials](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php#L110)" access to "password" key array directly.  In my opinion it's illogical.

It's actual for [DatabaseUserProvider.php](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/DatabaseUserProvider.php) and [EloquentUserProvider.php](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php).

### Steps To Reproduce:

1. For example call the "attempt"  method: 

```
Auth::attempt([
    'email' => 'topsecretuser@laravel.com',
    'super_password' => 'topsercetpassword'
]);
```

**Comment by driesvints** [comment]
So, the explanation for this is that the first check in `retrieveByCredentials` is just to see if *only* a password value was passed. If you look further down at https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php#L120 you'll see that all password keys are filtered out from the lookup. The first check is just an early return to see if there's only one value in credentials and if it's a password one. If it is, we can early exit the method.

This is unrelated to https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php#L156 which still expects `password` as the actual key for the password check.

The reason why your example fails is because Laravel still expects `password` to be the key for the password value. All other "password" fields are purely an app related concept.

**Comment by korkoshko** [comment]
@driesvints My point is that the use of "str_contains" in this case is useless and misleading. Just use equals operator.

**Comment by driesvints** [comment]
@korkoshko I think you didn't understand what I was saying. The first check in https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/EloquentUserProvider.php#L120 is just to early return when there's only one value in credentials and if it's *any* password value. The password values are filtered out anyway in the loop. It's totally intended to use `str_contains` here.

**Comment by korkoshko** [comment]
@korkoshko okay , why not using `===` to filter in the loop ?

```
if (str_contains($key, 'password')) {
    continue;
}
```
change to:
```
if ($key === 'password') {
    continue;
}
```

**Comment by driesvints** [comment]
Because we want to filter out *every* password value. If we don't, passwords will be added to the query which may end up in logs etc. We want to prevent to expose password values.

**Comment by driesvints** [comment]
You also never query for a password value because they should always be hashed. They'll never match the values in the database.
