### ISSUE TITLE
preventLazyLoading doesnt work

### ISSUE THREAD

**Issue by JamesHemery** [laravel/framework#42285]
- Laravel Version: ^9.11
- PHP Version: 8.1
- Database Driver & Version: Sqlite or Mysql (both tested)

### Description:

When I enable the preventLazyLoading like that:

```
        Model::preventLazyLoading(! app()->isProduction());
```

I don't have any mistakes that I make a lazy load:

```
$user = User::first();
dump($user->posts);
```

### Steps To Reproduce:

1. git clone git@github.com:JamesHemery/strict-lazy-bug.git
2. composer install
3. php artisan migrate:fresh --seed (sqlite database)
4. php artisan tinker
5. $user = User::first();
6. $user->posts

**Comment by JamesHemery** [comment]
It's good: https://github.com/JamesHemery/strict-lazy-bug

Thanks,

**Comment by driesvints** [comment]
Ah so, I see the reason even though it's not obvious. If you only load a single model instance and call a relationship lazily on it it won't trigger the exception. It only happens when you load multiple instances and call relationships on those. Those will trigger an n+1 issue.

```
User::all()->first()->posts;
```

Make sure to have more than one user in the database.

**Comment by riabiy-denis** [comment]
Very unintuitive. Really :D 

I can understand the reasonings, but, in a nutshell, belongsTo is not covered by lazy loading, from what I get.

**Comment by MightySepp666** [comment]
@driesvints please reopen this issue. It is clearly a bug and obviously not working as described. 

You are mixing up two things that are not the same: the term "lazy loading" and "n + 1 query". The terms are connected, but denote different things. If I disable lazy loading, I expect, that lazy loading is disabled. I don't expect that lazy loading is still allowed, as long as the number of datasets is low.

Consider a real-world use case, not just a hello world example. In this scenario you have dozens of relations, which can be nested in multiple levels. If you have to ensure, that every level contains multiple datasets to be sure for your code to behave as in production, it will make it almost impossible to write tests for it. Or these tests will end up being overly complicated, hard to maintain and very slow. If you write tests for a new feature, and the feature code is completely covered, it should be safe to assume, that the code will behave the same way in production. But it doesn't.

That's why we can't use this feature right now. Because it depends on an invisible side effect if it will throw an exception or not. This feature would have been a great improvement for us, as it would enforce the requirement to implement efficient queries. That is vital for applications that receive (tens of) thousands of requests per second. Therefore we would like to use `Model::preventsLazyLoading()` gradually in every endpoint.

Decisions like this make me think, that Laravel might not be a good choice for enterprise applications (with millions of sessions per day). Because this design promotes errors, that are hard to reproduce, not detectable by tests and will only occur in production. There are already many design decisions in the framework, that make it difficult to use it in a professional context (like hiding errors instead of failing fast, the heavy use of magic invocations or the lack of use of interfaces). But this one should be easy to solve, it's just this single line of code in `Eloquent\Builder::hydrate`, that causes the unwanted side effect:
```php
if (count($items) > 1) {
    $model->preventsLazyLoading = Model::preventsLazyLoading();
}
```

Please listen to the feedback of your users, you can really learn a lot of them.

**Comment by MightySepp666** [comment]
> [...] You just test locally [...]

@riabiy it seems like you didn't take enough time to read and understand my comment. Because the lack of testability is the whole point of it. I tried to provide all the necessary information to explain why the current implementation is error prone. Please read the comment again, carefully. If I really missed out any important detail, let me know.

Of course we have implemented feature tests for this use case. These tests do hit the database (no mocking), these tests do cover all the lines of code and they complete successfully. But as I already pointed out: the behavior of this `Model::preventsLazyLoading()` depends on the number of datasets in the database (which is an unexpected side effect). It is especially unexpected, when you are accessing models through nested relations. Then the restriction is not applied to some of the models that are loaded through a relation because of the condition that I included in my comment above. In that case, the relation model can load other relations lazily, which is clearly not what I'm expecting, when I call the `preventsLazyLoading()` method.

I can't see any reason, where this behavior would make any sense. That's like I would call a method `failOnError()`, which silently catches certain exceptions and only throws for others.

I always try to improve my code and follow best practices to keep our code maintainable and to allow us to keep implementing new features. One of these practices is to fail fast and reliably. Another one is to implement tests specifically and with the smallest possible scope. If you are unsure about these topics, I highly recommend you to get a better understanding of them (which seems a bit out of scope here). There is excellent literature available about both topics, that provide a deep understanding of why these conventions make sense.

However, I want to point out, that I'm not criticizing the fact that this error exists. I criticize how reported errors and problems are dealt with. Instead of just fixing them, the bug reports are close and handled as if it was a user's mistake. If a lot of users keep making the same "mistake" over and over again, than this point of view should be reconsidered.

**Comment by MightySepp666** [comment]
@driesvints could you please reconsider this issue, based on my explanation above? It's really keeping us from using this feature.

**Comment by decadence** [comment]
@MightySepp666 I don't think anyone from the Laravel team is looking at closed issues. So it's better if you try to open a pull request with the desired fix.
