### ISSUE TITLE
Scheduled Job with strongly typed nullable Carbon in constructor gets default value

### ISSUE THREAD

**Issue by VincentBean** [laravel/framework#42347]
- Laravel Version: 9.4.1
- PHP Version: 8.1.3
- Redis Version: 6.2.6

Also tested with Laravel 8 and PHP 8.0.

### Description:

Dispatching jobs with a nullable Carbon instance and not passing it via the scheduler will set the Carbon instance to the date adn time that the job is dispatched.

When you have a job that has a constructor like this:

```php
public function __construct(protected ?\Carbon\Carbon $fromDate = null) {
...
```

And schedule it like this:
```php
$schedule->job(MyJob::class)->hourly();
```

The scheduled job gets a new carbon instance. When directly using `MyJob::dispatch()` this doesn't happen.
I've tested this with the `sync`, `redis` and `database` drivers

The expected behaviour should be that the nullable Carbon parameter remains null because it is never passed.
Without the typehint it works fine.

The `\Illuminate\Support\Carbon` class gives the same result.

### Steps To Reproduce:

Create a new Laravel project with database queues or Horizon queues.

Create a new job with a nullable strongly typed `\Carbon\Carbon` parameter in the constructor.

Add the job to the scheduler:

`$schedule->job(MyJob::class)->everyMinute();`

Run the scheduler: `php artisan schedule:run`

Check the job in the database or Horizon, the Carbon parameter is set to the date that the job was dispatched.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by VincentBean** [comment]
Hi Dries, thank you for your reply.

[I've setup a repo to reproduce this.](https://github.com/VincentBean/laravel-bug-report-42347)

See [this commit](https://github.com/VincentBean/laravel-bug-report-42347/commit/b232363ab8bfb11217350c3b79da43077c9de2dc) for the code and the readme for instructions.

**Comment by driesvints** [comment]
So this is actually expected. The job is resolved from the container which sees the carbon dependency and injects it. If you need to resolve a job from the container you'll need to pass it with the `::class` notation like you do. Otherwise you'll need to pass the actual instance:

```php
$schedule->job(new MyJob)->everyMinute();
```
