### ISSUE TITLE
Migration: foreignIdFor: $column argument doesn't make sense currently

### ISSUE THREAD

**Issue by levu42** [laravel/framework#42519]
- Laravel Version: 9.13.0
- PHP Version: 8.1.6
- Database Driver & Version: MariaDB 10.7.3 / PDO

### Description:

The `foreignIdFor()` method in migrations has a second argument `$column` that doesn't make sense in how it (not) works currently.

Imagine I have a `User` model and a `Post` model and a post has both a `author_user_id` and an `reviewer_user_id`. Intuitively, the migration would look like

```php
$table->foreignIdFor(App\Models\User::class, 'author_user_id')->constrained();
```

Which would be the short form for:

```php
$table->unsignedBigInteger('author_user_id');
$table->foreign('author_user_id')->references('id')->on('users');
```

Instead, it behaves as if the code had an `->on('author_users')`.

In my understanding, either the `$column` argument of the `foreignIdFor()` method is useless (because if the model is ignored, it's just the same as the `foreignId()` method - why make it available as another method as well?), or, rather, `foreignIdFor($model, $class)` should get the table name (here: `'users'`) from the first argument, from the model.

**Comment by DarkGhostHunter** [comment]
## Short fix:

    $table->foreignIdFor(App\Models\User::class, 'author_user_id')->constrained('users');

## Long story:

The `constrained()` method accept the table and its primary column. If not, it will try to guess the table based on the foreign column name: 

    author_user_id
    author_user // before last "_id"
    author_users // plural

This is normal because it works for a column that is called `user_id`.

    user_id
    user
    users

There is no reliable way to get the column name... unless the `ForeignIdcolumnDefinition` allows to include the name of the Model so it can guess it from there with `(new $model)->getTable()`, model name that should be passed when using `foreignIdFor()`. A nice PR could fix that.

**Comment by driesvints** [comment]
Since there's no real bug but rather some confusing method arguments I'm going to close this. Appreciating PR's to the docs if anything is unclear and can be explained better 👍

**Comment by LWlook** [comment]
This is really confusing, i hope they rethink this, and merge the pull request.
