### ISSUE TITLE
Route caching returns wrong route if route name is equal to the application prefix

### ISSUE THREAD

**Issue by nielsdos** [laravel/framework#42539]
- Laravel Version: 9.14.0
- PHP Version: 8.1.6
- Database Driver & Version: MariaDB 10.8.3

### Description:

While upgrading a Laravel application from 6.x to 9.x, I encountered the following regression.

**Context**: We have a Laravel application installed on the path http://server/pathname/.
We have a route linked to a controller in our application with the same name as the prefix path of the application: "/pathname" (i.e. accessible via http://server/pathname/pathname).

**The bug**: The application works fine in 9.x *unless* I enable route caching. When I surf to the homepage (http://server/pathname/) with route caching enabled, Laravel believes I'm actually surfing to http://server/pathname/pathname. This did work perfectly fine in Laravel 6.x with route caching enabled.

I tracked it down to the function `match` in the class `CompiledRouteCollection`. The wrong route is returned from the `matchRequest` call. I manually worked around this issue by modifying `requestWithoutTrailingSlash` to also remove the prefix "/pathname".

### Steps To Reproduce:

* Create a new Laravel 9.x app under a subdirectory "/pathname" (perhaps a directory is not strictly necessary, I believe any kind of prefix will do)
* Create a route linked to a controller with path "/pathname"
* Execute `route:cache`
* The application returns the page for "/pathname/pathname" when surfing to "/pathname"

**Comment by rodrigopedra** [comment]
Serving a Laravel application from a subdirectory is not officially unsupported at this time:

https://laravel.com/docs/9.x#directory-configuration

There was some issues before regarding this subjects and all were closed due to this feature being unsupported:

- https://github.com/laravel/framework/issues/32082#issuecomment-604986571
- https://github.com/laravel/framework/issues/32236#issuecomment-692546842
- https://github.com/laravel/framework/issues/32832#issuecomment-629628020
- https://github.com/laravel/framework/issues/34362#issuecomment-693220173
- https://github.com/laravel/framework/issues/34977#issuecomment-717105251
- https://github.com/laravel/framework/issues/35241

*linked comments are from Laravel core members*

Although this PR merged on 9.x might help you out, if you are using nginx: https://github.com/laravel/framework/pull/40014

**Comment by nielsdos** [comment]
Alright thanks for the insight.
The nginx approach will do.

**Comment by taai** [comment]
> Serving a Laravel application from a subdirectory is not officially unsupported at this time:

I believe you meant "is not officially supported". :wink:

**Comment by rodrigopedra** [comment]
Thanks @taai 😀
