### ISSUE TITLE
laravel.EMERGENCY: Log [deprecations] is not defined.

### ISSUE THREAD

**Issue by xversial** [laravel/framework#42774]
- Laravel Version: 9/latest
- PHP Version: 8.1
- Database Driver & Version:

### Description:
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at ./vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)

This is spamming the shit out of my production logs every time someone browses a page. I can't disable it or stop it regardless of what logging level I set. Seems like this issue has been posted countless times with no real fix or solution.

### Steps To Reproduce:
It happens on a fresh install of laravel 9, nothing I do seems to silence it.

**Comment by xversial** [comment]
Setting LOG_DEPRECATIONS_CHANNEL=daily rather than the default of null seems to have shut it up.

**Comment by ahmedsayedabdelsalam** [comment]
i think we need to open it again because this happens in the default setup

**Comment by j-fulbright** [comment]
this appears to still be an issue in Laravel 11?

**Comment by GalahadXVI** [comment]
Same here. Getting it on one application, but not on another. The only difference is that the application that is encountering this issue has Laravel Octane installed.

This error makes no sense to me. Looking at the framework, Laravel injects a `deprecations` channel at runtime or lets you define one in `config/logging.php`. In theory it should always exist by the time any deprecation is handled.

```php
public function handleDeprecationError($message, $file, $line, $level = E_DEPRECATED)
{
    $this->ensureDeprecationLoggerIsConfigured();

    $options = static::$app['config']->get('logging.deprecations') ?? [];

    with($logger->channel('deprecations'), function ($log) use ($message, $file, $line, $level, $options) {
            if ($options['trace'] ?? false) {
                $log->warning((string) new ErrorException($message, 0, $level, $file, $line));
            } else {
                $log->warning(sprintf('%s in %s on line %s',
                    $message, $file, $line
                ));
            }
    });
}

protected function ensureDeprecationLoggerIsConfigured()
{
        with(static::$app['config'], function ($config) {
            if ($config->get('logging.channels.deprecations')) {
                return;
            }

            $this->ensureNullLogDriverIsConfigured();

            if (is_array($options = $config->get('logging.deprecations'))) {
                $driver = $options['channel'] ?? 'null';
            } else {
                $driver = $options ?? 'null';
            }

            $config->set('logging.channels.deprecations', $config->get("logging.channels.{$driver}"));
        });
}
```

This doesn't make sense because:
- If you’ve never defined `channels.deprecations`, Laravel will do it on first deprecation by copying your LOG_DEPRECATIONS_CHANNEL driver (e.g. stack or daily) into `logging.channels.deprecations`.
- If you have defined it manually, Laravel exits early and uses your definition.
        
Either way, Log::channel('deprecations') should always find something... so seeing it “not defined” means neither path ran.

Strangely, I only get this in my octane app. My other application (which doesn't use Ocane) never trips this error. That makes me wonder if Octane’s long-running process model is triggering the injection logic differently (or maybe skipping it entirely). I can’t confirm myself, but it’s the main difference between my two codebases.

This can be fixed fairly quickly by manually adding in a deprecations channel. But it is still worth investigating further though.

```
        'deprecations' => [
            'driver' => 'daily',
            'path'   => storage_path('logs/deprecations.log'),
            'level'  => env('LOG_LEVEL','warning'),
            'days'   => 14,
        ],
```
