### ISSUE TITLE
Incorrect Query Params by Arr::query()

### ISSUE THREAD

**Issue by comes** [laravel/framework#42794]
- Laravel Version: 8.83.16 & 9.17.0
- PHP Version: 8.0.19 & 8.1.6
- Database Driver & Version: unneeded

### Description:

Query params built by `Arr::query()` didn't match the expected result.

### Steps To Reproduce:

```php
$query = ['foo' => 1, 'bar' => 'hello world', 'nullable' => null, 'empty' => ''];

dump(http_build_query($query, '', '&', PHP_QUERY_RFC3986)); // foo=1&bar=hello%20world&empty=

dump(\Arr::query($query)); // foo=1&bar=hello%20world&empty=
```

the expected output should be `foo=1&bar=hello%20world&empty=&nullable=`

`Arr::query()` use an internal php function which did not produce the expected results.

```
Route::any('test', function (Request $request) {
    $laravelQuery = $request->all();
    $vanillaQuery = $_GET;

    return print_r([$vanillaQuery,
        $laravelQuery,
        $vanillaQuery === $laravelQuery,
        \Arr::query($vanillaQuery),
        \Arr::query($laravelQuery)
    ]);
});
```

output:
```

Array
(
    [0] => Array
        (
            [foo] => bar
            [empty] => 
        )

    [1] => Array
        (
            [foo] => bar
            [empty] => 
        )

    [2] => 
    [3] => foo=bar&empty=
    [4] => foo=bar
)

```

The reason for the null-value is the default middleware `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,` in https://github.com/laravel/laravel/blob/1f9eee06ddb38abf86e2f7df37a20281cd774e3d/app/Http/Kernel.php#L23

but the reason for the wrong query parameters is in `http_build_query` see https://www.php.net/manual/en/function.http-build-query.php#60523

The follow up error here is, if you create a pagination `withQueryParams()`, the resulting query parameter is something different, than the original one.

**Comment by rodrigopedra** [comment]
Sent PR #42795

**Comment by rodrigopedra** [comment]
Hey @comes , I tried PR #42795 targeting 8.x, as it seemed a bug fix, and PR #42806 targeting master as the first PR was rejected due to being a breaking change on expected behavior. 

But this last PR was also rejected as maintainers are not willing to change this behavior at all. And I kind agree that, besides one might expect the use case you describe to work like this issue report, `Arr::query()`, with its current behavior, is around for so long, that many other apps might be expecting the current behavior as the default.

My suggestion is that you add a macro to the `Illuminate\Support\Arr` class, adding a custom method that handle `null` values as you'd expect.

Inside a Service Provider `boot` method, for example in your app's `AppServiceProvider@boot` add this:

~~~php 
use Illuminate\Support\Arr;

// ...

public function boot()
{
    Arr::macro('queryWithNulls', function (array $array) {
        array_walk_recursive($array, function (&$value) {
            if ($value === null) {
                $value = '';
            }
        });

        return http_build_query($array, '', '&', PHP_QUERY_RFC3986);
    });
}
~~~

This will allow you to call `Arr::queryWithNulls()` throughout your project's codebase..

**Comment by rodrigopedra** [comment]
@comes thanks for the example. I understand, and agree, that the behavior should be changed.

But although I try contribute to Laravel whenever I can, in a way to give back how much I earned from using it, I am not a core team member.

You can leave this issue open, so maybe one of the maintainers sees this enriched example and come up with a improved solution.

As a workaround, I think you might know it already, you can try this:

~~~
curl http://sample.test/sample\?active=1
~~~

By the way, I wasn't aware of the `json_pp` utility, thanks for that. Have a nice day =)

**Comment by comes** [comment]
Highly appricate this, @rodrigopedra. if you like `json_pp`, see what's happend if you pipe it to bat. `json_pp | bat -l json`

**Comment by driesvints** [comment]
Heya. We don't plan to change this behavior, sorry. We'd appreciate a PR to the docs if anything can be clarified. Thanks

**Comment by swaty007** [comment]
Use in Service provider in boot method

Paginator::queryStringResolver(function () {
            $query = $this->app['request']->query();
            array_walk_recursive($query, function (&$value) {
                if ($value === null) {
                    $value = '';
                }
            });
            return $query;
        });
