### ISSUE TITLE
PostgreSQL dropPrimary does not work, if using prefix

### ISSUE THREAD

**Issue by mihy** [laravel/framework#42804]
- Laravel Version: v9.17.0 (but also the same with any lower version
- PHP Version: 8.1 (but PHP version does not take affect)
- Database Driver & Version: PostgreSQL (14.3), but also does not take affect

### Description:
I can not drop existing index in my database (PostgreSQL) with standard migration.
The problem persist, if using PostgreSQL and prefix is not empty string.
The problem is in file: 

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php

Line: 355

It generates index name without prefix. 

When primary key index name is generating, it leaves naming for PostgreSQL, even if passing optional parameter $index. Generated SQL is something like: 

alter table "prefix_test" add primary key ("id")

and PostgreSQL creates index name: prefix_test_pkey

When executing $table->dropPrimary(), raw sql is: 
alter table "prefix_test" drop constraint "test_pkey", it does not add prefix and so migration throws error that:

constraint "test_pkey" of relation "prefix_test" does not exist.

It should generate prefix_test_pkey

Optionally $table->primary() and $table->dropPrimary() allows to pass index name, but PostgresGrammar ignores it. 

### Steps To Reproduce:

1. install Laravel
2. change .env DB_CONNECTION to pgsql
3. change config/database.php line 75 from 'prefix' => '',  to 'prefix' => 'prefix_', (under pgsql)
4. delete all files from database/migrations
5. create migration file (php artisan make:migration create_test_table (see below)
6. php artisan migrate (throws error)

file: XXXXXX_create_test_table.php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->id();
            $table->dropPrimary();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
};

**Comment by mihy** [comment]
Actual code of migration file
`<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->id();
            $table->dropPrimary();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
};`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll re-open this once you provided a repo.

**Comment by programster** [comment]
@driesvints  I am experiencing a similar issue, whereby I am struggling to remove a primary key that has a custom constraint name. This happened because I am moving an existing database over to using Laravel, so its tables were not set up by Laravel itself.

I have never submitted a bug report for Laravel before, but hopefully I followed your instructions correctly on setting up a demonstraton repo, which can be found here:

https://github.com/programster/Laravel-bug-report-dropPrimary

They key commit demonstrating the bug is here:
https://github.com/programster/Laravel-bug-report-dropPrimary/commit/7f1e774b355d7cfb386a0db3f9454a7684291e6c

I made sure to test it was still the case after setting up PostgreSQL running in a docker container and updating my .env file database settings to:

```bash
DB_CONNECTION=pgsql
DB_HOST=192.168.0.x
DB_PORT=5432
DB_DATABASE=bug_report
DB_USERNAME=laravel
DB_PASSWORD=laravel
```

**Comment by driesvints** [comment]
@programster I think:

1. You need to use the Schema builder, not a raw query
2. You can't do those two operations in the same migration

**Comment by programster** [comment]
@driesvints the first query where I'm creating the table, is not supposed to show how I would have built it in Laravel, but to simulate the problematic table structure I have inherited by trying to move a legacy database over to Laravel. I am showing an example of how I am trying to fix it by using `dropPrimary()` in the second statement.

I don't think I need to split the operations into two migrations to demonstrate the bug, as  the db statement query executes immediately, and it is the one that I need to execute first. If it makes  you happier to demonstrate the point though, I would be happy to do so....

**Comment by yasirmturk** [comment]
👍  I have the same issue

**Comment by programster** [comment]
> 

@driesvints can yoiu re-open this issue now that you have the example info you asked for

**Comment by driesvints** [comment]
I'm sorry, but I don't think you should be using raw queries in that situation. Right now I don't have intention of reopening this.

**Comment by programster** [comment]
> I'm sorry, but I don't think you should be using raw queries in that situation. Right now I don't have intention of reopening this.

Your missing the point. The raw query in that case was simply to set up the state that the database is already in! Not a demonstration of the user using raw queries.

What is the user supposed to do if they are converting an existing codebase over to using Laravel, and the database (from the legacy system) already has primary keys that have an index name that Laravel is not expecting? This is what the sample codebase is trying to simulate to demonstrate the problem?

**Comment by warlof** [comment]
Hello,

I discover the exact same issue on my database using Postgres 15 and Laravel 10.

According to me, issue seems to come from this place https://github.com/laravel/framework/blob/e3350e87a52346af9cc655a3012d2175d2d05ad7/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L383-L388
https://github.com/laravel/framework/blob/256f4974a09e24170ceeeb9e573651fd5e1c703e/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L428-L433

In case a key name was provided, it's not used and hardcooded with current table name suffixed with `_pkey`

In my case, I had a table that I renamed.
The table was properly renamed - but the primary key was still using the previous table name as a constraint name prefix.

```php
    public function up()
    {
        Schema::rename('corporation_mining_observer_data', 'corporation_industry_mining_observer_data');
    }
```

With this simple migration, I moved the table from `corporation_mining_observer_data` to `corporation_industry_mining_observer_data`

![image](https://github.com/laravel/framework/assets/648753/e1aa8662-2e98-4c31-8324-3b2e6ddff1d4)

So now, if I try to drop the primary key using this code:

```php
    public function up()
    {
        Schema::table('corporation_industry_mining_observer_data', function (Blueprint $table) {
            $table->dropIndex('corporation_mining_observer_data_pkey');
            $table->primary(['corporation_id', 'observer_id', 'recorded_corporation_id', 'character_id', 'type_id', 'last_updated'],
                'obeserver_data_primary');
        });
    }
```

Laravel will replaced the provided name `corporation_mining_observer_data_pkey` with `corporation_industry_mining_observer_data_pkey`

And of course, it crash because the constraint `corporation_industry_mining_observer_data_pkey` does not exist in the database.

**Comment by hafezdivandari** [comment]
Fixed on Laravel 11.x via #50019
