### ISSUE TITLE
@json throw error when array is more than 3 items

### ISSUE THREAD

**Issue by ziming** [laravel/framework#42822]
- Laravel Version: 9.17
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 8

### Steps To Reproduce:

This below is fine. 3 items. Worked perfectly

```blade
@json(['view', 'form', 'tree'])
```

This below throw error. 4 items in the array.

Error message is Unclosed '[' does not match ')'

```blade
@json(['view', 'form', 'tree', 'code'])
```

If more than 3 items, error happen

To give some extra context,I'm using it like this

```blade
// work with 3 items in array
modes: @json($field['modes'] ?? ['form', 'tree', 'code', 'view']),
```

**Comment by npostman** [comment]
Give your array as a variable.. @json can get 3 parameters:
- your data to json encode
- json_encode flags (optional)
- depth (optional)

So:
```php
$array = ['view', 'form', 'tree', 'code'];
@json($array);
```

works

**Comment by ziming** [comment]
what I dont get is why is 1 item, 2 item, 3 items okay. but the 4th item onwards fail?

**Comment by npostman** [comment]
It is because of the way the blade directive gets compiled to PHP. Look at the method that compiles it down:

```php
protected function compileJson($expression)
    {
        $parts = explode(',', $this->stripParentheses($expression));

        $options = isset($parts[1]) ? trim($parts[1]) : $this->encodingOptions;

        $depth = isset($parts[2]) ? trim($parts[2]) : 512;

        return "<?php echo json_encode($parts[0], $options, $depth) ?>";
    }
```

It basically takes your @json parameters as a string, and explodes it at the comma. It then uses the first bit as your JSON data, the second bit as the json encode options and the third bit as the depth parameter.

So, your code `@json($field['modes'] ?? ['form', 'tree', 'code', 'view'])` would compile down to:

```php
<?php echo json_encode($field['modes'] ?? ['form', 'tree', 'code') ?>
```

For your use-case, you'd do something like this:

```php
@php
$modes = $field['modes'] ?? ['form', 'tree', 'code', 'view'];
@endphp
@json($modes);
```

Or you write a method that gets the modes:
```php
class SomeModel extends Model
{
    public function getModes() {
        return $this->modes ?? ['form', 'tree', 'code', 'view'];
    }
}

// And use it in your blade like so
@json($model->getModes());
```

**Comment by ankurk91** [comment]
```blade 
<script>
    var app = {{ Js::from($array) }};
</script>
```

**Comment by driesvints** [comment]
Please use a variable when working with the JSON directive.
