### ISSUE TITLE
Scoped container bindings accessed via Facade are not reset 

### ISSUE THREAD

**Issue by ankorstore-haddowg** [laravel/framework#43151]
- Laravel Version: 8.x
- PHP Version: 8.0.26
- Database Driver & Version: Mysql 8

### Description:
Accessing a scoped binding via a Facade will cache the resolved instance statically on the Facade meaning its not reset when the `scopedInstances` are cleared on the container.

I don't belive this is intended/desired or intuitive behavior and it certainly wasn't immediately obvious why my service was not being reinitialised within my workers.

I would be happy to attempt a pr to resolve if it is agreed that this this should be fixed.

### Steps To Reproduce:
- Create a scoped singleton binding in the container.
- Resolve this binding via a facade within a worker or octane server 
- resolved instance accessed via Facade is not cleared/reset between request/jobs.

**Comment by driesvints** [comment]
That's odd because that's exactly what's done here: https://github.com/laravel/octane/blob/1.x/src/CurrentApplication.php#L24

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by ankorstore-haddowg** [comment]
Apologies I actually never tested if the issue existed in an a octane context just assumed without checking 🙈.

My own issue was simply within queue workers in a vanilla laravel application.
I believe the issue is that this same Facade method call you linked to is not present here: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Queue/QueueServiceProvider.php#L198 in the workers reset scope callback after the scopedInstances are cleared. I can pr to add this, 
should I target 8.x or 9?

**Comment by ankorstore-haddowg** [comment]
Have raised pr to fix to 8.x, many thanks!
https://github.com/laravel/framework/pull/43215
