### ISSUE TITLE
Factory uses getForeignKeyName instead of getForeignPivotKeyName on morphToMany/belongToMany relationship

### ISSUE THREAD

**Issue by yazeed** [laravel/framework#43217]
- Laravel Version: 9.19
- PHP Version: 8.1.7
- Database Driver & Version: Postgres 14.4

### Description:
Factory has a bug where it tries to use getForeignKeyName() method instead of getForeignPivotKeyName() method on morphToMany or belongsToMany relationships causing the following error:

```
Call to undefined method Illuminate\Database\Eloquent\Relations\MorphToMany::getForeignKeyName()
```

### Steps To Reproduce:

- Create 4 models following the morph-to-many example from Laravel documentation with the pivot morph table.
- Attempt to create morph objects using the factory to create instances of the morphToMany model.

```
$user = User::factory()->create();
$posts = Post::factory()->count(10)->for($user, 'user')->create();
$tags = Tag::factory()->count(3)->for($user->posts[0], 'posts')->create();
```

- You will end up with the following error as factory attempts to use an erroneous method name getForeignKeyName() which only exists on BelongsTo/HasMany instead of getForeignPivotKeyName() which is the method name on BelongsToMany and MorphToMany relationships.

```
Call to undefined method Illuminate\Database\Eloquent\Relations\MorphToMany::getForeignKeyName()
```

### Conclusion? 

- getForeignKeyName() only exists on hasMany and belongsTo relationships. Factory should know when it's being used on a belongsToMany or morphToMany and use getForeignPivotKeyName() instead.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll re-open this once you can provide a repo. Thanks
