### ISSUE TITLE
Missing [doctrine/dbal] error when using model:show

### ISSUE THREAD

**Issue by weavdale** [laravel/framework#43284]
- Laravel Version: 9.21.0
- PHP Version: 8.1.8
- Database Driver & Version: sqlite

### Description:
when runing `php artisan model:show user` I get the error `Displaying model information requires [doctrine/dbal]`

### Steps To Reproduce:

`php artisan model:show user`

**Comment by jessarcher** [comment]
Hi @weavdale,

You'll need to install `doctrine/dbal` for this command to be able to inspect your database.

```sh
composer require --dev doctrine/dbal
```

@nunomaduro has a PR to do this automatically for you in future.

**Comment by nunomaduro** [comment]
Are you using the latest version of Laravel?

**Comment by adampatterson** [comment]
@nunomaduro humm, I was using 9.21.0. I updated to 9.22.1 and it works now 🤓

Thanks!

**Comment by garciaantonio20k** [comment]
For future readers

In Laravel 10 (last 10.x version) you found a error when install doctrine/dbal as requirement of php artisan db:show
The problem is a conflict between carbon 2.73.0 and doctrine/dbal 3.5.1.

My solution is , based in @jessarcher comment, install doctrine/dbal in a concrete version
`composer require --dev doctrine/dbal:3.* `

This install the 3.9.4 version and then you can use db:show and db:table command without problem

My setup is: 
PHP 8.1.10
Laravel v10.48.28
