### ISSUE TITLE
Horizon Commands Not Found

### ISSUE THREAD

**Issue by ajmeireles** [laravel/framework#43464]
- Laravel Version: 9.22.1
- PHP Version: 8.1.8 **(Laravel Sail)**
- Database Driver & Version: mariadb (latest)

### Description:
When I try to run any commands about Horizon in Laravel, for example `horizon:purge` or `horizon:terminate` the Laravel throws an exception that the command does not exist as below example:

![image](https://user-images.githubusercontent.com/60591772/181584460-de28d07c-af25-4063-a3b4-0c7bb1b77123.png)

The Laravel `about` command:

![image](https://user-images.githubusercontent.com/60591772/181586007-f38481a6-26a0-4e0c-9e92-2b23083b49ea.png)

### Steps To Reproduce:

Try to call any command about Horizon inside a Laravel application with same environment configurations.

### Note:

1. The "error" occurs with Horizon running or not.
2. The Horizon works fine.
3. The Horizon commands work fine in terminal:

![image](https://user-images.githubusercontent.com/60591772/181585752-dea21742-eee2-4291-89d9-12541c17e046.png)

**Comment by Quiss** [comment]
@ajmeireles Hi, this is not a bug, Horizon commands available run only in console

Proof:
https://github.com/laravel/horizon/blob/5.x/src/HorizonServiceProvider.php#L110

**Comment by rodrigopedra** [comment]
First, I believe this should have been reported on Horizon's issue tracker:

https://github.com/laravel/horizon/issues

Second, the reason this does not work is because most Horizon commands are only available in the console, they are not available during a HTTP request. The only exception being the `horizon:snapshot` command. Check its Service Provider on how it register its commands:

https://github.com/laravel/horizon/blob/a67fc86072087df8d49fadee17e69a5d67c36a14/src/HorizonServiceProvider.php#L108-L133

Therefore, this is not a bug, but intended behavior. If you believe this behavior should be changed I would advise you to send a PR to horizon or open a discussion thread here:

https://github.com/laravel/framework/discussions

As @Quiss already suggested, if you really want to run Horizon commands, other than `horizon:snapshot`, from a HTTP request you can use his code snippet to register the command on the fly.

I can't think of a use case to expose running these commands from an HTTP interface, but I am sure you have one. Not asking, no judgments.

Good luck =)

**Comment by driesvints** [comment]
Thanks all
