### ISSUE TITLE
Vite::asset() method not found

### ISSUE THREAD

**Issue by elidrissidev** [laravel/framework#43764]
- Laravel Version: 9.25.1
- PHP Version: 8.1.9
- Database Driver & Version: not relevant

### Description:
I'm trying to reference an image (`resources/images/auth_splash.jpg`) from a blade template following the [documentation section](https://laravel.com/docs/9.x/vite#blade-processing-static-assets), but I keep getting the error: `Call to undefined method Illuminate\Foundation\Vite::asset()`. I tried using both namespaces as there are 2 classes called `Vite`(`\Illuminate\Foundation\Vite` and `\Illuminate\Support\Facades\Vite`) but getting the same exact error.

Am I missing something here?

Thanks.

### Steps To Reproduce:

Try to reference a static asset stored in `resources` folder as mentioned in [documentation](https://laravel.com/docs/9.x/vite#blade-processing-static-assets).

**Comment by lhilton** [comment]
@elidrissidev I bumped into this issue as well. I ended up finding  #43702 for this problem. Confirming the fix, if you look at the latest version of the class:

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Vite.php

You will see that the `asset()` function was added on August 17, 2022. I am guessing this will be in the next release, probably 9.25.2 or whatever.

For the moment, since I'm pre-release on the effected software, I just copied stuff in place in the public folder and coded around the issue by hard coding those paths. A minor annoyance for me, but I only have a few images to deal with.

**Comment by timacdonald** [comment]
Apologies that the documentation has been merged before release on this one - but you are correct that the feature has been merged but not yet tagged. You will be able to access this feature when Laravel is released on Tuesday.

**Comment by alokVishu** [comment]
I cannot able to use `vite_asset` function in blade file.

**Comment by timacdonald** [comment]
There is no global helper. You should instead reference the `Vite::asset()` function.
