### ISSUE TITLE
Morph pivot table name conventions wrong when using MorphPivot model

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#43800]
- Laravel Version: 9.25.1
- PHP Version: 8.1.9
- Database Driver & Version: N/A

### Description:

You can tell a `morphToMany` or `morphedByMany` relations to use a Morph Pivot model by using a third parameter as the Model class name. This will also set the pivot table from it.

```php
return $this->morphToMany(Tag::class, 'taggable', Taggable::class).
```

The problem is that Eloquent tries to find the `subscription` table, where as it should be `subscriptions`. This is becase [`getTable()` in a `Pivot|MorphPivot`](https://github.com/laravel/framework/blob/b8db0d27f7dbefa0f066a7ca6472ea85e8fe2acc/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php#L155-L169) model doesn't returns the model plural, but rather the snake-singular.

```php
class Post extends \Illuminate\Database\Eloquent\Model {
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable', Taggable::class);
    }
}

Post::find(1)->tags()->dd();

// "select * from "tags" 
//    inner join "taggable" on "tags"."id" = "taggable"."tag_id" 
//    where 
//        "taggable"."taggable_id" = ? 
//    and 
//        "taggable"."taggable_type" = ?"
```

Here, the table should be `taggables` instead of `taggable`. This would force the developer to, unexplainably, set the table name property in the pivot model.

### What it should happen?

If the developer is setting the morph pivot model, it should always use the plural instead of a two-model-junction to guess the table. This shouldn't affect the normal pivot model (for belongs to many).

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!
