### ISSUE TITLE
Fluent JSON testing is invalid

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#43990]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9
- Database Driver & Version:

### Description:

I want to test exact response of the my api call.

Request returns many fields, but in my test I add only one field and test should be failed but the test is passed.

![image](https://user-images.githubusercontent.com/7753600/188263925-3b45dea2-601b-4af4-94c8-efc659e6ba1c.png)

But in the [documentation](https://laravel.com/docs/9.x/http-tests#fluent-json-testing) we have: 
`
If the etc method is not used, the test will fail if other attributes that you did not make assertions against exist on the JSON object.
`

I don't use `etc` method in my test.

How I can exact structure of the response?

### Steps To Reproduce:

Please take a look at screenshot above.

**Comment by sethsandaru** [comment]
> How I can exact structure of the response?

So basically you want to do something like this?:

```php
->assertExactJson([
    'data' => [
        'id' => $promotion->id,
        // more fields....
    ],
]);
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by siarheipashkevich** [comment]
Hi @driesvints it's very simple to reproduce.

Please create simple route:
![image](https://user-images.githubusercontent.com/7753600/188398493-4e754201-79b3-40fd-bc09-c0b7e7b02533.png)

and test:
![image](https://user-images.githubusercontent.com/7753600/188398791-0f128924-b205-47fa-a2a0-8e65476521e8.png)

**Comment by driesvints** [comment]
I see what's happening. This behavior only applies to top level attributes, not nested attributes. I've sent in a PR to clarify this in the docs: https://github.com/laravel/docs/pull/8185

**Comment by siarheipashkevich** [comment]
@driesvints thank you so much.

Could you please suggest how I can test nested structure in my case?

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
