### ISSUE TITLE
Eloquent count returning all times 1 when is spitted

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#44081]
- Laravel Version: 9.28.0
- PHP Version: 8.1.9
- Database Driver & Version:

### Description:
Eloquent count not working, when using Eloquent builder spitted.
So right now we need fetch all models, even millions, and after that we count all returned models ;/ Sounds like memory leak and incorrect value.

### Steps To Reproduce:
```php
$query = SomeModel::query()
    ->leftJoin()
    ->where()
    ->when()
    ->groupBy();

$a = $query->get()->count(); // return good value
$b = $query->count(); // return wrong value, always 1
```

**Comment by DarkGhostHunter** [comment]
Do you have data or a repo to reproduce this?

**Comment by rodrigopedra** [comment]
> Sounds like memory leak

Why? What hints you in this direction? I am genuinely curious.

This is known behavior. 

All aggregates methods on the query builder (`count`, `min`, `max`, `sum`, `avg`) return only the first result (see the `$results[0]` below)

https://github.com/laravel/framework/blob/004163a06fccd0e95fcd7f78989b6744b8f6325f/src/Illuminate/Database/Query/Builder.php#L3076-L3086

There were several similar issues, I will point to two lengthy ones, with deeper discussion on the rationale on this is would be an expected behavior.

- https://github.com/laravel/framework/issues/28931
- https://github.com/laravel/ideas/issues/1693

As always, if you believe this behavior should be changed, you could try a PR. But I would prepare a very lengthy defense on why this should be changed as this *"issue"* (or *non-issue*) comes up every once in a while.

P.S. actually it doesn't always return `1`, if you order by a different column where the first result is different than `1`, it will always return that. What happens is that it always returns the first record.

**Comment by DarkGhostHunter** [comment]
Since the same questions appears multiple times, it could be a good idea to push a PR for `countGroupsBy` and `countDistinctBy()`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by WilliamStam** [comment]
i feel this IS a bug tho. no idea how returning N1 from a group by is considered the "right" answer. if anything return an iterator or sum of all the values or something. 

`"illuminate/database": "^9.38"`

but anyways.. a potential solution.. since this totaly stumped me till i checked the query log (`$queries = \App\DB::getQueryLog();`:

```
$record_count = \App\DB::table( "fake" );
$record_count->fromSub($records->select(\App\DB::raw(1)),"query");
$record_count->count();
```

1. create a "fake" query builder
2. add a sub "from" `from (...) query` 
3. set the "sub query" to `select 1` instead of returning huge column data. not sure if this is needed but in my mind it seems like a good idea
4. do the normal ->count() 

results in a sub query ie

```
select count(*) as aggregate from (select 1 from table group by column1) as `query`
```

(PLEASE NOTE: this is JUST a demonstration query. please dont be all "but you could just do $records->count() and remove the group by", thats not the point, my queries are far more complex - this cause after much searching ive come to realize some people are... interesting.. a lot of the answers are "change your query")

**Comment by rodrigopedra** [comment]
> As always, if you believe this behavior should be changed, you could try a PR. But I would prepare a very lengthy defense on why this should be changed as this "issue" (or non-issue) comes up every once in a while.

As said before, If you do believe this should be changed, please send a PR. Up until now, all the discussions about it lead to the conclusion no change is needed.

Also, what I pointed out is that all aggregates return only the first row from the result set - by pointing out where in the code one could check it out - and that this is a known behavior. I understand the cause of frustration, but I also do understand the arguments around the current stance. I didn't make any value judgment around the matter.

PRs are always welcome, and if they provide enough explanation on the matter, they are actually reviewed. One option could be @DarkGhostHunter suggestion to add an alternative method implementation to cover the alternative outcome some people think is expected.

**Comment by WilliamStam** [comment]
other than a quick mention about potential performance (subjective?) what are the main reasons for this being an issue (or non issue as has been said). setting up a query builder and using groupBy (which is perfectly valid) and doing a count() and getting the first records aggregate seems very very strange to me. (`return $result[0]` - therby basicaly "throwing away" a bunch of info that the code originally requested)  

surely "this is my query, i want to know how many records it returns, so i use ->count()" is a valid expectation. instead.. "this is my query, i want to know how many records it returns.. o i cant unless i do a count(...->get()) and deal with that resource issue" or use the above. 

is there maybe an issue that makes it super hard to do in the code base? surely it shouldnt break any backwards compatibility.

im not being facetious with these posts. im just genuinely curious why some people feel that doing return $result[0] is considered "working as intended". ("we are too busy and its been like this a long time, we dont feel like changing it" is a perfectly acceptable response as well)

**Comment by LocalHeroPro** [comment]
It's hard to fix issue, because till now bunch of developers write tons of work around code and each one spend a lot of time figuring out what happened inside framework.
I think, good behavior is to fix that issues, even if they changing some "crazy" logic and bring that fix with new release. Then developers can read about breaking changes and have clear situation what have to working in what organized way.
