### ISSUE TITLE
Storage Facade doesn't catch `CorruptedPathDetected` Exception when `throw` is disabled

### ISSUE THREAD

**Issue by jacobmllr95** [laravel/framework#44244]
- Laravel Version: 9.31.0
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 5.7.38

### Description:

When trying to store a file with a corrupted filename with the `Storage` Facades `putFile` or `putFileAs` methods, a `CorruptedPathDetected` exception is thrown even though `throw` is disabled in the filesystem disk's configuration.

### Steps To Reproduce:

1. Build a file upload form using the `Storage` Facade.
2. Try to upload the following sample file.
3. Get a `CorruptedPathDetected` exception.

**Sample file:**
[Klteanlage Prfbefund.pdf](https://github.com/laravel/framework/files/9620553/K.lteanlage.Pr.fbefund.pdf)

**Comment by driesvints** [comment]
Can you please share a code example of how you're calling the filesystem?

**Comment by jacobmllr95** [comment]
I can reproduce it with the most basic example:

```php
$file = $request->file('file');
$path = $request->input('path');
$storagePath = 'files/' . $path;

if (Storage::putFileAs(dirname($storagePath), $file, basename($storagePath)) === false) {
    return response()->error('File could not be uploaded.');
}

...
```

**Comment by driesvints** [comment]
I talked this over with @frankdejonge but I personally feel this is something you should solve in the code before passing the path. Flysystem will normalize the path for almost every filesystem operation which means we'd have to catch the exception everywhere. Since it's not a true filesystem operation that goes amis but rather something you can solve up front I think it's best that we always inform apps and developers about this. So we won't be taking action here and suggest you sanitize your paths up front. Unsanitized paths can be misused by hackers.

**Comment by jacobmllr95** [comment]
@driesvints I get the point that I can handle it upfront but when there is a configuration option for `Storage` write operations that states wether exceptions will be thrown or just `false` is returned, I expect it to catch all possible exceptions during the write process.

**Comment by driesvints** [comment]
@jacobmllr95 I'm sorry but that's not what that option means. It's meant to catch *some* exceptions but not all. For example, if you're running into authentication errors in Flysystem, those will bubble up as well to indicate clearly what's going wrong. There's a difference between file operations and app related issues (like your own).

**Comment by jacobmllr95** [comment]
@driesvints Ok, I get that. Maybe it could be stated a bit more clear in the docs what it does and what not 👍

**Comment by driesvints** [comment]
We'd welcome a PR for that 👍
