### ISSUE TITLE
Illuminate/Support/Collection::Map take 70% of the request time

### ISSUE THREAD

**Issue by AdilAmanat** [laravel/framework#44455]
- Laravel Version: 8.44
- PHP Version: 8.1
- Database Driver & Version: Mysql 8

### Description:
using new relic I'm seeing that `Illuminate/Support/Collection::Map` take most of the request time. I'm using laravel nova 3.28 and seeing this on the `ResourceIndexController@handle`. 

<img width="1335" alt="Screenshot 2022-10-04 at 11 13 39 PM" src="https://user-images.githubusercontent.com/21098295/193894593-4dda73da-69cc-4199-8d26-c191b53dedb8.png">

<img width="1335" alt="Screenshot 2022-10-04 at 11 19 30 PM" src="https://user-images.githubusercontent.com/21098295/193895685-835ffdd1-b9c5-4203-bd2b-8949fc887dbe.png">

Please Help me with this because I have lost control at my end my query is running in 300ms but TTFB  is 11 seconds. The majority of the time is taken by the Collection map method.

**Comment by eduance** [comment]
This isn't a Laravel related issue, more a performance issue, check the Q&A section. However, I do like a fun performance question.

So, map() is by far the slowest due to its implementation using array_map. 

https://stackoverflow.com/questions/18144782/performance-of-foreach-array-map-with-lambda-and-array-map-with-static-function

Foreach: 0.7 sec
Map on closure: 3.4 sec
Map on function name: 1.2 sec.

PHP doesn't work asynchronously, that means that the interpreter has to read line by line and re-iterate every single time, set the context up every time you pass that same closure. Imagine the following:

You're giving your best friend a set of numbers: [6,5,9], and you ask your friend to multiply each number with 2. As a human, we tend to be really smart, and we know that 6 times 2 makes 12, we instantly know that 5 times 2 makes 10 and 9 times 2 makes 18.
But now imagine your friend has to look up the value, save that variable inside the memory, multiply that variable, put the value back in the variable, go over the next item, define that same variable, multiply that variable and so on.

To fix this, there are two things you can do:

1. Identify the collection it's trying to map over and chunk it.
2. See if you can add pagination and load a more relevant set of numbers, do you really need all those items to be mapped over and directly visible?

Let me know!

**Comment by AdilAmanat** [comment]
@eduance  This is the laravel related thing I guess check out the namespace of `Collection` in my question. As I mentioned in my question I'm using laravel nova and nova is actually doing it I'm not using directly this in my code. JFYI page where I'm seeing this issue is already paginated and only showing 25 records.

**Comment by eduance** [comment]
@AdilAmanat 

Open a issue with Laravel Nova, the map() method isn't broken in any way.

https://nova.laravel.com/docs/3.0/support.html

**Comment by rodrigopedra** [comment]
@AdilAmanat 

- How may items are you iterating in this collection?
- Are those items Eloquent models?
- What transformation are you doing inside your map function?

It is very hard to even try to understand where the eventual issue lies with only a stack trace screenshot. 

A code like this would spend a lot of its time on a `->map()` call too:

~~~php
return collect(range(1, 1000))->map(fn() => usleep(300_000));
~~~

So please provide more insightful information. 

So far I agree with @eduance , it is either a Nova issue, or a question for the support forums. 

No issue is being reported that we can relate to Laravel with the information you provide.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
