### ISSUE TITLE
`Model::preventAccessingMissingAttributes` is crashing with Mailable 

### ISSUE THREAD

**Issue by ankurk91** [laravel/framework#44558]
- Laravel Version: 9.35.1
- PHP Version: 8.1 (latest)
- Database Driver & Version: any

### Description:
My `users` table does not have `name` column, but Mailable is trying to access the `name` property on `$recipient` object.

https://github.com/laravel/framework/blob/31091a54085101f743960c9ca013058028e6ea35/src/Illuminate/Mail/Mailable.php#L687-L688

### Steps To Reproduce:

* Remove the `name` column from `users` table 
* Then update your code as follows

```php
// Enable in AppServiceProvider
Model::preventAccessingMissingAttributes(true)

// Some Controller method
$user = User::find(1)
Mail::to($user)->send(new ExampleMail());
```
* This will throw an exception

**Possible solution is to get attributes from array like**
```php
$recipient->toArray()['name'] ?? null
// or
$recipient->getAttributeValue('name') ?? null
// or
$recipient->attributes['name'] ?? null
```

There might be other components in core which are accessing non-existing model properties.

**Comment by milewski** [comment]
Also crashing with the default logout route:

```
The attribute [remember_token] either does not exist or was not retrieved for model [App\Models\User].
```

**Comment by axlon** [comment]
I mentioned this in the pr that introduced this feature, but to me it seems that the `__isset()` method on the model should catch this exception and return false.

Because if you really think about it, what the framework is trying to do here makes sense: it tries to set the name only if it exists. And it assigns the email without any safety checks because if the email doesn't exist the framework can't send the mail.

I don't think changing the framework to call `toArray()` on a model to prevent this is the way to go. Strict models should simply allow checking for attribute existence through isset (and by extension null coalesce)

**Comment by ankurk91** [comment]
Ping @inxilpro

**Comment by inxilpro** [comment]
@milewski with the `remember_token` issue, you need to update the `User::$rememberTokenName` value to whatever you use. If you don't use remember me tokens, just set that value to `null`.

@ankurk91  The `$recipient->name` issue is a little trickier. I think we may need to update Mailable to check for Model instances and either call `getAttributeValue()` or add a new helper method for checking if that attribute exists in the attributes array.

@axlon I still maintain that `isset()` on an un-retrieved column is problematic. Is it not set because it's not set (i.e. `null`) in the database? Or is it not set because I forgot to retrieve it?

This is definitely the trade-off of the added "strictness" though. Let me see if I can come up with a decent solution.

**Comment by inxilpro** [comment]
So I put together a draft PR with a potential solution: #44639

But honestly, the more I think about it, the more I think this is expected behavior. The `Mailable` doesn't know if your model doesn't have a `$name` property, or if you didn't retrieve it. A better solution might be to offer something like an `Emailable` contract that you can implement to account for the fact that your model works differently. Something like:

```
interface Emailable
{
  public function getEmailAddress(): Illuminate\Mail\Mailables\Address;
}
```

You could either implement that or create an accessor for the `$name` attribute if you prefer.

**Comment by inxilpro** [comment]
> Since Laravel presents model attributes as regular properties, isset should just work, null coalesce should just work, etc., etc.

And it does. The default behavior is that it *just works.*  You have to explicitly opt-in to this feature. And if you do, you now need to play by new rules—one of which is, "if you're using functionality that expects a `$name` property on the model, but one doesn't exist, you must create an accessor for it."

This is only a bug because:

1. they opted-in with `Model::preventAccessingMissingAttributes()`, and
2. they chose to not use the default `$name` attribute in their `User` model.

There should 100% be a way to make things work in this scenario, but I actually think this is a perfectly good example of what `preventAccessingMissingAttributes` is meant to guard against. Before, Laravel was happily ignoring the fact that there's no `$name` attribute. With that opt-in feature turned on, you now need to decide explicitly how to account for the fact that it doesn't exist.

**Comment by axlon** [comment]
> Before, Laravel was happily ignoring the fact that there's no $name attribute

I think that's where we fundamentally disagree then. In my eyes Laravel _did_ account for that property missing, it uses a null-coalesce to ensure that code should not break in the event of the attribute not being there.

And that is also the exact reason I feel what is happening here is a bug in the new strict mode (no hard feelings though! I actually like the idea overall)
