### ISSUE TITLE
Route Model Binding issue with SQLSRV

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel/framework#44593]
- Laravel Version: 9.35.1
- PHP Version: 8.1.11
- Database Driver & Version: Microsoft SQL Server 2019 v15.00.4198.2.v1 

### Description:
When using route model binding, if a user enters a string instead of the expected integer for the URL parameter, an `Illuminate\Database\QueryException` is thrown instead of the expected 404 response via a `ModelNotFoundException`.

For example, if I have the route:
```
Route::get('users/{user}', [UsersController::class, 'show']);
```

With the controller method:
```
public function show(User $user) {
    dd($user);
}
```

We would expect the user to invoke the route with something like `https://example.app/users/3`. This works as expected. However, if a user accidentally passes a string for the user parameter (`https://example.app/users/asdf`), instead of throwing a `ModelNotFoundException`, SQLSRV throws a `Illuminate\Database\QueryException` with the error that we are passing incorrect types (Error converting data type nvarchar to bigint).

`ImplicitRouteBinding.php` contains the logic for running the query to find the model and to throw a `ModelNotFoundException` if it is not found. Line 59 runs the query to see if the model exists, or it throws the exception:
```
} elseif (! $model = $instance->{$routeBindingMethod}($parameterValue, $route->bindingFieldFor($parameterName))) {
    throw (new ModelNotFoundException)->setModel(get_class($instance), [$parameterValue]);
}
```

I would submit a PR for this, but I am unsure how this should best be handled. Being a database driver specific issue, I'm not sure if adding a try/catch block in the route binding logic is the cleanest way to handle this. This does appear to be the default configuration for SQLSRV as we are using a new AWS RDS instance without any config changes.

I would certainly expect a 404 be returned in this case instead of a database error being thrown.

**Comment by rodrigopedra** [comment]
@aaronhuisinga in the meanwhile you can use route parameter constraints so the router does not match any route when using string instead of parameters:

~~~php
Route::get('/user/{user}', function (User $user) {
    //
})->where('user', '[0-9]+');
~~~

reference: https://laravel.com/docs/9.x/routing#parameters-regular-expression-constraints

If you are willing to try a PR, you can try checking a model `$keyType`, which is accessible through the `Model@getKeyType()` public method.

As the method you referenced in `ImplicitRouteBinding` already makes a model instance before resolving the route paramenter, you could then check if its key type matches the provided parameter.

reference: https://laravel.com/docs/9.x/eloquent#primary-keys

**Comment by driesvints** [comment]
We’ve had this issue before. Unfortunately there’s no way to know which column type the database column has. You’ll have to solve this like @rodrigopedra explains.
