### ISSUE TITLE
`Model::handleLazyLoadingViolation` behaves differently with a custom handler

### ISSUE THREAD

**Issue by aarondfrancis** [laravel/framework#44611]
- Laravel Version: 9.35.1
- PHP Version: NA
- Database Driver & Version: NA

### Description:

I'm not sure if this is intentional or not, but if the developer provides a `lazyLoadingViolationCallback` handler the `handleLazyLoadingViolation` behavior seems wrong.

In the default execution (no custom handler) the violation is not triggered if the model doesn't exist or it was recently created.

If the developer provides a callback, that safety check is skipped and a violation is triggered, even though it's not truly a violation.

Here's the relevant code, from [HasAttributes.php#L551](https://github.com/laravel/framework/blob/faf384276ee437c556eabc1fed4c6262ce8103d2/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L551)
```php
protected function handleLazyLoadingViolation($key)
{
    if (isset(static::$lazyLoadingViolationCallback)) {
        return call_user_func(static::$lazyLoadingViolationCallback, $this, $key);
    }

    if (!$this->exists || $this->wasRecentlyCreated) {
        return;
    }

    throw new LazyLoadingViolationException($this, $key);
}
```

The safety check (`exists` and `wasRecentlyCreated`) was added after the fact, so I think it might just have gotten put in the wrong place?

It's possible that this was done on purpose, but I'd say it's not actually a violation until the existence check has passed.

If y'all think this is a bug, I can open a PR for it. If this is intended, feel free to close!

**Comment by juse-less** [comment]
Since no one else has answered yet, I thought I'd give a different point of view.

Logically speaking, when you provide your own handler, be it for `Model::preventLazyLoading()`, or anything else, you normally do that to override the default logic.

Not enforcing the default logic leaves more room for those wanting to override that logic, instead of enforcing it.

I guess there's two pieces in this -
1. Check if _you_ believe it's a violation
1. if (1), handle the violation, the way you see fit (which may or may not include throwing that Exception, or another)

I _think_ the usual way these things are done in Laravel, is to have everything in a default callback, and call that instead of the custom one, if no custom one is defined.
But this method is so small, maybe that's the reason it was used entirely instead of a default callback?
Which I guess could cause some confusion as to if something is intentional or not.

**Comment by driesvints** [comment]
Hi Aaron. This was probably done on purpose to give full control to the developer on what the behavior should be.
