### ISSUE TITLE
[BUG] - Squashing Migrations is not taking updated Auto Increment Value

### ISSUE THREAD

**Issue by hirenkeraliya** [laravel/framework#44644]
- Laravel Version: v9.28.0
- PHP Version: 8.1
- Database Driver & Version: 8.0.30

### Description:

When we reset the auto-increment value of the new table by using `->from(100)` Laravel `schema:dump --prune` it's not taking the auto-increment value inside the dump file. Ideally, we need to add `AUTO_INCREMENT=100` at the end of the table creation SQL query.

### Steps To Reproduce:

Migration looks like 
```
Schema::create('test_table', function (Blueprint $table) {
    $table->increments('id')->from(100);
    $table->string('name');
});
```
And the generated schema should be like this:

```
CREATE TABLE `test_table` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=100;
```

It is not adding `AUTO_INCREMENT=100` on the dump File.

Thanks, Let me know if I was missing something.

**Comment by driesvints** [comment]
Hi @hirenkeraliya. Thanks for reporting this. At first glance this seems like a bug with `mysqldump` and not Laravel. I found https://bugs.mysql.com/bug.php?id=14515 which notes something similar got fixed in MySQL 5.1 however when I browse [the manual of 8.0](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) I cannot find anything about this. I have no idea how to manipulate `mysqldump` to also include the auto incrementing value. I think it's best that you file a bug report with MySQL itself as this isn't Laravel specific it would seem.
