### ISSUE TITLE
Queue retry doesn't use the flag $deleteWhenMissingModels

### ISSUE THREAD

**Issue by honekawa-yamazaki** [laravel/framework#44949]
- Laravel Version: 9.x.x
- PHP Version: 8.1
- Database Driver & Version: Mysql 8

### Description:
When a job failed, and I run the command `php artisan queue:retry all`, it gave me an error: "No result for model [...]". Although I already have the flag `public $deleteWhenMissingModels = true` inside my job class.

### Steps To Reproduce:
- Create a sample job that uses a model resource instance, like `__constructor(\App\Models\SampleModel $model)`.
- Add `public $deleteWhenMissingModels = true;` to the job class.
- Throw an exception inside the job to make it fails.
- Delete the model resource from the database.
- Run `php artisan queue:retry all`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing until a repo is provided

**Comment by samizdam** [comment]
Actual, has same issue. 
It should be handled in  \Illuminate\Queue\SerializesAndRestoresModelIdentifiers::restoreModel (https://github.com/laravel/framework/blob/10.x/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php#L109). 
$deleteWhenMissingModels handled in CallQueuedHandler, but not for failed job on unserializing. 

PS: Serialization -- bad magic.
