### ISSUE TITLE
Arr::get != data_get, structure

### ISSUE THREAD

**Issue by dgoring** [laravel/framework#44982]
- Laravel Version: 9.40.1
- PHP Version: 9.1
- Database Driver & Version:

### Description:
Arr::get != data_get

Not sure why these are different,
code wize shouldn't all the data_* functions just be aliases of the Arr::* functions which is why it confuses me why they are intertwined in stead of Arr:: being able to exist on its own

if you do move everything to `Arr` please preserve the code in data_get as has more functionality 

### Steps To Reproduce:
```php
data_get(['test' => 'value'], ['test']) // -> 'value'

Arr::get(['test' => 'value'], ['test']); //-> ['test' => 'value'] + error
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rodrigopedra** [comment]
> code wize shouldn't all the data_* functions just be aliases of the Arr::*

Do you have any link to the docs (current or older) that suggests that? Since I started working with Laravel (around 2015, version 5.0), I never saw a mention, or suggestion, in the docs that these helpers should behave the same.

`data_*` helpers operates also on objects and collections, while `Arr` helpers (and previously `arr_*` helpers) do not.

For example, let's review the docs on `Arr::get()`

> The Arr::get method retrieves a value from **a deeply nested array** using "dot" notation

https://laravel.com/docs/9.x/helpers#method-array-get

And for `data_get()`

> The data_get function retrieves a value from a nested array **or object** using "dot" notation
>
>The function also accepts **wildcards using asterisks**, which may target any key of the array **or object**

https://laravel.com/docs/9.x/helpers#method-data-get

As you can see, one difference is that `data_get` accept wildcards in the key path, while `Arr::get()` does not.

Not sure what you were trying to accomplish here:

```php
Arr::get(['test' => 'value'], ['test']); // INVALID
```

But that is invalid syntax, as the second parameter, the key, should be a string, an int or null

https://github.com/laravel/framework/blob/171d0dccddd061e119170e063167b72e7c7cd632/src/Illuminate/Collections/Arr.php#L300-L308

I suggest you to read through the docs on these helpers to understand their differences and when to use one or another:

https://laravel.com/docs/9.x/helpers#arrays-and-objects-method-list

> if you do move everything to Arr please preserve the code in data_get as has more functionality

It does not. They actually have distinct functionality. And they are expected to be different.
