### ISSUE TITLE
Request from API Laravel to another API Laravel returns Malformed UTF-8 characters

### ISSUE THREAD

**Issue by douglascaddoweb** [laravel/framework#45025]
- Laravel Version: 8.0
- PHP Version: 7.3.3
- Database Driver & Version: mysql 5.7

### Description:

Hi guys, 

I have two applications develop with Laravel and the sames configurations. 

In the first application, I  return data in route api. When I send request from insominia or postman, the response  status 200 and data is ok.

In the second application, I send request to route the first application, but I get response status is 500 and the message is InvalidArgumentException: Malformed UTF-8 characters, possibly incorrect (truncated...).

I was try with another api that I have and returned success, but this request to  API in laravel is not work. 

I think that be anything on header the response, but I don't know.

The return API from first application is this...

```
$dados = AnoModel::get();
return response()->json((string)$dados, 200);

```

And I send request with Http Client Facade and is this...

```
$response = Http::get('http://continentaladmin.deltacode.com.br/api/years')->throw();
$data = json_decode($response->getBody());
```

Can anybody help me?

**Comment by teikun-86** [comment]
Maybe try to change the
```php
$dados = AnoModel::get();
return response()->json((string)$dados, 200);
```
to
```php
$dados = AnoModel::get();
return response()->json($dados, 200);
```

**Comment by rodrigopedra** [comment]
First, docs says this about support questions:

> Laravel's GitHub issue trackers are **not intended** to provide Laravel help or support. Instead, use one of the following channels...

https://laravel.com/docs/9.x/contributions#support-questions

Please review the link above for the support channels.

Second: Laravel 8.x is unsupported. It will receive Security Fixes until January 24th, 2023, but, in general, it won't accept any bug fixes anymore.

https://laravel.com/docs/9.x/releases#support-policy

So if you think the behavior you describe is a bug, please upgrade to a supported version (Laravel 9), and check if the behavior has been corrected already.

Third, as @teikun-86 suggested, you don't need to cast to string when returning a Laravel collection. 

Your issue seems to be you are double encoding the JSON response. When you cast a collection to a string it already encodes it as a JSON, then the `response()->json()` will encode it to JSON again. 

Please review the docs on how to use JSON responses:

https://laravel.com/docs/9.x/responses#json-responses

And here is the reference on `EnumeratesValues@__toString()` method (`EnumeratesValues` is a trait used by `Collection`)

https://github.com/laravel/framework/blob/5813acbeaf6a030c2c70c137c8b6612e4823fdc4/src/Illuminate/Collections/Traits/EnumeratesValues.php#L890-L900

**Comment by mmkhakdaman** [comment]
try this
```
$dados = AnoModel::get()->toArray();
return response()->json($dados, 200);
```

**Comment by douglascaddoweb** [comment]
Hi guys,

Thanks for the answer.

@teikun-86  and @mmkhakdaman I was try with you did mention, but I not success, already seen in foruns and mainly the documentation of Laravel, I used all examples that I seen but any not work.

```
$dados = AnoModel::get()->toArray();
return response()->json($dados, 200);

OR
$dados = AnoModel::get();
return response()->json($dados, 200);

OR

$dados = AnoModel::get();
return response($dados);

OR 

$dados = AnoModel::get();
return response()->json($dados, 200, [],JSON_UNESCAPED_UNICODE );
```

I think that be a bug of laravel, because I try in APIs that was develop with another languages, for example, C# or same until PHP without framework and were work fine.

@rodrigopedra Sorry by write here, but really I thinking that a bug, I don't knew that this version is unsuported. I'll try update this version.

**Comment by rodrigopedra** [comment]
@douglascaddoweb, if you think it is a bug, there is no problem at all on reporting it here. 

Maybe I was misled by your wording and the code sample provided. It seemed more a support request than a bug report. I apologize for misunderstanding it.

Can you put up an example repository, with a data seeder that generates the issue, so we can replicate the issue?

Or at least provide some sample data that shows the issue happening?

**Comment by douglascaddoweb** [comment]
@rodrigopedra no problem, my english no is so good, sorry.

But I updated the PHP to version 8.
Send a new request and for my surprise, the request returned all data. 

I think that problem was the version of PHP.
I was use the version 7.3 and update to 8.0

Thanks guys for the interaction.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
