### ISSUE TITLE
Laravel 9. Migration Silently Fails with SQLite when Dropping and Adding a Column in the Same Modification 

### ISSUE THREAD

**Issue by Sunhat** [laravel/framework#45058]
https://github.com/laravel/framework/issues/39442

Laravel Version: 9.38.0
PHP Version: 8.1
Database Driver & Version: SQLite 3
OS: MacOS and Docker ubuntu latest
Description:
This is an easily re-producible bug that is consistent across new and old installations of Laravel 8 & 9. It was already reported, and has been a bug in Laravel for over a year. @driesvints couldn't be bothered to investigate, so closed the issue.

https://github.com/laravel/framework/issues/39442

Create migration with drop col and new columns
Write a test that reads or writes this field
Watch it not exist

@driesvints In my previous ticket, I reported this as Laravel 8 forgetting Laravel 9 exists. I'm using Laravel 9. The same bug exists. If you waste more of my time, I'll bill you. You've been handed the exact lines of code responsible for this, and that obviously hasn't changed.

@driesvints Open source, yes, that means I'm contributing to your project for free. You're rude and lack the curiosity to be a developer. I hope to God you're not actually paid.

**Comment by Sunhat** [comment]
@taylorotwell Your employee is closing bugs that actually exist, because he's arrogant and childish.

**Comment by freekmurze** [comment]
@SunhatWith this attitude, don't count on any support at all. Imagine that somebody would talk in that way to you. Would you be motivated to help that person out?

The bug that you are encountering might not be important for others.  

Do mind your tone of voice and stay friendly. This not only applies to this issue tracker but for interactions with all living things.

Some interesting resources:
- https://blog.container-solutions.com/entitlement-in-open-source
- https://opensource.com/article/22/1/open-source-contributions-career
- https://www.youtube.com/watch?v=fMFjO2szDnk

**Comment by Sunhat** [comment]
@freekmurze I've displayed absolutely no sense of entitlement. I urge you to re-read what's actually happened

1. A ticket was opened a year ago and @driesvints refused to investigate.
2. I opened a new ticket with a typo relating to an unsupported version. @driesvints closed the ticket, despite common sense suggesting this bug still exists.

My tone is perfectly fine when addressing rude children.

**Comment by freekmurze** [comment]
> If you take on an open-source project, you owe everyone everything. That's the sacrifice you chose. If you can't hack it, then don't do it.

I guess are differences come because we don't agree on this at all. If somebody invests time creating a library, you play by the rules of the creator / maintainer. Don't assume that you as a contributor can set the rules. A creator/maintainer owes you nothing. Not even if you come with the gift of opening an issue.

Personally, I think your stance on open source will leave both you and maintainers of open source software feel bad. There are no winners with such an attitude. 

You can find the code of conduct of Laravel here: https://laravel.com/docs/9.x/contributions#code-of-conduct

> Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
> Behavior that can be reasonably considered harassment will not be tolerated.

I think suggestion that someone should be fired surely goes against to rules set by the creators / maintainers.
