### ISSUE TITLE
Mailable containing replyTo Address with name shows an RFC 2822 error

### ISSUE THREAD

**Issue by fylzero** [laravel/framework#45162]
- Laravel Version: 9.42.2
- PHP Version: 8.1.8
- Database Driver & Version: mysql  Ver 8.0.29 for macos12.2 on arm64 (Homebrew)

### Description:
When sending a mailable with a replyTo address that includes a name, it throws the following error
```
Email "Name Of Recipient Here" does not comply with addr-spec of RFC 2822.
```

This seems to be happening due to the combination of Address in replyTo only passing the name value and nullifying the email address.  replyTo is essentially only receiving the name field here.

### Steps To Reproduce:

- Fresh copy of Laravel
- Setup a way to receive email - I am using Helo (from beyondco.de)
- Create a mailable and method of firing mailable
- In the Envelope add a replyTo entry (per the Laravel docs: https://laravel.com/docs/9.x/mail#using-the-envelope - bottom example)
- Send the mailable (via command, route, however)
- This error will occur:  `Email "Name Of Recipient Here" does not comply with addr-spec of RFC 2822.`

Note:  This does not happen if replyTo is inside an array.  I submitted this to the docs as it was tripping me up in a recent Laravel 9 upgrade.  Not sure if this is a bug or if the change made to the documentation before being added is incorrect.  https://github.com/laravel/docs/pull/8370

Repo created to demo issue here:
https://github.com/fylzero/laravel-reply-to-issue

Relevant files are:
app/Console/Commands/SendMailCommand.php
app/Mail/MerpDerpMail.php

**Comment by PerryvanderMeer** [comment]
In my opinion, it's better to just update the docs, since `Envelope` expects params `to`, `cc`, `bcc` and `replyTo` to be an array.

https://github.com/laravel/framework/blob/1dc597098b7c30fb71cde8247c5f9a91e84e021b/src/Illuminate/Mail/Mailables/Envelope.php#L92

When passing an `Address` object directly to `replyTo`, [`normalizeAddress`](https://github.com/laravel/framework/blob/1dc597098b7c30fb71cde8247c5f9a91e84e021b/src/Illuminate/Mail/Mailables/Envelope.php#L111) is getting mad.

**Comment by fylzero** [comment]
@PerryvanderMeer Thanks for confirming and resubmitting that!

**Comment by fylzero** [comment]
Docs have been updated, thanks again @PerryvanderMeer
