### ISSUE TITLE
Migration constrained error

### ISSUE THREAD

**Issue by abdosaeedelhassan** [laravel/framework#46126]
- Laravel Version: v10.0.0
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
in migration table i added field like next,
`
$table->foreignIdFor(\App\Models\User::class, 'createdby_id')->constrained()
`
when i try doing migration i received next:
![Screenshot from 2023-02-15 10-36-21](https://user-images.githubusercontent.com/15355610/218981230-8ec61895-d8e1-47eb-ad4c-0f41ca0cbeb7.png)

but when i added on table like next:
`
$table->foreignIdFor(\App\Models\User::class, 'createdby_id')->constrained()->on('users')
`
it worked success like next
![Screenshot from 2023-02-15 10-44-17](https://user-images.githubusercontent.com/15355610/218985673-1a0fb144-86a5-4228-8cc0-9b521623e6c2.png)

### Steps To Reproduce:

i think that when using foreignIdFor and specifying model the table name will automatically setting for this model table name, so that    the method constrained if called without passing table name will be check firstly if table name specified in previous step.

Thank you

**Comment by falko100** [comment]
I think this is expected behaviour.
The `constrained` method of the `ForeignIdColumnDefinition` has no knowledge of the model.
The model is used in `foreignIdFor` to determine the type of the foreign id column and the column name.
Afterwards the model isn't remembered, so the `constrained` cannot access the `$table` property of the model, hence the need for specificity.

The solution you might by looking for is:
```php
$table->foreignIdFor(\App\Models\User::class, 'createdby_id')->constrained('users')
```

**Comment by abdosaeedelhassan** [comment]
@falko100 thank you for explanation, you are right that what current exists, also i think this  will be additional advantage because there is no other table need to linked except that is foreign key for, feel free to close this  issue.
Thank you.

**Comment by driesvints** [comment]
Thanks @falko100
