### ISSUE TITLE
IPv6 URLs with square brackets are not supported by Laravel's routing system

### ISSUE THREAD

**Issue by hasanemreozer** [laravel/framework#46315]
- Laravel Version: 9.x
- PHP Version: 8.2
- Laravel UI

### Description:
When attempting to access a Laravel project through an IPv6 URL that includes square brackets, Laravel encodes the square brackets in the URL, which causes routing issues. This can prevent the project from functioning correctly, as routes may not be resolved properly.

For example, if I try to access `http://[xxxx:xxxx:xx:xxxx::xx]/`, Laravel will encode the square brackets in the URL as `%5B` and `%5D`, resulting in the following URL: `http://%5Bxxxx:xxxx:xx:xxxx::xx%5D/`. This causes the route to fail and the application to malfunction.

Another example, if a user tries to access the root of a Laravel project through an IPv6 URL, such as `http://[xxxx:xxxx:xx:xxxx::xx]/`, Laravel should redirect them to the login page at `/login`. However, due to the URL encoding issue described above, the redirect URL is encoded as `http://%5Bxxxx:xxxx:xx:xxxx::xx%5D/login` in the `Location` header, causing the browser to fail to redirect and resulting in an error.

While some solutions have been suggested to disable URL encoding or modify the route function, these approaches may have security risks and may not be ideal for all projects.

Therefore, I propose that Laravel's routing system should be updated to support IPv6 URLs with square brackets without encoding them, allowing for proper routing and improved compatibility with modern networking technologies.

Thank you for your consideration.

**Comment by driesvints** [comment]
We use Symfony Router behind the scenes so therefor any route matching issues should be opened on their repo instead. Thanks

**Comment by MuriloChianfa** [comment]
Hello guys, recently i tested my system acessing by IPv6 addresses and have the same throubble of this.

Tested in two system:
- First => using Laravel 7 + PHP 7.2
- Second => using Laravel 10 + PHP 8.2

For the private proposes, im using the loopback ::1 IPv6 address, to anyone can be reproduce easylly.
The problem is in route() helper, that encodes the IPv6 brackets from access URL:

![expliciting-ipv6-brackets-encode](https://github.com/laravel/framework/assets/60560085/9efe29d5-c178-4e51-af1c-5f1f22dfd431)

But notice that this does not happen with secure_url() helper

![image](https://github.com/laravel/framework/assets/60560085/0fdf56e4-50d8-4969-ada6-a6c31167d31d)
![image](https://github.com/laravel/framework/assets/60560085/5dba0e3f-3a9c-4994-85f2-c958b9850153)

Searching for the problem into Symfony Router as describred by @driesvints, i dont finded anything, theferore back to laravel and have founded the list of characters to reverse the URL encode [$dontEncode](https://github.com/laravel/framework/blob/c59d540ab142d36ee0f62c3ddc749329a968466b/src/Illuminate/Routing/RouteUrlGenerator.php#L36).

Confirming the problem here:
![testing-laravel-framework-ipv6-encoding-brackets-in-domain](https://github.com/laravel/framework/assets/60560085/d97155b2-96b2-4c97-bc8d-7caf72e8d0ca)
Console output:
![viewing-logs-for-laravel-framework-ipv6-encoding-brackets-in-domain](https://github.com/laravel/framework/assets/60560085/f3c378f1-adc7-435f-aec1-a7f256fb282c)

And adding the IPv6 brackets to this list, the problem is solved =D

**Comment by JC5** [comment]
Is there a fix for this please?

**Comment by NiKiZe** [comment]
Seeing the same thing using LibreNMS
Tracing this down it comes down to: https://github.com/laravel/framework/blob/13.x/src/Illuminate/Routing/RouteUrlGenerator.php#L88-L101

To see what happens:
```php
        // First we will construct the entire URI including the root and query string. Once it
        // has been constructed, we'll make sure we don't have any missing parameters or we
        // will need to throw the exception to let the developers know one was not given.
        $uri = $this->addQueryString($this->url->format(
            $root = $this->replaceRootParameters($route, $domain, $parameters),
            $this->replaceRouteParameters($route->uri(), $parameters),
            $route
        ), $parameters);
print_r($root);
print_r($uri);

        if (preg_match_all('/{(.*?)}/', $uri, $matchedMissingParameters)) {
            throw UrlGenerationException::forMissingParameters($route, $matchedMissingParameters[1]);
        }

        // Once we have ensured that there are no missing parameters in the URI we will encode
        // the URI and prepare it for returning to the developer. If the URI is supposed to
        // be absolute, we will return it as-is. Otherwise we will remove the URL's root.
        $uri = strtr(rawurlencode($uri), $this->dontEncode);
print_r($uri);

```

This results in:
http://[::1]
http://[::1]/login
http://%5B::1%5D/login

I think it is wrong to do rawurlencode on the full uri, should only be done path and querystring
The special char exclusion logic is also on the dangerous side.

And then more mangling of the uri being done if !$absolute
~~I don't think this can be fixed as suggested in https://github.com/laravel/framework/pull/47802, rather~~ this function might need to be reconsidered, encode the separate parts only, and return what is relevant. (Actually that is what that PR is doing, but the exclusions should be removed as well, and only the individual parts of path and querystring keys and values should be encoded, you can never do that on a full string.) or does anyone actually think that schema or host part should be encoded?

Another point to this is $root which is no longer used.
A possible assert/sanity check would be to ensure that after the encode $uri does start with $root, if it does not, something is very wrong.

This was closed by @driesvints as being an issue in Symfony, but the bug is clearly in Laravel? - So since this bug is still here, and I can't find any other issue, could we reopen this, or should there be a new issue created?
