### ISSUE TITLE
Problem with withoutOverlapping in Schedule

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/framework#46334]
- Laravel Version: 9.50.2
- PHP Version: 8.1.16
- Database Driver & Version: MySQL
- Driver CACHE: DYNAMODB

### Description:

I have been using the same scheduler for some time without problems with the withoutOverlapping option, if I update laravel framework from 9.50.2 to another version major the my schedule not work anymore. If run downgrade 9.50.2 the scheduler starts working again. My code is:

### My Code (cache with DynamoDB)

```php
protected function schedule(Schedule $schedule)
{
    $schedule->command('database:traces:mails')
        ->everyMinute()
        ->onOneServer()
        ->environments(['production'])
        ->withoutOverlapping();

    $schedule->command('suppliers:update:reorders')
        ->everyMinute()
        ->onOneServer()
        ->environments(['production'])
        ->withoutOverlapping();
}
```
### Crontab status run OK with anywhere release
![image](https://user-images.githubusercontent.com/5731295/222533772-af6ef8a3-be09-4c30-9aac-038595d0a6c8.png)

**Comment by driesvints** [comment]
Are you saying you're attempting to update to another 9.x version or to 10.x?

**Comment by massimodellarovere** [comment]
> another 9.x version

**Comment by driesvints** [comment]
I think it might be related to https://github.com/laravel/framework/pull/45963. If you revert that code, does it work for you?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by mrhn** [comment]
@driesvints i have experienced similar issue, i firstly saw the reference to #45963 now, will investigate tomorrow.

My team experienced this issue, on a setup that has been running withoutOverlapping for at least 6 months.

On an upgrade to Laravel 10.x, the key that was set in dynamodb was not cleared. This is on a default Vapor setup.

In the logs from the scheduler we have this that is interesting.

The withoutOverlapping task is scheduled for each minute. The log line before the scheduler is breaking and the log line where the scheduler is broken. It calls the cmd, that executes insanely fast, which the command by nature never will.

Running ['artisan' some:cmd] ......... 4,487ms DONE
Running ['artisan' some:cmd] ......... 7ms DONE

Like the poster we have a setup where two scheduled cmds run without overlap and we are discussing if these two are conflicting but there is some evidence pointing that direction and some pointed another direction.

We added a manual log on the callbacks you can use on the scheduled tasks, this was not logged on the cases where it executes with the 7ms execution time. This problem is not instantly occurring but are occurring after some time, but has been reliably happening each day since we upgraded 4-5 days ago.

**Comment by massimodellarovere** [comment]
Unfortunately not having time to thoroughly analyze the problem I was stuck at version 9.50.2 as I update no longer works any scheduler and there are no errors indicated in the log.  I have a complicated installation with my customer with more than 40 schedules and at the moment or decided to stay stuck at version 9 until you find out why.

**Comment by mrhn** [comment]
Just for info, no errors in the logs too here. So we are on the same page, we are so lucky that we only have two witouthOverlap schedules and one of them has changed so much we actually can remove this.

**Comment by mrhn** [comment]
> After only having one scheduled command using withoutOverlapping(), the problem disappeared.
> 
> This smells like the cache lock changes, with multiple commands at the same time is fighting for the locks. Ending in a state where one is not released.

After this change it occurred again over the weekend.

**Comment by mrhn** [comment]
Seems like the commit https://github.com/laravel/framework/commit/965d77e754e01ca9b0644ca29d52e840bb52b59e fixes the issue @massimodellarovere haven't tested it yet.
