### ISSUE TITLE
User enumeration still possible through password reset functionality

### ISSUE THREAD

**Issue by williwlwilliwll** [laravel/framework#46465]
- Laravel Version: 9.52.4
- PHP Version: 8.2.3
- Database Driver & Version:

It is still possible to determine whether a user exists with a given email address by comparing the time taken for a password reset request against a request made for a known non-existent user. 

A user has posted a fix in the thread of an earlier issue (https://github.com/laravel/framework/issues/13658#issuecomment-785023918) but it would be good if it could be addressed by the framework itself  (as Symfony did - https://symfony.com/blog/cve-2021-21424-prevent-user-enumeration-in-authentication-mechanisms) so that all deployments are protected out-of-the-box. Is such a change in your roadmap? 

Thanks

**Comment by valorin** [comment]
Laravel's Timebox, which is currently in use on login verification could be used for this - rather than using a random delay (which isn't fully secure): https://github.com/laravel/framework/blob/10.x/src/Illuminate/Support/Timebox.php

That said, Laravel's registration form provides an easy enumeration vector by checking for a unique email address. It's an easier and quieter way to test enumeration via registration than using password resets. 

Enumeration needs to be solved at a deeper level to properly eliminate it from the framework.

**Comment by driesvints** [comment]
Right now, we don't consider user enumeration an issue as major social networks like Twitter, etc also allow for this through their password reset. 

<img width="947" alt="Screenshot 2023-03-17 at 12 52 54" src="https://user-images.githubusercontent.com/594614/225897201-7cd77114-eb61-43a4-abea-d6631d393ac5.png">
