### ISSUE TITLE
Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by hkp22** [laravel/framework#46545]
- Laravel Version: 10.4.0
- PHP Version: 8.1.0
- Database MySQL

After upgrading Laravel from `v10.3` to `v10.4`, I started getting this error:
```
Call to undefined method ReflectionUnionType::getName()  
at vendor/laravel/framework/src/Illuminate/Support/Reflector.php:151

    149▕     public static function isParameterBackedEnumWithStringBackingType($parameter)
    150▕     {
  ➜ 151▕         $backedEnumClass = $parameter->getType()?->getName();
    152▕ 
    153▕         if (is_null($backedEnumClass)) {
    154▕             return false;
    155▕         }
```

I guess it is because of this PR:
https://github.com/laravel/framework/pull/46483/files#diff-b805c0807464db01691ea9ce7f653eec5e84b51145fa7d8626398c82ac2cf95fR151

**Comment by X-Coder264** [comment]
This was already fixed with https://github.com/laravel/framework/pull/46511 and will be a part of the next Laravel 10 release.

**Comment by rodrigopedra** [comment]
Laravel 10.4.1 was tagged in March, 18th. The PR @X-Coder264 referenced was merged in March, 20th.

Reference: https://github.com/laravel/framework/commits/10.x

As @X-Coder264 said:

> will be a part of **the next** Laravel 10 release.

There were no releases since his comment.

Minor releases are usually done on Tuesdays, bot for some reason yesterday they didn't do a minor release.

Reference: https://github.com/laravel/framework/tags

If you believe this should be released as a patch release, tag one of the maintainers for awareness.

**Comment by driesvints** [comment]
This will be in the next Laravel release. Thanks @X-Coder264 @rodrigopedra
