### ISSUE TITLE
Allow Deprecation Errors be handled as standard error

### ISSUE THREAD

**Issue by tonybolzan** [laravel/framework#46551]
- Laravel Version: 10.4.1
- PHP Version: 8.2.4

### Description:
Today Laravel allow only capture Deprecation Errors using a Logger, but the default PHP "error_reporting=E_ALL" behavior are prevent the execution of script when a Deprecation Error occurs.

This can be achieved changing the `\Illuminate\Foundation\Bootstrap\HandleExceptions::handleError` to add a new function, maybe `canCaptureDeprecation()` to return `bool` If we want the default capture or throw behaviour.

```php
public function handleError($level, $message, $file = '', $line = 0)
{
    if ($this->isDeprecation($level) && $this->canCaptureDeprecation()) {
        $this->handleDeprecationError($message, $file, $line, $level);
    } elseif (error_reporting() & $level) {
        throw new ErrorException($message, 0, $level, $file, $line);
    }
}

private function canCaptureDeprecation(): bool
{
    return static::$app['config']->get('logging.deprecations_as_exceptions') ?? false;
}
```

### Steps To Reproduce:
1. Install Laravel
3. Trigger any PHP deprecation: `Route::get('/', fn () => str_replace(null, '', ''));`
4. Since `logging.deprecations=null` by default, nothing will happen
5. Change `if ($this->isDeprecation($level))` to `false` on `handleError` and see the behaviour wanted

**Comment by tonybolzan** [comment]
Deprecations messagens are a way to know what would break in next php versions, if I allow this messages break like a normal exception in local and staging environments, I would have more control on upgrades.

Today, this messages pass unnoticed on local environments, some devs simple don't look at log files or extension like Clockwork.
In Staging environment this messages goes to logs, but with fewer informatiom about the problem.

And in production all this Deprecations Warnings are captured by the APM and reported as a standard Warning, flooding logs in some circumstances.

Please let me know what more information you need to appreciate this Issue.

**Comment by nunomaduro** [comment]
Although it may seem interesting, in reality, most deprecations do not arise from user-written code, but rather from code exists in the vendor directory. So, the flag you're suggesting would just end up throwing an exception that's most likely unfixable by the user since it's coming from the vendor directory.

Consequently, even when working locally, logging deprecations to a file remains the most effective approach for users to address any potential deprecations present in their Laravel applications.

Just as a quick side note, don't forget that you can utilize `withoutDeprecationHandling` in your test suite to nab any deprecations that pop up during testing.

Well, it looks like quite a few people (with seven thumbs up and counting) are on board with your idea. That being said, can you submit a pull request (complete with tests) so we can get a better idea of what kind of code changes we're looking at? This will help Taylor making a decision on this too. Thank you! ❤️
