### ISSUE TITLE
[QUEUE] $tries + retryUntil() -> exceeding the `attempts` DB column size

### ISSUE THREAD

**Issue by lsmith77** [laravel/framework#47174]
### Laravel Version

v9.50.1

### PHP Version

8.0.23

### Database Driver & Version

MariaDB

### Description

This topic was previously discussed in https://github.com/laravel/framework/issues/24636 and https://github.com/laravel/framework/issues/35199

I am using the database backend ending up exceeding the `attempts` columns size. I have `$tries` set on the job, but I am also using `retryUntil()`.

I would expect both rules to be applied (`retryUntil()` and `tries`) but I see that instead if was agreed to silently ignore `tries`. IMHO if you are going to ignore a setting, you should then at least throw an error.

However, more importantly why isn't the job moved to `failed_jobs` once the exception is triggered? I assume this is because jobs are only moved to `failed_jobs` if the job itself failed and not when the "management" of the job failed. But the current behavior basically blocks the queue from processing jobs, which is imho the worst possible outcome.

I have not dug in deeply enough to confirm this but it seems like `retryUntil` is persisted in the DB, so I cannot add some logic in `retryUntil()` to check the `tries` myself.

So for now I guess my only option is to remove `retryUntil`, which is suboptimal as I am using a middleware to handle rate limiting (via SpatieRateLimitedMiddleware), with exponential backoff times and I do want to know if the job ends up taking too long and due to exponential backoff, it is tricky to set a low fixed number of tries to ensure this time period.

### Steps To Reproduce

```
class MyJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 50;

    public function retryUntil()
    {
        return ..;
    }
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by lsmith77** [comment]
I will try to put together the requested information but it might take a week or two to find the time.

**Comment by driesvints** [comment]
Feel free to re-open a new issue once you have found the time 👍
