### ISSUE TITLE
Pusher/Echo/Soketi AccessDeniedHttpException

### ISSUE THREAD

**Issue by theWebKeyGuy** [laravel/framework#47187]
### Laravel Version

10.12.0

### PHP Version

8.2

### Database Driver & Version

MySql 8.0

### Description

https://stackoverflow.com/questions/76319598/laravel-pusher-echo-soketi-accessdeniedhttpexception

I have posted my issue here on stack overflow but I have a feeling it has something to do with the Broadcaster maybe? 

### Steps To Reproduce

I'm using a fresh install of laravel sanctum with jetstream inertia non ssr with sail. The rest of the info is in stack overflow.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by theWebKeyGuy** [comment]
This is currently on a project for my employer, that is not willing for me to share the entire code base. I would be willing to reproduce in a new project though. As I said it is mainly just a fresh laravel sail application with soketi with a fresh inertia Jetstream install non-ssr. Other then that it is just custom migrations, tables and models, it still uses all of Jetstream's standard settings.

**Comment by driesvints** [comment]
If we cannot reproduce it in a fresh app then it won't be possible for us to debug. For this issue, I recommend reaching out to a support channel or hiring a consultant.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
