### ISSUE TITLE
Package route not found but shown in route:list

### ISSUE THREAD

**Issue by PrasadChinwal** [laravel/framework#47199]
### Laravel Version

^10.0

### PHP Version

8.2

### Description

I am writing a package and have registered the routes in the Package service provider in the boot method. 
#### Directory Structure
- config
- routes
- migrations
- src
  - ServiceProvider.php

```
public function boot(): void
    {
        $this->loadRoutesFrom(__DIR__ . '/../routes/routes.php');

        $this->loadMigrationsFrom(__DIR__ . '/../migrations');

        $this->publishes([
            __DIR__ . '/../migrations' => database_path('migrations'),
        ], 'migrations');
    }
```

In my routes.php file I have defined the route as below:
```
Route::name('login')->get('login', [AuthHandler::class, 'login']);
```
When I run `php artisan route:list --path login` I can see the route listed:
```
GET|HEAD       login .............................................. login › PrasadChinwal\Shibboleth\Actions\AuthHandler@login
```

When I try to visit the route I get a 404.

### Steps To Reproduce

- Create a fresh Laravel 10.0 application
- Create a package directory to add your package
  - packages
    - vendor
     - package_name
       - config
       - routes
         - routes.php
       - src
         - ServiceProvider.php
- Register the routes in the boot method of your ServiceProvider.
- Composer require the package in your laravel application.
- Run php artisan route:list
- Visit the route in the browser.

**Comment by nunomaduro** [comment]
So, it's probably a problem on your end because today we have multiple packages publishing routes and they're all working fine. On my side, I just created a repository and published routes using the PackageServiceProvider@boot method, and everything is working perfectly as expected.

So, can you first please try one of the support channels below? **If you can actually identify this as a bug**, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
