### ISSUE TITLE
queue:work restart behaviour inconsistent with respect to cache:clear

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#47674]
### Laravel Version

10.2.4

### PHP Version

8.2.8

### Database Driver & Version

8.0.33

### Description

The behaviour of `php artisan queue:work` is inconsistent with respect to calls to `php artisan cache:clear` dependent on whether `php artisan queue:restart` has been called (or not) since the last cache clear. 

# Scenario 1
In this scenario, there as been no `queue:restart` issued since the last cache clear. A call to `php artisan cache:clear` will **not** trigger the active `queue:work` process to exit.

# Scenario 2
If there has been a `queue:restart` issued since the last cache:clear then a call to `php artisan cache:clear` **will** trigger the active `queue:work` process to exit. 

The cause is the face that the queue:work process uses the value of the cache key `illuminate:queue:restart` to decide whether or not to restart. If no `queue:restart` is issued then this will be empty, so issuing a `cache:clear` does not "change" the value of the cache key. If a `queue:restart` has been issued then the queue:work process will have a value for that cache key, and clearing the cache will cause it to be "changed", and thus the worker to exit. 

Ideally, when the worker starts, if there is no value for the cache key `illuminate:queue:restart` then one should be generated and stored. That will cause the behaviour of `cache:clear` to be consistent in both cases (it will **always** trigger the worker to exit). 

### Steps To Reproduce

* Clear the cache using `php artisan cache:clear`
* Run a queue worker in a manner that you can monitor worker exits
* Clear the cache again using `php artisan cache:clear`, notice that no matter how often you do that, the worker **will not** exit
* Run `php artisan queue:restart`
* Notice that the worker exits. Restart it it does not automatically in your environment
* Run `php artisan cache:clear`
* Unlike the previous invocations, this **will** trigger the queue worker to exit

**Comment by abdallahalsamman** [comment]
@driesvints @leewillis77 Heya, I could reproduce the issue here,

> The cause is the face that the queue:work process uses the value of the cache key illuminate:queue:restart to decide whether or not to restart. If no queue:restart is issued then this will be empty, so issuing a cache:clear does not "change" the value of the cache key. If a queue:restart has been issued then the queue:work process will have a value for that cache key, and clearing the cache will cause it to be "changed", and thus the worker to exit.

Yes, that's correct!

> Ideally, when the worker starts, if there is no value for the cache key illuminate:queue:restart then one should be generated and stored. That will cause the behaviour of cache:clear to be consistent in both cases (it will always trigger the worker to exit).

We can fix it by just checking if the cache key returns null then we set `$lastRestart` to `now()` in here:

https://github.com/laravel/framework/blob/f7adb6184cc22f63e296d10e2ff0874155bb5e58/src/Illuminate/Queue/Worker.php#L131-L149

I just tried it and it fixes the issue. pushing a PR now.

**Comment by abdallahalsamman** [comment]
@driesvints @leewillis77 Heya, I could reproduce the issue here,

> The cause is the face that the queue:work process uses the value of the cache key illuminate:queue:restart to decide whether or not to restart. If no queue:restart is issued then this will be empty, so issuing a cache:clear does not "change" the value of the cache key. If a queue:restart has been issued then the queue:work process will have a value for that cache key, and clearing the cache will cause it to be "changed", and thus the worker to exit.

Yes, that's correct!

> Ideally, when the worker starts, if there is no value for the cache key illuminate:queue:restart then one should be generated and stored. That will cause the behaviour of cache:clear to be consistent in both cases (it will always trigger the worker to exit).

We can fix it by just checking if the cache key returns null then we set `$lastRestart` to `now()` in here:

https://github.com/laravel/framework/blob/f7adb6184cc22f63e296d10e2ff0874155bb5e58/src/Illuminate/Queue/Worker.php#L131-L149

Like so

```
protected function getTimestampOfLastQueueRestart()
    {
        $lastRestart = null;

        if ($this->cache) {
            $lastRestart = $this->cache->get('illuminate:queue:restart');
        }

        if ($lastRestart === null) {
            $lastRestart = now();
            $this->cache->forever('illuminate:queue:restart', $lastRestart);
        }

        return $lastRestart;
    }
```

I just tried it and it fixes the issue. pushing a PR now.

**Comment by driesvints** [comment]
Thanks but it seems we won't take any action here sorry.

**Comment by abdallahalsamman** [comment]
@driesvints not even my fix? I'm working on fixing the failing tests

**Comment by driesvints** [comment]
No sorry. Taylor was clear on this. We appreciate your efforts in this though

**Comment by leewillis77** [comment]
I'm baffled by the response here. Is it really OK that the behaviour of a command (`cache:clear`) a) has (undocumented) side-effects and b) that those side-effects themselves are inconsistent?

**Comment by driesvints** [comment]
@leewillis77 I'm sorry you feel that way. In the end the decision lies with Taylor. He'll need to maintain everything that goes into the codebase.

About tagging as "help-wanted": we do this because we can't investigate every single issue ourselves. We used to close issues that we weren't going to investigate, now we leave them open. Of course, it's totally possible that if someone sends in a PR for a "help-wanted" issue that we can determine if it's not worth fixing or that we don't want to maintain the code that's being sent in. It's impossible to know this up front...
