### ISSUE TITLE
model->field changes to json type field in static::creating static::updating are not saved

### ISSUE THREAD

**Issue by yodahack** [laravel/framework#47774]
### Laravel Version

9.52.10

### PHP Version

8.1.14

### Database Driver & Version

MySQL 8.0.31 Linux

### Description

```
/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'school_id', 'group_id', 'paid_by_school_owner', 'status', 'changes'
    ];

    protected $casts = [
        'changes' => 'json',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            Log::debug('Creating the record with ID ' . $model->id);
            $model->requested_at = date('Y-m-d H:i:s');
            $model->changes = ['test'=>1];
        });
```

this will save requested_at value but it will not save changes value, the same happens with static::updating(
what is interesting I have the same issue with overloading save() however if I set the value of changes from controller with

$object->changes =  ['test'=>1];
$object->save();

it will save() properly.

### Steps To Reproduce

just use the json type field in boot() in static::creating or static::updating or in overload save()

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by iazaran** [comment]
Can we know about the requested_at type. Maybe it is filled automatically in DB side.
Also, do we need to determine $model type? For example if you are in Student model, so `function (Student $model)` is correct one.

**Comment by driesvints** [comment]
@yodahack feel free to open a new issue with the repo, thanks!
