### ISSUE TITLE
`artisan schedule:test` cannot differentiate between scheduled closures

### ISSUE THREAD

**Issue by jlevers** [laravel/framework#47783]
### Laravel Version

10.15.0

### PHP Version

8.2.7

### Database Driver & Version

Not applicable

### Description

I have multiple scheduled closures, using `$schedule->call(...)` in the `app/Console/Kernel::schedule()` method. When I run `php artisan schedule:test`, all scheduled closures show up in the task list with the name `Callback`. No matter which closure-based task index number I input, the first scheduled closure task is run.

It looks to me like this is because the code which chooses a task based on user input bases its task search on the task name that's generated by the `schedule:test` command, rather than the index number inputted by the user. See here:

https://github.com/laravel/framework/blob/9c44052743b0ee7f3adea36994918b4d8019e8b3/src/Illuminate/Console/Scheduling/ScheduleTestCommand.php#L62-L66

Since all the closure tasks have the same `$commandName`, `$index` always ends up being the first closure task.

There's a second part of the problem that I noticed while reading the code: if you run `php artisan schedule:test --name Callback` with multiple closure-based tasks, you get the message `No matching scheduled command found.`, because there is more than one match found:

https://github.com/laravel/framework/blob/9c44052743b0ee7f3adea36994918b4d8019e8b3/src/Illuminate/Console/Scheduling/ScheduleTestCommand.php#L48-L59

Happy to make a PR for this if that would be welcome. Repro steps below.

### Steps To Reproduce

My reproduction repo is here: https://github.com/jlevers/laravel-schedule-test-bug-repro

Note that these two lines are the only thing I added to the base repo produced by `laravel new bug-report --github="public"`:

```php
$schedule->call(fn () => logger()->debug('first callback'))->everyMinute();
$schedule->call(fn () => logger()->debug('second callback'))->everyMinute();
```

Steps to reproduce:
```
$ git clone git@github.com:jlevers/laravel-schedule-test-bug-repro.git && cd laravel-schedule-test-bug-repro
$ composer install
$ php artisan schedule:test

  Which command would you like to run?
  Callback ....................................................................................................................................... 0  
  Callback ....................................................................................................................................... 1
> 1
  Running [Callback] ...................................................................................................................... 7ms DONE
```

If you check your logs, you should see `local.DEBUG: first callback`, even though we selected the index of the second task.

To reproduce the second problem I mentioned:

```
$ php artisan schedule:test --name Callback

  INFO  No matching scheduled command found
```

There are in fact two matching commands, so that message is clearly wrong.

**Comment by driesvints** [comment]
Thanks for this detailed issue! Would be cool to get a PR for this with passing tests.

**Comment by driesvints** [comment]
Looks like we won't be making any changes for this sorry. Please use unique names for commands.

**Comment by mobidev86** [comment]
Hi @driesvints @taylorotwell 

I understand that we can avoid this issue by using unique names for commands like
```
protected function schedule(Schedule $schedule): void
{
        $schedule->call(fn () => logger()->debug('first callback'))->everyMinute()->name('first command');
        $schedule->call(fn () => logger()->debug('second callback'))->everyMinute()->name('second command');
}
```
though here are a few inputs from my end on this if you would like to take this into consideration

if you add these two lines in this file `\app\Console\Kernel.php`
```
protected function schedule(Schedule $schedule): void
{
        $schedule->call(fn () => logger()->debug('first callback'))->everyMinute();
        $schedule->call(fn () => logger()->debug('second callback'))->everyMinute();
}
```
the command names will be auto-generated as `Callback`

because of the below code inside this file - `laravel\framework\src\Illuminate\Console\Scheduling\CallbackEvent.php`
```
public function getSummaryForDisplay()
{
        if (is_string($this->description)) {
            return $this->description;
        }
        return is_string($this->callback) ? $this->callback : 'Callback';
}
```
that function will be triggered from here - `laravel\framework\src\Illuminate\Console\Scheduling\ScheduleTestCommand.php`
```
foreach ($commands as $command) {
    $commandNames[] = $command->command ?? $command->getSummaryForDisplay();
}
```

so the PR I provided above had logic to show a prompt to users stating multiple command names found and which one would they like to run?
also in any case if there are more then one command found with the same name
you get the message `"No matching scheduled command found"` because there is more than one match found. the message itself could be misleading

would love to know your thoughts on this please
do let me know if any changes are needed in the [pull request](https://github.com/laravel/framework/pull/47875) as well

Thanks

**Comment by driesvints** [comment]
We have no plans to make changes here, sorry. Please use unique names for all commands just like on web routes.
