### ISSUE TITLE
Error when running laravel's phpunit test

### ISSUE THREAD

**Issue by Timtendo12** [laravel/framework#47917]
### Laravel Version

10.10

### PHP Version

8.1.21

### Database Driver & Version

n/a

### Description

I get an error when running the phpunit through github overflow

![image](https://github.com/laravel/framework/assets/41442518/657472c8-30bc-473b-bf7b-3c7b8d69dc5f)

### Steps To Reproduce

Run the standard "Test laravel project" workflow by github

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by nunomaduro** [comment]
While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

[Laracasts Forums](https://laracasts.com/discuss)
[Laravel.io Forums](https://laravel.io/forum)
[StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
[Discord](https://discordapp.com/invite/KxwQuKb)
[Larachat](https://larachat.co/)
[IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
