### ISSUE TITLE
Reason for sanctum X-XSRF-TOKEN mismatch code 419

### ISSUE THREAD

**Issue by ybzc-gg** [laravel/framework#47927]
### Laravel Version

^9.19

### PHP Version

8.1

### Database Driver & Version

mariadb 10.3

### Description

Because browser urlencoded cookie value, but middleware VerifyCsrfToken not do proccess with urldecode, so not match.

To resolve this bug.

Open File Illuminate\Foundation\Http\Middleware\VerifyCsrfToken

And we can replace this function in middleware VerifyCsrfToken :

protected function getTokenFromRequest($request)
{
$token = $request->input('_token') ?: $request->header('X-CSRF-TOKEN');

  if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
      try {
          $token = CookieValuePrefix::remove($this->encrypter->decrypt($header, static::serialized()));
      } catch (DecryptException $e) {
          $token = '';
      }
  }

  return $token;
}
With this new function :

protected function getTokenFromRequest($request)
{
$token = $request->input('_token') ?: $request->header('X-CSRF-TOKEN');

  if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
      try {
          $token = CookieValuePrefix::remove($this->encrypter->decrypt(urldecode($header), static::serialized()));
      } catch (DecryptException $e) {
          $token = '';
      }
  }

  return $token;
}

### Steps To Reproduce

 See https://github.com/laravel/framework/issues/46650#issuecomment-1571279254

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
