### ISSUE TITLE
Relationship constraints not applied when running a query inside a withCount relationship

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#47946]
### Laravel Version

10.17.1

### PHP Version

8.2.8

### Database Driver & Version

MySQL 8.0.33

### Description

Let's say we have a method on a User which checks the permission using a simple database query:
```php
// User model

public function hasPermission($permissionName) {
    return $this->permissions()->where('name', $permissionName)->exists();
}
```

Then on some other model we have a relation which needs to check this permission to determine its `wheres`:
```php
// Group model

public function visibleUsers()
{
    return $this->belongsToMany(User::class)->where(function(Builder $query) {
        if(!Auth::user()->hasPermission('viewInactiveUsers')) {
            $query->where('is_active', true);
        }
    });
}
```

Now when we run a query with a `withCount` aggregate using this relationship:
```php
Group::query()
    ->where('id', $group->id)
    ->withCount('visibleUsers')
    ->first()
```

the intrinsic constraints of the `User::permissions()` relationship are not applied - Laravel runs the select from `permission` table without applying the where clause on `user_id` which in effect fetches permissions for all users.

However when this count is fetched manually eg:
```php
Group::first()->visibleUsers()->count()
```
the permission is checked correctly.

Note that the permission check is independent of any other query that is being ran at that time. It only depends on the currently logged in user, not the groups we are fetching.

### Steps To Reproduce

1. Clone https://github.com/KKSzymanowski/test-relation
2. Run `composer install`
3. Create a database for running the tests (update `.env.testing` or `phpunit.xml` to adjust the DB name or credentials).
4. Run `phpunit`
5. See that the test passes
6. Uncomment the last assertion in `tests/Feature/ExampleTest.php`
7. See that the test fails

**Comment by cosmastech** [comment]
Tried to resolve this with https://github.com/laravel/framework/pull/46831 (to close https://github.com/laravel/framework/issues/46633)

**Comment by KKSzymanowski** [comment]
@crynobone what more info do you need?

**Comment by crynobone** [comment]
After further inspection of the reproduction repository and documentation I do agree that something isn't right here. @cosmastech you can try resubmit the PR but I do feel we need to include more example especially integration tests (may use the above use case as example).

**Comment by cosmastech** [comment]
@crynobone will do that today.

**Comment by cosmastech** [comment]
Upon further inspection, this is caused by Relation::noConstraint() being called from within withAggregate(). https://github.com/laravel/framework/blob/dd5c5178274e64d0384dc30bf2c8139b00dba098/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L626

Calling `Relation@noConstraints()` affects how all relationships are built. To your test case, you can add this and see how it fails.

```php
$this->assertTrue($superadmin->hasPermission('viewInactiveUsers'));
$this->assertFalse($admin->hasPermission('viewInactiveUsers'));
$this->assertEmpty($admin->permissions()->get());

Relation::noConstraints(function() use ($superadmin, $admin) {
    $this->assertTrue($superadmin->hasPermission('viewInactiveUsers'));
    $this->assertFalse($admin->hasPermission('viewInactiveUsers'));
    $this->assertEmpty($admin->permissions()->get());
});
```

More easily:

```php
Relation::noConstraints(function() use ($admin){
    $admin->permissions()->toRawSql();
});
// select * from `permissions` inner join `permission_user` on `permissions`.`id` = `permission_user`.`permission_id`
```

If Relation::$constraints wasn't a single static variable, there might be some kind of way around this.

I would suggest converting your method to a scope and just applying that.

**Comment by crishoj** [comment]
> I would suggest converting your method to a scope and just applying that.

In a project I'm working on, we have a global access control scope which relies on a `groups`-relation defined on `User`.

Due to the issue with `Relation::$constraints` described above, in cases where the `groups`-relation for the current user is loaded in the context of a `withCount`, _all_ user-group relationships in the database are returned — in one instance, 12887 groups (with many duplicates) instead of the expected 20.

Subsequent usages of `groups` for the current user are also affected, since the relation is already loaded (with incorrect data).

**Comment by crishoj** [comment]
> If Relation::$constraints wasn't a single static variable, there might be some kind of way around this.

Could it be per-relation, instead of a global flag?

**Comment by cosmastech** [comment]
Couldn't you make this a property on the User model instead of something you fetch during the query part?

```php
class User extends Model
{
    // ...
    public function hasPermission($permissionName) {
        return $this->loadMissing('permissions')->where('name', $permissionName)->exists();
    }
    // ...
}
```

```php
Auth::user()->load('permissions');

Group::query()
    ->where('id', $group->id)
    ->withCount('visibleUsers')
    ->first()
```

I know it's not ideal, but I feel like any PR to change this would be rejected, would be accepted but cause tons of side effects in other applications, or cause breaking changes that could only target 11.x.

Some thoughts on that front: make a Relation::withConstraints() method

```php
public function visibleUsers()
{
    return $this->belongsToMany(User::class)->where(function(Builder $query) {
        $canViewInactiveUsers =  Relation::withConstraints(fn() => Auth::user()->hasPermission('viewInactiveUsers'));
        if(!$canViewInactiveUsers) {
            $query->where('is_active', true);
        }
    });
}
```

But to me, this feels really clunky. 🤷 

I feel like in general, putting this into a relationship seems inefficient. Querying the database to check if a permission exists on an unrelated model every time this relationship is built seems would be something I would flag in a code review.

**Comment by driesvints** [comment]
Looks like there isn't a great solution to this and changing the behaviour would be problematic. It's probably best that a further discussion is done from a PR with a proposed solution, thanks.
