### ISSUE TITLE
The @aware directive functions exclusively with anonymous components.

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel/framework#48033]
### Laravel Version

10.18.0

### PHP Version

8.2.7

### Description

The @aware directive functions exclusively with anonymous components.

<img width="282" alt="image" src="https://github.com/laravel/framework/assets/3448603/02176ff9-3ffe-4f2c-9513-aea0ae3904a2">

### Steps To Reproduce

Create components with the class using the Laravel 9.x documentation on passing data to components: https://laravel.com/docs/10.x/blade#accessing-parent-data

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by CrazyBoy49z** [comment]
> Hey there, thanks for reporting this issue.
> 
> We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue _as one separate commit_ on the main/master branch and share the repository here?
> 
> Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.
> 
> ```
> laravel new bug-report --github="--public"
> ```
> 
> Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.
> 
> Thanks!

https://github.com/CrazyBoy49z/bug-report

**Comment by nunomaduro** [comment]
You need to declare the `color` as property of the Menu component.

```
class Menu extends Component
{
    public function __construct(
        public string $color,
    ) {}

    public function render(): View
    {
        return view('components.menu');
    }
}
```

**Comment by CrazyBoy49z** [comment]
> You need to declare the `color` as property of the Menu component.
> 
> ```
> class Menu extends Component
> {
>     public function __construct(
>         public string $color,
>     ) {}
> 
>     public function render(): View
>     {
>         return view('components.menu');
>     }
> }
> ```

Thanks
