### ISSUE TITLE
[10.x] - `SESSION_DRIVER` to `database` doesn't allow to login via `Jetstream` & `Sanctum`

### ISSUE THREAD

**Issue by RSickenberg** [laravel/framework#48153]
### Laravel Version

10.20.0

### PHP Version

8.2.9

### Database Driver & Version

MySQL 8 (docker)

### Description

When I try to login if:

- `SESSION_DRIVER` is set to `database`
- `Jetstream` & `Sanctum` is installed.
- The app is run by `Sail`

The user is not able to log in except if the `remember` is checked.

### Steps To Reproduce

https://github.com/RSickenberg/flywithme (Demo project / proof of concept)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by RSickenberg** [comment]
Hello @crynobone,

I tried to reproduce the issue but for some reasons I'm not 100% fully able to carbon copy my demo into a new project.

Let me try it, standby.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue with reproducing repository if you're still experiencing this problem.

**Comment by RSickenberg** [comment]
Hey @crynobone, Actually I found the issue.

It's due to the User migration `id` column set to `ulid('id')` instead of `id()`.
