### ISSUE TITLE
Broadcasting issue in 10.21.0

### ISSUE THREAD

**Issue by AnourValar** [laravel/framework#48242]
### Laravel Version

10.21.0

### PHP Version

8.2.5

### Description

Broadcasting stopped working in the last version of Laravel

### Steps To Reproduce

The reason - the contract in WS messages was changed:

10.21.0 // NOT WORKING
{"event":"App\\Notifications\\UserNotification\\MyNotification","channel":"private-App.User.1","data":"..."}

10.20.0 // WORKING
{"event":"Illuminate\\Notifications\\Events\\BroadcastNotificationCreated","channel":"private-App.User.1","data":"..."}

**Comment by crynobone** [comment]
Seem to be related to https://github.com/laravel/framework/pull/48136

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by cosmastech** [comment]
I think the issue you're describing is that the event name has changed, right @AnourValar

**Comment by AnourValar** [comment]
@cosmastech , yes... exactly

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

v10.21.1 with the relevant changes has been released, please try again and open up a new issue if you're still experiencing this problem.
