### ISSUE TITLE
Unable to install composer dependencies

### ISSUE THREAD

**Issue by Chance-fyi** [laravel/framework#48241]
### Laravel Version

10.x

### PHP Version

8.1.19

### Description

I noticed that the tests in the action can install dependencies normally, but after trying various methods, I still cannot install the `laravel/prompts` package.

### Steps To Reproduce

```bash
# git clone git@github.com:laravel/framework.git && cd framework && composer install

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/prompts v0.1.0 requires illuminate/collections ^10.3 -> found illuminate/collections[v10.3.0, ..., v10.21.0] but these were not loaded, likely because it conflicts with another require.
    - laravel/prompts[v0.1.1, ..., v0.1.2] require illuminate/collections ^10.0 -> found illuminate/collections[v10.0.0, ..., v10.21.0] but these were not loaded, likely because it conflicts with another require.
    - laravel/prompts[v0.1.3, ..., v0.1.6] require illuminate/collections ^10.0|^11.0 -> found illuminate/collections[v10.0.0, ..., v10.21.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravel/prompts ^0.1 -> satisfiable by laravel/prompts[v0.1.0, ..., v0.1.6].

```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by Chance-fyi** [comment]
I found the reason. I actually executed `composer install` inside my Docker container, but Git was not installed in my container, so this error occurred.
