### ISSUE TITLE
Batch Callbacks not triggering if job timeout while in transaction

### ISSUE THREAD

**Issue by NiroDeveloper** [laravel/framework#48392]
### Laravel Version

10.23.1

### PHP Version

8.1

### Database Driver & Version

MariaDB 10.6.14

### Description

I currently found a bug at our production servers, which leads to the fact that our job pipeline stopped.
We dispatch a batch with many jobs, these jobs are running a database transaction.
If a job fails because of a timeout (while being stuck in a transaction), the failed_jobs counter of the batch will not be increased.

### Pre-analysis
To detect a timeout a pcntl alarm is used to kill the process.
https://github.com/laravel/framework/blob/bfa85b811cf6545dd5b6be40b44a523d02897da9/src/Illuminate/Queue/Worker.php#L214
This opens like a second thread which will mark the job as failed and increment the batch failed jobs counter.
The SQL query on the batch table will also run in a transaction.
https://github.com/laravel/framework/blob/bfa85b811cf6545dd5b6be40b44a523d02897da9/src/Illuminate/Bus/DatabaseBatchRepository.php#L186
For some reason unknown to me, these two transactions from different threads get in each other's way, causing the batch transaction to be rolled back.
(The [mysql exporter](https://github.com/prometheus/mysqld_exporter) shows a transaction savepoint in this moment)

### Steps To Reproduce

1. Create a Job which will timeout in a transaction
```
class TimeoutJob implements ShouldQueue
{

    use Batchable;
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    
    public int $tries = 1;
    public int $timeout = 5;

    public function handle(): void
    {
        DB::transaction(fn() => sleep(999));
    }

}
```

2. Dispatch this job in a batch
```
Bus::batch([new TimeoutJob(), new TimeoutJob(), new TimeoutJob()])
  ->allowFailures()
  ->dispatch()
```

3. See results
![image](https://github.com/laravel/framework/assets/23154768/286712ae-593a-45a2-afce-f8421d0c1d5a)
![image](https://github.com/laravel/framework/assets/23154768/64f1aa62-d903-433a-972b-23eccac583cf)
![image](https://github.com/laravel/framework/assets/23154768/a6c34c50-6ce7-4d88-a86e-1ad138472031)
![image](https://github.com/laravel/framework/assets/23154768/e81b24a6-401d-4fa1-9d6a-68118bbc3f65)

**Comment by cosmastech** [comment]
Is this related to https://github.com/laravel/horizon/issues/1310

**Comment by sebapastore** [comment]
I have been looking into this issue and found that the problem is that the transaction from the Job (tx1) is never commited neither rollback. So, when the transaction that updates the job_batches table (tx2) is launched, it will only be commited if tx1 is commited to.

The solution that I found is to rollback any pending database transactions when the worker reach timeout, before any other updates.

[This code](https://github.com/sebapastore/laravel-framework/commit/d829090c3cc20bc7165d424cd1b60685216e58a0) works.  But I think there must be a "proper way" of getting the databse connection in `Worker` class without using the DB Facade.
