### ISSUE TITLE
Blade fails to compile when a block @php directive follows an inline directive

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#48407]
### Laravel Version

10.22.0

### PHP Version

8.2.10

### Description

Hello!

Blade currently fails when a block `@php` directive follows an inline `@php(...)` directive, this is because the regex skips over the block start and matches on the block end.

Below is a minimum reproducible example:
```blade
<html>
    <body>
        @php($total = 0)
        {{-- ... --}}
        <div>{{ $total }}</div>
        {{-- ... --}}
        @php
            // ...
        @endphp
    </body>
</html>
```

I understand there have been several issues created on this topic (some are several years old). However, this is still an issue and there is nothing in the docs stating that the two syntaxes are incompatible. This bug either needs to be fixed or the docs need to be updated to state their incompatibility.

![image](https://github.com/laravel/framework/assets/4176520/7772d4bb-cd24-448f-b3fd-28eb91d49bf7)

Thanks!

### Steps To Reproduce

1. Add an inline php statement to a blade file `@php(...)`
2. Later in the file, add a block php directive:
    ```
    @php
        // ...
    @endphp
    ```
3. Fail

**Comment by tylernathanreed** [comment]
This was called out in #45330 by @rikvdh, and was closed with the directive of "Don't mix these up", and favoritism to just use raw `<?php` tags.

If this issue gets closed for the same reasons, then I suggest we submit a PR to [laravel/docs](https://github.com/laravel/docs) to at least highlight the problem, so that developers don't waste hours of research & debugging only to find that there's a bug in the framework that isn't going to get fixed any time soon.

**Comment by crynobone** [comment]
The anyone want to contribute, the new code need to ensure existing tests as well as following still return successful:

```php
    public function testMultilinePhpStatementsWithParenthesesCanBeCompiled()
    {
        $string = "@php ("
                ."\n    \$classes = ["
                ."\n        'admin-font-mono'"
                ."\n    ])"
                ."\n@endphp"
                ."\n"
                ."\n<span class=\"{{ implode(' ', \$classes) }}\">Laravel</span>";

        $expected = "<?php (\n"
                ."    \$classes = [\n"
                ."        'admin-font-mono'\n"
                ."    ])\n"
                ."?>\n"
                ."\n"
                ."<span class=\"<?php echo  implode(' ', \$classes); ?>\">Laravel</span>";

        $this->assertEquals($expected, $this->compiler->compileString($string));
    }

    public function testMixedOfPhpStatementsCanBeCompiled()
    {
        $string = "@php(\$total = 0)"
                ."\n{{-- ... --}}"
                ."\n<div>{{ \$total }}</div>"
                ."\n@php"
                ."\n    // ..."
                ."\n@endphp";

        $expected = "<?php (\$total = 0); ?>\n"
                ."\n"
                ."<div><?php echo e(\$total); ?></div>\n"
                ."<?php\n"
                ."    // ...\n"
                ."?>";

        $this->assertEquals($expected, $this->compiler->compileString($string));
    }
```

**Comment by rikvdh** [comment]
To be fair.. Since my PR and issue I re-thought this and approach this a different way.

Your priorities should be the following:

1. Don't use PHP in views!! 
2. If you REALLY want to, use regular `<?php ... ?>` tags.

Using PHP in views is not always avoidable but is almost never the way to go forward.
I think that there should be a debate maybe on removing the `@php`-tags as a whole in the next major.. imo there is no real reason to have them anyway.

**Comment by CalebDW** [comment]
@rikvdh,

As you said, sometimes it's not avoidable...

> If you REALLY want to, use regular <?php ... ?> tags.

This argument is kind of ridiculous in my opinion---you're basically saying that a feature in the framework exists, but nobody should use it. I'm fine if the framework wants to remove them in 11, but until then it's a feature that should be supported.

Although another option is to just remove the inline directive and enforce that everyone uses the `@endphp` tag.

A lot of the headaches in the regex-based parser could be avoided however, by Laravel supporting an AST parser as a first class citizen which can also be used for highlighting, indentation, formatting, etc.

Even better would be first class support for a blade language server similar to the one for [antlers](https://github.com/Stillat/vscode-antlers-language-server) (Statamic template engine)

**Comment by rikvdh** [comment]
@CalebDW I 100% agree. I also want that features that exist should be supported and work.
But if you read up on the history I have with this issue:

My initial fix:

https://github.com/laravel/framework/pull/45333

Which was released and shortly after reverted and then with the updated regex:

https://github.com/laravel/framework/pull/45390

Which was denied. I now hang to my argument that the feature is better gone all together.

**Comment by jezmck** [comment]
**This still reproduces on Laravel 12.62.0 (PHP 8.4.18).**

I hit this today while adding a second `@php ... @endphp` block to a Blade view that already had an inline `@php($x = ...)` earlier in the file — compilation failed with `syntax error, unexpected token "class"` (varies depending on what HTML follows the block). Tracked it down to the exact same root cause as this issue, using `Blade::render()` directly to rule out anything view-cache related:

```php
$tpl = <<<'BLADE'
@php($x = 1)
<span>test</span>
@php
    $y = 2;
@endphp
<div>done</div>
BLADE;

Blade::render($tpl);
// ErrorException: syntax error, unexpected token ">"
```

No nested parentheses required in either directive — just an inline `@php(...)` anywhere earlier in the template followed by a block `@php ... @endphp` anywhere later. I confirmed via `hasEvenNumberOfParentheses`/`compileStatements` tracing that the inline directive's paren-balancing loop in `BladeCompiler::compileStatements()` walks past its own closing paren and swallows everything up to and including the later block's content, leaving it uncompiled — the same failure mode described here.

#48420 fixed this for 10.x back in 2023 (switching the regex to a negative lookahead), but per the discussion there it also broke ternaries inside `@php(...)`, so it's possible a later change reworked/reverted that fix and reintroduced this case. Given it reproduces cleanly on current 12.x, reopening or a follow-up fix seems warranted.

Workaround: convert the inline `@php(expr)` to block form `@php expr; @endphp` — that avoids the regex ambiguity entirely.

**Versions:**
- Laravel Framework 12.62.0
- PHP 8.4.18
