### ISSUE TITLE
Undefined array key 1 in ServeCommand.php

### ISSUE THREAD

**Issue by inxty** [laravel/framework#48547]
### Laravel Version

10.24.0

### PHP Version

8.1.13

### Description

Sometimes for no reasons the application stops when it is started using `php artisan serve` with the error
`Undefined array key 1` in the ServeCommand.php line 312

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Console/ServeCommand.php#L312

It also was reported on stackoverflow
https://stackoverflow.com/questions/74283799/laravel-undefined-array-key-1-php-artisan-serve

### Steps To Reproduce

`php artisan serve`
`Undefined array key 1` in the ServeCommand.php line 312

Windows 10

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by inxty** [comment]
I guess the issue could be that I upgraded the application from version 6.x to 10.x, but I followed all the instructions

**Comment by inxty** [comment]
https://github.com/laravel/framework/issues/44282
