### ISSUE TITLE
When using Kernel `appendMiddlewareToGroup` to add middleware into middleware group, it will override router middleware group.

### ISSUE THREAD

**Issue by sam-tang-sw** [laravel/framework#48549]
### Laravel Version

10.24.0

### PHP Version

8.2.7

### Database Driver & Version

no

### Description

When using Kernel `appendMiddlewareToGroup` to add middleware into middleware group, it will override router middleware group.

Same issue happens in the following functions in Kernel.php
- `appendMiddlewareToGroup`
- `prependMiddlewareToGroup`
- `appendToMiddlewarePriority`
- `prependToMiddlewarePriority`

in Kernel.php `syncMiddlewareToRouter()` using `$this->router->middlewareGroup($key, $middleware);` to set router middleware group.
In Router.php
```
    public function middlewareGroup($name, array $middleware)
    {
        $this->middlewareGroups[$name] = $middleware;

        return $this;
    }
```
Before execute `syncMiddlewareToRouter()`, another service provider use `Route::prependMiddlewareToGroup('web', MiddlewareA::class);` to add Middleware. In this case MiddlewareA will disappear from router group.

Can we use merge to solve this issue?
In Kernel.php
```
    protected function syncMiddlewareToRouter()
    {
        $this->router->middlewarePriority = $this->middlewarePriority;

        foreach ($this->middlewareGroups as $key => $middlewares) {
            foreach ($middlewares as $middleware) {
                $this->router->pushMiddlewareToGroup($key, $middleware);
            }
        }

        foreach (array_merge($this->routeMiddleware, $this->middlewareAliases) as $key => $middleware) {
            $this->router->aliasMiddleware($key, $middleware);
        }
    }
```

### Steps To Reproduce

https://github.com/sam-tang-sw/middleware-override-bug/commit/ce1b426862a5b98c01572ef7e127f27c6f3a7dc5

config/app.php
```
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

+        App\Providers\ProviderA::class,
```

ProviderA.php
```
    public function boot(): void
    {
        Route::prependMiddlewareToGroup('web', MiddlewareA::class);
    }
```

Print `dd(Route::getMiddlewareGroups());` result
```
array:2 [▼ // routes/web.php:17
  "web" => array:7 [▼
    0 => "App\Http\Middleware\MiddlewareA"
    1 => "App\Http\Middleware\EncryptCookies"
    2 => "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
    3 => "Illuminate\Session\Middleware\StartSession"
    4 => "Illuminate\View\Middleware\ShareErrorsFromSession"
    5 => "App\Http\Middleware\VerifyCsrfToken"
    6 => "Illuminate\Routing\Middleware\SubstituteBindings"
  ]
  "api" => array:2 [▼
    0 => "Illuminate\Routing\Middleware\ThrottleRequests:api"
    1 => "Illuminate\Routing\Middleware\SubstituteBindings"
  ]
]
```

When add `App\Providers\ProviderB::class,`
config/app.php
```
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        App\Providers\ProviderA::class,
+        App\Providers\ProviderB::class,
```

ProviderB.php
```
    public function boot(): void
    {
        /** @var \Illuminate\Foundation\Http\Kernel $kernel */
        $kernel = app()->make(Kernel::class);

        /**
         * Kernel syncMiddlewareToRouter will override router middleware group.
         */
        $kernel->appendMiddlewareToGroup('api', MiddlewareB::class);
    }
```

Print `dd(Route::getMiddlewareGroups());` result
```
array:2 [▼ // routes/web.php:17
  "web" => array:6 [▼
    0 => "App\Http\Middleware\EncryptCookies"
    1 => "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
    2 => "Illuminate\Session\Middleware\StartSession"
    3 => "Illuminate\View\Middleware\ShareErrorsFromSession"
    4 => "App\Http\Middleware\VerifyCsrfToken"
    5 => "Illuminate\Routing\Middleware\SubstituteBindings"
  ]
  "api" => array:3 [▼
    0 => "Illuminate\Routing\Middleware\ThrottleRequests:api"
    1 => "Illuminate\Routing\Middleware\SubstituteBindings"
    2 => "App\Http\Middleware\MiddlewareB"
  ]
]
```
Missing `App\Http\Middleware\MiddlewareA` in web

**Comment by sam-tang-sw** [comment]
https://github.com/sam-tang-sw/framework/commit/1fc3836c225ce6ae6df520e2e9892905f734de87

I have written some tests to describe the results I expect.
I can't determine whether this is a bug or if my usage is incorrect.

Thank you!

**Comment by NickSdot** [comment]
I ran into the same - or at least a very similar - problem a few weeks ago, and I agree that this is a bug, or at least a missing feature. 

I haven't been able to come up with a simple and clean fix. I am afraid that two-way sync via merge may end up messing things up even more. For example, @sam-tang-sw, your proposed PR also only fixed part of the problems you showed in your tests. In my case, I ended up with ordering problems as things got more complex. I then wrote myself a kernel decorator, overrode some kernel methods, and gave up trying to find a bulletproof fix for the framework itself.

**For your case**, you might get around this by only adding/removing/modifying via `kernel` methods and not a mix of `kernel` and `route` in your providers. Unless I am missing something, this should ensure that your kernel is the single source of truth that is always synchronised back to the router.

**Generally**, I am afraid the best way to fix this problem in the framework itself would be to change the way middleware groups are handled. I think the router should **not** be responsible for handling it's own state for middleware groups, but rather pass it's middleware methods to the kernel, which then syncs back. IMO this would solve the main problem here. We are still left with ordering issues in some cases because we only have append/prepend methods. What we really need is the ability to add an entry to any of the middleware methods after a specific other middleware. 

Something like:

```php
public function addToMiddlewareGroup(string $group, string $addable, string $addAfter = ''): void`
```

In addition, I think there should be a kernel property like `$middlewareAfterDispatch` that allows defining global middleware that is only applied after the router has already been dispatched. Currently, this is only possible with middleware groups, which IMO is an unnecessary extra step in cases where a group actually is not needed at all. For example, `SubstituteBindings` can't be a global middleware. One might wonder why this is even useful, so I wanna add that in our case we bind different kernels while bootstrapping.

I actually have a complete custom implementation for all kernel middleware methods ready here. Since there are no contracts, I would carefully say that it should even work without breaking changes. However, routes, kernel and middleware are a sensitive part of the application, I don't dare to PR anything without a bit of brainstorming and extra eyes from someone with deeper knowledge of the little details, tho. Maybe someone from the team is down for a chat about it.

**Comment by NickSdot** [comment]
I've put together a POC for `Router::pushMiddlewareToGroup()` based on the tests (https://github.com/sam-tang-sw/framework/commit/1fc3836c225ce6ae6df520e2e9892905f734de87) @sam-tang-sw  provided to show what I meant by:

> Generally, I am afraid the best way to fix this problem in the framework itself would be to change the way middleware groups are handled. I think the router should not be responsible for handling it's own state for middleware groups, but rather pass it's middleware methods to the kernel, which then syncs back. IMO this would solve the main problem here. 

## POC Repo
https://github.com/laravel/framework/compare/10.x...NickSdot:laravel-framework:middleware-sync-bug-issue-48549

It's very quick and dirty. If this approach in general is something that would work, the following methods should later be changed in the same manner:

```php
Router::prependMiddlewareToGroup();
Router::removeMiddlewareFromGroup();
Router::aliasMiddleware();
Router::flushMiddlewareGroups(); // (??)
```

All middleware 'setters' in the router are then proxies to the actual methods in the kernel. The called methods in the Kernel then take care of syncing back to the router, which makes the Kernel the single source of truth.

Does that make sense? 😅

## Reproduction
1. Clone the [repo](https://github.com/laravel/framework/compare/10.x...NickSdot:laravel-framework:middleware-sync-bug-issue-48549) and run the tests, the newly added tests will fail.
2. Set [this var](https://github.com/NickSdot/laravel-framework/blob/81cb0cf352b656b91f81e600c911bddb8d549389/src/Illuminate/Routing/Router.php#L1069,) to `true` and run the tests again. They will pass.

## Considerations
- Please note the comments in `pushMiddlewareToGroup()`. I need input for that.
- I have no idea if it is _legal_ to make methods in the Router dependent on a kernel binding.
- Without [this else statement](https://github.com/NickSdot/laravel-framework/blob/81cb0cf352b656b91f81e600c911bddb8d549389/src/Illuminate/Routing/Router.php#L1080-L1091) 4 old tests fail. Did not look into that yet. Needs a solution.


---

@driesvints maybe someone from the team can have a look at this and my previous comment and provide some feedback?

**Comment by driesvints** [comment]
Right now we don't have time to look at this and would appreciate any community contribution here.

**Comment by NickSdot** [comment]
> Right now we don't have time to look at this and would appreciate any community contribution here.

Yes, I know, I saw the 'help wanted' label. I try is to contribute, but would need a very quick info to keep going. :)

**My question basically is:** 
is it allowed/legal (by framework policy) to rely on a Kernel binding in `Illuminate\Routing\Router`:

```php
$kernelInterface = \Illuminate\Contracts\Console\Kernel::class;

if ($this->container && $this->container->bound($kernelInterface)) {
    $kernel = $this->container->make($kernelInterface);
    $kernel->appendMiddlewareToGroup($group, $middleware);
} 
```

Why I am asking this is, because there is only one other dependency to a binding. And this is `ResourceRegistrar`, which lives in the same `Illuminate\Routing` namespace. Since the Routing component requires `"illuminate/contracts": "^11.0",` I believe it's ok, butI rather ask first before doing all the work for nothing.

If this would be in general allowed, I would need to update **four** old test to bind a Kernel.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
