### ISSUE TITLE
ambiguous order by created as in `whereHas` subquery

### ISSUE THREAD

**Issue by gepopp** [laravel/framework#48598]
### Laravel Version

10.4.1

### PHP Version

8.2

### Database Driver & Version

MYSQL 8

### Description

If i setup a Query like:

```
 $this->records = TimeRecord::notBilled()->whereHas('estimatePosition', function ( Builder $query) use ( $pids ){
                $query->whereHas('estimate', function (Builder $query) use ( $pids ){
                    $query->whereIn('estimatable_id', $pids);
                });
            })->reorder()->get();
```

in the sql:

```
`select * from `time_records` 
where `bill_postition_id` is null and exists (
select * from `estimate_positions` inner join `estimate_postition_time_record` 
on `estimate_positions`.`id` = `estimate_postition_time_record`.`estimate_position_id` 
where `time_records`.`id` = `estimate_postition_time_record`.`time_record_id` 
and exists (
select * from `estimates` where `estimate_positions`.`estimate_id` = `estimates`.`id` and `estimatable_id` in (6, 1)
and `estimates`.`deleted_at` is null 
and `account_id` = 1 order by `created_at` desc) 
and `account_id` = 1 order by `created_at` desc) 
and `time_records`.`deleted_at` is null 
and `account_id` = 1 
order by `created_at` desc`
```

the order by clauses arent tied to its table, and it seems thy cannot be removed by the reorder() function.

### Steps To Reproduce

The TimeRecord Model has a belongsToMany Relation to the EstimatePositions which further belong to an Estimate which belongs to an Project.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
