### ISSUE TITLE
Can't I underline the @yield('title ') ?

### ISSUE THREAD

**Issue by huaiguoguo** [laravel/framework#48721]
### Laravel Version

9.52.14

### PHP Version

8.2.11

### Description

i am defined a section variable in subpages blade file,  and use it in layout file
example:   i defined a section, eg

```php
 @section('title')  // in resources/views/home/index.blade.php
```

and i use it eg:  
```php
// it not work.
<title>sports website_@yield('title')</title>   // in resources/views/layout/default.blade.php
```

if  i use it eg:
```php
// it work!!!
<title>sports website @yield('title')</title>  // in resources/views/layout/default.blade.php
```

Can't I  underline the @yield('title ') ?

```<title>sports website @yield('title')</title>```     it work!!!

```<title>sports website_@yield('title')</title>```     not work!!!

### Steps To Reproduce

As described above

## i think it is a bug

**Comment by huaiguoguo** [comment]
![image](https://github.com/laravel/framework/assets/1888094/f84cd1bc-7b22-4a5e-9675-ebc0035eeddb)

![image](https://github.com/laravel/framework/assets/1888094/0560e064-4450-4a3c-ab1c-1852a8adb29e)

**Comment by huaiguoguo** [comment]
### it work
![image](https://github.com/laravel/framework/assets/1888094/d75842de-a13a-4e62-ad9a-0dba2216e346)
![image](https://github.com/laravel/framework/assets/1888094/e80b4f96-efa6-4cf6-90fd-0e44ddbcab32)

**Comment by mpyw** [comment]
Try this:

```blade
<title>sports {{ 'website_' }}@yield('title')</title>
```

**Comment by huaiguoguo** [comment]
> Try this:
> 
> ```
> <title>sports {{ 'website_' }}@yield('title')</title>
> ```

it is work,  but i still think this is a bug

**Comment by mpyw** [comment]
@huaiguoguo Currently this is the expected behavior. **In regular expressions, an underscore `_` is not regarded as a non-letter, but as a letter**. 

https://3v4l.org/H3qar

The regular expression is actually used here:
https://github.com/laravel/framework/blob/4b4b1e489623c4c7c31447a2bc06450050f0686e/src/Illuminate/View/Compilers/BladeCompiler.php#L521

```php
<?php

function check(string $str): ?array
{
    return preg_match_all('/\B@(\w+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $str, $m) ? $m[0] : null;
}

$cases = [
    "@yield('example')",
    "@yield('example1')@yield('example2')",
    "example@yield('example')",
    "example+@yield('example')",
    "example-@yield('example')",
    "example_@yield('example')",
];

var_dump(array_map(check(...), array_combine($cases, $cases)));
```
 
> ```php
> array(6) {
>   ["@yield('example')"]=>
>   array(1) {
>     [0]=>
>     string(17) "@yield('example')"
>   }
>   ["@yield('example1')@yield('example2')"]=>
>   array(2) {
>     [0]=>
>     string(18) "@yield('example1')"
>     [1]=>
>     string(18) "@yield('example2')"
>   }
>   ["example@yield('example')"]=>
>   NULL
>   ["example+@yield('example')"]=>
>   array(1) {
>     [0]=>
>     string(17) "@yield('example')"
>   }
>   ["example-@yield('example')"]=>
>   array(1) {
>     [0]=>
>     string(17) "@yield('example')"
>   }
>   ["example_@yield('example')"]=>
>   NULL
> }
> ```

`\B` indicates a match at **a non-word boundary**.
(This is the opposite of `\b`, which matches at a word boundary.)

`[Letter]\B[Letter]` → Matches
`[Letter]\B[Non-Letter]` → Does not match
`[Non-Letter]\B[Letter]` → Does not match
`[Non-Letter]\B[Non-Letter]` → Matches

If this comes before the `@` symbol, it only matches when non-letter characters, i.e., symbols other than letters, are consecutive. While characters like a ` ` `+` `-` (which are not letters) will match, `_` will not because it is considered part of the alphabet group, like `a` `b` `c`.

**Comment by mpyw** [comment]
Changing this now would be a breaking change, and would require community consensus in [discussion](https://github.com/laravel/framework/discussions).

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
