### ISSUE TITLE
Inline Images not embedded in Mail Preview

### ISSUE THREAD

**Issue by tkempf** [laravel/framework#48808]
### Laravel Version

10.15.0

### PHP Version

8.1.18

### Description

Mailables which have inline images embedded by 
`{!! $message->embed(public_path($storagepath.'/img/image.jpg')) !!}`
do not have the binary Data embedded when the preview is rendered in the browser by the render() method.
The Images are embedded correctly in the mail when it is sent.

### Steps To Reproduce

1. Generate a mailable where an image is embedded in the view-template via $message->embed() method.
    i.e. `<img  src="{!! $message->embed(public_path($storagepath.'/img/image.jpg')) !!}" />`

3. send mail to check that the image is visible in the mail
4. preview mail in the browser as explained here https://laravel.com/docs/10.x/mail#previewing-mailables-in-the-browser
5. Image is not shown in the preview. The Source in the image-tag is  src="cid:imageid", but the corresponding data-part is missing in the output

**Comment by phpfour** [comment]
Hey @tkempf, this issue has been fixed in this PR: https://github.com/laravel/framework/pull/48292. You can update your Laravel version and it should be working. Here's my test results:

**resources/views/emails/document_uploaded.blade.php**
```php
<body>
    A new document has been uploaded to the system. <br><br>

    <img src="{!! $message->embed(public_path('storage/head_first_sql.png')) !!}">
</body>
```

![CleanShot 2023-10-26 at 10 44 14](https://github.com/laravel/framework/assets/171715/950014d6-8f8b-4b17-9b9f-6132e96b8a84)

Cheers!

**Comment by tkempf** [comment]
Oh, i must have missed this one. Allthough i searched the issues for the described behaviour.
Since this is already fixed, i close this issue .
Sorry for the noise and Thankyou Mohammad!
