### ISSUE TITLE
TrustHosts middleware does not cause SuspiciousOperationException to throw during handle()?

### ISSUE THREAD

**Issue by nickjbedford** [laravel/framework#49005]
### Laravel Version

10.31

### PHP Version

8.2.12

### Database Driver & Version

MySQL 5.7

### Summary
In an effort to prevent Host header injection, cache poisoning and other related attacks, I added the TrustHosts middleware at the beginning of my global middleware list. I then configured the hosts() method to return the hosts I wished to allow.

The Host header poisoning vulnerability still existed. Should the TrustsHosts base middleware not cause an exception to be thrown when sending a malicious Host header poisoning request?

Either I don't understand the usage of TrustHosts base middleware, or I have misused it or it is incomplete. Please help me understand it.

### Details
The TrustHosts middleware only calls `Request::setTrustedHosts()` and does not actually call `$request->getHost()` which throws the `SuspiciousOperationException` if an untrusted host is found. This `getHost()` method on Request does not seem to be called _after_ TrustHosts sets the trusted host patterns.

Should the TrustHosts middleware base class not also _check_ the host is valid during the call to `Illuminate\Http\Middleware\TrustHosts::handle()`?

### Impact
Host header injection which can (and did) result in Cache Poisoning and other unintended side effects of the host being not a trusted host inside Laravel's framework.

### Current Fix

I implemented the following code to trigger the SuspiciousOperationException as it should have been already:

```php
function handle(Request $request, $next)
{
	$result = parent::handle($request, $next); // This does not actually check the host and no call afterwards does in my middleware chain.

	try
	{
		$request->getHost(); // This triggers the validation of the host
	}
	catch(SuspiciousOperationException $exception)
	{
		report($exception);
		abort(400, 'Bad request');
	}

	return $result;
}
```

### Steps To Reproduce

- Add a custom middleware that extends `Illuminate\Http\Middleware\TrustHosts`.
- Configure the results given by the overridden `hosts()` method.
- Using BurpSuite or similar software, send a HTTP/1.1 request that contains a URL with a different host in the absolute request URL.
  - `POST https://suspicious-domain.com/path HTTP/1.1`
  - `Host: mydomain.com`
- Expect a response indicating the host is untrusted (provided by `SuspiciousOperationException`).

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by valorin** [comment]
@nickjbedford I believe `TrustHosts` only works with the forwarded headers, such as `X-Forwarded-Host`, while what you're doing is directly modifying the main host. A common protection against modifying the main host is to configure your server (i.e. nginx/apache) to only respond to requests on your allowed hosts through vhosts. This way when your forged request hits the server, it just ignores it.

Is this the case, or am I missing something? I'd love to dig into it further. 🙂

I can definitely see a benefit to including the primary host in the Trusted Hosts checks though, it shouldn't be something that requires the server to be correctly configured.

**Comment by nickjbedford** [comment]
> @nickjbedford I believe `TrustHosts` only works with the forwarded headers, such as `X-Forwarded-Host`, while what you're doing is directly modifying the main host. A common protection against modifying the main host is to configure your server (i.e. nginx/apache) to only respond to requests on your allowed hosts through vhosts. This way when your forged request hits the server, it just ignores it.
> 
> Is this the case, or am I missing something? I'd love to dig into it further. 🙂
> 
> I can definitely see a benefit to including the primary host in the Trusted Hosts checks though, it shouldn't be something that requires the server to be correctly configured.

Hi Valorin, thanks for responding. `TrustHosts` appears to look for a few different possible host values (`X-Forwarded-Host:` on trusted proxies and `Host:` next in line, before using the Apache ServerName etc). What it doesn't actually do is trigger the _detection_ of a suspicious host on its own and prevent an untrusted host from proceeding.

I had to add a call to `$request->getHost()` in my subclass' `handle()` method for it to actually prevent the request from proceeding. The `\Illuminate\Http\Middleware\TrustHosts` base class does nothing to actually prevent the untrusted host from proceeding, which seems unintuitive and incomplete to me at any rate.

I would have expected the original TrustHosts middleware to also _check_ the host is not malicious. All that TrustHosts does is set an array variable and pass the request onto the next middleware. At this point (even the first in Kernal's middleware), no other call to getHost() happens naturally in my own middleware stack.

### Illuminate\Http\Middleware\TrustHosts source

```php
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return \Illuminate\Http\Response
     */
    public function handle(Request $request, $next)
    {
        if ($this->shouldSpecifyTrustedHosts()) {
            Request::setTrustedHosts(array_filter($this->hosts())); // this does not check the host
        }

        return $next($request); // malicious host continues unchecked in my own stack
    }
```

**Comment by vcardillo** [comment]
This code is still the same in Laravel 11, and it seems like a bug. The documentation states: "Incoming requests with other Host headers will be rejected", which is not the behavior that happens.

**Comment by vcardillo** [comment]
Update on simulating this locally. It took me a little while to figure this out.

PHP: 8.3.7
Laravel: 11.21.0

Important note for simulating production locally:
If you are using the Sail docker container, the behavior is currently that changes to `APP_ENV` are not picked up, but only for this variable. You can clear the cache, or restart the container. This fact is important if using Sail, since **TrustedHosts doesn't trigger in `local`**. Corresponding Sail bug report: https://github.com/laravel/sail/issues/658

It's very important to note and worth repeating:
**TrustedHosts does not trigger in `local`**. This is built into the code. 

Once I had my local environment's `APP_ENV` set to something other than "local", the core Laravel code behaved as expected with:
```php
$middleware->trustHosts(at: ['foo.com'], subdomains: false);
```

Note that if you do not specify `subdomains: false`, then the domain itself that you are running on will pass the regex, so set this flag as well fi you want to see this work locally. For example, without `subdomains: false`, if your local testing domain is set as "myapp.test", the following regex will be added to the array: `^(.+\\.)?myapp\\.test$`. Once I ensured I was not in "local" and I set the subdomains flag to false, TrustHosts triggered a return of Bad Request locally:

<img width="1369" alt="Screen Shot 2024-08-30 at 15 48 37" src="https://github.com/user-attachments/assets/2d2ebf6a-fd00-401d-8762-679b4e480893">

I am on Laravel 11; the core code in TrustHosts.php looks the same in 10 and 11, but I don't know if something was changed/fixed elsewhere between 10 and 11. But regardless, this appears to work correctly in Laravel 11.
