### ISSUE TITLE
[POSTGRESQL][TESTING] RefreshDatabase trait tries to create tables that exist.

### ISSUE THREAD

**Issue by logic-b-o-m-b** [laravel/framework#49078]
### Laravel Version

10.x, possibly earlier versions as well

### PHP Version

8.2

### Database Driver & Version

Postgresql 14.5 run in docker (ubuntu 22.04)

### Description

When tables are created in schema other then public, and RefreshDatabase trait is used in tests, the trait tries to create all tables despite the fact thet they exists, which results in all tests failing  

### Steps To Reproduce

Example migration that causes tests to fail:

```php
    public function up(): void
    {
            Schema::create('other_schema.table', function (Blueprint $table) {
                $table
                    ->uuid('id')
                    ->primary();
            });
    }
```

Workaround that allow tests to run normally:

```php
    public function up(): void
    {
        if (!Schema::hasTable('other_schema.table')) {
            Schema::create('other_schema.table', function (Blueprint $table) {
                $table
                    ->uuid('id')
            });
        }
    }
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue with reproducing repository if you're still experiencing this problem.
