### ISSUE TITLE
Eloquent: API Resources set $wrap Not effective

### ISSUE THREAD

**Issue by season886** [laravel/framework#49155]
### Laravel Version

10.33.0

### PHP Version

8.2.11

### Database Driver & Version

postgresql 16

### Description

Eloquent: API Resources set $wrap Not effective

### Steps To Reproduce

```
<?php

namespace App\Http\Resources\System;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class MenuResource extends JsonResource
{
    public static $wrap = 'list';
 
    public function toArray(Request $request): array
    {
        return [
            'id'=> $this->id,
            'pid'=> $this->pid,
            'component'=> $this->component,
            'redirect'=> $this->redirect,
        ];
    }
}
```

```
return MenuResource::collection($menuService->index($keywords));
```
return data:
```
{
    "data": [
        {
            "id": "316897264566009856",
            "pid": "0",
            "path": "\/home",
            "component": "\/home",
            "redirect": null
        },
        {
            "id": "316897264595369984",
            "pid": "0",
            "path": "\/system\/menu",
            "component": "\/system\/menu",
            "redirect": null
        }
    ]
}
```
the data It should be:

```
{
    "list": [
        {
            "id": "316897264566009856",
            "pid": "0",
            "path": "\/home",
            "component": "\/home",
            "redirect": null
        },
        {
            "id": "316897264595369984",
            "pid": "0",
            "path": "\/system\/menu",
            "component": "\/system\/menu",
            "redirect": null
        }
    ]
}
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by season886** [comment]
I understand now，that we need to first define a ResourceCollection, then define a JsonResource, and set ResourceCollection the $collections attribute to JsonResource. Only collection data with theResourceCollection  $wrap is effective.
Thank you!
