### ISSUE TITLE
Table "migrations" and "password_resets" have no unique keys

### ISSUE THREAD

**Issue by phanan** [laravel/framework#49261]
### Laravel Version

10.4.1

### PHP Version

Irrelevant

### Database Driver & Version

MySQL 8.0

### Description

Out of the box, the two tables `migrations` and `password_resets` have no unique keys. This normally shouldn't be an issue, since there's no real use for such a key in these two tables. However, on platforms like PlanetScale, having a table without a unique key can be problematic, e.g., [safe migrations](https://planetscale.com/docs/concepts/safe-migrations) would be disabled. 

![image](https://github.com/laravel/framework/assets/8056274/f29f5ef7-1f01-47b0-9c4e-f2737d5450ad)

I believe adding a unique key for these two tables should be straightforward enough and isn't too much of a cost to support these platforms. Can attempt a PR myself if this issue is considered valid.

### Steps To Reproduce

1. Generate a new Laravel application
2. Back up the database and import it into PlanetScale
3. Look at the "Branches" screen for the problems

**Comment by crynobone** [comment]
We going to look into improving this in Laravel 11, as for now it might be best to publish the migrations and add it manually if you have such requirements.

**Comment by rimace** [comment]
@phanan The version 10.4.1 you mentioned defines a primary key "id" (see [here](https://github.com/laravel/framework/blob/v10.4.1/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php#L169)).
Have you tried reproducing that using the "Steps To Reproduce" you wrote? Because I got a primary key in my migrations table.

The primary key for the migrations table was added in version 5.3 (published 2016). Could it be that you created the database with Laravel earlier than version 5.3?
Because if so, even after upgrading, the field "id" will not be added in the "migrations" table. You have to do that yourself.
