### ISSUE TITLE
After upgrading from version 10.20.0 to 10.37.1, an error occurs with route::cache.

### ISSUE THREAD

**Issue by silie666** [laravel/framework#49357]
### Laravel Version

10.37.1

### PHP Version

8.1.21

### Description

After running `php artisan route:cache`, it directly throws an exception.
```
 Exception 

  Serialization of 'WeakMap' is not allowed

  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1344
    1340▕     public function prepareForSerialization()
    1341▕     {
    1342▕         if ($this->action['uses'] instanceof Closure) {
    1343▕             $this->action['uses'] = serialize(
  ➜ 1344▕                 SerializableClosure::unsigned($this->action['uses'])
    1345▕             );
    1346▕         }
    1347▕
    1348▕         if (isset($this->action['missing']) && $this->action['missing'] instanceof Closure) {

      +14 vendor frames 

  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```
   
![image](https://github.com/laravel/framework/assets/38691833/b59c0afd-7ba9-4283-a8f1-c94c9eb2d55e)
![image](https://github.com/laravel/framework/assets/38691833/86b78836-cb58-4fb4-852a-6633e251b090)

### Steps To Reproduce

My route file is `web.php`. Here is a snippet of my code.
```
use Illuminate\Support\Facades\Route;

$log = app('log');
Route::any('/{all}', function () use ($log) {

})->where(['all' => '.*']);
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by silie666** [comment]
@crynobone [repository](https://github.com/silie666/artisan-route-cache-bug)

**Comment by crynobone** [comment]
Such usage is not supported unfortunately, you should however can change it to the following:

```php
use Psr\Log\LoggerInterface;

Route::any('/{all}', function (LoggerInterface $log) {

})->where(['all' => '.*']);
```
