### ISSUE TITLE
Calling having() with a Closure throws error

### ISSUE THREAD

**Issue by Ken-vdE** [laravel/framework#49749]
### Laravel Version

10

### PHP Version

8.3

### Description

When calling `having()` on a `Builder` with a Closure as a parameter, without previously calling `having()` with a column, throws an error because `addNestedHavingQuery()` does `count($this->havings)` which expects `$this->havings` to be countable (and it's `null`).
```
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
```

### Steps To Reproduce

see description

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by Ken-vdE** [comment]
Doing what you asked and writing the test to zoom in on the issue caused me to figure out the underlying problem.
I was calling having() with a \Closure but I was not calling any other having()s within that closure.
So, when the havingNested() method stepped into addNestedHavingQuery(), no $query->havings had been set. 
That threw the TypeError.

I've expanded the condition determining to call or not call the inner having('column') to outside of the main having(\Closure), so when no having('column') is called, neither is the having(\Closure)
