### ISSUE TITLE
Issue with backslash escaping in Laravel Blade templates

### ISSUE THREAD

**Issue by mirataollahi** [laravel/framework#49892]
### Laravel Version

10

### PHP Version

8.1

### Description

I encountered an issue while using **localization** in Laravel **Blade templates** involving the escaping of **backslash characters (\)**. When attempting to include a JavaScript string containing a backslash in a Blade template using the **{!! !!}** directive, the backslash is not properly rendered, leading to unexpected behavior.

### Steps To Reproduce

1 - I have a localization file (en/messages.php) where I define a translated message containing a **backslash**

`alert_message' => 'The message translate text\\'
`

<br>

2 - In my Blade template, I attempt to include this translated message in a **JavaScript** string using the **{!! !!}** directive

`<script>alert("{!! __('alert_message') !!}");</script>
`

<br>

3 - However, the backslash in the translated message is not properly escaped, causing issues with the JavaScript string

<br>

After investigating, I found a workaround using the addcslashes helper function:
`<script>alert("{{ addcslashes('\\','\\') }}")</script>
`

<br>

This workaround effectively resolves the issue by ensuring that the backslash is properly escaped in the JavaScript string.

<br>

While this workaround works for my case, it would be beneficial if Laravel could handle backslash escaping more gracefully in Blade templates, especially when using the {!! !!} directive.

<br>

I believe this issue could be addressed by improving the handling of backslashes in the Blade templating engine, ensuring that they are properly escaped in JavaScript strings when using the **{!! !!}** directive.

<br>

Thank you for your attention to this matter.

**Comment by rojtjo** [comment]
This is happening because your are manually creating a string in JS and not doing any escaping.

This is what's happening now:
`"{!! 'Foo \\' !!}"` = `"Foo \"`

Double escaping (once for PHP and once for JS) would work in this case, but I still wouldn't recommend it:
`"{!! 'Foo \\\\' !!}"` = `"Foo \\"`

It would probably be safer to use `json_encode` with the correct flags, or even better use the built in `Illuminate\Support\Js::from` helper:
`{{ Illuminate\Support\Js::from('Foo \\') }}` = `'Foo \\'`

See: https://laravel.com/docs/10.x/blade#rendering-json

**Comment by driesvints** [comment]
Thanks @rojtjo
