### ISSUE TITLE
NotificationFake error

### ISSUE THREAD

**Issue by Herbertzz** [laravel/framework#49950]
### Laravel Version

10.41.0

### PHP Version

8.3

### Description

TypeError: get_class(): Argument #1 ($object) must be of type object, string given
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php:315
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php:280
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355
/var/www/html/tests/Feature/NotificationSendTest.php:21
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:177

### Steps To Reproduce

Execute the following test classes
```
<?php

namespace Tests\Feature;

use App\Notifications\MobileVerifyCode;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class NotificationSendTest extends TestCase
{
    use RefreshDatabase;

    public function test_mobile_verify_code()
    {
        Notification::fake();
        $mobiles = ['18800001111', '19911112222'];
        Notification::send($mobiles, new MobileVerifyCode('012345', 5));
        Notification::assertSentTimes(MobileVerifyCode::class, 2);

//        $user = User::factory()->create();
//        Notification::send($user, new MobileVerifyCode('012345', 5));
    }
}
```

**Comment by mateusjunges** [comment]
You are getting this issue because you are passing an array of strings to the `send` method, while it expects an `array` or `\Illuminate\Support\Collection` of objects. The `$notifiables` argument is then passed one by one to the `via` method  (which is typed as `object`) of your notification by the `NotificationSender` class:
https://github.com/laravel/framework/blob/c4f46abce0e69737de35b71439943ac2a24d6ec3/src/Illuminate/Notifications/NotificationSender.php#L96-L99

When faking notifications using `Notification::fake`, the `\Illuminate\Support\Testing\Fakes\NotificationFake` class is used instead of the ChannelManager. Now, when trying to send your notification, laravel will try to store your notification in a in memory array, so you can perform assertions against it later on:

https://github.com/laravel/framework/blob/c4f46abce0e69737de35b71439943ac2a24d6ec3/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L315

The line above tries to add the notification you just sent to an array like this:

 
```
$array[FQCN of the notifiable][Notifiable primary key][Notification FQCN]

$array[User::class][12345][MobileVerifyCode::class]
``` 

Since you are passing an array of strings, that line will throw an exception when calling [`get_class`](https://www.php.net/manual/en/function.get-class.php) using a string as parameter.

## Possible solution

By reading your example code, I assume you are trying to send [on-demand notifications](https://laravel.com/docs/10.x/notifications#on-demand-notifications).

If you want to send the `MobileVerifyCode` notification (which I assume that uses some sms channel) to recipients `18800001111` and `19911112222`, you can do this using the `Notification::route` method:

```php
Notification::fake();
$mobiles = ['18800001111', '19911112222'];

foreach ($mobiles as $mobile) {
    Notification::route('vonage', $mobile)
        ->notify(new MobileVerifyCode('012345', 5));
}
// Or:

Notification::route('vonage', $mobiles[0])
    ->route('vonage', $mobiles[1])
    ->notify(new MobileVerifyCode('012345', 5));
}
```

**Comment by crynobone** [comment]
See above.
