### ISSUE TITLE
Gate::after method not update results

### ISSUE THREAD

**Issue by MertcanDinler** [laravel/framework#50097]
### Laravel Version

10.44.0

### PHP Version

8.3

### Description

> "Similar to the before method, if the after closure returns a non-null result that result will be considered the result of the authorization check."

This is how the Gate::after method is described in the Laravel documentation. However, it does not function as described. Instead, it returns the result prior to calling the 'callAfterCallbacks' method if the parameter '$result' is non-null.

### Steps To Reproduce

```php
\Illuminate\Support\Facades\Gate::define('some-permission', function ($user) {
    return false; //for example check any permission for user
});

\Illuminate\Support\Facades\Gate::after(function ($user, $ability, $result) {
    return true; //for example is admin
});

\Illuminate\Support\Facades\Gate::inspect('some-permission', App\Models\User::first())->allowed() //returns false;
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by MertcanDinler** [comment]
Hi @driesvints, thanks for the fast response!

I followed your instructions reproduced the issue in this repository: https://github.com/MertcanDinler/laravel-gate-bug.
This is the exact commit: https://github.com/MertcanDinler/laravel-gate-bug/commit/73dba6585908f07e86c9b08e799786d3b94dc319

and i fix at https://github.com/laravel/framework/pull/50098 pull request

**Comment by driesvints** [comment]
After reviewing this, it seems the current behaviour is the expected one.

**Comment by MertcanDinler** [comment]
@driesvints I think the function does not perform the function described in the document. Can you explain the purpose of the function?

**Comment by driesvints** [comment]
@MertcanDinler it's a catch all for when no conditions were hit.

**Comment by MertcanDinler** [comment]
I think the documentation needs to be updated to be more descriptive of this method.
Thanks.
