### ISSUE TITLE
[Bug] MorphToMany cannot retrievable

### ISSUE THREAD

**Issue by brkfun** [laravel/framework#50111]
### Laravel Version

10.13.5

### PHP Version

8.2.8

### Database Driver & Version

Postgresql docker image latest

### Description

If you try to add the same context as laravel documentation tolds you, over here : [https://laravel.com/docs/master/eloquent-relationships#many-to-many-polymorphic-relations](url) i created same tables i created same relation functions over same models. and when i try to gather tags from my post i can't see. You can definetly understand this with the attached image.
![K11pD 1](https://github.com/laravel/framework/assets/19393636/c8d0fc4e-e63d-4897-a078-298ad64a563a)

```
// Post model get.
$p = Post::find(1);

//Post model is here.
dump($p);

//tags are not shown.
dump($p->tags);

//Tags can seen here.
dump($p->tags()->get());
```

we also try to declare `$with` over the model to be sure about it can come before initialization. and also in the example you can definetly see that.

### Steps To Reproduce

just try to create fresh laravel application and create same tables at the document example and try to run commands i show as example at the above.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by brkfun** [comment]
it was a silly thing but. It's about having a column as same name as the relation that i've. Sorry about bothering
