### ISSUE TITLE
Memory leak when using Query Builder's chunk method

### ISSUE THREAD

**Issue by masoudgh** [laravel/framework#50148]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

MariaDB 10.6.12 for Linux

### Description

I got a memory leak error when I used the `chunk` method of the Query Builder. Whereas if I use the `chunk` method of the Collection, there will be no problem.

### Steps To Reproduce

The following code snippet shows the memory leak error:

```
Leaderboard::query()
     ->withoutGlobalScope('lang')
     ->whereRelation('user', 'display_name', 'not like', 'admin_%')
     ->orderBy('user_id')
     ->chunk(100000, function (Collection $leaderboards) {
         $leaderboards = $leaderboards->map(function ($item) {
             return [
                 'user_id' => $item->user_id,
                 'score'   => $item->total,
             ];
         })->toArray();

         Leaderboard::fill(Leaderboard::GENERAL, $leaderboards);
     });
```

While this code snippet works correctly:

```
Leaderboard::query()
    ->withoutGlobalScope('lang')
    ->whereRelation('user', 'display_name', 'not like', 'admin_%')
    ->get()
    ->map(function ($item) {
        return [
            'user_id' => $item->user_id,
            'score'   => $item->total,
        ];
    })
    ->chunk(100000)
    ->toArray();
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
