### ISSUE TITLE
cant change broadcast event name in Notification file

### ISSUE THREAD

**Issue by amikavousi** [laravel/framework#50475]
### Laravel Version

8.83.27

### PHP Version

7.4

### Database Driver & Version

Mysql

### Description

cant change broadcasting event name in Notification class.

### Steps To Reproduce

i made a Notification class with php artisan make:notification and i tried db notifications and then i wanted to broadcast notification with pusher but i found this problem: in Notification.php we cant change name of the broadcasting event and **broadcastAs()**  method not working

**Comment by cojocaru-david** [comment]
There are two ways to change the broadcasting event name in Laravel:

**Simpler Method (Recommended):**

1. Create a new event class (e.g., `MyNotificationEvent`) using `php artisan make:event MyNotificationEvent`.
2. In your notification class (e.g., `MyNotification`), tell it to use the new event class instead of the default one:

```php
class MyNotification extends Notification
{
  public function broadcastOn(): Broadcastable
  {
    return new MyNotificationEvent();
  }
}
```

3. Inside the `MyNotificationEvent` class, set the broadcast channel to your desired name:

```php
class MyNotificationEvent extends Broadcastable
{
  public function broadcastOn(): string
  {
    return 'my-custom-channel'; // Replace with your actual channel name
  }
}
```

**Alternative Method (More Complex):**

1. Create a listener class (e.g., `MyNotificationEventListener`) using `php artisan make:listener MyNotificationEventListener`.
2. This listener will listen for the default event and potentially modify the event name before broadcasting.

This second method is more complex and generally not recommended unless you need to do something special before broadcasting the notification.

**Remember:**

* Set up your Pusher credentials for broadcasting to work.
* You can find more details in the Laravel documentation ([https://laravel.com/docs/10.x/broadcasting](https://laravel.com/docs/10.x/broadcasting)).

**Comment by amikavousi** [comment]
Yeah, I know there is another way (using events and listeners), but I think we can change the broadcast event name — not the channel name— in the created notification file. As for the first method you mentioned, I don't think it works in version 8 because the broadcastOn() method should return a string, not an object. thank you.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
