### ISSUE TITLE
Registering Commands using directories fails outside the app directory

### ISSUE THREAD

**Issue by neoighodaro** [laravel/framework#50545]
### Laravel Version

11.0.4

### PHP Version

8.3

### Database Driver & Version

_N/A_

### Description

Currently, to load a command outside the `app` directory, one would have to directly reference the class because [registering the directory](https://laravel.com/docs/11.x/artisan#registering-commands) the class is in will fail. This happens for several reason, but the main reason being, it's hard coded to use the App namespace in 

* [src/Illuminate/Foundation/Console/Kernel.php:366](https://github.com/laravel/framework/blob/08acc925f1ec8e1c41a54774a36720f506c5b5a8/src/Illuminate/Foundation/Console/Kernel.php#L366)
* [src/Illuminate/Foundation/Console/Kernel.php:385](https://github.com/laravel/framework/blob/08acc925f1ec8e1c41a54774a36720f506c5b5a8/src/Illuminate/Foundation/Console/Kernel.php#L385)

### Steps To Reproduce

* Create a directory outside the `app` directory
* Register it as a namespace in `composer.json`
* Create an artisan command inside this directory
* Register that directory in the `bootstrap/app.php` file

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by nunomaduro** [comment]
It seems that, indeed, the path provided need to be within the main application namespace for a for having "withCommands" discovering commands within a directory. We are open to a pull request if you wish to enable this feature for a commands directory outside of the main application namespace.

Meanwhile, you can use the `withCommands` method with the command "class" string in your application's `bootstrap/app.php`:

```php
use App\Domain\Orders\Commands\SendEmails;
 
->withCommands([
    SendEmails::class,
])
```
