### ISSUE TITLE
Call to undefined method ::middleware() when calling authorizeResource()

### ISSUE THREAD

**Issue by MichaelRushton** [laravel/framework#50566]
### Laravel Version

11

### PHP Version

8.3

### Description

Calling authorizeResource() in a resource controller throws a "Call to undefined method ::middleware()" exception.

### Steps To Reproduce

```php
Route::apiResource("/users", UserController::class);
```
```php
abstract class Controller
{
    use AuthorizesRequests;
}
```
```php
class UserController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, "user");
    }
}
```
```
[2024-03-14 21:45:45] testing.ERROR: Call to undefined method App\Http\Controllers\UserController::middleware() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\UserController::middleware() at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php:100)
```

**Comment by waynefederigan** [comment]
To be able to use `authorizeResource()` in Laravel 11, your base controller class in `app\Http\Controllers\Controller.php` should extend `\Illuminate\Routing\Controller` (because that's where the `middleware()` method is), just like the `Controller.php` file found in a fresh Laravel 10 installation.

This is what I do with the `Controller.php` file in a fresh Laravel 11 installation if I want to use `authorizeResource()`:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends \Illuminate\Routing\Controller
{
    use AuthorizesRequests;
}
```
I wonder why they removed this in Laravel 11. Even in the docs. If Laravel 11 is somebody's first time using the framework, they'll never know lol

If you also want to use the `ValidatesRequests` trait:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends \Illuminate\Routing\Controller
{
    use AuthorizesRequests, ValidatesRequests;
}
```

**Comment by waynefederigan** [comment]
To be able to use `authorizeResource()` in Laravel 11, your base controller class in `app\Http\Controllers\Controller.php` should extend `\Illuminate\Routing\Controller` (because that's where the `middleware()` method is), just like the `Controller.php` file found in a fresh Laravel 10 installation.

This is what I do with the `Controller.php` file in a fresh Laravel 11 installation if I want to use `authorizeResource()`:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends \Illuminate\Routing\Controller
{
    use AuthorizesRequests;
}
```
Now you can use it:
```php
class PostController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class);
    }
}
```
I wonder why they removed it in `laravel/laravel` 11. Even in the docs. If Laravel 11 is somebody's first time using the framework, they'll never know lol

If you also want to use the `ValidatesRequests` trait:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends \Illuminate\Routing\Controller
{
    use AuthorizesRequests, ValidatesRequests;
}
```

**Comment by nunomaduro** [comment]
@MichaelRushton Check @waynefederigan's answer.

**Comment by MichaelRushton** [comment]
@waynefederigan Thanks

@nunomaduro Is this documented anywhere? All mention of `authorizeResource` has been removed from https://laravel.com/docs/11.x/authorization?

**Comment by Henridv** [comment]
It was removed in this commit: https://github.com/laravel/docs/commit/745bab30b0c845db5bacadcc99309a8d1d6565c3

It's not linked to any pull request or bug report, so it's not clear why it's been removed.

**Comment by leo95batista** [comment]
@Henridv @nunomaduro 
any idea why this was removed from the documentation?

**Comment by vassilidev** [comment]
Up

**Comment by justinkekeocha** [comment]
The reason why this was removed, is because the middle way defined in use Illuminate\Routing\Controller will conflict with this way of defining middleware in controller: https://laravel.com/docs/11.x/controllers#controller-middleware
