### ISSUE TITLE
php artisan route:list

### ISSUE THREAD

**Issue by satrianovember** [laravel/framework#50595]
### Laravel Version

11.x

### PHP Version

8.3.3

### Database Driver & Version

MySQL 8.0.30 winx64

### Description

 Array to string conversion

  at vendor\laravel\framework\src\Illuminate\Routing\ResourceRegistrar.php:616
    612▕     protected function getResourceAction($resource, $controller, $method, $options)      
    613▕     {
    614▕         $name = $this->getResourceRouteName($resource, $method, $options);
    615▕
  ➜ 616▕         $action = ['as' => $name, 'uses' => $controller.'@'.$method];
    617▕
    618▕         if (isset($options['middleware'])) {
    619▕             $action['middleware'] = $options['middleware'];
    620▕         }

  1   vendor\laravel\framework\src\Illuminate\Routing\ResourceRegistrar.php:616
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}(}("Array to string conversion", "C:\laragon\www\rumahta\vendor\laravel\framework\src\Illuminate\utRouting\ResourceRegistrar.php")

  2   vendor\laravel\framework\src\Illuminate\Routing\ResourceRegistrar.php:275
      Illuminate\Routing\ResourceRegistrar::getResourceAction("p3ke", "index", [])

### Steps To Reproduce

![image](https://github.com/laravel/framework/assets/139841734/4cf6b6d4-bb24-4e46-9fa6-5951110126f1)

**Comment by devajmeireles** [comment]
Impossible to identify the cause without description, details, or steps to reproduce the problem. This issue will probably be closed!

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Feel free to re-open this when you have a clear way to reproduce. Thanks
