### ISSUE TITLE
Validation in / not in breaks with values ending in backslash

### ISSUE THREAD

**Issue by vkwbpo** [laravel/framework#50712]
### Laravel Version

10.29.0

### PHP Version

8.2.14

### Description

In and NotIn validation rules do not work correctly for values ending in backslash.

### Steps To Reproduce

Execute the following tinker commands:
```
Validator::make(['a' => 'b\\'], ['a' => Illuminate\Validation\Rule::notIn('b\\')])->passes();
Validator::make(['a' => 'b\\c'], ['a' => Illuminate\Validation\Rule::notIn('b\\c')])->passes();
```
First validator passes, seconds fails as expected. First should fail too.

**Comment by Katalam** [comment]
The Validator uses the function `str_getcsv($parameter)` inside the validation cycle to hydrate the Validation Rules based on a string. In your example `not_in:"b\"` the problem is, that the function `str_getcsv` uses `\"` as an escape and enclose character. So the value the parser will output will be `b\"` and that is not `b\` so the validation passes. I don't really have an idea on how to fix this

But the probleme is here: https://github.com/laravel/framework/blob/fc453b908fc41fea8b428260b2d4f3527d046bf8/src/Illuminate/Validation/ValidationRuleParser.php#L283

**Comment by PaperTurtle** [comment]
This might not be the prettiest solution, but it seems to work.
```php
protected static function parseParameters($rule, $parameter)
{
     $parameters = static::ruleIsRegex($rule) ? [$parameter] : str_getcsv(
         str_replace('\\\\', '__BACKSLASH__', trim($parameter, '"'))
     );
     return str_replace('__BACKSLASH__', '\\\\', $parameters);
 }
```

I don't know if there are any security concerns, but I could do a PR and implement this.

**Comment by driesvints** [comment]
Looks like for now, we're not going to support this, sorry.
