### ISSUE TITLE
Impossible to use a password mutator now

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/framework#50739]
### Laravel Version

11.x

### PHP Version

8.3.x

### Description

The big impact of using this new behavior of password rehashing is this, a password mutator:

```php
// app/Models/User.php

/**
 * Interact with the user's password.
 */
public function password(): Attribute
{
    return Attribute::make(
        set: fn(string $value) => Hash::make($value)
    );
}
```

I'm aware you can disable it on login by changing a config value: https://laravel.com/docs/11.x/upgrade#password-rehashing

But when calling the `Auth::logoutOtherDevices($request->get('password'));` for example, we have this executed: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Auth/EloquentUserProvider.php#L172-L174
And you can't login with your password because it will be hashed twice

### Steps To Reproduce

* Create a fresh laravel project
* Use a password mutator

```php
/**
 * Interact with the user's password.
 */
public function password(): Attribute
{
    return Attribute::make(
        set: fn(string $value) => Hash::make($value)
    );
}
```
* (optionnal) Install Breeze and refactor the password hashing from the controllers/actions and use the mutator instead
* Use `Auth::logoutOtherDevices($currentPassword);` https://laravel.com/docs/11.x/authentication#invalidating-sessions-on-other-devices

You can't use the same password because it will be hashed twice

**Comment by crynobone** [comment]
Wouldn't it be better to use the available `hashed` cast?

**Comment by valorin** [comment]
This wasn't caused by the rehashing changes in 11.x, the `Auth::logoutOtherDevices($request->get('password'));` function has always rehashed the password - that's how it works.

Either `logoutOtherDevices` needs to use something other than the password hash - so it can be changed without rehashing, or your custom hash cast needs to take into account the possibility of receiving a hash.

Checkout how the default `hashed` cast works: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1374-L1389

**Comment by crynobone** [comment]
Just added #50744 to verify that this behavior exists from Laravel 10 and what @valorin has said.

**Comment by driesvints** [comment]
Think @valorin gives everything you need to make your code work @arcanedev-maroc.
