### ISSUE TITLE
PHP expression runs twice when passing to blade component

### ISSUE THREAD

**Issue by mokhosh** [laravel/framework#50777]
### Laravel Version

11.0.8

### PHP Version

8.3.3

### Description

If you use a method to pass data to a blade component, the method will be run twice, leading to unexpected behaviour.

For example, you would think this will simply `shift` the first item, and pass it to the component:
```blade
<x-article :article="$articles->shift()"/>
```
But it removes two items from the `$articles` collection.

You would have to do something like this to fix it:
```blade
@php($first = $articles->shift())
<x-article-card :article="$first"/>
```

### Steps To Reproduce

1. Create a blade component with a prop
2. Use that component in another blade template
3. Create a collection of 4 items and pass the first item to the component using `shift`
4. Dump the collection after the component

**Comment by danharrin** [comment]
Ref #50403 #50479

**Comment by driesvints** [comment]
Using the solution from above is, for now at least, the only one.

**Comment by schakko** [comment]
Just came here to provide another workaround as I also stumbled upon that behavior. The issue above only happens when using anonymous Blade components (e.g. `resources/views/components/article/card.blade.php` in the opener's comment).
In case of using class-backed Blade components, the method `shift()` would only be called once.

Because of this you can create a wrapper component like

```php
class Card extends Component {
	public function __construct(public readonly Article $article) {
	}

	public function render() {
		return view('components.article.blade', ['article' => $this->article]);
	}
}
```

and then use it in your caller view like
```php
<x-article-card :article="$articles->shift()" />
```

It does not fix the original issue, introduces a little bit more complexity but is easier to re-use.
