### ISSUE TITLE
fill method not working on mutators if you have some guarded attributes

### ISSUE THREAD

**Issue by mokhosh** [laravel/framework#51065]
### Laravel Version

11.1.0

### PHP Version

8.3.3

### Description

If you have a user model like this:

```php
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Foundation\Auth\User as IlluminateUser;

class User extends IlluminateUser
{
    protected $guarded = [
        'remember_token',
    ];

    protected $appends = [
        'location',
    ];

    public function location(): Attribute
    {
        return Attribute::make(
            get: fn (mixed $value, array $attributes) => [
                'lat' => $attributes['latitude'],
                'lng' => $attributes['longitude'],
            ],
            set: fn (array $value) => [
                'latitude' => $value['lat'],
                'longitude' => $value['lng'],
            ],
        );
    }
}
```

This doesn't work and completely ignores `location`:
```php
$user->fill(['location' => [
    'lat' => 1,
    'lng' => 2,
]])
```

This works:
```php
$user->forceFill(['location' => [
    'lat' => 1,
    'lng' => 2,
]])
```

Interestingly, `fill` works fine with this:
```php
protected $guarded = [];
```
but not if you have guarded the `remember_token` as per the original example!

This also works, but you have to add all attributes again, and you can't mix and match with `guarded`:
```php
protected $fillable = [
    'location',
];
```

### Steps To Reproduce

Add `latitude` and `longitude` columns to the `users` table in a fresh Laravel installation, and paste the codes above, and `tinker` with the model to see the behaviour.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
