### ISSUE TITLE
Possible bug in the ORM

### ISSUE THREAD

**Issue by Mdhesari** [laravel/framework#51105]
### Laravel Version

10.45.1

### PHP Version

8.3

### Database Driver & Version

MYSQL 8.0

### Description

I think there is a problem with Laravel's ORM. 
We wanted to support both id and slug so this is our query:

`$query->whereSlug("02t-19")->orWhere("id", "02t-19")->firstOrFail();`

I was amazed that it also finds an id of product 2 with the wrong slug.

### Steps To Reproduce

* A table called products is created on the db having slug and id with many records.
* Run the query in route service provider:
`Route::bind('product', fn ($value) => Product::whereSlug($value)->orWhere('id', $value)->firstOrFail());`
* It returns a record with the id of "2" with the slug of "156-tfb" instead of id "502" and slug of "02t-19"

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by Mdhesari** [comment]
I found out that the problem is with the mysql itself when ran the query in its cli!

So no problem with the ORM!
