### ISSUE TITLE
Some events are listed and called twice since v11.9.2

### ISSUE THREAD

**Issue by clementbirkle** [laravel/framework#51646]
### Laravel Version

11.9.2

### PHP Version

8.2

### Description

After updating Laravel from v11.8.0 to v11.9.2, some events are listed and called twice in my testing environment.

For instance, `php artisan event:list` shows:

<img width="397" alt="events" src="https://github.com/laravel/framework/assets/9021081/44969fbf-a785-4f0b-8d21-6def36a0aa35">

I didn't manually register those events.

I don't know if it's an issue linked to Laravel or my app.

### Steps To Reproduce

Try `php artisan event:list` command.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by clementbirkle** [comment]
@driesvints thank you very much!!

It was exactly my case! I just removed `shouldDiscoverEvents` from `EventServiceProvider` and now it works well.

**Comment by gmanikandan-dev** [comment]
It works.Thank you @clementbirkle

**Comment by HassanElshazlyEida** [comment]
in my case it seem that when you inject Event as **Dependency injection** `OrderPlaced` into your listener it will be automatically called without register it in `EventServiceProvider`
```
  /**
     * Handle the event.
     *
     * @param OrderPlaced $event
     * @return void
     */
    public function handle(OrderPlaced $event): void
    {

    }

```
you can debug your active listeners here
```
Route::get('/debug-events', function () {
    $listeners = Event::getListeners(OrderPlaced::class);
    dd([
        'event_class' => OrderPlaced::class,
        'listener_count' => count($listeners),
        'listeners' => array_map(function($listener) {
            if (is_array($listener) && is_object($listener[0])) {
                return get_class($listener[0]);
            }
            return $listener;
        }, $listeners)
    ]);
});

```

**Comment by gokigoks** [comment]
@HassanElshazlyEida Thank you for the snippet and the useful info. I was scratching my head on why my events were being fired twice.
