### ISSUE TITLE
PHP Fatal error:  Uncaught BadMethodCallException: Method Illuminate\Foundation\Application::withSchedule does not exist. in /vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:115

### ISSUE THREAD

**Issue by BrenoRibeiro706** [laravel/framework#51808]
### Laravel Version

11.10.0

### PHP Version

8.3.8

### Description

I'm trying to use the "withScheduling" method in my `bootstrap/app.php` but I'm not succeeding.

**My `app.php`:**

```php
<?php

use Illuminate\Console\Scheduling\Schedule;
use App\Tasks\DisableInactiveUsers;
use App\Tasks\DeleteDisabledUsers;
use App\Tasks\NotifyUsersOfInactiveColleagues;

$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

$app->withSchedule(function (Schedule $schedule) {
    $schedule->call(new DisableInactiveUsers())->daily();
    $schedule->call(new DeleteDisabledUsers())->daily();
    $schedule->call(new NotifyUsersOfInactiveColleagues())->daily();
});

return $app;


### Steps To Reproduce

Use the withSchedule method as mentioned in the documentation

**Comment by rodrigopedra** [comment]
Documentation never stated the `Illuminate\Foundation\Application` class to have a `withSchedule` method.

This method is available within the `\Illuminate\Foundation\Configuration\ApplicationBuilder` class.

Why are you new'ing up a `Illuminate\Foundation\Application` object, instead of using `Application::configure()` as it is shown in the docs when on the application skeleton (https://github.com/laravel/laravel)?

https://github.com/laravel/laravel/blob/3b3f9f13faab1753e7b7cad6a0e7098e54c8199f/bootstrap/app.php#L3-L18

**Comment by rodrigopedra** [comment]
Oh, I guess I figured out what is happening... You are following Laravel 11 docs but are using an older Laravel version...

If you can't upgrade your project to Laravel 11, please follow an older version of the docs, such as:

https://laravel.com/docs/10.x

**Comment by driesvints** [comment]
Thanks @rodrigopedra
