### ISSUE TITLE
[11.11] Cannot bind an instance to a static closure

### ISSUE THREAD

**Issue by rcerljenko** [laravel/framework#51839]
### Laravel Version

11.11.0

### PHP Version

8.3.8

### Database Driver & Version

MySQL 8.0.37

### Description

With a new minor release came [this PR](https://github.com/laravel/framework/pull/51772) that broke factory `afterCreating()` method.

Issue is happening when a closure function is declared as `static` ([rector](https://github.com/rectorphp/rector) does that autmatically for us) in the factory `afterCreating()` method.

See images below.

Error message:
![image](https://github.com/laravel/framework/assets/16762056/c9f02357-4e90-4317-ad24-be95519bee5e)

Our code that uses this method:
![image](https://github.com/laravel/framework/assets/16762056/1653d403-fb4e-49b3-9e20-1d1d4cfc970f)

### Steps To Reproduce

Use a `static` clusure in factory `afterCreating()` method.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by rcerljenko** [comment]
We don't have to do all of that... You can just change this line in the factory test to declare a `static` closure instead of non-static one.

https://github.com/laravel/framework/blob/11.x/tests/Database/DatabaseEloquentFactoryTest.php#L271

**Comment by driesvints** [comment]
Ping @jacob418

**Comment by mabdullahsari** [comment]
Can confirm:

https://github.com/laravel/framework/pull/51772#issuecomment-2180130828

**Comment by driesvints** [comment]
Reverted.
