### ISSUE TITLE
Exceptions::fake() not working after upgrading from Laravel v8 to v11

### ISSUE THREAD

**Issue by antonkomarev** [laravel/framework#52010]
### Laravel Version

11.11.1

### PHP Version

8.2.18

### Description

I'm trying to use new feature `Exceptions::fake()`, but it just ignored. Not in HTTP tests, but in integration ones.

I've double checked that `Concerns\InteractsWithExceptionHandling` trait is exists in base test case class.

After upgrade I haven't migrated app to the new slim structure as it stated in upgrade guide:
> However, we do not recommend that Laravel 10 applications upgrading to Laravel 11 attempt to migrate their application structure, as Laravel 11 has been carefully tuned to also support the Laravel 10 application structure.

### Steps To Reproduce

This test is working well:
```php
public function testWorking(): void
{
    $this->expectException(\DomainException::class);
    $this->expectExceptionMessage(
        "The order was invalid.",
    );

    app(OrderService::class)->process(
        123,
    );
}
```

This test is failing because it's not handling exceptions:
```php
public function testNotWorking(): void
{
    Exceptions::fake();

    app(OrderService::class)->process(
        123,
    );

    Exceptions::assertReported(function (\DomainException $e) {
        return $e->getMessage() === 'The order was invalid.';
    });
}
```

This one is not working too:
```php
public function testNotWorkingToo(): void
{
    $exceptions = Exceptions::fake();
    
    app(OrderService::class)->process(
        123,
    );

    $exceptions->assertReported(function (\DomainException $e) {
        return $e->getMessage() === 'The order was invalid.';
    });
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by antonkomarev** [comment]
I'm not sure it will reproduce on v11 from scratch, I need to create v10 or below and upgrade it first

**Comment by driesvints** [comment]
We’ll need to figure out what’s missing from the upgrade guide if this isn’t working for you. Please indeed provide a repo and commit the upgrade steps separately

**Comment by donnysim** [comment]
I don't think it works in the way you expect. If you don't call a route it does not go through the exception handling pipeline and you have to specify on the test what exception you're expecting because it's not a framework exception but a direct call to a service/class etc.. For this to work outside of the routes, the framework would most likely need to override the PHPUnits test running as the exception you see in the console is handled by the try/catch in the PHPUnit side and the exception/error does not reach the application exception handler.

**Comment by donnysim** [comment]
In short, you cannot do this:
```php
    public function testNotWorkingToo(): void
    {
        Exceptions::fake();

        throw new \DomainException('The order was invalid.');

        Exceptions::assertReported(function (\DomainException $e) {
            return $e->getMessage() === 'The order was invalid.';
        });
    }
```
and expect that the exception magically gets silenced/swallowed.

**Comment by crynobone** [comment]
Thanks @donnysim

**Comment by nickezekias** [comment]
Hello guys!
I'm using latest laravel 11 as fo date of writing, and I still get the same Exceptions::fake() problem in unit tests.

This is the error I get when the test fails:
`Illuminate\Support\Testing\Fakes\ExceptionHandlerFake::__construct(): Argument #1 ($handler) must be of type Illuminate\Contracts\Debug\ExceptionHandler, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Exceptions.php on line 54`

**Comment by einenlum** [comment]
> I don't think it works in the way you expect. If you don't call a route it does not go through the exception handling pipeline and you have to specify on the test what exception you're expecting because it's not a framework exception but a direct call to a service/class etc.. The exception you see in the console is handled by the try/catch in the PHPUnit side and the exception/error does not reach the application exception handler.

Wow. It took me a while to debug this and finally find this issue and finally understand what was wrong. I know [this part](https://laravel.com/docs/12.x/http-tests#exception-handling) is in the "http tests" section of the documentation but maybe we could add a small paragraph to warn devs about this?
