### ISSUE TITLE
Bug: `Attribute "..." cannot target parameter (allowed targets: property)`

### ISSUE THREAD

**Issue by devajmeireles** [laravel/framework#52247]
### Laravel Version

11.17

### PHP Version

8.2.21

### Description

The PR: https://github.com/laravel/framework/pull/52167 accidentally introduced what I think is a potential breaking change related to attribute usage through container. This bug was originally reported here: https://github.com/tallstackui/tallstackui/issues/567.

---

One of my [open-source package](https://github.com/tallstackui/tallstackui) contains an attribute that we use only to mark properties to skip certain conditions **(see below)**. After upgrading any of my projects using this package to Laravel 11.17 this error happens:

![CleanShot 2024-07-23 at 16 46 19@2x](https://github.com/user-attachments/assets/06f22577-908a-4d6a-9b8b-7095465bb14a)

---

The source of the error matches the changes made in the PR mentioned above:

![CleanShot 2024-07-23 at 16 50 30@2x](https://github.com/user-attachments/assets/fad19e75-d2b6-46c0-a1a7-54fe3f7dcb3f)

Here: https://github.com/laravel/framework/pull/52167/files#diff-cc160328d7d447677b8d359453f4416c820a9117c5efd500a3f0361d1d5bab1a

### Steps To Reproduce

IDK exactly how to reproduce this, but I guess it just try to use an attribute in a public parameter, like this:

```php
<?php

namespace App\Attributes;

use Attribute;

#[Attribute(Attribute::TARGET_PROPERTY)]
class SkipDebug
{
    //
}
```

```php
use App\Attributes\SkipDebug;

public function __construct(
    #[SkipDebug]
    public ?string $size = null,
) {
    //
}
```

**Comment by devajmeireles** [comment]
The fix in my case seems easy: 

```php
#[Attribute(Attribute::TARGET_PROPERTY | Attribute::TARGET_PARAMETER)]
class SkipDebug
{
    //
}
```

... But I just want to confirm that this will not generate a breaking change in other applications using this new version of Laravel 🤔

**Comment by innocenzi** [comment]
While technically this was, in fact, a breaking change, you have to specify `TARGET_PROPERTY` and `TARGET_PARAMETER` if you are going to use an attribute on a parameter using property promotion. That's why `newInstance` throws here.

I'll see tomorrow if we can mitigate this breaking change by looking for the attribute targets before creating the instance (or rescuing the throw), because marker attributes that are not properly configured will all throw now.

**Comment by innocenzi** [comment]
Okay, I was trying to make a `getTarget` check, but the more I thought about it, the more I realized that this is just trying to work around userland bugs.

When using an attribute in a constructor, you need that attribute to have the right target for it. Otherwise it means that the attribute wasn't supposed to be used in that place. 

The fact that this new version of Laravel throws because of that is just revealing of an issue in your code, and the breaking of the package is a side-effect of that.

I think this is not an actual issue with Laravel, and should be taken care of in userland packages.

**Comment by devajmeireles** [comment]
> Okay, I was trying to make a `getTarget` check, but the more I thought about it, the more I realized that this is just trying to work around userland bugs.
> 
> When using an attribute in a constructor, you need that attribute to have the right target for it. Otherwise it means that the attribute wasn't supposed to be used in that place.
> 
> The fact that this new version of Laravel throws because of that is just revealing of an issue in your code, and the breaking of the package is a side-effect of that.
> 
> I think this is not an actual issue with Laravel, and should be taken care of in userland packages.

I guess I disagree because it worked perfectly fine in Laravel 11.16, but not in the new version. Anyway, I will update it to the expected format. I believe that thousands of other applications and packages will have the same problem.

**Comment by driesvints** [comment]
we reverted the causing PR.
