### ISSUE TITLE
Class Illuminate\Http\Request has a method named "method".

### ISSUE THREAD

**Issue by abarker-gravity** [laravel/framework#52567]
### Laravel Version

11.16.0

### PHP Version

8.3.10

### Database Driver & Version

N/A

### Description

Class Illuminate\Http\Request has a method named "method". Doubling classes that have a method named "method" is deprecated. Support for this will be removed in PHPUnit 12.

Looks like PHPUnit is deprecating mocking classes with a method called "method." I am not sure what the work around here is. Mockery has its own set of issues with PHPStan when setting up expectations. `Call to an undefined method Mockery\ExpectationInterface|Mockery\ExpectsHigherOrderMessage::with()`.

I would prefer to use PHPUnit's built in mocking but I am wondering how that is going to work with Laravel moving forward as you've implemented `Illuminate\Http\Request::method()`. If I need to move to PSR-7 or something else to avoid this, I would rather do that sooner than later.

### Steps To Reproduce

```
class MyControllerTest extends Illuminate\Foundation\Testing\TestCase
{
    public function testMyEndpoint(): void
    {
        // Class Illuminate\Http\Request has a method named "method". Doubling classes that have a method named "method" is deprecated. Support for this will be removed in PHPUnit 12.
        $this->createMock(Request::class)
            ->expects($this->once())
            ->method('input')
            ->with('param')
            ->willReturn('data');
  
       /* OR */

        // phpstan: Call to an undefined method Mockery\ExpectationInterface|Mockery\HigherOrderMessage::with().
        Mockery::mock(Request::class)
            ->shouldReceive('input')
           ->with('param')
           ->andReturn('data');
    }
}
```

**Comment by samlev** [comment]
It would be a difficult decision to make. The `method()` function is just a wrapper for `getMethod()` from Symfony/PSR-7 with no extra functionality so removing it to appease PHPUnit wouldn't be a loss of functionality... But it's still a _massive_ BC break because `method()` has been the documented function to use for many, many years.

To a certain extent I don't like the idea of removing or changing the interface of a very commonly used class because an external library made a decision like this, and I suspect that the answer will be "we're leaving `method()` where it is. Just don't use PHPUnit's doubling feature for HTTP requests."

Laravel tests internally use Mockery, not PHPUnit's doubling features. I've never seen PHPStan complain about mocked classes - are you using Larastan? I suspect that it might be an issue with Mockery's documentation, so maybe it's worth going there to update doc blocks, or you might just be able to stub it out or add a rule to ignore that specific complaint.

**Comment by crynobone** [comment]
It's not a common practise to actually mock a Request, since you can easily create an object instance using.

```php
$request = Request::create(/* ... */);
```

https://github.com/symfony/http-foundation/blob/f602d5c17d1fa02f8019ace2687d9d136b7f4a1a/Request.php#L280

**Comment by abarker-gravity** [comment]
@crynobone I've spent a few hours trying to get `$request = Request::create(/* ... */);` working but unfortunately I still haven't figured out how to use `Request::create(/* ... */)->validate()` because it's macro is expecting `$this->isPrecognitive()` and it doesn't get set by `FoundationServiceProvider`.
