### ISSUE TITLE
Mariadb 10.1 breaks with Laravel 11, and no warning in upgrade instruction!

### ISSUE THREAD

**Issue by programmin1** [laravel/framework#52634]
### Laravel Version

11.x

### PHP Version

8.2

### Database Driver & Version

10.1.48-MariaDB, for debian-linux-gnu

### Description

Laravel 11 and nunomaduro/collision 8.1 upgrades in composer, break some upgrades and inserts!

It mentions curl and PHP but it doesn't mention Mariadb requirement on https://laravel.com/docs/11.x/upgrade#updating-dependencies

### Steps To Reproduce

On Ubuntu 18.04, 
Change the dependencies noted here - framework and collision:
https://laravel.com/docs/11.x/upgrade#updating-dependencies

You will note that it throws errors on insert/update:

Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql, SQL: select...

As I have read on other libraries this seems to be caused by Mariadb 10.1. Setting back to Laravel 10.x works fine.

**Comment by rodrigopedra** [comment]
The database section on documentation lists the compatible databases:

https://laravel.com/docs/11.x/database#introduction

Regarding MariaDB, it supports versions 10.3+.

I am not sure if this should be listed in the upgrade guide, as it is an external component.

**Comment by rodrigopedra** [comment]
Actually, Laravel 10 supported an even more recent MariaDB version (MariaDB 10.10+)

https://laravel.com/docs/10.x/database#introduction

So, Laravel 11 expanded support on MariaDB versions.

According to MariaDB's Maintenance Policy, version 10.1 is "End of life" since Oct 17th, 2020. 

https://mariadb.org/about/#maintenance-policy

You should consider upgrading your database to a newer version.

**Comment by driesvints** [comment]
As @rodrigopedra says, 10.1 isn't supported anymore. Please upgrade.
