### ISSUE TITLE
URL Validation passes with a url without a TLD

### ISSUE THREAD

**Issue by cirolosapio** [laravel/framework#52921]
### Laravel Version

9.52.16

### PHP Version

8.2.23

### Description

The `url` validation rule passes on a url without a TLD, e.g. `http://laravel`

### Steps To Reproduce

```
>>> Validator::validate(['test' => 'http://google'], ['test' => 'url'])
[
  "test" => "http://google",
]
```

related https://github.com/symfony/symfony/issues/44252

**Comment by staudenmeir** [comment]
Hi @cirolosapio,
URLs don't have to include a TLD to be valid, consider `http://localhost` for example.

> related https://github.com/symfony/symfony/issues/44252

This Symfony issue describes the "opposite" case: A bug that _stopped_ URLs without TLD from passing the validation.

**Comment by Jubeki** [comment]
Hey, I think the validator works as expected, because you can use such url for internal company networks, or with something like Docker (https://docs.docker.com/engine/network/#ip-address-and-hostname: In the same way, a container's hostname defaults to be the container's ID in Docker. )

```
http://google
```

is in that regard a valid URL, even without a TLD.

See https://stackoverflow.com/a/28008119

The rule `url` checks not only for https or http, but for many different possible URL schemes:
https://laravel.com/docs/11.x/validation#rule-url

If you want you can use `active_url` which will check for a valid A or AAAA record:
https://laravel.com/docs/11.x/validation#rule-active-url

**Comment by crynobone** [comment]
Thanks @Jubeki @staudenmeir
