### ISSUE TITLE
Method Illuminate\Foundation\Application::fireAfterResolvingAttributeCallbacks does not exist.

### ISSUE THREAD

**Issue by AkramZerarka** [laravel/framework#52920]
### Laravel Version

11.24.0

### PHP Version

8.3

### Description

---

I have an application based on Laravel and Livewire using a multi-tenant architecture. When I upgraded the project from **x10** to **x11** and fixed the routing, I encountered the following error when trying to access the "show" page (which is a simple page to view details):

```
Method Illuminate\Foundation\Application::fireAfterResolvingAttributeCallbacks does not exist.
```

---

### Steps To Reproduce

![Capture d’écran 2024-09-25 105321](https://github.com/user-attachments/assets/0deedf3c-a956-4251-bae7-f95d9a1f6971)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by AkramZerarka** [comment]
I think fireAfterResolvingAttributeCallbacks doen't existe

**Comment by crynobone** [comment]
That's not correct: `Illuminate\Foundation\Application` extends `Illuminate\Container\Container`: https://github.com/laravel/framework/blob/09aaeb40cb7c21b4837305c4561164997c45f090/src/Illuminate/Container/Container.php#L1359

**Comment by AkramZerarka** [comment]
I will close this issue because it originates from the package [michael-rubel/laravel-enhanced-container](https://github.com/michael-rubel/laravel-enhanced-container).
