### ISSUE TITLE
storage exists is not working in s3

### ISSUE THREAD

**Issue by Rignesh-Sarvaliya** [laravel/framework#53037]
### Laravel Version

8.40

### PHP Version

7.4

### Database Driver & Version

MySQL 8.0

### Description

`Storage::disks('s3')->exists()` is not functioning correctly when using Amazon S3 as the storage driver in a Laravel project. The method consistently returns false, even for files known to exist in the specified bucket.

### Steps To Reproduce

Configure Laravel to use S3 as the storage driver.
Upload a file to the S3 bucket using` Storage::disks('s3')->put()`.
Call `Storage::disks('s3')->exists('path/to/file')` for the uploaded file.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by Rignesh-EWW** [comment]
> Hey there,
> 
> Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!

Hey @crynobone ,

Thanks for your response. I understand that this version is no longer supported. However, this issue just recently started happening after the functionality was working fine for a while. It was working just 2 days ago, but now I can't understand why it suddenly stopped. Nothing has changed in terms of configuration or permissions, and the issue seems to have appeared out of nowhere.

Any thoughts on what might have caused this?

Thanks!
