### ISSUE TITLE
Checking custom validation messages not using translator has() function

### ISSUE THREAD

**Issue by petrzpav** [laravel/framework#53510]
### Laravel Version

11

### PHP Version

8.2

### Description

The `getCustomMessageFromTranslator` function is using custom logic to check for translation messages instead of leveraging the translator's `has()` function.

This behavior causes an error when checking if a translation exists within the get function. Replacing this logic with the `has()` function would standardize the check and prevent such errors.

Reference: [Laravel source](https://github.com/laravel/framework/blob/a296e813d041ddff000d856aa2f7ae1cd4d616b7/src/Illuminate/Validation/Concerns/FormatsMessages.php#L159-L165)

### Steps To Reproduce

```
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email:rfc,dns|max:255|unique:users',
        ]);
```
Calling translator `get()` instead of translator `has()`.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
