### ISSUE TITLE
AI and CDR files cannot be uploaded.

### ISSUE THREAD

**Issue by hmingv** [laravel/framework#53523]
### Laravel Version

11.31.0

### PHP Version

8.2

### Description

From https://github.com/laravel/framework/issues/53494

### Steps To Reproduce

Just need to try uploading the file and verify the mimetype through form validation.

**Comment by hmingv** [comment]
I took his advice seriously, so I tested it with the latest Laravel version, but the problem still persisted. So I replicated the issue.

**Comment by tisuchi** [comment]
> I took his advice seriously, so I tested it with the latest Laravel version, but the problem still persisted. So I replicated the issue.

Hmm.. Get your point!

Interesting!

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by hmingv** [comment]
Thank you for your response, I have already released a public repository

Here it is: https://github.com/hmingv/bug-report

**Comment by ahinkle** [comment]
`AI` and `CDR`file types are not included in the [Apache MIME Type Registry](https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types).

To handle these file types, you can either extend your server's MIME type configuration or create a custom validation rule in your application.

https://laravel.com/docs/11.x/validation#rule-mimes

**Comment by crynobone** [comment]
Thanks @ahinkle
