### ISSUE TITLE
Auto-Discovery for Events and Listeners Causes Duplicate Listener Entries and Conflicts with Manual Registration

### ISSUE THREAD

**Issue by votkapower** [laravel/framework#53533]
### Laravel Version

11.31

### PHP Version

8.2

### Database Driver & Version

Mysql

### Description

**Problem Description**

Laravel's auto-discovery for events and listeners, along with its automatic linking, is a fantastic feature. However, **there is no way to disable this functionality**.

When you manually specify listeners for each event in the `AppServiceProvider` and then run `php artisan event:list`, the **listeners are listed twice—once from auto-discovery and once from manual registration.**

This creates a conflict, especially when you want to control the order of execution. Currently:

- The execution order of listeners is unclear.
- There is no documented way to define or enforce the order of execution.

**Suggested Improvement**

Laravel should provide a method to disable the auto-linking of events and listeners. This would allow developers to manually specify listeners and their order, ensuring a predictable and controlled execution flow.

Related Issues I found  reporting similar concerns, such as this one: https://github.com/laravel/framework/issues/52714

### Steps To Reproduce

Follow steps into this issue: https://github.com/laravel/framework/issues/52714

**Comment by votkapower** [comment]
tried:
- php artisan cache:clear
- composer dump autoload
- tried creating new EventServiceProvider with the old $listens prop

Still for my custom evets I see double the listenrs once ending with "@handle" and once without. Is there any solution to remove the duplicates and configure the order of execution?

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by mariusaustr** [comment]
I have just faced the same issue. I wonder if there is a solve for this?

**Comment by victor-david** [comment]
According to the docs, Laravel 13 has a way to disable auto discovery on listeners.

I'm using Laravel 12 and solved the problem by placing the listeners in another directory that Laravel doesn't auto scan, and registering them explicitly in `AppServiceProvider`.
