### ISSUE TITLE
Eloquent should support composite keys

### ISSUE THREAD

**Issue by aebersold** [laravel/framework#5355]
Eloquent assumes heavily that you are using [surrogate keys](http://en.wikipedia.org/wiki/Surrogate_key) on your tables (the `id` field in every table). However in real world usage, particularly older database systems not designed with web frameworks in mind, there are often tables with [composite keys](http://en.wikipedia.org/wiki/Compound_key). That is, the primary key is over two or more columns. Often, you can't just add autoincremented id's. This is definitely a game stopper for a lot of use-cases, where you are forced to access existing RDBMS (e.g. building a frontend for an existing db). See also this [reddit post](http://www.reddit.com/r/PHP/comments/1yqown/worse_things_about_laravel/cfn9w24) about this issue.

The schema builder has already support for [composite keys](http://laravel.com/docs/schema#adding-indexes), however eloquent doesn't seem to support it yet.

I request the feature to use composite keys in your eloquent models and queries. The default configuration for surrogate keys is fine, just add the option.

**Comment by piotrchludzinski** [comment]
I want it!

**Comment by HiroKws** [comment]
-1
This is not "should" stuff. Please keep Eloquent simple.
As you mentioned, query builder supported it, so it is enough.

Don't do every thing by Eloquent. Just use query builder, results became collections in L5, so what problem?

**Comment by GrahamCampbell** [comment]
I doubt this will ever happen.

**Comment by ClickerMonkey** [comment]
Why do you doubt this will ever happen? 

Composite keys are extremely common, if the SchemaBuilder supports it why wouldn't you want to have it supported by Eloquent as well?

Keeping Eloquent "simple" is a very silly reason. To the end-user nothing changes - but they now have the ability to specify an array for the primary key. If Laravel/Eloquent really expects to be taken seriously and provide further credit for using PHP for web development it should naturally support what every other ORM supports for alternative web development libraries.

Using pivot only is doable when you have a few extra columns on your relation... otherwise it's very awkward.

Using the query builder for saving & deleting is kind of silly, why would anyone want those inconsistencies in their code? Some places you use Eloquent for saving/deleting and some places you use QueryBuilder? This kind of attitude is poor and sounds lazy.

If Laravel is open to receiving a feature like this, I would be more than willing to supply a nice simple and efficient solution.

**Comment by Evertt** [comment]
+1

**Comment by fireball70** [comment]
+1
Maybe in 90% of my projects I use composite primary keys. For localisation and for one to many relationships composite keys is the best practice for me... I'm very dissapointed that in Laravel 5 there is no composite keys, but a lot of complicated design patterns. That is my opinion. Don't want to argue with anyone.

**Comment by vvinhas** [comment]
Eloquent uses the Active Record pattern, it needs a single primary key to work. 
If you need composite keys in your project, maybe Eloquent isn't the best tool for it.

**Comment by ClickerMonkey** [comment]
The Active Record pattern makes no restrictions about primary keys - I don't know where you're getting that from. 

Eloquent/Laravel is currently developed to work with a single primary key, there's no reason why someone shouldn't be able to make a contribution to the project which adds composite keys. What is the best way to go about this?

**Comment by vvinhas** [comment]
All I'm saying is that this is a convenction in other frameworks as well. Since Rails made it popular, the other frameworks followed the same path, that's what we see out there with most PHP frameworks (except Yii 2, for what I know).

Don't get me wrong, I would love to see Eloquent working with composite keys but I agree with Campbell, we're not going to see that happen so soon and my opinion is that I don't think it's worth the trouble. Well, only Taylor can tell :)

**Comment by ClickerMonkey** [comment]
If the current contributors aren't interested in implementing this feature, I'm more than willing to submit how I'm going to solve it (so I don't waste my time and have it be later rejected) - I just don't know who exactly to message to get the go ahead to work on it.

**Comment by vvinhas** [comment]
Laravel developers are always willing to accept new ideas from the community, you can write to @GrahamCampbell or even @taylorotwell

**Comment by GrahamCampbell** [comment]
> Laravel developers are always willing to accept new ideas from the community, you can write to @GrahamCampbell or even @taylorotwell

Please pose questions to Taylor. He's the only one that can say yes/no to proposals.

**Comment by GrahamCampbell** [comment]
As things stand, this issue is rejected, so it's unlikely for this to make it into the framework.

**Comment by aebersold** [comment]
@taylorotwell are you willing to accept a pull request for this proposal?

**Comment by Evertt** [comment]
@taylorotwell please respond, I'd love this

**Comment by mysteryos** [comment]
Just hit this bump as well.
Would love support for composite keys.

**Comment by emersonku** [comment]
I want this feature badly.

**Comment by rossedman** [comment]
This seems like a package waiting to happen more than something that needs to be added to the framework. I agree with @vvinhas . Just switch out your ORM to Doctrine 2? Is that a logical solution?

[Article here](http://culttt.com/2014/06/30/getting-started-doctrine-2-laravel/)
[Doctrine Composite Keys](http://doctrine-orm.readthedocs.org/en/latest/tutorials/composite-primary-keys.html)

**Comment by basementjack** [comment]
Yes this would be great to have.

**Comment by mikevrind** [comment]
I would also love to see this being implement within Eloquent.  Why would it be rejected as a proposal?
If the $primaryKey property could be an array of columns it would be awesome.

**Comment by clydiksen** [comment]
+1 for composite primary key support

**Comment by JumpmanJunior** [comment]
+1

**Comment by milroyfraser** [comment]
+1

**Comment by CatoMinor** [comment]
+1 for composite key support in eloquent.

**Comment by caiorobaldo** [comment]
More one L5 user needs composite key => me !!!

**Comment by caiorobaldo** [comment]
Its works!!! 
I ignored the model of the relationship table and set "belongsToMany" in the two tables with a little details: set the two  foreign key of two tables and set the name of the relationship table. The whole foreign keys will works like a composite key.

Ex:
//--------- Model "Table1": ------------//
class Table1 extends Model {
...
public function table2()
    {
        return $this->belongsToMany('App\Table2', 'table_relashionship', 'id_table2', 'id_table1');
    }
}

//--------- Model "Table2": ------------//
class Table2 extends Model {
...
public function table1()
    {
        return $this->belongsToMany('App\Table1', 'table_relashionship', 'id_table1', 'id_table2');
    }
}
--------------
Now the Eloquent undestand that you have a 'table_relashionship' in your database with columns 'id_table1' and 'id_table2' and you can access the data with the comand:
$table1 = Table2::find(1);
dd($table1->table2)

Its solve my problem!

**Comment by ajcastro** [comment]
+1 for composite primary keys. 

In my opinion, using composite primary keys gives more clarity of the code as it shows that it is a dependent model (aggregate) of an entity model. Thus,  the dependent model cannot exists without its parent entity (or the aggregate root).

**Comment by fidgetwidget** [comment]
I am BAFFLED by the decisions being made. This is a COMMON practice in database design, and pushing people to hack their table designs to work with eloquent rather than support such a common practice is insane to me.

**Comment by taylorotwell** [comment]
@fidgetwidget to be fair, it is not supported by Rails either. It is not as if every major framework supports this and Laravel is refusing to.

**Comment by basementjack** [comment]
@taylorotwell I'm in the same camp, I realize it's not a super requested feature, and even less so with new developers. And true, lots of other frameworks haven't done this either.

It's actually a great thing that people are asking - what I hear them saying is they want to use Laravel!

I feel like there are a few options for those of us in need of this functionality:
1) don't use eloquent, use query builder instead.
2) Don't use eloquent, use a different ORM like doctrine
3) Fork Eloquent to a new project and update it to support CK - let those that need it pull from that repo.

Taylor can you share your vision of where Composite Keys fit in Laravel long term?
i.e. Are CK's something you see as desirable, just further down the roadmap?
Or are CK's something you feel are not a good fit for what you're trying to do with Laravel?

- Jack

**Comment by taylorotwell** [comment]
I currently have no plans to implement composite key support.

**Comment by basementjack** [comment]
Thanks Taylor, I appreciate the clarity!

**Comment by rossedman** [comment]
Extend Laravel, make a package, release it and then all the peoples can use it. Just because its not part of the framework doesn't mean this can't be done.

**Comment by Disparity** [comment]
+1

**Comment by atkaye** [comment]
I'm currently working on a package to do this, I'll post a link when I've done.

Extending the `Model` was fairly simple but there are a ton of integration points dealing with relationships. I'm currently extending Eloquent but it's increasingly looking like a fork might be more appropriate.

**Comment by DaveyBoyCrocky** [comment]
Don't understand why this would be so difficult.

**Comment by ClickerMonkey** [comment]
@atkaye A fork might be more appropriate. I've looked through all of the code myself and refactoring it to include composite keys provides an opportunity to clean up the code a bit (all of the joins due to relationships has a lot of repetitive string concatenation code). I think if you write out the few different ways to add conditions & joins to a query in separate methods (on a new class?) it will give you a single place to handle the composite key logic instead of all over the Eloquent code base. Just my 2c

**Comment by atkaye** [comment]
@ClickerMonkey Agree 100%, still a little way to go (I was crazy busy last week) but I've made good progress so far

**Comment by JTallis** [comment]
I would enjoy seeing this myself too but I'm okay using the query builder to get the job done. It means I will have to update the timestamps myself but nothing major.

**Comment by basementjack** [comment]
@JTallis I tried using query builder and I've got it working, but it's a ton more work, since you can't just assign the request data to the ORM to have it save a new record. So lots of mundane code to assign each and every field.

@atkaye How is progress going on the fork?  I've considered trying doctrine, but I think a fork of Eloquent would be easier to use.

**Comment by antonybudianto** [comment]
It's kind confusing that the builder [can create primary composite keys](http://laravel.com/docs/5.1/migrations#writing-migrations) while the Eloquent can't
```php
$table->primary(['first', 'last']);	// Add composite keys.
```

**Comment by lukasgeiter** [comment]
@antonybudianto Not really. I'm pretty sure there are people who use the schema and query builder without Eloquent models.

**Comment by wadtech** [comment]
@lukasgeiter I'd argue that it's actually quite a disconnect between two integral parts of the framework. 
One can build schema in such a way that it can't be used with the existing Eloquent API. It feels like a fight with the tooling, which is a red flag to me.

The fact that these tools can be used independently is great but I think they should work together with feature parity in the first instance.

**Comment by ShirleyCC** [comment]
+1 for composite primary keys.

**Comment by gmanish** [comment]
Me too. +1 for CK.

**Comment by hlogeon** [comment]
+1

**Comment by warrickhill** [comment]
+1

**Comment by adrazich** [comment]
+1

**Comment by jaszczur171** [comment]
+1

**Comment by rapliandras** [comment]
I was just silently listening this thread for a year, still nothing new? I'm playing with the idea of coding an Eloquent extension specifically for supporting comp keys until this feature comes out.

**Comment by CrossProd** [comment]
+1

**Comment by rogierborst** [comment]
+1

**Comment by Riesjart** [comment]
+1

**Comment by bgarrison25** [comment]
+1

**Comment by younes0** [comment]
this should be locked

**Comment by GrahamCampbell** [comment]
lol - I don't lock issues anymore because it causes massive rage

**Comment by nguyenhu** [comment]
+1

**Comment by rcbytes** [comment]
+1

**Comment by bgarrison25** [comment]
Why should this issue be locked?

**Comment by mikevrind** [comment]
Because of what Taylor said about this feature:

> to be fair, it is not supported by Rails either. It is not as if every major framework supports this **and Laravel is refusing to**.

**Comment by bgarrison25** [comment]
So just because other frameworks don't support it means Laravel doesn't need to? In fact I would think this would be a driving force TO support it since it will be yet one more feature it has that other frameworks don't.

**Comment by mikevrind** [comment]
I (and a lot of others) totally agree with you. It's quite a common thing to use in database tables that simply don't require a 'id' field.

**Comment by ClickerMonkey** [comment]
Taylor's response is interesting. It could one of a few things.

1. He doesn't think Laravel can/should be better than Rails.
2. He knows this is an excuse for not wanting to do it himself. Could be lack of time or passion.
3. He protests the idea of composite keys, because some folks actually think you should always have a surrogate key.

I don't mean to pick on him, he's done fantastic work, but with all of the support this issue has gotten I think we need a well thought out reason on why Laravel will never have composite keys OR, even better, 
what can be done to get this done.

After assessing what needs to be done to get composite keys working I can understand why he would want to avoid it. I think it would lead to a very healthy refactoring of the relationship classes.

As I've said before, If he's willing to accept a patch for this feature there are many people who want to work on this. If he's hesitant because he has specific things in mind for this feature - or lines he wouldn't want crossed, he could communicate them to us on this issue.

Outside of my work in PHP, ALL ORMS I've developed or used in the real world supported composite keys (Java might've spoiled me) so I find other libraries being hesitant a little odd.

As I've said before, Laravel to me completely legitimizes developing large and well architected websites in PHP. The company I work for has used it dozens of times for small to large clients. It's definitely one of my favorite frameworks - save this one thing.

Laravel's tagline shouldn't be "At least as good as the competition".

**Comment by crynobone** [comment]
@ClickerMonkey I don't think @taylorotwell would reject if you/anyone can come out with a complete Pull Request to add composite key support for Eloquent. 

You can't expect someone that doesn't use composite key him/herself to create such feature. I myself would never consider making that PR because I don't have all the knowledge to cover all possible use case.

**Comment by jayeley** [comment]
I rarely use surrogate key if it's meaningless, and I use composite keys a lot in applications. I don't see a good reason to force using surrogate key. So please support composite keys in Eloquent.

**Comment by hlogeon** [comment]
May be if we collect enough "+1" I will make the solution

**Comment by codestic** [comment]
Guys this is ridiculous, while I really enjoy working with Eloquent, the idea of adding a completely useless column just to "make it work" is unacceptable. This is such a no-brainer, Doctrine 2 does have native support for composite keys as well.

Why not Laravel?!

+1!

**Comment by stevenap** [comment]
+1

**Comment by MTon** [comment]
+1

**Comment by Payetus** [comment]
I would like composite keys +1

**Comment by j3j5** [comment]
+1 for composite primary keys, there's no good reason to force using surrogate key, is there?

**Comment by gabidavila** [comment]
Composite keys are really useful in use cases where you have an NxN table with a High read and write throughput. 

I guess one could argue in that case you don't use auto_increment, you should use a hash as primary_key and suck it up using an UNIQUE constraint, but in my point of view this "workaround" is not the ideal scenario for a situation like this, it just creates confusion in something that should be simple.

**Comment by samuelfa** [comment]
+1

I put here my own solution:

```php
    /**
     * Set the keys for a save update query.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function setKeysForSaveQuery(Builder $query)
    {
        $keys = $this->getKeyName();
        if(!is_array($keys)){
            return parent::setKeysForSaveQuery($query);
        }

        foreach($keys as $keyName){
            $query->where($keyName, '=', $this->getKeyForSaveQuery($keyName));
        }

        return $query;
    }

    /**
     * Get the primary key value for a save query.
     *
     * @param mixed $keyName
     * @return mixed
     */
    protected function getKeyForSaveQuery($keyName = null)
    {
        if(is_null($keyName)){
            $keyName = $this->getKeyName();
        }

        if (isset($this->original[$keyName])) {
            return $this->original[$keyName];
        }

        return $this->getAttribute($keyName);
    }
```

I'm using a Abstract Model which one final model has extended and in his private property of primaryKey I declared an array with the name of each field on my composite key.

**Comment by Wayfearer** [comment]
This is just sad. +1 for all its worth...
