### ISSUE TITLE
v11.21.0 - v11.33.1 throwing Method Illuminate\Foundation\Application::fireAfterResolvingAttributeCallbacks does not exist.

### ISSUE THREAD

**Issue by joshuaeasy** [laravel/framework#53594]
### Laravel Version

11.20.0

### PHP Version

8.2.4

### Description

v11.21.0 to v11.33.1 (latest as of now) throwing Method Illuminate\Foundation\Application::fireAfterResolvingAttributeCallbacks does not exist.

Whenever a routing action has parameter

e.g 

`Route::any('/test', function () {
    
})->name('test');`

works

`Route::any('/test', function (Request $request) {
    
})->name('test');`

doesn't work

everything is fine on v11.20.0,
this issue only happens on my localhost, working fine on my production server.

### Steps To Reproduce

e.g 

`Route::any('/test', function () {
    
})->name('test');`

works

`Route::any('/test', function (Request $request) {
    
})->name('test');`

doesn't work

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Maybe related to 3rd party package? https://github.com/laravel/framework/issues/52920#issuecomment-2374158988

**Comment by joshuaeasy** [comment]
> Maybe related to 3rd party package? [#52920 (comment)](https://github.com/laravel/framework/issues/52920#issuecomment-2374158988)

That's true, i also use "michael-rubel/laravel-value-objects": "^7.0" in my project, let me remove it and run test again.

**Comment by joshuaeasy** [comment]
> Maybe related to 3rd party package? [#52920 (comment)](https://github.com/laravel/framework/issues/52920#issuecomment-2374158988)

it works.
