### ISSUE TITLE
Enums are not compatible with `Collection::value()`

### ISSUE THREAD

**Issue by CasEbb** [laravel/framework#53676]
### Laravel Version

11.34.0

### PHP Version

8.4.1

### Description

When trying to retrieve a value with `Collection::value()` and the expected value is an enum it is skipped. 

### Steps To Reproduce

```php
<?php

enum MyEnum {
    case MyCase;
}

collect([
    ['id' => 1, 'type' => MyEnum::MyCase],
])->value('type'); // == null

collect([
    ['id' => 1, 'type' => MyEnum::MyCase],
    ['id' => 2, 'type' => 'b'],
])->value('type'); // == "b"

```

**Comment by CasEbb** [comment]
While trying to draft a pull request I ran into the following.

I delved a little deeper into it and it looks like the issue lies in `operatorForWhere`. `value` calls `firstWhere` with only 1 argument (the key, and no value) which ultimately uses `operatorForWhere`, also with 1 argument. When `operatorForWhere` is called with just 1 argument it tries to search for any truthy value.

https://github.com/laravel/framework/blob/e7b12ff811e4955224d292962d2f369627c6a47b/src/Illuminate/Collections/Traits/EnumeratesValues.php#L1082-L1086

The closure that `operatorForWhere` returns checks whether the retrieved value and the comparison value differ in being objects. If it does, a simple truth check occurs whether the requested operation is an inequality.

https://github.com/laravel/framework/blob/e7b12ff811e4955224d292962d2f369627c6a47b/src/Illuminate/Collections/Traits/EnumeratesValues.php#L1101-L1103

Enums are objects, `true` is not, so this check will return false. We could change this check to exclude enums:

```php
if (count($strings) < 2 && count(array_filter([$retrieved, $value], function ($v) {
    return is_object($v) && ! $v instanceof UnitEnum;
})) == 1) {
    return in_array($operator, ['!=', '<>', '!==']);
}
```

However, we run into a strange issue now. `operatorForWhere` now returns the result of `$retrieved == $value`. `$retrieved` is our enum, `$value` is `true`. The result of this comparison is `false`! This might actually be a bug in PHP (see: https://github.com/php/php-src/issues/16954).

Any ideas on how to proceed from here?

**Comment by joelbladt** [comment]
If I have understood correctly, you want to receive all results from the collection as an array and the enums should not be skipped. In your second example, the enum is skipped because the value is null.

https://github.com/laravel/framework/blob/e7b12ff811e4955224d292962d2f369627c6a47b/src/Illuminate/Collections/Traits/EnumeratesValues.php#L317-L335

https://github.com/laravel/framework/blob/e7b12ff811e4955224d292962d2f369627c6a47b/src/Illuminate/Collections/Traits/EnumeratesValues.php#L1096-L1100

This check fails. Simply because method_exists('__toString') cannot be satisfied. In your previous check, you have no values that return the result true. Therefore, the result is also null .

If you want to get all results back as an array, try that:

```php
collect([
    ['id' => 1, 'type' => MyEnum::MyCase],
])->select('type')->toArray();
    
collect([
    ['id' => 1, 'type' => MyEnum::MyCase],
    ['id' => 2, 'type' => 'b'],
])->select('type')->toArray();

/**
 * Result:
 * 
 * array(1) {
 *   [0]=> array(1) {
 *     ["type"]=> enum(App\Enums\MyEnum::MyCase)
 *   }
 * }
 * 
 * array(2) {
 *   [0]=> array(1) {
 *     ["type"]=> enum(App\Enums\MyEnum::MyCase)
 *   }
 *   [1]=> array(1) {
 *     ["type"]=> string(1) "b"
 *   }
 * }
 */
```
