### ISSUE TITLE
\Illuminate\Support\Arr#map() calls closure without keys if there's an ArgumentCountError happening inside the closure

### ISSUE THREAD

**Issue by ropi-bc** [laravel/framework#53865]
### Laravel Version

11.4

### PHP Version

8.3

### Description

[This](https://github.com/ropi-bc/MapCallsClosureWithoutKeys/blob/master/app/Http/Controllers/Controller.php) repo contains a minimal reproducible example project. A brand new laravel project, where the only change is the issue I'm reporting here.

When there's an `ArgumentCountError` happening inside a `collect()->map(fn ($value, $key) => ...)` closure, for example due to making a mistake when calling a `spatie/laravel-data` class's `::from([...])` function, the resulting error message is being masked, because of `Illuminate\Support\Arr.php:606`, where `ArgumentCountError`s are handled by retrying the closure without passing `$keys` to it. This will of course result in another `ArgumentCountError`, because our closure expects both the value AND the key.

### Steps To Reproduce

```
php artisan serve
curl http://localhost:8000
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Sorry, wrong reply template

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
