### ISSUE TITLE
[5.1] Move Mass Assignment Protection Off Of Model

### ISSUE THREAD

**Issue by RyanNielson** [laravel/framework#5635]
I posted this awhile back, and didn't get much of a response so I thought I'd bring it up again. Currently mass assignment protection is done on the model level using $fillable. This is simple, but seems to have some limitations when it comes to providing different rules based on different circumstances like user roles, or request specifics.

This could be done on the controller level, or perhaps somewhere else since it looks like 4.3 is trying to move to less of a strict MVC model. For example, the `FormRequest` class could override `all()` to call a user specified `fillable()` function to filter user input similar to how Rails does it using [Strong Parameters](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters). Basically fillable could return a `FilteredParameters` object to the model that could behave like an array and work similarly to how it does today, but perhaps through some exceptions if a value is missing or data is there that shouldn't be. I just have run into a few pain points when it comes to fillable and have had to hack up my own solutions, so it'd be nice to have a more standard approach. 

I'd love to work on this, so perhaps some of you have an idea of the best way to approach this, if at all.

**Comment by otagi** [comment]
>  I don't think it would hurt Laravel to support both mass assignment and strong parameter approaches.

I think it would, actually. Laravel should choose the best concept and stick with it (and deprecate the old one, if applicable). Otherwise, it will create confusion for newcomers (which one should I choose?) and dilute code consistency in the Laravel ecosystem (example code, support forums, etc.).

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by GrahamCampbell** [comment]
Been no response here for a very long time. Ping @taylorotwell. Do we want this closing?

**Comment by donnykurnia** [comment]
It will be better to move validation into the model first, before moving fillable out of the model. In Laravel 5.1, model still not handling validations, it could accept any values even if it's not valid. If Model handle validations, then it will be safe to move the fillable out of Model because Model can now make sure that the object model is valid before saving it into the database.

**Comment by anismomin** [comment]
is there any way to define 2 set of fillable array for super admin and client in one Modal.

**Comment by Sladewill** [comment]
Do it via Request Validation.

**Comment by bewitchingme** [comment]
Whitelisting and blacklisting parameters should ideally be provided in it's own class; so we "select" the parameters we want to let through prior to the request.  The Rails 4 strong parameterization is an excellent example of this approach, though there's one small feature I would suggest that Rails doesn't provide.  If a parameter in my blacklist appears I would love to be able to configure the parameters to throw an exception or otherwise raise an error so it can be logged/handled.

**Comment by deividaspetraitis** [comment]
ping.
