### ISSUE TITLE
[5.0] Do not automatically generate compiled.php (or get better at regenerating it)

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#6121]
On a recent update to the latest L5 base project and framework, I encountered an issue where `compiled.php` ended up being stale and was basically from a version prior to my update (#6117).

Forgetting that L5 is currently in development, for a couple of reasons, I'd like to suggest that this file not be generated automatically based on a default install of the framework:

 - If any minor release happens and someone is counting on that file to be regenerated automatically, they could end up inadvertently **not** upgrading their actual framework code.  In the rare case of security patches, this could reflect negatively on L5 as many people "stick with defaults" and would never end up with a new `compiled.php`.

 - During development and in cases such as mine, pulling the latest updates doesn't flush out that file, so I end up with a situation similar to #6117. Addressing this will help avoid some accidental non-bugs from coming up.

**Comment by GrahamCampbell** [comment]
Just talked to Taylor about this. He'll think about it. :

**Comment by garygreen** [comment]
It's like having the routes cached automatically when you pull down Laravel. That doesn't happen because it's just weird.
Maybe it would be better to have a new command added for like `php artisan optimize:all` which will generate the compiled optimize file, cache routes, etc. Everything needed to 'optimize' your app. Or just have the optimize command cache routes and all the stuff needed to 'optimize' your app.
