### ISSUE TITLE
[5.0] Allow dot notation in .env to overwrite 

### ISSUE THREAD

**Issue by jimmypuckett** [laravel/framework#6733]
Now that the ENV method is being used to pull SOME_VAR in over file.some.var, we are not able to easily add a new variable to .env. I think that when the variables in the .env should follow the dot notation, and the "env() ?:" stuff removed from the config arrays. Then any config could be dropped in the .env without having to wire it up all over the place.

**Comment by Garbee** [comment]
So, I just ran a test... I'm not sure of the point of this request. It already works if you use dot notation over underscores. Underscores are simply the default provided look. You are free to change it if you wish. And if you are worried about uppercase vs lowercase, just be consistent since env variable naming is case-sensitive.

Is there something I'm missing to this request?

Also, another good tip to keep requests from being closed is to create them in the proper repository. Laravel takes advantage of the [phpdotenv](https://github.com/vlucas/phpdotenv) package to handle the environment configuration. So if you want something changed with how it is handled, issues need to be opened there. Please read the docs on the phpdotenv readme as well for more tips on how to setup nice env handling (like restricting what variables can be and requiring certain ones be given.)

**Comment by GrahamCampbell** [comment]
I agree with @Garbee here.

**Comment by jimmypuckett** [comment]
This has nothing to do with case of variable or even if dotenv supports object oriented looking names. I know that dotenv will support the format--that point was more of a convention request to eep things consistent & make the automagically work. 

It has to do with the fact that the config files are becoming default values unless overwritten by an ENV variable. It is just a matter of time when the remaining variables all get the env() method worked arround them, so instead, I'm proposing that Illuminate's config class (hence why this is a laravel/framework issue) just check to see if the env exist & use it. If not, then use the config files. With the naming convention above, this is a simple matter.

**Comment by Arhimandril** [comment]
@Garbee it seems to me that all of your complaints have already been addressed:

>I see you want  env('APP_DEBUG') for example to be overwritten with  app.debug=true  for example in the .env. This is just wrong. 

No, `env('APP_DEBUG')` would not be overwritten since by default there would be no `env('APP_DEBUG')`. Keys in .env files would simply follow the same convention as `Config::get` and `Config::set` and that's it. Saying that "this is just wrong" is not an argument.

>You can very easily just specify things consistently throughout your code (as you should) and use the env system's helpers to force required ones to be given on each install. No big deal.

Examples of how littering your config files with `env` helpers is uglier, more difficult to manage and more difficult to understand were already provided in [this comment ](https://github.com/laravel/framework/issues/6733#issuecomment-68177698) above.

**Comment by jimmypuckett** [comment]
@Arhimandril, thanks for having the vision in seeing the need & understanding the request before commenting.

**Comment by Garbee** [comment]
Ok, :fireworks: time.

config/filesystem.php

```php
<?php

return [
'default' => env('filesystems.default')
];
```

MAGIC! You will get the same dot notation you want, the config engine will operate just fine. And no extra technical debt in the framework that someone has to maintain over time for no good reason! It is an *AMAZING* solution.... that I stated in my first comment.

As far as the "cleanliness" mentioned. That is all due to what is a misuse of the setup. You shouldn't be setting default void values that won't work. You should simply set them to env('config.path') and then in a service provider make the proper env variables required. 

> Keys in .env files would simply follow the same convention as Config::get and Config::set and that's it. Saying that "this is just wrong" is not an argument.

Funny how you say exactly what is already possible, as explained initially... Yet you are trying to show I am wrong somehow. Also as a side-note, I was pretty brief with my example, I really meant something more like this:

You want app.php:
```php
<?php

return [
    'debug' => env('APP_DEBUG')
];
```

to be overridden by app.debug existing in the .env file. Since it follows the same dot notation as the config, if it exists it should be overridden entirely by the config engine. This is what I gathered from the original post (and as pointed out since is *STILL* entirely the way it is wanted.) Well, this is technical debt for no real good reason. It is confusing behavior unless you are one of the few people who would understand it and then even take advantage of it.

Narrow use-case code, extra logic in core creating debt to maintain, already available end-goal... Not a good request to be implemented. The benefits just aren't there to outweigh the negatives of addition.

**Comment by Arhimandril** [comment]
@Garbee that seems to me like the opposite of "magic". We're just manually repeating ourselves all over the place. Users of your app still have to edit both the config files and the .env files, and then they have to manage differences between the remote and the local versions, which may become quite a problem depending on how technical those users are.

As far as technical debt is concerned, we're talking about adding a simplest conditional statement to `Config::get`. With that conditional we would introduce the possibility of replacing all logic in `Config::set` with a simple assignment operation, thus actually reducing technical debt.

Of course, I'm not at all confident that this is the best approach, or even that it is a good approach. That's why we're discussing it, I guess.
