### ISSUE TITLE
[L5] Package config

### ISSUE THREAD

**Issue by barryvdh** [laravel/framework#6895]
In L4, package were easy to configure because of `php artisan config:publish` and the cascading user config. I want to open this issue to discuss the new best ways and pros/cons of the new way.

I assume that Taylor wants the following:

 - Load the configuration in the package SP register()
 - Users copy the things they need to App/Providers/ConfigServiceProvider
 - The package config is overridden by the register() from the ConfigServiceProvider

At first sight, that has a few disadvantages:
 - Not clear what the config is directly. First it could be published so it was in sync with the used version. Now one has to find the file on github and copy it?
 - Config files were nicely seperated in files/namespaces, would these all need to go in 1 file, or let the users create their own logic of loading config files from a seperate dir?
 - You cannot use the config in the register function, because then it isn't overridden yet.
 - Package developers need to implement their own loading of files again (not a big deal, but probably everybody has to do this again so why not in the base service provider?) (`$app['config']->set('my-package', require __DIR__.'/config.php';);`)

Or I might be missing something. But I'd rather discuss here then on Twitter with 140 chars ;)

**Comment by franzliedke** [comment]
:+1:

There are some things that aren't all that clear with the new config system yet. For example, what about having multiple databases in production and only one in development? How would you do that with environment variables?

**Comment by GrahamCampbell** [comment]
Yeh, I do agree here. It's funny how you don't appreciate something properly until it gets taken away. I really like laravel 4's config system. I'm not fussed over the view/lang changes, but the config will be greatly missed by me.

**Comment by atrauzzi** [comment]
The old config system was definitely convenient and I made good use of it.  During the weekend however, I managed to get some clarification from @taylorotwell.  I summarized it all as a blog post (better than a back and forth of disjointed 140 character tweets).  This might serve as a good basis to help people who are confused by the changes get accustomed to what's intended: 

http://atrauzzi.blogspot.ca/2015/01/changes-to-packages-and-configs-in.html

In terms of merits, I'd wager the new approach might end up encouraging us to write better packages.  We might see people start talking about how their service providers are getting really big (solution: make more?) because of all the different things going on in them.

I'd say at the very least, the docs should be sure to contain a very clear direction and explanation of what `register` and `boot` are, as well as their features.

**Comment by barryvdh** [comment]
@GrahamCampbell this was not meant as a 'documentation' issue, but more as a discussion about the Config system.

@atrauzzi I understand that it's easier to develop, just not sure for some packages that rely more in config. Some package just change some defaults, but packages like Rocketeer (https://github.com/rocketeers/rocketeer/blob/master/src/config/config.php) rely much more on config, so imho it's often easier to publish the config and change the values that are available..

**Comment by Anahkiasen** [comment]
Plus you kind of lose all the comments explaining the config, with the new system.

**Comment by kirkbushell** [comment]
@taylorotwell mentioned today on that thread on twitter that he wasn't a fan of the configuration files, saying that keeping them organised was difficult and loading of them was very slow. So now, you have to manage it yourself in service providers:

```php
$this->app['config']->set(['package-namespace' => $myConfigArray]);
```

Users can then overload that in their own service providers if needs be, for individual options they want to change. I believe this is also tied in with the fact that configuration can now be cached, whereas I'm not sure it was previously.

**Comment by taylorotwell** [comment]
@franzliedke tell me more about your multiple databases in production but one in development... im not sure how this is impossible with current environment setup?

**Comment by slovenianGooner** [comment]
I see no issue with the change, if it's heavily documented. We, as the developers, should be able to understand these changes without any problems if the documentation is great, which I have no doubt it will be.

The performance issue alone has convinced me this is a better idea, although I might have to do some changes to my packages in the coming weeks. But mostly it's just few fixes in the ServiceProviders and a different override of config vars.

**Comment by franzliedke** [comment]
@taylorotwell I think I was referring to [read/write connections](http://laravel.com/docs/4.2/database#read-write-connections) (where you use that in production, but not in development)...

**Comment by crynobone** [comment]
Few thing that I see doesn't work with having `config` files (sure some of this can be solved via Service Providers):

* Setting up service providers based on environment. `local` include generator, clockwork, debugbar etc while this is ignore for production (as you would normally have these packages under `require-dev`).
* You can't use `Closure` (if you have a use case for it) and at the same time use cached config file. `var_export` can't serialize closure.
* As @franzliedke mention, of course you could just set the same host for both read and write on local, but that also mean on every request that use database connection, you creating two separate connection instead of one (this is from what I understand from the code, but could be wrong).
* As @barryvdh mention "You cannot use the config in the register function, because then it isn't overridden yet." If for example `App\Providers\ConfigServiceProvider` is called before say `Packages\FooServiceProvider`, the supposedly overwritten configuration for that packages is loaded early. Which means more documentation need to be added to explain this condition/scenario.
* Some people (including myself) use environment config to allow development team to swap database configuration from "local" (personal playground) to "development" database (shared between developers) for testing. Having to just swap `APP_ENV` and have the configuration ready is still a plus for development.

**Comment by kirkbushell** [comment]
@crynobone your point about environment-based config is a good one. 

@taylorotwell are we now advised to have conditionals checking environment for specific configuration?

**Comment by taylorotwell** [comment]
I'll address @crynobone's situations and @franzliedke's one by one:

**Local only service providers:**
 
```
if ($this->app->environment('local') { 
     $this->app->register('LocalOnlyServiceProvider');
}
```

**Closures In Config**

This has always been a bad idea as it made configuration not able to stored in another loader such as database. That's why the core removed Closures from configuration back in Laravel 3.

**Read/Write Database For Prod, Not For Local**

Define two database connections in config/database, one for read/write and one for "local", set a DB_CONNECTION environment variable and use that as your `default` connection option.

**Config In Register**

You should never need to do this. The register method is only for registering things in the container or registering configuration. If you feel like you need this you probably just need a better architected service provider.

**Comment by atrauzzi** [comment]
@taylorotwell - Thanks for the info.

Just slightly confused by your last paragraph as the heading is "Config in Register", but then you go on to say "*...or registering configuration*".

Any chance you could expand on that slightly?

**Comment by mvalim** [comment]
I'm currently working on some helpers for package development in Laravel 5 (publishing configuration and publishing migrations, for now). At first it was for personal use only but maybe it can help other people. You can check if it fit your needs at: https://github.com/mvalim/package-utils

**Comment by GrahamCampbell** [comment]
Also see https://github.com/orchestral/config.

**Comment by barryvdh** [comment]
What about simple recursive loading of files in subdirectories:

config
 /app.php  -> `app`
 /package1.php -> `package1`
 /package2/defaults.php -> `package2.defaults`

This could be either in the ConfigServiceProvider, or a method in the Support ServiceProvider:

	protected function loadConfigFrom($key, $path, $isDir)
	{
        $appPath = $this->app->basePath().'/config/'.$key;
        if ($isDir) {
            $this->app['config']->loadDir($key, $path);
            if (is_dir($appPath)) {
                $this->app['config']->loadDir($key, $appPath);
            }
        } else {
            $this->app['config']->set($key, require $path);
            if (is_file($appPath)) {
                $this->app['config']->set($key, require $appPath);
            }
        }
	}

That way people could just copy the files together in a subdirectory to keep it more clean. Without having all that logic about environments, lazy loading/merging etc.

**Comment by GrahamCampbell** [comment]
I don't think Taylor has any plans to change this. If you like the old config system, use https://github.com/orchestral/config. All my laravel packages are using that package now.

**Comment by barryvdh** [comment]
I don't have plans to use that, I was just hoping to provide some easy functionality while keeping it simple.

I read yesterday on Twitter that Taylor was still playing with some ideas: https://twitter.com/RyanTablada/status/556597608949772290
(cc @rtablada )

So perhaps we can keep this open untill Taylor says it's final?

**Comment by barryvdh** [comment]
And btw, this doesn't actually change that much, it would mostly consist of 1 method on the config, to load a directory. Doesn't even have to be default, but people could just load a single directory at once with a given key..
