### ISSUE TITLE
Query builder with with select inside a select statement ?

### ISSUE THREAD

**Issue by sangle137** [laravel/framework#7039]
i have to build a query like " SELECT * FROM (SELECT a,b,c,d JOIN ... WHERE ... FROM abc) WHERE ... " with query builder(QB), the select statemet inside the bracket, it's ok with laravel QB, but i can not find any way to use QB to build the above query string with two select statement. My way is build the string inside bracket by query builder and assigned it to $query, after that i have to create a new string $raw = " SELECT * FROM ($query->toSql()) WHERE ...", that i need is use query builder instead of create $raw as a string and use DB::select($raw) to get the result. Anyone has an good idea?

**Comment by devonzara** [comment]
I'm not entirely sure what you're asking, something about doing a sub-select. Please take the time to type a clear and nicely formatted question, as it'll make the job of help you much easier.

Either way, I believe this is more of a 'how-to' question rather than a framework issue, so I'm not going to go into detail. 

However, do note that there are several ways to accomplish a subselect; depending upon your specific needs. You can use the query builder or raw queries as demonstrated [ [here](http://fideloper.com/laravel-raw-queries) ]. It looks like you're trying to do a subselect for setting `from` in which case [ [this topic](http://stackoverflow.com/questions/24823915/how-to-select-from-subquery-using-laravel-query-builder) ] may be helpful.

If you need more help, you'll probably get a better response if you post on a site such as laravel.io or Stack Overflow.

**Comment by GrahamCampbell** [comment]
This looks like a question for the forums. :)
