### ISSUE TITLE
artisan migrate --pretend does not output SQL statements

### ISSUE THREAD

**Issue by stevenmyhre** [laravel/framework#7085]
Full command:

`php artisan migrate --pretend -vvv`

Outputs nothing.

I believe this is because the method `$db->enableQueryLog()` is never called anywhere (actually not anywhere in the framework itself either)

**Comment by pavankumarkatakam** [comment]
Ofcourse in laravel 4.2 $db->enableQueryLog() is not called but it will give output because the protected boolean variable is set to "true". but in laravel 5.0 this property set to false. i have already given a pull request to master branch about [see this](https://github.com/laravel/framework/pull/7471).

**Comment by briedis** [comment]
I vote for this! This is really annoying, specially for rollback, when it's important to know what will be rolled back :(

**Comment by MaartenStaa** [comment]
@pavankumarkatakam's pull request #7477 was merged, isn't it fixed on the latest version?

**Comment by briedis** [comment]
Just updated and yeah, it's fixed! :+1:
