### ISSUE TITLE
Filters in controllers construct

### ISSUE THREAD

**Issue by 2byte** [laravel/framework#7219]
Set callback function to filter.
```php
function __construct()
{
    $this->beforeFilter(function () {
    });
}
```
Does not work when the call App::make('Controller')->getIndex();
`Call to a member function filter() on a non-object`

**Comment by crynobone** [comment]
You're are never suppose to call it that way.

**Comment by 2byte** [comment]
I need to call so

**Comment by GrahamCampbell** [comment]
> I need to call so

That's unlikely. There are other ways of making internal requests. Maybe ask on the forums.

**Comment by deefour** [comment]
@GrahamCampbell The underlying problem is that things blow up when resolving a controller with filters set in the constructor through the service container.

`\Illuminate\Routing\Controller` only seems to have the static `$router` property *(expecting an instance of `\Illuminate\Routing\Router`)* set when being called through the controller dispatcher.

Sure, @2byte is calling a controller action incorrectly. Artisan's `route:list` command [is guilty of instantiating controller instances through the service container too though](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/RouteListCommand.php#L158).

Calling `php artisan route:list` blows up with the same error reported here when the constructor has filters defined.

**Comment by crynobone** [comment]
> Sure, @2byte is calling a controller action incorrectly. Artisan's route:list command is guilty of instantiating controller instances through the service container too though.

`route:list` doesn't need to execute a routing method, it only used it to fetch `getMiddleware()`, does using this execute any filters? No, which is the expected behaviour.

**Comment by crynobone** [comment]
> Calling `php artisan route:list` blows up with the same error reported here when the constructor has filters defined.

That probably a bug which should be fixed, the PR was only recently added (1 or 2 days maybe?)

**Comment by 2byte** [comment]
usage
```
Route::get('/',  function () {
    if (Spad\Components\Auth::isAuth()) {
        return App::make('Spad\Controllers\User\UserController')->getIndex();
    } else {
        return App::make('Spad\Controllers\HomeController')->getIndex();
    }
});
```
