### ISSUE TITLE
route:cache with duplicate routes throws wrong exception

### ISSUE THREAD

**Issue by minorgod** [laravel/framework#7452]
I stumbled upon this weird behavior when testing route caching. If I have a routes file containing only the following routes:

Route::get('home', 'WelcomeController@index');
Route::get('home', 'HomeController@index');

Running artisan route:cache throws exception:
exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in ..\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteCacheCommand.php:95

After carefully inspecting the RouteCollection passed to the buildRouteCacheFile() function in the RouteCacheCommand.php, I see no indication that there are any closures in the collection. 

I realize it's silly to define the 'home' route twice pointing to different controllers, but it seems like the wrong exception is being thrown in the above case.

**Comment by jobrios** [comment]
`RouteCollection` maintains 4 arrays of routes: `$routes`, `$allRoutes`, `$nameList`, and `$actionList`. After routes #1 and #2 are created for the 'home' path, route #2 overwrites route #1 in `$routes` and `$allRoutes`. But `$allRoutes`, which indexes `Route` instances by the controller-method "action" string, still holds route #1 (`$nameList` remains empty since you don't have named routes in this case). This is because `$allRoutes` is the only array for which the two routes have different indices ('App\Http\Controllers\WelcomeController@index' !=  'App\Http\Controllers\HomeController@index').
In [`RouteCacheCommand::fire`](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/RouteCacheCommand.php#L48), the foreach loop iterates over the routes in `$allRoutes`, so it misses preparing route #1 for serialization. If, after the loop, you run
```
$routes->getByAction('App\Http\Controllers\WelcomeController@index')->prepareForSerialization();
```
you won't get the exception.

The line `unset($container)` in [`Route::prepareForSerialization`](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Routing/Route.php#L944) stops the attempt at serializing the application which is responsible for the exception.

**Comment by jobrios** [comment]
Also, just saw that PR #7432 addresses this issue.
