### ISSUE TITLE
[5.0] Custom paginator in Query Builder

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#7510]
At the moment when using e.g. `User::paginate(20)` it will always return an instance of `LengthAwarePaginator`. This is due to the following https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Builder.php#L255

The builder is creating a concrete implementation to that specific paginator. It would be good if you could dependency inject a paginator contract to override it somehow. I think in 4.2 it was possible to override the paginator that was returned.

**Comment by mayoz** [comment]
:+1: @taylorotwell how can override it, Builder unchanged? Maybe, register which will be used paginator manager in PaginationServiceProvider? So that, we use custom paginator service. I need it for custom seo friendly paginate url. [Registrar](https://github.com/laravel/laravel/blob/6249969271a6d8adea5df8efdd41de93c2bd15d6/app/Providers/AppServiceProvider.php#L28) is a great example of this.

**Comment by garygreen** [comment]
Closed without reason, again?

**Comment by GrahamCampbell** [comment]
Closed because there was no interest, and "issues" aren't really for proposals.

**Comment by GrahamCampbell** [comment]
Our current issue policy is that issues are exclusively for the community to report issues and fix them.

**Comment by GrahamCampbell** [comment]
If you'd like something implemented, please send a PR.

**Comment by GrahamCampbell** [comment]
If you want to know if it's likely to be accepted, you need to contact Taylor directly.

**Comment by garygreen** [comment]
I think that's the most frustrating thing with Laravel contributions at the moment -- you can spend a long time doing a PR, with tests etc and then just have Taylor reject it. (It's happened to me a few times and there's nothing more frustrating).

There needs to be a better process for 1. proposing new functionality / changes, 2. accepting that something needs to be changed / draft ideas, 3. submit a pr with all the bells and whistles with tests etc for review.

I suspect this puts a lot of other people off contributing to Laravel as well, as I've seen a number of issues being closed with a PR requested merely to review an idea. Doing a PR is a considerable amount of more time to invest, especially when it would be for a futile effort. Even a simple Yes / No from Taylor on proposals would be a massive help.

**Comment by GrahamCampbell** [comment]
> Even a simple Yes / No from Taylor on proposals would be a massive step forward.

You need to contact him on slack then. He doesn't read the issues anymore.

**Comment by taylorotwell** [comment]
I don't remember if it was possible in 4.2. However, as noted in the contribution guide (http://laravel.com/docs/5.1/contributions#core-development-discussion) ... the best place for these kinds of discussions right now is the #internals chat on Slack. Otherwise, these types of issues are not very "actionable" for us, since it's more of a general comment that it's not overridable, and not necessarily a "bug" per se.

However, for this particular case, I will say that I am not opposed to making this more configurable if someone would like to PR it.
