### ISSUE TITLE
[Proposal] SqlServer2012 grammar file

### ISSUE THREAD

**Issue by crissi** [laravel/framework#7568]
That implements limit and offset with sql server 2012's: **OFFSET** AND **FETCH** instead of **row_number() over**

**Comment by GrahamCampbell** [comment]
Any thoughts?

**Comment by twaileit** [comment]
Well, that "should" be pretty easy.

In SqlServerGrammar.php:
```php
    protected function compileOffset(Builder $query, $offset)
    {
        return '"OFFSET {$offset} ROWS";
    }

    protected function compileLimit(Builder $query, $limit)
    {
        return "FETCH {$limit} ROWS ONLY";
    }
```

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by yansern** [comment]
I attempted to implement OFFSET...FETCH but it only take effect when `->orderBy` is used. Otherwise it will fallback to `ROW_NUMBER()`.

Gist: https://gist.github.com/yansern/4d7017351314eb37fa0df284ccd51c40

This is for the file: `src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php`.

Perhaps this can be a starting point for others to follow.
