### ISSUE TITLE
Difference between Foundation\helpers.php and Support\helpers.php ?

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#7571]
I think it's quite confusing having these seperate, as the foundation helpers suggests it's all functions that Laravel uses internally, and support\helpers.php 'extra' ones that core doesn't use -- which isn't the case as `array_*` functions are used extensively in core and are in `Support\helpers.php`

Any reason why they're separate? :confused:

**Comment by JosephSilber** [comment]
The support helpers are standalone helpers that do not rely on the framework. You can composer require `illuminate/support` in your non-laravel project and use all those helpful helpers.

The foundation helpers are those that rely on the framework, and only make sense when you are actually using the full laravel framework. We don't want these helpers in the support package, since we don't want the support package to have all those dependencies.

**Comment by garygreen** [comment]
ok thanks
