### ISSUE TITLE
handler:event Command adding invalid use command if not event is in command

### ISSUE THREAD

**Issue by jahumes** [laravel/framework#7649]
When I run the artisan command ````php artisan handler:event UserEventHandler```` in Laravel 5.0.13 the resulting generated file has a syntax error in the use statements. It generates:

````php
<?php namespace RevampCredit\Handlers\Events;

use RevampCredit\Events\;

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldBeQueued;

class UserEventHandler {
	...
}
````

I can see why it would be necessary to make someone have to have an event, but it makes sense that either the event should be required as an argument or the use statement shouldn't be included.

**Comment by GrahamCampbell** [comment]
We're open to pulls if you want something changing. Please don't create issues for this.

**Comment by RomainLanz** [comment]
Why not create an issue? This is a bug on Laravel, issue exists to report them no?

**Comment by GrahamCampbell** [comment]
> Why not create an issue? This is a bug on Laravel, issue exists to report them no?

This is not a bug. This is a request for a change. It's a waste of time creating an issue first. If you want something changing, send a pull.

**Comment by RomainLanz** [comment]
Sorry, but this is a bug.

Firing this command `php artisan handler:event UserEventHandler` should generate a file.

`$ php artisan handler:event UserEventHandler
Handler created successfully.`

The file is correctly created, but it has a syntax error on it because we don't set the `--event` option.
We can see on the code that it should be required.
````php
array('event', null, InputOption::VALUE_REQUIRED, 'The event class the handler handles.'),
````

But it's not.
