### ISSUE TITLE
artisan queue:listen + app in maintenance mode does not sleep

### ISSUE THREAD

**Issue by jonsa** [laravel/framework#7673]
If a queue listener is running ```php artisan queue:listen``` and the app is in maintenance mode ```php artisan down``` the queue process goes rampage. This is due to the fact that ```queue:work```-command terminates immediately if it detects maintenance mode and doesn't utilize the provided sleep option.

**Comment by GrahamCampbell** [comment]
Thank you for reporting. We're open to pull requests if you have any time. :)

**Comment by vinicarlos56** [comment]
What is the expected behaviour? As @jonsa mentioned, using the option sleep apparently solves the problem.

Changing [this](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Queue/Console/WorkCommand.php#L52):
```php
if ($this->downForMaintenance() && ! $this->option('daemon')) return;
```
For this:
```php
if ($this->downForMaintenance() && ! $this->option('daemon')) {
    $this->worker->sleep($this->option('sleep'));
    return;
}
```
But I'm not sure because looks like the command is still running. I tried to use $this->worker->stop() (stop the listener when in maintenance mode shouldn't be the expected?) but the listener still goes rampage.

**Comment by GrahamCampbell** [comment]
@vinicarlos56 Could you send a PR please so Taylor can review it.
