### ISSUE TITLE
Wrong optional route param parsing

### ISSUE THREAD

**Issue by shemusok** [laravel/framework#7835]
routes.php:
```php	
Route::get('/test/{one?}/{two?}/{three?}', function($one = null, $two = null, $three = null) {
  dd([
    'one' => $a,
    'two' => $n,
    'three' => $id
  ]);
})
->where('one', '.*')
->where('two', '.*')
->where('three', '\d+');
```

*GET http://localhost/test/hoho//1*
expected reply:
``` 
array:3 [
  "one" => "hoho"
  "two" => null
  "three" => "1"
]
```
actual reply:
```
array:3 [
  "one" => "hoho"
  "two" => "1"
  "three" => null
]
```
**But**
If I put
```
dd($this->parametersWithoutNulls());
```
in  **vendor/laravel/framework/src/Illuminate/Routing/Route.php:runCallable** method
I got
```
array:2 [
  "one" => "hoho"
  "three" => "1"
]
```
what is very close to what I'm expecting to get.

**Comment by TheShiftExchange** [comment]
This isnt a bug. The issue is you are supplying invalid URI. You should not be using double forward slashes to dictate and empty variable. You should use an entirely different route for that.

As discussed on SO here: http://stackoverflow.com/q/10161177/1317935 - HTTP RFC 2396 defines path separator to be single slash.
