### ISSUE TITLE
any, pattern helpers

### ISSUE THREAD

**Issue by sukonovs** [laravel/framework#7861]
Hello!

Is there a reason why any() and, pattern() helpers are not added? I migrated laravel 4 to 5th version. And route files have Route::any(), Route::pattern() and get(), post(). One convention would be nice.

**Comment by GrahamCampbell** [comment]
We don't want to fill the framework with 100s of global helpers.

**Comment by sukonovs** [comment]
```php
Route::pattern('faqscategories', '[0-9]+');
Route::pattern('faqs', '[0-9]+');
resource('faqscategories', 'FaqsCategoriesController');
resource('faqscategories.faqs', FaqsController');
```

This is one of my route files, looks not so good right? I completely understand that there is no need for helper function for all mehtods. But consistency I think matters too. If you make several helpers for route, it makes sense to add for all public methods. 

It makes framework more intuitive. If I know there are helpers for route I can be sure there is helper for any and pattern and I dont need to check documentation.

You as core developer know all internals of framework, but others that use it dont.

**Comment by conorsmith** [comment]
You can make your routes file look better by using the `Route` facade for all your route declarations, instead of just the ones that don't have a helper function. This may not be the solution you want, but I think it's an acceptable one for the purposes of style.

Regarding the consistency of the available routing helper functions, I totally see your point. A developer could be confused if they've been writing routes with `get()` and `post()` helpers and then they attempt to use a less common routing method that doesn't have a corresponding helper function.

However, the developers using these helper functions are likely to have found out about them from reading [the documentation](http://laravel.com/docs/5.0/helpers), which lists the available routing helpers. (Actually, it's missing the `resource()` helper at the moment, that should probably be there too.) I believe that it isn't a big ask to expect developers to read and check up on the documentation for their application's framework.

So you have to weigh the gain in intuitiveness against the impact of additional global helper functions, which is not small.

Currently there are 6 helper functions for routing: one for each HTTP verb and one for the `resource` method. These, I assume, are the most common routing methods used. There are likely a great number of Laravel applications that only use these methods for routing, which means they wouldn't have any issue with inconsistent style in their routes file.
