### ISSUE TITLE
Incorrect translation result

### ISSUE THREAD

**Issue by arammkr** [laravel/framework#7997]
I got some problem with translation, my trans key is 'user.notification.email_confirmation_code.text' which equal to ":email_confirmation_code".

My code is
```php
trans('user.notification.email_confirmation_code.text', [
    "email" => "armo.mkrtchyan@gmail.com",
    "email_confirmation_code" => "110753"
]); 
```
trans function result is "armo.mkrtchyan@gmail.com_confirmation_code" instead of "110753", is this bug?

**Comment by taiyaei** [comment]
You seem to have an error in your code.

[email] => armo.mkrtchyan@gmail.com
[email_confirmation_code] => 110753

Shouldn't have the left and right brackets there for the indexes, because in that way you're declaring the index of the values as an array.

Does that fix your problem?

**Comment by overtrue** [comment]
```php
trans('user.notification.email_confirmation_code.text', 
    [
        'email' => 'armo.mkrtchyan@gmail.com'
        'email_confirmation_code' => 110753,
   ]
]); 
```

**Comment by arammkr** [comment]
sorry it's result of copy pasting , I have updated my code example, it's not parsing error !

**Comment by taiyaei** [comment]
Ah, I see what's happening, it's converting ":email" to your "email" index ("armo.mkrtchyan@gmail.com") and then keeping the "_confirmation_code" part.  It seems to be using your "email" index because it appears first and is seen by the parser before "email_confirmation_code".

This is most likely a bug, or maybe an unintended side-effect that has been left.

I'd leave this open for someone else to review, but I'd say it's not necessarily a bug but rather an unintended consequence of how it parses translation strings.  In the meantime, changing "email_confirmation_code" to just "code" or anything else without "email" in the beginning will resolve this.

**Comment by taiyaei** [comment]
Actually, maybe try this:

    trans('user.notification.email_confirmation_code.text', 
      [
          'email_confirmation_code' => 110753,
          'email' => 'armo.mkrtchyan@gmail.com'
      ]
    ]);

I can't test it myself at the moment but I'm curious if it works then?
