### ISSUE TITLE
DocBlock return typo on \Illuminate\Database\Connection::getSchemaGrammar

### ISSUE THREAD

**Issue by tormit** [laravel/framework#8029]
@return should be \Illuminate\Database\Schema\Grammars\Grammar

Fixed this in my fork.

**Comment by taiyaei** [comment]
PR it instead of an issue?

**Comment by tormit** [comment]
I already have pending pull request https://github.com/laravel/framework/pull/7963 . Can't make separate one for this issue.

**Comment by taiyaei** [comment]
@tormit Ah, I see.  Just a protip, branch your fork into something like "patch-pagination" for your PR so this doesn't happen, because then you could make another for "patch-docblock-typo" or something along the lines.

Since it seems you committed this change in your PR #7963, I guess you can close this?

**Comment by tormit** [comment]
Yes. But they should accept my fix about pagination too.
