### ISSUE TITLE
'tmp' folder for temporary files

### ISSUE THREAD

**Issue by barryvdh** [laravel/framework#8123]
In regard with all the commotion/problems by moving some files to the `vendor` dir, perhaps it would be smart to start a constructive discussion about what the old problem is, what the problem with the new method is and how to fix it?

The old problem was (I guess) that the `storage` folder is meant to store files that are available throughout releases, like logs, generated pdfs, cache, compiled views etc. And some files aren't meant to be shared across releases so don't really belong there?

The solution was to move the files to the `vendor` dir, so they aren't saved through releases.
Pros:
 - They aren't shared between releases
Cons:
 - Problems with permissions (some people don't make vendor writable)
 - Different vendor dir (is configurable)
 - It doesn't 'feel' right? (vendor folder = managed by composer, not Laravel)

Other solutions?
 - A different 'tmp' folder for temporary stuff, like the compiled file or cached routes etc.
 - A 'release' command to cleanup before/after a release?
 - Something else?

(And this is not for trolling/complaining, just that there might be a solution that fits all.. And serious discussion, not +1 or angry comments please)

**Comment by overtrue** [comment]
+1

**Comment by Anahkiasen** [comment]
> +1

=>

@barryvdh :

> So let's be constructive instead of complaining. I created an issue, serious feedback only please (not +1 or angry comments). #8123

**Comment by arcadas** [comment]
+1

**Comment by barryvdh** [comment]
As stated in the other issue, this is fixed in https://github.com/laravel/framework/commit/49e91aeabba71e16e88b175e1e0b62a6e8d506c9

So to avoid more breaking perhaps it's best to consider this for the 5.1 release.

**Comment by szekeresa** [comment]
+1

**Comment by winglian** [comment]
Seems like it would have made more sense to have this configurable rather than now having conditional logic based on a directory's permissions.

**Comment by driesvints** [comment]
I'd also argue for a dedicated tmp folder storage. Perhaps use the server one as default and use the dedicated one as fallback?

It's something I almost always create myself on a Laravel project that uses file handling (create zip files, generate documents etc for downloads). I always create a `tmp/` dir in the storage folder.

I also feel that the vendor directory isn't the right location for this. Like you said, the cons (people apply different behavior to it) outweigh the benefits.

**Comment by javiereguiluz** [comment]
Just in case it's useful for the discussion, I'd like to say that in the Symfony community we had a similar discussion. Ultimately we decided to create a `var/` folder to store the things that you propose to store in the `tmp/` directory.

The `var/` name was chosen because it's the common practice used in servers and system administration. Symfony 2 applications can already use this `var/` folder and it will be the default practice in the Symfony 3 version released at the end of this year.

**Comment by dcarrith** [comment]
I agree with the community that vendor is not the proper place for framework generated files.  It wasn't a breaking change for the project I've been working on in particular, but that's because (to my surprise) vendor is writable (along with every other directory of my Laravel site - `#justaskingtobehacked`).  But, I agree with what many have said... vendor should not be writable by the web server.  The only reason it is writable in my case is because I haven't gotten to the point where I want to secure everything (anything) yet.  But, it's "just" my own home server.  Leaving potential vulnerabilities like web server writable directories open in an enterprise environment is a different story.  Having requirements that certain directories must be writable could exclude Laravel from consideration (to the detriment of us developers who love working with Laravel) when an enterprise development team is evaluating framework options.  I have certainly been preaching "Laravel is an awesome framework" to everyone I know and meet here at ____, but I have yet to use it for a client project (though, I do look forward to that day).  Anyway, sorry for rambling on...

@barryvdh proposed some good options.  I also like @driesvints' and @javiereguiluz' suggestions.  I think it would make a lot of sense for Laravel to follow Symfony's lead on this one.

**Comment by antonioribeiro** [comment]
Most operating systems maintain their own temporary folder (/tmp on Linux, %TEMP% on Windows) and imo some of those framework generated files could be stored there: compiled views, sessions, cache... Why? Because on systems like Linux (and BSD) based, this temporary folder is erased on boot, [and even on Windows this is easily doable](http://www.groovypost.com/howto/create-batch-file-auto-clean-windows-temp-folder/), so you get a free and automatic sweep, and, if your server crashes during the creation of one of those files, you won't risk seeing your application behave oddly, because it will be starting from scratch, having to re-create all those files.

To avoid conflict between different apps, we could name the folder after our own application's, so the path

```
/home/forge/laravel.com/storage/temp
```

Could be in temp

```
/tmp/laravel.tmp/home/forge/laravel.com/storage/temp
```

Cheers!

**Comment by crynobone** [comment]
I would think that `routes.php`, `services.json` and `compiled.php` belongs under bootstrap folder, maybe new `bootstrap/framework` thus allow it to be better maintain (and at the same time reduce current number of folders). This also would work well with zero deployment downtime structure as we can still share `storage` folder between build and prepared all the compiled file before swapping the build folder.

**Comment by crynobone** [comment]
> Most operating systems maintain their own temporary folder (/tmp on Linux, %TEMP% on Windows) and imo some of those framework generated files could be stored there: compiled views, sessions, cache... 

I think the idea now is to have a none shared folder, which would be the logical use case why @taylorotwell opt to move the compiled files to `vendor` instead of `storage`.

**Comment by phanan** [comment]
Uhm... System's tmp dir is acessible by any process, so unless I have a dedicated server, I wouldn't store my files there. The fact that the tmp dir is erased with every reboot might harm more than help in this case, too -- if I store my session files somewhere else, my users can just continue working after the reboot without having to log in again. Here is [a good read](http://stackoverflow.com/questions/6671781/are-php-sessions-stored-in-tmp-on-shared-hosting-safe).

**Comment by dcarrith** [comment]
@phanan makes a great argument against using system tmp.

**Comment by antonioribeiro** [comment]
Yeah, you got a point there @phanan...

But I'm not confortable with vendor for some reasons. Every time you create a file in a root folder, and app/vendor is sort of a root folder, you have to think about it conflicting with any other else. I don't like the idea of those files being written in vendor, even more if we make them easily conflictable, and, sir, **services.json** is probably a very common file name.

The vendor folder should never be writable by the webserver, nor should be used as a temporay files holder, maybe except for Composer, which not only stores packages on it, but also has to use it to build and store the autoloading classmap files. Other than that vendor should be related only to third party packages and be read-only. 

People will more and more `chmod 777 vendor`, [opening more doors than we already have in our systems](http://stackoverflow.com/questions/11271596/how-will-a-server-become-vulnerable-with-chmod-777). That's their problem some will say, but I don't agree, I think the framework should try to protect users, so "security guidelines" is something every framework should have in their docs, in their install sections:

* After installing Laravel, which folders should and should not be made writable by the webserver?
* Wich files and folders should I not add to my git repository?
* Why?

Every time someone sees a `failed to open stream: Permission denied`, you can expect it to `chmod 777` the hell of it. Look at the original thread, there's at least one doing that for a living. And I've seen people doing `sudo chmod 777 /` to fix things like these.

If you make it easier for people that are not aware of simple things, your framework may be started to be seen as an unsecure one, do you want that?

Okay but if vendor is not writable the framework will use a different folder to store those files, right? Maybe, but not cool, that's pretty confusing:

```
- I can't figure this thing out, mate, could you help me?
- Take a look at your services.json.
- Where is it? 
- In your vendor folder.
- No it's not. :(
- Wait, your vendor is writable by the webserver? 
- Of course it's not, I do things right, mate! :P
- Yeah, sorry, please take a look in storage, it must be there then. :(
```

I also don't agree that `registerConfiguredProviders` is related only to "installed dependencies", because if I create a bunch of service providers in my application and register them, Laravel will probably use the very same sevices.json to store info about application packages, right? So it's about both, and if my application changes the services.json file will have to change.

Okay, but I also understand that Taylor must have seen some nasty stuff happening while deploying things with Envoyer, and decided to fix it all by changing that in Laravel 5.0, but, maybe, it should move again to a better place.

Cheers!

**Comment by phanan** [comment]
No @antoniofrignani, don't get me wrong. I'm not saying we should put these files under `vendor` -- in fact, I'm against it, and totally agree with what you've just said. The Symfony approach mentioned by @javiereguiluz above sounds like a better solution IMHO.

**Comment by taylorotwell** [comment]
I'm not sure we have come up with a totally valid reason not to just use
vendor other "Composer uses it."

**Comment by ikari7789** [comment]
@taylorotwell Don't get me wrong, but that one reason alone is a pretty hefty one. If Laravel was the application creating and managing the contents of the vendor folder, it would be one thing, but it feels like storing one application's files in another application's files.

**Comment by taylorotwell** [comment]
But we're not discussing any real issues with that directory I feel like,
are we? There is no known issue with storing a few files in that directory.
If we had any real, concrete reasons why not to do it that way I would
certainly consider them. As I said, we've had optional components (cashier)
that have done this for quite some time, and honestly nobody has ever
mentioned anything about it.

**Comment by willrowe** [comment]
My main concern would be a possible conflict with file names. Since the names of those files are somewhat general, another package or even Composer itself could use the same names causing one or both to not work as expected.
Everything else in the framework is organized and named very thoughtfully (the storage directory is a great example), so putting these files in the top of the `vendor` directory seems uncharacteristic for Laravel, since `vendor` doesn't seem to describe that use very well.
I think what is making most people uncomfortable is the fact that the `vendor` directory is not managed by us like the other directories in our applications. Since Composer manages that directory and it represents a very specific version of the packages within it, we are very careful not to make any changes to it. Adding or editing files instantly raises a red flag, so we'd prefer to leave the directory untouched. If there was another directory like `tmp` or `var` then it would only be used by the application for that specific purpose and we would be able to manage it with confidence.
I think that it is a great idea to not have these compiled files in the storage and I'm glad that Taylor is always thinking of ways to improve the framework and prevent issues. I hope we can come up with a solution that makes sense for everyone.

**Comment by taylorotwell** [comment]
rather than using top level vendor we could just vendor/laravel.

**Comment by phanan** [comment]
`vendor/laravel` is not a bad idea at all. Actually it makes much sense, as
now there's no conflict, and hey, I'm putting Laravel logic inside a
`laravel` dir, what more could you ask? ;)

**Comment by barryvdh** [comment]
Maybe @seldaek can give us some feedback about any known problems with storing (temporary) files in the vendor directory?

**Comment by driesvints** [comment]
I think @seldaek should join this thread and weigh in. He probably knows a lot more about the cons.

**Comment by driesvints** [comment]
Dammit, @barryvdh beat me too it :)

**Comment by Seldaek** [comment]
I haven't read the whole thread but it sounds to me like a potentially bad idea if only because the common expectation is that composer manages this and it contains only third party libs and isn't typically written in by anything else. 

This means it could lead to people doing things with the vendor dir that you won't expect and that you will mess with. I don't have concrete examples but it just sounds like asking for trouble to me.

**Comment by dcarrith** [comment]
@taylorotwell - The potential naming conflict of `services.json` and/or `compiled.php` were valid concerns, which would certainly be remedied by moving them into `vendor/laravel`.   But, there is also the issue of requiring people to make vendor writable (or even, `vendor/laravel`).  I know it will fall back to `storage` if vendor is not writable, but that seemed like an undesirable quick fix to me (or maybe not, you tell me).  

Some might think the concern over making `vendor/laravel` writable by the web server is moot since nothing in the vendor directory can then be executed by the web server directly.  But, isn't `vendor/laravel` for dependencies that are in fact loaded at some point by code that **is** directly executable by the web server?

Although **Drupal** probably has a few antagonists in the Laravel community (myself included, trust me, I work with it ever day) it **is** being used (somewhat confidently) by Enterprises and even in Government (particularly, US Government).  I only mention that because I hope to someday be building sites with Laravel instead and wanted to link to this Drupal post about [**Securing file permissions and ownership**](https://www.drupal.org/node/244924).  That is an example of top notch guidance by a framework which has helped to gain the trust of Enterprises and Government.  Compare that to `Laravel may require some permissions to be configured: folders within storage and vendor require write access by the web server.`  

Are there any community members who are CEH or LPT certified?  Is anyone out there associated with [**OWASP**](https://www.owasp.org/index.php/Main_Page) in any way that might like to comment on the notion of making `vendor` or `vendor/laravel` writable by the web server?

**Comment by taylorotwell** [comment]
I don't really want to drag this discussion on much longer. If we make
another folder that will just be another folder we have to make writable
instead of vendor. Both will contain PHP code. I don't see the difference
really?

**Comment by driesvints** [comment]
@taylorotwell I just think that it's best that you do this in a place which is under your control. You don't have any control over Composer's vendor folder because you can't predict what will happen with it in the future or with people's specific setups.

However, you _have_ control over all of Laravel's skeleton folders. If it's another folder to which people need to set permissions on then so be it. At least you can clearly state in the documentation which folders need to be writeable. Perhaps also make a config option out if it with the path to the directory so people can change the location if they want.

**Comment by dcarrith** [comment]
Maybe you could generate a hash of the generated files and store somewhere that isn't writable by the web server, only by the user who is running the composer install/update.  Then you could check the hash before using those files (if it doesn't match then regenerate on the fly).  That might alleviate some of the general concerns of having *any* directory writable when the files inside will later be loaded and used by the framework.  Sorry if this is tangential to the main discussion.

**Comment by taylorotwell** [comment]
I think we're getting a little carried away. We're operating primarily
under FUD right now rather than actual, proven problems.

**Comment by antonioribeiro** [comment]
The difference is enourmous and I would call it **autoload.php**. Some time in the future every possbile app in PHP might have one of this in vendor/, so if you want to create an exploit which affects every PHP app in the world, just find a way to write over autoload.php.

**Comment by taylorotwell** [comment]
OK, but even if we have a "tmp" directory, someone could just somehow, someway create an exploit to modify the compiled.php file to contain whatever code they want?

We should also note I still don't even really know why the "WEB" user would need to write this directory. All of the files would be created via the command line.

**Comment by driesvints** [comment]
Well, I'd say prevent instead of heal. It's better to prevent these problems and do it in a way that we know for sure won't introduce broken systems in the future than go with the vendor folder and hope for the best.

Besides (and this is just my own personal opinion), the fact that Jordi says that he thinks this is a bad idea is enough for me to conclude that we need to find another solution and not do this inside the vendor folder.

**Comment by taylorotwell** [comment]
We could just put these files in "bootstrap/cache" or something. I'm not
sure why we need a whole new top-level directory for these optimization
files.

**Comment by antonioribeiro** [comment]
Globally writable PHP files (or any other executable files) are bad idea, so compiled.php should be writable only by the server administrator, using the artisan command, not the webserver process, and it can be, right? So, I would have no problem in placing this one inside vendor/laravel/whatever. But as Jordi said, still a bad idea...

**Comment by taylorotwell** [comment]
The only remaining reason why it's a bad idea is because... the Composer
directory structure might change or something? I think we have eliminated
the somehow injecting malicious code into it because that can happen no
matter what direction we take I guess if the application is built that
poorly.

**Comment by dcarrith** [comment]
@taylorotwell - you've raised a rather good point.  After reading the thread I kept thinking the directory in question needed to be writable by the "WEB" user.  But, of course, it only needs to be writable by the user who is running the composer install/update.  Sorry for all the FUD.

**Comment by crynobone** [comment]
The only time a user would have issue writing to `vendor` folder could be that they're running `composer install` as `sudo`/different user while `php artisan` as something else. This would cause an issue to write to said folder thus the idea of `chmod 777`.

**Comment by dcarrith** [comment]
`bootstrap/cache` sounds good to me.

**Comment by winglian** [comment]
+1 for `bootstrap/cache` although I'm still a fan of something like `protected $optimizationBasePathRelativeDir = 'bootstrap/cache'` so the bikeshedders can point it wherever they please.

**Comment by antonioribeiro** [comment]
I would prefer something like a top-level `tmp/`, writable by the webserver, for things like routes.php and services.json and `bootstrap/cache`, writable only by the user and root, for executable code like `compiled.php`. And this would also show people, very clearly, where temporary files should be written to in Laravel.

**Comment by dnixx** [comment]
Every suggestion is better than `vendor/` (including a sub-directory), regardless of permission settings. Yes, you can make it work, and quite easily so, but it's illogical and potentially troublesome for reasons stated earlier in this thread.

**Comment by taylorotwell** [comment]
Actually it's pretty logical and no real concrete reasons have been
presented other than someday something somehow might break... maybe.

Anyways, I can see that pretty much it will be a total storm of fury on
this thread if I do anything other than use a tmp directory so I guess
that's what we'll do in 5.1.

**Comment by driesvints** [comment]
The storm of fury would only come from people who have no other means than to voice their opinion through rage :)

We (current participants in this thread) can only give your our concerns and opinions. It's still up to you to decide.

But I think it's really nice of you that you listen to your contributors and users and decided to do this so thank you for that! :)

**Comment by taylorotwell** [comment]
Done. Committed to laravel/framework master and laravel/laravel develop.
Uses new bootstrap/cache directory to store temporary optimization files
loaded during bootstrapping such as compiled.php, routes.php,
services.json, etc.

**Comment by taiyaei** [comment]
Sweet. :) Glad we could get this sorted so everyone's happy, or at least mostly happy. I think this can be closed now, at least for the meantime?

**Comment by taylorotwell** [comment]
Will leave this here as well: http://laravel.com/docs/master/upgrade#upgrade-5.1.0

The upgrade guide for 5.1 so far.

**Comment by JosephSilber** [comment]
@taylorotwell you should probably add to the upgrade guide that the `bootstrap/cache` directory you have to create should be writable.

**Comment by taylorotwell** [comment]
Ah, right. Thanks

**Comment by dakira** [comment]
I've got the feeling there is a silent majority who didn't voice their opinions here. Let me try to be their voice: I don't care, I'm sure you'll make the right decision. Don't make design choices by who screams the loudest. [Here's a piece](http://mystilleef.blogspot.com/2006/10/no-tabs-why.html) someone else wrote on that.

So does it feel right? No. Does it make a difference? I don't think so.

**Comment by thunderdiesel** [comment]
Thanks for fixing this for 5.1. I was having issues with SELinux labels since I didn't want to apply a rw label to the entire vendor directory. This meant I had to relabel services.json etc every time a dev did a composer update.
