### ISSUE TITLE
Paginators are broken when constructing them manually

### ISSUE THREAD

**Issue by dhardtke** [laravel/framework#8156]
Hi,
the title says it all.
Check out my example:
```php
$items = [
	"One",
	"Two",
	"Three",
	"Four"
];

$paginator = new \Illuminate\Pagination\Paginator($items, 1);

var_dump($paginator->getCollection()->first());
die();
```
**What I expect:** example.org/?page=2 should give me **Two**, but I always get **One** for every page.

PS:
The LengthAwarePaginator doesn't even consider the amount of items. With that one it gives all four items on every page, although I just want to have one per page (and yes, the Parameters I set are correctly).

**Comment by taylorotwell** [comment]
The paginator doesn't slice items for you, you have to slice the items before giving them to the paginator. The paginator is mainly for presenting links.

**Comment by hartantothio** [comment]
@taylorotwell, correct me if I'm wrong. But when I look at the Paginator constructor, since it takes the pre-sliced items, it might not generate the links correctly. Shouldn't it at the very least accept total count of items as parameters?

**Comment by taylorotwell** [comment]
The LengthAwarePaginator **does** take a total count.

**Comment by hartantothio** [comment]
Ah... Cool... I actually saw the file, but didn't realize.

**Comment by Francismori7** [comment]
@taylorotwell Looking at simplePaginate, I get the sense that you should get 6 items from the database if you want 5. This is weird, and explains this issue. If one was to slice the items to the max per page, Paginator->hasMore would be false, since 5 == 5.

```$this->hasMore = count($this->items) > ($this->perPage);```

So is this the expected behavior? Pass 1 more row to the Paginator so it slices of the last one, and knows there is more?

**Comment by taylorotwell** [comment]
@Francismori7 yes I think you will need to pass the rows + 1

**Comment by Francismori7** [comment]
@taylorotwell Perhaps then this should be mentionned in the docs here http://laravel.com/docs/master/pagination#manually-creating-a-paginator

It never mentions it need x+1 rows, just that it doesn't need to know the total number of items (which of course, makes no sense since it couldn't know when to stop paginating)
