### ISSUE TITLE
BelongsToMany::findOrNew() returns object with wrong id

### ISSUE THREAD

**Issue by tormit** [laravel/framework#8217]
I have pivot table, which has it's own _id_ field. If I use BelongsToMany::findOrNew() to find related object, it returns correct object, but it's _id_ field is pivot table's _id_ not target object id.

**Example**
_Tables_
Company:
* id
* name

User: 
* id
* name

CompanyUser:
* id
* user_id
* company_id
* role

```php
class User extends Model {
    public function companies()
    {
        return $this->belongsToMany('App\Company');
    }
}
```

```php
$company = $user->companies()->findOrNew(1);

// $company->id has value of CompanyUser->id, not Company->id
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by zmorris** [comment]
Has this been fixed in a branch?  I ran into the same issue and had to add `->select('company.*')` within the `companies()` method to get it to use `Company->id` rather than `CompanyUser->id`.  I'm concerned that this may interfere with additional `select()` clauses outside the `companies()` method down the road.
