### ISSUE TITLE
Paginator Exceeding Pages

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#8252]
If you have 20 items per page on the paginator and you have 21 items, if someone else comes along and deletes one item leaving only 20, now there's only 1 page if the other person then refreshes they are still on page 2 and the paginator returns no results.

```php
$model->paginate(20);
```

Should the paginator not throw an Exception to catch them being out of bounds, or as most paginators do show the last possible page if there are any results at all.

**Comment by j4k** [comment]
I would quite like to see something like this also, I've encountered this problem before. I think an Exception should be thrown that can be dealt with personally.

**Comment by Sladewill** [comment]
Apparently there's some weird issue where this occurs on another installation on the latest 5.0.* and 5.0.5 it appears to be working.

**Comment by cs475x** [comment]
I noticed this same behavior today and did a little digging. If you navigate beyond the last page, it's supposed to show you the last page. The cause of the issue is in [`Illuminate\Database\Eloquent\Builder`](https://github.com/laravel/framework/blob/45495066373ff6daa314f6550cab2b3de16f26f7/src/Illuminate/Database/Eloquent/Builder.php#L265). It [resolves the current page number](https://github.com/laravel/framework/blob/79f15d98809a48274a281dfae7fa69d66bf734d7/src/Illuminate/Pagination/PaginationServiceProvider.php#L21) and uses the result without validating it like [`Illuminate\Pagination\LengthAwarePaginator`](https://github.com/laravel/framework/blob/57695c173ffddaa45eb5b5d958b80086bb3c9547/src/Illuminate/Pagination/LengthAwarePaginator.php#L64-L72) does. The resulting query still offsets the results by the out-of-bounds page number instead of the corrected page number used in the paginator.

**Comment by GrahamCampbell** [comment]
@cs475x If you could send a PR, though would be great. :)
