### ISSUE TITLE
[Bug] Homestead default github user is mvdstam

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#8348]
So user @mvdstam appears to be the default Homestead Github user?

If you do a completely new Homestead install, and do not set a global username + email on your build, then when you push to Github it will tag all your commits as from @mvdstam.

At first I thought it must have been me and I accidently set the wrong name. But today on Stackoverflow someone else posted the **exact** same issue - for the **exact** same github name: http://stackoverflow.com/q/29522925/1317935

I checked the contribution history - and @mvdstam has not contributed to Homestead - so I dont know how/why this is occurring?

Obviously you should set your global github username+email (I normally do, but my script failed so I didnt notice)

But can we at least change the default user? Perhaps even make a 'homestead' github user that is the default - so it is more obvious? Or can we force the variables to be null?

**Comment by TheShiftExchange** [comment]
p.s. I cant link the contriubtions for my commits as it is on a private repo.

I did contact Github about the issue (when I thought it was just me) - and they said that having these commits with the wrong username is just 'symbolic' - and doesnt provide @mvdstam with access to those projects, and it wont show up on @mvdstam's contribution profile either.

**Comment by franzliedke** [comment]
Why don't you use Git on the host machine?

**Comment by kdoichinov** [comment]
I think the real question is why Homestead comes with a git repo that has a preconfigured remote, user and all...

**Comment by mvdstam** [comment]
Well, this is awkward.

I *did* do a fork of the installer repo: https://github.com/mvdstam/installer to screw around a bit. But why does this change things for other people?

**Comment by mvdstam** [comment]
Ah, I think I've found it. My previous comment had nothing to do with it.

When doing git-related stuff from within the homestead box, you are doing it as a user called "vagrant" if things aren't configured properly (such as SSH keys not being transferred correctly to the vagrant box upon provisioning). In that case, when you try to push something, you can't since you're doing it under some "vagrant" user that doesn't exist.

I, however, in my youthful enthousiasm, linked that user (somehow) to my github account. Which means that everyone that tries to do something with the vagrant user and git, ends up in my github account.

I removed the link from the vagrant user and my github account under my profile settings; people shouldn't end up in my github account anymore.

However, this doesn't really alleviate the problem itself since anyone could do this apparently. Homestead shouldn't come preconfigured with preconfigured git users, because stuff like this can happen.

**Comment by TheShiftExchange** [comment]
Thanks @mvdstam - at least that explains it.

The real question now is how do we stop it from happening again - otherwise anyone else could potentially do this?

**Comment by franzliedke** [comment]
Interesting. You should submit a pull request to the laravel/settler repository. It has [a provisioning script](https://github.com/laravel/settler/blob/3653aeefaf69e5a54709a29e07ab702664d4576c/scripts/provision.sh#L35) that installs Git etc. You should add a line to make sure no Git user is configured... (maybe setting the user correctly can then be integrated into Homestead).

**Comment by mvdstam** [comment]
Now that I think about it, I believe git normally just assumes the current username and emailaddress ({username}@{hostname}) if nothing is configured. I don't think there are any git users "preconfigured" in the homestead box:

`git config --global --list`

The command above simply returns:

`fatal: unable to read config file '/home/vagrant/.gitconfig': No such file or directory`

Which means absolutely nothing is configured.

In this case, the username "vagrant" and the emailaddres "vagrant@homestead.tld" is assumed. Although the user is prompted during commits to check the global git configuration in these cases, it is still possible to just go ahead and do commits under the assumed username and emailaddress. I don't think this is really a "homestead" issue, but more like standard git behavior.

Furthermore, I believe the reason I could successfully link the vagrant account to my github account, is because github provides the option to link accounts fully by command-line when you're pushing something to a repo you own. All I had to do, is provide my *real* github credentials, and suddenly I could then do commits and pushes from the "authorized" or "linked" vagrant account. From that perspective, the real security flaw here lies with Github itself since all you need to "steal" someone's identity is a emailaddress. Not that you can do anything of course because it's simply an alias of an account for which you don't have any access to, but still.

**Comment by franzliedke** [comment]
Maybe Homestead could copy the Git config file from the host computer to the guest on provisioning?

**Comment by mvdstam** [comment]
I think the solution lies with Github. In my opinion, linking emailaddresses to Github accounts should *always* be confirmed by email (which is normally the case when you want to add additional emailaddresses to your github account in your profile settings). In other words, you should be a authorized owner of the emailaddress you're trying to link, even when doing it from the command line when pushing from a different emailaddress to a repo you own.

Thoughts?

**Comment by franzliedke** [comment]
Agreed. I'm confused that they seem to do this automatically.

@mvdstam Can you take care of sending an email to their support team? https://github.com/contact

**Comment by TheShiftExchange** [comment]
So what if the Homestead box had a default email address as "homestead@laravel.com". 

Taylor creates a special "homestead" user on Github with that email, and puts a fancy Laravel logo there.

Then at least worse case, you are only ever committing under the secure "Homestead" github name that Taylor has control over...

(At least until Github provide a solution - but there is no guarantee they will - seems like a generic issue to me).

**Comment by TheShiftExchange** [comment]
p.s. or better yet - as part of provisioning Homestead - can we **force** people to type a github username and email perhaps?

Obviously that is ideal - but we just need a safe fallback option...

**Comment by mvdstam** [comment]
Agreed. But that's only assuming that it's actually not possible to have one emailaddress linked to more than one account this way.

I'll contact their support team to see what they think of this.

**Comment by mvdstam** [comment]
Right, I just sent an message to Github through the contact form @franzliedke gave me. I'll let you guys know what they think of the whole issue through this issue.

Finally, @TheShiftExchange: even when forcing people to type github usernames during provisioning or stuff like that, it wouldn't stop anyone from reverting settings and simply recreating the scenario we're discussing now. If you want, you could do commits from Bill Gates' emailaddress if you'd know where to find it.

**Comment by TheShiftExchange** [comment]
So are you saying I can commit to any project as Taylor? Since I know his email?

It just doesnt seem right??

**Comment by GrahamCampbell** [comment]
> So are you saying I can commit to any project as Taylor? Since I know his email?

That seems right to me. It's really useful, and without this, projects like symfony wouldn't be able to work in the way they do.

**Comment by mvdstam** [comment]
Right, this is what Github had to say:

----

Hi Max,

Thanks for getting in touch. What you're referring to is a known part of Git and is discussed here:

https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user

Many people confuse this impersonation/commit authorship issue with a security/repository access issue.

While it would be nice to only allow commits to be linked for authorised email addresses, this would also mean that an enormous number of commits wouldn't be able to be linked to people's accounts for old email addresses that they no longer have access to etc.

Thanks,
James

**Comment by GrahamCampbell** [comment]
@mvdstam You need to unlike our email from your GitHub account please.

**Comment by franzliedke** [comment]
I fully agree that the impersonation is a good feature.

I still don't quite understand how this email address was connected to your account, @mvdstam. That is the part that worries me a bit.

**Comment by GrahamCampbell** [comment]
@franzliedke yeh

**Comment by crynobone** [comment]
> I still don't quite understand how this email address was connected to your account, @mvdstam. That is the part that worries me a bit.

@franzliedke @GrahamCampbell 

> In this case, the username "vagrant" and the emailaddres "vagrant@homestead.tld" is assumed. 

![screen shot 2015-04-09 at 10 06 35 pm](https://cloud.githubusercontent.com/assets/172966/7068427/da101306-df04-11e4-950d-82dda6aa9532.png)

**Comment by franzliedke** [comment]
@crynobone If I remember correctly, you have to confirm these ones, no?

**Comment by crynobone** [comment]
@franzliedke 

From Github response:

> While it would be nice to only allow commits to be linked for authorised email addresses, this would also mean that an enormous number of commits wouldn't be able to be linked to people's accounts for old email addresses that they no longer have access to etc.

How would you confirm it's your email when you no longer have access to it?

**Comment by franzliedke** [comment]
Okay, thanks. Sorry for causing confusion, everyone.

**Comment by mvdstam** [comment]
@GrahamCampbell Just so we're clear: the only emailaddress that was linked to my account in addition to my own emailaddresses, was the vagrant@homestead.tld emailaccount. I never ever had any other emailaddresses linked to my account, especially not emailaddresses belonging to homestead.

Finally, for those still wondering about how the emailaddress was linked, please re-read the following I've already written in an earlier reply to this issue:

---

Furthermore, I believe the reason I could successfully link the vagrant account to my github account, is because github provides the option to link accounts fully by command-line when you're pushing something to a repo you own. All I had to do, is provide my real github credentials, and suddenly I could then do commits and pushes from the "authorized" or "linked" vagrant account. From that perspective, the real security flaw here lies with Github itself since all you need to "steal" someone's identity is a emailaddress. Not that you can do anything of course because it's simply an alias of an account for which you don't have any access to, but still.

**Comment by TheShiftExchange** [comment]
@GrahamCampbell  - so wouldnt it make sense for Taylor to link the email `vagrant@homestead.tld` to his account? Or create a special "Homestead" Github account?

Otherwise there is **nothing** stopping anyone else from just hijacking the email address for future commits...?
