### ISSUE TITLE
Composer update fails at psysh, prompts for Github credentials

### ISSUE THREAD

**Issue by krustchinsky** [laravel/framework#8354]
This just started happening today. I'll run composer update and receive the following:
![capture](https://cloud.githubusercontent.com/assets/389009/7067983/db857a02-de94-11e4-83f0-2164b3dea30c.PNG)

**Comment by brunogaspar** [comment]
If you read the error, it's saying that you've reached the GitHub API rate limit, therefore it asks you to input your GitHub credentials to authenticate you against the GitHub API and continue downloading the packages, otherwise you'll need to wait until your limit resets.

Related:
- https://developer.github.com/changes/2012-10-14-rate-limit-changes/
- https://developer.github.com/v3/rate_limit/
