### ISSUE TITLE
[L5] Eloquent interoperatibility with Twig

### ISSUE THREAD

**Issue by danipardo** [laravel/framework#8366]
When rendering properties using Twig of a brand new Model (not fetched from the DB and populated), BadMethodCallException will happen. 

class Post extends \Illuminate\Database\Eloquent\Model {

} 

When calling {{ post.created_at }} inside Twig, it will:

- Check if post is an array, and if so, check if created_at is an element of that array.
- Check if post is an object, and create_at is a property of that object (its not there yet).
- Check if created_at is a method in the Post model.

Problem is that dynamic methods used by Eloquent query builder will end up throwing the error.
Ideally, dynamic properties should be set when within the constructor of a model.

**Comment by GrahamCampbell** [comment]
Hmmm. I suggest that you "preset" the model before passing it to the view. That way you can wrap the model so that this stuff works. I co-maintain https://github.com/ShawnMcCool/laravel-auto-presenter. I don't know if flicking through that would be of any use to you.

I think this issue has come up before though, or rather, the same underlying thing.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. Can't remember why nothing was done?

**Comment by billmn** [comment]
Are you using this package for Twig integration? https://github.com/rcrowe/TwigBridge/tree/0.7

**Comment by GrahamCampbell** [comment]
Closing as this has been discussed many times since. See Taylor's response on #9644 for example. :)
