### ISSUE TITLE
$matcher->createMatcher() capturing brackets

### ISSUE THREAD

**Issue by Tylerian** [laravel/framework#8430]
# file ''Illuminate\View\Compilers\BladeCompiler.php"

The current 'createMatcher( ... )' function is matching all including the brackets.
i.e:
```php
/*
 * @hello('world')
 * expected: world
 * captured: ('world')
 */

$compiler->createMatcher('hello');
```

Is this capture intended?
Because on Blade documentation, there's an example where you're extending Blade with the 'datetime' keyword, and it expects to capture the text within the brackets, not the text plus the brackets.

´´The following example creates a @datetime($var) directive which simply calls ->format() on $var:´´

I attach you the patched function below:
```php
/**
 * Get the regular expression for a generic Blade function.
 *
 * @param  string  $function
 * @return string
 */
public function createMatcher($function)
{
	return '/(?<!\w)(\s*)@'.$function.'\s*\(\s*(.*)\)/';
}
```

Cheers, Jairo Tylera

**Comment by Arrilot** [comment]
According to tests it looks like intended behavior, but everyone admits that it's pretty confusing.
Taylor even removed that section from the docs.
So this is probably gonna be reworked in 5.1 (see #8425).

I don't think this method should be changed in 5.0 because many 3rd party packages are already adapted to the current behaviour.
