### ISSUE TITLE
Databse - Losing connecting silently reconnects and aborts transaction

### ISSUE THREAD

**Issue by mrjgreen** [laravel/framework#8628]
What would happen [here in the database connection](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Connection.php#L569) if your connection drops out during a transaction, say after you have successfully ran a few inserts or deletes?

~~~PHP
		// Here we will run this query. If an exception occurs we'll determine if it was
		// caused by a connection that has been lost. If that is the cause, we'll try
		// to re-establish connection and re-run the query with a fresh connection.
		try
		{
			$result = $this->runQueryCallback($query, $bindings, $callback);
		}
		catch (QueryException $e)
		{
			$result = $this->tryAgainIfCausedByLostConnection(
				$e, $query, $bindings, $callback
			);
		}
~~~

It seems that the reconnection would happen silently and your previous queries would never be committed. You wouldn't start a new transaction, but would just blindly start auto-committing the remaining queries, before obliviously calling "commit" which would succeed despite no longer being in a transaction, and you would never know anything went wrong... 

I may be wrong about this, but I've had some problems with transactions half-committing in high network traffic environments, where connection loss is frequent enough to cause this to happen regularly.

**Comment by mrjgreen** [comment]
Closed - already fixed in later version - apologies.

**Comment by ockle** [comment]
@mrjgreen Just stumbled on this after having an issue with Laravel trying to reconnect while in a transaction. You mention that this has been fixed in a later version, but I don't see the code you're referring to? It looks like it will [still attempt a reconnect](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Connection.php#L655) regardless of whether it's in a transaction?
