### ISSUE TITLE
Artisan app:name and fresh bug

### ISSUE THREAD

**Issue by it-can** [laravel/framework#8692]
Hi,

I just noticed a little bug in Laravel 5. I setup a new project, and used ```php artisan app:name testProject``` and if you call ```php artisan fresh``` after that, It will reset the namespace in the  ```app/Providers/AppServiceProvider.php``` to ```<?php namespace App\Providers;```

**Comment by GrahamCampbell** [comment]
Yeh, this is expected. You need to do fresh first.

**Comment by dbbk** [comment]
Why is this expected? This bug just tripped me up. `php artisan fresh` is advertised as removing the scaffold files, not breaking your namespace and causing fatal errors.

In addition, the documentation makes no mention of `php artisan fresh` having to be called prior to setting the app namespace.

**Comment by willrowe** [comment]
I can see how it might be expected that the namespace would be reset to `App` because the command is named `fresh`. However, it does not actually check and do so for all existing files like `app:rename` does, it only does so for `AppServiceProvider` as a side-effect. If it is indeed expected behavior then this command should also call `app:rename` to reset the namespace to `App` for all files, otherwise it should preserve the current app namespace by using `Illuminate\Console\AppNamespaceDetectorTrait` and replacing it in the stub.
