### ISSUE TITLE
Redis cluster configuration

### ISSUE THREAD

**Issue by trompx** [laravel/framework#8750]
Hello,

Just like this stackoverflow question : 
http://stackoverflow.com/questions/28309671/configuring-highly-available-redis-cluster-in-laravel
I am trying to setup a redis cluster (at least a redis replication system : first I wanted to setup something with redis sentinel, some packages already exists like this one https://github.com/Sparkcentral/PSRedis/issues but they use Predis and I am using Phpredis for performance).
I tried to find some information about how to configure the database.php correctly for redis cluster without success and was wondering if you'd have some tips. If I add more redis servers, how Laravel will pick the right one ? how will it balance writes/reads between masters/slaves ?
One more thing, do you know where would be a good place to implement that kind of logic and to autopromote a slave when the master is down ?

Thank you

**Comment by GrahamCampbell** [comment]
Sorry, we don't provide support on GitHub. I'd recommend you try our forums. I'm sure someone can help you out there. :)

**Comment by trompx** [comment]
No problem, I understand but it was the kind of question similar to https://github.com/laravel/framework/issues/5 for mysql which draw some attention so as I did not find precise documentation about the redis configuration (which I believe could be complemented in a certain way), I thought it was still relevant to ask.

Anyway thanks and direction the forums.

**Comment by cyrossignol** [comment]
@trompx I know this issue is pretty old, but this was one of the first results that I came across when searching for information about using Sentinel with Laravel. I'll leave a reply here for anyone who finds this issue looking for the same information:

I just wrote a [Laravel package](https://github.com/monospice/laravel-redis-sentinel-driver) that help to configure Laravel for master-slave replicated Sentinel setups using the functionality now included in the Predis client library. The code is pretty simple, so we could consider merging this into future Laravel releases for native replication support one we collect some extended experience testing it in the field on production servers.
