### ISSUE TITLE
Models folder for models created by artisan.

### ISSUE THREAD

**Issue by pflirae** [laravel/framework#8797]
With version 5 a new folder struture was defined under the app folder. This has been greate to structure the code and work faster than ever on development. Only one new folder was missing Models, where all models should be cretaed and stored by artisan, instead of saving them to the app folder. So, I propose to create a Models folder under app, where all models are stored automatically by artisan when created.

**Comment by overtrue** [comment]
:+1:

**Comment by hernandev** [comment]
Where to store the resources are personal choices, the whole `laravel/laravel` structure is just a kind of example for you to do whatever you want.

Notice that the skeleton application does not even contains a license file, since it should be used as a started point.

you can of course, extend the make command to attend your needs.

BUT,

Personal advice: a basic model including the use clause the the Model class is 90 char long, type it manually or have your editor to help you with that (you can do that on phpstorm with less than 10 key strokes) or even sublime snippets.

Just in case productivity matters here.

**Comment by franzliedke** [comment]
Can't you do something like `php artisan make:model My/Model/Namespace/Bar` (using slashes, not backslashes)?

**Comment by pflirae** [comment]
You are right franzliedke, it worked perfect, thanks for your comment.
