### ISSUE TITLE
Artisan:rollback missing --path argument

### ISSUE THREAD

**Issue by itsash--** [laravel/framework#8813]
I believe this is a bug because `--path` is available when running `php artisan migrate --path=/vendor/package/database/migrations`.

However I get the following error when I run: `php artisan migrate:rollback`

```
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'CreateSomeRandomTable' not found
```

This is because the migrations keeps looking in /database/migrations, but the migrations were run from `--path`.

Also, since `artisan:rollback` works by the most recent batch, until the batch prior using `--path` would work.  I can see how `refresh` and `reset` would not work with this argument though.

**Comment by Sladewill** [comment]
The problem is even with that, some of the migrations might exist in one place but some in another, it would need to work like the views where you can setup multiple directories for it to look for.

**Comment by itsash--** [comment]
I agree with the multiple directories.

Also, when you use the `--path` argument, it only runs the migrations within that path. Therefore you do not run in to migrations existing in other places because the rollback will only migrate down one batch a time.  Which means, so long as you don't move the migrations between paths it would be fine.

Only reset and refresh could not work with `--path` for that reason.

**Comment by GrahamCampbell** [comment]
This is a duplicate though I can't remember why nothing was done. Ping @taylorotwell.

**Comment by itsash--** [comment]
I've been looking into this issue and it's more difficult that I thought. I've had inconsistent results, in that it sometimes works and then it doesn't with different errors from cannot redelcare classes etc.

I think the best thing would be to allow multiple directories to glob for the migrator instead of `--path` because i personally don't see the point in publishing everything from a package into the application, otherwise it defeats the point of them imo.

What are your thoughts on this?

**Comment by levacic** [comment]
I'm actually pretty certain that it doesn't make sense *not* to publish package migrations into your project - in fact, if it were up to me, I'd completely disable publishing migrations directly from packages.

First of all, in case of using vendor migrations, each developer, and each environment (e.g. staging/production) must also manually execute the appropriate package migration, instead of `php artisan migrate` providing a complete, working database.

Furthermore, if a package introduces a backwards-compatible update with different migrations (e.g. a new table for some new functionality), this might result in different database structures in different environments, which is awful (I don't think an explanation is required here).

However, given that this functionality *does* exist, it would probably be better to provide a working rollback mechanism, but I can't think of a more robust approach besides actually storing the `path` for each migration (automatically scanning directories wouldn't work, as it would be possible to run a migration from one directory, and later provide the same migration in another auto-scanned directory, leading to potentially inconsistent behavior).
