### ISSUE TITLE
Builder Not Found Method

### ISSUE THREAD

**Issue by beyazkurt** [laravel/framework#8879]
In controller write these codes:

     $allContents = Icerik::with(['relatedLang', 'relatedUsers', 'relatedTips'])->get();

And in my Icerik model has got relations:

    public function relatedUsers(){
        $this->belongsTo("App\Model\User","creater_user_id","id");
    }

    public function relatedLang(){
        $this->belongsTo("App\Model\Langs", "lang_id", "id");
    }

    public function relatedTips(){
        $this->belongsTo("App\Model\IcerikTipler", "icerik_tipi", "id");
    }

But i get this error:

FatalErrorException in Builder.php line 424:
Call to a member function addEagerConstraints() on a non-object.

Step by step i follow the codes and in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php file 422. line running this function:

    $relation = $this->getRelation($name);

But this function return "null" value. So addEagerConstraints() function not found in a null variable. 
But why relation return error? The $name value is "relatedLang" and at 450. line has passed $relation variable value "relatedLang". This method goes to model function with name is "relatedLang" execute it. But i was remove the relation from database so it return null. 

In Builder.php after $relation (422. line) variable must be controlled if null or not a relation.

**Comment by lukasgeiter** [comment]
Your relationship declarations have to `return` the relationship object:

    public function relatedUsers(){
        $this->belongsTo("App\Model\User","creater_user_id","id");
    }
    // and so on

**Please note:** I helped you because I immediately saw the error in your code. Usually this isn't the place to get help if you are having problems with Laravel. Github issues are for bug reports, feature requests or proposals. For support questions please turn to the [Laravel Forum](http://laravel.io/forum) or other external sources like the Laracasts Forum or Stack Overflow.

**Comment by beyazkurt** [comment]
Sorry for that and thanks for help.

**Comment by jbrooksuk** [comment]
@beyazkurt don't forget to close the issue :)
