### ISSUE TITLE
Issue in framework/src/Illuminate/Foundation/helpers.php 

### ISSUE THREAD

**Issue by Ermac25** [laravel/framework#8913]
public_path() , database_path() , config_path() , app_path() 

fail to work correcly on widows

as you can see here

https://github.com/laravel/framework/compare/5.0...Ermac25:Ermac25-patch-1?expand=1

adding '/' as a string  assumes a linux eviroment , using DIRECTORY_SEPARATOR solves the issue

**Comment by GrahamCampbell** [comment]
> adding '/' as a string assumes a linux eviroment 

No it doesn't. PHP converts it internally before doing the low level operations.

**Comment by Ermac25** [comment]
Really? because public_path() on widows  returns
in case off  c:\www\lamp\project\public
it returns c:\www\lamp\project\public/ 

so why the / if it's already corrected?

**Comment by Garbee** [comment]
This is an issue, but it is a BC breaking change. So should be done at the next major release whenever that happens.

**Comment by nicholasruunu** [comment]
The issue is with consistency and parsing of paths.

public_path uses / while path.public uses DIRECTORY_SEPARATOR:

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L338
https://github.com/laravel/framework/blob/cb6902f24537557642293e23528c86b2bf0afe5d/src/Illuminate/Foundation/helpers.php#L377

Not a huge deal but something to be considered. Possible BC break for windows users who have parsed paths.

**Comment by GrahamCampbell** [comment]
> it returns c:\www\lamp\project\public/

Yes, that's fine. Under the hood, php will make the correct low level calls when you actually use the filesystem.

**Comment by nicholasruunu** [comment]
@GrahamCampbell Feels like you're dodging the actual issue here. Paths can be saved to db/returned by API and be used in other languages too. And as I stated earlier, inconsistency when parsing strings is still an issue, just `explode(DIRECTORY_SEPARATOR, $path)` would not work as expected on windows.

**Comment by GrahamCampbell** [comment]
That doesn't seem to be an issue as far as I'm concerned. You need a more robust solution if you want  to do that. You may want to write yourself a simple normalize path function or something.

**Comment by nicholasruunu** [comment]
Yeah, you're right, you should write a normalize function for exploding separators using public_path(). It actually should be inconsistent for no apparent reason.

**Comment by Garbee** [comment]
This is the framework producing inconsistent output. Something Taylor prides himself on it doing. Consistency and reliability are major things Laravel offers developers, and this fails in that regard.

It is a major issue, and in fact breaks the ability to simply hand off the paths generated to another method since you then would need to wrap it in your own function to normalize it yourself.

Either way though, it is an existing issue that could be relied upon in user-land code. Fixing it could introduce a BC break. So it should not be addressed in the 5.x line but taken care of in 6.0 whenever that happens to land.
