### ISSUE TITLE
[L5] [Doctrine\DBAL\DBALException when trying to change a decimal column

### ISSUE THREAD

**Issue by eschmid72** [laravel/framework#8930]
I tried to change the size of a decimal column from 8,2 to 15,3:

```php
Schema::table('table_name', function ($table) {
    $table->double('length',15,3)->change();
});
```

I'm getting a weird exception message:

```
  [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

**Comment by GrahamCampbell** [comment]
Is still an issue in the very latest release. I thought I fixed this?

**Comment by soee** [comment]
Yes it is in the latest release, have this problem in current project.

**Comment by phroggyy** [comment]
@grahamcampbell @soee: this is no issue of Laravel but rather Doctrine. If Doctrine is available, it is used for all migrations, and Doctrine does not support enums. Since the Schema builder accesses the entire table with `Schema::table`, it fails if the table has one or more enum columns, regardless of if that column is being changed or not.
