### ISSUE TITLE
Integrity constraint violation when using database session driver

### ISSUE THREAD

**Issue by thewinterwind** [laravel/framework#9251]
Experienced this in 5.0 and 5.1

MySQL version: 5.6
Forge provisioned server.

We use Galera Cluster for MySQL, but each site reads and writes from only one database. I don't think that would have anything to do with this error. I used `artisan session:table` to create the table so everything is standard schema-wise. Happens quite intermittently, about once per day.

```
Illuminate\Database\QueryExceptionGET /diaz/edit
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4c1698dcfe5da87c5f77c90592855490817e575d' for key 'sessions_id_unique' (SQL: insert into `sessions` (`id`, `payload`, `last_activity`) values (4c1698dcfe5da87c5f77c90592855490817e575d, YTo1OntzOjY6Il90b2tlbiI7czo0MDoid1NLSjlmNGFxUml4RkowRVVkU0M3UjhNdldhWlZEY2hwTDhrbEU3YSI7czo3OiJtZXNzYWdlIjtzOjI2OiJMb2dpbiB0byBlZGl0IHlvdXIgcHJvZmlsZSI7czo1OiJmbGFzaCI7YToyOntzOjM6Im5ldyI7YTowOnt9czozOiJvbGQiO2E6MTp7aTowO3M6NzoibWVzc2FnZSI7fX1zOjk6Il9wcmV2aW91cyI7YToxOntzOjM6InVybCI7czozNzoiaHR0cHM6Ly9tYW5pbGEuZXNjb3J0cy5saWZlL2RpYXovZWRpdCI7fXM6OToiX3NmMl9tZXRhIjthOjM6e3M6MToidSI7aToxNDM0MTY4Njc0O3M6MToiYyI7aToxNDM0MTY4Njc0O3M6MToibCI7czoxOiIwIjt9fQ==, 1434168674))
```

**Comment by rkgrep** [comment]
Is it possible that insert quieries are not written immediately but with some latency?

**Comment by thewinterwind** [comment]
yes but not much.

**Comment by GrahamCampbell** [comment]
You probably need to cache config. That fixes most issues I see like this.

**Comment by ibrasho** [comment]
I'm using config:cache but I still see this issue every day or so.
We still relay on `dotenv` to populate server variables, so this might be the issue.

**Comment by rkgrep** [comment]
Why do you think it is a config cache issue?
I guess there may be some latency between sending response (with session ID) and app termination (when session is being saved to databse).

For example:
1. User sends request - session id created (session->exists == false)
2. User gets response (with generated session id).
3. Some ajax or another request catches session id (session->exists == false as the first request is not finished).
4. One of requests terminates app ([session written to database with INSERT](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Session/DatabaseSessionHandler.php#L79))
5. Anothers request terminates with INSERT statement again (because session->exists is false in both cases)

**Comment by ghprod** [comment]
Happened to me now after switched to database driver for session .. any idea?

Thanks

ping @taylorotwell

**Comment by mgrimard** [comment]
I am experiencing the issue as well, using the default session build with the DB.

**Comment by ghprod** [comment]
:+1:

**Comment by deanmraz** [comment]
@GrahamCampbell why close this ticket, seems like lots of people are having issues with this problem and continue to have this problem. I think the issue lies in the database driver -> save method.

**Comment by taylorotwell** [comment]
This needs reopening.

**Comment by taylorotwell** [comment]
Does anyone have a solution?

**Comment by deanmraz** [comment]
Deployed this fix to my environment today. I will let you know if that resolves the issue. 
#12059

**Comment by nolros** [comment]
@taylorotwell  @GrahamCampbell         

I've seen a number of these session integrity issues show up on laracasts, stackoverflow, etc. I ran into the same issue today and able to replicate to some degree. It seems to a session DB related issue vs. session file. To be honest it is not really a bug but a dev issue that can be solved with middleware. That said given the norm of multi device it might be something you want to look into, but unsure if even that applies.

REPLICATE: Let’s say you have a home.blade.php and second page called register.blade.php a route ‘/register’ which yields content from home. If you load /register from lets say from a MAMP stack everything will work fine as expected. Now while you still have that session, open a new browser tab. Make a copy of home.blade.php , lets say debug.blade.php which again yields to the same register.blade.php a route ‘/register’ and now if you load /register it will load register and will create the duplicate session id. Now if you go back to original tab and attempt to load register or you will get a DB session integrity duplicate issue. Which is why a number of bug complaints are login / logout related as I suspect is because they are directing to a different (duplicate) home page while still using the same session. Unsure what is causing the duplicate issue i.e if it is csrf token / session / DB session / home page issue.

Hope his helps.

**Comment by tuproyecto** [comment]
Any solution for this Bug?

**Comment by ghprod** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
> Any solution for this Bug?

Not in 3 hours.

**Comment by nolros** [comment]
fwiw, I noticed I can also replicate it again by breaking a blade template load during ajax requests. For example if I force a blade template fails (e.g. wrong name) while I'm doing an ajax init() data load on vanilla route. 

<code>
Route::get('/register', [
    'as'            => 'getRegister',
    'uses'          => 'ApiController@getRegister',
]); 
</code>

been trying to debug it further but none of angular / testing tools are giving me any additional insight. I do believe that to @rkgrep summary above that there is a session / queue issue / conflict and might be ajax related. 

In my case I have a number of angular services init ajax http requests and if the template fails i.e. exception and then attempt to reload . I get a

      javascript?v=1453465343:2050 Uncaught SyntaxError: Unexpected token < 

    followed by a 

     angular.js:13642 SyntaxError: Unexpected token < in JSON at position 11625. 

the position 11625 is where the html document gets appended to the JSON data. 

I think it is worth nothing that I get the following exception if it detects an existing session record, but I get the above silent fail if it has 2 existing session records i.e somehow the DB has written 2 identical session records and if it attempts to write a 3rd it fails silently and sends back JSON data but unencoded.


Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a26e09eaf0a210a34e58ebab42acd9435681e0a5' for key 'sessions_id_unique' (SQL: insert into `sessions` (`payload`, `last_activity`, `user_id`, `ip_address`, `user_agent`, `id`) values (YTo0OntzOjY6Il90b2tlbiI7czo0MDoiOVE3M3ZLam12YlpFVEhLNDBSOVAwMDdIZWpKeGY0YUFNQVZDRTFJUCI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MzI6Imh0dHA6Ly93d3cuY21vOjg4ODgvYXBpL3BlcnNvbmFzIjt9czo5OiJfc2YyX21ldGEiO2E6Mzp7czoxOiJ1IjtpOjE0NjU5MjE0ODU7czoxOiJjIjtpOjE0NjU5MjE0ODU7czoxOiJsIjtzOjE6IjAiO31zOjU6ImZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=, 1465921486, , ::1, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36, a26e09eaf0a210a34e58ebab42acd9435681e0a5))' in /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713
Stack trace:
#0 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#1 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#2 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\Database\Connection->statement('insert into `se...', Array)
#3 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2039): Illuminate\Database\Connection->insert('insert into `se...', Array)
#4 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(117): Illuminate\Database\Query\Builder->insert(Array)
#5 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Session/Store.php(262): Illuminate\Session\DatabaseSessionHandler->write('a26e09eaf0a210a...', 'a:4:{s:6:"_toke...')
#6 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#7 /Users/nolros/Documents/cmo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(155): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 /Users/nolros/Documents/cmo/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#9 {main}  


The issue is resolved if I delete the DB session. This probably doesn't help much but I thought I would share anyway.

**Comment by tuproyecto** [comment]
Any solution?

**Comment by GrahamCampbell** [comment]
Is it working on the very latest version?

**Comment by tuproyecto** [comment]
5.1.*

**Comment by GrahamCampbell** [comment]
Please provide the exact version.

**Comment by tuproyecto** [comment]
Laravel Framework version 5.1.39 (LTS)

**Comment by nolros** [comment]
@GrahamCampbell fails in version 5.2.37 but no problem in version 5.2.38. I've run all tests and tried all scenarios and pleased to report no problem. Thank you!

**Comment by GrahamCampbell** [comment]
Great. ;)

**Comment by GrahamCampbell** [comment]
But, if it's still broken on 5.1?

**Comment by tuproyecto** [comment]
Version 5.1.39 does not work

**Comment by taylorotwell** [comment]
I made the same change to 5.1 as to 5.2. If there is still a problem please someone make a PR. I am on vacation.

**Comment by tuproyecto** [comment]
Version 5.1.39 does not work

**Comment by taylorotwell** [comment]
Someone make a PR to fix please.

**Comment by mikerockett** [comment]
I think this was a recent change/update. Have been working on something for a client for months now, and only after a recent composer update did this issue starting showing... Any chance this is a dependency problem?

**Comment by tuproyecto** [comment]
They never think to fix this, I'm in version 5.1.39 or 5.1.40 does not work

**Comment by tuproyecto** [comment]
?

**Comment by GrahamCampbell** [comment]
@tuproyecto If you'd like to fix this in a PR, that would be appreciated.

**Comment by Dmurph24** [comment]
I'm having the same issues. For me, the session is expiring after 2 hours, but when I go back to login it uses the same session. However, it appears the session id is not regenerating after the session has timed out. To fix this or any similar issues you can do something like this before you perform your login authentication checks.
```php
$count = DB::table('sessions')->where('id', Session::getId())->count();
if ($count > 0) $request->session()->regenerate();
```
I haven't tested this yet but this seems to be the problem. Let me know if this helps anyone or its not wokring.

**Comment by theTrip73** [comment]
I'm trying to understand the problem since it is occurring like crazy on one of my sites but not the others. On that particular domain, we have implemented an SSO login, so the process looks like this:

1. attempt to access restricted area
2. redirect to SSO route on other domain
3. check for auth or require login
4. redirect back to restricted area at original domain

I can not reproduce the error myself, but my bug reporting system is throwing this error at me 20+ times a day. Since it doesn't happen regularly, it seems that it's potentially a browser issue, which got me thinking... Tell me if I'm being stupid here, but is this possible:

- Laravel sends the Redirect response in Step 1 and writes the session to the database.
- ??? browser handles redirect but ignores/misses/trashes session cookie because of redirect ???
- Because of missing session cookie Laravel tries to insert the session again when the user is returned to the site.

Is this plausible? I can dig into the framework code to see if this is possible, but I figured someone (Graham or Taylor) might know right away if this is even a feasible explanation/scenario.

**Comment by theTrip73** [comment]
The only other explanation I can fathom is that sometimes the loop back is too fast (which seems highly, highly unlikely) and starts a second request before the first one inserts, resulting in a duplicate session that has a false value for ```$this->exists```.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Session/DatabaseSessionHandler.php#L95

If ```$this->exists``` is not going to be reliable (for whatever reason), then the obvious fix is to query the database ahead of insert/update. I would be happy to fork and create a pull request for this, but maybe there's a better option... ?

**Comment by theTrip73** [comment]
Here's my last theory before I hang up and listen...

(My previously mentioned scenario in which the same session is saved twice is also unlikely since the first save event sets ```->exists``` to ```true``` which would trigger updates instead of inserts on future ```->write()``` calls.)

generateSessionId() should never generate a duplicate ID. This means that the "duplicate" entry is either (1) being read from the database before a ```->setExists(false)``` is called or (2) being spawned from the original on the same request. It basically eliminates my previous scenarios as possibilities.

Scenario 1 seems unlikely since ```->setExists(false)``` is only called during ```->migrate()``` which also calls ```->generateSessionId()``` which should prevent duplicate IDs. (https://github.com/laravel/framework/blob/5.1/src/Illuminate/Session/Store.php#L226)

That leaves the odd scenario where two session objects with the same ID are being saved for a single request. The catch is that the second object has to be a copy of the first because of ```->generateSessionId()```. This suggests that somewhere there's a "branch" in the code or a left-hand assignment that effectively creates a duplicate session.

This would be a valid explanation -- say if somehow ```SessionStart->terminate()``` were to be called twice -- except that is appears to happen "randomly".

That's about all I can offer since I still can't track down why it happens sometimes and not others. Hopefully some part of my digging and rambling will help someone else figure this out. If anyone else has ideas, I'm willing to look into them.

**Comment by rkgrep** [comment]
@theTrip73 I've told something like that [a long time ago](https://github.com/laravel/framework/issues/9251#issuecomment-111737561) but nobody paid attention )) I still think it may be the main reason

**Comment by theTrip73** [comment]
UPDATE: My errors appear to be coming exclusively from the following user-agent (info I just added to my error reports): "Rackspace Monitoring/1.1 (https://monitoring.api.rackspacecloud.com)". This explains why no human has complained to me about this.

I can't imagine what the Rackspace crawler is doing to cause this though, and I suppose it's still technically a bug... ?

**Comment by geoom** [comment]
I'm on 5.2.39 and I also have this issue, I had to migrate to cache server to get normal status of my app.

**Comment by geoom** [comment]
I'm on 5.2.39 and I also have this issue, I had to migrate to cache server to get normal status of my app.

**Comment by chrisvickers** [comment]
I am running 5.2.39 as well using reddis for cache and using database for sessions as i have 3 servers running production, all on forge, all using envoyer and i still ssee this issue now and again. I believe it is because of write delay on the database. This only happens when i start loading up the database to around 80% CPU capacity on amazon RDS.

**Comment by PLaRoche** [comment]
I see this and am just following this chain of comments.  I'm pretty novice when it comes to where to store session stuff, would it make sense to move it to redis instead of mysql?  (my stuff is similar to @chrisvickers but on aws and everything in a rds / mysql shared db)

**Comment by arjasco** [comment]
Just received this error in slack from one of my apps. If there is no PR in the pipeline, might have a look at this myself.

**Comment by wicochandra** [comment]
Hi All, I think we need to solved this problem or is there any suggestion where to store session?

I have an idea, but I don't know how to test if it works. How about if we use `openssl_random_pseudo_bytes(25)` instead of `Str::random(25)`

```
protected function generateSessionId()
{
    return sha1(uniqid('', true).openssl_random_pseudo_bytes(25).microtime(true));
}
```

**Comment by GrahamCampbell** [comment]
> I have an idea, but I don't know how to test if it works. How about if we use openssl_random_pseudo_bytes(25) instead of Str::random(25)

Really bad idea.

**Comment by jbellomy** [comment]
Taylor merged #12059 into 5.2 which would also help reduce the read/write race condition in the 5.1 database session handler.

**Comment by theTrip73** [comment]
PROPOSAL: A try-catch for the DatabaseSessionHandler::write() method's insert attempt to watch for PDOExceptions and check PDO::errorCode() for SQLSTATE 23505 (Unique violation: 7).

If 23505, read + update. If not 23505, re-throw.

It's an extremely targeted strike, but it should narrow the race condition to the smallest possible timeframe while also avoiding an overly general approach that could cause problems elsewhere.

**Comment by dzafel** [comment]
Hi guys, I’m still having this issue on 5.2.45, I don’t use any custom session providers/services, I use the default ones with DB. I tried to temporarily change the `generateSessionId()` method as suggested above, and as it is in 5.3:
```php
protected function generateSessionId()
{
    return Str::random(40);
}
```
but this does not help. Unfortunatelly I still do not know what is the reason. Anyone has any solution yet?

**Comment by suncoastkid** [comment]
I've been seeing this on a 5.1.6 app for a long time. Any updates on a fix?

**Comment by drawmyattention** [comment]
I'm using separate read and write hosts on the db connection used to handle sessions, so it's entirely possible that the read server hasn't been updated with the session data written to the write server. I've never encountered replication lag (using RDS) but to eliminate this as a potential cause, I've created a new connection which has a single read/write host.

If I get no further duplicate errors in the next week or so, I'll be happy to say this is related to some sort of race condition caused by read/write replication.

**Comment by drawmyattention** [comment]
Unfortunately I'm still seeing this error, so I can rule out that having separate read/write connections is not the cause of this bug.

**Comment by ryzr** [comment]
Issue is still present in Laravel v5.3.26.

Currently, we have anywhere between 3 and 40 instances serving our app, with a single read/write MariaDB database.  Our sessions table typically contains 15k+ sessions at a time, expiring in 2 hour intervals.

`Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'fLOk3VaO0TxW1vFxrXX6q3hcGg8DmGKGpb7QsIUZ' for key 'sessions_id_unique'`

```
Stack trace:
#0 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(725): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#1 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(480): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#2 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->statement('insert into `se...', Array)
#3 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2136): Illuminate\Database\Connection->insert('insert into `se...', Array)
#4 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(119): Illuminate\Database\Query\Builder->insert(Array)
#5 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Session/Store.php(263): Illuminate\Session\DatabaseSessionHandler->write('fLOk3VaO0TxW1vF...', 'a:4:{s:6:"_toke...')
#6 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#7 /app/xxx/current/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(177): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 /app/xxx/current/src/public/index.php(62): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#9 {main}
```

**Comment by adam-boduch** [comment]
I also have this this issue in Laravel 5.2.X/Laravel 5.3.X on PostgreSQL. I am gonna have to change session driver from database to redis :(

**Comment by calebfavor** [comment]
I am having this issue as well. It seems to be more prevalent when a page makes multiple ajax requests.

**Comment by aydot** [comment]
I can also confirm the issue in Laravel v5.3.26.

**Comment by taylorotwell** [comment]
There is absolutely no point in **anyone else** saying "I have this issue". It is very apparent people have had the issue. What is more helpful is someone working to **fix** the issue.

**Comment by trip-somers** [comment]
Here's another proposal since my earlier one didn't seem to gain any traction...

Instantly create/update the database record when a new session ID is generated, then proceed as normal. The idea would be to make sure there's a record (creating if necessary) when loading the session ('before' middleware) rather than waiting until storing it ('after' middleware).

[[NOTE: My previous proposal worked well for me, so I haven't spent any more time on this. Forgive me if I've spaced out or spoken incorrectly on the 'before' and 'after' parts of the session middleware.]]

**Comment by taylorotwell** [comment]
@trip-somers thanks for both suggestions. Have we actually nailed down *why* this is happening?

**Comment by taylorotwell** [comment]
Fixed on Laravel 5.4.

**Comment by calebfavor** [comment]
@taylorotwell - Any chance you could point me to where this was patched? I am hoping to put together a fix for 4.2 as well.

**Comment by roshangautam** [comment]
Can someone please tag a release in 5.1 for this fix ?

**Comment by mediaceh** [comment]
I have same error in version 5.3.23. 

`[2017-02-06 11:37:18] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'XlZRvW1oqTObXyH3oI5HQi9r8HubHOoIt2eA0sJS' for key 'sessions_id_unique'' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(479): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(762): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `se...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(725): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(480): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->statement('insert into `se...', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2136): Illuminate\Database\Connection->insert('insert into `se...', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(119): Illuminate\Database\Query\Builder->insert(Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Store.php(263): Illuminate\Session\DatabaseSessionHandler->write('XlZRvW1oqTObXyH...', 'a:4:{s:6:"_toke...')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#11 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#12 {main}`

**Comment by roshangautam** [comment]
How wonderful, this is not patched in [5.2](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Session/DatabaseSessionHandler.php) branch too.

**Comment by carltondickson** [comment]
This fix isn't in release v5.1.45 but is in [5.1 branch](https://github.com/laravel/framework/tree/5.1).

How often are new tags/releases created for the LTS releases?

**Comment by Priet** [comment]
This fix isn't included in the v5.1.46 release.

Is it possible to release a new 5.1 version with the fix included so we can update our composer projects?

**Comment by cupit** [comment]
Hello, I'm using v5.2.45 and I noticed many problems with this, usually when the website has rush hours.. any idea how to fix it in v5.2.45?

**Comment by markwinters** [comment]
We received the integrity constraint violation on the session table yesterday. But noticed in a request that happend 38 seconds later that another error occurd stating -> General error: 1205 Lock wait timeout exceeded. This happend on the garbage collection on the session table. 

When looking into this I wonder, how can the fix work? It seems to update when the insert fails. But the database already received an invalid insert in the first place. I believe this fix to be a workarround on the real issue that is not solved. It should not try to insert in the first place. 

I would like to propose a solution (that was already mentioned before) to do a count request or something like that to properly check if the session already exists in the database.

**Comment by art-vanesyan** [comment]
Laravel 9
Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'LgM92Cl35ZxNS3b6EACA3itfgmAn77BaO91HadLf' for key 'PRIMARY'. Transaction has been restarted. Attempt 7/10. SQL: insert into `sessions` (`payload`, `last_activity`, `user_id`, `ip_address`, `user_agent`, `id`) values ('YToyOntzOjY6Il90b2tlbiI7czo0MDoib0M2MTVrZ2xtdjJ6WkRvelFWZGExdW9BQVkxVHc5Zk5QSXRReklGbiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', '1669315180', '923363', '91.211.136.202', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', 'LgM92Cl35ZxNS3b6EACA3itfgmAn77BaO91HadLf')
