### ISSUE TITLE
lists() inconsistency in Query Builder vs. Eloquent/Collection

### ISSUE THREAD

**Issue by orrd** [laravel/framework#9269]
Starting with Laravel 5.1, the `lists()` method of `Eloquent` and the `lists()` method of `Collection` both now return a `Collection` instead of a plain array.  But Query Builder's `lists()` method still returns an array.  So now we have this situation:

	User::where('status', 'ok')->lists('id'); // returns a Collection
	User::where('status', 'ok')->get()->lists('id'); // returns a Collection
	DB::table('users')->where('status', 'ok')->lists('id'); // returns an array

This feels inconsistent and confusing.  Is there a reason why Query Builder can't also return a `Collection`?  From looking at the code, it starts with a `Collection`, and then calls `all()` to convert it to an array before returning.  Should I create a pull request to remove that call to `all()`?  (But we would probably need to wait for 5.2 to release it since it would cause some existing code to break.)

**Comment by Sladewill** [comment]
What version are you on because I'm pretty sure that was fixed the other day. 5.1 - which minor version.

**Comment by rkgrep** [comment]
It seems that simple query builder never returns collections. There is a reason in such behavior as operations with arrays are almost 3 times faster than with collections - and you don't get any complex structures from queries.
But using collection [here](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L1515) instead of `array_pluck` is confusing

**Comment by mikerogne** [comment]
Why was this closed without saying anything? Was this issue fixed elsewhere?

**Comment by janhartigan** [comment]
@GrahamCampbell if this has already been discussed before, could you at least point to other discussion on the topic instead of just closing this one? I don't see how this issue merits a drive-by close without a comment.

**Comment by orrd** [comment]
It would be preferable if GrahamCampbell at least gave a brief reason when closing issues.  Not that we don't greatly appreciate his excellent work maintaining Laravel and I'm sure he's busy, but I've seen the same thing happen where a number of people are describing running into the same difficult issue, and then it just gets closed with no explanation. 

In response to rkgrep, I'm not sure that explanation because otherwise they wouldn't have changed `Eloquent`'s `lists()` to return a Collection.  Also Query Builder's `lists()` already creates a Collection anyway, but then calls `all()` to convert it to an array before returning.  So speed-wise it would make more sense if it just returned the Collection, and let us call `all()` if we want an array (as we now do with Eloquent's `lists()`.

**Comment by mikerogne** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Honestly, I can't remember the exact reason I closed this now, though there must have been one. Maybe have a look through the PRs, both merged and closed.

**Comment by orrd** [comment]
I did a quick search for 'lists' in open/closed PRs and didn't see anything related to this.  

In general, it would be really nice if a brief reason was given whenever an issue is closed.  For example, if a PR was merged, that should be linked to the issue so that people experiencing the problem and finding the issue closed will know that a fix is coming in an upcoming version.

**Comment by GrahamCampbell** [comment]
Unfortunately people are bad at naming PRs.

> In general, it would be really nice if a brief reason was given whenever an issue is closed

I agree. Sorry.

**Comment by mikerogne** [comment]
:+1: thank you for acknowledging the problem, GC.

So.... Taylor on twitter was inconclusive, but in general it seems like this change will not happen.... as in, lists() from query builder will stay as an array. Plus having already launched and being a LTS version, I don't see this likely changing. But maybe I'm wrong! At any rate... I'll be interested to see if anything changes. Thanks all for the help.

**Comment by GrahamCampbell** [comment]
I think the issue was BC on the PR that was proposed.

**Comment by Flynsarmy** [comment]
Could the issue at least be reopened until we know what the reason for closing was? It's clearly still an issue until any PR is accepted and merged - so why not wait until we have a reason to close before doing so?

**Comment by InstanceOfMichael** [comment]
Why was this change made at all?

 * rename ``pluck`` to ``lists``
 * keep ``pluck``'s new behavior instead of ``lists`` original behavior when pretending to make a "backwards compatible" copy of pluck
 * above changes apply to Collection and Eloquent\Builder, but not to DB Builder

Seems like you could have simply added ``pluck`` to collection and no one would have ever had problems.

Then you get this rude comment in https://github.com/laravel/framework/pull/8528

> how hard is it to run a search-and-replace to ->lists()->all()?

How exactly would you do an automated search and replace on this? Nobody has ``->lists()->all()`` in their code, they have ``->lists('attr1','attr2')`` and carrying the parameters inside of ``lists`` when adding all is not a well-known regex, let alone IDE support.

**Comment by shssoichiro** [comment]
I found this by searching the issues for `lists` after having an issue with this inconsistency as well (and figured I would comment rather than opening a new issue). In #9001 @taylorotwell says:

> No. Eloquent returns collections. Query bolder returns arrays.

However I'd like to know if there is a good reason for this, considering chaining methods onto an Eloquent model can change whether running `lists` on it returns an array or a collection. Most real-world queries run from an Eloquent model will return a query builder instance, which returns an array from its `lists` method. However, `Model::lists()` and `$model->attached->lists()` both return a `Collection`. It can become very easy to lose track of where to append `toArray()` and where not to.

**Comment by taylorotwell** [comment]
This is under discussion for 5.2.

**Comment by taylorotwell** [comment]
There is an open PR on laravel/framework for it here: https://github.com/laravel/framework/pull/10552

**Comment by mikerogne** [comment]
Cheers!

**Comment by myregistration** [comment]
Is there any reason we shouldn't use ->toArray() instead of ->all() on the lists() collection?  I'd prefer to use toArray since seems more intuitive and consistent.

**Comment by janhartigan** [comment]
@myregistration for a list of simple values, [`->all()`](https://github.com/laravel/framework/blob/8444190a742d7d77818f3938b214a95a4585ea35/src/Illuminate/Support/Collection.php#L49-L57) and [`->toArray()`](https://github.com/laravel/framework/blob/8444190a742d7d77818f3938b214a95a4585ea35/src/Illuminate/Support/Collection.php#L1015-L1025) have the same behavior. When you say `->lists()`, you're getting an array of integers. Since each integer doesn't implement the `Arrayable` interface, you'll just get an array of integers in either case.
