### ISSUE TITLE
Logging levels discrepancy

### ISSUE THREAD

**Issue by gregrobson** [laravel/framework#9518]
Reading from the docs http://laravel.com/docs/5.1/errors#logging

> The logger provides the **seven** logging levels defined in RFC 5424: debug, info, notice, warning, error, critical, and alert.

In [RFC 5424](http://tools.ietf.org/html/rfc5424), **eight** levels are defined.

```
              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages
```

Was this intentional? I personally consider *emergency* as required as Laravel might be used for monitoring other services (databases, other APIs etc)

**Comment by ArjanSchouten** [comment]
As you can see in the [log writer](https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/Log/Writer.php) there are eight levels defined.

There was a pull request for it: https://github.com/laravel/docs/pull/562/files
And in this pull request there where 7: https://github.com/laravel/docs/pull/328/files

Probably that's the issue. So don't think this was intentional.
