### ISSUE TITLE
Route group's domain parameter is unneeded in controller

### ISSUE THREAD

**Issue by hkan** [laravel/framework#9592]
The route is as follows:

```php
Route::group(['domain' => '{domain}.{tld}'], function ($route)
{
    $route->get('{something}', 'SomeController@someMethod');
}
```

At this point, my `someMethod` in `SomeController` has to be like this:

```php
...
class SomeController extends BaseController {
    public function someMethod($domain, $tld, $someParameter)
    {
        ...
    }
}
...
```

The problem is, I don't need to have `domain` parameter in every single controller method. It begins to look bad after a bunch of methods in a few controller. I already check it at somepoint before a controller method gets executed. 

Wouldn't it be better if we could have the power of deciding which route parameters to be sent to controllers? Or do you have a better way of doing what I'm trying to do here?

**Comment by ArjanSchouten** [comment]
Think this is more a question for a forum. Haven't tested it but I came up with this:

In you're basecontroller you can add the call magic method. In this method you can grab the method name => subtract a prefix => call the method without the prefix and send 2 instead of 3 parameters.

You're keeping you're controllers clean and you only have to add this once in you're application. Probably only a few people are going to use something like this. Therefore, in my opinion, it isn't something for the core of Laravel. Just hack around with this if you wan't :+1:

**Comment by ArjanSchouten** [comment]
If that won't work due to reflection you can try to use the ```missingMethod()```

**Comment by kjdion84** [comment]
> Probably only a few people are going to use something like this.

Only every single SAAS app ever.

**Comment by Joemires** [comment]
I came up with a solution for this
Add the following code to your Controller class, replace domain with your domain parameter
`/**
     * Execute an action on the controller.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function callAction($method, $parameters)
    {
        if(Arr::exists($parameters, 'domain')) Arr::forget($parameters, 'domain');

        return $this->{$method}(...array_values($parameters));
    }
    `
