### ISSUE TITLE
trans() / has() Should return null / false if the lang will be returning an array.

### ISSUE THREAD

**Issue by RyanThompson** [laravel/framework#9803]
If an exact string match is not found then trans should return null and has() should return false.

Otherwise the innards will through array to string exceptions. has('message') is true even though trans('message') will throw the exception described.

**Comment by brunogaspar** [comment]
:-1:

If you ever need to do something like `$lines = trans('foo');` on a controller or whatever and in case it returns an array, with your proposal we can no longer do it or rely on, as it would always return `null`, which isn't the expected behavior IMO.

You are responsible to use the proper language key name like `trans('foo.bar')` for example in order to avoid those exceptions that are thrown, most of the times on views.

You can always create your own helpers that fits your own needs i guess.

**Comment by RyanThompson** [comment]
Hmm.. touché - never thought about that use case / never done that surprisingly.
