### ISSUE TITLE
[Proposal] To add validation rule for Credit Cards

### ISSUE THREAD

**Issue by prady00** [laravel/framework#9844]
This feature will be used by developers as below :

    $validator = Validator::make(
        array('creditcard' => array('creditcard'))
    );

It can be implemented by adding a function in Illuminate/Validation/Validator.php

    validateCreditcard($attribute, $value){
        //
    }

I would like to work on it, @taylorotwell just need your consent :)

**Comment by shehi** [comment]
+1 for this.

**Comment by TheShiftExchange** [comment]
No - this is a terrible idea.

1. In almost every instance - you should never be receiving the credit card on your server. It should be directly sent to your credit card provider, like Stripe. If you have the credit card number hitting your server - you are doing it wrong.

2. In the small cases where you are PCI complaint and doing the processing yourself - then regardless if the card number "appears" valid or not according to a regex check - that is irrevelant because the only true test is to try and charge the charge.

If your organisation is smart enough to be doing PCI complaint processing yourself - then you have the ability to write a custom validation yourself.

Putting a credit card validation into the framework will lead to misconfigurations of credit card processing by developers.

**Comment by prady00** [comment]
@GrahamCampbell , May I know your thoughts on this?

**Comment by TheShiftExchange** [comment]
@prady00 - I already gave you two very good reasons already...
