### ISSUE TITLE
[5.1.9] mcrypt_decrypt(): Received initialization vector of size 32, but size 16 is required for this encryption mode

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#9852]
After deploying an application Laravel 5.1.9, I'm seeing the following error showing up in Sentry. 

```
exception 'ErrorException' with message 'mcrypt_decrypt(): Received initialization vector of size 32, but size 16 is required for this encryption mode' in /home/forge/default/releases/20150806062346/vendor/laravel/framework/src/Illuminate/Encryption/McryptEncrypter.php:127
```

It doesn't appear to affect all users, I've yet to work out what determines whether a user will be affected or not, but all pages are broken for these users.

I thought this had something to do with the cipher, noticing the default Laravel cipher changed from `MCRYPT_RIJNDAEL_128` to `AES-256-CBC`. 

However upon looking deeper through our diffs I noticed the issue only showed up once we upgraded from 5.1.8 to 5.1.9. Once I locked in the `laravel/framework` dependency to 5.1.8 we are no longer seeing the issue.

I'm not that familiar with how this encryption works or what else could be causing this issue (is it cookies, or sessions?) so I'm not sure what to look for when looking at the changes from 5.1.8 to 5.1.9.

This application was only just upgraded from Laravel 5.0 to Laravel 5.1 and the session store is a Redis cluster, I'm not sure if that makes any difference.

**Comment by jbrooksuk** [comment]
If you change `cipher` you'll need to run `php artisan key:generate` again.

**Comment by dwightwatson** [comment]
I didn't change the cipher, I left my project on MCRYPT_RIJNDAEL_128.

**Comment by jbrooksuk** [comment]
Try changing the cipher to `AES-256-CBC` and then run key generate. It's what I've done in the past. Sessions will be expired though.

**Comment by dwightwatson** [comment]
Not sure why this has only become an issue in 5.1.9 though. I'd like to avoid expiring all sessions as I have ~600 signed in active users.

**Comment by GrahamCampbell** [comment]
We haven't changed the encrypted component at all since 5.1.8.

**Comment by dwightwatson** [comment]
Just a postmortem for anyone who runs into a similar issue - I'm still not sure why this issue only appeared in 5.1.9, however the cookie causing the problem turned out to be the one created from [Sentry](https://github.com/cartalyst/sentry) which this project used up until last year. Sentry's cookie lifespan was until 2020 and seemingly used an encryption that was not compatible with the new version of Laravel. Adding the name of the Sentry cookie to the `$except` array of the `EncryptCookies` middleware solved the issue.

**Comment by orrd** [comment]
Did you recently also upgrade to PHP 5.6?  As of 5.6.0, mcrypt_encrypt() no longer silently accepts shorter keys.  See http://php.net/manual/en/function.mcrypt-encrypt.php.  

Some of us have 16 byte 'key' values set in our config/app.php.  I'm not sure why that is, but it may be that older versions of Laravel generated a 16 byte key instead of 32.  That didn't used to be a problem since mcrypt_encrypt() used to silently pad it with 16 '\0' bytes, but it is once you upgrade to PHP 5.6, that no longer happens.  

So what is the best solution at this point?  I don't know what the ramifications are of changing the 'key' in config/app.php.  Would it just break session cookies, or would other things also break?  

McryptEncrypter.php could pad 16 byte keys with 16 '\0' bytes so that installs that use PHP 5.6 would behave just as older versions did.  Is that the best solution, or is there a better way for Laravel to handle this?

**Comment by orrd** [comment]
(I recommend re-opening this issue since this is probably something that Laravel should be modified to handle better in my opinion.)

Did you recently also upgrade to PHP 5.6?  As of 5.6.0, mcrypt_encrypt() no longer silently accepts invalid key lengths.  See http://php.net/manual/en/function.mcrypt-encrypt.php.  

Some of us have 32 byte 'key' values set in our config/app.php with MCRYPT_RIJNDAEL_128 as the 'cipher' value, but MCRYPT_RIJNDAEL_128 only needs a 16 byte key.  That didn't used to be a problem since mcrypt_encrypt() used to silently ignore the extra 16 bytes, but it is once you upgrade to PHP 5.6, that no longer happens.  

So what is the best solution at this point?  I don't know what the ramifications are of changing the 'cipher' in config/app.php on a live site.  Would it just break session cookies, or would other things also break?  

McryptEncrypter.php should probably detect 32 byte keys when used with MCRYPT_RIJNDAEL_128 and automatically discard the extra 16 bytes so that installs that use PHP 5.6 would behave just as older versions did.  Is that the best solution, or is there a better way for Laravel to handle this?
